// Server-only editorial bank: Baseball (tranche 1). Never import this module from client components.
// Every fact below was checked against the cited sourceUrl at authoring time; Wikipedia is never a source.
export const BASEBALL = Object.freeze([
  // ---------------------------------------------------------------- simple
  {
    id: 'bb001',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Black Sox 1919',
    difficulty: 'simple',
    question: 'Which team beat the "Black Sox" Chicago White Sox in the fixed 1919 World Series?',
    options: ['Cincinnati Reds', 'New York Giants', 'Brooklyn Robins', 'Cleveland Indians'],
    correctIndex: 0,
    explanation: 'Cincinnati won the best-of-nine Series five games to three.',
    sourceUrl: 'https://www.baseball-reference.com/postseason/1919_WS.shtml',
    sourceLabel: 'Baseball-Reference: 1919 World Series',
  },
  {
    id: 'bb002',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Black Sox 1919',
    difficulty: 'simple',
    question: 'How many White Sox players did Commissioner Landis ban for life over the 1919 fix?',
    options: ['Six', 'Eight', 'Ten', 'Twelve'],
    correctIndex: 1,
    explanation: 'Landis, a former federal judge, banned the eight in 1921 despite their acquittal in court.',
    sourceUrl: 'https://baseballhall.org/hall-of-famers/landis-kenesaw',
    sourceLabel: 'Baseball Hall of Fame: Kenesaw Landis',
  },
  {
    id: 'bb003',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Steroid era',
    difficulty: 'simple',
    question: 'Who hit 70 home runs for the Cardinals in the 1998 race with Sammy Sosa?',
    options: ['Ken Griffey Jr.', 'Albert Belle', 'Mark McGwire', 'Barry Bonds'],
    correctIndex: 2,
    explanation: 'McGwire finished with 70 and Sosa with 66; both later became Hall of Fame lightning rods.',
    sourceUrl: 'https://www.baseball-reference.com/players/m/mcgwima01.shtml',
    sourceLabel: 'Baseball-Reference: Mark McGwire',
  },
  {
    id: 'bb004',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Steroid era',
    difficulty: 'simple',
    question: 'How many home runs did Barry Bonds hit in 2001 to set the single-season record?',
    options: ['70', '71', '75', '73'],
    correctIndex: 3,
    explanation: 'Bonds also finished with 762 career home runs, the most ever.',
    sourceUrl: 'https://www.baseball-reference.com/players/b/bondsba01.shtml',
    sourceLabel: 'Baseball-Reference: Barry Bonds',
  },
  {
    id: 'bb005',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Pete Rose',
    difficulty: 'simple',
    question: 'Pete Rose holds the all-time MLB record in which category?',
    options: ['Hits', 'Stolen bases', 'Home runs', 'Runs batted in'],
    correctIndex: 0,
    explanation: 'Rose finished with 4,256 hits, still the most in major league history.',
    sourceUrl: 'https://www.baseball-reference.com/players/r/rosepe01.shtml',
    sourceLabel: 'Baseball-Reference: Pete Rose',
  },
  {
    id: 'bb006',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Curse of the Bambino',
    difficulty: 'simple',
    question: 'Which club sold Babe Ruth to the Yankees for $100,000 after the 1919 season?',
    options: ['Philadelphia Athletics', 'Boston Red Sox', 'Baltimore Orioles', 'Chicago White Sox'],
    correctIndex: 1,
    explanation: 'Owner Harry Frazee made the sale; Boston then went 86 years without a title.',
    sourceUrl: 'https://baseballhall.org/hall-of-famers/ruth-babe',
    sourceLabel: 'Baseball Hall of Fame: Babe Ruth',
  },
  {
    id: 'bb007',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Curse of the Bambino',
    difficulty: 'simple',
    question: 'Whom did the Red Sox sweep to end the "curse" in the 2004 World Series?',
    options: ['Houston Astros', 'Atlanta Braves', 'St. Louis Cardinals', 'Los Angeles Dodgers'],
    correctIndex: 2,
    explanation: 'Boston swept St. Louis 4-0, with Manny Ramirez named Series MVP.',
    sourceUrl: 'https://www.baseball-reference.com/postseason/2004_WS.shtml',
    sourceLabel: 'Baseball-Reference: 2004 World Series',
  },
  {
    id: 'bb008',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Cubs 2016',
    difficulty: 'simple',
    question: 'Which team did the Cubs beat in seven games to win the 2016 World Series?',
    options: ['Kansas City Royals', 'Boston Red Sox', 'Toronto Blue Jays', 'Cleveland Indians'],
    correctIndex: 3,
    explanation: 'Game 7 in Cleveland went ten innings and finished 8-7 to the Cubs.',
    sourceUrl: 'https://www.baseball-reference.com/postseason/2016_WS.shtml',
    sourceLabel: 'Baseball-Reference: 2016 World Series',
  },
  {
    id: 'bb009',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Astros sign-stealing',
    difficulty: 'simple',
    question: 'What did the 2017 Astros bang to tell hitters an off-speed pitch was coming?',
    options: ['A trash can', 'A dugout railing', 'A bat rack', 'A water cooler'],
    correctIndex: 0,
    explanation: 'The Commissioner’s report found players banged a trash can with a bat, and occasionally a massage gun.',
    sourceUrl: 'https://img.mlbstatic.com/mlb-images/image/upload/mlb/cglrhmlrwwbkacty27l7.pdf',
    sourceLabel: 'MLB: Statement of the Commissioner on the Astros investigation',
  },
  {
    id: 'bb010',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Jackie Robinson',
    difficulty: 'simple',
    question: 'For which club did Jackie Robinson break the colour line on April 15, 1947?',
    options: ['New York Giants', 'Brooklyn Dodgers', 'Cleveland Indians', 'Boston Braves'],
    correctIndex: 1,
    explanation: 'Branch Rickey signed him; Robinson won the inaugural Rookie of the Year award that season.',
    sourceUrl: 'https://baseballhall.org/hall-of-famers/robinson-jackie',
    sourceLabel: 'Baseball Hall of Fame: Jackie Robinson',
  },
  {
    id: 'bb011',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Jackie Robinson',
    difficulty: 'simple',
    question: 'Which uniform number was retired across all of MLB in Jackie Robinson’s honour in 1997?',
    options: ['24', '32', '42', '44'],
    correctIndex: 2,
    explanation: 'The league-wide retirement came on April 15, 1997, fifty years after his debut.',
    sourceUrl: 'https://baseballhall.org/hall-of-famers/robinson-jackie',
    sourceLabel: 'Baseball Hall of Fame: Jackie Robinson',
  },
  {
    id: 'bb012',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Negro Leagues',
    difficulty: 'simple',
    question: 'Who founded the Negro National League in 1920 and is called the "father of Black baseball"?',
    options: ['Josh Gibson', 'Buck O’Neil', 'Satchel Paige', 'Rube Foster'],
    correctIndex: 3,
    explanation: 'Foster owned and managed the Chicago American Giants and served as the league’s president.',
    sourceUrl: 'https://baseballhall.org/hall-of-famers/foster-rube',
    sourceLabel: 'Baseball Hall of Fame: Rube Foster',
  },
  {
    id: 'bb013',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Perfect games',
    difficulty: 'simple',
    question: 'Who threw the only perfect game in World Series history, for the 1956 Yankees?',
    options: ['Don Larsen', 'Whitey Ford', 'Sandy Koufax', 'Bob Turley'],
    correctIndex: 0,
    explanation: 'Larsen beat Brooklyn 2-0 in Game 5 and was named Series MVP.',
    sourceUrl: 'https://www.baseball-reference.com/postseason/1956_WS.shtml',
    sourceLabel: 'Baseball-Reference: 1956 World Series',
  },
  {
    id: 'bb014',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'The 1994 strike',
    difficulty: 'simple',
    question: 'The 1994 players’ strike forced the cancellation of which event for the first time since 1904?',
    options: ['The All-Star Game', 'The World Series', 'The amateur draft', 'Opening Day'],
    correctIndex: 1,
    explanation: 'Acting commissioner Bud Selig presided over the first lost World Series in 90 years.',
    sourceUrl: 'https://baseballhall.org/hall-of-famers/selig-bud',
    sourceLabel: 'Baseball Hall of Fame: Bud Selig',
  },
  {
    id: 'bb015',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Home run records',
    difficulty: 'simple',
    question: 'Who passed Babe Ruth’s 714 career home runs on April 8, 1974?',
    options: ['Willie Mays', 'Frank Robinson', 'Hank Aaron', 'Harmon Killebrew'],
    correctIndex: 2,
    explanation: 'Aaron finished with 755 and still holds the career RBI record with 2,297.',
    sourceUrl: 'https://baseballhall.org/hall-of-famers/aaron-hank',
    sourceLabel: 'Baseball Hall of Fame: Hank Aaron',
  },
  {
    id: 'bb016',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Home run records',
    difficulty: 'simple',
    question: 'Which Yankee broke Babe Ruth’s single-season record with his 61st home run in 1961?',
    options: ['Mickey Mantle', 'Yogi Berra', 'Moose Skowron', 'Roger Maris'],
    correctIndex: 3,
    explanation: 'Maris hit No. 61 off Boston’s Tracy Stallard on the season’s final day, October 1.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/NYA/NYA196110010.shtml',
    sourceLabel: 'Baseball-Reference: Red Sox at Yankees, October 1, 1961',
  },
  {
    id: 'bb017',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Shohei Ohtani',
    difficulty: 'simple',
    question: 'In which season did Shohei Ohtani post his 54-homer, 59-steal "50-50" campaign?',
    options: ['2024', '2021', '2023', '2022'],
    correctIndex: 0,
    explanation: 'It was his first Dodgers season and brought a third unanimous MVP award.',
    sourceUrl: 'https://www.baseball-reference.com/players/o/ohtansh01.shtml',
    sourceLabel: 'Baseball-Reference: Shohei Ohtani',
  },
  {
    id: 'bb018',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Shohei Ohtani',
    difficulty: 'simple',
    question: 'Which MLB club did Shohei Ohtani play for from 2018 until joining the Dodgers?',
    options: ['Seattle Mariners', 'Los Angeles Angels', 'San Diego Padres', 'Texas Rangers'],
    correctIndex: 1,
    explanation: 'Ohtani won the 2018 AL Rookie of the Year and two AL MVPs with the Angels.',
    sourceUrl: 'https://www.baseball-reference.com/players/o/ohtansh01.shtml',
    sourceLabel: 'Baseball-Reference: Shohei Ohtani',
  },
  {
    id: 'bb019',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Buckner 1986',
    difficulty: 'simple',
    question: 'Which team benefited from Bill Buckner’s error and went on to win the 1986 World Series?',
    options: ['Houston Astros', 'California Angels', 'New York Mets', 'Philadelphia Phillies'],
    correctIndex: 2,
    explanation: 'The Mets won Game 6 in ten innings and then took Game 7; Ray Knight was Series MVP.',
    sourceUrl: 'https://www.baseball-reference.com/postseason/1986_WS.shtml',
    sourceLabel: 'Baseball-Reference: 1986 World Series',
  },
  {
    id: 'bb020',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Shot Heard Round the World',
    difficulty: 'simple',
    question: 'Bobby Thomson’s 1951 "Shot Heard Round the World" won the pennant for which club?',
    options: ['Brooklyn Dodgers', 'Boston Braves', 'New York Yankees', 'New York Giants'],
    correctIndex: 3,
    explanation: 'Russ Hodges’ call, "The Giants win the pennant!", capped a playoff against Brooklyn.',
    sourceUrl: 'https://sabr.org/bioproj/person/bobby-thomson/',
    sourceLabel: 'SABR: Bobby Thomson biography',
  },
  // ---------------------------------------------------------------- expert
  {
    id: 'bb021',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Black Sox 1919',
    difficulty: 'expert',
    question: 'The fixed 1919 World Series was played under which unusual format?',
    options: ['Best-of-nine', 'Best-of-five', 'Best-of-seven', 'Best-of-eleven'],
    correctIndex: 0,
    explanation: 'Cincinnati clinched in Game 8; Joe Jackson hit the Series’ only home run in that game.',
    sourceUrl: 'https://sabr.org/bioproj/person/shoeless-joe-jackson/',
    sourceLabel: 'SABR: Shoeless Joe Jackson biography',
  },
  {
    id: 'bb022',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Black Sox 1919',
    difficulty: 'expert',
    question: 'Which White Sox ace hit Reds leadoff man Morrie Rath to signal the gamblers that the fix was on?',
    options: ['Lefty Williams', 'Eddie Cicotte', 'Red Faber', 'Dickey Kerr'],
    correctIndex: 1,
    explanation: 'Cicotte had won 29 games in 1919 and later confessed to the grand jury.',
    sourceUrl: 'https://sabr.org/bioproj/person/eddie-cicotte/',
    sourceLabel: 'SABR: Eddie Cicotte biography',
  },
  {
    id: 'bb023',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Shot Heard Round the World',
    difficulty: 'expert',
    question: 'Which Dodgers reliever threw the pitch Bobby Thomson hit for the 1951 pennant?',
    options: ['Don Newcombe', 'Preacher Roe', 'Ralph Branca', 'Carl Erskine'],
    correctIndex: 2,
    explanation: 'Branca had relieved Don Newcombe with one out in the ninth; Thomson hit his second pitch.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/NY1/NY1195110030.shtml',
    sourceLabel: 'Baseball-Reference: Dodgers at Giants, October 3, 1951',
  },
  {
    id: 'bb024',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Steroid era',
    difficulty: 'expert',
    question: 'Off which Cubs pitcher did Mark McGwire hit his record-breaking 62nd home run on September 8, 1998?',
    options: ['Kerry Wood', 'Kevin Tapani', 'Rod Beck', 'Steve Trachsel'],
    correctIndex: 3,
    explanation: 'The line drive down the left-field line came in the fourth inning at Busch Stadium.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/SLN/SLN199809080.shtml',
    sourceLabel: 'Baseball-Reference: Cubs at Cardinals, September 8, 1998',
  },
  {
    id: 'bb025',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Steroid era',
    difficulty: 'expert',
    question: 'Which former US Senator authored the December 2007 report into steroid use in baseball?',
    options: ['George Mitchell', 'Bill Bradley', 'Jim Bunning', 'Tom Harkin'],
    correctIndex: 0,
    explanation: 'The Mitchell Report, dated December 13, 2007, ran to more than 400 pages.',
    sourceUrl: 'https://www.mlbstatic.com/mlb.com/pdfs/mitchell-report/full.pdf',
    sourceLabel: 'MLB: The Mitchell Report',
  },
  {
    id: 'bb026',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Steroid era',
    difficulty: 'expert',
    question: 'Who was the only player elected in the 2022 BBWAA vote, the year Bonds and Clemens fell off the ballot?',
    options: ['Scott Rolen', 'David Ortiz', 'Todd Helton', 'Alex Rodriguez'],
    correctIndex: 1,
    explanation: 'Ortiz got 77.9 percent; Bonds (66.0) and Clemens (65.2) were in their tenth and final year.',
    sourceUrl: 'https://bbwaa.com/22-hof/',
    sourceLabel: 'BBWAA: 2022 Hall of Fame election results',
  },
  {
    id: 'bb027',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Pete Rose',
    difficulty: 'expert',
    question: 'Which commissioner reached the 1989 settlement that placed Pete Rose on the permanently ineligible list?',
    options: ['Fay Vincent', 'Peter Ueberroth', 'Bart Giamatti', 'Bowie Kuhn'],
    correctIndex: 2,
    explanation: 'Giamatti had hired John Dowd, whose report documented Rose’s betting on games.',
    sourceUrl: 'https://sabr.org/bioproj/person/pete-rose/',
    sourceLabel: 'SABR: Pete Rose biography',
  },
  {
    id: 'bb028',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Pete Rose',
    difficulty: 'expert',
    question: 'Off which Padres pitcher did Pete Rose single for hit 4,192 to pass Ty Cobb on September 11, 1985?',
    options: ['Andy Hawkins', 'LaMarr Hoyt', 'Goose Gossage', 'Eric Show'],
    correctIndex: 3,
    explanation: 'Rose, then Cincinnati’s player-manager, lined the first-inning single to left at Riverfront.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/CIN/CIN198509110.shtml',
    sourceLabel: 'Baseball-Reference: Padres at Reds, September 11, 1985',
  },
  {
    id: 'bb029',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Curse of the Bambino',
    difficulty: 'expert',
    question: 'Which Red Sox starter gave up Bucky Dent’s three-run homer in the 1978 one-game playoff?',
    options: ['Mike Torrez', 'Luis Tiant', 'Dennis Eckersley', 'Bill Lee'],
    correctIndex: 0,
    explanation: 'Dent’s seventh-inning shot at Fenway turned a 2-0 deficit into a 3-2 Yankees lead; they won 5-4.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/BOS/BOS197810020.shtml',
    sourceLabel: 'Baseball-Reference: Yankees at Red Sox, October 2, 1978',
  },
  {
    id: 'bb030',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Curse of the Bambino',
    difficulty: 'expert',
    question: 'Whose 11th-inning homer off Tim Wakefield won Game 7 of the 2003 ALCS for the Yankees?',
    options: ['Derek Jeter', 'Aaron Boone', 'Jorge Posada', 'Hideki Matsui'],
    correctIndex: 1,
    explanation: 'Boone led off the 11th; Jorge Posada’s two-run double off Pedro Martinez had tied it 5-5 in the eighth.',
    sourceUrl: 'https://www.baseball-reference.com/postseason/2003_ALCS.shtml',
    sourceLabel: 'Baseball-Reference: 2003 ALCS',
  },
  {
    id: 'bb031',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Buckner 1986',
    difficulty: 'expert',
    question: 'Which Mets batter hit the ground ball that rolled through Bill Buckner’s legs in Game 6?',
    options: ['Lenny Dykstra', 'Keith Hernandez', 'Mookie Wilson', 'Gary Carter'],
    correctIndex: 2,
    explanation: 'Wilson’s ten-pitch at-bat included the Bob Stanley wild pitch that had tied the game.',
    sourceUrl: 'https://sabr.org/bioproj/person/bill-buckner/',
    sourceLabel: 'SABR: Bill Buckner biography',
  },
  {
    id: 'bb032',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Cubs 2016',
    difficulty: 'expert',
    question: 'Who was named MVP of the 2016 World Series after his go-ahead double in the tenth inning of Game 7?',
    options: ['Kris Bryant', 'Anthony Rizzo', 'Javier Baez', 'Ben Zobrist'],
    correctIndex: 3,
    explanation: 'Zobrist hit .357 in the Series; Baez and Jon Lester had shared the NLCS award.',
    sourceUrl: 'https://www.baseball-reference.com/postseason/2016_WS.shtml',
    sourceLabel: 'Baseball-Reference: 2016 World Series',
  },
  {
    id: 'bb033',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Cubs 2016',
    difficulty: 'expert',
    question: 'Which Cleveland hitter tied Game 7 of the 2016 World Series with an eighth-inning homer off Aroldis Chapman?',
    options: ['Rajai Davis', 'Francisco Lindor', 'Jason Kipnis', 'Jose Ramirez'],
    correctIndex: 0,
    explanation: 'Davis’s two-run line drive made it 6-6 before the Cubs won in the tenth.',
    sourceUrl: 'https://www.baseball-reference.com/postseason/2016_WS.shtml',
    sourceLabel: 'Baseball-Reference: 2016 World Series',
  },
  {
    id: 'bb034',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Astros sign-stealing',
    difficulty: 'expert',
    question: 'Which former Astros pitcher went on the record in November 2019 to expose the 2017 sign-stealing scheme?',
    options: ['Dallas Keuchel', 'Mike Fiers', 'Charlie Morton', 'Collin McHugh'],
    correctIndex: 1,
    explanation: 'Fiers spoke to The Athletic; Manfred suspended A.J. Hinch and Jeff Luhnow for the 2020 season.',
    sourceUrl: 'https://img.mlbstatic.com/mlb-images/image/upload/mlb/cglrhmlrwwbkacty27l7.pdf',
    sourceLabel: 'MLB: Statement of the Commissioner on the Astros investigation',
  },
  {
    id: 'bb035',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Negro Leagues',
    difficulty: 'expert',
    question: 'Who became the first Black player in the American League, debuting for Cleveland on July 5, 1947?',
    options: ['Monte Irvin', 'Minnie Minoso', 'Larry Doby', 'Satchel Paige'],
    correctIndex: 2,
    explanation: 'Bill Veeck signed Doby from the Newark Eagles; he pinch-hit that day at Comiskey Park.',
    sourceUrl: 'https://sabr.org/gamesproj/game/july-5-1947-larry-doby-integrates-american-league-with-pinch-hitting-appearance-for-cleveland/',
    sourceLabel: 'SABR Games Project: July 5, 1947, Larry Doby integrates the American League',
  },
  {
    id: 'bb036',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Perfect games',
    difficulty: 'expert',
    question: 'Which Yankee threw a perfect game against Montreal on "Yogi Berra Day" in July 1999?',
    options: ['Andy Pettitte', 'Roger Clemens', 'David Wells', 'David Cone'],
    correctIndex: 3,
    explanation: 'Cone needed just 88 pitches, after Don Larsen had thrown out the ceremonial first pitch.',
    sourceUrl: 'https://sabr.org/journal/article/eleven-masterpieces-yankee-stadiums-no-hitters/',
    sourceLabel: 'SABR: Eleven Masterpieces, Yankee Stadium’s no-hitters',
  },
  {
    id: 'bb037',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Perfect games',
    difficulty: 'expert',
    question: 'Which umpire’s missed call at first base cost Armando Galarraga a perfect game in June 2010?',
    options: ['Jim Joyce', 'Joe West', 'Angel Hernandez', 'Bob Davidson'],
    correctIndex: 0,
    explanation: 'Joyce admitted "I just cost that kid a perfect game"; Commissioner Selig declined to overturn it.',
    sourceUrl: 'https://sabr.org/bioproj/person/armando-galarraga/',
    sourceLabel: 'SABR: Armando Galarraga biography',
  },
  {
    id: 'bb038',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'The 1994 strike',
    difficulty: 'expert',
    question: 'On which date did the 1994 players’ strike begin?',
    options: ['July 4, 1994', 'August 12, 1994', 'September 14, 1994', 'October 1, 1994'],
    correctIndex: 1,
    explanation: 'Tony Gwynn was hitting .394 and Montreal had the best record in baseball when play stopped.',
    sourceUrl: 'https://sabr.org/bioproj/person/bud-selig/',
    sourceLabel: 'SABR: Bud Selig biography',
  },
  {
    id: 'bb039',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Home run records',
    difficulty: 'expert',
    question: 'Which Dodgers pitcher gave up Hank Aaron’s 715th home run in Atlanta in 1974?',
    options: ['Don Sutton', 'Andy Messersmith', 'Al Downing', 'Tommy John'],
    correctIndex: 2,
    explanation: 'Aaron hit a 1-0 pitch from Downing into the left-field bullpen at Atlanta-Fulton County Stadium.',
    sourceUrl: 'https://baseballhall.org/hall-of-famers/aaron-hank',
    sourceLabel: 'Baseball Hall of Fame: Hank Aaron',
  },
  {
    id: 'bb040',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Shohei Ohtani',
    difficulty: 'expert',
    question: 'Against which team did Shohei Ohtani hit three homers and steal two bases to reach 50-50 in September 2024?',
    options: ['Colorado Rockies', 'San Diego Padres', 'Arizona Diamondbacks', 'Miami Marlins'],
    correctIndex: 3,
    explanation: 'He went 6-for-6 with 10 RBIs in Miami on September 19, 2024, finishing the day at 51 homers and 51 steals.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/MIA/MIA202409190.shtml',
    sourceLabel: 'Baseball-Reference: Dodgers at Marlins, September 19, 2024',
  },
  // ---------------------------------------------------------------- extreme
  {
    id: 'bb041',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Black Sox 1919',
    difficulty: 'extreme',
    question: 'Which banned Black Sox third baseman hit .324 in the Series, took no money, and petitioned for reinstatement until 1953?',
    options: ['Buck Weaver', 'Chick Gandil', 'Swede Risberg', 'Fred McMullin'],
    correctIndex: 0,
    explanation: 'Weaver was expelled for knowing of the fix and not reporting it; his last plea went to Ford Frick.',
    sourceUrl: 'https://sabr.org/bioproj/person/buck-weaver/',
    sourceLabel: 'SABR: Buck Weaver biography',
  },
  {
    id: 'bb042',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Black Sox 1919',
    difficulty: 'extreme',
    question: 'Which newspaper’s reporter, Charley Owens, first printed the "Say it ain’t so, Joe" anecdote?',
    options: ['Chicago Tribune', 'Chicago Daily News', 'Chicago Herald and Examiner', 'New York World'],
    correctIndex: 1,
    explanation: 'Jackson himself denied the exchange outside the grand jury ever happened.',
    sourceUrl: 'https://sabr.org/bioproj/person/shoeless-joe-jackson/',
    sourceLabel: 'SABR: Shoeless Joe Jackson biography',
  },
  {
    id: 'bb043',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Steroid era',
    difficulty: 'extreme',
    question: 'How many intentional walks did Barry Bonds draw in 2004, the record season in which he walked 232 times?',
    options: ['96', '104', '120', '133'],
    correctIndex: 2,
    explanation: 'Bonds posted a .609 on-base percentage that year and won his seventh MVP.',
    sourceUrl: 'https://www.baseball-reference.com/players/b/bondsba01.shtml',
    sourceLabel: 'Baseball-Reference: Barry Bonds',
  },
  {
    id: 'bb044',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Steroid era',
    difficulty: 'extreme',
    question: 'What share of the 2022 BBWAA vote did Barry Bonds receive in his tenth and final year on the ballot?',
    options: ['61.8 percent', '71.1 percent', '73.6 percent', '66.0 percent'],
    correctIndex: 3,
    explanation: 'Bonds had 260 of 394 ballots; Roger Clemens, a seven-time Cy Young winner, got 65.2 percent.',
    sourceUrl: 'https://bbwaa.com/22-hof/',
    sourceLabel: 'BBWAA: 2022 Hall of Fame election results',
  },
  {
    id: 'bb045',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Pete Rose',
    difficulty: 'extreme',
    question: 'Pete Rose was suspended 30 days in 1988 for shoving which umpire?',
    options: ['Dave Pallone', 'Eric Gregg', 'Bruce Froemming', 'Doug Harvey'],
    correctIndex: 0,
    explanation: 'The Pallone incident came a year before the betting investigation that ended his career.',
    sourceUrl: 'https://sabr.org/bioproj/person/pete-rose/',
    sourceLabel: 'SABR: Pete Rose biography',
  },
  {
    id: 'bb046',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Curse of the Bambino',
    difficulty: 'extreme',
    question: 'Who was the winning pitcher for the Yankees in the 1978 one-game playoff at Fenway Park?',
    options: ['Catfish Hunter', 'Ron Guidry', 'Ed Figueroa', 'Goose Gossage'],
    correctIndex: 1,
    explanation: 'Guidry improved to 25-3; Gossage recorded the save in the 5-4 win.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/BOS/BOS197810020.shtml',
    sourceLabel: 'Baseball-Reference: Yankees at Red Sox, October 2, 1978',
  },
  {
    id: 'bb047',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Curse of the Bambino',
    difficulty: 'extreme',
    question: 'Which Yankees pitcher gave up David Ortiz’s 14th-inning walk-off single in Game 5 of the 2004 ALCS?',
    options: ['Tom Gordon', 'Paul Quantrill', 'Esteban Loaiza', 'Tanyon Sturtze'],
    correctIndex: 2,
    explanation: 'A night earlier Ortiz had ended Game 4 with a 12th-inning homer after Dave Roberts’ steal.',
    sourceUrl: 'https://www.baseball-reference.com/postseason/2004_ALCS.shtml',
    sourceLabel: 'Baseball-Reference: 2004 ALCS',
  },
  {
    id: 'bb048',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Cubs 2016',
    difficulty: 'extreme',
    question: 'In the 2003 "Bartman game", which Cubs shortstop booted a potential double-play grounder during Florida’s eight-run eighth?',
    options: ['Mark Grudzielanek', 'Ramon Martinez', 'Aramis Ramirez', 'Alex Gonzalez'],
    correctIndex: 3,
    explanation: 'Gonzalez’s error on Miguel Cabrera’s grounder came with Chicago still ahead 3-1 in NLCS Game 6.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/CHN/CHN200310140.shtml',
    sourceLabel: 'Baseball-Reference: Marlins at Cubs, NLCS Game 6, October 14, 2003',
  },
  {
    id: 'bb049',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Cubs 2016',
    difficulty: 'extreme',
    question: 'Which Cleveland reliever gave up Ben Zobrist’s go-ahead double in the tenth inning of Game 7 in 2016?',
    options: ['Bryan Shaw', 'Andrew Miller', 'Cody Allen', 'Trevor Bauer'],
    correctIndex: 0,
    explanation: 'Albert Almora scored from second on the one-out double, with Anthony Rizzo moving to third.',
    sourceUrl: 'https://www.baseball-reference.com/postseason/2016_WS.shtml',
    sourceLabel: 'Baseball-Reference: 2016 World Series',
  },
  {
    id: 'bb050',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Astros sign-stealing',
    difficulty: 'extreme',
    question: 'The Astros forfeited their first- and second-round picks in which two amateur drafts as punishment?',
    options: ['2019 and 2020', '2020 and 2021', '2021 and 2022', '2020 only'],
    correctIndex: 1,
    explanation: 'The club was also fined $5 million, the maximum allowed under the MLB Constitution.',
    sourceUrl: 'https://img.mlbstatic.com/mlb-images/image/upload/mlb/cglrhmlrwwbkacty27l7.pdf',
    sourceLabel: 'MLB: Statement of the Commissioner on the Astros investigation',
  },
  {
    id: 'bb051',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Astros sign-stealing',
    difficulty: 'extreme',
    question: 'Which two reporters wrote The Athletic story in which Mike Fiers exposed the Astros scheme?',
    options: [
      'Jeff Passan and Buster Olney',
      'Tom Verducci and Jon Heyman',
      'Ken Rosenthal and Evan Drellich',
      'Jayson Stark and Joel Sherman',
    ],
    correctIndex: 2,
    explanation: 'The story ran on November 12, 2019; Manfred’s findings were published on January 13, 2020.',
    sourceUrl: 'https://img.mlbstatic.com/mlb-images/image/upload/mlb/cglrhmlrwwbkacty27l7.pdf',
    sourceLabel: 'MLB: Statement of the Commissioner on the Astros investigation',
  },
  {
    id: 'bb052',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Jackie Robinson',
    difficulty: 'extreme',
    question: 'Which club provided the opposition for Jackie Robinson’s major league debut at Ebbets Field?',
    options: ['Philadelphia Phillies', 'New York Giants', 'St. Louis Cardinals', 'Boston Braves'],
    correctIndex: 3,
    explanation: 'Robinson went 0-for-3 at first base before a crowd of 26,623, reaching on an error off Johnny Sain.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/BRO/BRO194704150.shtml',
    sourceLabel: 'Baseball-Reference: Braves at Dodgers, April 15, 1947',
  },
  {
    id: 'bb053',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Negro Leagues',
    difficulty: 'extreme',
    question: 'For which club did Satchel Paige pitch three shutout innings at age 59 in September 1965?',
    options: ['Kansas City Athletics', 'St. Louis Browns', 'Cleveland Indians', 'Washington Senators'],
    correctIndex: 0,
    explanation: 'Paige had made his AL debut for Cleveland in 1948 at 42, signed by Bill Veeck.',
    sourceUrl: 'https://baseballhall.org/hall-of-famers/paige-satchel',
    sourceLabel: 'Baseball Hall of Fame: Satchel Paige',
  },
  {
    id: 'bb054',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Negro Leagues',
    difficulty: 'extreme',
    question: 'Which Newark Eagles owner became the first woman elected to the Baseball Hall of Fame in 2006?',
    options: ['Toni Stone', 'Effa Manley', 'Marge Schott', 'Olivia Taylor'],
    correctIndex: 1,
    explanation: 'Her 1946 Eagles won the Negro League World Series; she later won compensation for Larry Doby’s signing.',
    sourceUrl: 'https://baseballhall.org/hall-of-famers/manley-effa',
    sourceLabel: 'Baseball Hall of Fame: Effa Manley',
  },
  {
    id: 'bb055',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Perfect games',
    difficulty: 'extreme',
    question: 'Which Cleveland batter, the would-be 27th out, was wrongly called safe to end Armando Galarraga’s perfect game?',
    options: ['Trevor Crowe', 'Mark Grudzielanek', 'Jason Donald', 'Shin-Soo Choo'],
    correctIndex: 2,
    explanation: 'It would have been the 21st perfect game in history and Detroit’s first.',
    sourceUrl: 'https://sabr.org/bioproj/person/armando-galarraga/',
    sourceLabel: 'SABR: Armando Galarraga biography',
  },
  {
    id: 'bb056',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'The 1994 strike',
    difficulty: 'extreme',
    question: 'How many days did the 1994-95 players’ strike last?',
    options: ['187', '204', '256', '232'],
    correctIndex: 3,
    explanation: 'It ended after Judge Sonia Sotomayor’s injunction blocked the owners’ replacement-player plan.',
    sourceUrl: 'https://sabr.org/bioproj/person/bud-selig/',
    sourceLabel: 'SABR: Bud Selig biography',
  },
  {
    id: 'bb057',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Home run records',
    difficulty: 'extreme',
    question: 'Which Washington Senators pitcher gave up Babe Ruth’s 60th home run on September 30, 1927?',
    options: ['Tom Zachary', 'Walter Johnson', 'Firpo Marberry', 'Hod Lisenbee'],
    correctIndex: 0,
    explanation: 'The eighth-inning shot down the right-field line drove in Ruth’s 165th run of the season.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/NYA/NYA192709300.shtml',
    sourceLabel: 'Baseball-Reference: Senators at Yankees, September 30, 1927',
  },
  {
    id: 'bb058',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Home run records',
    difficulty: 'extreme',
    question: 'Off which Rangers pitcher did Aaron Judge hit his AL-record 62nd home run in October 2022?',
    options: ['Martin Perez', 'Jesus Tinoco', 'Jon Gray', 'Kolby Allard'],
    correctIndex: 1,
    explanation: 'Judge led off the second game of a doubleheader in Arlington with the homer.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/TEX/TEX202210042.shtml',
    sourceLabel: 'Baseball-Reference: Yankees at Rangers, October 4, 2022 (game 2)',
  },
  {
    id: 'bb059',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Shohei Ohtani',
    difficulty: 'extreme',
    question: 'How many runs did Shohei Ohtani drive in during his 50-50 game in Miami on September 19, 2024?',
    options: ['7', '8', '10', '12'],
    correctIndex: 2,
    explanation: 'His three homers came off George Soriano, Mike Baumann and Vidal Brujan, and he also doubled twice.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/MIA/MIA202409190.shtml',
    sourceLabel: 'Baseball-Reference: Dodgers at Marlins, September 19, 2024',
  },
  {
    id: 'bb060',
    domain: 'sports',
    region: 'US',
    topic: 'Baseball',
    subtopic: 'Buckner 1986',
    difficulty: 'extreme',
    question: 'Whose leadoff homer in the top of the tenth had put Boston ahead in Game 6 before the Mets’ rally?',
    options: ['Jim Rice', 'Dwight Evans', 'Wade Boggs', 'Dave Henderson'],
    correctIndex: 3,
    explanation: 'Henderson homered off Rick Aguilera; Boston led 5-3 with two out and nobody on before the collapse.',
    sourceUrl: 'https://www.baseball-reference.com/boxes/NYN/NYN198610250.shtml',
    sourceLabel: 'Baseball-Reference: Red Sox at Mets, World Series Game 6, October 25, 1986',
  },
]);
