// Server-only editorial bank: Basketball (tranche 1). Never import this module from client components.
// Every fact below was checked against the cited sourceUrl at authoring time; Wikipedia is never a source.
// Where a primary page is no longer served live (the Pedowitz report, ESPN's 2010 story, olympics.com results,
// the old NBA.com and USA Basketball history pages), the cited URL is the Wayback Machine capture that was read.
export const BASKETBALL = Object.freeze([
  // ---------------------------------------------------------------- simple
  {
    id: 'bk001',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Wilt’s 100',
    difficulty: 'simple',
    question: 'Against which team did Wilt Chamberlain score his 100 points on 2 March 1962?',
    options: ['New York Knicks', 'Boston Celtics', 'Los Angeles Lakers', 'Syracuse Nationals'],
    correctIndex: 0,
    explanation: 'The Warriors won 169-147 in front of just 4,124 people, though many thousands more later claimed to have been there.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-1961-62',
    sourceLabel: 'NBA.com: Season Review 1961-62',
  },
  {
    id: 'bk002',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Kobe’s 81',
    difficulty: 'simple',
    question: 'Kobe Bryant’s 81-point game in January 2006 came against which opponent?',
    options: ['Dallas Mavericks', 'Toronto Raptors', 'Memphis Grizzlies', 'Portland Trail Blazers'],
    correctIndex: 1,
    explanation: 'The Lakers won 122-104; only Wilt’s 100 has ever beaten Kobe’s total in a single NBA game.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-2005-06',
    sourceLabel: 'NBA.com: Season Review 2005-06',
  },
  {
    id: 'bk003',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'The 3-1 comeback (2016)',
    difficulty: 'simple',
    question: 'Which franchise ended a 52-year city title drought by overturning a 3-1 NBA Finals deficit in 2016?',
    options: ['Toronto Raptors', 'Oklahoma City Thunder', 'Cleveland Cavaliers', 'Golden State Warriors'],
    correctIndex: 2,
    explanation: 'No team had ever come back from 3-1 in the Finals; LeBron averaged 36.3 points over the last three games.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-2015-16',
    sourceLabel: 'NBA.com: Season Review 2015-16',
  },
  {
    id: 'bk004',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'The 3-1 comeback (2016)',
    difficulty: 'simple',
    question: 'LeBron James’s chase-down block in Game 7 of the 2016 Finals denied which Warrior?',
    options: ['Stephen Curry', 'Klay Thompson', 'Harrison Barnes', 'Andre Iguodala'],
    correctIndex: 3,
    explanation: 'The block came with the score tied 89-89 and under two minutes left; Cleveland never trailed again.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/pbp/201606190GSW.html',
    sourceLabel: 'Basketball-Reference: 2016 Finals Game 7 play-by-play',
  },
  {
    id: 'bk005',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Warriors 73-9',
    difficulty: 'simple',
    question: 'The 2015-16 Warriors’ 73 wins broke a regular-season record set by which team?',
    options: ['1995-96 Chicago Bulls', '1971-72 Los Angeles Lakers', '1985-86 Boston Celtics', '1996-97 Chicago Bulls'],
    correctIndex: 0,
    explanation: 'Jordan’s Bulls went 72-10 under Phil Jackson; Golden State went 73-9 and then lost the Finals.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-2015-16',
    sourceLabel: 'NBA.com: Season Review 2015-16',
  },
  {
    id: 'bk006',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Malice at the Palace',
    difficulty: 'simple',
    question: 'The 2004 “Malice at the Palace” brawl erupted during a Pistons home game against which visiting team?',
    options: ['Chicago Bulls', 'Indiana Pacers', 'Cleveland Cavaliers', 'Milwaukee Bucks'],
    correctIndex: 1,
    explanation: 'The fight on 19 November 2004 spilled into the stands at the Palace of Auburn Hills and led to lawsuits as well as suspensions.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-2004-05',
    sourceLabel: 'NBA.com: Season Review 2004-05',
  },
  {
    id: 'bk007',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Tim Donaghy',
    difficulty: 'simple',
    question: 'Tim Donaghy, at the centre of the NBA’s 2007 betting scandal, had worked for the league in what role?',
    options: ['Team physician', 'Official scorer', 'Referee', 'Assistant coach'],
    correctIndex: 2,
    explanation: 'Donaghy officiated 753 regular-season games from 1994-95 to 2006-07 before his guilty plea.',
    sourceUrl: 'https://www.basketball-reference.com/referees/donagti99r.html',
    sourceLabel: 'Basketball-Reference: Tim Donaghy referee page',
  },
  {
    id: 'bk008',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Kings-Lakers 2002',
    difficulty: 'simple',
    question: 'Which team pushed the Lakers to a Game 7 overtime in the 2002 Western Conference finals?',
    options: ['San Antonio Spurs', 'Dallas Mavericks', 'Portland Trail Blazers', 'Sacramento Kings'],
    correctIndex: 3,
    explanation: 'The Lakers won Game 7 112-106 in Sacramento; the series’ officiating is still argued about today.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-2001-02',
    sourceLabel: 'NBA.com: Season Review 2001-02',
  },
  {
    id: 'bk009',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Shaq-Kobe split',
    difficulty: 'simple',
    question: 'After the 2004 Finals defeat, Shaquille O’Neal was traded from the Lakers to which team?',
    options: ['Miami Heat', 'Phoenix Suns', 'Cleveland Cavaliers', 'Boston Celtics'],
    correctIndex: 0,
    explanation: 'Shaq promised Miami a title on arrival and delivered it in 2006 alongside Dwyane Wade.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-2004-05',
    sourceLabel: 'NBA.com: Season Review 2004-05',
  },
  {
    id: 'bk010',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: '1985 lottery',
    difficulty: 'simple',
    question: 'Whom did the Knicks select after winning the NBA’s first draft lottery in 1985?',
    options: ['Hakeem Olajuwon', 'Patrick Ewing', 'Karl Malone', 'Chris Mullin'],
    correctIndex: 1,
    explanation: 'Ewing made his debut on 26 October 1985 and went on to win Rookie of the Year.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-1985-86',
    sourceLabel: 'NBA.com: Season Review 1985-86',
  },
  {
    id: 'bk011',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Bird-Magic',
    difficulty: 'simple',
    question: 'In the 1979 NCAA final, Magic Johnson’s Michigan State beat which school led by Larry Bird?',
    options: ['Indiana', 'DePaul', 'Indiana State', 'Penn'],
    correctIndex: 2,
    explanation: 'Michigan State won 75-64 in Salt Lake City and Magic was named Most Outstanding Player.',
    sourceUrl: 'https://www.sports-reference.com/cbb/postseason/men/1979-ncaa.html',
    sourceLabel: 'Sports-Reference: 1979 NCAA Tournament',
  },
  {
    id: 'bk012',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Bird-Magic',
    difficulty: 'simple',
    question: 'Magic Johnson retired days into the 1991-92 season after announcing he had contracted what?',
    options: ['Hepatitis', 'Lyme disease', 'Leukaemia', 'HIV'],
    correctIndex: 3,
    explanation: 'Fans still voted him into the 1992 All-Star Game, where he scored 25 points and won MVP.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-1991-92',
    sourceLabel: 'NBA.com: Season Review 1991-92',
  },
  {
    id: 'bk013',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'Dream Team',
    difficulty: 'simple',
    question: 'The original Dream Team won Olympic gold in 1992 in which city?',
    options: ['Barcelona', 'Atlanta', 'Seoul', 'Sydney'],
    correctIndex: 0,
    explanation: 'It was the first US Olympic team to include NBA stars and beat its eight opponents by an average of 44 points.',
    sourceUrl: 'https://web.archive.org/web/2012id_/http://www.nba.com/history/dreamT_moments.html',
    sourceLabel: 'NBA.com (archived): The Original Dream Team',
  },
  {
    id: 'bk014',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'Dream Team',
    difficulty: 'simple',
    question: 'Who coached the 1992 Dream Team?',
    options: ['Pat Riley', 'Chuck Daly', 'Lenny Wilkens', 'Mike Krzyzewski'],
    correctIndex: 1,
    explanation: 'Daly likened travelling with the team to “Elvis and the Beatles put together”.',
    sourceUrl: 'https://web.archive.org/web/2012id_/http://www.nba.com/history/dreamT_moments.html',
    sourceLabel: 'NBA.com (archived): The Original Dream Team',
  },
  {
    id: 'bk015',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'Olympic basketball',
    difficulty: 'simple',
    question: 'Which nation won men’s basketball gold at Athens 2004, with the USA settling for bronze?',
    options: ['Italy', 'Lithuania', 'Argentina', 'Spain'],
    correctIndex: 2,
    explanation: 'Italy took silver; the shock prompted USA Basketball to rebuild its whole national-team programme.',
    sourceUrl: 'https://web.archive.org/web/2024id_/https://olympics.com/en/olympic-games/athens-2004/results/basketball/basketball-men',
    sourceLabel: 'Olympics.com (archived): Athens 2004 men’s basketball results',
  },
  {
    id: 'bk016',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'FIBA World Cup',
    difficulty: 'simple',
    question: 'Which country won the 2023 FIBA Basketball World Cup, finishing ahead of Serbia and Canada?',
    options: ['Spain', 'USA', 'Australia', 'Germany'],
    correctIndex: 3,
    explanation: 'Dennis Schröder was tournament MVP; the USA finished fourth in the event co-hosted by the Philippines, Japan and Indonesia.',
    sourceUrl: 'https://www.fiba.basketball/basketballworldcup/2023',
    sourceLabel: 'FIBA: Basketball World Cup 2023',
  },
  {
    id: 'bk017',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'WNBA',
    difficulty: 'simple',
    question: 'Which team won the WNBA’s first four championships, from 1997 to 2000?',
    options: ['Houston Comets', 'Los Angeles Sparks', 'New York Liberty', 'Phoenix Mercury'],
    correctIndex: 0,
    explanation: 'Behind Cynthia Cooper, Sheryl Swoopes and Tina Thompson, Houston won every title of the league’s first four seasons before the franchise folded in 2008.',
    sourceUrl: 'https://www.wnba.com/all-time-wnba-champions/',
    sourceLabel: 'WNBA: All-Time WNBA Champions',
  },
  {
    id: 'bk018',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'WNBA',
    difficulty: 'simple',
    question: 'Caitlin Clark won the 2024 WNBA Rookie of the Year award with which team?',
    options: ['Chicago Sky', 'Indiana Fever', 'Las Vegas Aces', 'Dallas Wings'],
    correctIndex: 1,
    explanation: 'A’ja Wilson of Las Vegas was the league MVP that same season.',
    sourceUrl: 'https://www.wnba.com/awards2024',
    sourceLabel: 'WNBA: 2024 Season Awards',
  },
  {
    id: 'bk019',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'The 2020 bubble',
    difficulty: 'simple',
    question: 'Whom did the Lakers beat in the 2020 Finals played inside the Disney World bubble?',
    options: ['Boston Celtics', 'Denver Nuggets', 'Miami Heat', 'Milwaukee Bucks'],
    correctIndex: 2,
    explanation: 'LeBron closed the series with 28 points, 14 rebounds and 10 assists in Game 6 and nobody tested positive in three months on campus.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-2019-20',
    sourceLabel: 'NBA.com: Season Review 2019-20',
  },
  {
    id: 'bk020',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Jordan’s Bulls',
    difficulty: 'simple',
    question: 'Jordan’s final shot as a Bull, the 1998 Finals winner with 5.2 seconds left, beat which team?',
    options: ['Seattle SuperSonics', 'Phoenix Suns', 'Portland Trail Blazers', 'Utah Jazz'],
    correctIndex: 3,
    explanation: 'He scored 45 in that Game 6, making the steal and then the jumper that won it 87-86.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-1997-98',
    sourceLabel: 'NBA.com: Season Review 1997-98',
  },
  // ---------------------------------------------------------------- expert
  {
    id: 'bk021',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Wilt’s 100',
    difficulty: 'expert',
    question: 'Wilt’s 100-point game was played not in Philadelphia but in which Pennsylvania town?',
    options: ['Allentown', 'Scranton', 'Hershey', 'Pittsburgh'],
    correctIndex: 2,
    explanation: 'The venue was the Hershey Sports Arena; Richie Guerin’s 39 for New York went almost unnoticed.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/196203020NYK.html',
    sourceLabel: 'Basketball-Reference: Warriors vs Knicks, March 2, 1962',
  },
  {
    id: 'bk022',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Kobe’s 81',
    difficulty: 'expert',
    question: 'How many of Kobe Bryant’s 81 points came after half-time?',
    options: ['41', '48', '55', '62'],
    correctIndex: 2,
    explanation: 'He had 26 at the break, then went 18-of-28 from the field in the second half as the Lakers came from behind.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/200601220LAL.html',
    sourceLabel: 'Basketball-Reference: Raptors vs Lakers, January 22, 2006',
  },
  {
    id: 'bk023',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'The 3-1 comeback (2016)',
    difficulty: 'expert',
    question: 'Who hit the go-ahead three-pointer with 53 seconds left in Game 7 of the 2016 Finals?',
    options: ['Kyrie Irving', 'LeBron James', 'J.R. Smith', 'Kevin Love'],
    correctIndex: 0,
    explanation: 'The 25-footer broke an 89-89 tie; Irving finished with 26 points.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/pbp/201606190GSW.html',
    sourceLabel: 'Basketball-Reference: 2016 Finals Game 7 play-by-play',
  },
  {
    id: 'bk024',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'The 3-1 comeback (2016)',
    difficulty: 'expert',
    question: 'Which Warrior sat out Game 5 of the 2016 Finals through suspension, with Golden State leading 3-1?',
    options: ['Andrew Bogut', 'Draymond Green', 'Festus Ezeli', 'Klay Thompson'],
    correctIndex: 1,
    explanation: 'Cleveland won that game 112-97 in Oakland and the Warriors never won again in the series.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/201606130GSW.html',
    sourceLabel: 'Basketball-Reference: 2016 Finals Game 5 box score',
  },
  {
    id: 'bk025',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Warriors 73-9',
    difficulty: 'expert',
    question: 'How many three-pointers did Stephen Curry make in the 2015-16 regular season, the first time anyone passed 400?',
    options: ['386', '414', '402', '373'],
    correctIndex: 2,
    explanation: 'He broke his own record on the way to becoming the NBA’s first unanimous MVP.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-2015-16',
    sourceLabel: 'NBA.com: Season Review 2015-16',
  },
  {
    id: 'bk026',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Malice at the Palace',
    difficulty: 'expert',
    question: 'Nine players were suspended after the Malice at the Palace for a combined total of how many games?',
    options: ['86', '120', '172', '146'],
    correctIndex: 3,
    explanation: 'Ron Artest, the first player into the stands, was banned for the rest of the season.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-2004-05',
    sourceLabel: 'NBA.com: Season Review 2004-05',
  },
  {
    id: 'bk027',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Tim Donaghy',
    difficulty: 'expert',
    question: 'In which year did Tim Donaghy plead guilty in federal court in Brooklyn?',
    options: ['2007', '2005', '2008', '2010'],
    correctIndex: 0,
    explanation: 'He admitted two felonies on 15 August 2007, including conspiracy to commit wire fraud.',
    sourceUrl: 'https://web.archive.org/web/2009id_/http://www.nba.com/media/PedowitzReport.pdf',
    sourceLabel: 'NBA (archived): Pedowitz report to the Board of Governors, October 2008',
  },
  {
    id: 'bk028',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Kings-Lakers 2002',
    difficulty: 'expert',
    question: 'After escaping Sacramento in 2002, whom did the Lakers sweep in the Finals to complete their three-peat?',
    options: ['Boston Celtics', 'New Jersey Nets', 'Indiana Pacers', 'Philadelphia 76ers'],
    correctIndex: 1,
    explanation: 'Shaq averaged 36.3 points in the sweep and joined Jordan as the only men with three straight Finals MVPs.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-2001-02',
    sourceLabel: 'NBA.com: Season Review 2001-02',
  },
  {
    id: 'bk029',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Shaq-Kobe split',
    difficulty: 'expert',
    question: 'Who was Finals MVP when Detroit beat the Lakers’ “Big Four” in five games in 2004?',
    options: ['Ben Wallace', 'Richard Hamilton', 'Chauncey Billups', 'Rasheed Wallace'],
    correctIndex: 2,
    explanation: '“Mr. Big Shot” outplayed a Lakers side that had added Karl Malone and Gary Payton to Shaq and Kobe.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-2003-04',
    sourceLabel: 'NBA.com: Season Review 2003-04',
  },
  {
    id: 'bk030',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: '1985 lottery',
    difficulty: 'expert',
    question: 'Patrick Ewing arrived at the Knicks from which college?',
    options: ['Syracuse', 'St. John’s', 'North Carolina', 'Georgetown'],
    correctIndex: 3,
    explanation: 'His rookie class also included Karl Malone, Joe Dumars and Chris Mullin.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-1985-86',
    sourceLabel: 'NBA.com: Season Review 1985-86',
  },
  {
    id: 'bk031',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Bird-Magic',
    difficulty: 'expert',
    question: 'Magic Johnson’s Game 4 winner in the 1987 Finals borrowed which teammate’s signature shot?',
    options: ['Kareem Abdul-Jabbar’s sky-hook', 'James Worthy’s finger roll', 'Byron Scott’s pull-up jumper', 'Michael Cooper’s corner three'],
    correctIndex: 0,
    explanation: '“You expect to lose on a sky-hook,” Bird said afterwards. “You don’t expect it to be from Magic.”',
    sourceUrl: 'https://www.nba.com/news/history-season-review-1986-87',
    sourceLabel: 'NBA.com: Season Review 1986-87',
  },
  {
    id: 'bk032',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Bird-Magic',
    difficulty: 'expert',
    question: 'Who was Finals MVP in 1985, when the Lakers beat the Celtics in a Finals for the first time ever?',
    options: ['Magic Johnson', 'Kareem Abdul-Jabbar', 'James Worthy', 'Byron Scott'],
    correctIndex: 1,
    explanation: 'Los Angeles clinched in Game 6 at Boston Garden, silencing a building where the Celtics had lost only one Finals before.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-1984-85',
    sourceLabel: 'NBA.com: Season Review 1984-85',
  },
  {
    id: 'bk033',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'Dream Team',
    difficulty: 'expert',
    question: 'The Dream Team won the 1992 gold-medal game 117-85 against which country?',
    options: ['Lithuania', 'Unified Team', 'Croatia', 'Brazil'],
    correctIndex: 2,
    explanation: 'Croatia took silver and Lithuania bronze; the closest anyone got to the Americans all tournament was 32 points.',
    sourceUrl: 'https://web.archive.org/web/2012id_/http://www.usab.com/mens/national/moly_1992.html',
    sourceLabel: 'USA Basketball (archived): 1992 Olympic Games',
  },
  {
    id: 'bk034',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'Olympic basketball',
    difficulty: 'expert',
    question: 'The USA’s first ever Olympic basketball defeat came in the 1972 Munich final by what score?',
    options: ['50-49', '51-50', '52-51', '49-48'],
    correctIndex: 1,
    explanation: 'Doug Collins’s free throws had put the USA ahead before the final three seconds were replayed and Aleksander Belov scored for the Soviets.',
    sourceUrl: 'https://web.archive.org/web/2013id_/http://www.usab.com/mens/national/moly_1972.html',
    sourceLabel: 'USA Basketball (archived): 1972 Olympic Games',
  },
  {
    id: 'bk035',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'Olympic basketball',
    difficulty: 'expert',
    question: 'Which team did the USA’s “Redeem Team” beat 118-107 in the Beijing 2008 final?',
    options: ['Argentina', 'Greece', 'Lithuania', 'Spain'],
    correctIndex: 3,
    explanation: 'Argentina, the 2004 champions, took bronze; the USA went 8-0 after the bronze-medal embarrassment of Athens.',
    sourceUrl: 'https://web.archive.org/web/2012id_/http://www.usab.com/mens/national/moly_2008.html',
    sourceLabel: 'USA Basketball (archived): 2008 Olympic Games',
  },
  {
    id: 'bk036',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'FIBA World Cup',
    difficulty: 'expert',
    question: 'Who was tournament MVP when Spain won the 2019 FIBA World Cup in China?',
    options: ['Ricky Rubio', 'Pau Gasol', 'Marc Gasol', 'Sergio Llull'],
    correctIndex: 0,
    explanation: 'Spain beat Argentina in the final; France took bronze and the USA finished seventh.',
    sourceUrl: 'https://www.fiba.basketball/basketballworldcup/2019',
    sourceLabel: 'FIBA: Basketball World Cup 2019',
  },
  {
    id: 'bk037',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'WNBA',
    difficulty: 'expert',
    question: 'Who won the WNBA’s first Most Valuable Player award, in 1997?',
    options: ['Sheryl Swoopes', 'Lisa Leslie', 'Cynthia Cooper', 'Tina Thompson'],
    correctIndex: 2,
    explanation: 'Cooper’s Houston coach Van Chancellor was Coach of the Year and Teresa Weatherspoon the first Defensive Player of the Year.',
    sourceUrl: 'https://www.wnba.com/awards1997',
    sourceLabel: 'WNBA: 1997 Season Awards',
  },
  {
    id: 'bk038',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'WNBA',
    difficulty: 'expert',
    question: 'In 2008, which player won WNBA MVP and Rookie of the Year in the same season?',
    options: ['Maya Moore', 'Candace Parker', 'Diana Taurasi', 'Sylvia Fowles'],
    correctIndex: 1,
    explanation: 'Parker did it for the Los Angeles Sparks, who had drafted her first overall.',
    sourceUrl: 'https://www.wnba.com/awards2008',
    sourceLabel: 'WNBA: 2008 Season Awards',
  },
  {
    id: 'bk039',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'The 2020 bubble',
    difficulty: 'expert',
    question: 'On 26 August 2020 the Bucks refused to take the court for Game 5 against which opponent, halting the playoffs?',
    options: ['Miami Heat', 'Indiana Pacers', 'Orlando Magic', 'Toronto Raptors'],
    correctIndex: 2,
    explanation: 'The walkout protested the police shooting of Jacob Blake in Kenosha, 40 miles from Milwaukee, and spread to other leagues that day.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-2019-20',
    sourceLabel: 'NBA.com: Season Review 2019-20',
  },
  {
    id: 'bk040',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Jordan’s Bulls',
    difficulty: 'expert',
    question: 'How many points did a flu-stricken Michael Jordan score in Game 5 of the 1997 Finals in Utah?',
    options: ['45', '33', '41', '38'],
    correctIndex: 3,
    explanation: 'The Bulls won 90-88 with Jordan playing 44 minutes and going 13-of-27 from the field.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/199706110UTA.html',
    sourceLabel: 'Basketball-Reference: 1997 Finals Game 5 box score',
  },
  // ---------------------------------------------------------------- extreme
  {
    id: 'bk041',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Wilt’s 100',
    difficulty: 'extreme',
    question: 'A notoriously poor foul shooter, how many of his 32 free throws did Wilt make in the 100-point game?',
    options: ['20', '28', '24', '32'],
    correctIndex: 1,
    explanation: 'He also went 36-of-63 from the field; the 36 field goals and 63 attempts were both records.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/196203020NYK.html',
    sourceLabel: 'Basketball-Reference: Warriors vs Knicks, March 2, 1962',
  },
  {
    id: 'bk042',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Kobe’s 81',
    difficulty: 'extreme',
    question: 'How many three-pointers did Kobe Bryant make on his way to 81 points?',
    options: ['5', '9', '7', '11'],
    correctIndex: 2,
    explanation: 'He was 7-of-13 from deep, 28-of-46 overall and 18-of-20 at the line in under 42 minutes.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/200601220LAL.html',
    sourceLabel: 'Basketball-Reference: Raptors vs Lakers, January 22, 2006',
  },
  {
    id: 'bk043',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'The 3-1 comeback (2016)',
    difficulty: 'extreme',
    question: 'What was the final score of Game 7 of the 2016 Finals in Oakland?',
    options: ['95-91', '97-93', '89-87', '93-89'],
    correctIndex: 3,
    explanation: 'LeBron had a 27-11-11 triple-double while Draymond Green’s 32 points led the losing side.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/201606190GSW.html',
    sourceLabel: 'Basketball-Reference: 2016 Finals Game 7 box score',
  },
  {
    id: 'bk044',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Warriors 73-9',
    difficulty: 'extreme',
    question: 'While Steve Kerr recovered from back surgery, who coached the Warriors to a 39-4 start in 2015-16?',
    options: ['Luke Walton', 'Ron Adams', 'Alvin Gentry', 'Mike Brown'],
    correctIndex: 0,
    explanation: 'Walton was interim coach from 27 October 2015 to 20 January 2016, but the wins were credited to Kerr.',
    sourceUrl: 'https://www.basketball-reference.com/teams/GSW/2016.html',
    sourceLabel: 'Basketball-Reference: 2015-16 Golden State Warriors',
  },
  {
    id: 'bk045',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Malice at the Palace',
    difficulty: 'extreme',
    question: 'Which referee, later jailed for betting on games, was one of the three officials at the Malice at the Palace?',
    options: ['Dick Bavetta', 'Tim Donaghy', 'Joey Crawford', 'Steve Javie'],
    correctIndex: 1,
    explanation: 'Donaghy worked the game with Ron Garretson and Tommy Nunez Jr.; the final score stood at 97-82 to Indiana.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/200411190DET.html',
    sourceLabel: 'Basketball-Reference: Pacers vs Pistons, November 19, 2004',
  },
  {
    id: 'bk046',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Tim Donaghy',
    difficulty: 'extreme',
    question: 'Which lawyer’s October 2008 report to the NBA Board of Governors reviewed the Donaghy scandal and referee gambling?',
    options: ['George Mitchell', 'Kenneth Starr', 'Lawrence Pedowitz', 'Louis Freeh'],
    correctIndex: 2,
    explanation: 'Pedowitz, of Wachtell, Lipton, Rosen & Katz, found Donaghy had bet on games he officiated with co-conspirators James Battista and Thomas Martino.',
    sourceUrl: 'https://web.archive.org/web/2009id_/http://www.nba.com/media/PedowitzReport.pdf',
    sourceLabel: 'NBA (archived): Pedowitz report to the Board of Governors, October 2008',
  },
  {
    id: 'bk047',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Kings-Lakers 2002',
    difficulty: 'extreme',
    question: 'In the infamous fourth quarter of Game 6 of the 2002 Western finals, how many free throws did the Lakers attempt?',
    options: ['18', '22', '34', '27'],
    correctIndex: 3,
    explanation: 'They made 21 of 27 in the quarter while Sacramento shot nine; the Lakers won 106-102 to force Game 7.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/200205310LAL.html',
    sourceLabel: 'Basketball-Reference: 2002 West finals Game 6 box score',
  },
  {
    id: 'bk048',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Shaq-Kobe split',
    difficulty: 'extreme',
    question: 'Which player came to the Lakers from Miami in the July 2004 trade that sent Shaq east?',
    options: ['Lamar Odom', 'Kwame Brown', 'Smush Parker', 'Vlade Divac'],
    correctIndex: 0,
    explanation: 'Odom, Caron Butler, Brian Grant and two picks (one became Jordan Farmar) were the return; Divac was signed as a free agent a week later.',
    sourceUrl: 'https://www.basketball-reference.com/teams/LAL/2005_transactions.html',
    sourceLabel: 'Basketball-Reference: 2004-05 Lakers transactions',
  },
  {
    id: 'bk049',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: '1985 lottery',
    difficulty: 'extreme',
    question: 'Who went second overall, to Indiana, straight after Ewing in the 1985 draft?',
    options: ['Benoit Benjamin', 'Wayman Tisdale', 'Xavier McDaniel', 'Chris Mullin'],
    correctIndex: 1,
    explanation: 'The Oklahoma forward was followed by Benoit Benjamin to the Clippers and Xavier McDaniel to Seattle.',
    sourceUrl: 'https://www.basketball-reference.com/draft/NBA_1985.html',
    sourceLabel: 'Basketball-Reference: 1985 NBA Draft',
  },
  {
    id: 'bk050',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Bird-Magic',
    difficulty: 'extreme',
    question: 'Whose steal of a James Worthy pass in Game 2 of the 1984 Finals turned that series for Boston?',
    options: ['Dennis Johnson', 'Danny Ainge', 'Gerald Henderson', 'M.L. Carr'],
    correctIndex: 2,
    explanation: 'The Lakers led by two with 18 seconds left; Henderson’s layup forced overtime and Boston won the series in seven.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-1983-84',
    sourceLabel: 'NBA.com: Season Review 1983-84',
  },
  {
    id: 'bk051',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'Dream Team',
    difficulty: 'extreme',
    question: 'Who was the only college player on the 1992 Dream Team?',
    options: ['Shaquille O’Neal', 'Alonzo Mourning', 'Grant Hill', 'Christian Laettner'],
    correctIndex: 3,
    explanation: 'The Duke forward, the best college player of 1991-92, completed a roster of eleven NBA stars.',
    sourceUrl: 'https://web.archive.org/web/2012id_/http://www.usab.com/mens/national/moly_1992.html',
    sourceLabel: 'USA Basketball (archived): 1992 Olympic Games',
  },
  {
    id: 'bk052',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'Olympic basketball',
    difficulty: 'extreme',
    question: 'Who coached the 1972 USA team that voted unanimously to refuse its silver medals?',
    options: ['Henry Iba', 'Dean Smith', 'Bob Knight', 'John Thompson'],
    correctIndex: 0,
    explanation: 'The defeat ended a 63-game Olympic winning streak and a run of seven straight golds; the US protest was rejected by FIBA.',
    sourceUrl: 'https://web.archive.org/web/2013id_/http://www.usab.com/mens/national/moly_1972.html',
    sourceLabel: 'USA Basketball (archived): 1972 Olympic Games',
  },
  {
    id: 'bk053',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'Olympic basketball',
    difficulty: 'extreme',
    question: 'Which country beat John Thompson’s USA 82-76 in the 1988 Seoul semifinal, the last Olympics before NBA players?',
    options: ['Yugoslavia', 'Soviet Union', 'Australia', 'Brazil'],
    correctIndex: 1,
    explanation: 'The Soviets took gold, Yugoslavia silver and the USA bronze; four years later the Dream Team arrived.',
    sourceUrl: 'https://web.archive.org/web/2012id_/http://www.usab.com/mens/national/moly_1988.html',
    sourceLabel: 'USA Basketball (archived): 1988 Olympic Games',
  },
  {
    id: 'bk054',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'FIBA World Cup',
    difficulty: 'extreme',
    question: 'In what position did the USA finish at the 2019 FIBA World Cup?',
    options: ['4th', '5th', '9th', '7th'],
    correctIndex: 3,
    explanation: 'Australia, Serbia and the Czech Republic all placed above a US squad missing most of its stars.',
    sourceUrl: 'https://www.fiba.basketball/basketballworldcup/2019',
    sourceLabel: 'FIBA: Basketball World Cup 2019',
  },
  {
    id: 'bk055',
    domain: 'sports',
    region: 'Global',
    topic: 'Basketball',
    subtopic: 'FIBA World Cup',
    difficulty: 'extreme',
    question: 'Which country hosted and won the first FIBA World Championship in 1950?',
    options: ['Brazil', 'Argentina', 'USA', 'Uruguay'],
    correctIndex: 1,
    explanation: 'The USA finished second and Chile third; Argentina would not win the event again.',
    sourceUrl: 'https://www.fiba.basketball/en/history/201-fiba-basketball-world-cup',
    sourceLabel: 'FIBA: Basketball World Cup editions',
  },
  {
    id: 'bk056',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'WNBA',
    difficulty: 'extreme',
    question: 'Who was MVP of the first WNBA All-Star Game, played in New York in 1999?',
    options: ['Tina Thompson', 'Cynthia Cooper', 'Teresa Weatherspoon', 'Lisa Leslie'],
    correctIndex: 3,
    explanation: 'The West won 79-61; Leslie won the honour again in 2001 and 2002.',
    sourceUrl: 'https://www.wnba.com/all-time-wnba-all-star-game-results/',
    sourceLabel: 'WNBA: All-Time All-Star Game results',
  },
  {
    id: 'bk057',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'WNBA',
    difficulty: 'extreme',
    question: 'Which franchise won its only WNBA title in 2005, the first year of the best-of-five Finals?',
    options: ['Sacramento Monarchs', 'Detroit Shock', 'Connecticut Sun', 'Charlotte Sting'],
    correctIndex: 0,
    explanation: 'Yolanda Griffith was Finals MVP as Sacramento beat Connecticut 3-1.',
    sourceUrl: 'https://www.wnba.com/all-time-wnba-champions/',
    sourceLabel: 'WNBA: All-Time WNBA Champions',
  },
  {
    id: 'bk058',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'The 2020 bubble',
    difficulty: 'extreme',
    question: 'Which Pacer scored 53 points against Philadelphia in Indiana’s first game inside the 2020 bubble?',
    options: ['Victor Oladipo', 'T.J. Warren', 'Domantas Sabonis', 'Malcolm Brogdon'],
    correctIndex: 1,
    explanation: 'Warren shot 20-of-29 and 9-of-12 from three in a 127-121 win on 1 August 2020.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/202008010IND.html',
    sourceLabel: 'Basketball-Reference: 76ers vs Pacers, August 1, 2020',
  },
  {
    id: 'bk059',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Jordan’s Bulls',
    difficulty: 'extreme',
    question: 'Which jersey number did Michael Jordan wear on his March 1995 comeback before reverting to 23?',
    options: ['12', '9', '45', '32'],
    correctIndex: 2,
    explanation: 'He had sat out 17 months playing baseball; the switch back to 23 came during that spring’s playoffs.',
    sourceUrl: 'https://www.nba.com/news/history-season-review-1994-95',
    sourceLabel: 'NBA.com: Season Review 1994-95',
  },
  {
    id: 'bk060',
    domain: 'sports',
    region: 'US',
    topic: 'Basketball',
    subtopic: 'Jordan’s Bulls',
    difficulty: 'extreme',
    question: '“The Shot” over Cleveland in 1989 came in Game 5 of the first round at which arena?',
    options: ['Chicago Stadium', 'Richfield Coliseum', 'Gund Arena', 'Cleveland Arena'],
    correctIndex: 1,
    explanation: 'Jordan scored 44 in the 101-100 win on 7 May 1989 at the Coliseum in Richfield, Ohio.',
    sourceUrl: 'https://www.basketball-reference.com/boxscores/198905070CLE.html',
    sourceLabel: 'Basketball-Reference: 1989 East first round Game 5 box score',
  },
]);
