// Server-only editorial bank: Indian cricket, tranche 7 (cr400-cr449): 2020 to 2026.
// Never import this module from client components.
// Every fact below was checked against the page at sourceUrl when written.
export const CRICKET_INDIA_7 = Object.freeze([
  // ------------------------------------------------ Adelaide 2020 and the Gabba
  {
    id: 'cr400',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Adelaide 36 all out',
    difficulty: 'simple',
    question:
      'For how many runs were India bowled out in their second innings of the day-night Adelaide Test in December 2020, their lowest total in Test cricket?',
    options: ['36', '42', '47', '58'],
    correctIndex: 0,
    explanation:
      'No Indian batsman reached double figures, a first in Test history, and Australia chased the small target to win by eight wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2020%E2%80%9321',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2020-21',
  },
  {
    id: 'cr401',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Adelaide 36 all out',
    difficulty: 'extreme',
    question: 'Which Australian bowler took 5 for 8 as India collapsed to 36 all out at Adelaide in December 2020?',
    options: ['Pat Cummins', 'Josh Hazlewood', 'Mitchell Starc', 'Nathan Lyon'],
    correctIndex: 1,
    explanation:
      'Australia went 1-0 up, yet India won the series 2-1 and Pat Cummins was still named player of the series.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2020%E2%80%9321',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2020-21',
  },
  {
    id: 'cr402',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Gabba 2021',
    difficulty: 'simple',
    question:
      'Who captained India in the last three Tests of the 2020-21 series in Australia after Virat Kohli returned home on paternity leave?',
    options: ['Rohit Sharma', 'Cheteshwar Pujara', 'Ajinkya Rahane', 'KL Rahul'],
    correctIndex: 2,
    explanation:
      'Rahane also made 112 in the Boxing Day Test at Melbourne, which India won by eight wickets to level the series.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2020%E2%80%9321',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2020-21',
  },
  {
    id: 'cr403',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Gabba 2021',
    difficulty: 'simple',
    question: 'Who was unbeaten on 89 when India completed the 328-run chase to win the Gabba Test in January 2021?',
    options: ['Shubman Gill', 'Cheteshwar Pujara', 'Washington Sundar', 'Rishabh Pant'],
    correctIndex: 3,
    explanation:
      'Pant faced 138 balls and sealed the win with a boundary to long-off; it was the first Test Australia had lost at the Gabba since 1988.',
    sourceUrl:
      'https://www.cricket.com.au/news/match-report/australia-india-day-five-fourth-test-gabba-brisbane-scorecard-highlights-live-weather-updates/2021-01-19',
    sourceLabel: 'cricket.com.au: Indian summer, Gabba streak ends with classic Test win',
  },
  {
    id: 'cr404',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Gabba 2021',
    difficulty: 'expert',
    question:
      "Who took 5 for 73 in Australia's second innings at the Gabba in January 2021, his first five-wicket haul in Tests?",
    options: ['Mohammed Siraj', 'Shardul Thakur', 'T Natarajan', 'Navdeep Saini'],
    correctIndex: 0,
    explanation:
      'Natarajan and Washington Sundar were both making their Test debuts in that match, with Bumrah, Ashwin and Jadeja all injured.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2020%E2%80%9321',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2020-21',
  },
  // ------------------------------------------------ WTC finals 2021 and 2023
  {
    id: 'cr405',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'WTC final 2021',
    difficulty: 'simple',
    question: 'Which team beat India in the inaugural World Test Championship final at Southampton in June 2021?',
    options: ['Australia', 'New Zealand', 'England', 'South Africa'],
    correctIndex: 1,
    explanation:
      'The match went into its reserve sixth day; Kane Williamson and Ross Taylor were unbeaten as the target of 139 was reached for two wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2021_ICC_World_Test_Championship_final',
    sourceLabel: 'Wikipedia: 2021 ICC World Test Championship final',
  },
  {
    id: 'cr406',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'WTC final 2021',
    difficulty: 'expert',
    question:
      "Who was player of the match in the 2021 World Test Championship final after taking 5 for 31 in India's first innings?",
    options: ['Trent Boult', 'Tim Southee', 'Kyle Jamieson', 'Neil Wagner'],
    correctIndex: 2,
    explanation: 'Jamieson took seven wickets in the match as India were bowled out for 217 and 170.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2021_ICC_World_Test_Championship_final',
    sourceLabel: 'Wikipedia: 2021 ICC World Test Championship final',
  },
  {
    id: 'cr407',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'WTC final 2023',
    difficulty: 'simple',
    question: 'At which ground did India lose the 2023 World Test Championship final to Australia?',
    options: ["Lord's", 'Edgbaston', 'Southampton', 'The Oval'],
    correctIndex: 3,
    explanation: 'Australia won by 209 runs in June 2023 to claim their first World Test Championship title.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_ICC_World_Test_Championship_final',
    sourceLabel: 'Wikipedia: 2023 ICC World Test Championship final',
  },
  {
    id: 'cr408',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'WTC final 2023',
    difficulty: 'expert',
    question:
      'Which Australian scored 163 in the first innings of the 2023 World Test Championship final and was named player of the match?',
    options: ['Travis Head', 'Steven Smith', 'Marnus Labuschagne', 'Alex Carey'],
    correctIndex: 0,
    explanation: 'Steven Smith made 121 in the same innings; Ajinkya Rahane top-scored for India with 89.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_ICC_World_Test_Championship_final',
    sourceLabel: 'Wikipedia: 2023 ICC World Test Championship final',
  },
  {
    id: 'cr409',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'WTC final 2023',
    difficulty: 'extreme',
    question: 'By what margin did Australia win the 2023 World Test Championship final at The Oval?',
    options: ['143 runs', '209 runs', '254 runs', '312 runs'],
    correctIndex: 1,
    explanation: 'India were set 444 and bowled out for 234 on the final day, with Nathan Lyon taking 4 for 41.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_ICC_World_Test_Championship_final',
    sourceLabel: 'Wikipedia: 2023 ICC World Test Championship final',
  },
  // ------------------------------------------------ England 2021 and the Manchester Test
  {
    id: 'cr410',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England tour 2021',
    difficulty: 'simple',
    question:
      "At which ground was the fifth Test between England and India in September 2021 called off before a ball was bowled, after COVID-19 cases in India's camp?",
    options: ["Lord's", 'Headingley', 'Old Trafford', 'The Oval'],
    correctIndex: 2,
    explanation:
      'The match was rescheduled for Edgbaston in July 2022, where England won by seven wickets and the series finished 2-2.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_2021',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 2021',
  },
  {
    id: 'cr411',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England tour 2021',
    difficulty: 'expert',
    question: 'Who captained India in the rescheduled fifth Test at Edgbaston in July 2022, his first Test as captain?',
    options: ['KL Rahul', 'Rishabh Pant', 'Virat Kohli', 'Jasprit Bumrah'],
    correctIndex: 3,
    explanation:
      "England chased 378, their highest successful run chase in Tests, with Jonny Bairstow making 106 and Joe Root 142 not out.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_2021',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 2021',
  },
  // ------------------------------------------------ 2022 T20 World Cup
  {
    id: 'cr412',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'T20 World Cup 2022',
    difficulty: 'simple',
    question:
      "What was Virat Kohli's unbeaten score against Pakistan at the MCG in the 2022 T20 World Cup, in front of more than 90,000 spectators?",
    options: ['82', '76', '92', '67'],
    correctIndex: 0,
    explanation:
      'India were 31 for 4 before Kohli and Hardik Pandya added 113, and they won by four wickets off the final ball.',
    sourceUrl:
      'https://www.skysports.com/cricket/news/12344/12728468/virat-kohli-stands-tall-as-kingpin-after-india-vs-pakistan-t20-world-cup-game-that-had-everything',
    sourceLabel: 'Sky Sports: Virat Kohli stands tall as kingpin after India vs Pakistan T20 World Cup game',
  },
  {
    id: 'cr413',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'T20 World Cup 2022',
    difficulty: 'extreme',
    question: 'How many balls did Virat Kohli face for his 82 not out against Pakistan at the MCG in October 2022?',
    options: ['48', '53', '58', '61'],
    correctIndex: 1,
    explanation:
      'His sixes off Haris Rauf late in the chase cut the requirement from 48 off three overs to 16 off the last, in front of more than 90,000 people.',
    sourceUrl:
      'https://www.skysports.com/cricket/news/12344/12728468/virat-kohli-stands-tall-as-kingpin-after-india-vs-pakistan-t20-world-cup-game-that-had-everything',
    sourceLabel: 'Sky Sports: Virat Kohli stands tall as kingpin after India vs Pakistan T20 World Cup game',
  },
  {
    id: 'cr414',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'T20 World Cup 2022',
    difficulty: 'expert',
    question:
      'Which Pakistan bowler delivered the final over against India at the MCG in 2022, including the waist-high full toss that was called a no-ball after Kohli hit it for six?',
    options: ['Haris Rauf', 'Shaheen Shah Afridi', 'Mohammad Nawaz', 'Naseem Shah'],
    correctIndex: 2,
    explanation:
      'On the free hit that followed, Kohli was bowled but India ran three byes; the over took more than 12 minutes to complete.',
    sourceUrl:
      'https://www.cricket.com.au/news/rules-explainer-india-pakistan-t20-world-cup-final-over-waist-dead-ball-free-hit-nawaz-kohli-ashwin/2022-10-24',
    sourceLabel: 'cricket.com.au: No ball, free hit explained, the rules that sealed Indian victory',
  },
  {
    id: 'cr415',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'T20 World Cup 2022',
    difficulty: 'extreme',
    question: "Who scored the winning run off the last ball of India's 2022 T20 World Cup match against Pakistan at the MCG?",
    options: ['Dinesh Karthik', 'Hardik Pandya', 'Axar Patel', 'Ravichandran Ashwin'],
    correctIndex: 3,
    explanation:
      'Ashwin bunted the ball over mid-off after Karthik had been stumped by Mohammad Rizwan; umpire Marais Erasmus had called the no-ball two deliveries earlier.',
    sourceUrl:
      'https://www.cricket.com.au/news/rules-explainer-india-pakistan-t20-world-cup-final-over-waist-dead-ball-free-hit-nawaz-kohli-ashwin/2022-10-24',
    sourceLabel: 'cricket.com.au: No ball, free hit explained, the rules that sealed Indian victory',
  },
  // ------------------------------------------------ Rohit Sharma, all-format captain
  {
    id: 'cr416',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Rohit Sharma captaincy',
    difficulty: 'expert',
    question:
      "In which month was Rohit Sharma appointed India's Test captain, completing his hold on all three formats after Virat Kohli resigned?",
    options: ['February 2022', 'November 2021', 'December 2021', 'July 2022'],
    correctIndex: 0,
    explanation:
      'He had taken over the T20I captaincy in November 2021 and the ODI captaincy in December 2021.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Rohit_Sharma',
    sourceLabel: 'Wikipedia: Rohit Sharma',
  },
  // ------------------------------------------------ 2023 ODI World Cup
  {
    id: 'cr417',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2023 ODI World Cup',
    difficulty: 'simple',
    question: 'How many matches in a row did India win at the 2023 ODI World Cup before losing the final?',
    options: ['9', '10', '11', '8'],
    correctIndex: 1,
    explanation:
      'Nine group wins and the semi-final against New Zealand; Australia then won the final in Ahmedabad by six wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 2023 Cricket World Cup',
  },
  {
    id: 'cr418',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2023 ODI World Cup',
    difficulty: 'expert',
    question:
      "What were Mohammed Shami's figures in the 2023 World Cup semi-final against New Zealand at the Wankhede, the best by an Indian in ODIs?",
    options: ['5 for 18', '6 for 45', '7 for 57', '5 for 54'],
    correctIndex: 2,
    explanation:
      'Shami only entered the tournament from the fifth match, yet finished as its leading wicket-taker with 24 in seven games.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_Cricket_World_Cup_knockout_stage',
    sourceLabel: 'Wikipedia: 2023 Cricket World Cup knockout stage',
  },
  {
    id: 'cr419',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2023 ODI World Cup',
    difficulty: 'simple',
    question:
      "At which ground did Virat Kohli score his 50th ODI century, passing Sachin Tendulkar's record, in November 2023?",
    options: ['Eden Gardens', 'Narendra Modi Stadium', 'M Chinnaswamy Stadium', 'Wankhede Stadium'],
    correctIndex: 3,
    explanation:
      'Tendulkar watched from the stands as Kohli made 117 in the semi-final against New Zealand.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_Cricket_World_Cup_knockout_stage',
    sourceLabel: 'Wikipedia: 2023 Cricket World Cup knockout stage',
  },
  {
    id: 'cr420',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2023 ODI World Cup',
    difficulty: 'expert',
    question: 'How many runs did Virat Kohli score at the 2023 ODI World Cup, the most by any batter in a single edition?',
    options: ['765', '673', '711', '802'],
    correctIndex: 0,
    explanation: "He passed Sachin Tendulkar's 673 from 2003 and was named player of the tournament.",
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 2023 Cricket World Cup',
  },
  {
    id: 'cr421',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2023 World Cup final',
    difficulty: 'expert',
    question: 'Which Australian batter made 137 in the 2023 World Cup final against India in Ahmedabad?',
    options: ['Marnus Labuschagne', 'Travis Head', 'David Warner', 'Mitchell Marsh'],
    correctIndex: 1,
    explanation:
      'Labuschagne was unbeaten on 58 as Australia reached 241 for 4 in 43 overs to win their sixth World Cup.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_Cricket_World_Cup_final',
    sourceLabel: 'Wikipedia: 2023 Cricket World Cup final',
  },
  {
    id: 'cr422',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2023 ODI World Cup',
    difficulty: 'extreme',
    question:
      "Who scored 105 off 70 balls alongside Kohli's century in India's 397 for 4 in the 2023 World Cup semi-final against New Zealand?",
    options: ['Shubman Gill', 'KL Rahul', 'Shreyas Iyer', 'Rohit Sharma'],
    correctIndex: 2,
    explanation:
      'Daryl Mitchell replied with 134 before New Zealand were bowled out for 327 and India won by 70 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_Cricket_World_Cup_knockout_stage',
    sourceLabel: 'Wikipedia: 2023 Cricket World Cup knockout stage',
  },
  // ------------------------------------------------ 2024 T20 World Cup
  {
    id: 'cr423',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'T20 World Cup 2024',
    difficulty: 'simple',
    question: 'At which ground did India beat South Africa in the 2024 T20 World Cup final?',
    options: ['Sabina Park, Jamaica', "Queen's Park Oval, Trinidad", 'Providence Stadium, Guyana', 'Kensington Oval, Barbados'],
    correctIndex: 3,
    explanation:
      'India defended 176 for 7 on 29 June 2024 to become the first side to win the tournament unbeaten.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2024_ICC_Men%27s_T20_World_Cup_final',
    sourceLabel: "Wikipedia: 2024 ICC Men's T20 World Cup final",
  },
  {
    id: 'cr424',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'T20 World Cup 2024',
    difficulty: 'expert',
    question:
      'What did Virat Kohli score in the 2024 T20 World Cup final against South Africa, hours before announcing his T20I retirement?',
    options: ['76', '59', '82', '47'],
    correctIndex: 0,
    explanation:
      'It came off 59 balls after early wickets had fallen; Axar Patel made 47 and Kohli was player of the match.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2024_ICC_Men%27s_T20_World_Cup_final',
    sourceLabel: "Wikipedia: 2024 ICC Men's T20 World Cup final",
  },
  {
    id: 'cr425',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'T20 World Cup 2024',
    difficulty: 'expert',
    question:
      'Who took the catch on the boundary to dismiss David Miller in the final over of the 2024 T20 World Cup final?',
    options: ['Ravindra Jadeja', 'Suryakumar Yadav', 'Rohit Sharma', 'Arshdeep Singh'],
    correctIndex: 1,
    explanation:
      'The catch was disputed on social media but upheld; Hardik Pandya bowled that over and finished with 3 for 20.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2024_ICC_Men%27s_T20_World_Cup_final',
    sourceLabel: "Wikipedia: 2024 ICC Men's T20 World Cup final",
  },
  {
    id: 'cr426',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'T20 World Cup 2024',
    difficulty: 'expert',
    question: 'Who was player of the tournament at the 2024 T20 World Cup in the West Indies and the United States?',
    options: ['Virat Kohli', 'Arshdeep Singh', 'Jasprit Bumrah', 'Rohit Sharma'],
    correctIndex: 2,
    explanation:
      "Bumrah took 15 wickets at an economy rate of 4.17; Arshdeep's 17 wickets equalled the record for one edition.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Jasprit_Bumrah',
    sourceLabel: 'Wikipedia: Jasprit Bumrah',
  },
  {
    id: 'cr427',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'T20 World Cup 2024',
    difficulty: 'extreme',
    question: 'By how many runs did India beat South Africa in the 2024 T20 World Cup final in Bridgetown?',
    options: ['3', '5', '9', '7'],
    correctIndex: 3,
    explanation:
      'South Africa finished on 169 for 8 chasing 177, with Heinrich Klaasen making 52 off 27 balls and Bumrah taking 2 for 18.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2024_ICC_Men%27s_T20_World_Cup_final',
    sourceLabel: "Wikipedia: 2024 ICC Men's T20 World Cup final",
  },
  // ------------------------------------------------ Coaches
  {
    id: 'cr428',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Gautam Gambhir',
    difficulty: 'expert',
    question: "Who replaced Rahul Dravid as head coach of India's men's team in July 2024?",
    options: ['Gautam Gambhir', 'VVS Laxman', 'Ravi Shastri', 'Ashish Nehra'],
    correctIndex: 0,
    explanation:
      "Dravid signed off with the 2024 T20 World Cup; Gambhir's first assignment was the tour of Sri Lanka and he later won the 2025 Champions Trophy.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Gautam_Gambhir',
    sourceLabel: 'Wikipedia: Gautam Gambhir',
  },
  // ------------------------------------------------ New Zealand whitewash 2024
  {
    id: 'cr429',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'New Zealand whitewash 2024',
    difficulty: 'simple',
    question: 'Which team inflicted a 3-0 home Test series whitewash on India in 2024, the first in their history?',
    options: ['Australia', 'New Zealand', 'England', 'South Africa'],
    correctIndex: 1,
    explanation:
      "It was India's first home series defeat since 2012; Tom Latham captained the visitors and Will Young was player of the series.",
    sourceUrl: 'https://en.wikipedia.org/wiki/New_Zealand_cricket_team_in_India_in_2024%E2%80%9325',
    sourceLabel: 'Wikipedia: New Zealand cricket team in India in 2024-25',
  },
  {
    id: 'cr430',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'New Zealand whitewash 2024',
    difficulty: 'expert',
    question:
      "What was India's first-innings total in the Bengaluru Test against New Zealand in October 2024, their lowest in a home Test?",
    options: ['36', '56', '46', '66'],
    correctIndex: 2,
    explanation:
      'Matt Henry took 5 for 15; Sarfaraz Khan replied with 150 in the second innings but New Zealand still won by eight wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/New_Zealand_cricket_team_in_India_in_2024%E2%80%9325',
    sourceLabel: 'Wikipedia: New Zealand cricket team in India in 2024-25',
  },
  // ------------------------------------------------ Border-Gavaskar Trophy 2024-25
  {
    id: 'cr431',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Ashwin retirement',
    difficulty: 'simple',
    question:
      'In which city did R Ashwin announce his retirement from international cricket in December 2024, midway through the series in Australia?',
    options: ['Perth', 'Adelaide', 'Melbourne', 'Brisbane'],
    correctIndex: 3,
    explanation:
      "He finished with 537 Test wickets from 106 matches, second among Indians to Anil Kumble's 619.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Ravichandran_Ashwin',
    sourceLabel: 'Wikipedia: Ravichandran Ashwin',
  },
  {
    id: 'cr432',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Border-Gavaskar Trophy 2024-25',
    difficulty: 'extreme',
    question:
      'How many wickets did Jasprit Bumrah take in the 2024-25 Border-Gavaskar Trophy, the most by an Indian in an away Test series?',
    options: ['32', '28', '35', '24'],
    correctIndex: 0,
    explanation:
      'They came at an average of 13.06; Australia won 3-1, their first series win over India since 2014-15.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2024%E2%80%9325',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2024-25',
  },
  // ------------------------------------------------ Champions Trophy 2025
  {
    id: 'cr433',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Champions Trophy 2025',
    difficulty: 'simple',
    question: 'Who was player of the match in the 2025 Champions Trophy final against New Zealand in Dubai?',
    options: ['Shreyas Iyer', 'Rohit Sharma', 'KL Rahul', 'Virat Kohli'],
    correctIndex: 1,
    explanation:
      'Rohit made 76 off 83 balls as India chased 252 to win by four wickets and lift the trophy for a third time.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2025_ICC_Champions_Trophy_final',
    sourceLabel: 'Wikipedia: 2025 ICC Champions Trophy final',
  },
  {
    id: 'cr434',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Champions Trophy 2025',
    difficulty: 'extreme',
    question: 'Which India bowler took 5 for 42 against New Zealand in the group stage of the 2025 Champions Trophy?',
    options: ['Kuldeep Yadav', 'Mohammed Shami', 'Varun Chakravarthy', 'Axar Patel'],
    correctIndex: 2,
    explanation:
      "India won that match by 44 runs; all of their games were played in Dubai under the tournament's hybrid hosting model.",
    sourceUrl: 'https://en.wikipedia.org/wiki/2025_ICC_Champions_Trophy',
    sourceLabel: 'Wikipedia: 2025 ICC Champions Trophy',
  },
  // ------------------------------------------------ Test retirements, May 2025
  {
    id: 'cr435',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Rohit Sharma retirement',
    difficulty: 'expert',
    question: 'How many Tests had Rohit Sharma played when he announced his retirement from the format on 7 May 2025?',
    options: ['59', '74', '81', '67'],
    correctIndex: 3,
    explanation: 'He scored 4,301 runs with 12 hundreds and captained India in 24 Tests, announcing the decision on Instagram.',
    sourceUrl: 'https://www.icc-cricket.com/news/india-captain-rohit-sharma-announces-test-retirement',
    sourceLabel: 'ICC: India captain Rohit Sharma announces Test retirement',
  },
  {
    id: 'cr436',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Virat Kohli retirement',
    difficulty: 'extreme',
    question: 'How many Test centuries did Virat Kohli finish with when he retired from the format in May 2025?',
    options: ['30', '27', '33', '36'],
    correctIndex: 0,
    explanation: 'He made 9,230 runs in 123 Tests; his last hundred was 100 not out at Perth in November 2024.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Virat_Kohli',
    sourceLabel: 'Wikipedia: Virat Kohli',
  },
  // ------------------------------------------------ Gill and England 2025
  {
    id: 'cr437',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Shubman Gill captaincy',
    difficulty: 'simple',
    question: "Who was named India's Test captain in May 2025 following Rohit Sharma's retirement?",
    options: ['Jasprit Bumrah', 'Shubman Gill', 'KL Rahul', 'Rishabh Pant'],
    correctIndex: 1,
    explanation: 'Gill was 25 at the appointment; Pant was named his vice-captain for the tour of England.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Shubman_Gill',
    sourceLabel: 'Wikipedia: Shubman Gill',
  },
  {
    id: 'cr438',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England tour 2025',
    difficulty: 'expert',
    question:
      'What did Shubman Gill score in the first innings at Edgbaston in July 2025, the highest Test score by an Indian captain?',
    options: ['221', '254', '269', '287'],
    correctIndex: 2,
    explanation:
      'He added 161 in the second innings for a match aggregate of 430, second only to Graham Gooch, and India won by 336 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Shubman_Gill',
    sourceLabel: 'Wikipedia: Shubman Gill',
  },
  {
    id: 'cr439',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England tour 2025',
    difficulty: 'extreme',
    question: 'How many runs did Shubman Gill score in the five-Test series in England in 2025?',
    options: ['612', '674', '701', '754'],
    correctIndex: 3,
    explanation: 'He made four centuries at an average of 75.40 in his first series as captain.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_2025',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 2025',
  },
  {
    id: 'cr440',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England tour 2025',
    difficulty: 'simple',
    question: "What was the result of India's five-Test series in England in 2025, the first Anderson-Tendulkar Trophy?",
    options: ['Drawn 2-2', 'England won 3-2', 'India won 3-2', 'Drawn 1-1'],
    correctIndex: 0,
    explanation: 'India won the final Test at The Oval by six runs to square the series after losing at Headingley and Lord\'s.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_2025',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 2025',
  },
  {
    id: 'cr441',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England tour 2025',
    difficulty: 'extreme',
    question: 'By how many runs did India win the fifth Test at The Oval in 2025, their narrowest victory in Test cricket?',
    options: ['4', '6', '9', '12'],
    correctIndex: 1,
    explanation: 'Mohammed Siraj took 5 for 104 and Yashasvi Jaiswal made 118 in that match; Chris Woakes played his last Test.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_2025',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 2025',
  },
  // ------------------------------------------------ 2026 T20 World Cup at home
  {
    id: 'cr442',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'T20 World Cup 2026',
    difficulty: 'extreme',
    question: 'By how many runs did India beat New Zealand in the 2026 T20 World Cup final in Ahmedabad?',
    options: ['72', '84', '96', '108'],
    correctIndex: 2,
    explanation:
      'India made 255 for 5, the highest total in a T20 World Cup final, and New Zealand were bowled out for 159 on 8 March 2026.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2026_Men%27s_T20_World_Cup_final',
    sourceLabel: "Wikipedia: 2026 Men's T20 World Cup final",
  },
  {
    id: 'cr443',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'T20 World Cup 2026',
    difficulty: 'simple',
    question: 'Who was player of the tournament at the 2026 T20 World Cup, which India won at home?',
    options: ['Abhishek Sharma', 'Jasprit Bumrah', 'Ishan Kishan', 'Sanju Samson'],
    correctIndex: 3,
    explanation:
      "Samson's 89 off 46 balls in the final is the highest individual score in a men's T20 World Cup final.",
    sourceUrl: 'https://en.wikipedia.org/wiki/2026_Men%27s_T20_World_Cup',
    sourceLabel: "Wikipedia: 2026 Men's T20 World Cup",
  },
  {
    id: 'cr444',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'T20 World Cup 2026',
    difficulty: 'extreme',
    question: 'Who took 4 for 15 as New Zealand were bowled out for 159 in the 2026 T20 World Cup final?',
    options: ['Jasprit Bumrah', 'Axar Patel', 'Varun Chakravarthy', 'Hardik Pandya'],
    correctIndex: 0,
    explanation:
      'Suryakumar Yadav captained India, the first host nation to win the tournament and the first team to defend the title.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2026_Men%27s_T20_World_Cup_final',
    sourceLabel: "Wikipedia: 2026 Men's T20 World Cup final",
  },
  // ------------------------------------------------ England in India 2024 and Jaiswal
  {
    id: 'cr445',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Yashasvi Jaiswal',
    difficulty: 'extreme',
    question:
      'At which venue did Yashasvi Jaiswal score 214 not out against England in February 2024, his second double century in successive Tests?',
    options: ['Visakhapatnam', 'Rajkot', 'Ranchi', 'Dharamsala'],
    correctIndex: 1,
    explanation:
      "India won by 434 runs, their biggest Test win by a runs margin, and Jaiswal hit 12 sixes in the innings to equal Wasim Akram's record.",
    sourceUrl: 'https://en.wikipedia.org/wiki/English_cricket_team_in_India_in_2023%E2%80%9324',
    sourceLabel: 'Wikipedia: English cricket team in India in 2023-24',
  },
  {
    id: 'cr446',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England in India 2024',
    difficulty: 'simple',
    question: "What was the result of India's five-Test home series against England in early 2024?",
    options: ['India won 3-2', 'India won 3-1', 'India won 4-1', 'Drawn 2-2'],
    correctIndex: 2,
    explanation:
      'England won the opening Test at Hyderabad before India took the next four, finishing with an innings win at Dharamsala.',
    sourceUrl: 'https://en.wikipedia.org/wiki/English_cricket_team_in_India_in_2023%E2%80%9324',
    sourceLabel: 'Wikipedia: English cricket team in India in 2023-24',
  },
  {
    id: 'cr447',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England in India 2024',
    difficulty: 'extreme',
    question: 'By how many runs did England win the first Test at Hyderabad in January 2024?',
    options: ['12', '18', '36', '28'],
    correctIndex: 3,
    explanation: 'Ollie Pope made 196 in the second innings and debutant Tom Hartley took 7 for 62.',
    sourceUrl: 'https://en.wikipedia.org/wiki/English_cricket_team_in_India_in_2023%E2%80%9324',
    sourceLabel: 'Wikipedia: English cricket team in India in 2023-24',
  },
  {
    id: 'cr448',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Yashasvi Jaiswal',
    difficulty: 'extreme',
    question:
      'How many runs did Yashasvi Jaiswal score in the 2024 home series against England, when he was named player of the series?',
    options: ['712', '655', '688', '740'],
    correctIndex: 0,
    explanation: 'His 209 at Visakhapatnam and 214 not out at Rajkot came in consecutive Tests.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Yashasvi_Jaiswal',
    sourceLabel: 'Wikipedia: Yashasvi Jaiswal',
  },
  {
    id: 'cr449',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England in India 2024',
    difficulty: 'expert',
    question: 'At which venue did R Ashwin take his 500th Test wicket, against England in February 2024?',
    options: ['Hyderabad', 'Rajkot', 'Visakhapatnam', 'Dharamsala'],
    correctIndex: 1,
    explanation:
      'He became the second Indian after Anil Kumble to reach 500, and played his 100th Test at Dharamsala later in the same series.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ravichandran_Ashwin',
    sourceLabel: 'Wikipedia: Ravichandran Ashwin',
  },
]);
