// Server-only editorial bank: Indian cricket, tranche 5 — the Dhoni era, 2008 to 2013 (50 questions).
// Never import this module from client components.
// Every fact below was checked against the page at sourceUrl when written.
export const CRICKET_INDIA_5 = Object.freeze([
  // ---------------------------------------------------------------- Sydney 2008
  {
    id: 'cr300',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sydney 2008',
    difficulty: 'simple',
    question:
      'Harbhajan Singh was charged with racially abusing which Australian all-rounder during the January 2008 Sydney Test?',
    options: ['Michael Clarke', 'Matthew Hayden', 'Andrew Symonds', 'Brad Hogg'],
    correctIndex: 2,
    explanation:
      'Symonds made an unbeaten 162 in that Test, which Australia won by 122 runs with seven balls to spare.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2007%E2%80%9308',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2007–08',
  },
  {
    id: 'cr301',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sydney 2008',
    difficulty: 'expert',
    question:
      'Which ICC match referee handed Harbhajan Singh the initial three-Test ban after the 2008 Sydney hearing?',
    options: ['Mike Procter', 'Chris Broad', 'Ranjan Madugalle', 'Roshan Mahanama'],
    correctIndex: 0,
    explanation:
      'The BCCI considered pulling out of the tour, and the ban was later overturned on appeal and replaced by a fine.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2007%E2%80%9308',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2007–08',
  },
  {
    id: 'cr302',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sydney 2008',
    difficulty: 'extreme',
    question:
      "Which New Zealand judge heard Harbhajan Singh's appeal in 2008 and reduced the racial-abuse charge to one of abusive language?",
    options: ['Justice Albie Sachs', 'Justice Michael Beloff', 'Justice Mukul Mudgal', 'Justice John Hansen'],
    correctIndex: 3,
    explanation: 'Harbhajan was fined 50 per cent of his match fee under the lesser charge and the three-Test ban was rescinded.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2007%E2%80%9308',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2007–08',
  },
  {
    id: 'cr303',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sydney 2008',
    difficulty: 'extreme',
    question:
      'After BCCI complaints about the Sydney Test of 2008, which umpire was stood down and replaced by Billy Bowden for the Perth Test?',
    options: ['Mark Benson', 'Steve Bucknor', 'Rudi Koertzen', 'Asad Rauf'],
    correctIndex: 1,
    explanation:
      "Among the disputed calls, Bucknor gave Dravid out caught behind on the final day when replays showed the ball brushed only his pad.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2007%E2%80%9308',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2007–08',
  },
  // ---------------------------------------------------------------- Perth 2008
  {
    id: 'cr304',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Perth 2008',
    difficulty: 'simple',
    question:
      "India's 72-run win at the WACA in January 2008 ended an Australian run of how many consecutive Test victories?",
    options: ['12', '16', '19', '21'],
    correctIndex: 1,
    explanation: 'The Sydney win a fortnight earlier had equalled the record set by Steve Waugh\'s side in 2001.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2007%E2%80%9308',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2007–08',
  },
  {
    id: 'cr305',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Perth 2008',
    difficulty: 'expert',
    question: 'Who was named man of the match when India beat Australia at Perth in January 2008?',
    options: ['Irfan Pathan', 'RP Singh', 'VVS Laxman', 'Rahul Dravid'],
    correctIndex: 0,
    explanation: 'Pathan took 3 for 54 and also opened the batting; Dravid top-scored in the match with 93.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2007%E2%80%9308',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2007–08',
  },
  {
    id: 'cr306',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Perth 2008',
    difficulty: 'extreme',
    question:
      "Which senior player urged Anil Kumble to give the 19-year-old Ishant Sharma one more over at Ricky Ponting in the famous Perth spell of 2008?",
    options: ['Sachin Tendulkar', 'Rahul Dravid', 'VVS Laxman', 'Virender Sehwag'],
    correctIndex: 3,
    explanation:
      "Kumble was picked up by the stump microphone asking 'ek aur daalega'; Ponting fended the next over to Dravid at first slip.",
    sourceUrl: 'https://scroll.in/field/905628/watch-when-a-19-year-old-ishant-sharma-tormented-ricky-ponting-at-perth-in-2008',
    sourceLabel: 'Scroll.in: When a 19-year-old Ishant Sharma tormented Ricky Ponting at Perth in 2008',
  },
  // ---------------------------------------------------------------- CB Series 2008
  {
    id: 'cr307',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2008 CB Series',
    difficulty: 'simple',
    question:
      'Who made an unbeaten 117 in the first final of the 2008 Commonwealth Bank Series at the SCG to set up India\'s 2-0 finals win over Australia?',
    options: ['Gautam Gambhir', 'MS Dhoni', 'Sachin Tendulkar', 'Rohit Sharma'],
    correctIndex: 2,
    explanation: 'India chased 240 with six wickets in hand, and Tendulkar followed up with 91 in the second final at Brisbane.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2007%E2%80%9308_Commonwealth_Bank_Series',
    sourceLabel: 'Wikipedia: 2007–08 Commonwealth Bank Series',
  },
  {
    id: 'cr308',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2008 CB Series',
    difficulty: 'extreme',
    question:
      'Which Indian seamer took 4 for 46 and was player of the match in the second final of the 2008 CB Series at the Gabba?',
    options: ['Ishant Sharma', 'Praveen Kumar', 'Sreesanth', 'Munaf Patel'],
    correctIndex: 1,
    explanation: 'India defended 258 to win by nine runs; Nathan Bracken took 21 wickets and was player of the series.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2007%E2%80%9308_Commonwealth_Bank_Series',
    sourceLabel: 'Wikipedia: 2007–08 Commonwealth Bank Series',
  },
  // ---------------------------------------------------------------- Kumble and Ganguly bow out
  {
    id: 'cr309',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Kumble retires',
    difficulty: 'expert',
    question: 'At which ground did Anil Kumble announce his retirement on 2 November 2008, during the third Test against Australia?',
    options: ['Eden Gardens, Kolkata', 'Chinnaswamy Stadium, Bangalore', 'Wankhede Stadium, Mumbai', 'Feroz Shah Kotla, Delhi'],
    correctIndex: 3,
    explanation: 'It was the same ground where he had taken 10 for 74 against Pakistan in February 1999.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Anil_Kumble',
    sourceLabel: 'Wikipedia: Anil Kumble',
  },
  {
    id: 'cr310',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Ganguly farewell',
    difficulty: 'expert',
    question: 'How many runs did Sourav Ganguly make in the last innings of his Test career, at Nagpur in November 2008?',
    options: ['0', '27', '85', '102'],
    correctIndex: 0,
    explanation: 'He had made 85 in the first innings and finished his final series with 324 runs at an average of 54.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sourav_Ganguly',
    sourceLabel: 'Wikipedia: Sourav Ganguly',
  },
  {
    id: 'cr311',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Ganguly farewell',
    difficulty: 'extreme',
    question:
      'In the closing stages of the Nagpur Test of November 2008, captain MS Dhoni handed on-field leadership to which retiring player?',
    options: ['Anil Kumble', 'VVS Laxman', 'Sourav Ganguly', 'Rahul Dravid'],
    correctIndex: 2,
    explanation: 'India won by 172 runs to take the series 2-0 and regain the Border-Gavaskar Trophy.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sourav_Ganguly',
    sourceLabel: 'Wikipedia: Sourav Ganguly',
  },
  {
    id: 'cr312',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Dhoni Test captain',
    difficulty: 'extreme',
    question:
      'MS Dhoni first captained India in a Test as a stand-in for the injured Anil Kumble in April 2008 at which venue?',
    options: ['Chennai', 'Ahmedabad', 'Kanpur', 'Mohali'],
    correctIndex: 2,
    explanation: 'India beat South Africa by eight wickets to level that series 1-1, with Ganguly player of the match for his 87.',
    sourceUrl: 'https://en.wikipedia.org/wiki/South_African_cricket_team_in_India_in_2007%E2%80%9308',
    sourceLabel: 'Wikipedia: South African cricket team in India in 2007–08',
  },
  // ---------------------------------------------------------------- Brabourne 2009 and No.1
  {
    id: 'cr313',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sehwag 293',
    difficulty: 'simple',
    question: "Virender Sehwag's 293 at the Brabourne Stadium in December 2009 came against which opponent?",
    options: ['Australia', 'Sri Lanka', 'South Africa', 'New Zealand'],
    correctIndex: 1,
    explanation: 'He faced 254 balls and India won the Test by an innings and 24 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sri_Lankan_cricket_team_in_India_in_2009%E2%80%9310',
    sourceLabel: 'Wikipedia: Sri Lankan cricket team in India in 2009–10',
  },
  {
    id: 'cr314',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sehwag 293',
    difficulty: 'extreme',
    question: 'Which bowler ended Sehwag\'s innings of 293 at the Brabourne Stadium, seven runs short of a third Test triple century?',
    options: ['Rangana Herath', 'Chanaka Welegedara', 'Nuwan Kulasekara', 'Muttiah Muralitharan'],
    correctIndex: 3,
    explanation: 'Sehwag was caught and bowled; the innings included 40 fours and seven sixes.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Virender_Sehwag',
    sourceLabel: 'Wikipedia: Virender Sehwag',
  },
  {
    id: 'cr315',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Test No.1',
    difficulty: 'simple',
    question: 'In which year did India reach No.1 in the ICC Test rankings for the first time?',
    options: ['2009', '2007', '2011', '2013'],
    correctIndex: 0,
    explanation: 'The 2-0 home series win over Sri Lanka in December 2009 took India to the top under MS Dhoni.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sri_Lankan_cricket_team_in_India_in_2009%E2%80%9310',
    sourceLabel: 'Wikipedia: Sri Lankan cricket team in India in 2009–10',
  },
  // ---------------------------------------------------------------- Gwalior 2010
  {
    id: 'cr316',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Tendulkar 200',
    difficulty: 'simple',
    question: 'Where did Sachin Tendulkar score the first double century in men\'s one-day internationals on 24 February 2010?',
    options: ['Hyderabad', 'Jaipur', 'Gwalior', 'Nagpur'],
    correctIndex: 2,
    explanation: 'India made 401 for 3 against South Africa and won by 153 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/South_African_cricket_team_in_India_in_2009%E2%80%9310',
    sourceLabel: 'Wikipedia: South African cricket team in India in 2009–10',
  },
  {
    id: 'cr317',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Tendulkar 200',
    difficulty: 'expert',
    question: "How many balls did Tendulkar face for his unbeaten 200 against South Africa in 2010?",
    options: ['131', '147', '158', '163'],
    correctIndex: 1,
    explanation: 'He beat the previous ODI record of 194 shared by Saeed Anwar and Charles Coventry.',
    sourceUrl: 'https://en.wikipedia.org/wiki/South_African_cricket_team_in_India_in_2009%E2%80%9310',
    sourceLabel: 'Wikipedia: South African cricket team in India in 2009–10',
  },
  // ---------------------------------------------------------------- 2011 World Cup
  {
    id: 'cr318',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2011 World Cup',
    difficulty: 'simple',
    question: 'India tied a 2011 World Cup group match at Bangalore, with both sides making 338, against which team?',
    options: ['South Africa', 'West Indies', 'Australia', 'England'],
    correctIndex: 3,
    explanation: 'Tendulkar made 120 and Graeme Swann took a single off the last ball from Munaf Patel to level the scores.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2011_Cricket_World_Cup_Group_B',
    sourceLabel: 'Wikipedia: 2011 Cricket World Cup Group B',
  },
  {
    id: 'cr319',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2011 World Cup',
    difficulty: 'expert',
    question: 'Which England batsman made 158 in the tied 2011 World Cup match against India at Bangalore?',
    options: ['Kevin Pietersen', 'Ian Bell', 'Andrew Strauss', 'Jonathan Trott'],
    correctIndex: 2,
    explanation: 'It was his highest ODI score; Tim Bresnan took 5 for 48 for England earlier in the day.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2011_Cricket_World_Cup_Group_B',
    sourceLabel: 'Wikipedia: 2011 Cricket World Cup Group B',
  },
  {
    id: 'cr320',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2011 World Cup',
    difficulty: 'simple',
    question: "Who scored a century on his World Cup debut in India's 2011 tournament opener against Bangladesh?",
    options: ['Virat Kohli', 'Suresh Raina', 'Yuvraj Singh', 'Gautam Gambhir'],
    correctIndex: 0,
    explanation: 'Sehwag made 175 in the same innings as India piled up 370 for 4 and won by 87 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2011_Cricket_World_Cup_Group_B',
    sourceLabel: 'Wikipedia: 2011 Cricket World Cup Group B',
  },
  {
    id: 'cr321',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2011 World Cup',
    difficulty: 'expert',
    question: 'Which Australian made 104 against India in the 2011 World Cup quarter-final at Ahmedabad?',
    options: ['Michael Clarke', 'Brad Haddin', 'Shane Watson', 'Ricky Ponting'],
    correctIndex: 3,
    explanation: 'India chased 261 with five wickets in hand; Yuvraj Singh made 57 not out and was man of the match.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2011_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 2011 Cricket World Cup',
  },
  {
    id: 'cr322',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2011 World Cup',
    difficulty: 'simple',
    question: 'Where was the 2011 World Cup semi-final between India and Pakistan played on 30 March 2011?',
    options: ['Nagpur', 'Mohali', 'Delhi', 'Chennai'],
    correctIndex: 1,
    explanation: 'India won by 29 runs, watched by prime ministers Manmohan Singh and Yousaf Raza Gilani.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2011_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 2011 Cricket World Cup',
  },
  {
    id: 'cr323',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2011 World Cup',
    difficulty: 'expert',
    question: 'Which Pakistan bowler took 5 for 46 against India in the 2011 World Cup semi-final?',
    options: ['Wahab Riaz', 'Umar Gul', 'Saeed Ajmal', 'Shahid Afridi'],
    correctIndex: 0,
    explanation: 'Tendulkar was let off repeatedly on his way to 85, and Pakistan were bowled out for 231 chasing 261.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2011_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 2011 Cricket World Cup',
  },
  {
    id: 'cr324',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2011 World Cup final',
    difficulty: 'simple',
    question: 'How many runs did Gautam Gambhir make in the 2011 World Cup final at the Wankhede Stadium?',
    options: ['85', '91', '97', '103'],
    correctIndex: 2,
    explanation: 'He was bowled by Thisara Perera in the 42nd over after adding 109 with Dhoni for the fourth wicket.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2011_Cricket_World_Cup_final',
    sourceLabel: 'Wikipedia: 2011 Cricket World Cup final',
  },
  {
    id: 'cr325',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2011 World Cup final',
    difficulty: 'expert',
    question: 'Which Sri Lankan bowled the ball that MS Dhoni hit for six to win the 2011 World Cup final?',
    options: ['Lasith Malinga', 'Nuwan Kulasekara', 'Thisara Perera', 'Suraj Randiv'],
    correctIndex: 1,
    explanation: 'India finished on 277 for 4 in 48.2 overs, chasing 275 after Mahela Jayawardene\'s unbeaten 103.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2011_Cricket_World_Cup_final',
    sourceLabel: 'Wikipedia: 2011 Cricket World Cup final',
  },
  {
    id: 'cr326',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2011 World Cup final',
    difficulty: 'extreme',
    question: 'From how many balls did MS Dhoni make his unbeaten 91 in the 2011 World Cup final?',
    options: ['64', '72', '86', '79'],
    correctIndex: 3,
    explanation: 'Dhoni had promoted himself above Yuvraj Singh and was named man of the match.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2011_Cricket_World_Cup_final',
    sourceLabel: 'Wikipedia: 2011 Cricket World Cup final',
  },
  {
    id: 'cr327',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2011 World Cup',
    difficulty: 'simple',
    question: 'Who was named player of the tournament at the 2011 World Cup after scoring 362 runs and taking 15 wickets?',
    options: ['Yuvraj Singh', 'Sachin Tendulkar', 'Zaheer Khan', 'Tillakaratne Dilshan'],
    correctIndex: 0,
    explanation: 'He won four man-of-the-match awards, and was diagnosed with cancer soon after the tournament.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Yuvraj_Singh',
    sourceLabel: 'Wikipedia: Yuvraj Singh',
  },
  // ---------------------------------------------------------------- England 2011
  {
    id: 'cr328',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England 2011',
    difficulty: 'simple',
    question: 'Which Indian batsman scored three centuries during the 4-0 Test series defeat in England in 2011?',
    options: ['Sachin Tendulkar', 'Rahul Dravid', 'VVS Laxman', 'Gautam Gambhir'],
    correctIndex: 1,
    explanation: 'He made 461 runs in the series; England replaced India at No.1 in the Test rankings as a result of the whitewash.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_2011',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 2011',
  },
  {
    id: 'cr329',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England 2011',
    difficulty: 'expert',
    question: 'At which ground did Rahul Dravid carry his bat for 146 not out in the 2011 series in England?',
    options: ["Lord's", 'Trent Bridge', 'The Oval', 'Edgbaston'],
    correctIndex: 2,
    explanation: 'England still won by an innings and eight runs after Ian Bell made 235 in their 591 for 6 declared.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_2011',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 2011',
  },
  {
    id: 'cr330',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England 2011',
    difficulty: 'extreme',
    question: 'Which England batsman made 294 against India at Edgbaston in August 2011 as England declared on 710 for 7?',
    options: ['Alastair Cook', 'Kevin Pietersen', 'Ian Bell', 'Eoin Morgan'],
    correctIndex: 0,
    explanation: 'India lost by an innings and 242 runs, and Sehwag suffered a king pair in the match.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_2011',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 2011',
  },
  // ---------------------------------------------------------------- Australia 2011-12
  {
    id: 'cr331',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Australia 2011-12',
    difficulty: 'expert',
    question: 'Which Australian made an unbeaten 329 against India at Sydney in January 2012 during the 4-0 whitewash?',
    options: ['Ricky Ponting', 'Michael Hussey', 'David Warner', 'Michael Clarke'],
    correctIndex: 3,
    explanation: 'He finished the series with 626 runs at an average of 125.20 and was player of the series.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2011%E2%80%9312',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2011–12',
  },
  {
    id: 'cr332',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Tendulkar 100th century',
    difficulty: 'simple',
    question: "Sachin Tendulkar's 100th international century came against Bangladesh in March 2012 at which venue?",
    options: ['Chittagong', 'Colombo', 'Mirpur', 'Karachi'],
    correctIndex: 2,
    explanation: 'He made 114 in an Asia Cup match that India lost by five wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2012_Asia_Cup',
    sourceLabel: 'Wikipedia: 2012 Asia Cup',
  },
  {
    id: 'cr333',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Laxman retires',
    difficulty: 'expert',
    question: 'VVS Laxman announced his international retirement in August 2012 despite being picked for a home Test series against which side?',
    options: ['England', 'New Zealand', 'Australia', 'West Indies'],
    correctIndex: 1,
    explanation: 'He finished with 8,781 runs and 17 centuries in 134 Tests, without ever playing a World Cup.',
    sourceUrl: 'https://en.wikipedia.org/wiki/VVS_Laxman',
    sourceLabel: 'Wikipedia: VVS Laxman',
  },
  // ---------------------------------------------------------------- Australia at home, 2013
  {
    id: 'cr334',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Australia 2013 whitewash',
    difficulty: 'expert',
    question: 'What was MS Dhoni\'s score in the Chennai Test of February 2013, the highest by an Indian Test captain?',
    options: ['224', '206', '217', '231'],
    correctIndex: 0,
    explanation: 'Ashwin took 12 wickets in the match and India won by eight wickets on the way to a 4-0 sweep.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Australian_cricket_team_in_India_in_2012%E2%80%9313',
    sourceLabel: 'Wikipedia: Australian cricket team in India in 2012–13',
  },
  {
    id: 'cr335',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Australia 2013 whitewash',
    difficulty: 'expert',
    question: 'How many wickets did R Ashwin take in the four-Test home series against Australia in 2013, a record for an Indian in a four-Test series?',
    options: ['22', '25', '27', '29'],
    correctIndex: 3,
    explanation: 'He passed Anil Kumble\'s mark of 27 and was player of the series; Nathan Lyon led Australia with 15.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ravichandran_Ashwin',
    sourceLabel: 'Wikipedia: Ravichandran Ashwin',
  },
  {
    id: 'cr336',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Australia 2013 whitewash',
    difficulty: 'extreme',
    question: 'Shikhar Dhawan reached the fastest century on Test debut at Mohali in March 2013 off how many balls?',
    options: ['79', '85', '92', '101'],
    correctIndex: 1,
    explanation: 'He went on to 187 from 174 balls and was man of the match in a six-wicket win.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Shikhar_Dhawan',
    sourceLabel: 'Wikipedia: Shikhar Dhawan',
  },
  {
    id: 'cr337',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Australia 2013 whitewash',
    difficulty: 'extreme',
    question: 'Which batsman was suspended for the 2013 Mohali Test alongside Shane Watson, James Pattinson and Mitchell Johnson in the "homework" affair?',
    options: ['Phillip Hughes', 'Ed Cowan', 'Usman Khawaja', 'Matthew Wade'],
    correctIndex: 2,
    explanation: 'The four had failed to submit performance-improvement assignments demanded by the team management.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Australian_cricket_team_in_India_in_2012%E2%80%9313',
    sourceLabel: 'Wikipedia: Australian cricket team in India in 2012–13',
  },
  {
    id: 'cr338',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Australia 2013 whitewash',
    difficulty: 'extreme',
    question: 'Who shared a 370-run second-wicket stand with Cheteshwar Pujara at Hyderabad in March 2013?',
    options: ['Murali Vijay', 'Virat Kohli', 'Sachin Tendulkar', 'Shikhar Dhawan'],
    correctIndex: 0,
    explanation: 'Pujara made 204 and Australia became the first side to declare its first innings and lose by an innings.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Cheteshwar_Pujara',
    sourceLabel: 'Wikipedia: Cheteshwar Pujara',
  },
  // ---------------------------------------------------------------- Champions Trophy 2013
  {
    id: 'cr339',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2013 Champions Trophy',
    difficulty: 'simple',
    question: 'India won the 2013 Champions Trophy final at Edgbaston, cut to 20 overs a side by rain, against which team?',
    options: ['Sri Lanka', 'South Africa', 'Australia', 'England'],
    correctIndex: 3,
    explanation: 'India defended 129 for 7 to win by five runs, and Dhoni became the first captain to win all three ICC white-ball trophies.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2013_ICC_Champions_Trophy',
    sourceLabel: 'Wikipedia: 2013 ICC Champions Trophy',
  },
  {
    id: 'cr340',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2013 Champions Trophy',
    difficulty: 'expert',
    question: 'Who was man of the match in the 2013 Champions Trophy final with an unbeaten 33 and 2 for 24?',
    options: ['R Ashwin', 'Virat Kohli', 'Ravindra Jadeja', 'Ishant Sharma'],
    correctIndex: 2,
    explanation: 'He also took the golden ball as the tournament\'s leading wicket-taker with 12.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2013_ICC_Champions_Trophy',
    sourceLabel: 'Wikipedia: 2013 ICC Champions Trophy',
  },
  {
    id: 'cr341',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2013 Champions Trophy',
    difficulty: 'extreme',
    question: 'Which two England batsmen did Ishant Sharma remove in consecutive balls in the 18th over of the 2013 Champions Trophy final?',
    options: ['Ian Bell and Joe Root', 'Eoin Morgan and Ravi Bopara', 'Jos Buttler and Tim Bresnan', 'Jonathan Trott and Ravi Bopara'],
    correctIndex: 1,
    explanation: 'Morgan had made 33 and Bopara 30; England finished on 124 for 8 after Ashwin bowled the last over.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2013_ICC_Champions_Trophy_final',
    sourceLabel: 'Wikipedia: 2013 ICC Champions Trophy final',
  },
  {
    id: 'cr342',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2013 Champions Trophy',
    difficulty: 'expert',
    question: 'Who was player of the tournament at the 2013 Champions Trophy with 363 runs in five matches?',
    options: ['Shikhar Dhawan', 'Rohit Sharma', 'Virat Kohli', 'Jonathan Trott'],
    correctIndex: 0,
    explanation: 'His 114 against South Africa at Cardiff in the opening match was the first of his two centuries in the event.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2013_ICC_Champions_Trophy',
    sourceLabel: 'Wikipedia: 2013 ICC Champions Trophy',
  },
  // ---------------------------------------------------------------- Australia ODIs, late 2013
  {
    id: 'cr343',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Kohli Jaipur 2013',
    difficulty: 'simple',
    question: 'Virat Kohli reached the fastest ODI hundred by an Indian at Jaipur in October 2013 off how many balls?',
    options: ['61', '58', '44', '52'],
    correctIndex: 3,
    explanation: 'India chased 360 against Australia with 39 balls to spare, finishing on 362 for 1 as Rohit Sharma made 141 not out.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Australian_cricket_team_in_India_in_2013%E2%80%9314',
    sourceLabel: 'Wikipedia: Australian cricket team in India in 2013–14',
  },
  {
    id: 'cr344',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Rohit 209',
    difficulty: 'simple',
    question: "Rohit Sharma's first ODI double century, 209 at Bangalore on 2 November 2013, came against which team?",
    options: ['Sri Lanka', 'West Indies', 'Australia', 'Pakistan'],
    correctIndex: 2,
    explanation: 'India won by 57 runs to take the series 3-2 and Rohit was player of the series with 491 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Australian_cricket_team_in_India_in_2013%E2%80%9314',
    sourceLabel: 'Wikipedia: Australian cricket team in India in 2013–14',
  },
  {
    id: 'cr345',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Rohit 209',
    difficulty: 'extreme',
    question: 'How many sixes, then a world record for an ODI innings, did Rohit Sharma hit in his 209 at Bangalore in 2013?',
    options: ['13', '16', '18', '21'],
    correctIndex: 1,
    explanation: 'The innings took 158 balls and included 12 fours; James Faulkner replied with 116 for Australia.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Rohit_Sharma',
    sourceLabel: 'Wikipedia: Rohit Sharma',
  },
  // ---------------------------------------------------------------- Tendulkar's 200th Test
  {
    id: 'cr346',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Tendulkar's 200th Test",
    difficulty: 'simple',
    question: "At which ground did Sachin Tendulkar play his 200th and final Test in November 2013?",
    options: ['Wankhede Stadium, Mumbai', 'Eden Gardens, Kolkata', 'Brabourne Stadium, Mumbai', 'Feroz Shah Kotla, Delhi'],
    correctIndex: 0,
    explanation: 'India beat West Indies by an innings and 126 runs, and the Bharat Ratna for Tendulkar was announced the same week.',
    sourceUrl: 'https://en.wikipedia.org/wiki/West_Indian_cricket_team_in_India_in_2013%E2%80%9314',
    sourceLabel: 'Wikipedia: West Indian cricket team in India in 2013–14',
  },
  {
    id: 'cr347',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Tendulkar's 200th Test",
    difficulty: 'expert',
    question: "Who took ten wickets and was man of the match in Tendulkar's farewell Test at the Wankhede?",
    options: ['R Ashwin', 'Mohammed Shami', 'Bhuvneshwar Kumar', 'Pragyan Ojha'],
    correctIndex: 3,
    explanation: 'It was his first ten-wicket match haul, with 5 for 40 and 5 for 49; Rohit Sharma made 111 not out.',
    sourceUrl: 'https://en.wikipedia.org/wiki/West_Indian_cricket_team_in_India_in_2013%E2%80%9314',
    sourceLabel: 'Wikipedia: West Indian cricket team in India in 2013–14',
  },
  {
    id: 'cr348',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Tendulkar's 200th Test",
    difficulty: 'extreme',
    question: 'How many runs did Sachin Tendulkar score in the final innings of his Test career, at the Wankhede in November 2013?',
    options: ['38', '51', '74', '94'],
    correctIndex: 2,
    explanation: 'He retired with 15,921 Test runs and 51 Test centuries from 200 matches.',
    sourceUrl: 'https://en.wikipedia.org/wiki/West_Indian_cricket_team_in_India_in_2013%E2%80%9314',
    sourceLabel: 'Wikipedia: West Indian cricket team in India in 2013–14',
  },
  // ---------------------------------------------------------------- Mohali 2010
  {
    id: 'cr349',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Mohali 2010',
    difficulty: 'extreme',
    question: 'Which fast bowler added 81 for the ninth wicket with VVS Laxman as India beat Australia by one wicket at Mohali in October 2010?',
    options: ['Ishant Sharma', 'Zaheer Khan', 'Pragyan Ojha', 'Harbhajan Singh'],
    correctIndex: 0,
    explanation: 'Laxman finished on 73 not out chasing 216, and Ojha helped him add the last 11 runs after Ishant fell for 31.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Australian_cricket_team_in_India_in_2010%E2%80%9311',
    sourceLabel: 'Wikipedia: Australian cricket team in India in 2010–11',
  },
]);
