// Server-only editorial bank: Indian cricket, tranche 6 — the Kohli era, 2014 to 2019 (50 questions).
// Never import this module from client components.
// Every fact below was checked against the page at sourceUrl when written.
export const CRICKET_INDIA_6 = Object.freeze([
  // ------------------------------------------------- Australia 2014-15 and Dhoni's Test exit
  {
    id: 'cr350',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Dhoni's Test retirement",
    difficulty: 'simple',
    question:
      'MS Dhoni retired from Test cricket with immediate effect in December 2014 after a drawn Test at which ground?',
    options: ['Sydney Cricket Ground', 'Melbourne Cricket Ground', 'Adelaide Oval', 'The Gabba'],
    correctIndex: 1,
    explanation:
      'The BCCI broke the news on 30 December 2014, minutes after Dhoni had faced reporters without mentioning it; he cited the strain of playing all formats.',
    sourceUrl: 'https://www.aljazeera.com/sports/2014/12/30/indias-dhoni-retires-from-test-cricket',
    sourceLabel: "Al Jazeera: India's Dhoni retires from Test cricket",
  },
  {
    id: 'cr351',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Dhoni's Test retirement",
    difficulty: 'simple',
    question: 'Who captained India in the Sydney Test of January 2015, the first after Dhoni quit the format?',
    options: ['Ajinkya Rahane', 'Murali Vijay', 'R Ashwin', 'Virat Kohli'],
    correctIndex: 3,
    explanation:
      'Dhoni had led India in 60 Tests with a 45 per cent win rate, the best of any Indian captain with at least five matches in charge at the time.',
    sourceUrl: 'https://www.aljazeera.com/sports/2014/12/30/indias-dhoni-retires-from-test-cricket',
    sourceLabel: "Al Jazeera: India's Dhoni retires from Test cricket",
  },
  {
    id: 'cr352',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Australia 2014-15',
    difficulty: 'expert',
    question: 'How many runs did Virat Kohli score in the four-Test series in Australia in 2014-15?',
    options: ['692', '588', '741', '654'],
    correctIndex: 0,
    explanation:
      'Kohli made four centuries in the series, the most runs by an Indian batsman in a Test series in Australia, yet Australia won 2-0 with two draws.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2014%E2%80%9315',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2014-15',
  },
  {
    id: 'cr353',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Australia 2014-15',
    difficulty: 'extreme',
    question:
      'Which pair of scores did Kohli make in the Adelaide Test of December 2014, his first match as stand-in captain?',
    options: ['103 and 128', '119 and 96', '115 and 141', '141 and 169'],
    correctIndex: 2,
    explanation:
      'Chasing 364 on the final day, India were bowled out for 315 as Nathan Lyon took 7 for 152 and finished with ten wickets in the match.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2014%E2%80%9315',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2014-15',
  },
  {
    id: 'cr354',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: 'Australia 2014-15',
    difficulty: 'expert',
    question: 'Who was player of the series with 769 runs when Australia beat India 2-0 in 2014-15?',
    options: ['David Warner', 'Steven Smith', 'Nathan Lyon', 'Mitchell Johnson'],
    correctIndex: 1,
    explanation:
      'Smith made a century in every Test of the series, equalling a record shared by Don Bradman and Jacques Kallis.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2014%E2%80%9315',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2014-15',
  },
  // ------------------------------------------------- 2015 World Cup
  {
    id: 'cr355',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: '2015 World Cup',
    difficulty: 'simple',
    question: "India's defence of the World Cup ended in a 95-run semi-final defeat to Australia in March 2015 at which ground?",
    options: ['Sydney Cricket Ground', 'Melbourne Cricket Ground', 'Eden Park', 'Adelaide Oval'],
    correctIndex: 0,
    explanation:
      'Australia made 328 for 7 and India were bowled out for 233; Australia then beat New Zealand in the final at the MCG.',
    sourceUrl:
      'https://www.espncricinfo.com/series/icc-cricket-world-cup-2014-15-509587/australia-vs-india-2nd-semi-final-656493/match-report',
    sourceLabel: 'ESPNcricinfo: Smith ton sets up trans-Tasman finale',
  },
  {
    id: 'cr356',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2015 World Cup',
    difficulty: 'extreme',
    question: 'Who top-scored for India with 65 in the 2015 World Cup semi-final against Australia?',
    options: ['Shikhar Dhawan', 'Rohit Sharma', 'MS Dhoni', 'Suresh Raina'],
    correctIndex: 2,
    explanation:
      'Steven Smith made 105 off 93 balls for Australia, his fourth ODI century, while Umesh Yadav took 4 for 72 for India.',
    sourceUrl:
      'https://www.espncricinfo.com/series/icc-cricket-world-cup-2014-15-509587/australia-vs-india-2nd-semi-final-656493/match-report',
    sourceLabel: 'ESPNcricinfo: Smith ton sets up trans-Tasman finale',
  },
  // ------------------------------------------------- 2016 World T20
  {
    id: 'cr357',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2016 World T20',
    difficulty: 'simple',
    question:
      "Kohli's unbeaten 82 off 51 balls at Mohali in the 2016 World T20, which he later called his best T20 innings, came against which side?",
    options: ['Australia', 'Pakistan', 'New Zealand', 'West Indies'],
    correctIndex: 0,
    explanation:
      'India chased 161 with five balls to spare on 27 March 2016 and the win sent them into a semi-final against West Indies.',
    sourceUrl:
      'https://royalchallengers.com/rcb-cricket-news/news/on-this-day-in-2016-kohlis-breathtaking-innings-takes-india-to-the-semis',
    sourceLabel: "Royal Challengers: On this day in 2016, Kohli's breathtaking innings takes India to the semis",
  },
  {
    id: 'cr358',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2016 World T20',
    difficulty: 'expert',
    question: 'How many runs did India still need from the last 18 balls at Mohali in 2016 before Kohli took the chase apart?',
    options: ['45', '33', '39', '52'],
    correctIndex: 2,
    explanation:
      'Kohli took 19 off James Faulkner and then four boundaries in a row off Nathan Coulter-Nile, leaving four to get in the last over, which Dhoni finished.',
    sourceUrl:
      'https://royalchallengers.com/rcb-cricket-news/news/on-this-day-in-2016-kohlis-breathtaking-innings-takes-india-to-the-semis',
    sourceLabel: "Royal Challengers: On this day in 2016, Kohli's breathtaking innings takes India to the semis",
  },
  {
    id: 'cr359',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2016 World T20',
    difficulty: 'extreme',
    question:
      'For what total were India bowled out by New Zealand at Nagpur in their opening Super 10 match of the 2016 World T20?',
    options: ['92', '85', '101', '79'],
    correctIndex: 3,
    explanation:
      'Chasing 127, India lost by 47 runs as Mitchell Santner took 4 for 11 and Ish Sodhi 3 for 18; only Dhoni (30) and Kohli (23) reached 20.',
    sourceUrl:
      'https://www.icc-cricket.com/tournaments/mens-t20-world-cup-2026/news/looking-back-previous-india-v-new-zealand-t20-world-cup-matches',
    sourceLabel: 'ICC: Looking back at previous India v New Zealand T20 World Cup matches',
  },
  {
    id: 'cr360',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2016 World T20',
    difficulty: 'expert',
    question:
      'Who bowled the final over when India beat Bangladesh by one run at Bangalore in the 2016 World T20?',
    options: ['Jasprit Bumrah', 'Hardik Pandya', 'Ashish Nehra', 'R Ashwin'],
    correctIndex: 1,
    explanation:
      'Defending 146 for 7, India took three wickets in the last three balls after Bangladesh had needed two from the final delivery.',
    sourceUrl:
      'https://www.dnaindia.com/cricket/report-throwback-watch-when-ms-dhoni-eliminated-bangladesh-out-of-2016-world-cup-with-epic-last-ball-run-out-2998079',
    sourceLabel: 'DNA India: When MS Dhoni eliminated Bangladesh from the 2016 World Cup with a last-ball run-out',
  },
  {
    id: 'cr361',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2016 World T20',
    difficulty: 'extreme',
    question:
      'Which Bangladesh batsman was run out by Dhoni off the last ball of the one-run thriller at Bangalore in March 2016?',
    options: ['Mahmudullah', 'Mushfiqur Rahim', 'Mustafizur Rahman', 'Shuvagata Hom'],
    correctIndex: 2,
    explanation:
      'Dhoni had already pulled off one glove before the ball was bowled, then sprinted to the stumps himself; Mushfiqur and Mahmudullah had fallen to the two previous deliveries.',
    sourceUrl:
      'https://www.dnaindia.com/cricket/report-throwback-watch-when-ms-dhoni-eliminated-bangladesh-out-of-2016-world-cup-with-epic-last-ball-run-out-2998079',
    sourceLabel: 'DNA India: When MS Dhoni eliminated Bangladesh from the 2016 World Cup with a last-ball run-out',
  },
  {
    id: 'cr362',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: '2016 World T20',
    difficulty: 'simple',
    question: 'Who was named player of the tournament at the 2016 World T20 in India after scoring 273 runs?',
    options: ['Tamim Iqbal', 'Carlos Brathwaite', 'Mohammad Nabi', 'Virat Kohli'],
    correctIndex: 3,
    explanation:
      'West Indies beat England by four wickets in the final at Eden Gardens; Tamim Iqbal topped the run charts with 295 and Nabi the wickets with 12.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2016_ICC_World_Twenty20',
    sourceLabel: 'Wikipedia: 2016 ICC World Twenty20',
  },
  // ------------------------------------------------- Kumble, the rift and Shastri
  {
    id: 'cr363',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Kumble-Kohli rift',
    difficulty: 'simple',
    question:
      "Which India head coach resigned in June 2017, calling his partnership with captain Kohli 'untenable'?",
    options: ['Anil Kumble', 'Duncan Fletcher', 'Ravi Shastri', 'Sanjay Bangar'],
    correctIndex: 0,
    explanation:
      'He stepped down on 20 June 2017, two days after the Champions Trophy final, having overseen a 19-match unbeaten home Test streak.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Anil_Kumble',
    sourceLabel: 'Wikipedia: Anil Kumble',
  },
  {
    id: 'cr364',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Kumble-Kohli rift',
    difficulty: 'expert',
    question: "Which event was Anil Kumble's last as India head coach?",
    options: ['The 2016 World T20', 'The 2017 tour of the West Indies', 'The 2017 Champions Trophy', 'The 2017 tour of Sri Lanka'],
    correctIndex: 2,
    explanation:
      'Kumble had been appointed on a one-year term on 24 June 2016 and India lost the Champions Trophy final to Pakistan at The Oval.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Anil_Kumble',
    sourceLabel: 'Wikipedia: Anil Kumble',
  },
  {
    id: 'cr365',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Ravi Shastri',
    difficulty: 'expert',
    question:
      'Which three former players made up the Cricket Advisory Committee that appointed Ravi Shastri head coach in July 2017?',
    options: [
      'Rahul Dravid, Anil Kumble and Javagal Srinath',
      'Sunil Gavaskar, Kapil Dev and Dilip Vengsarkar',
      'Sourav Ganguly, Rahul Dravid and VVS Laxman',
      'Sourav Ganguly, Sachin Tendulkar and VVS Laxman',
    ],
    correctIndex: 3,
    explanation:
      'Shastri succeeded Kumble on a reported Rs 8 crore a year and was reappointed in August 2019 through to the 2021 T20 World Cup.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ravi_Shastri',
    sourceLabel: 'Wikipedia: Ravi Shastri',
  },
  {
    id: 'cr366',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Ravi Shastri',
    difficulty: 'extreme',
    question: 'What title did Ravi Shastri hold with the India team from August 2014 until 2016, before he became head coach?',
    options: ['Team director', 'Batting consultant', 'Chairman of selectors', 'Team manager'],
    correctIndex: 0,
    explanation:
      "Shastri's coaching tenure ended in November 2021 after the T20 World Cup, after which he became commissioner of the Legends League Cricket.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Ravi_Shastri',
    sourceLabel: 'Wikipedia: Ravi Shastri',
  },
  // ------------------------------------------------- 2017 Champions Trophy final
  {
    id: 'cr367',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: '2017 Champions Trophy',
    difficulty: 'simple',
    question: "Whose 114 set up Pakistan's 180-run win over India in the 2017 Champions Trophy final at The Oval?",
    options: ['Babar Azam', 'Fakhar Zaman', 'Mohammad Hafeez', 'Azhar Ali'],
    correctIndex: 1,
    explanation:
      'It was his maiden ODI century; Pakistan had entered the tournament ranked eighth and the margin remains the largest in an ICC ODI final.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2017_ICC_Champions_Trophy_final',
    sourceLabel: 'Wikipedia: 2017 ICC Champions Trophy final',
  },
  {
    id: 'cr368',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2017 Champions Trophy',
    difficulty: 'expert',
    question: 'Whose no-ball reprieved Fakhar Zaman on 3 in the 2017 Champions Trophy final?',
    options: ['Bhuvneshwar Kumar', 'Hardik Pandya', 'Jasprit Bumrah', 'R Ashwin'],
    correctIndex: 2,
    explanation:
      'Fakhar had been given out, but the overstep was called and he went on to 114 off 106 balls as Pakistan posted 338 for 4.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2017_ICC_Champions_Trophy_final',
    sourceLabel: 'Wikipedia: 2017 ICC Champions Trophy final',
  },
  {
    id: 'cr369',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: '2017 Champions Trophy',
    difficulty: 'extreme',
    question: 'Which Pakistan bowler dismissed Rohit Sharma, Virat Kohli and Shikhar Dhawan in the 2017 Champions Trophy final?',
    options: ['Mohammad Amir', 'Hasan Ali', 'Junaid Khan', 'Shadab Khan'],
    correctIndex: 0,
    explanation:
      'His 3 for 16 from six overs wrecked the chase as India were bowled out for 158; Hasan Ali took the Golden Ball with 13 wickets and was player of the tournament.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2017_ICC_Champions_Trophy_final',
    sourceLabel: 'Wikipedia: 2017 ICC Champions Trophy final',
  },
  {
    id: 'cr370',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2017 Champions Trophy',
    difficulty: 'expert',
    question: "How did Hardik Pandya's 76 off 43 balls end in the 2017 Champions Trophy final?",
    options: ['Caught in the deep', 'Bowled', 'Stumped', 'Run out'],
    correctIndex: 3,
    explanation:
      'Pandya was run out during a partnership with Ravindra Jadeja, and India folded for 158 in 30.3 overs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2017_ICC_Champions_Trophy_final',
    sourceLabel: 'Wikipedia: 2017 ICC Champions Trophy final',
  },
  // ------------------------------------------------- Kohli's ODI chasing
  {
    id: 'cr371',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Kohli's ODI records",
    difficulty: 'expert',
    question:
      "Kohli reached 10,000 ODI runs against West Indies in October 2018 in how many innings, beating Tendulkar's 259?",
    options: ['213', '198', '205', '220'],
    correctIndex: 2,
    explanation:
      'He scored 453 runs in that five-match series, which India won 3-1 with one tie, and was player of the series.',
    sourceUrl: 'https://en.wikipedia.org/wiki/West_Indian_cricket_team_in_India_in_2018%E2%80%9319',
    sourceLabel: 'Wikipedia: West Indian cricket team in India in 2018-19',
  },
  {
    id: 'cr372',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Kohli's ODI records",
    difficulty: 'extreme',
    question:
      "Against which side did Kohli's unbeaten 111 in July 2017 take him past Tendulkar's record for the most ODI centuries in run chases?",
    options: ['West Indies', 'Sri Lanka', 'New Zealand', 'England'],
    correctIndex: 0,
    explanation:
      'It was his 18th ODI century while chasing, one more than Tendulkar, and it came at Kingston in the fifth match of a series India won 3-1.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_the_West_Indies_in_2017',
    sourceLabel: 'Wikipedia: Indian cricket team in the West Indies in 2017',
  },
  // ------------------------------------------------- South Africa 2018
  {
    id: 'cr373',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'South Africa 2018',
    difficulty: 'extreme',
    question: 'At which ground did Jasprit Bumrah make his Test debut in January 2018?',
    options: ['Cape Town', 'Centurion', 'Johannesburg', 'Durban'],
    correctIndex: 0,
    explanation:
      'South Africa won that Newlands Test by 72 runs; Wriddhiman Saha took ten catches in the match for India.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_South_Africa_in_2017%E2%80%9318',
    sourceLabel: 'Wikipedia: Indian cricket team in South Africa in 2017-18',
  },
  {
    id: 'cr374',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'South Africa 2018',
    difficulty: 'expert',
    question: "Kohli's 153 in the 2018 Test series in South Africa came at which venue?",
    options: ['Cape Town', 'Johannesburg', 'Centurion', 'Port Elizabeth'],
    correctIndex: 2,
    explanation:
      'South Africa still won that second Test by 135 runs to take the series, with Lungi Ngidi impressive on debut.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_South_Africa_in_2017%E2%80%9318',
    sourceLabel: 'Wikipedia: Indian cricket team in South Africa in 2017-18',
  },
  {
    id: 'cr375',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'South Africa 2018',
    difficulty: 'extreme',
    question: "Who was player of the match in India's 63-run win at the Wanderers in January 2018?",
    options: ['Jasprit Bumrah', 'Bhuvneshwar Kumar', 'Mohammed Shami', 'Virat Kohli'],
    correctIndex: 1,
    explanation:
      'Bumrah took his first Test five-wicket haul in the same match; India then won the ODI series 5-1 with Kohli scoring 558 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_South_Africa_in_2017%E2%80%9318',
    sourceLabel: 'Wikipedia: Indian cricket team in South Africa in 2017-18',
  },
  // ------------------------------------------------- England 2018
  {
    id: 'cr376',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England 2018',
    difficulty: 'simple',
    question: 'How many Test runs did Kohli score on the 2018 tour of England, where India lost the series 4-1?',
    options: ['480', '655', '521', '593'],
    correctIndex: 3,
    explanation:
      'He made 149 and 51 at Edgbaston and 97 and 103 at Trent Bridge; James Anderson took 24 wickets for England.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_2018',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 2018',
  },
  {
    id: 'cr377',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England 2018',
    difficulty: 'expert',
    question: "At which ground did India record their only win of the 2018 Test series in England, by 203 runs?",
    options: ["Lord's", 'Trent Bridge', 'The Rose Bowl', 'The Oval'],
    correctIndex: 1,
    explanation:
      "England had won by an innings and 159 runs at Lord's earlier in the series; Pujara's unbeaten 132 at Southampton could not prevent a 60-run defeat next.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_2018',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 2018',
  },
  {
    id: 'cr378',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: 'England 2018',
    difficulty: 'extreme',
    question: 'Which England player shared the player of the series award with Kohli in 2018?',
    options: ['James Anderson', 'Ben Stokes', 'Sam Curran', 'Joe Root'],
    correctIndex: 2,
    explanation:
      'Alastair Cook signed off with 147 at The Oval, becoming only the fifth batsman to score a century in both his first and last Tests.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_2018',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 2018',
  },
  {
    id: 'cr379',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Rishabh Pant',
    difficulty: 'simple',
    question: 'Which Indian wicketkeeper scored 114 at The Oval in 2018, the first Test century by an Indian keeper in England?',
    options: ['Wriddhiman Saha', 'Dinesh Karthik', 'Parthiv Patel', 'Rishabh Pant'],
    correctIndex: 3,
    explanation:
      'He had made his Test debut at Trent Bridge earlier in the series and got off the mark in Test cricket with a six.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Rishabh_Pant',
    sourceLabel: 'Wikipedia: Rishabh Pant',
  },
  // ------------------------------------------------- Australia 2018-19
  {
    id: 'cr380',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Australia 2018-19',
    difficulty: 'simple',
    question: "What was the result of India's 2018-19 Test series in Australia, their first series win in that country?",
    options: ['3-1', '2-1', '2-0', '3-0'],
    correctIndex: 1,
    explanation:
      'India won at Adelaide and Melbourne, lost at Perth and drew a rain-hit Sydney Test to become the first Asian side to win a Test series in Australia.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2018%E2%80%9319',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2018-19',
  },
  {
    id: 'cr381',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Australia 2018-19',
    difficulty: 'expert',
    question: 'How many centuries did Cheteshwar Pujara make on the way to 521 runs in the 2018-19 series in Australia?',
    options: ['Two', 'Four', 'Three', 'One'],
    correctIndex: 2,
    explanation:
      'He made 123 at Adelaide, 106 at Melbourne and 193 at Sydney and was named player of the series.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2018%E2%80%9319',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2018-19',
  },
  {
    id: 'cr382',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Australia 2018-19',
    difficulty: 'simple',
    question: 'Which Indian took 6 for 33 in the first innings of the 2018 Boxing Day Test at Melbourne?',
    options: ['Ishant Sharma', 'Mohammed Shami', 'R Ashwin', 'Jasprit Bumrah'],
    correctIndex: 3,
    explanation:
      'India won by 137 runs to go 2-1 up; he and Nathan Lyon each finished the series with 21 wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2018%E2%80%9319',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2018-19',
  },
  {
    id: 'cr383',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: 'Australia 2018-19',
    difficulty: 'expert',
    question:
      "Which Australia captain's 'can you babysit' jab at Rishabh Pant was picked up by the stump microphones in the 2018 Boxing Day Test?",
    options: ['Aaron Finch', 'Tim Paine', 'Steve Smith', 'Pat Cummins'],
    correctIndex: 1,
    explanation:
      "Pant shot back with 'have you heard of a temporary captain ever', and days later Bonnie Paine posted a photo of him with her children captioned 'best babysitter'.",
    sourceUrl:
      'https://www.cricket.com.au/news/rishabh-pant-tim-paine-babysitter-sledging-australia-india-test-series/2019-01-01',
    sourceLabel: 'cricket.com.au: Pant debuts as Paine family babysitter',
  },
  // ------------------------------------------------- 2019 World Cup
  {
    id: 'cr384',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2019 World Cup',
    difficulty: 'simple',
    question: 'By how many runs did New Zealand beat India in the 2019 World Cup semi-final at Old Trafford?',
    options: ['5', '31', '12', '18'],
    correctIndex: 3,
    explanation:
      'Rain pushed the match into a reserve day; New Zealand made 239 for 8 and India were bowled out for 221 in the final over.',
    sourceUrl: 'https://www.aljazeera.com/sports/2019/7/10/cricket-world-cup-new-zealand-stun-india-to-reach-final',
    sourceLabel: 'Al Jazeera: Cricket World Cup: New Zealand stun India to reach final',
  },
  {
    id: 'cr385',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2019 World Cup',
    difficulty: 'expert',
    question: 'Whose direct hit from deep square leg ran out Dhoni for 50 in the 2019 World Cup semi-final?',
    options: ['Martin Guptill', 'Jimmy Neesham', 'Trent Boult', 'Kane Williamson'],
    correctIndex: 0,
    explanation:
      'Dhoni had turned for a second run; it turned out to be the last ball he faced in international cricket.',
    sourceUrl:
      'https://gulfnews.com/sport/cricket/cricket-world-cup-2019-professional-new-zealand-cause-heartbreak-for-india-fans-1.65149197',
    sourceLabel: 'Gulf News: Professional New Zealand cause heartbreak for India fans',
  },
  {
    id: 'cr386',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2019 World Cup',
    difficulty: 'expert',
    question:
      "Which commentator's 'bits and pieces player' remark preceded Ravindra Jadeja's 77 off 59 balls in the 2019 semi-final?",
    options: ['Sunil Gavaskar', 'Sanjay Manjrekar', 'Harsha Bhogle', 'Aakash Chopra'],
    correctIndex: 1,
    explanation:
      "Jadeja had replied on Twitter that he had played twice as many matches, adding that he had heard enough 'verbal diarrhoea'.",
    sourceUrl:
      'https://gulfnews.com/sport/cricket/enough-of-your-verbal-diarrhoea-ravindra-jadeja-hits-out-at-sanjay-manjrekar-1.1562235230196',
    sourceLabel: 'Gulf News: Enough of your verbal diarrhoea, Ravindra Jadeja hits out at Sanjay Manjrekar',
  },
  {
    id: 'cr387',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2019 World Cup',
    difficulty: 'extreme',
    question:
      'Rohit Sharma, KL Rahul and Virat Kohli were each dismissed for the same score as India slumped to 5 for 3 in the 2019 semi-final. What was it?',
    options: ['0', '4', '1', '2'],
    correctIndex: 2,
    explanation:
      'Matt Henry took 3 for 37 and was player of the match; Jadeja and Dhoni added 116 for the seventh wicket before both fell.',
    sourceUrl:
      'https://www.outlookindia.com/sports/sports-news-live-score-live-blog-icc-cricket-world-cup-2019-india-vs-new-zealand-semi-final-old-trafford-manchester-news-333848',
    sourceLabel: 'Outlook India: India vs New Zealand, ICC World Cup 2019 semi-final highlights',
  },
  {
    id: 'cr388',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Bumrah',
    difficulty: 'simple',
    question: "At which ground did Jasprit Bumrah take his Test hat-trick against West Indies in August 2019?",
    options: ['Sabina Park, Kingston', 'Kensington Oval, Bridgetown', "Queen's Park Oval, Port of Spain", 'Sir Vivian Richards Stadium, Antigua'],
    correctIndex: 0,
    explanation:
      'He removed Darren Bravo, Shamarh Brooks and Roston Chase on the way to 6 for 27, becoming the third Indian with a Test hat-trick.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_the_West_Indies_in_2019',
    sourceLabel: 'Wikipedia: Indian cricket team in the West Indies in 2019',
  },
  {
    id: 'cr389',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2019 World Cup',
    difficulty: 'simple',
    question: 'How many centuries did Rohit Sharma score at the 2019 World Cup, a record for a single edition?',
    options: ['Four', 'Five', 'Three', 'Six'],
    correctIndex: 1,
    explanation: 'He finished as the tournament\'s leading scorer with 648 runs and took the Golden Bat.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Rohit_Sharma',
    sourceLabel: 'Wikipedia: Rohit Sharma',
  },
  {
    id: 'cr390',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2019 World Cup',
    difficulty: 'extreme',
    question:
      "Rohit Sharma's 2019 World Cup centuries came against South Africa, Pakistan, England, Bangladesh and which other side?",
    options: ['West Indies', 'Australia', 'Afghanistan', 'Sri Lanka'],
    correctIndex: 3,
    explanation:
      "That fifth hundred was also his sixth World Cup century overall, equalling Sachin Tendulkar's record at the time.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Rohit_Sharma',
    sourceLabel: 'Wikipedia: Rohit Sharma',
  },
  {
    id: 'cr391',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2019 World Cup',
    difficulty: 'expert',
    question: "Who took the 2019 World Cup's first hat-trick, in India's 11-run win over Afghanistan at Southampton?",
    options: ['Mohammed Shami', 'Jasprit Bumrah', 'Bhuvneshwar Kumar', 'Hardik Pandya'],
    correctIndex: 0,
    explanation:
      'India topped the group with seven wins from nine, their only defeat coming against England at Edgbaston.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2019_Cricket_World_Cup_group_stage',
    sourceLabel: 'Wikipedia: 2019 Cricket World Cup group stage',
  },
  // ------------------------------------------------- Home dominance, pink ball, Dhoni's coda
  {
    id: 'cr392',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'First day-night Test',
    difficulty: 'simple',
    question: "Who were India's opponents in their first day-night Test, played with the pink ball at Eden Gardens in November 2019?",
    options: ['Sri Lanka', 'South Africa', 'Bangladesh', 'West Indies'],
    correctIndex: 2,
    explanation:
      'Sheikh Hasina and Mamata Banerjee rang the ceremonial bell; India won by an innings and 46 runs inside three days.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bangladeshi_cricket_team_in_India_in_2019%E2%80%9320',
    sourceLabel: 'Wikipedia: Bangladeshi cricket team in India in 2019-20',
  },
  {
    id: 'cr393',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'First day-night Test',
    difficulty: 'extreme',
    question: 'Which India seamer took 5 for 22 and nine wickets in the match in the pink-ball Test at Eden Gardens in 2019?',
    options: ['Umesh Yadav', 'Ishant Sharma', 'Mohammed Shami', 'Jasprit Bumrah'],
    correctIndex: 1,
    explanation:
      "Kohli's 136 was the first pink-ball Test century by an Indian, and Bangladesh became the first side to use two concussion substitutes in one Test.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Bangladeshi_cricket_team_in_India_in_2019%E2%80%9320',
    sourceLabel: 'Wikipedia: Bangladeshi cricket team in India in 2019-20',
  },
  {
    id: 'cr394',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England 2016',
    difficulty: 'simple',
    question: 'Who scored 303 not out against England at Chennai in December 2016, in only his third Test?',
    options: ['Cheteshwar Pujara', 'KL Rahul', 'Murali Vijay', 'Karun Nair'],
    correctIndex: 3,
    explanation:
      'He became the second Indian after Virender Sehwag to make a Test triple century, and the first to convert a maiden hundred into one.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Karun_Nair',
    sourceLabel: 'Wikipedia: Karun Nair',
  },
  {
    id: 'cr395',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England 2016',
    difficulty: 'expert',
    question: "In which city did Kohli make 235, then the highest Test score by an Indian against England, in December 2016?",
    options: ['Mumbai', 'Chennai', 'Visakhapatnam', 'Mohali'],
    correctIndex: 0,
    explanation:
      'India won that fourth Test by an innings and 36 runs and took the series 4-0; Kohli finished with 655 runs and Ashwin with 28 wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/English_cricket_team_in_India_in_2016%E2%80%9317',
    sourceLabel: 'Wikipedia: English cricket team in India in 2016-17',
  },
  {
    id: 'cr396',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Ashwin and Jadeja',
    difficulty: 'extreme',
    question: "In how many Tests did R Ashwin reach 300 wickets in 2017, beating Dennis Lillee's record of 56?",
    options: ['56', '54', '51', '58'],
    correctIndex: 1,
    explanation:
      'Ashwin was the ICC Cricketer of the Year for 2016 and finished his career with 11 Test player-of-the-series awards, level with Muttiah Muralitharan.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ravichandran_Ashwin',
    sourceLabel: 'Wikipedia: Ravichandran Ashwin',
  },
  {
    id: 'cr397',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: 'Australia in India 2017',
    difficulty: 'extreme',
    question:
      'Which Australian spinner took 12 for 70 at Pune in February 2017, the best figures by a visiting spinner in a Test in India?',
    options: ['Nathan Lyon', 'Mitchell Starc', 'Josh Hazlewood', "Steve O'Keefe"],
    correctIndex: 3,
    explanation:
      'Australia won that Test by 333 runs, but India came back to take the series 2-1 with Jadeja named player of the series for 25 wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Australian_cricket_team_in_India_in_2016%E2%80%9317',
    sourceLabel: 'Wikipedia: Australian cricket team in India in 2016-17',
  },
  {
    id: 'cr398',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Dhoni's retirement",
    difficulty: 'simple',
    question: 'On which date did MS Dhoni announce his retirement from international cricket with an Instagram post?',
    options: ['10 July 2019', '1 January 2020', '15 August 2020', '26 January 2021'],
    correctIndex: 2,
    explanation:
      "Suresh Raina announced his own retirement the same evening, writing that he had chosen 'to join you in this journey'.",
    sourceUrl: 'https://www.aljazeera.com/sports/2020/8/15/ms-dhoni-ex-india-cricket-captain-says-consider-me-as-retired',
    sourceLabel: "Al Jazeera: MS Dhoni, ex-India cricket captain, says 'consider me as retired'",
  },
  {
    id: 'cr399',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Dhoni's retirement",
    difficulty: 'extreme',
    question: "From what time on 15 August 2020 did Dhoni's Instagram post ask fans to 'consider me as retired'?",
    options: ['19:29', '20:00', '18:45', '21:15'],
    correctIndex: 0,
    explanation:
      'The post carried a montage of his career; he had not played for India since the 2019 World Cup semi-final defeat to New Zealand.',
    sourceUrl: 'https://www.aljazeera.com/sports/2020/8/15/ms-dhoni-ex-india-cricket-captain-says-consider-me-as-retired',
    sourceLabel: "Al Jazeera: MS Dhoni, ex-India cricket captain, says 'consider me as retired'",
  },
]);
