// Server-only editorial bank: Cricket, India tranche 8 (50 questions) — the Indian Premier League, 2008-2026.
// Never import this module from client components.
// Every fact below was checked against the page at sourceUrl when written.
export const CRICKET_INDIA_8 = Object.freeze([
  // ---------------------------------------------------------------- IPL 2008
  {
    id: 'cr450',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2008',
    difficulty: 'simple',
    question:
      'Brendon McCullum hit 158 not out in the very first IPL match in April 2008. Which franchise was he playing for?',
    options: ['Kolkata Knight Riders', 'Royal Challengers Bangalore', 'Mumbai Indians', 'Deccan Chargers'],
    correctIndex: 0,
    explanation:
      'Kolkata made 222 for 3 at the Chinnaswamy Stadium in Bangalore and won the opening match by 140 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2008_Indian_Premier_League',
    sourceLabel: 'Wikipedia: 2008 Indian Premier League',
  },
  {
    id: 'cr451',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2008',
    difficulty: 'expert',
    question: "How many balls did Brendon McCullum face for his 158 not out in the IPL's opening match in 2008?",
    options: ['61', '73', '84', '92'],
    correctIndex: 1,
    explanation:
      'The innings came against Royal Challengers Bangalore; the tournament ran from 18 April to 1 June 2008.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2008_Indian_Premier_League',
    sourceLabel: 'Wikipedia: 2008 Indian Premier League',
  },
  {
    id: 'cr452',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2008',
    difficulty: 'simple',
    question: 'Who captained Rajasthan Royals to the inaugural IPL title in 2008?',
    options: ['Shane Watson', 'Graeme Smith', 'Shane Warne', 'Sohail Tanvir'],
    correctIndex: 2,
    explanation:
      'Rajasthan beat Chennai Super Kings by three wickets in the final, scoring the winning single off the last ball.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2008_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2008 Indian Premier League final',
  },
  {
    id: 'cr453',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2008',
    difficulty: 'expert',
    question: 'Where was the first IPL final, between Rajasthan Royals and Chennai Super Kings, played on 1 June 2008?',
    options: ['Wankhede Stadium, Mumbai', 'Eden Gardens, Kolkata', 'M. Chinnaswamy Stadium, Bangalore', 'DY Patil Stadium, Navi Mumbai'],
    correctIndex: 3,
    explanation:
      'Rajasthan reached 164 for 7 chasing 163; Yusuf Pathan was player of the match with 56 off 39 balls and 3 for 22.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2008_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2008 Indian Premier League final',
  },
  {
    id: 'cr454',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2008',
    difficulty: 'extreme',
    question: 'Which Chennai Super Kings bowler delivered the final over of the 2008 IPL final, from which Rajasthan Royals took the last-ball single?',
    options: ['Lakshmipathy Balaji', 'Makhaya Ntini', 'Albie Morkel', 'Manpreet Gony'],
    correctIndex: 0,
    explanation: 'Sohail Tanvir and Shane Warne ran the single that completed the three-wicket win.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2008_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2008 Indian Premier League final',
  },
  {
    id: 'cr455',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2008 auction',
    difficulty: 'simple',
    question: 'Who was the most expensive signing at the first IPL player auction in 2008, going for US$1.5 million?',
    options: ['Andrew Symonds', 'MS Dhoni', 'Sanath Jayasuriya', 'Yuvraj Singh'],
    correctIndex: 1,
    explanation: 'Chennai Super Kings bought Dhoni, who scored 414 runs in the first season and led them to the final.',
    sourceUrl: 'https://en.wikipedia.org/wiki/MS_Dhoni',
    sourceLabel: 'Wikipedia: MS Dhoni',
  },
  {
    id: 'cr456',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2008',
    difficulty: 'expert',
    question: 'Which Kings XI Punjab batsman won the first Orange Cap as leading run-scorer of IPL 2008?',
    options: ['Gautam Gambhir', 'Sanath Jayasuriya', 'Shaun Marsh', 'Adam Gilchrist'],
    correctIndex: 2,
    explanation: 'Marsh made 616 runs; Shane Watson of Rajasthan Royals was player of the tournament.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2008_Indian_Premier_League',
    sourceLabel: 'Wikipedia: 2008 Indian Premier League',
  },
  {
    id: 'cr457',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2008',
    difficulty: 'extreme',
    question: 'Which Rajasthan Royals bowler won the first Purple Cap as leading wicket-taker of IPL 2008?',
    options: ['Shane Warne', 'Sreesanth', 'Irfan Pathan', 'Sohail Tanvir'],
    correctIndex: 3,
    explanation: 'The Pakistan left-armer took 22 wickets in the season.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2008_Indian_Premier_League',
    sourceLabel: 'Wikipedia: 2008 Indian Premier League',
  },
  // ---------------------------------------------------------------- IPL 2009-2010
  {
    id: 'cr458',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2009',
    difficulty: 'simple',
    question: 'The second IPL season in 2009 was moved out of India because of the general elections. Which country hosted it?',
    options: ['South Africa', 'United Arab Emirates', 'England', 'Sri Lanka'],
    correctIndex: 0,
    explanation:
      'The Indian government would not commit paramilitary security during the polls; the season ran from 18 April to 24 May 2009.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2009_Indian_Premier_League',
    sourceLabel: 'Wikipedia: 2009 Indian Premier League',
  },
  {
    id: 'cr459',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2009',
    difficulty: 'expert',
    question: 'Who captained Deccan Chargers to the 2009 IPL title after they had finished bottom in 2008?',
    options: ['VVS Laxman', 'Adam Gilchrist', 'Andrew Symonds', 'Rohit Sharma'],
    correctIndex: 1,
    explanation: 'Gilchrist was also player of the tournament; Deccan beat Royal Challengers Bangalore by six runs at the Wanderers.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2009_Indian_Premier_League',
    sourceLabel: 'Wikipedia: 2009 Indian Premier League',
  },
  {
    id: 'cr460',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2009',
    difficulty: 'extreme',
    question: 'Which player from the losing side was named player of the match in the 2009 IPL final in Johannesburg?',
    options: ['Herschelle Gibbs', 'RP Singh', 'Anil Kumble', 'Jacques Kallis'],
    correctIndex: 2,
    explanation: 'Kumble, captaining Bangalore, took 4 for 16, but RCB finished on 137 for 9 chasing 144.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2009_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2009 Indian Premier League final',
  },
  {
    id: 'cr461',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2010',
    difficulty: 'simple',
    question: 'Chennai Super Kings won their first IPL title in 2010. Which team did they beat in the final?',
    options: ['Royal Challengers Bangalore', 'Deccan Chargers', 'Kolkata Knight Riders', 'Mumbai Indians'],
    correctIndex: 3,
    explanation: 'CSK made 168 for 5 and won by 22 runs at the DY Patil Stadium on 25 April 2010, in Mumbai\'s first final.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2010_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2010 Indian Premier League final',
  },
  {
    id: 'cr462',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2010',
    difficulty: 'expert',
    question: 'Who was player of the match in the 2010 IPL final with an unbeaten 57 off 35 balls for Chennai Super Kings?',
    options: ['Suresh Raina', 'MS Dhoni', 'Albie Morkel', 'Murali Vijay'],
    correctIndex: 0,
    explanation: 'Sachin Tendulkar top-scored for Mumbai with 48 and finished the season with the Orange Cap for 618 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2010_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2010 Indian Premier League final',
  },
  {
    id: 'cr463',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Lalit Modi',
    difficulty: 'extreme',
    question: 'In which year did the BCCI suspend founding IPL commissioner Lalit Modi, immediately after that season\'s final?',
    options: ['2008', '2010', '2011', '2013'],
    correctIndex: 1,
    explanation: 'He faced 22 charges including bid rigging; a BCCI committee expelled him for life in September 2013.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Lalit_Modi',
    sourceLabel: 'Wikipedia: Lalit Modi',
  },
  // ---------------------------------------------------------------- Kochi and Pune
  {
    id: 'cr464',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Kochi Tuskers Kerala',
    difficulty: 'simple',
    question: 'Which IPL franchise played only one season, in 2011, before the BCCI terminated it?',
    options: ['Pune Warriors India', 'Deccan Chargers', 'Kochi Tuskers Kerala', 'Gujarat Lions'],
    correctIndex: 2,
    explanation:
      'Captained by Mahela Jayawardene, Kochi finished eighth of ten; the franchise was terminated in September 2011 over an unpaid bank guarantee.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Kochi_Tuskers_Kerala',
    sourceLabel: 'Wikipedia: Kochi Tuskers Kerala',
  },
  {
    id: 'cr465',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Pune Warriors India',
    difficulty: 'extreme',
    question: 'Which group owned Pune Warriors India, the franchise that withdrew from the IPL in May 2013 over its fee?',
    options: ['Reliance', 'Videocon', 'Adani', 'Sahara'],
    correctIndex: 3,
    explanation: 'Sahara paid about 1,702 crore rupees for the franchise in 2010; Pune won only 12 of 46 matches.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pune_Warriors_India',
    sourceLabel: 'Wikipedia: Pune Warriors India',
  },
  // ---------------------------------------------------------------- IPL 2012-2013
  {
    id: 'cr466',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2012',
    difficulty: 'simple',
    question: 'Who captained Kolkata Knight Riders to their first IPL title in 2012?',
    options: ['Gautam Gambhir', 'Sourav Ganguly', 'Jacques Kallis', 'Brendon McCullum'],
    correctIndex: 0,
    explanation: 'Kolkata chased 191 at Chepauk in Chennai to beat the holders by five wickets with two balls to spare.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2012_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2012 Indian Premier League final',
  },
  {
    id: 'cr467',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2012',
    difficulty: 'expert',
    question: 'Whose 89 off 48 balls won the player-of-the-match award in the 2012 IPL final for Kolkata Knight Riders?',
    options: ['Shakib Al Hasan', 'Manvinder Bisla', 'Jacques Kallis', 'Manoj Tiwary'],
    correctIndex: 1,
    explanation: 'Suresh Raina had made 73 off 38 for Chennai; Tiwary hit the winning boundaries in the last over.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2012_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2012 Indian Premier League final',
  },
  {
    id: 'cr468',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Chris Gayle 175',
    difficulty: 'simple',
    question: 'Chris Gayle scored an unbeaten 175 for Royal Challengers Bangalore in April 2013. Who were the opponents?',
    options: ['Kochi Tuskers Kerala', 'Delhi Daredevils', 'Pune Warriors India', 'Kings XI Punjab'],
    correctIndex: 2,
    explanation: 'The innings came off 66 balls at the Chinnaswamy Stadium on 23 April 2013 and remains the highest IPL score.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Chris_Gayle',
    sourceLabel: 'Wikipedia: Chris Gayle',
  },
  {
    id: 'cr469',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Chris Gayle 175',
    difficulty: 'extreme',
    question: 'Off how many balls did Chris Gayle reach his century on the way to 175 not out in 2013?',
    options: ['17', '23', '26', '30'],
    correctIndex: 3,
    explanation: 'At the time it was the fastest hundred in any form of cricket, and it stood as the fastest in the IPL.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Chris_Gayle',
    sourceLabel: 'Wikipedia: Chris Gayle',
  },
  {
    id: 'cr470',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Chris Gayle 175',
    difficulty: 'extreme',
    question: "How many sixes did Chris Gayle hit in his 175 not out against Pune Warriors India in 2013, still the most in an IPL innings?",
    options: ['17', '15', '13', '11'],
    correctIndex: 0,
    explanation: 'He also hit 13 fours; Gayle finished his IPL career with 357 sixes, the most by any batsman.',
    sourceUrl: 'https://en.wikipedia.org/wiki/List_of_Indian_Premier_League_records_and_statistics',
    sourceLabel: 'Wikipedia: List of Indian Premier League records and statistics',
  },
  // ---------------------------------------------------------------- 2013 spot-fixing
  {
    id: 'cr471',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2013 spot-fixing',
    difficulty: 'simple',
    question: 'Sreesanth, Ajit Chandila and Ankeet Chavan were arrested for spot-fixing in May 2013. Which franchise were they playing for?',
    options: ['Chennai Super Kings', 'Rajasthan Royals', 'Pune Warriors India', 'Mumbai Indians'],
    correctIndex: 1,
    explanation: 'Delhi Police arrested the three on 16 May 2013; a Patiala House court discharged all 36 accused in July 2015.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2013_Indian_Premier_League_spot-fixing_and_betting_case',
    sourceLabel: 'Wikipedia: 2013 Indian Premier League spot-fixing case',
  },
  {
    id: 'cr472',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2013 spot-fixing',
    difficulty: 'expert',
    question: 'Gurunath Meiyappan, the Chennai Super Kings team principal arrested in the 2013 case, was related to BCCI president N. Srinivasan how?',
    options: ['Nephew', 'Brother-in-law', 'Son-in-law', 'Son'],
    correctIndex: 2,
    explanation: 'The Supreme Court-appointed Mudgal committee found in February 2014 that Meiyappan had violated the IPL anti-corruption code.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2013_Indian_Premier_League_spot-fixing_and_betting_case',
    sourceLabel: 'Wikipedia: 2013 Indian Premier League spot-fixing case',
  },
  {
    id: 'cr473',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2013 spot-fixing',
    difficulty: 'expert',
    question: 'The Lodha committee suspended Chennai Super Kings and Rajasthan Royals from the IPL for which two seasons?',
    options: ['2014 and 2015', '2015 and 2016', '2017 and 2018', '2016 and 2017'],
    correctIndex: 3,
    explanation: 'The verdict of 14 July 2015 also imposed life bans on Gurunath Meiyappan and Rajasthan co-owner Raj Kundra.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2013_Indian_Premier_League_spot-fixing_and_betting_case',
    sourceLabel: 'Wikipedia: 2013 Indian Premier League spot-fixing case',
  },
  {
    id: 'cr474',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sreesanth',
    difficulty: 'extreme',
    question: "Which body set aside Sreesanth's BCCI life ban in March 2019 and asked the board to reconsider its length?",
    options: ['Supreme Court of India', 'Kerala High Court', 'Delhi High Court', 'Court of Arbitration for Sport'],
    correctIndex: 0,
    explanation: 'The BCCI ombudsman then cut the ban to seven years in August 2019, so Sreesanth could play again from September 2020.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sreesanth',
    sourceLabel: 'Wikipedia: Sreesanth',
  },
  {
    id: 'cr475',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2013',
    difficulty: 'extreme',
    question: 'Whose unbeaten 60 off 32 balls earned the player-of-the-match award as Mumbai Indians won their first IPL title in the 2013 final?',
    options: ['Rohit Sharma', 'Kieron Pollard', 'Lasith Malinga', 'Harbhajan Singh'],
    correctIndex: 1,
    explanation: 'Mumbai recovered from 52 for 4 to 148 for 9 and beat Chennai by 23 runs at Eden Gardens on 26 May 2013.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2013_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2013 Indian Premier League final',
  },
  // ---------------------------------------------------------------- IPL 2016-2017
  {
    id: 'cr476',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Kohli 973',
    difficulty: 'simple',
    question: 'Virat Kohli scored a record 973 runs in IPL 2016. How many centuries did he make that season?',
    options: ['Two', 'Three', 'Four', 'Five'],
    correctIndex: 2,
    explanation: 'He averaged 81.08 and won both the Orange Cap and the most valuable player award, but RCB lost the final.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2016_Indian_Premier_League',
    sourceLabel: 'Wikipedia: 2016 Indian Premier League',
  },
  {
    id: 'cr477',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2016',
    difficulty: 'expert',
    question: 'Who was player of the match as Sunrisers Hyderabad beat Royal Challengers Bangalore by eight runs in the 2016 IPL final?',
    options: ['David Warner', 'Bhuvneshwar Kumar', 'Mustafizur Rahman', 'Ben Cutting'],
    correctIndex: 3,
    explanation: 'Hyderabad made 208 for 7 at the Chinnaswamy Stadium; captain Warner hit 69 and Chris Gayle 76 in reply.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2016_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2016 Indian Premier League final',
  },
  {
    id: 'cr478',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Rising Pune Supergiant',
    difficulty: 'expert',
    question: 'Who captained Rising Pune Supergiants in their first IPL season in 2016?',
    options: ['MS Dhoni', 'Steve Smith', 'Ajinkya Rahane', 'Faf du Plessis'],
    correctIndex: 0,
    explanation: 'The owners replaced him with Steve Smith for 2017, when the team dropped the final s from its name and lost the final by one run.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Rising_Pune_Supergiant',
    sourceLabel: 'Wikipedia: Rising Pune Supergiant',
  },
  {
    id: 'cr479',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Gujarat Lions',
    difficulty: 'extreme',
    question: 'Which city was the home base of Gujarat Lions, the stand-in franchise that topped the IPL table in 2016?',
    options: ['Ahmedabad', 'Rajkot', 'Vadodara', 'Surat'],
    correctIndex: 1,
    explanation: 'Owned by Intex and captained by Suresh Raina, the Lions played at the Niranjan Shah Stadium and were dissolved after 2017.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Gujarat_Lions',
    sourceLabel: 'Wikipedia: Gujarat Lions',
  },
  // ---------------------------------------------------------------- Mumbai Indians finals
  {
    id: 'cr480',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2019 final',
    difficulty: 'simple',
    question: 'Mumbai Indians beat Chennai Super Kings by one run in the 2019 IPL final. Who bowled the last over for Mumbai?',
    options: ['Jasprit Bumrah', 'Hardik Pandya', 'Lasith Malinga', 'Krunal Pandya'],
    correctIndex: 2,
    explanation: 'Shardul Thakur was lbw to the final ball in Hyderabad, leaving Chennai on 148 for 7 chasing 150.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2019_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2019 Indian Premier League final',
  },
  {
    id: 'cr481',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2019 final',
    difficulty: 'expert',
    question: 'Who was player of the match in the 2019 IPL final for figures of 2 for 14 from four overs?',
    options: ['Kieron Pollard', 'Quinton de Kock', 'Rohit Sharma', 'Jasprit Bumrah'],
    correctIndex: 3,
    explanation: 'The win was Mumbai\'s fourth title, taking them past Chennai\'s three at the time.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2019_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2019 Indian Premier League final',
  },
  {
    id: 'cr482',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2017 final',
    difficulty: 'extreme',
    question: 'Which Mumbai Indians bowler delivered the final over as they defended 129 to beat Rising Pune Supergiant by one run in the 2017 final?',
    options: ['Mitchell Johnson', 'Jasprit Bumrah', 'Lasith Malinga', 'Hardik Pandya'],
    correctIndex: 0,
    explanation: 'Washington Sundar was run out attempting a third run off the last ball; Krunal Pandya was player of the match for his 47.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2017_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2017 Indian Premier League final',
  },
  {
    id: 'cr483',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2020',
    difficulty: 'simple',
    question: 'The 2020 IPL was played entirely outside India because of the COVID-19 pandemic. Where was it held?',
    options: ['Sri Lanka', 'United Arab Emirates', 'South Africa', 'Oman'],
    correctIndex: 1,
    explanation: 'Matches ran from 19 September to 10 November 2020 in Dubai, Sharjah and Abu Dhabi, with no spectators.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2020_Indian_Premier_League',
    sourceLabel: 'Wikipedia: 2020 Indian Premier League',
  },
  {
    id: 'cr484',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2020',
    difficulty: 'expert',
    question: 'Who was player of the match in the 2020 IPL final in Dubai for taking 3 for 30 against Delhi Capitals?',
    options: ['Rohit Sharma', 'Jasprit Bumrah', 'Trent Boult', 'Ishan Kishan'],
    correctIndex: 2,
    explanation: 'Mumbai chased 157 with five wickets to spare for a fifth title; captain Rohit Sharma made 68.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2020_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2020 Indian Premier League final',
  },
  // ---------------------------------------------------------------- Chennai's later titles
  {
    id: 'cr485',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2018 final',
    difficulty: 'extreme',
    question: 'Who captained Sunrisers Hyderabad in the 2018 IPL final, which Chennai Super Kings won by eight wickets on their return from suspension?',
    options: ['David Warner', 'Shikhar Dhawan', 'Bhuvneshwar Kumar', 'Kane Williamson'],
    correctIndex: 3,
    explanation: 'Shane Watson made 117 not out off 57 balls at the Wankhede as Chennai chased 179 with 11 balls to spare.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2018_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2018 Indian Premier League final',
  },
  {
    id: 'cr486',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2021 final',
    difficulty: 'extreme',
    question: 'Whose 86 off 59 balls won the player-of-the-match award as Chennai Super Kings beat Kolkata Knight Riders in the 2021 final in Dubai?',
    options: ['Faf du Plessis', 'Ruturaj Gaikwad', 'Shardul Thakur', 'Moeen Ali'],
    correctIndex: 0,
    explanation: 'Chennai made 192 for 3 and won by 27 runs on 15 October 2021 for their fourth title.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2021_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2021 Indian Premier League final',
  },
  // ---------------------------------------------------------------- IPL 2022
  {
    id: 'cr487',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2022',
    difficulty: 'simple',
    question: 'Who captained Gujarat Titans to the IPL title in their very first season in 2022?',
    options: ['Shubman Gill', 'Hardik Pandya', 'Rashid Khan', 'David Miller'],
    correctIndex: 1,
    explanation: 'Pandya took 3 for 17 and made 34 as Gujarat beat Rajasthan Royals by seven wickets before 104,859 people in Ahmedabad.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2022_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2022 Indian Premier League final',
  },
  {
    id: 'cr488',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2022 mega auction',
    difficulty: 'expert',
    question: 'Who was the most expensive buy at the February 2022 mega auction, at 15.25 crore rupees to Mumbai Indians?',
    options: ['Deepak Chahar', 'Shreyas Iyer', 'Ishan Kishan', 'Liam Livingstone'],
    correctIndex: 2,
    explanation: 'The 2022 season was the first with ten teams and 74 matches; Jos Buttler won the Orange Cap with 863 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2022_Indian_Premier_League',
    sourceLabel: 'Wikipedia: 2022 Indian Premier League',
  },
  {
    id: 'cr489',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2022 expansion',
    difficulty: 'extreme',
    question: 'Which group paid about 7,090 crore rupees for the Lucknow franchise when the IPL expanded to ten teams for 2022?',
    options: ['CVC Capital', 'Adani Group', 'Torrent Group', 'RPSG Group'],
    correctIndex: 3,
    explanation: 'CVC Capital paid about 5,625 crore rupees for the Ahmedabad franchise that became Gujarat Titans.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2022_Indian_Premier_League',
    sourceLabel: 'Wikipedia: 2022 Indian Premier League',
  },
  // ---------------------------------------------------------------- IPL 2023-2024
  {
    id: 'cr490',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2023 final',
    difficulty: 'simple',
    question: 'Ravindra Jadeja needed 10 off the last two balls to win the 2023 IPL final for Chennai Super Kings. Which Gujarat Titans bowler was he facing?',
    options: ['Mohit Sharma', 'Mohammed Shami', 'Rashid Khan', 'Hardik Pandya'],
    correctIndex: 0,
    explanation: 'He hit a six over long-off and then a four behind square leg; the final had been pushed to a reserve day by rain for the first time.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2023 Indian Premier League final',
  },
  {
    id: 'cr491',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Impact Player rule',
    difficulty: 'expert',
    question: 'In which IPL season was the Impact Player substitution rule introduced?',
    options: ['2022', '2023', '2024', '2021'],
    correctIndex: 1,
    explanation: 'Teams name their substitutes before the first ball and may bring one in before the 14th over, to bat or bowl a full share.',
    sourceUrl: 'https://www.royalchallengers.com/rcb-cricket-news/news/explained-the-impact-player-rule-set-to-be-introduced-in-ipl-2023',
    sourceLabel: 'Royal Challengers Bengaluru: Explained, the Impact Player rule set to be introduced in IPL 2023',
  },
  {
    id: 'cr492',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2024',
    difficulty: 'simple',
    question: 'Who captained Kolkata Knight Riders to their third IPL title in 2024?',
    options: ['Nitish Rana', 'Gautam Gambhir', 'Shreyas Iyer', 'Rinku Singh'],
    correctIndex: 2,
    explanation: 'Kolkata bowled Sunrisers Hyderabad out for 113 in Chennai and won in 10.3 overs, the shortest IPL final; Mitchell Starc was player of the match.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2024_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2024 Indian Premier League final',
  },
  {
    id: 'cr493',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL records',
    difficulty: 'expert',
    question: 'Who scored a 41-ball hundred as Sunrisers Hyderabad posted the record IPL total of 287 for 3 against Royal Challengers Bengaluru in April 2024?',
    options: ['Abhishek Sharma', 'Heinrich Klaasen', 'Aiden Markram', 'Travis Head'],
    correctIndex: 3,
    explanation: 'Klaasen added 67 off 31 at the Chinnaswamy on 15 April 2024; the previous record was Hyderabad\'s own 277 against Mumbai 20 days earlier.',
    sourceUrl: 'https://www.tbsnews.net/sports/srh-slams-287-vs-rcb-shatter-their-own-highest-ipl-total-828706',
    sourceLabel: 'The Business Standard: SRH slams 287 vs RCB, shatter their own highest IPL total',
  },
  // ---------------------------------------------------------------- IPL 2025-2026
  {
    id: 'cr494',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2025 final',
    difficulty: 'simple',
    question: 'Who captained Royal Challengers Bengaluru to their first IPL title in 2025?',
    options: ['Rajat Patidar', 'Virat Kohli', 'Faf du Plessis', 'Phil Salt'],
    correctIndex: 0,
    explanation: 'Bengaluru beat Punjab Kings by six runs in Ahmedabad on 3 June 2025; Krunal Pandya was player of the match with 2 for 17.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2025_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2025 Indian Premier League final',
  },
  {
    id: 'cr495',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Bengaluru crowd crush',
    difficulty: 'expert',
    question: 'How many people died in the crowd crush outside the M. Chinnaswamy Stadium on 4 June 2025, the day after Royal Challengers Bengaluru won their first IPL title?',
    options: ['7', '11', '15', '21'],
    correctIndex: 1,
    explanation: 'A further 56 people were injured as an estimated 250,000 gathered for the felicitation; the open-top bus parade was cancelled.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2025_Bengaluru_stampede',
    sourceLabel: 'Wikipedia: 2025 Bengaluru stampede',
  },
  {
    id: 'cr496',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2026 final',
    difficulty: 'simple',
    question: 'Royal Challengers Bengaluru retained the IPL title in 2026. Which team did they beat in the final in Ahmedabad on 31 May?',
    options: ['Punjab Kings', 'Rajasthan Royals', 'Gujarat Titans', 'Mumbai Indians'],
    correctIndex: 2,
    explanation: 'Bengaluru chased 156 with five wickets and 12 balls to spare; Virat Kohli was player of the match with 75 not out off 42.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2026_Indian_Premier_League_final',
    sourceLabel: 'Wikipedia: 2026 Indian Premier League final',
  },
  {
    id: 'cr497',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL 2025 mega auction',
    difficulty: 'expert',
    question: 'Which franchise paid a record 27 crore rupees for Rishabh Pant at the November 2024 mega auction in Jeddah?',
    options: ['Delhi Capitals', 'Sunrisers Hyderabad', 'Royal Challengers Bengaluru', 'Lucknow Super Giants'],
    correctIndex: 3,
    explanation: 'Pant left Delhi Capitals after nine years; Shreyas Iyer went to Punjab Kings for 26.75 crore at the same auction.',
    sourceUrl: 'https://www.outlookindia.com/sports/cricket/ipl-auction-2025-full-list-of-a-z-player-facts-from-the-indian-premier-league-event-held-in-jeddah-saudi-arabia-rishabh-pant-kl-rahul',
    sourceLabel: 'Outlook India: IPL Auction 2025, A to Z of the event held in Jeddah',
  },
  {
    id: 'cr498',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL records',
    difficulty: 'extreme',
    question: 'Who set the record for the fastest IPL fifty, off 13 balls, against Kolkata Knight Riders at Eden Gardens in May 2023?',
    options: ['Yashasvi Jaiswal', 'KL Rahul', 'Pat Cummins', 'Abhishek Sharma'],
    correctIndex: 0,
    explanation: 'He went on to 98 not out for Rajasthan Royals; Urvil Patel of Chennai Super Kings equalled the 13-ball mark in 2026.',
    sourceUrl: 'https://sports.yahoo.com/articles/fastest-fifties-ipl-history-full-130114052.html',
    sourceLabel: 'Yahoo Sports: Fastest fifties in IPL history',
  },
  {
    id: 'cr499',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'IPL records',
    difficulty: 'extreme',
    question: 'Which bowler stood as the IPL\'s leading wicket-taker at the end of the 2026 season, with 233 wickets?',
    options: ['Bhuvneshwar Kumar', 'Yuzvendra Chahal', 'Piyush Chawla', 'Dwayne Bravo'],
    correctIndex: 1,
    explanation: 'Virat Kohli led the run charts with 9,336, and Mumbai Indians and Chennai Super Kings shared the most titles with five each.',
    sourceUrl: 'https://en.wikipedia.org/wiki/List_of_Indian_Premier_League_records_and_statistics',
    sourceLabel: 'Wikipedia: List of Indian Premier League records and statistics',
  },
]);
