// Server-only editorial bank: Cricket, India tranche 9 — the history of Indian women's cricket (50 questions).
// Never import this module from client components.
// Every fact below was checked against the page at sourceUrl when written.
export const CRICKET_INDIA_9 = Object.freeze([
  // ---------------------------------------------------------------- Beginnings: WCAI and the first Tests
  {
    id: 'cr500',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Women's Cricket Association of India",
    difficulty: 'simple',
    question: "In which year was the Women's Cricket Association of India, the body that ran the women's game before the BCCI took over, founded?",
    options: ['1965', '1973', '1978', '1983'],
    correctIndex: 1,
    explanation: "The WCAI was set up in Lucknow by Mahendra Kumar Sharma, and India's first inter-state women's nationals were played in Pune that April.",
    sourceUrl: "https://en.wikipedia.org/wiki/Women%27s_Cricket_Association_of_India",
    sourceLabel: "Wikipedia: Women's Cricket Association of India",
  },
  {
    id: 'cr501',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Women's Cricket Association of India",
    difficulty: 'extreme',
    question: "In which city did Mahendra Kumar Sharma register the Women's Cricket Association of India under the Societies Act in 1973?",
    options: ['Pune', 'Mumbai', 'Lucknow', 'Delhi'],
    correctIndex: 2,
    explanation: 'Sharma promoted his first tournament by touring the city in an auto rickshaw with a microphone; Hamida Habibullah was the first WCAI president.',
    sourceUrl: "https://en.wikipedia.org/wiki/Women%27s_Cricket_Association_of_India",
    sourceLabel: "Wikipedia: Women's Cricket Association of India",
  },
  {
    id: 'cr502',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Women's Test history",
    difficulty: 'simple',
    question: "Against which touring side did India's women play their first ever Test match, in October 1976?",
    options: ['West Indies', 'England', 'Australia', 'New Zealand'],
    correctIndex: 0,
    explanation: 'The tourists played a six-Test series that was drawn 1-1, with Louise Browne captaining the visitors.',
    sourceUrl: 'https://en.wikipedia.org/wiki/West_Indies_women%27s_cricket_team_in_India_in_1976%E2%80%9377',
    sourceLabel: "Wikipedia: West Indies women's cricket team in India in 1976-77",
  },
  {
    id: 'cr503',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Women's Test history",
    difficulty: 'extreme',
    question: "Which ground staged India women's inaugural Test, a draw that began on 31 October 1976?",
    options: ['Eden Gardens, Calcutta', 'Brabourne Stadium, Bombay', 'Chepauk, Madras', 'M. Chinnaswamy Stadium, Bangalore'],
    correctIndex: 3,
    explanation: 'The three-day match ended in a draw; the sixth and final Test of the series was played in Jammu.',
    sourceUrl: 'https://en.wikipedia.org/wiki/West_Indies_women%27s_cricket_team_in_India_in_1976%E2%80%9377',
    sourceLabel: "Wikipedia: West Indies women's cricket team in India in 1976-77",
  },
  {
    id: 'cr504',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Women's Test history",
    difficulty: 'extreme',
    question: "India women recorded their first Test victory, by five wickets, in the fourth Test of the 1976 series against West Indies. Where was it played?",
    options: ['Jammu', 'Patna', 'Delhi', 'Hyderabad'],
    correctIndex: 1,
    explanation: 'The win at the Moin-ul-Haq Stadium on 19 November 1976 came in front of a reported 25,000 spectators.',
    sourceUrl: "https://en.wikipedia.org/wiki/Women%27s_Cricket_Association_of_India",
    sourceLabel: "Wikipedia: Women's Cricket Association of India",
  },
  {
    id: 'cr505',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Shantha Rangaswamy',
    difficulty: 'simple',
    question: "Who was India's first women's Test captain, and also the first Indian woman to score a Test century?",
    options: ['Diana Edulji', 'Shubhangi Kulkarni', 'Shantha Rangaswamy', 'Sudha Shah'],
    correctIndex: 2,
    explanation: 'Her 108 against New Zealand at Carisbrook, Dunedin, in January 1977 was the first Test hundred by an Indian woman.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Shantha_Rangaswamy',
    sourceLabel: 'Wikipedia: Shantha Rangaswamy',
  },
  {
    id: 'cr506',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'ICC Hall of Fame',
    difficulty: 'simple',
    question: 'Who became the first Indian woman inducted into the ICC Cricket Hall of Fame, in 2023?',
    options: ['Mithali Raj', 'Diana Edulji', 'Jhulan Goswami', 'Shantha Rangaswamy'],
    correctIndex: 1,
    explanation: 'The left-arm spinner was inductee number 111, honoured at the Wankhede Stadium alongside Virender Sehwag and Aravinda de Silva.',
    sourceUrl: 'https://www.icc-cricket.com/media-releases/icc-hall-of-fame-welcomes-de-silva-edulji-and-sehwag-as-class-of-2023-inductees',
    sourceLabel: 'ICC: Hall of Fame welcomes De Silva, Edulji and Sehwag as Class of 2023 inductees',
  },
  {
    id: 'cr507',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "1978 Women's World Cup",
    difficulty: 'expert',
    question: "India hosted the 1978 Women's World Cup, a four-team round robin. Which side went through it unbeaten to lift the trophy?",
    options: ['Australia', 'England', 'New Zealand', 'India'],
    correctIndex: 0,
    explanation: "It was the first international tournament staged in India; the hosts, captained by Diana Edulji, lost all three of their matches.",
    sourceUrl: 'https://en.wikipedia.org/wiki/1978_Women%27s_Cricket_World_Cup',
    sourceLabel: "Wikipedia: 1978 Women's Cricket World Cup",
  },
  {
    id: 'cr508',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sandhya Agarwal',
    difficulty: 'expert',
    question: "Sandhya Agarwal's 190 at Worcester in 1986, then the highest score in women's Test cricket, came against which team?",
    options: ['Australia', 'New Zealand', 'West Indies', 'England'],
    correctIndex: 3,
    explanation: "It beat Betty Snowball's 189, a record that had stood since 1935; Denise Annetts passed it with 193 the following year.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Sandhya_Agarwal',
    sourceLabel: 'Wikipedia: Sandhya Agarwal',
  },
  {
    id: 'cr509',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Shubhangi Kulkarni',
    difficulty: 'extreme',
    question: "Which former India leg-spinner, who took 60 Test wickets, was secretary of the WCAI when it merged into the BCCI in 2006?",
    options: ['Sudha Shah', 'Sandhya Agarwal', 'Shantha Rangaswamy', 'Shubhangi Kulkarni'],
    correctIndex: 3,
    explanation: 'Kulkarni took a five-wicket haul in the first Test innings she bowled and won the Arjuna Award in 1985.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Shubhangi_Kulkarni',
    sourceLabel: 'Wikipedia: Shubhangi Kulkarni',
  },
  // ---------------------------------------------------------------- BCCI era, pioneers and record-holders
  {
    id: 'cr510',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'BCCI takeover of women\'s cricket',
    difficulty: 'simple',
    question: "In which year did the Women's Cricket Association of India merge into the BCCI, bringing the women's game under the men's board?",
    options: ['2003', '2006', '2009', '2012'],
    correctIndex: 1,
    explanation: 'The merger in November followed the International Women\'s Cricket Council folding into the ICC in 2005.',
    sourceUrl: "https://en.wikipedia.org/wiki/Women%27s_Cricket_Association_of_India",
    sourceLabel: "Wikipedia: Women's Cricket Association of India",
  },
  {
    id: 'cr511',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Purnima Rau',
    difficulty: 'extreme',
    question: "Which former captain, who led India in Tests and ODIs in 1995, was head coach of the women's national team from 2014 to 2017?",
    options: ['Purnima Rau', 'Anju Jain', 'Sudha Shah', 'Anjum Chopra'],
    correctIndex: 0,
    explanation: 'The Secunderabad-born all-rounder was noted as one of the first Indian women to attack the fielding restrictions in the opening 15 overs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Purnima_Rau',
    sourceLabel: 'Wikipedia: Purnima Rau',
  },
  {
    id: 'cr512',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Anjum Chopra',
    difficulty: 'expert',
    question: 'Who was the first woman to play 100 one-day internationals for India?',
    options: ['Mithali Raj', 'Anju Jain', 'Anjum Chopra', 'Jhulan Goswami'],
    correctIndex: 2,
    explanation: 'She finished with 127 ODIs across 18 years and in 2016 became the first Indian woman cricketer given honorary MCC membership.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Anjum_Chopra',
    sourceLabel: 'Wikipedia: Anjum Chopra',
  },
  {
    id: 'cr513',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Neetu David',
    difficulty: 'extreme',
    question: "Neetu David, whose 8 for 53 against England in 1995 remains the best figures in a women's Test innings, entered the ICC Hall of Fame in which year?",
    options: ['2022', '2023', '2024', '2025'],
    correctIndex: 2,
    explanation: 'India lost that Test by two runs despite her nine wickets in the match; she was later the first Indian to 100 women\'s ODI wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Neetu_David',
    sourceLabel: 'Wikipedia: Neetu David',
  },
  {
    id: 'cr514',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Mithali Raj',
    difficulty: 'expert',
    question: 'Against which team did a 16-year-old Mithali Raj score an unbeaten 114 on her ODI debut in June 1999?',
    options: ['Netherlands', 'Ireland', 'Sri Lanka', 'Denmark'],
    correctIndex: 1,
    explanation: 'She went on to play 232 ODIs and retire in June 2022 after 23 years of international cricket.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mithali_Raj',
    sourceLabel: 'Wikipedia: Mithali Raj',
  },
  {
    id: 'cr515',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Mithali Raj',
    difficulty: 'simple',
    question: "At which English ground did a 19-year-old Mithali Raj make 214 against England in 2002, then the highest score in women's Tests?",
    options: ['Taunton', 'Worcester', 'Leicester', 'Bristol'],
    correctIndex: 0,
    explanation: "The innings at the County Ground broke Karen Rolton's record of 209 not out.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Mithali_Raj',
    sourceLabel: 'Wikipedia: Mithali Raj',
  },
  {
    id: 'cr516',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Mithali Raj',
    difficulty: 'expert',
    question: 'Mithali Raj is the only woman to have captained India in more than one ODI World Cup final. Which two editions were they?',
    options: ['2000 and 2005', '2009 and 2013', '2013 and 2017', '2005 and 2017'],
    correctIndex: 3,
    explanation: 'India lost both finals to Australia at Centurion and to England at Lord\'s.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mithali_Raj',
    sourceLabel: 'Wikipedia: Mithali Raj',
  },
  {
    id: 'cr517',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Mithali Raj',
    difficulty: 'extreme',
    question: "Whose record of 10,273 runs did Mithali Raj pass during the 2021 England tour to become the leading run-scorer in women's international cricket?",
    options: ['Belinda Clark', 'Charlotte Edwards', 'Suzie Bates', 'Meg Lanning'],
    correctIndex: 1,
    explanation: 'She reached the mark in the third ODI of that series; four years earlier she had passed the same player\'s ODI record of 5,992.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_women%27s_cricket_team_in_England_in_2021',
    sourceLabel: "Wikipedia: Indian women's cricket team in England in 2021",
  },
  {
    id: 'cr518',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Jhulan Goswami',
    difficulty: 'simple',
    question: "At which ground did Jhulan Goswami, the leading wicket-taker in women's ODIs, play her farewell international in September 2022?",
    options: ['Eden Gardens', 'The Oval', "Lord's", 'Wankhede Stadium'],
    correctIndex: 2,
    explanation: 'India won that third ODI by 16 runs to complete a 3-0 series sweep; she retired with 255 ODI wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Jhulan_Goswami',
    sourceLabel: 'Wikipedia: Jhulan Goswami',
  },
  {
    id: 'cr519',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "2005 Women's World Cup",
    difficulty: 'simple',
    question: "India reached their first Women's World Cup final in 2005 at Centurion. Who beat them by 98 runs?",
    options: ['Australia', 'England', 'New Zealand', 'South Africa'],
    correctIndex: 0,
    explanation: 'Karen Rolton made 107 not out; India had beaten New Zealand by 40 runs in the semi-final with Mithali Raj scoring 91 not out.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2005_Women%27s_Cricket_World_Cup',
    sourceLabel: "Wikipedia: 2005 Women's Cricket World Cup",
  },
  // ---------------------------------------------------------------- 2017 World Cup and the 2020 MCG final
  {
    id: 'cr520',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "2017 Women's World Cup",
    difficulty: 'simple',
    question: "Harmanpreet Kaur's 171 not out off 115 balls in the 2017 World Cup semi-final at Derby came against which team?",
    options: ['England', 'New Zealand', 'Australia', 'South Africa'],
    correctIndex: 2,
    explanation: "India won the rain-shortened 42-over match by 36 runs; it remains the highest score by a woman in a World Cup knockout.",
    sourceUrl: 'https://en.wikipedia.org/wiki/2017_Women%27s_Cricket_World_Cup',
    sourceLabel: "Wikipedia: 2017 Women's Cricket World Cup",
  },
  {
    id: 'cr521',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "2017 Women's World Cup",
    difficulty: 'simple',
    question: "By how many runs did India lose the 2017 Women's World Cup final to England at Lord's?",
    options: ['9 runs', '19 runs', '29 runs', '39 runs'],
    correctIndex: 0,
    explanation: 'Chasing 229, India were bowled out for 219; Anya Shrubsole took 6 for 46, the best figures in any World Cup final.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2017_Women%27s_Cricket_World_Cup_final',
    sourceLabel: "Wikipedia: 2017 Women's Cricket World Cup final",
  },
  {
    id: 'cr522',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "2017 Women's World Cup",
    difficulty: 'expert',
    question: "Who top-scored for India with 86 off 115 balls in the 2017 World Cup final before the collapse of seven wickets for 28 runs?",
    options: ['Smriti Mandhana', 'Punam Raut', 'Veda Krishnamurthy', 'Deepti Sharma'],
    correctIndex: 1,
    explanation: 'Her dismissal at 191 for 4 triggered the slide; India needed 11 from the last two overs and managed one run.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2017_Women%27s_Cricket_World_Cup_final',
    sourceLabel: "Wikipedia: 2017 Women's Cricket World Cup final",
  },
  {
    id: 'cr523',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Deepti Sharma',
    difficulty: 'extreme',
    question: "Deepti Sharma's 188 against Ireland in 2017 came in a world-record 320-run opening partnership with which batter?",
    options: ['Mithali Raj', 'Smriti Mandhana', 'Mona Meshram', 'Punam Raut'],
    correctIndex: 3,
    explanation: 'Deepti, born in Agra, was spotted by a selector after a direct hit on the stumps from about 50 metres in practice.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Deepti_Sharma',
    sourceLabel: 'Wikipedia: Deepti Sharma',
  },
  {
    id: 'cr524',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2020 T20 World Cup final',
    difficulty: 'simple',
    question: "What was the attendance at the MCG for the 2020 Women's T20 World Cup final between Australia and India, a record for a women's cricket match?",
    options: ['86,174', '76,174', '96,174', '66,174'],
    correctIndex: 0,
    explanation: 'Australia made 184 for 4 and bowled India out for 99; Katy Perry performed before the match on International Women\'s Day.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2020_ICC_Women%27s_T20_World_Cup_final',
    sourceLabel: "Wikipedia: 2020 ICC Women's T20 World Cup final",
  },
  {
    id: 'cr525',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Poonam Yadav',
    difficulty: 'expert',
    question: "Which leg-spinner took 4 for 19 as India beat Australia by 17 runs in the opening match of the 2020 T20 World Cup in Sydney?",
    options: ['Radha Yadav', 'Poonam Yadav', 'Rajeshwari Gayakwad', 'Deepti Sharma'],
    correctIndex: 1,
    explanation: 'She finished the tournament with 10 wickets, second only to Megan Schutt, and had become India\'s leading T20I wicket-taker in 2018.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2020_ICC_Women%27s_T20_World_Cup',
    sourceLabel: "Wikipedia: 2020 ICC Women's T20 World Cup",
  },
  {
    id: 'cr526',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Shafali Verma',
    difficulty: 'simple',
    question: "Which 16-year-old opener went into the 2020 T20 World Cup ranked the number one batter in women's T20Is?",
    options: ['Jemimah Rodrigues', 'Richa Ghosh', 'Smriti Mandhana', 'Shafali Verma'],
    correctIndex: 3,
    explanation: 'She made 163 runs in the tournament, having become the youngest Indian to score an international fifty in November 2019.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Shafali_Verma',
    sourceLabel: 'Wikipedia: Shafali Verma',
  },
  {
    id: 'cr527',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Women's Test history",
    difficulty: 'expert',
    question: 'Shafali Verma scored 96 and 63 on Test debut in June 2021, India\'s first women\'s Test since 2014. Where was it played?',
    options: ['Bristol', 'Taunton', 'Worcester', 'Canterbury'],
    correctIndex: 0,
    explanation: 'India followed on and batted out a draw at 344 for 8, with Sneh Rana unbeaten on 80.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_women%27s_cricket_team_in_England_in_2021',
    sourceLabel: "Wikipedia: Indian women's cricket team in England in 2021",
  },
  {
    id: 'cr528',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Women's Test history",
    difficulty: 'expert',
    question: "Who scored 127 in India's first day-night pink-ball Test, a draw against Australia on the Gold Coast in October 2021?",
    options: ['Harmanpreet Kaur', 'Smriti Mandhana', 'Punam Raut', 'Shafali Verma'],
    correctIndex: 1,
    explanation: 'The innings at Carrara Oval was the first century by an Indian woman in a pink-ball Test and earned her player of the match.',
    sourceUrl: 'https://www.wionews.com/sports/pink-ball-test-indias-smriti-mandhana-rates-her-stunning-127-run-knock-in-as-top-three-against-australia-417945',
    sourceLabel: "WION: Smriti Mandhana rates her stunning 127-run knock as 'top three' against Australia",
  },
  {
    id: 'cr529',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2022 Commonwealth Games',
    difficulty: 'expert',
    question: "India took silver at the 2022 Commonwealth Games, losing the final to Australia by nine runs. Which ground hosted the Birmingham cricket tournament?",
    options: ["Lord's", 'The Oval', 'Edgbaston', 'Old Trafford'],
    correctIndex: 2,
    explanation: 'It was cricket\'s first Commonwealth Games appearance since 1998 and the first women\'s T20 event at the Games; India beat England by four runs in the semi-final.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Cricket_at_the_2022_Commonwealth_Games',
    sourceLabel: 'Wikipedia: Cricket at the 2022 Commonwealth Games',
  },
  // ---------------------------------------------------------------- 2022: pay parity, Lord's run-out, the WPL
  {
    id: 'cr530',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Renuka Singh',
    difficulty: 'extreme',
    question: "Which Himachal seamer was the leading wicket-taker at the 2022 Commonwealth Games with 11, including 4 for 18 against Australia?",
    options: ['Deepti Sharma', 'Sneh Rana', 'Pooja Vastrakar', 'Renuka Singh'],
    correctIndex: 3,
    explanation: "She was named ICC Emerging Cricketer of the Year for 2022 and took her first T20I five-for against England at the 2023 T20 World Cup.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Renuka_Singh_Thakur',
    sourceLabel: 'Wikipedia: Renuka Singh (cricketer)',
  },
  {
    id: 'cr531',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'BCCI equal match fees',
    difficulty: 'expert',
    question: 'Under the pay-equity policy Jay Shah announced on 27 October 2022, what match fee does an India woman cricketer receive for a Test, the same as the men?',
    options: ['Rs 15 lakh', 'Rs 10 lakh', 'Rs 6 lakh', 'Rs 3 lakh'],
    correctIndex: 0,
    explanation: 'ODIs pay Rs 6 lakh and T20Is Rs 3 lakh; New Zealand Cricket had agreed an equal-pay deal with its players three months earlier.',
    sourceUrl: 'https://www.onmanorama.com/sports/cricket/2022/10/27/bcci-men-women-equal-pay.html',
    sourceLabel: 'Onmanorama: Landmark decision: BCCI to pay equal fee to Indian men, women cricketers',
  },
  {
    id: 'cr532',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Deepti Sharma',
    difficulty: 'simple',
    question: "Deepti Sharma ended the third ODI at Lord's in September 2022 by running out which England batter at the non-striker's end?",
    options: ['Sophie Ecclestone', 'Charlie Dean', 'Kate Cross', 'Freya Davies'],
    correctIndex: 1,
    explanation: "England were all out for 153 chasing 170, India won by 16 runs, and the MCC later said the dismissal was plainly within the Laws.",
    sourceUrl: 'https://en.wikipedia.org/wiki/India_women%27s_cricket_team_in_England_in_2022',
    sourceLabel: "Wikipedia: India women's cricket team in England in 2022",
  },
  {
    id: 'cr533',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'WPL 2023',
    difficulty: 'simple',
    question: "Who was the most expensive buy at the first Women's Premier League auction in 2023, going to Royal Challengers Bangalore for Rs 3.4 crore?",
    options: ['Harmanpreet Kaur', 'Deepti Sharma', 'Jemimah Rodrigues', 'Smriti Mandhana'],
    correctIndex: 3,
    explanation: 'The five franchises had been sold for about Rs 4,670 crore, and 87 players were bought for a combined Rs 59.5 crore.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Women%27s_Premier_League_(cricket)',
    sourceLabel: "Wikipedia: Women's Premier League (cricket)",
  },
  {
    id: 'cr534',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'WPL 2023',
    difficulty: 'simple',
    question: "Which franchise won the inaugural Women's Premier League in 2023, beating Delhi Capitals by seven wickets at the Brabourne Stadium?",
    options: ['Mumbai Indians', 'Delhi Capitals', 'Royal Challengers Bangalore', 'UP Warriorz'],
    correctIndex: 0,
    explanation: 'Harmanpreet Kaur captained the winners; Nat Sciver-Brunt was player of the final and Hayley Matthews player of the tournament.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_Women%27s_Premier_League_(cricket)',
    sourceLabel: "Wikipedia: 2023 Women's Premier League (cricket)",
  },
  {
    id: 'cr535',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Women's Premier League",
    difficulty: 'expert',
    question: "Which franchise reached the final of each of the first four Women's Premier League seasons, from 2023 to 2026, and lost all of them?",
    options: ['Gujarat Giants', 'Delhi Capitals', 'UP Warriorz', 'Royal Challengers Bengaluru'],
    correctIndex: 1,
    explanation: 'They lost to Mumbai Indians in 2023 and 2025 and to Royal Challengers Bengaluru in 2024 and 2026.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Women%27s_Premier_League_(cricket)',
    sourceLabel: "Wikipedia: Women's Premier League (cricket)",
  },
  {
    id: 'cr536',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'WPL 2026',
    difficulty: 'expert',
    question: "Who was player of the match in the 2026 WPL final in Vadodara with 87 off 41 balls as Royal Challengers Bengaluru chased down 204?",
    options: ['Georgia Voll', 'Jemimah Rodrigues', 'Smriti Mandhana', 'Ellyse Perry'],
    correctIndex: 2,
    explanation: 'RCB won by six wickets with two balls to spare for their second title; Sophie Devine of Gujarat Giants was player of the tournament.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2026_Women%27s_Premier_League_(cricket)',
    sourceLabel: "Wikipedia: 2026 Women's Premier League (cricket)",
  },
  {
    id: 'cr537',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2023 T20 World Cup semi-final',
    difficulty: 'extreme',
    question: "By how many runs did India lose the 2023 T20 World Cup semi-final to Australia at Newlands, Cape Town, after Harmanpreet Kaur was run out for 52?",
    options: ['5', '3', '7', '9'],
    correctIndex: 0,
    explanation: 'Australia made 172 for 4 and India finished on 167 for 8; Australia then beat hosts South Africa in the final for a third straight title.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_ICC_Women%27s_T20_World_Cup',
    sourceLabel: "Wikipedia: 2023 ICC Women's T20 World Cup",
  },
  {
    id: 'cr538',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Under-19 T20 World Cup 2023',
    difficulty: 'simple',
    question: "Who captained India to the inaugural Under-19 Women's T20 World Cup title, a seven-wicket win over England in Potchefstroom in January 2023?",
    options: ['Richa Ghosh', 'Shweta Sehrawat', 'Shafali Verma', 'Titas Sadhu'],
    correctIndex: 2,
    explanation: 'Shweta Sehrawat was the tournament\'s leading run-scorer with 297; Grace Scrivens of England was player of the tournament.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2023_ICC_Under-19_Women%27s_T20_World_Cup',
    sourceLabel: "Wikipedia: 2023 ICC Under-19 Women's T20 World Cup",
  },
  {
    id: 'cr539',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Under-19 T20 World Cup 2025',
    difficulty: 'extreme',
    question: "Who was player of the tournament with 309 runs as India retained the Under-19 Women's T20 World Cup in Malaysia in 2025?",
    options: ['Gongadi Trisha', 'Vaishnavi Sharma', 'Niki Prasad', 'Kamalini G'],
    correctIndex: 0,
    explanation: 'India beat South Africa by nine wickets in the final at Bayuemas Oval; Vaishnavi Sharma took the most wickets with 17.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2025_ICC_Under-19_Women%27s_T20_World_Cup',
    sourceLabel: "Wikipedia: 2025 ICC Under-19 Women's T20 World Cup",
  },
  // ---------------------------------------------------------------- December 2023 Tests, the 2025 World Cup, Asia Cups
  {
    id: 'cr540',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Home Tests December 2023',
    difficulty: 'extreme',
    question: "India beat England at the DY Patil Stadium in December 2023 by the largest margin in women's Test history. What was it?",
    options: ['147 runs', '247 runs', '447 runs', '347 runs'],
    correctIndex: 3,
    explanation: 'Deepti Sharma took 5 for 7 in England\'s first innings of 136 and nine wickets in the match, plus 67 runs, in England\'s 100th women\'s Test.',
    sourceUrl: 'https://en.wikipedia.org/wiki/English_women%27s_cricket_team_in_India_in_2023%E2%80%9324',
    sourceLabel: "Wikipedia: English women's cricket team in India in 2023-24",
  },
  {
    id: 'cr541',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Home Tests December 2023',
    difficulty: 'extreme',
    question: "Which spinner was player of the match when India beat Australia by eight wickets at the Wankhede in December 2023, their first Test win over Australia?",
    options: ['Pooja Vastrakar', 'Deepti Sharma', 'Sneh Rana', 'Rajeshwari Gayakwad'],
    correctIndex: 2,
    explanation: 'It was India women\'s first win over Australia in 11 Tests since 1977; India made 406 in the first innings and Rana took two wickets in two balls on the final day.',
    sourceUrl: 'https://gulfnews.com/sport/cricket/india-women-beat-australia-by-eight-wickets-in-historic-test-1.100095433',
    sourceLabel: 'Gulf News: India women beat Australia by eight wickets in historic Test',
  },
  {
    id: 'cr542',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "2025 Women's World Cup",
    difficulty: 'simple',
    question: "Whom did India beat by 52 runs at the DY Patil Stadium, Navi Mumbai, on 2 November 2025 to win their first Women's ODI World Cup?",
    options: ['Australia', 'England', 'New Zealand', 'South Africa'],
    correctIndex: 3,
    explanation: "India made 298 for 7 and bowled the opposition out for 246; it was the first women's World Cup final without Australia or England.",
    sourceUrl: 'https://en.wikipedia.org/wiki/2025_Women%27s_Cricket_World_Cup_final',
    sourceLabel: "Wikipedia: 2025 Women's Cricket World Cup final",
  },
  {
    id: 'cr543',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "2025 Women's World Cup",
    difficulty: 'expert',
    question: "Who was player of the match in the 2025 Women's World Cup final, scoring 87 off 78 balls and then taking two wickets in two overs?",
    options: ['Shafali Verma', 'Deepti Sharma', 'Smriti Mandhana', 'Jemimah Rodrigues'],
    correctIndex: 0,
    explanation: 'Her wickets were Sune Luus and Marizanne Kapp; Laura Wolvaardt made 101, the first century by a captain in a women\'s World Cup final.',
    sourceUrl: 'https://www.icc-cricket.com/tournaments/womens-cricket-worldcup-2025/news/live-india-south-africa-eye-maiden-title-at-cwc25-final',
    sourceLabel: 'ICC: Deepti, Shafali shine as India claim maiden World Cup title',
  },
  {
    id: 'cr544',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Deepti Sharma',
    difficulty: 'extreme',
    question: "What were Deepti Sharma's bowling figures in the 2025 Women's World Cup final, which included the wickets of Laura Wolvaardt and Chloe Tryon in one over?",
    options: ['4 for 39', '5 for 39', '5 for 31', '6 for 20'],
    correctIndex: 1,
    explanation: 'She was player of the tournament with 215 runs and 22 wickets, the first cricketer to pair 200 runs and 20 wickets in a single World Cup.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Deepti_Sharma',
    sourceLabel: 'Wikipedia: Deepti Sharma',
  },
  {
    id: 'cr545',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "2025 Women's World Cup",
    difficulty: 'expert',
    question: "Who made an unbeaten 127 as India chased 339 against Australia in the 2025 World Cup semi-final, the highest successful chase in women's ODIs?",
    options: ['Harmanpreet Kaur', 'Smriti Mandhana', 'Jemimah Rodrigues', 'Richa Ghosh'],
    correctIndex: 2,
    explanation: 'The Mumbai batter, a former state hockey player, added 167 with captain Harmanpreet Kaur and was player of the match.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Jemimah_Rodrigues',
    sourceLabel: 'Wikipedia: Jemimah Rodrigues',
  },
  {
    id: 'cr546',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Richa Ghosh',
    difficulty: 'extreme',
    question: "Which wicketkeeper-batter scored 94 from number eight against South Africa at the 2025 World Cup, a record for that position in women's ODIs?",
    options: ['Deepti Sharma', 'Amanjot Kaur', 'Sneh Rana', 'Richa Ghosh'],
    correctIndex: 3,
    explanation: 'The Siliguri player made her international debut at 16 at the 2020 T20 World Cup and in December 2024 equalled the fastest women\'s T20I fifty, off 18 balls.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Richa_Ghosh',
    sourceLabel: 'Wikipedia: Richa Ghosh',
  },
  {
    id: 'cr547',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Women's Asia Cup",
    difficulty: 'expert',
    question: "After beating Sri Lanka by 72 runs in the 2026 final in Dubai, how many Women's Asia Cup titles had India won in total?",
    options: ['6', '7', '8', '9'],
    correctIndex: 2,
    explanation: 'Four came in the ODI era (2004 to 2008) and four in T20s (2012, 2016, 2022, 2026); Shafali Verma and Smriti Mandhana put on 129 for the first wicket in the 2026 final.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2026_Women%27s_Twenty20_Asia_Cup',
    sourceLabel: "Wikipedia: 2026 Women's Twenty20 Asia Cup",
  },
  {
    id: 'cr548',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Women's Asia Cup",
    difficulty: 'extreme',
    question: "Which team ended India's run of six straight Women's Asia Cup titles by beating them by three wickets in the 2018 final in Kuala Lumpur?",
    options: ['Pakistan', 'Bangladesh', 'Sri Lanka', 'Thailand'],
    correctIndex: 1,
    explanation: 'India\'s other final defeat came in 2024, when Sri Lanka won their first title by eight wickets in Dambulla.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Women%27s_Asia_Cup',
    sourceLabel: "Wikipedia: Women's Asia Cup",
  },
  {
    id: 'cr549',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Smriti Mandhana',
    difficulty: 'expert',
    question: "Smriti Mandhana's 50-ball hundred in 2025, the fastest ODI century by an Indian, came against which opposition?",
    options: ['Sri Lanka', 'England', 'South Africa', 'Australia'],
    correctIndex: 3,
    explanation: 'She was the first Indian woman with centuries in all three formats and was named ICC Women\'s Cricketer of the Year for 2018, 2021 and 2024.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Smriti_Mandhana',
    sourceLabel: 'Wikipedia: Smriti Mandhana',
  },
]);
