// Server-only editorial bank: Indian cricket, origins to the 1971 breakthrough (50 questions).
// Never import this module from client components.
// Every fact below was checked against the page at sourceUrl when written.
export const CRICKET_INDIA_1 = Object.freeze([
  // ------------------------------------------------- Parsi cricket and the Bombay tournament
  {
    id: 'cr100',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Bombay Quadrangular',
    difficulty: 'simple',
    question:
      'Which Bombay community first challenged the Europeans of the Bombay Gymkhana in 1877, the fixture that grew into the Quadrangular and Pentangular tournaments?',
    options: ['The Parsis', 'The Hindus', 'The Muslims', 'The Rest'],
    correctIndex: 0,
    explanation:
      'The Hindus joined in 1907 to make it a Triangular, and the tournament was recognised as first-class from 1892-93 onwards.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bombay_Quadrangular',
    sourceLabel: 'Wikipedia: Bombay Quadrangular',
  },
  {
    id: 'cr101',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Bombay Quadrangular',
    difficulty: 'expert',
    question:
      'In which year were the Muslims of the Mohammedan Gymkhana admitted, turning the Bombay Triangular into the Quadrangular?',
    options: ['1907', '1892', '1912', '1937'],
    correctIndex: 2,
    explanation:
      'The Hindus had joined in 1907 after beating the Europeans by 110 runs in February 1906.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bombay_Quadrangular',
    sourceLabel: 'Wikipedia: Bombay Quadrangular',
  },
  {
    id: 'cr102',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Bombay Pentangular',
    difficulty: 'expert',
    question:
      'Which fifth side, made up of Buddhists, Jews and Indian Christians, was admitted in 1937 to make the Bombay tournament a Pentangular?',
    options: ['The Europeans', 'The Rest', 'The Anglo-Indians', 'The Rajputs'],
    correctIndex: 1,
    explanation:
      'From 1937 the matches moved from the Bombay Gymkhana ground to the new Brabourne Stadium.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bombay_Quadrangular',
    sourceLabel: 'Wikipedia: Bombay Quadrangular',
  },
  {
    id: 'cr103',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Bombay Pentangular',
    difficulty: 'simple',
    question:
      'Which national leader asked the sporting public of Bombay in 1940 to erase communal matches from its sporting code, hastening the end of the Pentangular?',
    options: ['Jawaharlal Nehru', 'Sardar Patel', 'Subhas Chandra Bose', 'Mahatma Gandhi'],
    correctIndex: 3,
    explanation:
      'The BCCI announced in 1946 that the Pentangular was being abandoned; the Hindus won the last edition in 1945-46.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bombay_Quadrangular',
    sourceLabel: 'Wikipedia: Bombay Quadrangular',
  },
  {
    id: 'cr104',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Bombay Pentangular',
    difficulty: 'extreme',
    question: 'Which team won the final Bombay Pentangular tournament, staged in 1945-46?',
    options: ['The Hindus', 'The Parsis', 'The Muslims', 'The Rest'],
    correctIndex: 0,
    explanation:
      'The Parsis had the longest record in the event, with 10 outright titles and 11 shared ones over its first-class era.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bombay_Quadrangular',
    sourceLabel: 'Wikipedia: Bombay Quadrangular',
  },
  // ------------------------------------------------- Ranjitsinhji and Duleepsinhji
  {
    id: 'cr105',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: 'Ranjitsinhji',
    difficulty: 'simple',
    question: 'For which English county did K. S. Ranjitsinhji play from 1895 to 1920?',
    options: ['Middlesex', 'Yorkshire', 'Sussex', 'Kent'],
    correctIndex: 2,
    explanation:
      'Ranji became Jam Sahib of Nawanagar in March 1907 and later lost an eye in a hunting accident.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ranjitsinhji',
    sourceLabel: 'Wikipedia: Ranjitsinhji',
  },
  {
    id: 'cr106',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: 'Ranjitsinhji',
    difficulty: 'simple',
    question:
      'What did Ranjitsinhji score on his Test debut for England against Australia in July 1896?',
    options: ['62', '93', '175', '154 not out'],
    correctIndex: 3,
    explanation:
      'He finished with 989 runs in 15 Tests at 44.95, with two centuries.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ranjitsinhji',
    sourceLabel: 'Wikipedia: Ranjitsinhji',
  },
  {
    id: 'cr107',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: 'Ranjitsinhji',
    difficulty: 'expert',
    question: 'Which stroke is Ranjitsinhji credited with popularising, and possibly inventing?',
    options: ['The leg glance', 'The reverse sweep', 'The late cut', 'The hook'],
    correctIndex: 0,
    explanation:
      'In 1899 he became the first batsman to pass 3,000 first-class runs in a season, finishing with 3,159.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ranjitsinhji',
    sourceLabel: 'Wikipedia: Ranjitsinhji',
  },
  {
    id: 'cr108',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: 'Duleepsinhji',
    difficulty: 'expert',
    question: "Duleepsinhji's celebrated 173 for England at Lord's in June 1930 came against which side?",
    options: ['South Africa', 'West Indies', 'Australia', 'New Zealand'],
    correctIndex: 2,
    explanation:
      'He played only 12 Tests, averaging 58.52, before pulmonary illness forced his retirement in 1932.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Duleepsinhji',
    sourceLabel: 'Wikipedia: Duleepsinhji',
  },
  {
    id: 'cr109',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Duleepsinhji',
    difficulty: 'simple',
    question:
      "Which Indian domestic first-class competition is named after Ranjitsinhji's nephew, a Sussex captain who played 12 Tests for England?",
    options: ['Duleep Trophy', 'Irani Cup', 'Deodhar Trophy', 'Vijay Hazare Trophy'],
    correctIndex: 0,
    explanation:
      'After cricket Duleepsinhji served as India\'s High Commissioner to Australia and New Zealand.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Duleepsinhji',
    sourceLabel: 'Wikipedia: Duleepsinhji',
  },
  // ------------------------------------------------- Lord's 1932 and the first Tests
  {
    id: 'cr110',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Lord's 1932",
    difficulty: 'simple',
    question: "Who captained India in the country's first Test match, at Lord's in June 1932?",
    options: ['Maharaja of Porbandar', 'C. K. Nayudu', 'Lala Amarnath', 'Vijay Merchant'],
    correctIndex: 1,
    explanation:
      'The Maharaja of Porbandar held the nominal tour captaincy but stood down for the Test; England won by 158 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_1932',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 1932',
  },
  {
    id: 'cr111',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Farokh Engineer',
    difficulty: 'expert',
    question:
      'Which Indian wicketkeeper hit 94 before lunch on the first day at Madras in January 1967 against an attack of Hall, Griffith, Sobers and Gibbs?',
    options: ['Budhi Kunderan', 'Naren Tamhane', 'Farokh Engineer', 'Syed Kirmani'],
    correctIndex: 2,
    explanation:
      'India were 125 for no wicket at the interval and he went on to 109, caught by Kanhai off Sobers.',
    sourceUrl:
      'https://www.cricketcountry.com/articles/farokh-engineer-tears-into-famed-west-indies-attack-almost-scores-hundred-before-lunch-22018/',
    sourceLabel: 'Cricket Country: Farokh Engineer tears into famed West Indies attack',
  },
  {
    id: 'cr112',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Lord's 1932",
    difficulty: 'expert',
    question:
      "Which fast bowler took India's first Test wickets, removing Holmes and Sutcliffe in the same over at Lord's in 1932, and finished the innings with 5 for 93?",
    options: ['Mohammad Nissar', 'Amar Singh', 'Jahangir Khan', 'C. S. Nayudu'],
    correctIndex: 0,
    explanation:
      'Nissar played only six Tests, taking 25 wickets at 28.28, and later helped found the Pakistan cricket board.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mohammad_Nissar',
    sourceLabel: 'Wikipedia: Mohammad Nissar',
  },
  {
    id: 'cr113',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Lord's 1932",
    difficulty: 'extreme',
    question: "Who scored India's first Test half-century, 51 at Lord's in 1932?",
    options: ['C. K. Nayudu', 'Wazir Ali', 'Naoomal Jaoomal', 'Amar Singh'],
    correctIndex: 3,
    explanation:
      'Amar Singh, a fast-medium all-rounder, died of pneumonia in 1940 aged 29 after taking 28 wickets in seven Tests.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Amar_Singh_(cricketer)',
    sourceLabel: 'Wikipedia: Amar Singh (cricketer)',
  },
  {
    id: 'cr114',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'C. K. Nayudu',
    difficulty: 'extreme',
    question:
      'How many sixes did C. K. Nayudu hit in his 153 for the Hindus against the MCC at the Bombay Gymkhana in 1926-27, an innings credited with pushing India towards Test status?',
    options: ['7', '11', '9', '13'],
    correctIndex: 1,
    explanation:
      'Nayudu was the first Indian named a Wisden Cricketer of the Year, in 1933, and played first-class cricket until he was 62.',
    sourceUrl: 'https://en.wikipedia.org/wiki/C._K._Nayudu',
    sourceLabel: 'Wikipedia: C. K. Nayudu',
  },
  // ------------------------------------------------- Lala Amarnath
  {
    id: 'cr115',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Lala Amarnath',
    difficulty: 'simple',
    question:
      "Who scored India's first Test century, 118 against England at the Bombay Gymkhana in December 1933?",
    options: ['Lala Amarnath', 'C. K. Nayudu', 'Vijay Merchant', 'Mushtaq Ali'],
    correctIndex: 0,
    explanation:
      'It was India\'s first home Test; temporary stands held a record crowd of about 50,000.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bombay_Gymkhana',
    sourceLabel: 'Wikipedia: Bombay Gymkhana',
  },
  {
    id: 'cr116',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Lala Amarnath',
    difficulty: 'expert',
    question:
      'Which tour captain sent Lala Amarnath home from the 1936 tour of England for alleged indiscipline?',
    options: ['Maharaja of Porbandar', 'Nawab of Pataudi', 'Maharaja of Patiala', 'Maharajkumar of Vizianagram'],
    correctIndex: 3,
    explanation:
      'A later inquiry completely exonerated Amarnath; England won that series 2-0.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_1936',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 1936',
  },
  {
    id: 'cr117',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Lala Amarnath',
    difficulty: 'extreme',
    question:
      'Lala Amarnath is the only bowler to have dismissed Don Bradman in Test cricket by which method?',
    options: ['Stumped', 'Hit wicket', 'Handled the ball', 'Run out'],
    correctIndex: 1,
    explanation:
      'Amarnath captained independent India\'s first tour, to Australia in 1947-48, and his sons Mohinder and Surinder also played Tests.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Lala_Amarnath',
    sourceLabel: 'Wikipedia: Lala Amarnath',
  },
  // ------------------------------------------------- Merchant and Hazare
  {
    id: 'cr118',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Vijay Hazare',
    difficulty: 'simple',
    question:
      'Which batsman became the first Indian to score a century in each innings of a Test, with 116 and 145 at Adelaide in 1947-48?',
    options: ['Vijay Merchant', 'Lala Amarnath', 'Vijay Hazare', 'Vinoo Mankad'],
    correctIndex: 2,
    explanation:
      'Australia won that series 4-0 and Bradman made 715 runs at 178.75 in his final home series.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Vijay_Hazare',
    sourceLabel: 'Wikipedia: Vijay Hazare',
  },
  {
    id: 'cr119',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Vijay Hazare',
    difficulty: 'extreme',
    question:
      'With whom did Vijay Hazare add 577 for Baroda against Holkar in the 1946-47 Ranji Trophy final, a first-class partnership record for any wicket that stood for decades?',
    options: ['Gul Mohammad', 'Hemu Adhikari', 'C. S. Nayudu', 'Mushtaq Ali'],
    correctIndex: 0,
    explanation:
      'Gul Mohammad made 319 in that innings and later played a Test for Pakistan as well as eight for India.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Gul_Mohammad',
    sourceLabel: 'Wikipedia: Gul Mohammad',
  },
  {
    id: 'cr120',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Vijay Merchant',
    difficulty: 'extreme',
    question:
      'Which Indian batsman retired with a first-class average of 71.64, second only to Don Bradman among players with substantial careers?',
    options: ['Vijay Hazare', 'C. K. Nayudu', 'Mushtaq Ali', 'Vijay Merchant'],
    correctIndex: 3,
    explanation:
      'Merchant scored 2,385 runs at 74.53 on the 1946 tour of England and made 154 in his final Test, at Delhi in 1951, aged 40.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Vijay_Merchant',
    sourceLabel: 'Wikipedia: Vijay Merchant',
  },
  {
    id: 'cr121',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Mushtaq Ali',
    difficulty: 'extreme',
    question:
      "Who scored India's first Test century abroad, 112 against England at Old Trafford in 1936?",
    options: ['Vijay Merchant', 'C. K. Nayudu', 'Mushtaq Ali', 'Wazir Ali'],
    correctIndex: 2,
    explanation:
      'Vijay Merchant made 114 in the same innings; India\'s domestic T20 competition is now named after Mushtaq Ali.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mushtaq_Ali',
    sourceLabel: 'Wikipedia: Mushtaq Ali',
  },
  // ------------------------------------------------- Madras 1952: the first win
  {
    id: 'cr122',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Madras 1952',
    difficulty: 'simple',
    question:
      "Which left-arm spinner took 12 wickets in the match as India recorded its first Test victory, against England at Madras in February 1952?",
    options: ['Ghulam Ahmed', 'Subhash Gupte', 'Bapu Nadkarni', 'Vinoo Mankad'],
    correctIndex: 3,
    explanation:
      'His figures were 8 for 55 and 4 for 53, and the win came in India\'s 25th Test, twenty years after the first.',
    sourceUrl: 'https://en.wikipedia.org/wiki/English_cricket_team_in_India_in_1951%E2%80%9352',
    sourceLabel: 'Wikipedia: English cricket team in India in 1951-52',
  },
  {
    id: 'cr123',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Madras 1952',
    difficulty: 'expert',
    question: "By what margin did India win its first ever Test, at Madras in 1952?",
    options: ['Six wickets', '128 runs', 'Ten wickets', 'An innings and 8 runs'],
    correctIndex: 3,
    explanation:
      'Polly Umrigar made an unbeaten 130 and the series finished 1-1, with the other three Tests drawn.',
    sourceUrl: 'https://en.wikipedia.org/wiki/English_cricket_team_in_India_in_1951%E2%80%9352',
    sourceLabel: 'Wikipedia: English cricket team in India in 1951-52',
  },
  {
    id: 'cr124',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Madras 1952',
    difficulty: 'expert',
    question: "Who captained India in its first Test victory, at Madras in February 1952?",
    options: ['Lala Amarnath', 'Vijay Hazare', 'Vijay Merchant', 'Polly Umrigar'],
    correctIndex: 1,
    explanation:
      'Hazare led India in 14 Tests between 1951 and 1953; England were captained at Madras by Donald Carr.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Vijay_Hazare',
    sourceLabel: 'Wikipedia: Vijay Hazare',
  },
  // ------------------------------------------------- 1952-53 v Pakistan
  {
    id: 'cr125',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'India v Pakistan 1952-53',
    difficulty: 'simple',
    question:
      "What was the result of the first India-Pakistan Test series, played in India in 1952-53 and India's first series win?",
    options: ['India won 2-1', 'India won 3-0', 'India won 1-0', 'India won 2-0'],
    correctIndex: 0,
    explanation:
      'Lala Amarnath and Abdul Hafeez Kardar were the captains, and two of the five Tests were drawn.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pakistani_cricket_team_in_India_in_1952%E2%80%9353',
    sourceLabel: 'Wikipedia: Pakistani cricket team in India in 1952-53',
  },
  {
    id: 'cr126',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'India v Pakistan 1952-53',
    difficulty: 'extreme',
    question:
      "At which Indian venue did Pakistan record their first ever Test win, by an innings and 43 runs in October 1952?",
    options: ['Bombay', 'Delhi', 'Calcutta', 'Lucknow'],
    correctIndex: 3,
    explanation:
      'Nazar Mohammad carried his bat for 124 and Fazal Mahmood did the bowling damage in Pakistan\'s second Test.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pakistani_cricket_team_in_India_in_1952%E2%80%9353',
    sourceLabel: 'Wikipedia: Pakistani cricket team in India in 1952-53',
  },
  {
    id: 'cr127',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'India v Pakistan 1952-53',
    difficulty: 'extreme',
    question:
      "How many wickets did Vinoo Mankad take in Pakistan's inaugural Test, at Delhi in October 1952, including 8 for 52 in the first innings?",
    options: ['10', '13', '11', '15'],
    correctIndex: 1,
    explanation:
      'India won by an innings and 70 runs; Ghulam Ahmed made 50 at number 11 in a 109-run last-wicket stand with Hemu Adhikari.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pakistani_cricket_team_in_India_in_1952%E2%80%9353',
    sourceLabel: 'Wikipedia: Pakistani cricket team in India in 1952-53',
  },
  // ------------------------------------------------- Mankad, Roy and the 413
  {
    id: 'cr128',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'The 413 stand',
    difficulty: 'simple',
    question:
      'Who was Vinoo Mankad\'s partner in the world-record opening stand of 413 against New Zealand at Madras in January 1956?',
    options: ['Polly Umrigar', 'Nari Contractor', 'Pankaj Roy', 'Vijay Manjrekar'],
    correctIndex: 2,
    explanation:
      'Roy made 173; India declared at 537 for 3 and won by an innings and 109 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pankaj_Roy',
    sourceLabel: 'Wikipedia: Pankaj Roy',
  },
  {
    id: 'cr129',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'The 413 stand',
    difficulty: 'expert',
    question:
      'What was Vinoo Mankad\'s score in the 413 opening stand at Madras in 1956, then the highest Test innings by an Indian?',
    options: ['231', '223', '203', '256'],
    correctIndex: 0,
    explanation:
      'Mankad had also made 223 earlier in the same series, at Bombay, and Subhash Gupte took 34 wickets in the four Tests he played.',
    sourceUrl: 'https://en.wikipedia.org/wiki/New_Zealand_cricket_team_in_India_in_1955%E2%80%9356',
    sourceLabel: 'Wikipedia: New Zealand cricket team in India in 1955-56',
  },
  {
    id: 'cr130',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'The 413 stand',
    difficulty: 'extreme',
    question:
      "Which pair finally broke Mankad and Roy's Test first-wicket record of 413 in 2008, 52 years after it was set?",
    options: [
      'Matthew Hayden and Justin Langer',
      'Marcus Trescothick and Andrew Strauss',
      'Virender Sehwag and Rahul Dravid',
      'Neil McKenzie and Graeme Smith',
    ],
    correctIndex: 3,
    explanation:
      'Mankad was inducted into the ICC Cricket Hall of Fame in June 2021, 43 years after his death.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Vinoo_Mankad',
    sourceLabel: 'Wikipedia: Vinoo Mankad',
  },
  // ------------------------------------------------- The spin quartet
  {
    id: 'cr131',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Spin quartet',
    difficulty: 'extreme',
    question: 'How many Test wickets did Bishan Singh Bedi take in his 67 Tests?',
    options: ['242', '266', '189', '156'],
    correctIndex: 1,
    explanation:
      'Bedi debuted against West Indies on 31 December 1966 and his 1,560 first-class wickets remain the most by an Indian.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bishan_Singh_Bedi',
    sourceLabel: 'Wikipedia: Bishan Singh Bedi',
  },
  {
    id: 'cr132',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Spin quartet',
    difficulty: 'extreme',
    question:
      "Which spinner took 24 wickets in the 1967-68 series in New Zealand, India's first overseas Test series win?",
    options: ['Bishan Singh Bedi', 'Bapu Nadkarni', 'Erapalli Prasanna', 'B. S. Chandrasekhar'],
    correctIndex: 2,
    explanation:
      'Prasanna had paused his career to finish an engineering degree, returning to the side in 1967.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_New_Zealand_in_1967%E2%80%9368',
    sourceLabel: 'Wikipedia: Indian cricket team in New Zealand in 1967-68',
  },
  // ------------------------------------------------- Gupte and Umrigar
  {
    id: 'cr133',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Subhash Gupte',
    difficulty: 'simple',
    question:
      'Against which team did leg-spinner Subhash Gupte take 9 for 102 at Kanpur in 1958-59, the first nine-wicket innings haul by an Indian?',
    options: ['West Indies', 'Australia', 'England', 'Pakistan'],
    correctIndex: 0,
    explanation:
      'Garry Sobers called Gupte the best leg-spinner he had faced; Gupte finished with 149 wickets in 36 Tests.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Subhash_Gupte',
    sourceLabel: 'Wikipedia: Subhash Gupte',
  },
  {
    id: 'cr134',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1971 West Indies tour',
    difficulty: 'extreme',
    question:
      "Which off-spinner was India's leading wicket-taker, with 22, in the 1970-71 series win in the West Indies?",
    options: ['Erapalli Prasanna', 'S. Venkataraghavan', 'Salim Durani', 'Bishan Singh Bedi'],
    correctIndex: 1,
    explanation:
      'Bedi took 15 and Prasanna 11 in the series; Venkataraghavan later stood in 73 Tests as an umpire.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_the_West_Indies_in_1970%E2%80%9371',
    sourceLabel: 'Wikipedia: Indian cricket team in the West Indies in 1970-71',
  },
  {
    id: 'cr135',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Polly Umrigar',
    difficulty: 'simple',
    question:
      'Who became the first Indian to score a Test double century, with 223 against New Zealand at Hyderabad in 1955-56?',
    options: ['Vinoo Mankad', 'Vijay Manjrekar', 'Polly Umrigar', 'Pankaj Roy'],
    correctIndex: 2,
    explanation:
      'When Umrigar retired in 1962 he held the Indian records for most Tests (59), runs (3,631) and centuries (12).',
    sourceUrl: 'https://en.wikipedia.org/wiki/Polly_Umrigar',
    sourceLabel: 'Wikipedia: Polly Umrigar',
  },
  // ------------------------------------------------- Contractor and Pataudi
  {
    id: 'cr136',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Nari Contractor',
    difficulty: 'simple',
    question:
      "Whose bouncer fractured India captain Nari Contractor's skull in a tour match against Barbados at Bridgetown in March 1962?",
    options: ['Wes Hall', 'Roy Gilchrist', 'Garry Sobers', 'Charlie Griffith'],
    correctIndex: 3,
    explanation:
      'Contractor had led India to its first series win over England in 1961-62 and never played Test cricket again.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Nari_Contractor',
    sourceLabel: 'Wikipedia: Nari Contractor',
  },
  {
    id: 'cr137',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Nari Contractor',
    difficulty: 'expert',
    question:
      'Which West Indies captain was among those who gave blood for the transfusions Nari Contractor needed after his 1962 head injury?',
    options: ['Clyde Walcott', 'Frank Worrell', 'Everton Weekes', 'Gerry Alexander'],
    correctIndex: 1,
    explanation:
      'Teammates Chandu Borde, Bapu Nadkarni and Polly Umrigar also donated, and Contractor needed two operations to remove a clot.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Nari_Contractor',
    sourceLabel: 'Wikipedia: Nari Contractor',
  },
  {
    id: 'cr138',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Mansur Ali Khan Pataudi',
    difficulty: 'expert',
    question:
      "In which English town did the July 1961 car accident occur that permanently damaged Mansur Ali Khan Pataudi's right eye?",
    options: ['Brighton', 'Oxford', 'Hove', 'Winchester'],
    correctIndex: 2,
    explanation:
      'A shard of windscreen glass left him with double vision, yet he made his Test debut at Delhi five months later.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mansoor_Ali_Khan_Pataudi',
    sourceLabel: 'Wikipedia: Mansoor Ali Khan Pataudi',
  },
  {
    id: 'cr139',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Mansur Ali Khan Pataudi',
    difficulty: 'simple',
    question:
      'How old was Mansur Ali Khan Pataudi when he took over the India captaincy in the West Indies in March 1962, a record for a Test captain that stood until 2004?',
    options: ['21', '23', '19', '25'],
    correctIndex: 0,
    explanation:
      'He captained India in 40 of his 46 Tests, winning nine, and his father had played Tests for both England and India.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mansoor_Ali_Khan_Pataudi',
    sourceLabel: 'Wikipedia: Mansoor Ali Khan Pataudi',
  },
  {
    id: 'cr140',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'New Zealand 1967-68',
    difficulty: 'extreme',
    question:
      "At which ground did India record its first Test win away from home, by five wickets in the opening match of the 1967-68 series in New Zealand?",
    options: ['Auckland', 'Christchurch', 'Wellington', 'Dunedin'],
    correctIndex: 3,
    explanation:
      'India took the series 3-1 under Pataudi; Graham Dowling\'s 239 at Christchurch was then a New Zealand record score.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_New_Zealand_in_1967%E2%80%9368',
    sourceLabel: 'Wikipedia: Indian cricket team in New Zealand in 1967-68',
  },
  // ------------------------------------------------- 1971: Wadekar, Gavaskar, Sardesai
  {
    id: 'cr141',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'The Oval 1971',
    difficulty: 'simple',
    question:
      "Whose 6 for 38 bowled England out for 101 at The Oval in August 1971, setting up India's first Test win in England?",
    options: ['Bishan Singh Bedi', 'B. S. Chandrasekhar', 'S. Venkataraghavan', 'Erapalli Prasanna'],
    correctIndex: 1,
    explanation:
      'Chandrasekhar bowled with a right arm withered by childhood polio and was a Wisden Cricketer of the Year in 1972.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bhagwath_Chandrasekhar',
    sourceLabel: 'Wikipedia: Bhagwath Chandrasekhar',
  },
  {
    id: 'cr142',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Ajit Wadekar',
    difficulty: 'expert',
    question:
      "Which chairman of selectors used his casting vote to make Ajit Wadekar captain ahead of Pataudi for the 1971 tour of the West Indies?",
    options: ['Vijay Merchant', 'Lala Amarnath', 'Vijay Hazare', 'C. K. Nayudu'],
    correctIndex: 0,
    explanation:
      'Wadekar won series in the West Indies and England in 1971 and at home to England in 1972-73 before the 0-3 defeat of 1974 ended his career.',
    sourceUrl: 'https://www.wisden.com/wisden-cricketers-almanack/ajit-wadekar-the-unassuming-commander-almanack',
    sourceLabel: 'Wisden: Ajit Wadekar, the unassuming commander',
  },
  {
    id: 'cr143',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1971 West Indies tour',
    difficulty: 'expert',
    question:
      "At which ground did India beat West Indies by seven wickets in March 1971, its first Test win over them and the only result in a 1-0 series win?",
    options: ['Sabina Park, Kingston', 'Kensington Oval, Bridgetown', "Queen's Park Oval, Port of Spain", 'Bourda, Georgetown'],
    correctIndex: 2,
    explanation:
      'Garry Sobers captained West Indies; India\'s spinners Venkataraghavan, Bedi and Prasanna took 48 wickets between them in the series.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_the_West_Indies_in_1970%E2%80%9371',
    sourceLabel: 'Wikipedia: Indian cricket team in the West Indies in 1970-71',
  },
  {
    id: 'cr144',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sunil Gavaskar',
    difficulty: 'simple',
    question:
      'How many runs did Sunil Gavaskar score in his debut Test series, in the West Indies in 1971, still the record for a debut series?',
    options: ['642', '820', '703', '774'],
    correctIndex: 3,
    explanation:
      'He averaged 154.80 with four centuries after missing the first Test with a finger infection.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sunil_Gavaskar',
    sourceLabel: 'Wikipedia: Sunil Gavaskar',
  },
  {
    id: 'cr145',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sunil Gavaskar',
    difficulty: 'expert',
    question:
      'What were Sunil Gavaskar\'s scores in the final Test of the 1971 West Indies series, making him only the second batsman to pair a century with a double century in one Test?',
    options: ['117 and 205', '124 and 220', '116 and 210', '105 and 236'],
    correctIndex: 1,
    explanation:
      'Doug Walters had done it first; Gavaskar went on to become the first batsman past 10,000 Test runs, in 1987.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sunil_Gavaskar',
    sourceLabel: 'Wikipedia: Sunil Gavaskar',
  },
  {
    id: 'cr146',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Dilip Sardesai',
    difficulty: 'expert',
    question:
      "Which batsman's 212 at Kingston in the first Test of 1971 was the first double century by an Indian outside India?",
    options: ['Dilip Sardesai', 'Ajit Wadekar', 'Salim Durani', 'Eknath Solkar'],
    correctIndex: 0,
    explanation:
      'Sardesai, the first Goa-born Test cricketer, scored 642 runs in that series and was called the Renaissance Man of Indian cricket.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Dilip_Sardesai',
    sourceLabel: 'Wikipedia: Dilip Sardesai',
  },
  {
    id: 'cr147',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'The Oval 1971',
    difficulty: 'extreme',
    question:
      "Which Hyderabad all-rounder hit the winning boundary in India's four-wicket victory at The Oval in 1971?",
    options: ['Eknath Solkar', 'Farokh Engineer', 'Syed Abid Ali', 'Ajit Wadekar'],
    correctIndex: 2,
    explanation:
      'Abid Ali had taken 6 for 55 on Test debut at Adelaide in 1967, and the Oval win ended England\'s run of 26 Tests without defeat.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Syed_Abid_Ali',
    sourceLabel: 'Wikipedia: Syed Abid Ali',
  },
  // ------------------------------------------------- The first Ranji Trophy
  {
    id: 'cr148',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Ranji Trophy 1934-35',
    difficulty: 'extreme',
    question:
      'Which Madras bowler delivered the first ball in Ranji Trophy history, to Mysore\'s N. Curtis at Chepauk on 4 November 1934?',
    options: ['A. G. Ram Singh', 'C. P. Johnstone', 'S. M. Hadi', 'M. J. Gopalan'],
    correctIndex: 3,
    explanation:
      'Madras won by an innings and 23 runs inside a single day, still the only first-class match in India to finish that quickly.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1934%E2%80%9335_Ranji_Trophy',
    sourceLabel: 'Wikipedia: 1934-35 Ranji Trophy',
  },
  {
    id: 'cr149',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Ranji Trophy 1934-35',
    difficulty: 'expert',
    question: 'Whom did Bombay beat by 208 runs at the Bombay Gymkhana in the first Ranji Trophy final, in March 1935?',
    options: ['Madras', 'Northern India', 'Hyderabad', 'Bengal'],
    correctIndex: 1,
    explanation:
      'The competition was first called The Cricket Championship of India and took Ranjitsinhji\'s name from the 1935-36 season.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1934%E2%80%9335_Ranji_Trophy',
    sourceLabel: 'Wikipedia: 1934-35 Ranji Trophy',
  },
]);
