// Server-only editorial bank: Indian cricket, 1972 to 1988 (50 questions, cr150-cr199).
// Never import this module from client components.
// Every fact below was checked against the page at sourceUrl when written.
export const CRICKET_INDIA_2 = Object.freeze([
  // ---------------------------------------------------------------- Port of Spain 1976
  {
    id: 'cr150',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Port of Spain 1976',
    difficulty: 'simple',
    question: 'At which ground did India chase down 403 to beat West Indies in April 1976, then a Test record?',
    options: ["Queen's Park Oval", 'Kensington Oval', 'Sabina Park', 'Bourda'],
    correctIndex: 0,
    explanation: 'India finished on 406 for 4, a mark that stood as the highest successful Test chase until West Indies made 418 at Antigua in 2003.',
    sourceUrl: 'https://scroll.in/field/958935/406-4-when-gavaskar-viswanath-came-together-to-tame-the-mighty-west-indies-and-script-history',
    sourceLabel: 'Scroll.in: 406/4, when Gavaskar and Viswanath came together to tame the mighty West Indies',
  },
  {
    id: 'cr151',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Port of Spain 1976',
    difficulty: 'expert',
    question: 'Who made 112 in the 406 for 4 chase at Port of Spain in 1976, sharing the centuries with Gavaskar?',
    options: ['Sunil Gavaskar', 'Gundappa Viswanath', 'Mohinder Amarnath', 'Brijesh Patel'],
    correctIndex: 1,
    explanation: 'Gavaskar made 102 in the same innings; it was the first time the two had scored hundreds in the same Test.',
    sourceUrl: 'https://scroll.in/field/958935/406-4-when-gavaskar-viswanath-came-together-to-tame-the-mighty-west-indies-and-script-history',
    sourceLabel: 'Scroll.in: 406/4, when Gavaskar and Viswanath came together to tame the mighty West Indies',
  },
  {
    id: 'cr152',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Port of Spain 1976',
    difficulty: 'extreme',
    question: "How many balls did Mohinder Amarnath face for his 85 in India's record chase at Port of Spain in 1976?",
    options: ['220', '330', '440', '550'],
    correctIndex: 2,
    explanation: 'Clive Lloyd had gone in with three spinners, Jumadeen, Padmore and Imtiaz Ali, and switched to four fast bowlers for the next Test at Kingston.',
    sourceUrl: 'https://scroll.in/field/958935/406-4-when-gavaskar-viswanath-came-together-to-tame-the-mighty-west-indies-and-script-history',
    sourceLabel: 'Scroll.in: 406/4, when Gavaskar and Viswanath came together to tame the mighty West Indies',
  },
  {
    id: 'cr153',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: 'Port of Spain 1976',
    difficulty: 'extreme',
    question: "Whose 404 for 3 at Headingley in 1948 was the fourth-innings record that India's 406 for 4 at Port of Spain surpassed?",
    options: ['England', 'West Indies', 'South Africa', 'Australia'],
    correctIndex: 3,
    explanation: 'The win levelled the 1976 series at 1-1 before West Indies took the decider at Kingston, where five Indian batsmen were listed absent hurt.',
    sourceUrl: 'https://scroll.in/field/958935/406-4-when-gavaskar-viswanath-came-together-to-tame-the-mighty-west-indies-and-script-history',
    sourceLabel: 'Scroll.in: 406/4, when Gavaskar and Viswanath came together to tame the mighty West Indies',
  },
  // ---------------------------------------------------------------- 1975 World Cup
  {
    id: 'cr154',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1975 World Cup',
    difficulty: 'simple',
    question: "Against which team did Sunil Gavaskar bat through all 60 overs for 36 not out at Lord's in the 1975 World Cup?",
    options: ['England', 'Australia', 'New Zealand', 'East Africa'],
    correctIndex: 0,
    explanation: 'India finished on 132 for 3 in reply to 334 for 4 and lost by 202 runs in the opening match of the first World Cup.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1975_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 1975 Cricket World Cup',
  },
  {
    id: 'cr155',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1975 World Cup',
    difficulty: 'extreme',
    question: 'How many balls did Gavaskar face for his 36 not out against England at the 1975 World Cup?',
    options: ['132', '174', '196', '210'],
    correctIndex: 1,
    explanation: 'Dennis Amiss made 137 for England that day, and Indian supporters ran onto the field in frustration at the reply.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1975_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 1975 Cricket World Cup',
  },
  // ---------------------------------------------------------------- Kapil Dev's debut and rise
  {
    id: 'cr156',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Kapil Dev',
    difficulty: 'simple',
    question: 'At which Pakistani venue did Kapil Dev make his Test debut in October 1978?',
    options: ['Lahore', 'Karachi', 'Peshawar', 'Faisalabad'],
    correctIndex: 3,
    explanation: 'The 1978 tour was the first India-Pakistan series since 1961; Pakistan won the Tests 2-0.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Kapil_Dev',
    sourceLabel: 'Wikipedia: Kapil Dev',
  },
  {
    id: 'cr157',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Kapil Dev',
    difficulty: 'expert',
    question: "Who was Kapil Dev's first Test wicket, taken with his outswinger on debut in 1978?",
    options: ['Sadiq Mohammad', 'Majid Khan', 'Zaheer Abbas', 'Mushtaq Mohammad'],
    correctIndex: 0,
    explanation: 'Kapil was born in Chandigarh on 6 January 1959 and was 19 on debut.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Kapil_Dev',
    sourceLabel: 'Wikipedia: Kapil Dev',
  },
  {
    id: 'cr158',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Kapil Dev',
    difficulty: 'expert',
    question: 'At which ground did Kapil Dev make his first Test century, 126 against West Indies in 1979?',
    options: ['Eden Gardens', 'Feroz Shah Kotla', 'Wankhede Stadium', 'Chepauk'],
    correctIndex: 1,
    explanation: 'The hundred came off 124 balls; by the 1979-80 Pakistan series he had the 1,000-run, 100-wicket double in 25 Tests.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Kapil_Dev',
    sourceLabel: 'Wikipedia: Kapil Dev',
  },
  {
    id: 'cr159',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'The Oval 1979',
    difficulty: 'expert',
    question: 'What target were India chasing when they closed on 429 for 8 at The Oval in 1979, with Gavaskar making 221?',
    options: ['402', '418', '425', '438'],
    correctIndex: 3,
    explanation: 'Chetan Chauhan made 80 and Dilip Vengsarkar 52 in the chase; England took the series 1-0 with three draws.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_1979',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 1979',
  },
  {
    id: 'cr160',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'The Oval 1979',
    difficulty: 'expert',
    question: "Who captained India on the 1979 tour of England that ended with the 429 for 8 chase at The Oval?",
    options: ['Srinivas Venkataraghavan', 'Bishan Bedi', 'Sunil Gavaskar', 'Gundappa Viswanath'],
    correctIndex: 0,
    explanation: 'Ian Botham took 4 for 65 in 28 overs to halt the chase on the final day, 30 August to 4 September 1979.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_1979',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 1979',
  },
  // ---------------------------------------------------------------- Gavaskar's records
  {
    id: 'cr161',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sunil Gavaskar',
    difficulty: 'expert',
    question: 'In which city did Sunil Gavaskar become the first batsman to reach 10,000 Test runs, on 7 March 1987?',
    options: ['Bangalore', 'Bombay', 'Ahmedabad', 'Madras'],
    correctIndex: 2,
    explanation: 'He made 63 in that fourth Test against Pakistan before Imran Khan trapped him lbw; the crowd ran on to celebrate the landmark.',
    sourceUrl: 'https://gulfnews.com/opinion/today-in-history/march-7-1987-gavaskar-reaches-milestone-1.1989338',
    sourceLabel: 'Gulf News: March 7, 1987, Gavaskar reaches milestone',
  },
  {
    id: 'cr162',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sunil Gavaskar',
    difficulty: 'extreme',
    question: "Off which Pakistan bowler did Gavaskar late-cut the run that took him to 10,000 Test runs in 1987?",
    options: ['Imran Khan', 'Wasim Akram', 'Tauseef Ahmed', 'Ijaz Faqih'],
    correctIndex: 3,
    explanation: 'Gavaskar had come in with India struggling at 46 for 2 and the milestone triggered a pitch invasion.',
    sourceUrl: 'https://gulfnews.com/opinion/today-in-history/march-7-1987-gavaskar-reaches-milestone-1.1989338',
    sourceLabel: 'Gulf News: March 7, 1987, Gavaskar reaches milestone',
  },
  {
    id: 'cr163',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sunil Gavaskar',
    difficulty: 'expert',
    question: "What did Gavaskar score at Madras in December 1983 for the 30th Test century that took him past Don Bradman's record?",
    options: ['236 not out', '221', '205', '182'],
    correctIndex: 0,
    explanation: 'His 29th, which equalled Bradman, had come earlier that series at Delhi: 121 off 94 balls in his 95th Test.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sunil_Gavaskar',
    sourceLabel: 'Wikipedia: Sunil Gavaskar',
  },
  {
    id: 'cr164',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sunil Gavaskar',
    difficulty: 'expert',
    question: 'What was Gavaskar dismissed for in his final Test innings, against Pakistan at Bangalore in March 1987?',
    options: ['63', '84', '96', '103'],
    correctIndex: 2,
    explanation: 'Pakistan won that Test by 16 runs to take the series 1-0 after four draws; Gavaskar retired with 34 Test centuries and 10,122 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sunil_Gavaskar',
    sourceLabel: 'Wikipedia: Sunil Gavaskar',
  },
  // ---------------------------------------------------------------- 1983 World Cup
  {
    id: 'cr165',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1983 World Cup',
    difficulty: 'simple',
    question: "What total did India post batting first in the 1983 World Cup final at Lord's?",
    options: ['175', '178', '180', '183'],
    correctIndex: 3,
    explanation: 'India were bowled out in 54.4 overs and it remains the lowest total ever defended in a World Cup final.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1983_Cricket_World_Cup_final',
    sourceLabel: 'Wikipedia: 1983 Cricket World Cup final',
  },
  {
    id: 'cr166',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1983 World Cup',
    difficulty: 'simple',
    question: 'By how many runs did India beat West Indies in the 1983 World Cup final?',
    options: ['43', '34', '51', '29'],
    correctIndex: 0,
    explanation: 'West Indies were bowled out for 140 in 52 overs on 25 June 1983, in front of 24,609 spectators.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1983_Cricket_World_Cup_final',
    sourceLabel: 'Wikipedia: 1983 Cricket World Cup final',
  },
  {
    id: 'cr167',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1983 World Cup',
    difficulty: 'extreme',
    question: 'How many balls did Kapil Dev face for his 175 not out against Zimbabwe at Tunbridge Wells in 1983?',
    options: ['118', '138', '148', '162'],
    correctIndex: 1,
    explanation: 'The innings had 16 fours and six sixes and came after India had slumped to 17 for 5.',
    sourceUrl: 'https://scroll.in/field/964951/pause-rewind-play-why-kapil-devs-175-has-achieved-mythical-proportions',
    sourceLabel: "Scroll.in: Kapil Dev's 175* through the eyes of those who watched it",
  },
  {
    id: 'cr168',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1983 World Cup',
    difficulty: 'extreme',
    question: 'How many runs did Kapil Dev and Syed Kirmani add in their unbroken ninth-wicket stand against Zimbabwe in 1983?',
    options: ['98', '112', '126', '141'],
    correctIndex: 2,
    explanation: "Kirmani's share was 24 not out; India reached 266 for 8 and won by 31 runs.",
    sourceUrl: 'https://scroll.in/field/964951/pause-rewind-play-why-kapil-devs-175-has-achieved-mythical-proportions',
    sourceLabel: "Scroll.in: Kapil Dev's 175* through the eyes of those who watched it",
  },
  {
    id: 'cr169',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1983 World Cup',
    difficulty: 'simple',
    question: "In which English town did Kapil Dev play his 175 not out against Zimbabwe at the 1983 World Cup?",
    options: ['Tunbridge Wells', 'Taunton', 'Leicester', 'Bristol'],
    correctIndex: 0,
    explanation: "The match at the Nevill Ground was not televised, so no footage of the innings exists; it beat Glenn Turner's 171 not out as the highest ODI score.",
    sourceUrl: 'https://scroll.in/field/964951/pause-rewind-play-why-kapil-devs-175-has-achieved-mythical-proportions',
    sourceLabel: "Scroll.in: Kapil Dev's 175* through the eyes of those who watched it",
  },
  {
    id: 'cr170',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1983 World Cup',
    difficulty: 'simple',
    question: 'Who was named man of the match in both the semi-final and the final of the 1983 World Cup?',
    options: ['Kapil Dev', 'Mohinder Amarnath', 'Yashpal Sharma', 'Madan Lal'],
    correctIndex: 1,
    explanation: 'He made 46 and took 2 for 27 against England at Old Trafford, then 26 and 3 for 12 against West Indies in the final.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mohinder_Amarnath',
    sourceLabel: 'Wikipedia: Mohinder Amarnath',
  },
  {
    id: 'cr171',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1983 World Cup',
    difficulty: 'extreme',
    question: "What were Mohinder Amarnath's bowling figures in the 1983 World Cup final?",
    options: ['3 for 31', '2 for 32', '3 for 12', '1 for 21'],
    correctIndex: 2,
    explanation: 'Madan Lal also took three wickets, for 31, and Balwinder Sandhu two for 32 as West Indies fell for 140.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1983_Cricket_World_Cup_final',
    sourceLabel: 'Wikipedia: 1983 Cricket World Cup final',
  },
  {
    id: 'cr172',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1983 World Cup',
    difficulty: 'simple',
    question: 'Who bowled Gordon Greenidge for 1 in the 1983 final with an inswinger the opener shouldered arms to?',
    options: ['Madan Lal', 'Kapil Dev', 'Roger Binny', 'Balwinder Sandhu'],
    correctIndex: 3,
    explanation: 'It was the third time in three months he had dismissed Greenidge; batting at No. 11 he had earlier been hit on the head by a bouncer.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Balwinder_Sandhu',
    sourceLabel: 'Wikipedia: Balwinder Sandhu',
  },
  {
    id: 'cr173',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1983 World Cup',
    difficulty: 'expert',
    question: 'Off whose bowling did Kapil Dev take the running catch that dismissed Viv Richards for 33 in the 1983 final?',
    options: ['Roger Binny', 'Madan Lal', 'Balwinder Sandhu', 'Mohinder Amarnath'],
    correctIndex: 1,
    explanation: 'The bowler had asked Kapil for one more over after Richards hit him for boundaries; West Indies were 57 for 3 after the catch.',
    sourceUrl: 'https://scroll.in/field/965624/pause-rewind-play-when-viv-richards-hit-the-ball-in-the-air-in-1983-and-kapil-dev-ran-back',
    sourceLabel: 'Scroll.in: When Viv Richards hit the ball in the air in 1983 and Kapil Dev ran back',
  },
  {
    id: 'cr174',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1983 World Cup',
    difficulty: 'expert',
    question: 'Who was the leading wicket-taker of the 1983 World Cup, with 18 wickets?',
    options: ['Madan Lal', 'Kapil Dev', 'Roger Binny', 'Balwinder Sandhu'],
    correctIndex: 2,
    explanation: 'Madan Lal was next with 17, level with Sri Lanka\'s Ashantha de Mel.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1983_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 1983 Cricket World Cup',
  },
  {
    id: 'cr175',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1983 World Cup',
    difficulty: 'extreme',
    question: "Who top-scored for India with 38 in the 1983 World Cup final?",
    options: ['Mohinder Amarnath', 'Sandeep Patil', 'Yashpal Sharma', 'Krishnamachari Srikkanth'],
    correctIndex: 3,
    explanation: 'Andy Roberts took 3 for 32 and Kapil Dev made 15 off eight balls as India were bowled out in 54.4 overs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1983_Cricket_World_Cup_final',
    sourceLabel: 'Wikipedia: 1983 Cricket World Cup final',
  },
  {
    id: 'cr176',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1983 World Cup',
    difficulty: 'expert',
    question: 'Where did India beat England in the semi-final of the 1983 World Cup?',
    options: ['Edgbaston', 'Old Trafford', 'The Oval', 'Headingley'],
    correctIndex: 1,
    explanation: 'England made 213 and India reached 217 for 4 in 54.4 overs, with Yashpal Sharma making 61 and Sandeep Patil 51 off 32 balls.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1983_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 1983 Cricket World Cup',
  },
  {
    id: 'cr177',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Syed Kirmani',
    difficulty: 'simple',
    question: 'Who kept wicket for India in the 1983 World Cup final and was named the best wicketkeeper of the tournament?',
    options: ['Kiran More', 'Chandrakant Pandit', 'Bharath Reddy', 'Syed Kirmani'],
    correctIndex: 3,
    explanation: 'He played 88 Tests with 160 catches and 38 stumpings, and had equalled the world record of six victims in an innings in his second Test.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Syed_Kirmani',
    sourceLabel: 'Wikipedia: Syed Kirmani',
  },
  // ---------------------------------------------------------------- 1985 World Championship of Cricket
  {
    id: 'cr178',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1985 World Championship of Cricket',
    difficulty: 'simple',
    question: 'Which car did Ravi Shastri win as Champion of Champions at the 1985 World Championship of Cricket in Australia?',
    options: ['BMW 3 Series', 'Audi 100', 'Mercedes 190', 'Toyota Corolla'],
    correctIndex: 1,
    explanation: 'The car was valued at A$35,000 and he drove it around the MCG with his team-mates sitting in and on it.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1985_World_Championship_of_Cricket_final',
    sourceLabel: 'Wikipedia: 1985 World Championship of Cricket final',
  },
  {
    id: 'cr179',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1985 World Championship of Cricket',
    difficulty: 'simple',
    question: 'Whom did India beat by eight wickets in the final of the 1985 World Championship of Cricket at the MCG?',
    options: ['Australia', 'England', 'Pakistan', 'West Indies'],
    correctIndex: 2,
    explanation: 'The opponents made 176 for 9 and India got there with 17 balls to spare on 10 March 1985; the crowd of 35,296 was then the largest in Australia for a match without the home side.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1985_World_Championship_of_Cricket_final',
    sourceLabel: 'Wikipedia: 1985 World Championship of Cricket final',
  },
  {
    id: 'cr180',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1985 World Championship of Cricket',
    difficulty: 'extreme',
    question: 'Which Indian bowler was the leading wicket-taker of the 1985 World Championship of Cricket, with 10 wickets?',
    options: ['Kapil Dev', 'Chetan Sharma', 'Madan Lal', 'Laxman Sivaramakrishnan'],
    correctIndex: 3,
    explanation: 'The leg-spinner also took the most catches in the tournament; Srikkanth topped the run charts with 238.',
    sourceUrl: 'https://en.wikipedia.org/wiki/World_Championship_of_Cricket',
    sourceLabel: 'Wikipedia: World Championship of Cricket',
  },
  {
    id: 'cr181',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1985 World Championship of Cricket',
    difficulty: 'expert',
    question: 'Who captained India to the 1985 World Championship of Cricket title, unbeaten through the tournament?',
    options: ['Kapil Dev', 'Sunil Gavaskar', 'Dilip Vengsarkar', 'Ravi Shastri'],
    correctIndex: 1,
    explanation: 'The event marked the 150th anniversary of Victoria and staged the first matches under lights at the MCG.',
    sourceUrl: 'https://en.wikipedia.org/wiki/World_Championship_of_Cricket',
    sourceLabel: 'Wikipedia: World Championship of Cricket',
  },
  // ---------------------------------------------------------------- Sharjah 1986
  {
    id: 'cr182',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sharjah 1986',
    difficulty: 'simple',
    question: 'How many runs did Pakistan need off the final ball when Javed Miandad hit his famous six against India at Sharjah in April 1986?',
    options: ['2', '3', '4', '6'],
    correctIndex: 2,
    explanation: 'Pakistan had been 110 for 4 in pursuit of 246 in the Austral-Asia Cup final on 18 April 1986.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Javed_Miandad',
    sourceLabel: 'Wikipedia: Javed Miandad',
  },
  {
    id: 'cr183',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sharjah 1986',
    difficulty: 'simple',
    question: 'Which Indian bowler delivered the last ball that Javed Miandad hit for six in the 1986 Austral-Asia Cup final?',
    options: ['Kapil Dev', 'Madan Lal', 'Roger Binny', 'Chetan Sharma'],
    correctIndex: 3,
    explanation: 'The same bowler took 10 wickets in a Test at Edgbaston that summer, including 6 for 58 in the second innings.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Chetan_Sharma',
    sourceLabel: 'Wikipedia: Chetan Sharma',
  },
  {
    id: 'cr184',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sharjah 1986',
    difficulty: 'expert',
    question: 'What was Javed Miandad\'s unbeaten score in the 1986 Austral-Asia Cup final against India at Sharjah?',
    options: ['116', '102', '110', '124'],
    correctIndex: 0,
    explanation: 'India had made 245 for 7, with Gavaskar top-scoring with 92 off 134 balls, and Pakistan won by one wicket with 248 for 9.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1986_Austral-Asia_Cup',
    sourceLabel: 'Wikipedia: 1986 Austral-Asia Cup',
  },
  // ---------------------------------------------------------------- England 1986
  {
    id: 'cr185',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Lord's 1986",
    difficulty: 'simple',
    question: "Who made 126 not out for India in the 1986 Lord's Test, his third Test century at the ground?",
    options: ['Sunil Gavaskar', 'Mohinder Amarnath', 'Dilip Vengsarkar', 'Mohammad Azharuddin'],
    correctIndex: 2,
    explanation: "His earlier Lord's hundreds came in 1979 and 1982, making him the first non-English batsman with three Test centuries there.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Dilip_Vengsarkar',
    sourceLabel: 'Wikipedia: Dilip Vengsarkar',
  },
  {
    id: 'cr186',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Lord's 1986",
    difficulty: 'expert',
    question: "Which Indian captain took 4 for 52 and then hit the winning runs in the five-wicket win at Lord's in 1986?",
    options: ['Ravi Shastri', 'Mohammad Azharuddin', 'Sunil Gavaskar', 'Kapil Dev'],
    correctIndex: 3,
    explanation: 'It was his first win in 21 Tests as captain; Chetan Sharma took 5 for 64 in the match.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_1986',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 1986',
  },
  {
    id: 'cr187',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: "Lord's 1986",
    difficulty: 'expert',
    question: "Which England captain was removed after the Lord's defeat to India in 1986?",
    options: ['David Gower', 'Mike Gatting', 'Ian Botham', 'Graham Gooch'],
    correctIndex: 0,
    explanation: 'India went on to win by 279 runs at Headingley and took the series 2-0, with Vengsarkar scoring 360 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_1986',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 1986',
  },
  // ---------------------------------------------------------------- Madras tied Test 1986
  {
    id: 'cr188',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Madras tied Test 1986',
    difficulty: 'simple',
    question: 'Which Australian bowled the final ball of the tied Test at Madras in September 1986?',
    options: ['Greg Matthews', 'Ray Bright', 'Bruce Reid', 'Steve Waugh'],
    correctIndex: 0,
    explanation: 'He finished with 10 wickets in the match, 5 for 103 and 5 for 146, his only ten-wicket haul in Tests.',
    sourceUrl: 'https://scroll.in/field/817151/flashback-30-years-ago-maninder-singh-was-given-out-lbw-it-was-india-s-first-and-only-tied-test',
    sourceLabel: "Scroll.in: 30 years ago, Maninder Singh was given out lbw in India's first and only tied Test",
  },
  {
    id: 'cr189',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Madras tied Test 1986',
    difficulty: 'expert',
    question: 'Which Indian batsman was given out lbw by umpire V Vikramraju to end the 1986 Madras Test as a tie?',
    options: ['Maninder Singh', 'Ravi Shastri', 'Chetan Sharma', 'Kiran More'],
    correctIndex: 0,
    explanation: 'India needed four off the last over and were 347 all out chasing 348; Shastri was left on 48 not out.',
    sourceUrl: 'https://scroll.in/field/817151/flashback-30-years-ago-maninder-singh-was-given-out-lbw-it-was-india-s-first-and-only-tied-test',
    sourceLabel: "Scroll.in: 30 years ago, Maninder Singh was given out lbw in India's first and only tied Test",
  },
  {
    id: 'cr190',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: 'Madras tied Test 1986',
    difficulty: 'extreme',
    question: 'Which Australian batsman made 210 in the 1986 Madras tied Test while vomiting on the pitch from dehydration?',
    options: ['David Boon', 'Dean Jones', 'Allan Border', 'Greg Ritchie'],
    correctIndex: 1,
    explanation: 'Border told him he would get a Queenslander in if he could not cope; he was put on an intravenous drip afterwards and it remains the highest Test score by an Australian in India.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Dean_Jones_(cricketer)',
    sourceLabel: 'Wikipedia: Dean Jones (cricketer)',
  },
  {
    id: 'cr191',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Madras tied Test 1986',
    difficulty: 'extreme',
    question: "Who made 119 off 138 balls in India's first innings of the 1986 Madras tied Test and was named player of the match?",
    options: ['Sunil Gavaskar', 'Ravi Shastri', 'Kapil Dev', 'Mohammad Azharuddin'],
    correctIndex: 2,
    explanation: 'Australia had declared on 574 for 7; India replied with 397 before Border declared again at 170 for 5.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Australian_cricket_team_in_India_in_1986%E2%80%9387',
    sourceLabel: 'Wikipedia: Australian cricket team in India in 1986-87',
  },
  // ---------------------------------------------------------------- 1987 World Cup
  {
    id: 'cr192',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1987 World Cup',
    difficulty: 'simple',
    question: 'Against which team did Chetan Sharma take the first hat-trick in World Cup history, at Nagpur in 1987?',
    options: ['Australia', 'New Zealand', 'Zimbabwe', 'England'],
    correctIndex: 1,
    explanation: 'All three victims were bowled; the same match was Sunil Gavaskar\'s last ODI and brought his only ODI century.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1987_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 1987 Cricket World Cup',
  },
  {
    id: 'cr193',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1987 World Cup',
    difficulty: 'extreme',
    question: "Who was the third victim of Chetan Sharma's 1987 World Cup hat-trick, after Ken Rutherford and Ian Smith?",
    options: ['Ewen Chatfield', 'Martin Snedden', 'Willie Watson', 'Danny Morrison'],
    correctIndex: 0,
    explanation: 'India won five of six group matches but finished behind Australia on run rate; Navjot Sidhu made four fifties in his debut tournament.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1987_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 1987 Cricket World Cup',
  },
  {
    id: 'cr194',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1987 World Cup',
    difficulty: 'simple',
    question: 'Who scored 115 for England as they knocked India out of the 1987 World Cup in the semi-final at Bombay?',
    options: ['Mike Gatting', 'Allan Lamb', 'Graham Gooch', 'Chris Broad'],
    correctIndex: 2,
    explanation: 'England made 254 for 6 at the Wankhede Stadium and India were bowled out for 219, losing by 35 runs on 5 November 1987.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1987_Cricket_World_Cup_knockout_stage',
    sourceLabel: 'Wikipedia: 1987 Cricket World Cup knockout stage',
  },
  {
    id: 'cr195',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1987 World Cup',
    difficulty: 'extreme',
    question: 'Which England spinner took 4 for 52 as India collapsed to 219 all out in the 1987 World Cup semi-final?',
    options: ['John Emburey', 'Eddie Hemmings', 'Phil Edmonds', 'Nick Cook'],
    correctIndex: 1,
    explanation: 'Mohammad Azharuddin top-scored with 64 for India; Australia then beat England by seven runs in the final at Eden Gardens.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1987_Cricket_World_Cup_knockout_stage',
    sourceLabel: 'Wikipedia: 1987 Cricket World Cup knockout stage',
  },
  // ---------------------------------------------------------------- Bishan Bedi's captaincy
  {
    id: 'cr196',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Bishan Bedi',
    difficulty: 'extreme',
    question: 'Whose repeated bouncers led Bishan Bedi to concede the Sahiwal ODI against Pakistan in 1978 by calling his batsmen in?',
    options: ['Imran Khan', 'Sikander Bakht', 'Sarfraz Nawaz', 'Mudassar Nazar'],
    correctIndex: 2,
    explanation: 'Bedi became the first captain to concede an international match; Pakistan won the 1978 ODI series 2-1 and the Tests 2-0.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bishan_Singh_Bedi',
    sourceLabel: 'Wikipedia: Bishan Singh Bedi',
  },
  {
    id: 'cr197',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Bishan Bedi',
    difficulty: 'extreme',
    question: 'Which England bowler did Bedi accuse of using Vaseline to shine the ball during the 1976-77 Madras Test?',
    options: ['John Lever', 'Bob Willis', 'Derek Underwood', 'Chris Old'],
    correctIndex: 0,
    explanation: 'The bowler was cleared; he had taken 7 for 46 on debut at Delhi earlier in the series, which England won 3-1 under Tony Greig.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bishan_Singh_Bedi',
    sourceLabel: 'Wikipedia: Bishan Singh Bedi',
  },
  // ---------------------------------------------------------------- Hirwani 1988
  {
    id: 'cr198',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Narendra Hirwani',
    difficulty: 'expert',
    question: 'How many wickets did Narendra Hirwani take on his Test debut against West Indies at Madras in January 1988?',
    options: ['14', '16', '18', '19'],
    correctIndex: 1,
    explanation: 'His 8 for 61 and 8 for 75 beat Bob Massie\'s 16 for 137 from 1972 as the best match figures on Test debut, and he had 36 wickets after four Tests.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Narendra_Hirwani',
    sourceLabel: 'Wikipedia: Narendra Hirwani',
  },
  {
    id: 'cr199',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Narendra Hirwani',
    difficulty: 'extreme',
    question: "Which Indian wicketkeeper made a Test-record six stumpings in the 1988 Madras Test that Hirwani dominated?",
    options: ['Syed Kirmani', 'Chandrakant Pandit', 'Sadanand Viswanath', 'Kiran More'],
    correctIndex: 3,
    explanation: 'Five of the stumpings came in the second innings, also a Test record; he later chaired the selectors from 2002 to 2006.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Kiran_More',
    sourceLabel: 'Wikipedia: Kiran More',
  },
]);
