// Server-only editorial bank: Indian cricket, tranche 3 — 1989 to 1999 (50 questions, cr200–cr249).
// Never import this module from client components.
// Every fact below was checked against the page at sourceUrl when written.
export const CRICKET_INDIA_3 = Object.freeze([
  // ---------------------------------------------------------------- Tendulkar's debut, 1989
  {
    id: 'cr200',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Tendulkar debut 1989',
    difficulty: 'simple',
    question: 'At which ground did Sachin Tendulkar make his Test debut in November 1989, aged 16?',
    options: ['Karachi', 'Lahore', 'Sialkot', 'Faisalabad'],
    correctIndex: 0,
    explanation:
      'He was bowled for 15 by Waqar Younis, who was also making his debut, and all four Tests of the series were drawn.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Pakistan_in_1989%E2%80%9390',
    sourceLabel: 'Wikipedia: Indian cricket team in Pakistan in 1989–90',
  },
  {
    id: 'cr201',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Tendulkar debut 1989',
    difficulty: 'simple',
    question: 'Which Pakistan bowler, himself on debut, dismissed Tendulkar for 15 in his first Test innings?',
    options: ['Wasim Akram', 'Imran Khan', 'Abdul Qadir', 'Waqar Younis'],
    correctIndex: 3,
    explanation:
      'Tendulkar was 16 years and 205 days old; on the same tour a Waqar bouncer bloodied his nose at Sialkot and he batted on.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sachin_Tendulkar',
    sourceLabel: 'Wikipedia: Sachin Tendulkar',
  },
  {
    id: 'cr202',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Tendulkar debut 1989',
    difficulty: 'expert',
    question: 'Who captained India on the 1989-90 tour of Pakistan on which Tendulkar made his debut?',
    options: ['Kapil Dev', 'Dilip Vengsarkar', 'Kris Srikkanth', 'Ravi Shastri'],
    correctIndex: 2,
    explanation:
      "Imran Khan led Pakistan; Sanjay Manjrekar's 218 at Lahore was the highest score of a series drawn 0-0.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Pakistan_in_1989%E2%80%9390',
    sourceLabel: 'Wikipedia: Indian cricket team in Pakistan in 1989–90',
  },
  {
    id: 'cr203',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Tendulkar debut 1989',
    difficulty: 'extreme',
    question:
      'In which Test of the 1989-90 series was Tendulkar hit on the nose by a Waqar Younis bouncer and refused to leave the field?',
    options: ['Karachi', 'Sialkot', 'Lahore', 'Faisalabad'],
    correctIndex: 1,
    explanation: 'It was the fourth and final Test; he declined medical help and kept batting as his nose bled.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sachin_Tendulkar',
    sourceLabel: 'Wikipedia: Sachin Tendulkar',
  },
  // ---------------------------------------------------------------- England 1990
  {
    id: 'cr204',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England tour 1990',
    difficulty: 'simple',
    question: "Tendulkar's first Test century, 119 not out in August 1990, came at which English ground?",
    options: ['Old Trafford', "Lord's", 'The Oval', 'Headingley'],
    correctIndex: 0,
    explanation:
      'Aged 17, he became the second-youngest Test centurion at the time and his innings saved the second Test.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_1990',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 1990',
  },
  {
    id: 'cr205',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England tour 1990',
    difficulty: 'expert',
    question:
      "Which future India great made his Test debut in the same 1990 Old Trafford Test in which Tendulkar scored his maiden century?",
    options: ['Javagal Srinath', 'Venkatapathy Raju', 'Ajay Jadeja', 'Anil Kumble'],
    correctIndex: 3,
    explanation: 'Kumble had made his ODI debut against Sri Lanka at Sharjah four months earlier, in April 1990.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Anil_Kumble',
    sourceLabel: 'Wikipedia: Anil Kumble',
  },
  {
    id: 'cr206',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England tour 1990',
    difficulty: 'extreme',
    question:
      "At Lord's in 1990 Kapil Dev hit four consecutive sixes to avoid the follow-on. Which England spinner was the bowler?",
    options: ['John Emburey', 'Phil Tufnell', 'Eddie Hemmings', 'Ian Salisbury'],
    correctIndex: 2,
    explanation: "England still won by 247 runs after Graham Gooch's 333 and 123 in the same match.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Kapil_Dev',
    sourceLabel: 'Wikipedia: Kapil Dev',
  },
  {
    id: 'cr207',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'England tour 1990',
    difficulty: 'expert',
    question:
      "Graham Gooch made 333 and 123 at Lord's in 1990; India's captain replied with a 111-ball 121. Who was he?",
    options: ['Ravi Shastri', 'Mohammad Azharuddin', 'Dilip Vengsarkar', 'Sanjay Manjrekar'],
    correctIndex: 1,
    explanation:
      "Gooch's 456 remains the most runs by one batsman in a single Test; Azharuddin added 179 in the next Test at Old Trafford.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_1990',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 1990',
  },
  // ---------------------------------------------------------------- Azharuddin
  {
    id: 'cr208',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Mohammad Azharuddin',
    difficulty: 'simple',
    question:
      'Mohammad Azharuddin scored a century in each of his first three Tests, all in 1984-85 against which opponent?',
    options: ['England', 'Australia', 'Pakistan', 'West Indies'],
    correctIndex: 0,
    explanation: 'The scores were 110 at Kolkata, 105 at Chennai and 122 at Kanpur, a feat still unmatched in Test cricket.',
    sourceUrl:
      'https://www.cricketcountry.com/articles/mohammad-azharuddin-12-facts-you-should-know-about-the-former-india-captain-499856/',
    sourceLabel: 'Cricket Country: Mohammad Azharuddin, 12 facts you should know',
  },
  {
    id: 'cr209',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Mohammad Azharuddin',
    difficulty: 'extreme',
    question: "Azharuddin's third century in his first three Tests, 122, came at which venue?",
    options: ['Kolkata', 'Chennai', 'Delhi', 'Kanpur'],
    correctIndex: 3,
    explanation: 'He finished with 22 Test centuries in 99 Tests, the last against South Africa at Bangalore in March 2000.',
    sourceUrl:
      'https://www.cricketcountry.com/articles/mohammad-azharuddin-12-facts-you-should-know-about-the-former-india-captain-499856/',
    sourceLabel: 'Cricket Country: Mohammad Azharuddin, 12 facts you should know',
  },
  {
    id: 'cr210',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Mohammad Azharuddin',
    difficulty: 'extreme',
    question: 'In how many Tests did Azharuddin captain India?',
    options: ['35', '41', '47', '53'],
    correctIndex: 2,
    explanation: 'He won 14 and lost 14, and is the only Indian captain to have led at three World Cups: 1992, 1996 and 1999.',
    sourceUrl: 'https://en.wikipedia.org/wiki/List_of_India_national_cricket_captains',
    sourceLabel: 'Wikipedia: List of India national cricket captains',
  },
  // ---------------------------------------------------------------- 1992 World Cup
  {
    id: 'cr211',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: '1992 World Cup',
    difficulty: 'simple',
    question: 'The 1992 World Cup in Australia and New Zealand introduced coloured clothing and white balls. Who won it?',
    options: ['England', 'Pakistan', 'Australia', 'West Indies'],
    correctIndex: 1,
    explanation: 'Pakistan beat England by 22 runs in the final at the MCG; India finished seventh with two wins from eight matches.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1992_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 1992 Cricket World Cup',
  },
  {
    id: 'cr212',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1992 World Cup',
    difficulty: 'extreme',
    question:
      "Australia beat India by one run at Brisbane in the 1992 World Cup after rain revised India's target. Which Australian made 90?",
    options: ['Dean Jones', 'Allan Border', 'David Boon', 'Steve Waugh'],
    correctIndex: 0,
    explanation: "Azharuddin made 93 in reply, but India's target had become 236 off 47 overs and they fell one short.",
    sourceUrl: 'https://en.wikipedia.org/wiki/1992_Cricket_World_Cup_round-robin_stage',
    sourceLabel: 'Wikipedia: 1992 Cricket World Cup round-robin stage',
  },
  // ---------------------------------------------------------------- Titan Cup 1996
  {
    id: 'cr213',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Titan Cup 1996',
    difficulty: 'expert',
    question: 'Which team did India beat by 35 runs in the 1996 Titan Cup final at the Wankhede Stadium?',
    options: ['Australia', 'Sri Lanka', 'Pakistan', 'South Africa'],
    correctIndex: 3,
    explanation:
      "South Africa had won all six league matches; Anil Kumble's 4 for 25 was the match-winning spell under Tendulkar's captaincy.",
    sourceUrl: 'https://en.wikipedia.org/wiki/1996_Titan_Cup',
    sourceLabel: 'Wikipedia: 1996 Titan Cup',
  },
  // ---------------------------------------------------------------- Kumble
  {
    id: 'cr214',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Kumble 10 for 74',
    difficulty: 'simple',
    question: 'At which ground did Anil Kumble take all ten Pakistan wickets in an innings in February 1999?',
    options: ['Eden Gardens', 'Chepauk', 'Feroz Shah Kotla', 'Wankhede Stadium'],
    correctIndex: 2,
    explanation: 'His 10 for 74 set up a 212-run win that squared the two-Test series 1-1.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Anil_Kumble',
    sourceLabel: 'Wikipedia: Anil Kumble',
  },
  {
    id: 'cr215',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Kumble 10 for 74',
    difficulty: 'expert',
    question: 'Who took the close-in catch that gave Kumble his tenth wicket, Wasim Akram, at Delhi in 1999?',
    options: ['Sadagoppan Ramesh', 'VVS Laxman', 'Rahul Dravid', 'Nayan Mongia'],
    correctIndex: 1,
    explanation: 'Javagal Srinath bowled deliberately wide at the other end so that Kumble alone could complete the ten.',
    sourceUrl: 'https://www.icc-cricket.com/news/laker-kumble-patel-how-the-trio-claimed-all-ten',
    sourceLabel: 'ICC: Laker, Kumble, Patel — how the trio claimed all ten',
  },
  // ---------------------------------------------------------------- Robin Singh
  {
    id: 'cr216',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Robin Singh',
    difficulty: 'extreme',
    question: 'In which country was the India all-rounder Robin Singh born?',
    options: ['Trinidad and Tobago', 'Guyana', 'Kenya', 'Fiji'],
    correctIndex: 0,
    explanation: 'Born in Princes Town in 1963, he played 136 ODIs but only one Test, against Zimbabwe in 1998.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Robin_Singh_(cricketer)',
    sourceLabel: 'Wikipedia: Robin Singh (cricketer)',
  },
  {
    id: 'cr217',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: 'Kumble 10 for 74',
    difficulty: 'simple',
    question: 'Before Kumble in 1999, who was the only bowler to have taken all ten wickets in a Test innings?',
    options: ['Richard Hadlee', 'Sydney Barnes', 'Dennis Lillee', 'Jim Laker'],
    correctIndex: 3,
    explanation: "Laker's 10 for 53 came against Australia at Old Trafford in 1956; Ajaz Patel joined the club in Mumbai in 2021.",
    sourceUrl: 'https://www.icc-cricket.com/news/laker-kumble-patel-how-the-trio-claimed-all-ten',
    sourceLabel: 'ICC: Laker, Kumble, Patel — how the trio claimed all ten',
  },
  {
    id: 'cr218',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Hero Cup 1993',
    difficulty: 'expert',
    question: "Kumble's 6 for 12, then the best ODI figures by an Indian, came in the 1993 Hero Cup final against which team?",
    options: ['South Africa', 'Sri Lanka', 'West Indies', 'Zimbabwe'],
    correctIndex: 2,
    explanation:
      "India won by 102 runs at Eden Gardens in a tournament staged for the Cricket Association of Bengal's diamond jubilee.",
    sourceUrl: 'https://en.wikipedia.org/wiki/1993_Hero_Cup',
    sourceLabel: 'Wikipedia: 1993 Hero Cup',
  },
  {
    id: 'cr219',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1996 World Cup',
    difficulty: 'extreme',
    question: 'Who was the leading wicket-taker at the 1996 World Cup, with 15 wickets?',
    options: ['Waqar Younis', 'Anil Kumble', 'Shane Warne', 'Paul Strang'],
    correctIndex: 1,
    explanation: "Kumble's 15 came at 18.73 apiece in seven matches; Tendulkar topped the run charts with 523.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Anil_Kumble',
    sourceLabel: 'Wikipedia: Anil Kumble',
  },
  // ---------------------------------------------------------------- 1996 World Cup quarter-final, Bangalore
  {
    id: 'cr220',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1996 World Cup',
    difficulty: 'simple',
    question:
      'In the 1996 World Cup quarter-final at Bangalore, Venkatesh Prasad was hit for four, sledged, and bowled the batsman next ball. Who was the batsman?',
    options: ['Aamer Sohail', 'Saeed Anwar', 'Ijaz Ahmed', 'Inzamam-ul-Haq'],
    correctIndex: 0,
    explanation: 'Pakistan, chasing 288, finished on 248 for 9 and India won by 39 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Venkatesh_Prasad',
    sourceLabel: 'Wikipedia: Venkatesh Prasad',
  },
  {
    id: 'cr221',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Ajay Jadeja',
    difficulty: 'expert',
    question:
      "Ajay Jadeja's 45 off 25 balls in the 1996 quarter-final included 40 runs off the final two overs of which Pakistan bowler?",
    options: ['Wasim Akram', 'Aaqib Javed', 'Mushtaq Ahmed', 'Waqar Younis'],
    correctIndex: 3,
    explanation: 'India finished on 287 for 8; Jadeja went on to captain India in 13 ODIs as a regular vice-captain.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ajay_Jadeja',
    sourceLabel: 'Wikipedia: Ajay Jadeja',
  },
  {
    id: 'cr222',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1996 World Cup',
    difficulty: 'extreme',
    question: "What was India's total in the 1996 World Cup quarter-final against Pakistan at Bangalore?",
    options: ['262 for 6', '275 for 9', '287 for 8', '301 for 5'],
    correctIndex: 2,
    explanation: 'Navjot Sidhu made 93 at the top of the order and Pakistan replied with 248 for 9.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1996_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 1996 Cricket World Cup',
  },
  // ---------------------------------------------------------------- 1996 World Cup semi-final, Eden Gardens
  {
    id: 'cr223',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1996 World Cup semi-final',
    difficulty: 'simple',
    question: 'At which ground was the 1996 World Cup semi-final between India and Sri Lanka abandoned after crowd trouble?',
    options: ['Wankhede Stadium', 'Eden Gardens', 'Chepauk', 'Chinnaswamy Stadium'],
    correctIndex: 1,
    explanation: 'India had slumped from 98 for 1 to 120 for 8 chasing 252 when bottles and fruit rained onto the outfield.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1996_Cricket_World_Cup_1st_semi-final',
    sourceLabel: 'Wikipedia: 1996 Cricket World Cup 1st semi-final',
  },
  {
    id: 'cr224',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1996 World Cup semi-final',
    difficulty: 'expert',
    question: 'Which match referee awarded the 1996 semi-final to Sri Lanka by default?',
    options: ['Clive Lloyd', 'Raman Subba Row', 'Cammie Smith', 'Peter van der Merwe'],
    correctIndex: 0,
    explanation: "It was the first World Cup match ever awarded by default; Aravinda de Silva's 47-ball 66 earned the match award.",
    sourceUrl: 'https://en.wikipedia.org/wiki/1996_Cricket_World_Cup_1st_semi-final',
    sourceLabel: 'Wikipedia: 1996 Cricket World Cup 1st semi-final',
  },
  {
    id: 'cr225',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1996 World Cup semi-final',
    difficulty: 'extreme',
    question: "What was India's score when the 1996 semi-final at Eden Gardens was called off?",
    options: ['98 for 6', '110 for 7', '132 for 9', '120 for 8'],
    correctIndex: 3,
    explanation: "India lost seven wickets for 22 runs after Tendulkar's 65; Vinod Kambli walked off in tears, unbeaten.",
    sourceUrl: 'https://en.wikipedia.org/wiki/1996_Cricket_World_Cup_1st_semi-final',
    sourceLabel: 'Wikipedia: 1996 Cricket World Cup 1st semi-final',
  },
  {
    id: 'cr226',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1996 World Cup semi-final',
    difficulty: 'expert',
    question: "Tendulkar's 65 in the 1996 semi-final ended with a stumping off which bowler?",
    options: ['Muttiah Muralitharan', 'Kumar Dharmasena', 'Sanath Jayasuriya', 'Aravinda de Silva'],
    correctIndex: 2,
    explanation: 'Jayasuriya finished with 3 for 12 after Javagal Srinath had removed both Sri Lanka openers early.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1996_Cricket_World_Cup_1st_semi-final',
    sourceLabel: 'Wikipedia: 1996 Cricket World Cup 1st semi-final',
  },
  {
    id: 'cr227',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1996 World Cup',
    difficulty: 'simple',
    question: 'Who was the leading run-scorer of the 1996 World Cup, with 523 runs?',
    options: ['Mark Waugh', 'Sachin Tendulkar', 'Aravinda de Silva', 'Gary Kirsten'],
    correctIndex: 1,
    explanation: 'He made two centuries and three fifties; Sanath Jayasuriya was named player of the tournament.',
    sourceUrl: 'https://en.wikipedia.org/wiki/1996_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 1996 Cricket World Cup',
  },
  // ---------------------------------------------------------------- Lord's 1996: Ganguly and Dravid
  {
    id: 'cr228',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Lord's debuts 1996",
    difficulty: 'simple',
    question: "How many did Sourav Ganguly score on Test debut at Lord's in June 1996?",
    options: ['131', '101', '118', '152'],
    correctIndex: 0,
    explanation: "It remains the highest score by a debutant at Lord's; he followed it with 136 in his second Test.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Sourav_Ganguly',
    sourceLabel: 'Wikipedia: Sourav Ganguly',
  },
  {
    id: 'cr229',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Lord's debuts 1996",
    difficulty: 'expert',
    question: "Rahul Dravid made 95 on debut at Lord's in 1996 after which batsman was ruled out with an ankle injury?",
    options: ['Vinod Kambli', 'Navjot Sidhu', 'Ajay Jadeja', 'Sanjay Manjrekar'],
    correctIndex: 3,
    explanation: "Dravid's ODI debut had come two months earlier, against Sri Lanka in the Singer Cup at Singapore.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Rahul_Dravid',
    sourceLabel: 'Wikipedia: Rahul Dravid',
  },
  {
    id: 'cr230',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: "Lord's debuts 1996",
    difficulty: 'extreme',
    question: 'Ganguly followed his debut 131 with 136 in his second Test at which ground?',
    options: ['Edgbaston', 'Headingley', 'Trent Bridge', 'The Oval'],
    correctIndex: 2,
    explanation: 'Tendulkar made 177 in the same match; England won the three-Test series 1-0.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_1996',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 1996',
  },
  {
    id: 'cr231',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Navjot Sidhu',
    difficulty: 'expert',
    question:
      "Which opener walked out of India's 1996 tour of England after the second ODI following a row with captain Azharuddin?",
    options: ['Vikram Rathour', 'Navjot Sidhu', 'Ajay Jadeja', 'Manoj Prabhakar'],
    correctIndex: 1,
    explanation: 'Azharuddin lost the captaincy after the tour and Tendulkar was appointed in August 1996.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_1996',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 1996',
  },
  // ---------------------------------------------------------------- Kambli
  {
    id: 'cr232',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Vinod Kambli',
    difficulty: 'simple',
    question: "Vinod Kambli's 224 against England in February 1993 was made at which ground?",
    options: ['Wankhede Stadium', 'Eden Gardens', 'Chepauk', 'Feroz Shah Kotla'],
    correctIndex: 0,
    explanation: 'It came in only his third Test, in a total of 591, and India won by an innings and 15 runs to sweep the series 3-0.',
    sourceUrl: 'https://en.wikipedia.org/wiki/English_cricket_team_in_India_in_1992%E2%80%9393',
    sourceLabel: 'Wikipedia: English cricket team in India in 1992–93',
  },
  {
    id: 'cr233',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Vinod Kambli',
    difficulty: 'expert',
    question: "Kambli's next Test innings after his 224 was another double century, 227, against which team?",
    options: ['Sri Lanka', 'New Zealand', 'West Indies', 'Zimbabwe'],
    correctIndex: 3,
    explanation: 'The one-off Delhi Test in March 1993 was won by an innings and 13 runs; Kambli faced 301 balls.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Zimbabwean_cricket_team_in_India_in_1992%E2%80%9393',
    sourceLabel: 'Wikipedia: Zimbabwean cricket team in India in 1992–93',
  },
  {
    id: 'cr234',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Vinod Kambli',
    difficulty: 'extreme',
    question: 'Kambli played his last Test in November 1995, aged 23, against which team?',
    options: ['West Indies', 'South Africa', 'New Zealand', 'Sri Lanka'],
    correctIndex: 2,
    explanation: 'He finished with four centuries in 17 Tests at an average of 54.20, the highest by an Indian.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Vinod_Kambli',
    sourceLabel: 'Wikipedia: Vinod Kambli',
  },
  // ---------------------------------------------------------------- Jayasuriya
  {
    id: 'cr235',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: 'Sanath Jayasuriya',
    difficulty: 'extreme',
    question: "Sanath Jayasuriya's 340 against India at Colombo in 1997 came in a Sri Lanka total of what?",
    options: ['903 for 7 declared', '952 for 6 declared', '851 for 8 declared', '1,001 for 9 declared'],
    correctIndex: 1,
    explanation: 'His 576-run stand with Roshan Mahanama was then the highest for any wicket in Tests; the match was drawn.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Sri_Lanka_in_1997',
    sourceLabel: 'Wikipedia: Indian cricket team in Sri Lanka in 1997',
  },
  // ---------------------------------------------------------------- Desert Storm, Sharjah 1998
  {
    id: 'cr236',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Desert Storm 1998',
    difficulty: 'simple',
    question: "Tendulkar's 'Desert Storm' 143 at Sharjah in April 1998 was scored against which team?",
    options: ['Australia', 'New Zealand', 'Pakistan', 'South Africa'],
    correctIndex: 0,
    explanation: 'A sandstorm halted play; India lost the match but qualified for the final ahead of New Zealand.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sachin_Tendulkar',
    sourceLabel: 'Wikipedia: Sachin Tendulkar',
  },
  {
    id: 'cr237',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Desert Storm 1998',
    difficulty: 'extreme',
    question: 'How many did Tendulkar score in the 1998 Coca-Cola Cup final at Sharjah, played on his 25th birthday?',
    options: ['122', '143', '155', '134'],
    correctIndex: 3,
    explanation: "India chased Australia's 272 for 9 to win by six wickets; Tendulkar made 435 runs in the tournament.",
    sourceUrl:
      'https://www.cricket.com.au/news/sachin-tendulkar-revisits-1998-tri-series-final-desert-storm-century-australia-sharjah/2018-04-22',
    sourceLabel: "cricket.com.au: On this day, Sachin's stunning Desert Storm",
  },
  // ---------------------------------------------------------------- Tendulkar as captain
  {
    id: 'cr238',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Tendulkar captaincy',
    difficulty: 'expert',
    question:
      "In Tendulkar's first Test as captain, against Australia at Delhi in October 1996, which wicketkeeper opened the batting and made 152?",
    options: ['Kiran More', 'Saba Karim', 'Nayan Mongia', 'MSK Prasad'],
    correctIndex: 2,
    explanation: 'India won by seven wickets in the inaugural Border-Gavaskar Trophy match and Mongia was player of the match.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Australian_cricket_team_in_India_in_1996%E2%80%9397',
    sourceLabel: 'Wikipedia: Australian cricket team in India in 1996–97',
  },
  // ---------------------------------------------------------------- 1999 World Cup
  {
    id: 'cr239',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1999 World Cup',
    difficulty: 'simple',
    question: "Returning to the 1999 World Cup after his father's funeral, Tendulkar scored 140 not out against which team?",
    options: ['Zimbabwe', 'Kenya', 'Sri Lanka', 'England'],
    correctIndex: 1,
    explanation: 'Ramesh Tendulkar died on 19 May 1999; the 101-ball innings at Bristol was dedicated to him.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sachin_Tendulkar',
    sourceLabel: 'Wikipedia: Sachin Tendulkar',
  },
  {
    id: 'cr240',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1999 World Cup',
    difficulty: 'extreme',
    question:
      'Zimbabwe beat India by three runs at Leicester in the 1999 World Cup. Which bowler took three wickets in the final over?',
    options: ['Henry Olonga', 'Heath Streak', 'Eddo Brandes', 'Neil Johnson'],
    correctIndex: 0,
    explanation: "It was Zimbabwe's first World Cup win over India, in the match Tendulkar missed after his father's death.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Henry_Olonga',
    sourceLabel: 'Wikipedia: Henry Olonga',
  },
  {
    id: 'cr241',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '1999 World Cup',
    difficulty: 'expert',
    question: 'At which ground did Tendulkar score his 140 not out against Kenya in the 1999 World Cup?',
    options: ['Taunton', 'Hove', 'Leicester', 'Bristol'],
    correctIndex: 3,
    explanation: 'Rahul Dravid finished that tournament as its leading run-scorer with 461 runs in eight matches.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sachin_Tendulkar',
    sourceLabel: 'Wikipedia: Sachin Tendulkar',
  },
  // ---------------------------------------------------------------- Chennai 1999
  {
    id: 'cr242',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Chennai Test 1999',
    difficulty: 'expert',
    question: "By how many runs did Pakistan win the January 1999 Chennai Test despite Tendulkar's 136?",
    options: ['5', '21', '12', '46'],
    correctIndex: 2,
    explanation:
      'Saqlain Mushtaq took five wickets in each innings, and the Chennai crowd applauded the Pakistanis on a lap of honour.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pakistani_cricket_team_in_India_in_1998%E2%80%9399',
    sourceLabel: 'Wikipedia: Pakistani cricket team in India in 1998–99',
  },
  {
    id: 'cr243',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Chennai Test 1999',
    difficulty: 'simple',
    question: "Tendulkar's 136 at Chennai in 1999 ended when he was caught by Wasim Akram off which bowler?",
    options: ['Mushtaq Ahmed', 'Saqlain Mushtaq', 'Shahid Afridi', 'Waqar Younis'],
    correctIndex: 1,
    explanation: 'Saqlain took 5 for 93 in that innings after 5 for 94 in the first; India were all out for 258 chasing 271.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pakistani_cricket_team_in_India_in_1998%E2%80%9399',
    sourceLabel: 'Wikipedia: Pakistani cricket team in India in 1998–99',
  },
  {
    id: 'cr244',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Chennai Test 1999',
    difficulty: 'extreme',
    question: "Who made 141 in Pakistan's second innings of the 1999 Chennai Test?",
    options: ['Shahid Afridi', 'Inzamam-ul-Haq', 'Saeed Anwar', 'Yousuf Youhana'],
    correctIndex: 0,
    explanation: "It was Pakistan's first Test tour of India in 12 years and the two-match series ended 1-1.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Pakistani_cricket_team_in_India_in_1998%E2%80%9399',
    sourceLabel: 'Wikipedia: Pakistani cricket team in India in 1998–99',
  },
  // ---------------------------------------------------------------- Asian Test Championship, Kolkata 1999
  {
    id: 'cr245',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Javagal Srinath',
    difficulty: 'expert',
    question: "Who took 8 for 86 in Pakistan's second innings of the 1999 Asian Test Championship match at Eden Gardens?",
    options: ['Anil Kumble', 'Venkatesh Prasad', 'Harbhajan Singh', 'Javagal Srinath'],
    correctIndex: 3,
    explanation: "Srinath's 13 for 132 in the match was in vain; Saeed Anwar's 188 not out set up a 46-run Pakistan win.",
    sourceUrl: 'https://en.wikipedia.org/wiki/1998%E2%80%9399_Asian_Test_Championship',
    sourceLabel: 'Wikipedia: 1998–99 Asian Test Championship',
  },
  {
    id: 'cr246',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Eden Gardens 1999',
    difficulty: 'extreme',
    question: "What was Tendulkar's score when he was run out after colliding with Shoaib Akhtar at Eden Gardens in February 1999?",
    options: ['0', '24', '9', '57'],
    correctIndex: 2,
    explanation:
      "Substitute Nadeem Khan's direct hit did the damage; the crowd was cleared and the match finished in near-empty stands.",
    sourceUrl:
      'https://www.wisden.com/cricket-news/watch-when-the-run-out-of-sachin-tendulkar-against-pakistan-brought-the-game-to-a-standstill-at-the-eden-gardens',
    sourceLabel: 'Wisden: When the run out of Sachin Tendulkar brought the game to a standstill at Eden Gardens',
  },
  // ---------------------------------------------------------------- Jadeja, Sidhu, 1993 away win
  {
    id: 'cr247',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Ajay Jadeja',
    difficulty: 'simple',
    question:
      'Which India batsman, remembered for his 1996 quarter-final cameo against Pakistan, was banned for five years by the BCCI in June 2000?',
    options: ['Nayan Mongia', 'Ajay Jadeja', 'Robin Singh', 'Ajit Agarkar'],
    correctIndex: 1,
    explanation: 'The Delhi High Court lifted the ban in January 2003, ruling that the investigation had been one-sided.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ajay_Jadeja',
    sourceLabel: 'Wikipedia: Ajay Jadeja',
  },
  {
    id: 'cr248',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Navjot Sidhu',
    difficulty: 'expert',
    question: 'Navjot Sidhu hit eight sixes in his 124 at Lucknow in 1994, an Indian record. Six of them came off which bowler?',
    options: ['Muttiah Muralitharan', 'Kumar Dharmasena', 'Don Anurasiri', 'Ruwan Kalpage'],
    correctIndex: 0,
    explanation: "India won by an innings and 119 runs and Kumble's 7 for 59 earned him the match award.",
    sourceUrl:
      'https://www.cricketcountry.com/articles/navjot-singh-sidhu-bludgeons-muttiah-muralitharan-led-sri-lankan-attack-for-eight-sixes-in-1994-86701/',
    sourceLabel: 'Cricket Country: Navjot Singh Sidhu bludgeons Muralitharan-led attack for eight sixes in 1994',
  },
  {
    id: 'cr249',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'India abroad in the 1990s',
    difficulty: 'simple',
    question: 'In 1993 India won their first overseas Test series in seven years, 1-0. Who were the opponents?',
    options: ['Zimbabwe', 'New Zealand', 'West Indies', 'Sri Lanka'],
    correctIndex: 3,
    explanation: "The 235-run win at Colombo's SSC was built on Kambli's 125 and Tendulkar's unbeaten 104.",
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Sri_Lanka_in_1993',
    sourceLabel: 'Wikipedia: Indian cricket team in Sri Lanka in 1993',
  },
]);
