// Server-only editorial bank: Indian cricket, tranche 4 — 2000 to 2007 (50 questions, cr250–cr299).
// Never import this module from client components.
// Every fact below was checked against the page at sourceUrl when written.
export const CRICKET_INDIA_4 = Object.freeze([
  // ---------------------------------------------------------------- 2000: match-fixing and a new captain
  {
    id: 'cr250',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: '2000 match-fixing scandal',
    difficulty: 'simple',
    question:
      'Which South Africa captain was exposed by Delhi Police recordings in April 2000 and later banned from cricket for life?',
    options: ['Hansie Cronje', 'Shaun Pollock', 'Kepler Wessels', 'Gary Kirsten'],
    correctIndex: 0,
    explanation:
      'Cronje was sacked on 11 April 2000 and the King Commission followed; the life ban came in October 2000.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Hansie_Cronje',
    sourceLabel: 'Wikipedia: Hansie Cronje',
  },
  {
    id: 'cr251',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2000 match-fixing scandal',
    difficulty: 'simple',
    question:
      'Which former India captain was banned for life by the BCCI in December 2000 on the strength of a CBI report into match-fixing?',
    options: ['Ajay Jadeja', 'Kapil Dev', 'Manoj Prabhakar', 'Mohammad Azharuddin'],
    correctIndex: 3,
    explanation:
      'The CBI report was released on 1 November 2000; Cronje had claimed Azharuddin introduced him to fixers.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mohammad_Azharuddin',
    sourceLabel: 'Wikipedia: Mohammad Azharuddin',
  },
  {
    id: 'cr252',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2000 match-fixing scandal',
    difficulty: 'extreme',
    question: "Which court overturned Mohammad Azharuddin's life ban in November 2012?",
    options: ['Delhi High Court', 'Bombay High Court', 'Andhra Pradesh High Court', 'Supreme Court of India'],
    correctIndex: 2,
    explanation:
      'A divisional bench lifted the ban on 8 November 2012, twelve years after it was imposed; Azharuddin had by then served as MP for Moradabad.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mohammad_Azharuddin',
    sourceLabel: 'Wikipedia: Mohammad Azharuddin',
  },
  {
    id: 'cr253',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: '2000 match-fixing scandal',
    difficulty: 'extreme',
    question:
      'Hansie Cronje died in a plane crash in June 2002 in the Outeniqua Mountains near which South African town?',
    options: ['Bloemfontein', 'George', 'Pietermaritzburg', 'Kimberley'],
    correctIndex: 1,
    explanation:
      'The crash on 1 June 2002 also killed the two pilots; Cronje was 32 and had lost an appeal against his ban the previous October.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Hansie_Cronje',
    sourceLabel: 'Wikipedia: Hansie Cronje',
  },
  {
    id: 'cr254',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sourav Ganguly captaincy',
    difficulty: 'simple',
    question: 'Whose resignation as India captain in 2000 opened the way for Sourav Ganguly to take charge?',
    options: ['Sachin Tendulkar', 'Mohammad Azharuddin', 'Anil Kumble', 'Rahul Dravid'],
    correctIndex: 0,
    explanation:
      'Tendulkar stepped down after a 0-2 home Test defeat to South Africa; Ganguly went on to captain India in 49 Tests, winning 21.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sourav_Ganguly',
    sourceLabel: 'Wikipedia: Sourav Ganguly',
  },
  {
    id: 'cr255',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Sourav Ganguly captaincy',
    difficulty: 'expert',
    question:
      "Against which opponent did Sourav Ganguly captain India in a Test for the first time, in that nation's inaugural Test in November 2000?",
    options: ['Zimbabwe', 'Bangladesh', 'Sri Lanka', 'South Africa'],
    correctIndex: 1,
    explanation:
      'At Dhaka, Aminul Islam made 145 for the hosts and Sunil Joshi took 5 for 142 and scored 92 as India won by nine wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Bangladesh_in_2000%E2%80%9301',
    sourceLabel: 'Wikipedia: Indian cricket team in Bangladesh in 2000–01',
  },
  {
    id: 'cr256',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2000 ICC KnockOut Trophy',
    difficulty: 'expert',
    question:
      'Which side beat India in the final of the 2000 ICC KnockOut Trophy in Nairobi despite a Ganguly century?',
    options: ['New Zealand', 'South Africa', 'Australia', 'Pakistan'],
    correctIndex: 0,
    explanation:
      'Chris Cairns made an unbeaten 102 to chase down 265 with four wickets in hand; Ganguly had scored 117.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2000_ICC_KnockOut_Trophy',
    sourceLabel: 'Wikipedia: 2000 ICC KnockOut Trophy',
  },
  // ---------------------------------------------------------------- 2001: Kolkata and Bloemfontein
  {
    id: 'cr257',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2001 Kolkata Test',
    difficulty: 'simple',
    question:
      'Who scored 281 for India against Australia at Eden Gardens in March 2001 after India had been asked to follow on?',
    options: ['Rahul Dravid', 'Sachin Tendulkar', 'VVS Laxman', 'Sourav Ganguly'],
    correctIndex: 2,
    explanation:
      "Laxman's 281 off 452 balls beat Sunil Gavaskar's 236 not out as the highest Test score by an Indian at the time.",
    sourceUrl: 'https://en.wikipedia.org/wiki/VVS_Laxman',
    sourceLabel: 'Wikipedia: VVS Laxman',
  },
  {
    id: 'cr258',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2001 Kolkata Test',
    difficulty: 'expert',
    question: "Which three Australians fell to Harbhajan Singh's hat-trick at Eden Gardens in 2001, the first by an Indian in Tests?",
    options: [
      'Ricky Ponting, Adam Gilchrist, Shane Warne',
      'Steve Waugh, Adam Gilchrist, Jason Gillespie',
      'Ricky Ponting, Mark Waugh, Shane Warne',
      'Matthew Hayden, Steve Waugh, Glenn McGrath',
    ],
    correctIndex: 0,
    explanation:
      'The third wicket, Warne, was confirmed only after a long wait for the third umpire; Harbhajan took 7 for 123 in the innings.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Harbhajan_Singh',
    sourceLabel: 'Wikipedia: Harbhajan Singh',
  },
  {
    id: 'cr259',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2001 Kolkata Test',
    difficulty: 'extreme',
    question: 'How many runs did VVS Laxman and Rahul Dravid add together in the second innings at Kolkata in 2001?',
    options: ['303', '411', '353', '376'],
    correctIndex: 3,
    explanation:
      'Dravid made 180, his first century against Australia, as India declared on 657 for 7 and won by 171 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Australian_cricket_team_in_India_in_2000%E2%80%9301',
    sourceLabel: 'Wikipedia: Australian cricket team in India in 2000–01',
  },
  {
    id: 'cr260',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2001 Kolkata Test',
    difficulty: 'extreme',
    question:
      'How many consecutive Test wins had Steve Waugh\'s Australia recorded, a world record, before India ended the run at Kolkata in 2001?',
    options: ['12 Tests', '16 Tests', '14 Tests', '18 Tests'],
    correctIndex: 1,
    explanation:
      'India became only the third team to win a Test after following on; Australia had taken a 274-run first-innings lead.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Australian_cricket_team_in_India_in_2000%E2%80%9301',
    sourceLabel: 'Wikipedia: Australian cricket team in India in 2000–01',
  },
  {
    id: 'cr261',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2001 Border-Gavaskar Trophy',
    difficulty: 'expert',
    question: 'How many wickets did Harbhajan Singh take in the three-Test home series against Australia in 2001?',
    options: ['24', '28', '36', '32'],
    correctIndex: 3,
    explanation:
      'He was player of the series, taking 15 for 217 in the Chennai decider, which India won by two wickets to take the series 2-1.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Australian_cricket_team_in_India_in_2000%E2%80%9301',
    sourceLabel: 'Wikipedia: Australian cricket team in India in 2000–01',
  },
  {
    id: 'cr262',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Virender Sehwag',
    difficulty: 'simple',
    question: 'Against which side did Virender Sehwag score 105 on Test debut at Bloemfontein in November 2001?',
    options: ['England', 'Australia', 'South Africa', 'Zimbabwe'],
    correctIndex: 2,
    explanation:
      'The century came in a losing cause; the hosts won by nine wickets and took the two-Test series 1-0.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Virender_Sehwag',
    sourceLabel: 'Wikipedia: Virender Sehwag',
  },
  {
    id: 'cr263',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Virender Sehwag',
    difficulty: 'extreme',
    question: 'At which position in the batting order did Virender Sehwag make his debut hundred at Bloemfontein in 2001?',
    options: ['Number six', 'Opener', 'Number three', 'Number four'],
    correctIndex: 0,
    explanation:
      'He was a middle-order batsman then; his first ODI innings, in April 1999 at Mohali, had ended lbw to Shoaib Akhtar for 1.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Virender_Sehwag',
    sourceLabel: 'Wikipedia: Virender Sehwag',
  },
  {
    id: 'cr264',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2001 Port Elizabeth controversy',
    difficulty: 'expert',
    question:
      'Which match referee sanctioned six Indian players at Port Elizabeth in 2001, including Tendulkar for alleged ball-tampering?',
    options: ['Clive Lloyd', 'Ranjan Madugalle', 'Mike Denness', 'Chris Broad'],
    correctIndex: 2,
    explanation:
      'India refused to accept the sanctions and the ICC stripped the following Centurion match of Test status.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mike_Denness',
    sourceLabel: 'Wikipedia: Mike Denness',
  },
  // ---------------------------------------------------------------- 2002: NatWest final at Lord's
  {
    id: 'cr265',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2002 NatWest final',
    difficulty: 'simple',
    question: 'On the balcony of which ground did Sourav Ganguly whirl his shirt after India chased 326 in the 2002 NatWest final?',
    options: ['The Oval', 'Trent Bridge', 'Edgbaston', "Lord's"],
    correctIndex: 3,
    explanation:
      'Ganguly said he was mimicking Andrew Flintoff, who had done the same in India earlier that year; India won by two wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sourav_Ganguly',
    sourceLabel: 'Wikipedia: Sourav Ganguly',
  },
  {
    id: 'cr266',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2002 NatWest final',
    difficulty: 'simple',
    question: 'Who was man of the match in the 2002 NatWest final with an unbeaten 87 off 75 balls?',
    options: ['Yuvraj Singh', 'Mohammad Kaif', 'Sourav Ganguly', 'Virender Sehwag'],
    correctIndex: 1,
    explanation:
      'Kaif came in with India 146 for 5 and guided the tail home; England had made 325 for 5.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mohammad_Kaif',
    sourceLabel: 'Wikipedia: Mohammad Kaif',
  },
  {
    id: 'cr267',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2002 NatWest final',
    difficulty: 'expert',
    question: 'Which England captain made 115 in the 2002 NatWest final at Lord\'s?',
    options: ['Nasser Hussain', 'Michael Vaughan', 'Marcus Trescothick', 'Andrew Flintoff'],
    correctIndex: 0,
    explanation:
      'Hussain and Trescothick shared a 185-run stand, and Flintoff added 40 off 32 before Zaheer Khan removed him.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2002_NatWest_Series',
    sourceLabel: 'Wikipedia: 2002 NatWest Series',
  },
  {
    id: 'cr268',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2002 NatWest final',
    difficulty: 'extreme',
    question: 'How many runs did Yuvraj Singh score in his sixth-wicket stand with Mohammad Kaif in the 2002 NatWest final?',
    options: ['58', '75', '69', '87'],
    correctIndex: 2,
    explanation:
      'Yuvraj faced 63 balls and the pair added 121 before Paul Collingwood dismissed him; India won with three balls to spare.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Yuvraj_Singh',
    sourceLabel: 'Wikipedia: Yuvraj Singh',
  },
  // ---------------------------------------------------------------- 2003 World Cup
  {
    id: 'cr269',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2003 World Cup',
    difficulty: 'simple',
    question: 'At which South African ground did Sachin Tendulkar make his 98 off 75 balls against Pakistan in the 2003 World Cup?',
    options: ['Durban', 'Johannesburg', 'Centurion', 'Cape Town'],
    correctIndex: 2,
    explanation:
      'India chased 274 with more than four overs to spare after Saeed Anwar had made 101 for Pakistan; Shoaib Akhtar finally had Tendulkar caught off a bouncer.',
    sourceUrl: 'https://www.wisden.com/cricket-news/watch-sachin-tendulkar-shoaib-akhtar-six-ind-pak-2003-world-cup-india-pakistan',
    sourceLabel: 'Wisden: Tendulkar hard slashes Shoaib Akhtar for iconic six',
  },
  {
    id: 'cr270',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2003 World Cup final',
    difficulty: 'expert',
    question: 'By how many runs did Australia beat India in the 2003 World Cup final at the Wanderers?',
    options: ['140 runs', '96 runs', '77 runs', '125 runs'],
    correctIndex: 3,
    explanation:
      'Ricky Ponting hit 140 not out with eight sixes in a total of 359 for 2; India were bowled out for 234 with Sehwag top-scoring on 82.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2003_Cricket_World_Cup_final',
    sourceLabel: 'Wikipedia: 2003 Cricket World Cup final',
  },
  {
    id: 'cr271',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2003 World Cup',
    difficulty: 'expert',
    question: 'Which Indian bowler took 6 for 23 against England at Durban in the 2003 World Cup?',
    options: ['Zaheer Khan', 'Ashish Nehra', 'Javagal Srinath', 'Harbhajan Singh'],
    correctIndex: 1,
    explanation:
      'They stayed the best World Cup figures by an Indian until Mohammed Shami bettered them in 2023; India won by 82 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ashish_Nehra',
    sourceLabel: 'Wikipedia: Ashish Nehra',
  },
  {
    id: 'cr272',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2003 World Cup',
    difficulty: 'extreme',
    question: 'How many runs did Sachin Tendulkar score across the 2003 World Cup on his way to the player of the tournament award?',
    options: ['587', '673', '623', '712'],
    correctIndex: 1,
    explanation:
      'He played 11 matches and led the run charts by a distance even though Australia won the final.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2003_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 2003 Cricket World Cup',
  },
  // ---------------------------------------------------------------- 2003-04: Australia and Pakistan away
  {
    id: 'cr273',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2003 Adelaide Test',
    difficulty: 'simple',
    question: 'Who scored 233 and an unbeaten 72 as India won the Adelaide Test of December 2003 by four wickets?',
    options: ['VVS Laxman', 'Sachin Tendulkar', 'Rahul Dravid', 'Sourav Ganguly'],
    correctIndex: 2,
    explanation:
      'It was India\'s first Test win in Australia for 23 years; Dravid square-cut the winning boundary and kissed the crest on his cap.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Rahul_Dravid',
    sourceLabel: 'Wikipedia: Rahul Dravid',
  },
  {
    id: 'cr274',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2003 Adelaide Test',
    difficulty: 'expert',
    question: "Which Indian seamer took 6 for 41 to bowl Australia out for 196 in the second innings at Adelaide in 2003?",
    options: ['Ashish Nehra', 'Zaheer Khan', 'Irfan Pathan', 'Ajit Agarkar'],
    correctIndex: 3,
    explanation:
      'Australia had made 556 in the first innings; Dravid and Laxman replied with a 303-run stand after India were 85 for 4.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Australia_in_2003%E2%80%9304',
    sourceLabel: 'Wikipedia: Indian cricket team in Australia in 2003–04',
  },
  {
    id: 'cr275',
    domain: 'sports',
    region: 'Global',
    topic: 'Cricket',
    subtopic: '2003 Adelaide Test',
    difficulty: 'extreme',
    question: 'Which Australian made 242 in the first innings at Adelaide in 2003 and still finished on the losing side?',
    options: ['Matthew Hayden', 'Ricky Ponting', 'Justin Langer', 'Steve Waugh'],
    correctIndex: 1,
    explanation:
      'It was then the highest Test score in a defeat; Ponting followed it with 257 at Melbourne, where Australia won by nine wickets.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ricky_Ponting',
    sourceLabel: 'Wikipedia: Ricky Ponting',
  },
  {
    id: 'cr276',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2004 Pakistan tour',
    difficulty: 'simple',
    question: 'At which Pakistani venue did Virender Sehwag score 309, the first Test triple century by an Indian, in March 2004?',
    options: ['Lahore', 'Karachi', 'Multan', 'Rawalpindi'],
    correctIndex: 2,
    explanation:
      'The 309 came off 375 balls; India declared on 675 for 5 and won by an innings and 52 runs, their first Test win on Pakistani soil.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Pakistan_in_2003%E2%80%9304',
    sourceLabel: 'Wikipedia: Indian cricket team in Pakistan in 2003–04',
  },
  {
    id: 'cr277',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2004 Pakistan tour',
    difficulty: 'expert',
    question: 'On what score was Sachin Tendulkar left unbeaten when Rahul Dravid declared at Multan in 2004?',
    options: ['194', '199', '198', '186'],
    correctIndex: 0,
    explanation:
      'Dravid, standing in as captain, wanted overs at tired Pakistani batsmen; Tendulkar was six short of a fourth Test double hundred.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Rahul_Dravid',
    sourceLabel: 'Wikipedia: Rahul Dravid',
  },
  {
    id: 'cr278',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2004 Pakistan tour',
    difficulty: 'extreme',
    question: 'By what margin did India win the Rawalpindi Test of 2004, in which Rahul Dravid made 270, to take the series 2-1?',
    options: ['An innings and 131 runs', 'An innings and 52 runs', 'Ten wickets', 'Eight wickets'],
    correctIndex: 0,
    explanation:
      'The 270 remains Dravid\'s Test best; he was finally out to a reverse sweep. Pakistan had squared the series at Lahore, where Umar Gul took 5 for 31.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_Pakistan_in_2003%E2%80%9304',
    sourceLabel: 'Wikipedia: Indian cricket team in Pakistan in 2003–04',
  },
  {
    id: 'cr279',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2004 Karachi ODI',
    difficulty: 'expert',
    question: 'Who bowled the final over for India in the Karachi ODI of March 2004, defending nine runs to win by five?',
    options: ['Zaheer Khan', 'Irfan Pathan', 'Ashish Nehra', 'Lakshmipathy Balaji'],
    correctIndex: 2,
    explanation:
      'Moin Khan needed six off the last ball and skied a full toss to cover; India had made 349 for 7 and Inzamam-ul-Haq 122 in reply.',
    sourceUrl: 'https://www.thecricketmonthly.com/story/1372559/greatest-odis-no-10-pakistan-vs-india-karachi-2004',
    sourceLabel: 'The Cricket Monthly: Greatest ODIs No. 10, Pakistan v India, Karachi 2004',
  },
  // ---------------------------------------------------------------- 2005-06: Chappell, Dhoni, Pathan, Johannesburg
  {
    id: 'cr280',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Greg Chappell era',
    difficulty: 'simple',
    question: 'Which Australian was appointed India coach in May 2005 on a contract running to the 2007 World Cup?',
    options: ['John Wright', 'Greg Chappell', 'Dav Whatmore', 'Ian Chappell'],
    correctIndex: 1,
    explanation:
      'He resigned after India went out in the first round of the 2007 World Cup; Sehwag, Harbhajan and Zaheer all criticised his methods publicly.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Greg_Chappell',
    sourceLabel: 'Wikipedia: Greg Chappell',
  },
  {
    id: 'cr281',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Greg Chappell era',
    difficulty: 'expert',
    question:
      'On the 2005 tour of which country did Sourav Ganguly score a century and then allege that Greg Chappell had asked him to step down as captain?',
    options: ['Sri Lanka', 'Bangladesh', 'West Indies', 'Zimbabwe'],
    correctIndex: 3,
    explanation:
      'Ganguly made 101 at Bulawayo in an innings win; he was dropped in October 2005 and did not return until the end of 2006.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Greg_Chappell',
    sourceLabel: 'Wikipedia: Greg Chappell',
  },
  {
    id: 'cr282',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'MS Dhoni',
    difficulty: 'simple',
    question: 'At which venue did MS Dhoni hit 148 off 123 balls against Pakistan in April 2005, in only his fifth ODI?',
    options: ['Visakhapatnam', 'Kochi', 'Jamshedpur', 'Ahmedabad'],
    correctIndex: 0,
    explanation:
      'The innings beat the previous highest ODI score by an Indian wicketkeeper; Dhoni had been run out for a duck on debut four months earlier.',
    sourceUrl: 'https://en.wikipedia.org/wiki/MS_Dhoni',
    sourceLabel: 'Wikipedia: MS Dhoni',
  },
  {
    id: 'cr283',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'MS Dhoni',
    difficulty: 'expert',
    question: 'Against which side did MS Dhoni make an unbeaten 183 at Jaipur in October 2005 after being promoted to number three?',
    options: ['Sri Lanka', 'Pakistan', 'England', 'South Africa'],
    correctIndex: 0,
    explanation:
      'The 145-ball innings was then the highest ODI score in a run chase; Wisden called it uninhibited yet anything but crude.',
    sourceUrl: 'https://en.wikipedia.org/wiki/MS_Dhoni',
    sourceLabel: 'Wikipedia: MS Dhoni',
  },
  {
    id: 'cr284',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'MS Dhoni',
    difficulty: 'extreme',
    question: 'How was MS Dhoni dismissed for nought on his ODI debut against Bangladesh in December 2004?',
    options: ['Bowled', 'Caught behind', 'Lbw', 'Run out'],
    correctIndex: 3,
    explanation:
      'His Test debut followed a year later at Chennai against Sri Lanka, where he made 30 in a rain-hit draw.',
    sourceUrl: 'https://en.wikipedia.org/wiki/MS_Dhoni',
    sourceLabel: 'Wikipedia: MS Dhoni',
  },
  {
    id: 'cr285',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Irfan Pathan',
    difficulty: 'simple',
    question: 'Which Indian bowler took a hat-trick in the first over of the Karachi Test against Pakistan in January 2006?',
    options: ['Zaheer Khan', 'RP Singh', 'Munaf Patel', 'Irfan Pathan'],
    correctIndex: 3,
    explanation:
      'It remains the only hat-trick in the opening over of a Test; Pakistan recovered through Kamran Akmal\'s 113 and won by 341 runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Irfan_Pathan',
    sourceLabel: 'Wikipedia: Irfan Pathan',
  },
  {
    id: 'cr286',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Irfan Pathan',
    difficulty: 'expert',
    question: "Who was the third victim, bowled, in Irfan Pathan's first-over hat-trick at Karachi in 2006?",
    options: ['Younis Khan', 'Salman Butt', 'Mohammad Yousuf', 'Inzamam-ul-Haq'],
    correctIndex: 2,
    explanation:
      'Butt was caught and Younis lbw before Yousuf was bowled; Pathan finished with 5 for 61 in the innings.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Irfan_Pathan',
    sourceLabel: 'Wikipedia: Irfan Pathan',
  },
  {
    id: 'cr287',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2006 Johannesburg Test',
    difficulty: 'expert',
    question: "Who took 5 for 40 as South Africa were bowled out for 84 in India's first Test win on South African soil, at Johannesburg in December 2006?",
    options: ['Zaheer Khan', 'S Sreesanth', 'VRV Singh', 'Munaf Patel'],
    correctIndex: 1,
    explanation:
      'India won by 123 runs with Ganguly making 51 not out on his comeback, but South Africa took the series 2-1.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_South_Africa_in_2006%E2%80%9307',
    sourceLabel: 'Wikipedia: Indian cricket team in South Africa in 2006–07',
  },
  // ---------------------------------------------------------------- 2007: World Cup exit
  {
    id: 'cr288',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2007 World Cup',
    difficulty: 'simple',
    question: 'Which side beat India by five wickets at Port of Spain in the 2007 World Cup, setting up their group-stage exit?',
    options: ['Bangladesh', 'Sri Lanka', 'Ireland', 'Kenya'],
    correctIndex: 0,
    explanation:
      'India were bowled out for 191 on 17 March 2007; a 69-run loss to Sri Lanka then sent them home.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2007_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 2007 Cricket World Cup',
  },
  {
    id: 'cr289',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2007 World Cup',
    difficulty: 'expert',
    question: 'Which Bangladesh bowler took 4 for 38 in the 2007 World Cup upset of India at Port of Spain?',
    options: ['Abdur Razzak', 'Mashrafe Mortaza', 'Shakib Al Hasan', 'Mohammad Rafique'],
    correctIndex: 1,
    explanation:
      'Tamim Iqbal, Mushfiqur Rahim and Shakib Al Hasan all made fifties in the chase against a side ranked fifth in ODIs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2007_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 2007 Cricket World Cup',
  },
  {
    id: 'cr290',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2007 World Cup',
    difficulty: 'extreme',
    question: 'What total did India post against Bermuda at Port of Spain in the 2007 World Cup?',
    options: ['427 for 7', '398 for 6', '383 for 4', '413 for 5'],
    correctIndex: 3,
    explanation:
      'Virender Sehwag made 114; it was India\'s only win of the tournament under Rahul Dravid.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2007_Cricket_World_Cup',
    sourceLabel: 'Wikipedia: 2007 Cricket World Cup',
  },
  // ---------------------------------------------------------------- 2007: World Twenty20 in South Africa
  {
    id: 'cr291',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2007 World Twenty20',
    difficulty: 'simple',
    question: 'Off which England bowler did Yuvraj Singh hit six sixes in an over at Durban in the 2007 World Twenty20?',
    options: ['Andrew Flintoff', 'Stuart Broad', 'James Anderson', 'Chris Tremlett'],
    correctIndex: 1,
    explanation:
      'Yuvraj finished with 58 off 16 balls in India\'s 218 for 4; it was the first six-sixes over in Twenty20 cricket.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Yuvraj_Singh',
    sourceLabel: 'Wikipedia: Yuvraj Singh',
  },
  {
    id: 'cr292',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2007 World Twenty20',
    difficulty: 'extreme',
    question: 'How many balls did Yuvraj Singh need for his fifty against England at Durban in 2007, the fastest in T20 internationals?',
    options: ['10', '14', '12', '16'],
    correctIndex: 2,
    explanation:
      'It was also the fastest fifty in any form of international cricket at the time; he won man of the match.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Yuvraj_Singh',
    sourceLabel: 'Wikipedia: Yuvraj Singh',
  },
  {
    id: 'cr293',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2007 World Twenty20 final',
    difficulty: 'simple',
    question: 'Who bowled the last over of the 2007 World Twenty20 final for India with Pakistan needing 13 to win?',
    options: ['RP Singh', 'Harbhajan Singh', 'Joginder Sharma', 'Irfan Pathan'],
    correctIndex: 2,
    explanation:
      'After a wide and a six, Misbah-ul-Haq mistimed a scoop and Sreesanth took the catch at short fine leg; India won by five runs.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Joginder_Sharma',
    sourceLabel: 'Wikipedia: Joginder Sharma',
  },
  {
    id: 'cr294',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2007 World Twenty20',
    difficulty: 'extreme',
    question:
      'Which batsman joined Virender Sehwag and Harbhajan Singh in hitting the stumps for India in the bowl-out against Pakistan at Durban in 2007?',
    options: ['Robin Uthappa', 'Yuvraj Singh', 'Gautam Gambhir', 'Rohit Sharma'],
    correctIndex: 0,
    explanation:
      'Both sides had finished on 141; India won the bowl-out 3-0 after all three Pakistan attempts missed.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2007_ICC_World_Twenty20',
    sourceLabel: 'Wikipedia: 2007 ICC World Twenty20',
  },
  {
    id: 'cr295',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2007 World Twenty20 final',
    difficulty: 'extreme',
    question: 'Who top-scored for India with 75 off 54 balls in the 2007 World Twenty20 final at Johannesburg?',
    options: ['Yuvraj Singh', 'MS Dhoni', 'Rohit Sharma', 'Gautam Gambhir'],
    correctIndex: 3,
    explanation:
      'India made 157 for 5 and Irfan Pathan\'s 3 for 16 earned him man of the match as Pakistan were bowled out for 152.',
    sourceUrl: 'https://en.wikipedia.org/wiki/2007_ICC_World_Twenty20_final',
    sourceLabel: 'Wikipedia: 2007 ICC World Twenty20 final',
  },
  {
    id: 'cr296',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2007 World Twenty20',
    difficulty: 'extreme',
    question: 'By how many runs did India beat Australia in the 2007 World Twenty20 semi-final at Durban?',
    options: ['5 runs', '15 runs', '37 runs', '22 runs'],
    correctIndex: 1,
    explanation:
      'Yuvraj Singh made 70 off 30 balls and Joginder Sharma took two wickets in the last over with Australia needing 22.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Joginder_Sharma',
    sourceLabel: 'Wikipedia: Joginder Sharma',
  },
  // ---------------------------------------------------------------- 2007: England and Kumble's captaincy
  {
    id: 'cr297',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Anil Kumble captaincy',
    difficulty: 'expert',
    question: 'Which side did Anil Kumble face in his first Test series as India captain after his appointment in November 2007?',
    options: ['Australia', 'Sri Lanka', 'England', 'Pakistan'],
    correctIndex: 3,
    explanation:
      'Appointed at 37 after Rahul Dravid resigned, Kumble won that home series 1-0 and captained 14 Tests in all.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Anil_Kumble',
    sourceLabel: 'Wikipedia: Anil Kumble',
  },
  {
    id: 'cr298',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: 'Anil Kumble',
    difficulty: 'extreme',
    question: 'At which ground did Anil Kumble score his only Test century, an unbeaten 110, in August 2007?',
    options: ['The Oval', "Lord's", 'Trent Bridge', 'Headingley'],
    correctIndex: 0,
    explanation:
      'It came in his 118th Test, making him the only man to take all ten wickets in an innings and score a Test hundred.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Anil_Kumble',
    sourceLabel: 'Wikipedia: Anil Kumble',
  },
  {
    id: 'cr299',
    domain: 'sports',
    region: 'India',
    topic: 'Cricket',
    subtopic: '2007 tour of England',
    difficulty: 'simple',
    question: 'At which ground did Zaheer Khan find jelly beans on the pitch while batting in 2007, before bowling India to a Test win?',
    options: ['Trent Bridge', "Lord's", 'The Oval', 'Edgbaston'],
    correctIndex: 0,
    explanation:
      'Zaheer took five second-innings wickets in a seven-wicket win and finished with 18 in the series as India won 1-0, their first in England since 1986.',
    sourceUrl: 'https://en.wikipedia.org/wiki/Indian_cricket_team_in_England_in_2007',
    sourceLabel: 'Wikipedia: Indian cricket team in England in 2007',
  },
]);
