// Server-only editorial bank: Football (soccer), tranche 1. Never import this module from client components.
// Every fact below was checked against the page in sourceUrl at authoring time.
export const FOOTBALL = Object.freeze([
  {
    id: 'fb001',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Maracanazo 1950',
    difficulty: 'simple',
    question: 'Which country stunned hosts Brazil in the decisive match of the 1950 World Cup at the Maracanã?',
    options: ['Argentina', 'Uruguay', 'Italy', 'Sweden'],
    correctIndex: 1,
    explanation: 'Uruguay won 2-1 on 16 July 1950; Brazil only needed a draw in the final group to be champions.',
    sourceUrl: 'https://www.rsssf.org/tables/50full.html',
    sourceLabel: 'RSSSF: World Cup 1950 full details',
  },
  {
    id: 'fb002',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Maracanazo 1950',
    difficulty: 'expert',
    question: 'Who scored Uruguay’s winning goal against Brazil in the 1950 World Cup decider?',
    options: ['Juan Alberto Schiaffino', 'Óscar Míguez', 'Obdulio Varela', 'Alcides Ghiggia'],
    correctIndex: 3,
    explanation: 'Schiaffino equalised before Ghiggia beat Barbosa at his near post to silence the Maracanã.',
    sourceUrl: 'https://www.rsssf.org/tables/50full.html',
    sourceLabel: 'RSSSF: World Cup 1950 full details',
  },
  {
    id: 'fb003',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Maracanazo 1950',
    difficulty: 'extreme',
    question: 'Which Brazilian put the hosts ahead early in the second half of the 1950 decider before Uruguay’s comeback?',
    options: ['Ademir', 'Zizinho', 'Friaça', 'Jair'],
    correctIndex: 2,
    explanation: 'Friaça’s goal was the only one Brazil managed; Ademir had been the tournament’s top scorer.',
    sourceUrl: 'https://www.rsssf.org/tables/50full.html',
    sourceLabel: 'RSSSF: World Cup 1950 full details',
  },
  {
    id: 'fb004',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Wembley 1966',
    difficulty: 'simple',
    question: 'Who scored a hat-trick for England in the 1966 World Cup final against West Germany?',
    options: ['Bobby Charlton', 'Martin Peters', 'Geoff Hurst', 'Roger Hunt'],
    correctIndex: 2,
    explanation: 'Hurst’s treble plus a Peters goal won it 4-2; no one matched a final hat-trick until Mbappé in 2022.',
    sourceUrl: 'https://www.englandfootball.com/articles/2026/Jul/30/sir-geoff-hurst-1966-world-cup-interview-20263007',
    sourceLabel: 'England Football: Sir Geoff Hurst re-lives 1966',
  },
  {
    id: 'fb005',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Wembley 1966',
    difficulty: 'expert',
    question: 'The linesman who awarded England’s disputed third goal in the 1966 final represented which country?',
    options: ['Switzerland', 'Czechoslovakia', 'Hungary', 'Soviet Union'],
    correctIndex: 3,
    explanation: 'Tofiq Bahramov of Soviet Azerbaijan gave the goal; Swiss referee Gottfried Dienst took his word.',
    sourceUrl: 'https://www.rsssf.org/tables/66full.html',
    sourceLabel: 'RSSSF: World Cup 1966 full details',
  },
  {
    id: 'fb006',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Wembley 1966',
    difficulty: 'extreme',
    question: 'Who finished as top scorer of the 1966 World Cup with nine goals?',
    options: ['Helmut Haller', 'Geoff Hurst', 'Eusébio', 'Franz Beckenbauer'],
    correctIndex: 2,
    explanation: 'Eusébio’s nine for Portugal outscored Haller’s six; Hurst and Beckenbauer managed four each.',
    sourceUrl: 'https://www.rsssf.org/tables/66full.html',
    sourceLabel: 'RSSSF: World Cup 1966 full details',
  },
  {
    id: 'fb007',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Maradona 1986',
    difficulty: 'simple',
    question: 'Against which team did Diego Maradona score both the “Hand of God” goal and the “Goal of the Century” at Mexico 86?',
    options: ['England', 'West Germany', 'Italy', 'Brazil'],
    correctIndex: 0,
    explanation: 'Both came within minutes of each other in the Azteca quarter-final; Lineker’s late reply made it 2-1.',
    sourceUrl: 'https://www.rsssf.org/tables/86full.html',
    sourceLabel: 'RSSSF: World Cup 1986 full details',
  },
  {
    id: 'fb008',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Maradona 1986',
    difficulty: 'expert',
    question: 'Who scored Argentina’s 3-2 winner against West Germany in the 1986 World Cup final?',
    options: ['Jorge Valdano', 'José Luis Brown', 'Jorge Burruchaga', 'Diego Maradona'],
    correctIndex: 2,
    explanation: 'Burruchaga struck in the 88th minute after Rummenigge and Völler had wiped out a 2-0 lead.',
    sourceUrl: 'https://www.rsssf.org/tables/86full.html',
    sourceLabel: 'RSSSF: World Cup 1986 full details',
  },
  {
    id: 'fb009',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Maradona 1986',
    difficulty: 'extreme',
    question: 'Which Tunisian referee allowed Maradona’s “Hand of God” goal to stand?',
    options: ['Ali Bin Nasser', 'Bogdan Dochev', 'Romualdo Arppi Filho', 'Erik Fredriksson'],
    correctIndex: 0,
    explanation: 'Bin Nasser looked to Bulgarian linesman Dochev, who did not flag; Arppi Filho refereed the final.',
    sourceUrl: 'https://www.rsssf.org/tables/86full.html',
    sourceLabel: 'RSSSF: World Cup 1986 full details',
  },
  {
    id: 'fb010',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Zidane 2006',
    difficulty: 'simple',
    question: 'Which Italian defender did Zinedine Zidane headbutt in the 2006 World Cup final?',
    options: ['Marco Materazzi', 'Fabio Cannavaro', 'Gennaro Gattuso', 'Andrea Pirlo'],
    correctIndex: 0,
    explanation: 'Materazzi had also headed Italy’s equaliser after Zidane’s early penalty; Italy won the shootout 5-3.',
    sourceUrl: 'https://www.npr.org/2006/07/09/5544686/italy-outlasts-france-to-win-4th-world-cup-title',
    sourceLabel: 'NPR: Italy outlasts France to win 4th World Cup title',
  },
  {
    id: 'fb011',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Zidane 2006',
    difficulty: 'expert',
    question: 'Whose penalty hit the crossbar for France in the 2006 World Cup final shootout?',
    options: ['Thierry Henry', 'Sylvain Wiltord', 'Eric Abidal', 'David Trezeguet'],
    correctIndex: 3,
    explanation: 'Trezeguet’s miss on France’s second kick was the only failure; Fabio Grosso converted the winner.',
    sourceUrl: 'https://www.rsssf.org/tables/2006full.html',
    sourceLabel: 'RSSSF: World Cup 2006 full details',
  },
  {
    id: 'fb012',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Zidane 2006',
    difficulty: 'extreme',
    question: 'Which Argentine referee sent off Zidane in the 2006 World Cup final in Berlin?',
    options: ['Horacio Elizondo', 'Néstor Pitana', 'Héctor Baldassi', 'Benito Archundia'],
    correctIndex: 0,
    explanation: 'Elizondo also refereed the opening match; Pitana would take the 2018 final, Archundia a 2006 semi.',
    sourceUrl: 'https://www.rsssf.org/tables/2006full.html',
    sourceLabel: 'RSSSF: World Cup 2006 full details',
  },
  {
    id: 'fb013',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Mineirazo 2014',
    difficulty: 'simple',
    question: 'Which team beat hosts Brazil 7-1 in the 2014 World Cup semi-final?',
    options: ['Netherlands', 'Argentina', 'Spain', 'Germany'],
    correctIndex: 3,
    explanation: 'Germany led 5-0 inside 29 minutes at the Mineirão; Oscar’s late goal was Brazil’s only reply.',
    sourceUrl: 'https://www.guinnessworldrecords.com/news/2018/6/world-cup-rewind-miroslav-klose-beats-ronaldos-all-time-goals-record-as-germany-524073',
    sourceLabel: 'Guinness World Records: Klose beats Ronaldo’s record as Germany thump Brazil',
  },
  {
    id: 'fb014',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Mineirazo 2014',
    difficulty: 'simple',
    question: 'Who scored the extra-time winner for Germany against Argentina in the 2014 World Cup final?',
    options: ['Thomas Müller', 'Mario Götze', 'Miroslav Klose', 'André Schürrle'],
    correctIndex: 1,
    explanation: 'Götze volleyed in Schürrle’s cross in the 113th minute at the Maracanã.',
    sourceUrl: 'https://www.rsssf.org/tables/2014full.html',
    sourceLabel: 'RSSSF: World Cup 2014 full details',
  },
  {
    id: 'fb015',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Mineirazo 2014',
    difficulty: 'expert',
    question: 'Whose all-time World Cup scoring record did Miroslav Klose break with Germany’s second goal against Brazil in 2014?',
    options: ['Gerd Müller', 'Pelé', 'Just Fontaine', 'Ronaldo'],
    correctIndex: 3,
    explanation: 'Klose’s 16th finals goal passed Ronaldo’s 15, in front of Brazil’s own fans.',
    sourceUrl: 'https://www.guinnessworldrecords.com/news/2018/6/world-cup-rewind-miroslav-klose-beats-ronaldos-all-time-goals-record-as-germany-524073',
    sourceLabel: 'Guinness World Records: Klose beats Ronaldo’s record as Germany thump Brazil',
  },
  {
    id: 'fb016',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Mineirazo 2014',
    difficulty: 'extreme',
    question: 'Toni Kroos’s two goals in the 7-1 came how many seconds apart, the fastest double in World Cup history?',
    options: ['42', '69', '95', '120'],
    correctIndex: 1,
    explanation: 'Officially timed at 69 seconds apart, they took Germany from 2-0 to 4-0 before the half hour.',
    sourceUrl: 'https://www.guinnessworldrecords.com/news/2018/6/world-cup-rewind-miroslav-klose-beats-ronaldos-all-time-goals-record-as-germany-524073',
    sourceLabel: 'Guinness World Records: Klose beats Ronaldo’s record as Germany thump Brazil',
  },
  {
    id: 'fb017',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Qatar 2022 final',
    difficulty: 'simple',
    question: 'Who scored a hat-trick for France in the 2022 World Cup final against Argentina?',
    options: ['Antoine Griezmann', 'Olivier Giroud', 'Karim Benzema', 'Kylian Mbappé'],
    correctIndex: 3,
    explanation: 'It was the first World Cup final hat-trick since Geoff Hurst in 1966, and still ended on the losing side.',
    sourceUrl: 'https://www.skysports.com/football/news/12098/12768573/argentina-3-3-france-4-2-on-pens-lionel-messi-leads-argentina-to-world-cup-glory-despite-kylian-mbappe-hat-trick',
    sourceLabel: 'Sky Sports: Argentina 3-3 France (4-2 on pens) match report',
  },
  {
    id: 'fb018',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Qatar 2022 final',
    difficulty: 'expert',
    question: 'Which two France players failed to score in the 2022 World Cup final shootout?',
    options: ['Giroud and Griezmann', 'Kolo Muani and Fofana', 'Rabiot and Camavinga', 'Coman and Tchouaméni'],
    correctIndex: 3,
    explanation: 'Emiliano Martínez saved from Coman and Tchouaméni shot wide; Gonzalo Montiel converted the 4-2 winner.',
    sourceUrl: 'https://www.rsssf.org/tables/2022f.html',
    sourceLabel: 'RSSSF: World Cup 2022 final tournament',
  },
  {
    id: 'fb019',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Qatar 2022 final',
    difficulty: 'extreme',
    question: 'Who refereed the 2022 World Cup final at Lusail?',
    options: ['Szymon Marciniak', 'Daniele Orsato', 'Anthony Taylor', 'Clément Turpin'],
    correctIndex: 0,
    explanation: 'Poland’s Marciniak took charge in front of 88,966; Messi’s 108th-minute goal was confirmed by goal-line technology.',
    sourceUrl: 'https://www.rsssf.org/tables/2022f.html',
    sourceLabel: 'RSSSF: World Cup 2022 final tournament',
  },
  {
    id: 'fb020',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Champions League nights',
    difficulty: 'simple',
    question: 'Which two substitutes scored Manchester United’s stoppage-time goals in the 1999 Champions League final?',
    options: ['Sheringham and Solskjær', 'Yorke and Cole', 'Giggs and Scholes', 'Beckham and Butt'],
    correctIndex: 0,
    explanation: 'Sheringham came on in the 67th minute and Solskjær in the 81st; both scored after the 90th at the Camp Nou.',
    sourceUrl: 'https://www.rsssf.org/ec/ec199899.html',
    sourceLabel: 'RSSSF: European Champions Cup 1998/99',
  },
  {
    id: 'fb021',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Champions League nights',
    difficulty: 'expert',
    question: 'Who put Bayern Munich ahead in the sixth minute of the 1999 Champions League final?',
    options: ['Carsten Jancker', 'Stefan Effenberg', 'Mario Basler', 'Mehmet Scholl'],
    correctIndex: 2,
    explanation: 'Basler’s free-kick looked to have won it until United’s two goals in added time.',
    sourceUrl: 'https://www.rsssf.org/ec/ec199899.html',
    sourceLabel: 'RSSSF: European Champions Cup 1998/99',
  },
  {
    id: 'fb022',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Champions League nights',
    difficulty: 'extreme',
    question: 'Which Italian refereed the 1999 Champions League final at the Camp Nou?',
    options: ['Pierluigi Collina', 'Roberto Rosetti', 'Stefano Farina', 'Nicola Rizzoli'],
    correctIndex: 0,
    explanation: 'Collina later said the noise of the United comeback was like a lion’s roar; Rizzoli got the 2014 World Cup final.',
    sourceUrl: 'https://www.rsssf.org/ec/ec199899.html',
    sourceLabel: 'RSSSF: European Champions Cup 1998/99',
  },
  {
    id: 'fb023',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Champions League nights',
    difficulty: 'simple',
    question: 'Who scored the winning penalty for Chelsea in the 2012 Champions League final shootout against Bayern?',
    options: ['Frank Lampard', 'Didier Drogba', 'Ashley Cole', 'Juan Mata'],
    correctIndex: 1,
    explanation: 'Drogba had also headed the late equaliser in Bayern’s own Allianz Arena after Müller’s opener.',
    sourceUrl: 'https://www.rsssf.org/ec/ec201112.html',
    sourceLabel: 'RSSSF: Champions League 2011/12',
  },
  {
    id: 'fb024',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Champions League nights',
    difficulty: 'extreme',
    question: 'Which two Bayern players missed in the 2012 Champions League final shootout?',
    options: ['Robben and Ribéry', 'Lahm and Gómez', 'Neuer and Kroos', 'Olić and Schweinsteiger'],
    correctIndex: 3,
    explanation: 'Mata missed Chelsea’s first, then Olić and Schweinsteiger failed and Drogba settled it 4-3.',
    sourceUrl: 'https://www.rsssf.org/ec/ec201112.html',
    sourceLabel: 'RSSSF: Champions League 2011/12',
  },
  {
    id: 'fb025',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Champions League nights',
    difficulty: 'simple',
    question: 'Which club overturned a 4-0 first-leg deficit by beating PSG 6-1 in March 2017?',
    options: ['Real Madrid', 'Barcelona', 'Bayern Munich', 'Manchester City'],
    correctIndex: 1,
    explanation: 'Sergi Roberto scored in the fifth minute of stoppage time; no team had overturned 4-0 in the Champions League era.',
    sourceUrl: 'https://www.foxnews.com/sports/barca-mounts-6-1-comeback-to-oust-psg-roberto-nets-winner',
    sourceLabel: 'Fox News (AP): Barca mounts 6-1 comeback to oust PSG',
  },
  {
    id: 'fb026',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Club dynasties',
    difficulty: 'simple',
    question: 'Who managed Leicester City to the 2015/16 Premier League title?',
    options: ['Nigel Pearson', 'Brendan Rodgers', 'Claudio Ranieri', 'Craig Shakespeare'],
    correctIndex: 2,
    explanation: 'Ranieri’s counter-attacking Foxes had been priced at 5000/1 before the season.',
    sourceUrl: 'https://www.lcfc.com/media-article/claudio-ranieri-lcfc-leicester-city-champions-premier-league-5000-anniversary-match',
    sourceLabel: 'LCFC: “I Was So Proud” – Ranieri’s title memories',
  },
  {
    id: 'fb027',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Club dynasties',
    difficulty: 'expert',
    question: 'Leicester’s 2016 title was confirmed without them playing when Tottenham drew 2-2 away to which club?',
    options: ['Chelsea', 'Arsenal', 'Liverpool', 'West Ham United'],
    correctIndex: 0,
    explanation: 'Spurs dropping two points at Stamford Bridge the night after Leicester drew at Manchester United sealed it.',
    sourceUrl: 'https://www.lcfc.com/media-article/claudio-ranieri-lcfc-leicester-city-champions-premier-league-5000-anniversary-match',
    sourceLabel: 'LCFC: “I Was So Proud” – Ranieri’s title memories',
  },
  {
    id: 'fb028',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Club dynasties',
    difficulty: 'extreme',
    question: 'Which tenor sang at the King Power Stadium before Leicester lifted the 2016 trophy against Everton?',
    options: ['Plácido Domingo', 'José Carreras', 'Alessandro Safina', 'Andrea Bocelli'],
    correctIndex: 3,
    explanation: 'Bocelli, a friend of Ranieri, had asked months earlier to come and mark what the club was doing.',
    sourceUrl: 'https://www.lcfc.com/media-article/claudio-ranieri-lcfc-leicester-city-champions-premier-league-5000-anniversary-match',
    sourceLabel: 'LCFC: “I Was So Proud” – Ranieri’s title memories',
  },
  {
    id: 'fb029',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Club dynasties',
    difficulty: 'simple',
    question: 'Which club went through the entire 2003/04 Premier League season unbeaten?',
    options: ['Manchester United', 'Chelsea', 'Liverpool', 'Arsenal'],
    correctIndex: 3,
    explanation: 'The Invincibles won 26 and drew 12, the first unbeaten English top-flight season since Preston in 1889.',
    sourceUrl: 'https://www.premierleague.com/en/news/59016',
    sourceLabel: 'Premier League: 2003/04 season review – Invincible Arsenal',
  },
  {
    id: 'fb030',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Club dynasties',
    difficulty: 'expert',
    question: 'How many goals did Ferenc Puskás score in Real Madrid’s 7-3 win over Eintracht Frankfurt in the 1960 European Cup final?',
    options: ['2', '3', '4', '5'],
    correctIndex: 2,
    explanation: 'Puskás hit four and Di Stéfano three at Hampden Park as Madrid won a fifth straight European Cup.',
    sourceUrl: 'https://www.rsssf.org/ec/ec195960.html',
    sourceLabel: 'RSSSF: European Champions Cup 1959/60',
  },
  {
    id: 'fb031',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Club dynasties',
    difficulty: 'extreme',
    question: 'Real Madrid won the very first European Cup final in 1956, 4-3 in Paris, against which club?',
    options: ['Stade de Reims', 'AC Milan', 'Partizan Belgrade', 'Hibernian'],
    correctIndex: 0,
    explanation: 'Reims led 2-0 and 3-2 before Marquitos and Héctor Rial completed the comeback at the Parc des Princes.',
    sourceUrl: 'https://www.rsssf.org/ec/ec195556.html',
    sourceLabel: 'RSSSF: European Champions Cup 1955/56',
  },
  {
    id: 'fb032',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Ballon d’Or debates',
    difficulty: 'simple',
    question: 'Why was no Ballon d’Or awarded in 2020?',
    options: ['A voting scandal', 'The Covid-19 pandemic', 'A sponsor dispute', 'A tie between Messi and Ronaldo'],
    correctIndex: 1,
    explanation: 'France Football cancelled the award for the first time in its history; Robert Lewandowski had been the favourite.',
    sourceUrl: 'https://www.goal.com/en-us/news/why-is-the-ballon-dor-cancelled-for-2020-and-who-could-have-won-it/18ltdw02hyjp119bo7qwoxpu4',
    sourceLabel: 'Goal: Why is the Ballon d’Or cancelled for 2020?',
  },
  {
    id: 'fb033',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Ballon d’Or debates',
    difficulty: 'expert',
    question: 'Lionel Messi’s contested 2010 Ballon d’Or win beat which two World Cup-winning Barcelona teammates into second and third?',
    options: ['Puyol and Piqué', 'Villa and Xavi', 'Iniesta and Busquets', 'Iniesta and Xavi'],
    correctIndex: 3,
    explanation: 'Messi, who failed to score at the World Cup, won on the votes of national coaches and captains.',
    sourceUrl: 'https://www.foxsports.com/stories/soccer/messi-claims-2010-ballon-dor-award',
    sourceLabel: 'Fox Sports (AP): Messi claims 2010 Ballon d’Or award',
  },
  {
    id: 'fb034',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Ballon d’Or debates',
    difficulty: 'extreme',
    question: 'Which player topped the media vote for the 2010 Ballon d’Or yet finished outside the top three overall?',
    options: ['Diego Forlán', 'Cristiano Ronaldo', 'David Villa', 'Wesley Sneijder'],
    correctIndex: 3,
    explanation: 'Journalists ranked Sneijder first and Messi only fourth after his treble with Inter and a World Cup final.',
    sourceUrl: 'https://www.foxsports.com/stories/soccer/messi-claims-2010-ballon-dor-award',
    sourceLabel: 'Fox Sports (AP): Messi claims 2010 Ballon d’Or award',
  },
  {
    id: 'fb035',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Ballon d’Or debates',
    difficulty: 'expert',
    question: 'Which Bayern Munich treble-winner finished third behind Ronaldo and Messi in the 2013 Ballon d’Or vote?',
    options: ['Arjen Robben', 'Franck Ribéry', 'Philipp Lahm', 'Manuel Neuer'],
    correctIndex: 1,
    explanation: 'Ronaldo won his second award despite lifting no trophy that year, and Ribéry said he felt robbed.',
    sourceUrl: 'https://www.mlssoccer.com/news/cristiano-ronaldo-edges-out-lionel-messi-franck-ribery-2013-fifa-ballon-dor-awar',
    sourceLabel: 'MLSsoccer.com: Ronaldo edges out Messi, Ribéry for 2013 Ballon d’Or',
  },
  {
    id: 'fb036',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Ballon d’Or debates',
    difficulty: 'expert',
    question: 'Who in 1995 became the first player from outside Europe to win the Ballon d’Or?',
    options: ['Ronaldo', 'Rivaldo', 'Romário', 'George Weah'],
    correctIndex: 3,
    explanation: '1995 was the first year non-European-born players were eligible; Weah remains Africa’s only winner.',
    sourceUrl: 'https://www.fourfourtwo.com/features/george-weahs-ballon-dor-how-one-man-changed-the-course-of-the-award',
    sourceLabel: 'FourFourTwo: George Weah’s Ballon d’Or',
  },
  {
    id: 'fb037',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Ballon d’Or debates',
    difficulty: 'extreme',
    question: 'Who finished second to Fabio Cannavaro in the 2006 Ballon d’Or?',
    options: ['Thierry Henry', 'Gianluigi Buffon', 'Ronaldinho', 'Zinedine Zidane'],
    correctIndex: 1,
    explanation: 'Buffon was runner-up and Henry third; Cannavaro became only the third defender to win after Beckenbauer and Sammer.',
    sourceUrl: 'https://www.skysports.com/football/news/2396715/cannavaro-claims-ballon-dor',
    sourceLabel: 'Sky Sports: Cannavaro claims Ballon d’Or',
  },
  {
    id: 'fb038',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Calciopoli',
    difficulty: 'simple',
    question: 'Which club was relegated to Serie B in 2006 for its part in the Calciopoli scandal?',
    options: ['Juventus', 'AC Milan', 'Lazio', 'Fiorentina'],
    correctIndex: 0,
    explanation: 'It was the first relegation in Juventus’s history, and their 2005 and 2006 titles were stripped.',
    sourceUrl: 'https://www.foxnews.com/sports/10-years-ago-today-juventus-were-relegated-from-serie-a',
    sourceLabel: 'Fox Sports: 10 years ago today, Juventus were relegated from Serie A',
  },
  {
    id: 'fb039',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Calciopoli',
    difficulty: 'expert',
    question: 'Which Juventus managing director was found guilty of an exclusive relationship with Serie A’s referee designators?',
    options: ['Antonio Giraudo', 'Luciano Moggi', 'Roberto Bettega', 'Andrea Agnelli'],
    correctIndex: 1,
    explanation: 'Wiretaps showed Moggi steering which referees were appointed; the affair was nicknamed “Moggiopoli”.',
    sourceUrl: 'https://www.foxnews.com/sports/10-years-ago-today-juventus-were-relegated-from-serie-a',
    sourceLabel: 'Fox Sports: 10 years ago today, Juventus were relegated from Serie A',
  },
  {
    id: 'fb040',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Calciopoli',
    difficulty: 'expert',
    question: 'Which club was awarded the 2005/06 Serie A title after Juventus were stripped of it?',
    options: ['Inter', 'AC Milan', 'Roma', 'Fiorentina'],
    correctIndex: 0,
    explanation: 'Inter had finished third; Milan, second, were also punished, so the scudetto went to the unindicted Nerazzurri.',
    sourceUrl: 'https://www.si.com/soccer/2018/12/13/italian-supreme-court-rejects-juventus-appeal-have-inter-stripped-200506-scudetto',
    sourceLabel: 'Sports Illustrated: Supreme Court rejects Juventus appeal over Inter’s 2005/06 scudetto',
  },
  {
    id: 'fb041',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Calciopoli',
    difficulty: 'extreme',
    question: 'After appeals, Juventus began their 2006/07 Serie B season with a deduction of how many points?',
    options: ['30', '17', '9', '3'],
    correctIndex: 2,
    explanation: 'The penalty started at 30 and was cut on appeal to nine; Del Piero, Buffon, Nedvěd and Trezeguet stayed.',
    sourceUrl: 'https://www.foxnews.com/sports/10-years-ago-today-juventus-were-relegated-from-serie-a',
    sourceLabel: 'Fox Sports: 10 years ago today, Juventus were relegated from Serie A',
  },
  {
    id: 'fb042',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Bosman ruling',
    difficulty: 'simple',
    question: 'Jean-Marc Bosman, whose 1995 court case freed out-of-contract players, was a footballer of which nationality?',
    options: ['Dutch', 'French', 'Belgian', 'Luxembourgish'],
    correctIndex: 2,
    explanation: 'The judgment describes him as “a professional footballer of Belgian nationality” employed by RC Liège.',
    sourceUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:61993CJ0415',
    sourceLabel: 'EUR-Lex: Judgment of the Court, Case C-415/93 (Bosman)',
  },
  {
    id: 'fb043',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Bosman ruling',
    difficulty: 'expert',
    question: 'In which year did the European Court of Justice deliver the Bosman ruling?',
    options: ['1990', '1993', '1995', '1998'],
    correctIndex: 2,
    explanation: 'Judgment came on 15 December 1995, five years after Bosman’s contract had expired.',
    sourceUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:61993CJ0415',
    sourceLabel: 'EUR-Lex: Judgment of the Court, Case C-415/93 (Bosman)',
  },
  {
    id: 'fb044',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Bosman ruling',
    difficulty: 'extreme',
    question: 'Bosman’s case began when RC Liège blocked his move to which French club?',
    options: ['Lille', 'Lens', 'Valenciennes', 'US Dunkerque'],
    correctIndex: 3,
    explanation: 'Liège refused to release him to second-division Dunkerque without a fee once his contract had run out.',
    sourceUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:61993CJ0415',
    sourceLabel: 'EUR-Lex: Judgment of the Court, Case C-415/93 (Bosman)',
  },
  {
    id: 'fb045',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Bosman ruling',
    difficulty: 'extreme',
    question: 'Besides transfer fees, the Bosman ruling struck down UEFA’s “3+2” rule, which limited what?',
    options: ['Foreign players a club could field', 'Substitutions per match', 'Loan signings per season', 'Foreign coaches per club'],
    correctIndex: 0,
    explanation: 'Clubs could field three foreigners plus two “assimilated” players; the Court held it breached free movement of EU workers.',
    sourceUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:61993CJ0415',
    sourceLabel: 'EUR-Lex: Judgment of the Court, Case C-415/93 (Bosman)',
  },
  {
    id: 'fb046',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Heysel and Hillsborough',
    difficulty: 'simple',
    question: 'The 1985 Heysel Stadium disaster occurred before the European Cup final between Liverpool and which club?',
    options: ['Juventus', 'AC Milan', 'Roma', 'Inter'],
    correctIndex: 0,
    explanation: 'Thirty-nine people died before kick-off in Brussels; the match was played and Juventus won 1-0 with a Platini penalty.',
    sourceUrl: 'https://www.goal.com/en-gb/news/what-happened-at-heysel-juventus-vs-liverpool-european-club-ban-explained/71szgl9t3chj1ffeixroegci8',
    sourceLabel: 'Goal: What happened at Heysel? The European club ban explained',
  },
  {
    id: 'fb047',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Heysel and Hillsborough',
    difficulty: 'extreme',
    question: 'UEFA banned English clubs from Europe after Heysel on 2 June 1985; in which year were they readmitted?',
    options: ['1988', '1990', '1991', '1992'],
    correctIndex: 1,
    explanation: 'The ban was indefinite rather than fixed; English clubs returned in 1990 and Liverpool served one extra year.',
    sourceUrl: 'https://www.goal.com/en-gb/news/what-happened-at-heysel-juventus-vs-liverpool-european-club-ban-explained/71szgl9t3chj1ffeixroegci8',
    sourceLabel: 'Goal: What happened at Heysel? The European club ban explained',
  },
  {
    id: 'fb048',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Heysel and Hillsborough',
    difficulty: 'simple',
    question: 'The 1989 Hillsborough disaster happened at an FA Cup semi-final involving which club’s supporters?',
    options: ['Everton', 'Liverpool', 'Manchester United', 'Leeds United'],
    correctIndex: 1,
    explanation: 'Ninety-seven Liverpool supporters died; the 1989 Taylor interim report blamed a failure of police control.',
    sourceUrl: 'https://www.lfchistory.co.uk/hillsborough-disaster.html',
    sourceLabel: 'LFChistory.co.uk: Hillsborough disaster',
  },
  {
    id: 'fb049',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Heysel and Hillsborough',
    difficulty: 'expert',
    question: 'Who were Liverpool’s opponents in the FA Cup semi-final at Hillsborough on 15 April 1989?',
    options: ['Everton', 'Nottingham Forest', 'Arsenal', 'Norwich City'],
    correctIndex: 1,
    explanation: 'The Leppings Lane end crush happened at the neutral Sheffield Wednesday ground; Everton won the other semi-final.',
    sourceUrl: 'https://www.lfchistory.co.uk/hillsborough-disaster.html',
    sourceLabel: 'LFChistory.co.uk: Hillsborough disaster',
  },
  {
    id: 'fb050',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Heysel and Hillsborough',
    difficulty: 'extreme',
    question: 'In which year did fresh inquests conclude that the Hillsborough victims were unlawfully killed?',
    options: ['2012', '2014', '2016', '2019'],
    correctIndex: 2,
    explanation: 'The 2012 Independent Panel report led the High Court to quash the accidental-death verdicts; new inquests reported on 26 April 2016.',
    sourceUrl: 'https://www.lfchistory.co.uk/hillsborough-disaster.html',
    sourceLabel: 'LFChistory.co.uk: Hillsborough disaster',
  },
  {
    id: 'fb051',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Transfer records',
    difficulty: 'simple',
    question: 'Which club paid a world-record €222m for Neymar in 2017?',
    options: ['Manchester City', 'Real Madrid', 'Paris Saint-Germain', 'Juventus'],
    correctIndex: 2,
    explanation: 'PSG triggered his Barcelona release clause, then signed Mbappé from Monaco in the same window for the second-biggest fee.',
    sourceUrl: 'https://www.goal.com/en/news/100-most-expensive-football-transfers-all-time/ikr3oojohla51fh9adq3qkwpu',
    sourceLabel: 'Goal: The 100 most expensive football transfers of all time',
  },
  {
    id: 'fb052',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Transfer records',
    difficulty: 'expert',
    question: 'Whose 2001 move to Real Madrid set a world transfer record that stood for eight years?',
    options: ['Luís Figo', 'Zinedine Zidane', 'Ronaldo', 'David Beckham'],
    correctIndex: 1,
    explanation: 'Zidane cost £47m from Juventus; the record fell only when Cristiano Ronaldo joined Madrid in 2009.',
    sourceUrl: 'https://www.90min.com/what-is-most-expensive-football-transfer-ever',
    sourceLabel: '90min: What is the most expensive football transfer ever?',
  },
  {
    id: 'fb053',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Transfer records',
    difficulty: 'extreme',
    question: 'Cristiano Ronaldo’s 2009 move from Manchester United to Real Madrid cost roughly how much in euros?',
    options: ['€60m', '€75m', '€94m', '€120m'],
    correctIndex: 2,
    explanation: 'The €94m (about £80m) fee was the world record until Gareth Bale’s €100.8m move to Madrid in 2013.',
    sourceUrl: 'https://www.goal.com/en/news/100-most-expensive-football-transfers-all-time/ikr3oojohla51fh9adq3qkwpu',
    sourceLabel: 'Goal: The 100 most expensive football transfers of all time',
  },
  {
    id: 'fb054',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Messi–Ronaldo era',
    difficulty: 'simple',
    question: 'Lionel Messi set the record for most goals in a calendar year with 91 in which year?',
    options: ['2009', '2012', '2015', '2019'],
    correctIndex: 1,
    explanation: 'Messi passed Gerd Müller’s 85 from 1972; 79 of the goals were for Barcelona and 12 for Argentina.',
    sourceUrl: 'https://www.guinnessworldrecords.com/world-records/106274-most-football-goals-scored-in-a-calendar-year',
    sourceLabel: 'Guinness World Records: Most football goals scored in a calendar year',
  },
  {
    id: 'fb055',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'South Africa 2010',
    difficulty: 'simple',
    question: 'Who scored the only goal of the 2010 World Cup final for Spain against the Netherlands?',
    options: ['David Villa', 'Xavi', 'Fernando Torres', 'Andrés Iniesta'],
    correctIndex: 3,
    explanation: 'Iniesta struck in the 116th minute at Soccer City, after Heitinga had been sent off for a second yellow.',
    sourceUrl: 'https://www.rsssf.org/tables/2010full.html',
    sourceLabel: 'RSSSF: World Cup 2010 full details',
  },
  {
    id: 'fb056',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'South Africa 2010',
    difficulty: 'extreme',
    question: 'Which Uruguayan referee failed to award Frank Lampard’s “ghost goal” against Germany in 2010?',
    options: ['Héctor Baldassi', 'Carlos Amarilla', 'Óscar Ruiz', 'Jorge Larrionda'],
    correctIndex: 3,
    explanation: 'England lost 4-1 in Bloemfontein, and the outcry pushed FIFA to adopt goal-line technology for 2014.',
    sourceUrl: 'https://www.goal.com/en-us/news/lampard-my-disallowed-england-goal-changed-football/bltf9228ad5cafb1733',
    sourceLabel: 'Goal: Lampard – my disallowed England goal changed football',
  },
  {
    id: 'fb057',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Refereeing controversies',
    difficulty: 'expert',
    question: 'Who scored the goal set up by Thierry Henry’s handball that put France into the 2010 World Cup at Ireland’s expense?',
    options: ['Nicolas Anelka', 'William Gallas', 'Karim Benzema', 'André-Pierre Gignac'],
    correctIndex: 1,
    explanation: 'Henry handled twice in the 103rd minute of the Paris play-off; Swedish referee Martin Hansson let the goal stand.',
    sourceUrl: 'https://www.goal.com/en/news/thierry-henry-handball-france-vs-ireland-world-cup-2010-play-off-controversy-explained/bltbd0d04e8348f4b96',
    sourceLabel: 'Goal: Thierry Henry handball – the 2010 play-off controversy explained',
  },
  {
    id: 'fb058',
    domain: 'sports',
    region: 'Europe',
    topic: 'Football',
    subtopic: 'Refereeing controversies',
    difficulty: 'extreme',
    question: 'After the Henry handball, the FAI asked FIFA to admit Ireland to the 2010 World Cup as which numbered team?',
    options: ['17th', '25th', '33rd', '49th'],
    correctIndex: 2,
    explanation: 'FIFA refused a replay, and Sepp Blatter later revealed the request for a 33rd place, embarrassing the FAI.',
    sourceUrl: 'https://www.goal.com/en/news/thierry-henry-handball-france-vs-ireland-world-cup-2010-play-off-controversy-explained/bltbd0d04e8348f4b96',
    sourceLabel: 'Goal: Thierry Henry handball – the 2010 play-off controversy explained',
  },
  {
    id: 'fb059',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'Refereeing controversies',
    difficulty: 'expert',
    question: 'Whose golden goal for South Korea knocked Italy out of the 2002 World Cup?',
    options: ['Park Ji-sung', 'Ahn Jung-hwan', 'Seol Ki-hyeon', 'Hwang Sun-hong'],
    correctIndex: 1,
    explanation: 'Ahn scored in the 117th minute in Daejeon after Ecuadorian referee Byron Moreno had sent off Francesco Totti.',
    sourceUrl: 'https://www.rsssf.org/tables/2002full.html',
    sourceLabel: 'RSSSF: World Cup 2002 full details',
  },
  {
    id: 'fb060',
    domain: 'sports',
    region: 'Global',
    topic: 'Football',
    subtopic: 'National rivalries',
    difficulty: 'expert',
    question: 'Which two England players failed in the 1990 World Cup semi-final shootout against West Germany?',
    options: ['Lineker and Platt', 'Beardsley and Gascoigne', 'Pearce and Platt', 'Pearce and Waddle'],
    correctIndex: 3,
    explanation: 'Illgner saved from Pearce and Waddle blazed over after a 1-1 draw in Turin; Germany won 4-3 on penalties.',
    sourceUrl: 'https://www.rsssf.org/tables/90full.html',
    sourceLabel: 'RSSSF: World Cup 1990 full details',
  },
]);
