// Server-only editorial bank: Formula 1, tranche 1 (60 questions).
// Never import this module from client components.
// Every fact below was checked against the page at sourceUrl when written. Formula1.com result and
// standings pages are the primary record; Hall of Fame pages and major-outlet retrospectives carry
// the narrative facts. Regions: the world championship is 'Global'; Monaco is 'Europe'; the 2005 US GP is 'US'.
export const FORMULA_1 = Object.freeze([
  // ------------------------------------------------------- Senna v Prost (Suzuka 1989 / 1990)
  {
    id: 'f1001',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Senna v Prost',
    difficulty: 'simple',
    question:
      "Which McLaren driver clinched the 1989 title when he and team-mate Senna collided at Suzuka's chicane?",
    options: ['Alain Prost', 'Gerhard Berger', 'Nigel Mansell', 'Nelson Piquet'],
    correctIndex: 0,
    explanation: 'Prost shut the door on Senna in the chicane; it was his third of four world titles.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Alain_Prost.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Alain Prost',
  },
  {
    id: 'f1002',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Senna v Prost',
    difficulty: 'simple',
    question: 'At which Japanese circuit did Senna and Prost collide in both the 1989 and 1990 title deciders?',
    options: ['Fuji', 'Motegi', 'Aida', 'Suzuka'],
    correctIndex: 3,
    explanation: 'Prost took Senna out at the chicane in 1989; Senna returned the favour at the first corner in 1990.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Ayrton_Senna.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Ayrton Senna',
  },
  {
    id: 'f1003',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Senna v Prost',
    difficulty: 'expert',
    question: "Who was handed victory in the 1989 Japanese Grand Prix after Senna's disqualification?",
    options: ['Riccardo Patrese', 'Thierry Boutsen', 'Alessandro Nannini', 'Gerhard Berger'],
    correctIndex: 2,
    explanation: "It was the only Grand Prix win of Nannini's career, with Benetton.",
    sourceUrl: 'https://www.formula1.com/en/results/1989/races/557/japan/race-result',
    sourceLabel: 'Formula1.com: 1989 Japanese Grand Prix race result',
  },
  {
    id: 'f1004',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Senna v Prost',
    difficulty: 'expert',
    question: "Alongside a $100,000 fine, what further penalty did Senna receive after Suzuka 1989?",
    options: ['A one-race ban', 'Loss of his 1989 points', 'A grid penalty for 1990', 'A suspended six-month ban'],
    correctIndex: 3,
    explanation: 'He was disqualified for cutting the chicane when rejoining, then punished again on appeal.',
    sourceUrl:
      'https://www.formula1.com/en/latest/article/prost-vs-senna-the-top-10-moments-of-f1s-defining-rivalry.HXTkvgrOpnaYJoanGiwGq',
    sourceLabel: "Formula1.com: Prost vs Senna, the top 10 moments of F1's defining rivalry",
  },
  {
    id: 'f1005',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Senna v Prost',
    difficulty: 'extreme',
    question: 'After stalling on the grid at Suzuka in 1988, Senna rejoined in which position before winning?',
    options: ['8th', '22nd', '11th', '14th'],
    correctIndex: 3,
    explanation: 'He was second within 25 laps and passed Prost on lap 28 to clinch his first title.',
    sourceUrl:
      'https://www.formula1.com/en/latest/article/prost-vs-senna-the-top-10-moments-of-f1s-defining-rivalry.HXTkvgrOpnaYJoanGiwGq',
    sourceLabel: "Formula1.com: Prost vs Senna, the top 10 moments of F1's defining rivalry",
  },
  {
    id: 'f1006',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Senna v Prost',
    difficulty: 'extreme',
    question: 'Who won the 1990 Japanese Grand Prix after Senna and Prost crashed out at the first corner?',
    options: ['Nigel Mansell', 'Nelson Piquet', 'Roberto Moreno', 'Gerhard Berger'],
    correctIndex: 1,
    explanation: 'Piquet led a Benetton one-two from Moreno, with Aguri Suzuki third for Lola.',
    sourceUrl: 'https://www.formula1.com/en/results/1990/races/78/japan/race-result',
    sourceLabel: 'Formula1.com: 1990 Japanese Grand Prix race result',
  },
  // ------------------------------------------------------------------------- Imola 1994
  {
    id: 'f1007',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Imola 1994',
    difficulty: 'simple',
    question: "At which Imola corner did Ayrton Senna's fatal crash occur on 1 May 1994?",
    options: ['Acque Minerali', 'Villeneuve', 'Tosa', 'Tamburello'],
    correctIndex: 3,
    explanation: 'His race-leading Williams speared off into the concrete wall at Tamburello.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Ayrton_Senna.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Ayrton Senna',
  },
  {
    id: 'f1008',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Imola 1994',
    difficulty: 'simple',
    question: 'Which team was Senna driving for when he was killed at the 1994 San Marino Grand Prix?',
    options: ['McLaren', 'Lotus', 'Benetton', 'Williams'],
    correctIndex: 3,
    explanation: 'He had joined Williams for 1994 after six seasons and three titles with McLaren.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Ayrton_Senna.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Ayrton Senna',
  },
  {
    id: 'f1009',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Imola 1994',
    difficulty: 'expert',
    question: 'Which Austrian Simtek driver was killed in Saturday qualifying at Imola in 1994?',
    options: ['Roland Ratzenberger', 'Karl Wendlinger', 'Gerhard Berger', 'Jo Gartner'],
    correctIndex: 0,
    explanation: 'A damaged front wing failed at over 300 km/h approaching the Villeneuve kink; he was 33.',
    sourceUrl:
      'https://www.formula1.com/en/latest/article.a-racer-through-and-through-ratzenberger-remembered.4GgLrhjq9vSL5anb023G7.html',
    sourceLabel: 'Formula1.com: A racer through and through, Ratzenberger remembered',
  },
  {
    id: 'f1010',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Imola 1994',
    difficulty: 'extreme',
    question: "Whose stalled Benetton was hit by Pedro Lamy's Lotus at the start of the 1994 San Marino Grand Prix?",
    options: ['Michael Schumacher', 'JJ Lehto', 'Jos Verstappen', 'Johnny Herbert'],
    correctIndex: 1,
    explanation: 'Wheels from the collision flew into the crowd, injuring spectators and a policeman.',
    sourceUrl: 'https://www.motorsportmagazine.com/archive/article/june-1994/16/black-sunday',
    sourceLabel: 'Motor Sport Magazine: Black Sunday (June 1994 archive)',
  },
  {
    id: 'f1011',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Imola 1994',
    difficulty: 'extreme',
    question: 'At which Imola corner did Roland Ratzenberger crash in 1994 qualifying?',
    options: ['Tamburello', 'Rivazza', 'Villeneuve', 'Variante Bassa'],
    correctIndex: 2,
    explanation: 'He had run wide at Acque Minerali the lap before, damaging the front wing that then failed.',
    sourceUrl:
      'https://www.formula1.com/en/latest/article.a-racer-through-and-through-ratzenberger-remembered.4GgLrhjq9vSL5anb023G7.html',
    sourceLabel: 'Formula1.com: A racer through and through, Ratzenberger remembered',
  },
  // ------------------------------------------ Schumacher deciders: Adelaide 1994 and Jerez 1997
  {
    id: 'f1012',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Adelaide 1994 and Jerez 1997',
    difficulty: 'simple',
    question: 'Which Williams driver did Michael Schumacher collide with to settle the 1994 title in Adelaide?',
    options: ['Nigel Mansell', 'David Coulthard', 'Damon Hill', 'Riccardo Patrese'],
    correctIndex: 2,
    explanation: 'Both cars were out; Schumacher took the title by a single point.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Michael_Schumacher.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Michael Schumacher',
  },
  {
    id: 'f1013',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Adelaide 1994 and Jerez 1997',
    difficulty: 'simple',
    question: "Who won the 1997 title after Schumacher's failed attempt to ram him off the road at Jerez?",
    options: ['Jacques Villeneuve', 'Mika Hakkinen', 'Heinz-Harald Frentzen', 'David Coulthard'],
    correctIndex: 0,
    explanation: 'Villeneuve won seven races that year and took the crown in his second F1 season.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Jacques_Villeneuve.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Jacques Villeneuve',
  },
  {
    id: 'f1014',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Adelaide 1994 and Jerez 1997',
    difficulty: 'expert',
    question: 'By how many points did Michael Schumacher beat Damon Hill to the 1994 title?',
    options: ['Three', 'Five', 'Two', 'One'],
    correctIndex: 3,
    explanation: 'The final table read Schumacher 92, Hill 91.',
    sourceUrl: 'https://www.formula1.com/en/results/1994/drivers',
    sourceLabel: "Formula1.com: 1994 drivers' standings",
  },
  {
    id: 'f1015',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Adelaide 1994 and Jerez 1997',
    difficulty: 'expert',
    question: 'At which Jerez corner did Villeneuve dive inside Schumacher on lap 48 of the 1997 decider?',
    options: ['Curva Ferrari', 'Expo', 'Dry Sack', 'Nieto'],
    correctIndex: 2,
    explanation: "Schumacher turned in, hit the Williams' sidepod and beached his Ferrari in the gravel.",
    sourceUrl:
      'https://www.formula1.com/en/latest/article.how-i-beat-schumacher-to-the-title-at-jerez-97-by-jacques-villeneuve.2cerUxDqRaYUsoQi2KGSQW.html',
    sourceLabel: "Formula1.com: How I beat Schumacher to the title at Jerez '97, by Jacques Villeneuve",
  },
  {
    id: 'f1016',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Adelaide 1994 and Jerez 1997',
    difficulty: 'expert',
    question: 'Which driver took the first win of his F1 career at Jerez in the 1997 finale?',
    options: ['David Coulthard', 'Heinz-Harald Frentzen', 'Eddie Irvine', 'Mika Hakkinen'],
    correctIndex: 3,
    explanation: 'Coulthard and Villeneuve moved aside in the closing laps to let Hakkinen through.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Mika_Hakkinen.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Mika Hakkinen',
  },
  {
    id: 'f1017',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Adelaide 1994 and Jerez 1997',
    difficulty: 'extreme',
    question: 'Which third driver matched Villeneuve and Schumacher to the thousandth (1:21.072) in Jerez 1997 qualifying?',
    options: ['Heinz-Harald Frentzen', 'David Coulthard', 'Eddie Irvine', 'Gerhard Berger'],
    correctIndex: 0,
    explanation: 'Villeneuve took pole because he set the time first.',
    sourceUrl:
      'https://www.formula1.com/en/latest/article.how-i-beat-schumacher-to-the-title-at-jerez-97-by-jacques-villeneuve.2cerUxDqRaYUsoQi2KGSQW.html',
    sourceLabel: "Formula1.com: How I beat Schumacher to the title at Jerez '97, by Jacques Villeneuve",
  },
  {
    id: 'f1018',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Adelaide 1994 and Jerez 1997',
    difficulty: 'extreme',
    question: 'At which Adelaide corner did Schumacher hit the wall on lap 36 of 1994, just before turning into Hill?',
    options: ['Brabham Straight', 'East Terrace', 'Wakefield', 'Dequetteville'],
    correctIndex: 1,
    explanation: 'The Benetton had been damaged; Hill was forced into the barriers at the next corner and retired.',
    sourceUrl:
      'https://www.autosport.com/f1/news/the-most-controversial-f1-deciders-1990-japan-1994-australia-more/6867598/',
    sourceLabel: 'Autosport: The most controversial F1 deciders',
  },
  // ------------------------------------------------------------------ Hunt v Lauda 1976
  {
    id: 'f1019',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Hunt v Lauda 1976',
    difficulty: 'simple',
    question: 'Who won the 1976 world title after Niki Lauda withdrew from the rain-soaked finale at Fuji?',
    options: ['Jody Scheckter', 'Mario Andretti', 'James Hunt', 'Clay Regazzoni'],
    correctIndex: 2,
    explanation: 'Hunt stayed out and finished third, enough to take the title for McLaren.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/James_Hunt.html',
    sourceLabel: 'Formula1.com: Hall of Fame, James Hunt',
  },
  {
    id: 'f1020',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Hunt v Lauda 1976',
    difficulty: 'simple',
    question: "At which circuit did Lauda's Ferrari crash and burst into flames in 1976?",
    options: ['Monza', 'Nurburgring', 'Zandvoort', 'Brands Hatch'],
    correctIndex: 1,
    explanation: 'Four drivers and a marshal pulled him from the burning car on the second lap.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Niki_Lauda.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Niki Lauda',
  },
  {
    id: 'f1021',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Hunt v Lauda 1976',
    difficulty: 'expert',
    question: 'By how many points did James Hunt beat Niki Lauda to the 1976 championship?',
    options: ['Four', 'Two', 'Three', 'One'],
    correctIndex: 3,
    explanation: 'Hunt finished on 69 points to Lauda’s 68.',
    sourceUrl: 'https://www.formula1.com/en/results/1976/drivers',
    sourceLabel: "Formula1.com: 1976 drivers' standings",
  },
  {
    id: 'f1022',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Hunt v Lauda 1976',
    difficulty: 'expert',
    question: 'Who won the 1976 Japanese Grand Prix at Fuji while Hunt took the title in third?',
    options: ['Patrick Depailler', 'Alan Jones', 'Ronnie Peterson', 'Mario Andretti'],
    correctIndex: 3,
    explanation: 'Andretti won for Lotus with everyone else at least a lap behind.',
    sourceUrl: 'https://www.formula1.com/en/results/1976/races/373/japan/race-result',
    sourceLabel: 'Formula1.com: 1976 Japanese Grand Prix race result',
  },
  {
    id: 'f1023',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Hunt v Lauda 1976',
    difficulty: 'extreme',
    question: "Why was Hunt's 1976 Spanish Grand Prix win initially thrown out in scrutineering?",
    options: ['The car was underweight', 'The car was too wide', 'Illegal fuel octane', 'An oversized rear wing'],
    correctIndex: 1,
    explanation: 'New Goodyear sidewalls bulged the McLaren about 1.8 cm over the limit; the win was restored on appeal.',
    sourceUrl: 'https://www.motorsport.com/f1/news/mclaren-spanish-gp-1976-controversy/4787390/',
    sourceLabel: "Motorsport.com: McLaren's 1976 Spanish GP controversy",
  },
  {
    id: 'f1024',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Hunt v Lauda 1976',
    difficulty: 'extreme',
    question: 'Where did Lauda finish on his comeback at Monza, six weeks after his 1976 crash?',
    options: ['First', 'Second', 'Fourth', 'Eighth'],
    correctIndex: 2,
    explanation: 'He returned to the cockpit with his burns still unhealed and scored points immediately.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Niki_Lauda.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Niki Lauda',
  },
  // ------------------------------------------------------------------ Indianapolis 2005
  {
    id: 'f1025',
    domain: 'sports',
    region: 'US',
    topic: 'Formula 1',
    subtopic: 'Indianapolis 2005',
    difficulty: 'simple',
    question: 'How many cars took the start of the 2005 United States Grand Prix at Indianapolis?',
    options: ['Six', 'Ten', 'Twelve', 'Eight'],
    correctIndex: 0,
    explanation: 'All seven Michelin-shod teams withdrew after the formation lap on tyre-safety grounds.',
    sourceUrl: 'https://www.formula1.com/en/results/2005/races/779/united-states/race-result',
    sourceLabel: 'Formula1.com: 2005 United States Grand Prix race result',
  },
  {
    id: 'f1026',
    domain: 'sports',
    region: 'US',
    topic: 'Formula 1',
    subtopic: 'Indianapolis 2005',
    difficulty: 'expert',
    question: "Whose practice crash at Indianapolis's banked Turn 13 exposed the Michelin tyre problem in 2005?",
    options: ['Jarno Trulli', 'Kimi Raikkonen', 'Ralf Schumacher', 'Fernando Alonso'],
    correctIndex: 2,
    explanation: 'Michelin found standing waves in its sidewalls under the banking loads and told teams not to race.',
    sourceUrl: 'https://www.motorsport.com/f1/news/the-2005-us-gp-farce-the-full-inside-story/4809048/',
    sourceLabel: 'Motorsport.com: The 2005 US GP farce, the full inside story',
  },
  {
    id: 'f1027',
    domain: 'sports',
    region: 'US',
    topic: 'Formula 1',
    subtopic: 'Indianapolis 2005',
    difficulty: 'extreme',
    question: 'Which Jordan driver finished third behind the two Ferraris at Indianapolis in 2005?',
    options: ['Narain Karthikeyan', 'Tiago Monteiro', 'Christijan Albers', 'Patrick Friesacher'],
    correctIndex: 1,
    explanation: 'Karthikeyan was fourth in the other Jordan; the two Minardis completed the six classified.',
    sourceUrl: 'https://www.formula1.com/en/results/2005/races/779/united-states/race-result',
    sourceLabel: 'Formula1.com: 2005 United States Grand Prix race result',
  },
  // -------------------------------------------------------------- Ferrari team orders 2002
  {
    id: 'f1028',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Austria 2002 team orders',
    difficulty: 'simple',
    question: 'Which Ferrari driver slowed at the final corner to hand Schumacher the 2002 Austrian Grand Prix?',
    options: ['Eddie Irvine', 'Felipe Massa', 'Jean Alesi', 'Rubens Barrichello'],
    correctIndex: 3,
    explanation: 'Barrichello had led from pole; the crowd booed and Schumacher pushed him onto the top step.',
    sourceUrl: 'https://www.motorsport.com/f1/news/austria-2002-ferrari-team-orders/4791321/',
    sourceLabel: 'Motorsport.com: Austria 2002, when unnecessary team orders rocked F1',
  },
  {
    id: 'f1029',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Austria 2002 team orders',
    difficulty: 'expert',
    question: 'What did the FIA actually fine Ferrari and its drivers $1 million for after Austria 2002?',
    options: ['Breaching podium procedures', 'Issuing team orders', 'Dangerous driving', 'Bringing the sport into disrepute'],
    correctIndex: 0,
    explanation: 'The council ruled team orders were a traditional right; half the fine was suspended.',
    sourceUrl: 'https://www.autosport.com/f1/news/ferrari-fined-1-million-over-austrian-gp-incident-5060279/5060279/',
    sourceLabel: 'Autosport: Ferrari fined $1 million over Austrian GP incident',
  },
  {
    id: 'f1030',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Austria 2002 team orders',
    difficulty: 'extreme',
    question: "Which 2010 race, with the radio call 'Fernando is faster than you', preceded the lifting of the team orders ban?",
    options: ['Italian Grand Prix', 'Turkish Grand Prix', 'British Grand Prix', 'German Grand Prix'],
    correctIndex: 3,
    explanation: 'Ferrari was fined $100,000 at Hockenheim; the FIA then dropped the ban as unpoliceable.',
    sourceUrl:
      'https://www.autosport.com/f1/news/not-mclarens-first-radio-rodeo-a-brief-history-of-f1-team-orders-controversies/10637758/',
    sourceLabel: 'Autosport: A brief history of F1 team orders controversies',
  },
  // ------------------------------------------------------------------------ Spygate 2007
  {
    id: 'f1031',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Spygate 2007',
    difficulty: 'simple',
    question: "Which team was fined $100 million in 2007's Spygate affair over Ferrari technical documents?",
    options: ['Renault', 'Williams', 'McLaren', 'Honda'],
    correctIndex: 2,
    explanation: 'McLaren was also stripped of its constructors’ points, though Hamilton and Alonso kept theirs.',
    sourceUrl: 'https://www.autosport.com/f1/news/from-the-archive-how-spygate-rocked-mclaren-and-f1/10811148/',
    sourceLabel: 'Autosport: From the archive, how Spygate rocked McLaren and F1',
  },
  {
    id: 'f1032',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Spygate 2007',
    difficulty: 'expert',
    question: 'Which Ferrari employee passed the technical dossier to McLaren designer Mike Coughlan in 2007?',
    options: ['Nigel Stepney', 'Rory Byrne', 'Aldo Costa', 'Paolo Martinelli'],
    correctIndex: 0,
    explanation: 'The pair had worked together at Benetton; the leak surfaced via a photocopy shop.',
    sourceUrl: 'https://www.autosport.com/f1/news/from-the-archive-how-spygate-rocked-mclaren-and-f1/10811148/',
    sourceLabel: 'Autosport: From the archive, how Spygate rocked McLaren and F1',
  },
  {
    id: 'f1033',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Spygate 2007',
    difficulty: 'extreme',
    question: 'How many pages long was the Ferrari dossier at the centre of Spygate?',
    options: ['240', '780', '1,200', '95'],
    correctIndex: 1,
    explanation: "Coughlan's wife took it to a copy shop whose manager tipped off Ferrari.",
    sourceUrl: 'https://www.autosport.com/f1/news/from-the-archive-how-spygate-rocked-mclaren-and-f1/10811148/',
    sourceLabel: 'Autosport: From the archive, how Spygate rocked McLaren and F1',
  },
  // ------------------------------------------------------------------------ Crashgate 2008
  {
    id: 'f1034',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Crashgate',
    difficulty: 'simple',
    question: 'Which Renault driver deliberately crashed at the 2008 Singapore Grand Prix to help his team-mate?',
    options: ['Giancarlo Fisichella', 'Romain Grosjean', 'Heikki Kovalainen', 'Nelson Piquet Jr'],
    correctIndex: 3,
    explanation: 'The safety car he triggered handed the win to Fernando Alonso, who had pitted early.',
    sourceUrl: 'https://racingnews365.com/f1s-biggest-scandals-renault-lose-ps40m-a-year-after-crashgate',
    sourceLabel: "RacingNews365: F1's biggest scandals, Renault lose 40m a year after Crashgate",
  },
  {
    id: 'f1035',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Crashgate',
    difficulty: 'expert',
    question: "Who won the 2008 Singapore Grand Prix from 15th on the grid thanks to Piquet's crash?",
    options: ['Nico Rosberg', 'Lewis Hamilton', 'Fernando Alonso', 'Felipe Massa'],
    correctIndex: 2,
    explanation: 'Rosberg was second for Williams and Hamilton third; Alonso was cleared of any involvement.',
    sourceUrl: 'https://www.formula1.com/en/results/2008/races/839/singapore/race-result',
    sourceLabel: 'Formula1.com: 2008 Singapore Grand Prix race result',
  },
  {
    id: 'f1036',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Crashgate',
    difficulty: 'extreme',
    question: 'At which Marina Bay turn did Nelson Piquet Jr put his Renault into the wall in 2008?',
    options: ['Turn 7', 'Turn 10', 'Turn 17', 'Turn 22'],
    correctIndex: 2,
    explanation: 'A low-speed corner where a crash looked implausible, which is exactly why it was chosen.',
    sourceUrl:
      'https://www.motorsportmagazine.com/articles/single-seaters/f1/f1-crashgate-what-happened-and-why-felipe-massa-has-reignited-controversy/',
    sourceLabel: 'Motor Sport Magazine: F1 Crashgate, what happened',
  },
  {
    id: 'f1037',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Crashgate',
    difficulty: 'extreme',
    question: 'What sanction did the Renault team itself receive for Crashgate in 2009?',
    options: ['A $100 million fine', 'A two-year suspended disqualification', 'Loss of its 2008 points', 'A three-race ban'],
    correctIndex: 1,
    explanation: 'Briatore was banned indefinitely and Symonds for five years, while Piquet Jr had immunity.',
    sourceUrl: 'https://racingnews365.com/f1s-biggest-scandals-renault-lose-ps40m-a-year-after-crashgate',
    sourceLabel: "RacingNews365: F1's biggest scandals, Renault lose 40m a year after Crashgate",
  },
  // --------------------------------------------------------------------------- Multi-21
  {
    id: 'f1038',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Multi-21',
    difficulty: 'simple',
    question: 'Which Red Bull team-mate did Sebastian Vettel pass against orders to win the 2013 Malaysian Grand Prix?',
    options: ['Daniel Ricciardo', 'Mark Webber', 'David Coulthard', 'Daniil Kvyat'],
    correctIndex: 1,
    explanation: "Vettel later admitted it was payback; Horner said his driver's attitude was simply 'F*** you'.",
    sourceUrl:
      'https://www.formula1.com/en/latest/article/horner-reveals-what-sparked-multi-21-controversy.6rSHG4O9lCE0yUQaMC0SWq',
    sourceLabel: "Formula1.com: Horner reveals what sparked 'Multi 21' controversy",
  },
  {
    id: 'f1039',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Multi-21',
    difficulty: 'expert',
    question: "What did Red Bull's coded instruction 'Multi 21' tell its drivers at Sepang in 2013?",
    options: [
      'Car 2 to stay ahead of car 1',
      'Switch to engine map 21',
      'Pit within two laps',
      'Car 1 to pass car 2 by lap 21',
    ],
    correctIndex: 0,
    explanation: "Hold station with Webber (car 2) ahead of Vettel (car 1); Webber's 'Multi 21, Seb' became a catchphrase.",
    sourceUrl:
      'https://www.motorsportmagazine.com/articles/single-seaters/f1/multi-21-how-the-red-bull-rb9-spawned-a-famous-f1-saying/',
    sourceLabel: "Motor Sport Magazine: 'Multi 21', how the Red Bull RB9 spawned a famous F1 saying",
  },
  {
    id: 'f1040',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Multi-21',
    difficulty: 'extreme',
    question: "Which 2012 race did Christian Horner cite as the origin of Vettel's grudge behind Multi-21?",
    options: ['Brazilian Grand Prix', 'Abu Dhabi Grand Prix', 'Japanese Grand Prix', 'Italian Grand Prix'],
    correctIndex: 0,
    explanation: 'Webber squeezed Vettel against the pit wall at the start of the Interlagos decider.',
    sourceUrl:
      'https://www.formula1.com/en/latest/article/horner-reveals-what-sparked-multi-21-controversy.6rSHG4O9lCE0yUQaMC0SWq',
    sourceLabel: "Formula1.com: Horner reveals what sparked 'Multi 21' controversy",
  },
  // ------------------------------------------------------------------ Hamilton v Rosberg
  {
    id: 'f1041',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Hamilton v Rosberg',
    difficulty: 'simple',
    question: 'Which Mercedes driver won the 2016 title and announced his retirement five days later?',
    options: ['Valtteri Bottas', 'Lewis Hamilton', 'Nico Rosberg', 'Michael Schumacher'],
    correctIndex: 2,
    explanation: 'He broke the news at the FIA prize-giving in Vienna; father Keke had won the 1982 title.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Nico_Rosberg.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Nico Rosberg',
  },
  {
    id: 'f1042',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Hamilton v Rosberg',
    difficulty: 'expert',
    question: 'By how many points did Nico Rosberg beat Lewis Hamilton to the 2016 championship?',
    options: ['Twelve', 'One', 'Eight', 'Five'],
    correctIndex: 3,
    explanation: 'Hamilton won the last four races but the table finished 385 to 380.',
    sourceUrl: 'https://www.formula1.com/en/results/2016/drivers',
    sourceLabel: "Formula1.com: 2016 drivers' standings",
  },
  {
    id: 'f1043',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Hamilton v Rosberg',
    difficulty: 'extreme',
    question: 'Who finished third, 0.843s behind the winner, as Hamilton backed Rosberg into the pack at Abu Dhabi 2016?',
    options: ['Max Verstappen', 'Daniel Ricciardo', 'Kimi Raikkonen', 'Sebastian Vettel'],
    correctIndex: 3,
    explanation: 'Hamilton won, Rosberg held second by 0.4s over Vettel, and the title was his.',
    sourceUrl: 'https://www.formula1.com/en/results/2016/races/957/abu-dhabi/race-result',
    sourceLabel: 'Formula1.com: 2016 Abu Dhabi Grand Prix race result',
  },
  // ------------------------------------------------- Verstappen v Hamilton and Abu Dhabi 2021
  {
    id: 'f1044',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Abu Dhabi 2021',
    difficulty: 'simple',
    question: 'Max Verstappen became the first Formula 1 world champion from which country in 2021?',
    options: ['Netherlands', 'Belgium', 'Austria', 'Denmark'],
    correctIndex: 0,
    explanation: 'He passed Hamilton at Turn 5 on the final lap after a late safety-car restart.',
    sourceUrl:
      'https://www.formula1.com/en/latest/article.brilliant-verstappen-claims-maiden-title-after-victory-in-abu-dhabi-season.22Arui4l6BKK2PUsJgKqpZ.html',
    sourceLabel: 'Formula1.com: Verstappen claims maiden title after victory in Abu Dhabi season finale',
  },
  {
    id: 'f1045',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Abu Dhabi 2021',
    difficulty: 'expert',
    question: 'Whose crash brought out the safety car that reshaped the last laps of the 2021 Abu Dhabi finale?',
    options: ['Mick Schumacher', 'Antonio Giovinazzi', 'Nicholas Latifi', 'Kimi Raikkonen'],
    correctIndex: 2,
    explanation: 'Latifi spun into the wall exiting Turn 14 on lap 53 while fighting Schumacher for 15th.',
    sourceUrl:
      'https://www.formula1.com/en/latest/article.brilliant-verstappen-claims-maiden-title-after-victory-in-abu-dhabi-season.22Arui4l6BKK2PUsJgKqpZ.html',
    sourceLabel: 'Formula1.com: Verstappen claims maiden title after victory in Abu Dhabi season finale',
  },
  {
    id: 'f1046',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Verstappen v Hamilton',
    difficulty: 'expert',
    question: 'At which Silverstone corner did Hamilton and Verstappen collide on lap one of the 2021 British Grand Prix?',
    options: ['Stowe', 'Maggotts', 'Brooklands', 'Copse'],
    correctIndex: 3,
    explanation: 'Hamilton took a 10-second penalty and still won; Verstappen went to hospital for checks.',
    sourceUrl: 'https://www.autosport.com/f1/news/the-details-at-the-heart-of-the-hamilton-verstappen-debate/6634406/',
    sourceLabel: 'Autosport: The details at the heart of the Hamilton-Verstappen debate',
  },
  {
    id: 'f1047',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Abu Dhabi 2021',
    difficulty: 'extreme',
    question: 'How many lapped cars were allowed to un-lap themselves before the final-lap restart at Abu Dhabi 2021?',
    options: ['All eight', 'Five', 'Three', 'None'],
    correctIndex: 1,
    explanation: 'Race director Michael Masi let only the cars between Hamilton and Verstappen through.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Max_Verstappen.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Max Verstappen',
  },
  {
    id: 'f1048',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Abu Dhabi 2021',
    difficulty: 'extreme',
    question: 'Which pair replaced Michael Masi as alternating race directors in February 2022?',
    options: [
      'Niels Wittich and Eduardo Freitas',
      'Herbie Blash and Charlie Whiting',
      'Tim Mayer and Rui Marques',
      'Colin Haywood and Scot Elkins',
    ],
    correctIndex: 0,
    explanation: 'Herbie Blash returned as senior advisor and team radio to the race director left the TV feed.',
    sourceUrl:
      'https://www.formula1.com/en/latest/article.michael-masi-replaced-as-race-director-amid-fia-structural-changes.174xskJuXpEIAiXPQ98oPE.html',
    sourceLabel: 'Formula1.com: Michael Masi replaced as race director amid FIA structural changes',
  },
  // ----------------------------------------------------- Ground effect and the rulebooks
  {
    id: 'f1049',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Ground effect and the 2022 rules',
    difficulty: 'simple',
    question: 'Which aerodynamic concept, banned since the early 1980s, returned with the 2022 technical rules?',
    options: ['Active suspension', 'Fan cars', 'Ground effect', 'Six-wheelers'],
    correctIndex: 2,
    explanation: 'Venturi tunnels under the floor now do the work wings used to, cutting the dirty-air penalty.',
    sourceUrl:
      'https://www.autosport.com/f1/news/formula-1s-2021-regulations-what-will-the-cars-look-like-in-2022-5278037/5278037/',
    sourceLabel: "Autosport: Formula 1's 2021 regulations, what will the cars look like in 2022",
  },
  {
    id: 'f1050',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'The 2026 rules',
    difficulty: 'simple',
    question: 'Which hybrid component was dropped from Formula 1 power units under the 2026 engine rules?',
    options: ['MGU-H', 'MGU-K', 'Turbocharger', 'Energy store'],
    correctIndex: 0,
    explanation: 'The heat-recovery motor went, and the MGU-K grew to roughly half of total power output.',
    sourceUrl: 'https://www.autosport.com/f1/news/fia-finalises-2026-formula-1-engines-regulations/10353609/',
    sourceLabel: 'Autosport: FIA finalises 2026 Formula 1 engine regulations',
  },
  {
    id: 'f1051',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'The 2026 rules',
    difficulty: 'expert',
    question: 'Which overtaking aid did active aerodynamics, with its X-mode and Z-mode, replace for 2026?',
    options: ['KERS', 'Push-to-pass', 'F-duct', 'DRS'],
    correctIndex: 3,
    explanation: 'Movable front and rear wing elements switch between low-drag and high-downforce settings.',
    sourceUrl: 'https://www.autosport.com/f1/news/how-f1s-new-active-aero-will-work-in-2026/10620099/',
    sourceLabel: "Autosport: How F1's new active aero will work in 2026",
  },
  {
    id: 'f1052',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'The 2026 rules',
    difficulty: 'extreme',
    question: 'What electrical output was set for the MGU-K under the 2026 power unit regulations?',
    options: ['120 kW', '200 kW', '350 kW', '500 kW'],
    correctIndex: 2,
    explanation: 'That is about half the powertrain’s total output, with the V6 on fully sustainable fuel supplying the rest.',
    sourceUrl: 'https://www.autosport.com/f1/news/fia-finalises-2026-formula-1-engines-regulations/10353609/',
    sourceLabel: 'Autosport: FIA finalises 2026 Formula 1 engine regulations',
  },
  // ------------------------------------------------------------------------------ Monaco
  {
    id: 'f1053',
    domain: 'sports',
    region: 'Europe',
    topic: 'Formula 1',
    subtopic: 'Monaco',
    difficulty: 'simple',
    question: 'Which driver holds the record of six Monaco Grand Prix victories?',
    options: ['Graham Hill', 'Michael Schumacher', 'Ayrton Senna', 'Alain Prost'],
    correctIndex: 2,
    explanation: 'His first Monaco podium came in a Toleman in 1984, second in the rain to Prost.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Ayrton_Senna.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Ayrton Senna',
  },
  {
    id: 'f1054',
    domain: 'sports',
    region: 'Europe',
    topic: 'Formula 1',
    subtopic: 'Monaco',
    difficulty: 'expert',
    question: 'Who won the 1996 Monaco Grand Prix, in which only three cars were still running at the finish?',
    options: ['David Coulthard', 'Johnny Herbert', 'Jean Alesi', 'Olivier Panis'],
    correctIndex: 3,
    explanation: 'Panis’s Ligier beat Coulthard and Herbert home; it was his only F1 win.',
    sourceUrl: 'https://www.formula1.com/en/results/1996/races/643/monaco/race-result',
    sourceLabel: 'Formula1.com: 1996 Monaco Grand Prix race result',
  },
  {
    id: 'f1055',
    domain: 'sports',
    region: 'Europe',
    topic: 'Formula 1',
    subtopic: 'Monaco',
    difficulty: 'extreme',
    question: 'Who took his first Grand Prix win at Monaco in 1982 after the leaders fell away in the final laps?',
    options: ['Didier Pironi', 'Andrea de Cesaris', 'Riccardo Patrese', 'Derek Daly'],
    correctIndex: 2,
    explanation: 'Prost crashed, Patrese spun and recovered, Pironi stopped in the tunnel and de Cesaris ran dry.',
    sourceUrl: 'https://www.formula1.com/en/results/1982/races/442/monaco/race-result',
    sourceLabel: 'Formula1.com: 1982 Monaco Grand Prix race result',
  },
  // ------------------------------------------------------------ Constructors' dynasties
  {
    id: 'f1056',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: "Constructors' dynasties",
    difficulty: 'simple',
    question: 'Which team is the only one to have competed in every Formula 1 season since 1950?',
    options: ['McLaren', 'Williams', 'Ferrari', 'Lotus'],
    correctIndex: 2,
    explanation: 'Ferrari claimed a then-unprecedented five consecutive title doubles with Schumacher.',
    sourceUrl: 'https://www.formula1.com/en/teams/ferrari',
    sourceLabel: 'Formula1.com: Ferrari team profile',
  },
  {
    id: 'f1057',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: "Constructors' dynasties",
    difficulty: 'expert',
    question: "How many consecutive constructors' titles did Ferrari win in the Schumacher era from 1999?",
    options: ['Four', 'Six', 'Five', 'Eight'],
    correctIndex: 1,
    explanation: 'Six straight, 1999 to 2004, a run Mercedes later passed with eight from 2014.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Michael_Schumacher.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Michael Schumacher',
  },
  {
    id: 'f1058',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: "Constructors' dynasties",
    difficulty: 'extreme',
    question: "At which 2018 race did Mercedes clinch a fifth successive constructors' championship?",
    options: ['Brazilian Grand Prix', 'Mexican Grand Prix', 'Abu Dhabi Grand Prix', 'United States Grand Prix'],
    correctIndex: 0,
    explanation: 'Only the second team ever to win five in a row, one short of Ferrari’s six at the time.',
    sourceUrl:
      "https://www.formula1.com/en/latest/article.mercedes-clinch-constructors%27-title-for-fifth-successive-year.4bsymszebKSY62cAgMcGYg.html",
    sourceLabel: "Formula1.com: Mercedes clinch constructors' title for fifth successive year",
  },
  // ------------------------------------------------------------------------ Title deciders
  {
    id: 'f1059',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Title deciders',
    difficulty: 'simple',
    question: 'Who won the 2008 world title by a single point with a last-lap pass for fifth at Interlagos?',
    options: ['Felipe Massa', 'Lewis Hamilton', 'Kimi Raikkonen', 'Fernando Alonso'],
    correctIndex: 1,
    explanation: 'At 23 years and 300 days he was then the youngest champion; Massa won the race for Ferrari.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Lewis_Hamilton.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Lewis Hamilton',
  },
  {
    id: 'f1060',
    domain: 'sports',
    region: 'Global',
    topic: 'Formula 1',
    subtopic: 'Title deciders',
    difficulty: 'expert',
    question: "Who is Formula 1's only posthumous world champion?",
    options: ['Jochen Rindt', 'Jim Clark', 'Ronnie Peterson', 'Gilles Villeneuve'],
    correctIndex: 0,
    explanation: 'Rindt died in practice at Monza in September 1970 with an unassailable points lead for Lotus.',
    sourceUrl: 'https://www.formula1.com/en/drivers/hall-of-fame/Jochen_Rindt.html',
    sourceLabel: 'Formula1.com: Hall of Fame, Jochen Rindt',
  },
]);
