// HISAAB DO — Distribution: Centre lane (hdb001–hdb099), money-trail mode "Seedha Khaate Mein".
// Contract: docs/hisaab/CHARTER.md §2–§5, §3a and §4a–§4b; editions/hisaab/bank/schema.mjs.
// Research notes, sources, dropped items and stale-risk list: docs/hisaab/research/dist-centre-notes.md.
// Every figure was read on the item's sourceUrl (or a listed source) in September 2026 (asOf).
// enactedBy records who announced, presented or passed a measure — a public act, not an allegation.
// Timing facts (gapDays) are days from the announcement or first payment to the first day of polling.

export const HISAAB_DIST_CENTRE = Object.freeze([
  // ───────────────────────────── 2000–2004 ─────────────────────────────
  {
    id: "hdb001",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Antyodaya Anna Yojana",
    kind: "scheme",
    difficulty: "simple",
    year: 2000,
    asOf: "2026-09",
    govt: "NDA",
    question: "Antyodaya Anna Yojana, launched in December 2000 for one crore of the poorest families, sold them wheat and rice at what prices?",
    options: ["₹2 a kg wheat, ₹3 a kg rice", "₹4 a kg wheat, ₹6 a kg rice", "Free of cost", "₹1 a kg wheat, ₹2 a kg rice"],
    correctIndex: 0,
    explanation: "The food ministry's NFSA portal records AAY's launch in December 2000 for one crore 'poorest of the poor' families at ₹2 a kg for wheat and ₹3 a kg for rice, with states bearing distribution costs. The ration was raised from 25 kg a family a month from 1 April 2002. The 2004 interim budget noted it was launched by the Prime Minister, then Atal Bihari Vajpayee.",
    sourceUrl: "https://nfsa.gov.in/portal/PDS_page",
    sourceLabel: "Dept of Food & Public Distribution, NFSA portal — Public Distribution System: Antyodaya Anna Yojana (accessed Sep 2026)",
    sources: [
      "https://www.indiabudget.gov.in/budget_archive/ub2004-05(I)/bs/speecha.htm",
      "https://scroll.in/article/735000/modi-government-is-killing-vajpayees-food-security-scheme",
      "https://www.thehindu.com/news/national/tamil-nadu/tamil-nadu-drew-lower-quantity-of-rice-than-its-share-underantyodayaannayojana-in-five-of-the-last-seven-years/article71193040.ece",
    ],
    tags: ["distribution"],
    enactedBy: [{ name: "Atal Bihari Vajpayee", role: "Prime Minister", party: "BJP" }],
    outcome: "Expanded in three steps to 2.5 crore households by May 2005, about 38% of BPL families; its flat per-household ration carried into the 2013 food law.",
  },
  {
    id: "hdb002",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Education & Exams",
    subtopic: "Mid-day meals (PUCL order)",
    kind: "scheme",
    difficulty: "simple",
    year: 2001,
    asOf: "2026-09",
    govt: "NDA",
    question: "In its interim order of 28 November 2001 in the right-to-food case (PUCL v Union of India), what did the Supreme Court direct every state to start in primary schools within six months?",
    options: ["Free school uniforms", "Cooked mid-day meals", "Monthly cash stipends", "Free textbooks"],
    correctIndex: 1,
    explanation: "The interim order in Writ Petition 196 of 2001 directed all state governments to introduce cooked mid-day meals in primary schools within six months. Frontline reported in August 2002 that Jharkhand had still not complied, even as more than 65 million tonnes of wheat and rice lay in Food Corporation of India godowns.",
    sourceUrl: "https://frontline.thehindu.com/other/article30245718.ece",
    sourceLabel: "Frontline — Starving still in Jharkhand (3 Aug 2002)",
    tags: ["distribution"],
    outcome: "Compliance lagged: in August 2002, about eight months after the order, Frontline reported that Jharkhand had ignored the mid-day meal direction despite pressure from citizens' groups.",
  },
  {
    id: "hdb003",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Antyodaya Anna Yojana (2003 expansion)",
    kind: "spend",
    difficulty: "expert",
    year: 2003,
    asOf: "2026-09",
    govt: "NDA",
    question: "Jaswant Singh said he wanted it to be the very first announcement of his 2003-04 Union Budget. What was it?",
    options: ["A cut in income-tax rates", "A farm loan waiver", "Antyodaya grain for 50 lakh more families", "A new rural jobs guarantee law"],
    correctIndex: 2,
    explanation: "Presenting the NDA's sixth budget, Jaswant Singh extended Antyodaya Anna Yojana to 50 lakh more families from 1 April 2003 — taking it past a quarter of all BPL families — at an extra cost of ₹507 crore, calling it the first part of his assurance 'Garib ke pet me dana'.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2003-04/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2003-04, Jaswant Singh (Feb 2003)",
    sources: ["https://www.indiabudget.gov.in/budget_archive/ub2004-05/bs/speecha.htm"],
    tags: ["distribution"],
    enactedBy: [{ name: "Jaswant Singh", role: "Union Finance Minister", party: "BJP" }],
    outcome: "AAY covered 1.5 crore families by early 2004 and distributed 20.76 lakh tonnes of rice and 17.48 lakh tonnes of wheat in 2003-04, per the July 2004 budget.",
  },
  {
    id: "hdb004",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "Universal Health Insurance Scheme (2003)",
    kind: "scheme",
    difficulty: "extreme",
    year: 2003,
    asOf: "2026-09",
    govt: "NDA",
    question: "Budget 2003-04's community health insurance scheme charged an individual a premium of ₹1 a day. How much did the Centre offer to pay each year towards a BPL family's premium?",
    options: ["₹365", "₹30", "₹500", "₹100"],
    correctIndex: 3,
    explanation: "Jaswant Singh asked public sector insurers to design a universal health insurance scheme: ₹1 a day for an individual, ₹1.50 a day for a family of five, for hospitalisation cover of up to ₹30,000, accident death cover of ₹25,000 and lost-wage compensation. To make it affordable, the government would pay ₹100 a year towards a BPL family's premium.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2003-04/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2003-04, Jaswant Singh (Feb 2003)",
    sources: ["https://www.indiabudget.gov.in/budget_archive/ub2004-05/bs/speecha.htm"],
    tags: ["distribution"],
    enactedBy: [{ name: "Jaswant Singh", role: "Union Finance Minister", party: "BJP" }],
    outcome: "Only 11,408 BPL families had joined by May 2004. The UPA's July 2004 budget said the scheme was skewed towards the non-poor, limited it to BPL families and raised the premium subsidy to ₹200 an individual.",
  },
  {
    id: "hdb005",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Antyodaya Anna Yojana (2004 interim budget)",
    kind: "spend",
    difficulty: "expert",
    year: 2004,
    asOf: "2026-09",
    govt: "NDA",
    question: "Presenting the interim budget on 3 February 2004, weeks before the Lok Sabha polls, Jaswant Singh extended Antyodaya Anna Yojana to how many BPL families?",
    options: ["1 crore", "1.5 crore", "2 crore", "3 crore"],
    correctIndex: 2,
    explanation: "The interim budget said AAY, launched by the Prime Minister in December 2000, covered 1.5 crore BPL families and would reach 2 crore from 1 April 2004, with added allocations for tribal areas. The NDA lost the April–May election; in July 2004 the UPA's P. Chidambaram again proposed covering 2 crore families that year.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2004-05(I)/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Interim Budget Speech 2004-05, Jaswant Singh (3 Feb 2004)",
    sources: [
      "https://www.indiabudget.gov.in/budget_archive/ub2004-05/bs/speecha.htm",
      "https://www.livemint.com/news/india/80th-independence-day-india-8-decades-18-lok-sabha-polls-how-indian-elections-have-evolved-11786726502795.html",
      "https://www.aljazeera.com/news/2024/6/3/india-election-results-winners-and-losers-of-all-past-lok-sabha-votes",
    ],
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "Jaswant Singh", role: "Union Finance Minister", party: "BJP" }],
    outcome: "The UPA kept the expansion: its July 2004 budget set AAY at 2 crore families with a subsidy of nearly ₹3,500 crore, and a May 2005 order took it to 2.5 crore households.",
    poll: { label: "Lok Sabha 2004", month: "2004-04", gapDays: 77, result: "INC 145, BJP 138 seats; the Congress-led UPA formed the government" },
  },
  {
    id: "hdb006",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "National Food for Work Programme",
    kind: "scheme",
    difficulty: "expert",
    year: 2004,
    asOf: "2026-09",
    govt: "UPA",
    question: "Pending a rural jobs guarantee law, P. Chidambaram's July 2004 budget launched a new Food for Work programme. How many districts was it meant for?",
    options: ["50 drought-hit districts", "150 most backward districts", "All 600 districts", "330 tribal districts"],
    correctIndex: 1,
    explanation: "In his 8 July 2004 budget Chidambaram said work had begun on a National Employment Guarantee Act promising 100 days of work to one person in every poor household. Until it passed, a Food for Work programme would run in 150 districts classed as most backward, pooling over ₹6,000 crore already under SGRY, SGSY and other schemes.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2004-05/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2004-05, P. Chidambaram (8 Jul 2004)",
    sources: ["https://www.hindustantimes.com/india-news/raghuvansh-babu-the-architect-of-mgnrega-and-india-s-most-infulential-rural-development-minister/story-5fVSrl0jP44hBkbWCtJOqN.html"],
    tags: ["distribution"],
    enactedBy: [{ name: "P. Chidambaram", role: "Union Finance Minister", party: "INC" }],
    outcome: "The promised guarantee law, NREGA, was enacted in 2005 and rolled out in 200 districts in February 2006.",
  },

  // ───────────────────────────── 2005–2009 ─────────────────────────────
  {
    id: "hdb007",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "Janani Suraksha Yojana",
    kind: "scheme",
    difficulty: "simple",
    year: 2005,
    asOf: "2026-09",
    govt: "UPA",
    question: "Under Janani Suraksha Yojana, launched in April 2005, how much cash does a rural mother in a low-performing state get for giving birth in a health facility?",
    options: ["₹700", "₹5,000", "₹600", "₹1,400"],
    correctIndex: 3,
    explanation: "The National Health Mission says JSY was launched by the Prime Minister on 12 April 2005 to cut maternal and newborn deaths by promoting institutional delivery. A rural mother in the ten low-performing states gets ₹1,400 (plus ₹600 for the ASHA worker); in high-performing states the rural mother's package is ₹700.",
    sourceUrl: "https://nhm.gov.in/index1.php?lang=1&level=3&sublinkid=841&lid=309",
    sourceLabel: "National Health Mission — Janani Suraksha Yojana (accessed Sep 2026)",
    sources: ["https://indianexpress.com/article/india/nfhs-6-data-controversy-nadda-kharge-health-survey-row-10727183/"],
    tags: ["distribution"],
    enactedBy: [{ name: "Manmohan Singh", role: "Prime Minister", party: "INC" }],
    outcome: "Institutional births rose from 38.7% (NFHS-3, 2005-06) to 88.6% (NFHS-5) and 90.6% (NFHS-6), per NFHS figures reported by the Indian Express in June 2026; the surveys do not isolate JSY's share.",
  },
  {
    id: "hdb008",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "NREGA: who piloted it",
    kind: "scheme",
    difficulty: "simple",
    year: 2006,
    asOf: "2026-09",
    govt: "UPA",
    question: "Which Union Rural Development Minister (2004–09), a Rashtriya Janata Dal leader, has been called the 'unsung architect' of the rural jobs guarantee rolled out in February 2006?",
    options: ["C.P. Joshi", "Raghuvansh Prasad Singh", "M. Venkaiah Naidu", "Jairam Ramesh"],
    correctIndex: 1,
    explanation: "Hindustan Times called Raghuvansh Prasad Singh, rural development minister from 2004 to 2009, the 'unsung architect' of MGNREGA. When the rollout stalled, UPA chairperson Sonia Gandhi had the group of ministers under Pranab Mukherjee expedite it, and the scheme began in 200 districts in February 2006.",
    sourceUrl: "https://www.hindustantimes.com/india-news/raghuvansh-babu-the-architect-of-mgnrega-and-india-s-most-infulential-rural-development-minister/story-5fVSrl0jP44hBkbWCtJOqN.html",
    sourceLabel: "Hindustan Times — Raghuvansh babu, the architect of MGNREGA (13 Sep 2020)",
    tags: ["distribution"],
    enactedBy: [
      { name: "Raghuvansh Prasad Singh", role: "Union Rural Development Minister", party: "RJD" },
      { name: "Manmohan Singh", role: "Prime Minister", party: "INC" },
    ],
    outcome: "The programme outlived the UPA; in the Covid year 2020-21 it drew a record allocation of about ₹1 lakh crore and became a lifeline for returning migrant workers, HT noted.",
  },
  {
    id: "hdb009",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "NREGA launch (Bandlapalli)",
    kind: "scheme",
    difficulty: "expert",
    year: 2006,
    asOf: "2026-09",
    govt: "UPA",
    question: "On 2 February 2006 Prime Minister Manmohan Singh launched the rural employment guarantee scheme from Bandlapalli village. Which district is it in?",
    options: ["Anantapur, Andhra Pradesh", "Rae Bareli, Uttar Pradesh", "Vaishali, Bihar", "Dungarpur, Rajasthan"],
    correctIndex: 0,
    explanation: "The Hindu, marking the scheme's 15th anniversary in 2021, reported that it was launched from Bandlapalli in Narpala mandal of Anantapur district by then Prime Minister Manmohan Singh on 2 February 2006. The dryland Rayalaseema village had since received ₹8.88 crore in wages and material spending.",
    sourceUrl: "https://www.thehindu.com/news/national/andhra-pradesh/nregs-transforms-bandlapalli-where-it-was-launched-in-2006/article33721578.ece",
    sourceLabel: "The Hindu — NREGS transforms Bandlapalli, where it was launched in 2006 (1 Feb 2021)",
    tags: ["distribution"],
    enactedBy: [{ name: "Manmohan Singh", role: "Prime Minister", party: "INC" }],
    outcome: "By 2021 ₹8.88 crore in wages and materials had reached Bandlapalli, and The Hindu found the formerly dryland village visibly transformed.",
  },
  {
    id: "hdb010",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "Old-age pension (IGNOAPS)",
    kind: "scheme",
    difficulty: "extreme",
    year: 2007,
    asOf: "2026-09",
    govt: "UPA",
    question: "The revamped Indira Gandhi National Old Age Pension Scheme, launched on 19 November 2007, covered which group?",
    options: ["Every citizen aged 60 and above", "All persons aged 65+ in BPL households", "Only destitute widows over 40", "Retired informal workers over 58"],
    correctIndex: 1,
    explanation: "Pranab Mukherjee's February 2009 interim budget said the revised scheme covered all persons aged 65 and above in BPL households and had reached 146 lakh people that year; pensions for BPL widows aged 40–64 and for disabled people followed. The central rates were last revised in 2012.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2009-10(I)/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Interim Budget Speech 2009-10, Pranab Mukherjee (16 Feb 2009)",
    sources: ["https://indianexpress.com/article/india/nsap-pension-inflation-impact-report-india-10685019/"],
    tags: ["distribution"],
    outcome: "146 lakh pensioners in 2008-09, per the interim budget. The Centre's rates were last revised in 2012; a ministry study in 2026 found inflation had cut their real value by about 45%.",
  },
  {
    id: "hdb011",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "NREGA: national rollout",
    kind: "scheme",
    difficulty: "extreme",
    year: 2008,
    asOf: "2026-09",
    govt: "UPA",
    question: "NREGA began in 200 districts in 2006-07 and added 130 more in 2007-08. From which financial year did it cover the whole country?",
    options: ["2010-11", "2012-13", "2014-15", "2008-09"],
    correctIndex: 3,
    explanation: "The Indian Express notes the scheme was launched in India's 200 most backward rural districts in 2006-07, extended to 130 more in 2007-08 and to the entire country from 2008-09. The February 2009 interim budget confirmed it had been extended to all districts.",
    sourceUrl: "https://indianexpress.com/article/india/100-to-125-days-mnrega-scheme-to-get-name-change-10417717/",
    sourceLabel: "The Indian Express — MNREGA is now Pujya Bapu Rural Employment Guarantee Act (13 Dec 2025)",
    sources: ["https://www.indiabudget.gov.in/budget_archive/ub2009-10(I)/bs/speecha.htm"],
    tags: ["distribution"],
    outcome: "In 2008-09, its first nationwide year, it generated 138.76 crore person-days of work for 3.51 crore households, per the February 2009 interim budget.",
  },
  {
    id: "hdb012",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Farm debt waiver 2008",
    kind: "spend",
    difficulty: "simple",
    year: 2008,
    asOf: "2026-09",
    govt: "UPA",
    question: "In his Budget 2008-09, P. Chidambaram announced a farm debt waiver and one-time settlement. What total value did he estimate for the relief?",
    options: ["₹6,000 crore", "₹60,000 crore", "₹1.6 lakh crore", "₹16,000 crore"],
    correctIndex: 1,
    explanation: "On 29 February 2008 Chidambaram offered marginal and small farmers (up to 2 hectares) a complete waiver of overdue loans, and other farmers a 25% rebate in a one-time settlement. He put the waiver at ₹50,000 crore and the settlement relief at ₹10,000 crore, for about 3 crore small and marginal and 1 crore other farmers.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2008-09/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2008-09, P. Chidambaram (29 Feb 2008)",
    sources: [
      "https://www.indiabudget.gov.in/budget_archive/ub2009-10(I)/bs/speecha.htm",
      "https://www.thehindu.com/business/budget/2008-a-populist-budget-and-largest-farm-loan-waiver/article69157749.ece",
      "https://www.thehindu.com/news/national/sloppy-loan-waiver-edges-out-deserving-farmers-cag/article4478433.ece",
      "https://www.thehindu.com/news/national/manmohan-promises-strict-action-against-irregularities-in-loan-waiver-scheme/article4481565.ece",
      "https://frontline.thehindu.com/cover-story/article30186427.ece",
      "https://indianexpress.com/article/political-pulse/exit-polls-2009-2014-2019-lok-sabha-elections-9364231/",
    ],
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "P. Chidambaram", role: "Union Finance Minister", party: "INC" }],
    outcome: "The scheme was implemented by 30 June 2008, as the budget had set out; a 2013 CAG audit found eligible farmers left out and ineligible ones paid.",
    otherSide: "After the 2013 CAG audit, the Prime Minister promised 'stringent' action against defaulters if irregularities were found, and the finance ministry told RBI and NABARD to take corrective measures.",
    poll: { label: "Lok Sabha 2009", month: "2009-04", gapDays: 412, result: "INC 206 seats; the Congress-led UPA returned with 262" },
  },
  {
    id: "hdb013",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Farm debt waiver 2008: reported reach",
    kind: "spend",
    difficulty: "extreme",
    year: 2009,
    asOf: "2026-09",
    govt: "UPA",
    question: "Pranab Mukherjee's interim budget of 16 February 2009, two months before the Lok Sabha polls, said the 2008 debt waiver and relief scheme had covered how many farmers?",
    options: ["36 lakh", "1.2 crore", "3.6 crore", "8 crore"],
    correctIndex: 2,
    explanation: "The interim budget said the scheme was implemented by 30 June 2008 as scheduled and, per early reports, waiver and relief totalled ₹65,300 crore for 3.6 crore farmers, more than the 2008 budget had estimated. The Hindu's report on the CAG's 2013 audit called it a ₹52,000-crore scheme.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2009-10(I)/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Interim Budget Speech 2009-10, Pranab Mukherjee (16 Feb 2009)",
    sources: [
      "https://www.thehindu.com/news/national/sloppy-loan-waiver-edges-out-deserving-farmers-cag/article4478433.ece",
      "https://frontline.thehindu.com/cover-story/article30186427.ece",
      "https://indianexpress.com/article/political-pulse/exit-polls-2009-2014-2019-lok-sabha-elections-9364231/",
    ],
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "Pranab Mukherjee", role: "Union Finance Minister", party: "INC" }],
    outcome: "Polling began 59 days later; Congress won 206 seats and the UPA returned to power. The cited sources make no claim that the waiver caused the result.",
    poll: { label: "Lok Sabha 2009", month: "2009-04", gapDays: 59, result: "INC 206 seats; the Congress-led UPA returned with 262" },
  },
  {
    id: "hdb014",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "MGNREGA: the Mahatma Gandhi name",
    kind: "scheme",
    difficulty: "extreme",
    year: 2009,
    asOf: "2026-09",
    govt: "UPA",
    question: "The UPA government renamed NREGA the Mahatma Gandhi National Rural Employment Guarantee Act with effect from which date?",
    options: ["26 January 2008", "15 August 2009", "2 October 2009", "30 January 2010"],
    correctIndex: 2,
    explanation: "The Indian Express notes the 2005 law was renamed by the UPA with effect from 2 October 2009, Gandhi Jayanti, the government saying the association with Gandhi would reinforce its thrust towards equity and inclusion. In December 2025 Parliament replaced the law with the VB-G RAM G Act after the Cabinet had also discussed a 'Pujya Bapu' name.",
    sourceUrl: "https://indianexpress.com/article/india/100-to-125-days-mnrega-scheme-to-get-name-change-10417717/",
    sourceLabel: "The Indian Express — MNREGA is now Pujya Bapu Rural Employment Guarantee Act (13 Dec 2025)",
    sources: [
      "https://www.manoramayearbook.in/current-affairs/india/2026/07/01/vb-g-ram-g-act-upsc-explained.html",
      "https://www.hindustantimes.com/india-news/parliament-passes-new-vb-g-ram-g-bill-to-replace-mgnrega-amid-opposition-walkout-101766086029025.html",
    ],
    tags: ["distribution"],
    outcome: "The Gandhi name stayed until the VB-G RAM G Act, passed in December 2025, came into force on 1 July 2026 and replaced the law.",
  },

  // ───────────────────────────── 2010–2014 ─────────────────────────────
  {
    id: "hdb015",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "IGMSY maternity benefit",
    kind: "scheme",
    difficulty: "extreme",
    year: 2010,
    asOf: "2026-09",
    govt: "UPA",
    question: "The UPA's Indira Gandhi Matritva Sahyog Yojana, begun in October 2010, paid pregnant and lactating women ₹4,000. In how many pilot districts did it run?",
    options: ["53", "200", "640", "12"],
    correctIndex: 0,
    explanation: "The Indian Express explains IGMSY began in October 2010 as a pilot in 53 districts, paying women aged 19 and above ₹4,000 for up to two living children. After the 2013 food law set a higher minimum maternity benefit, the IGMSY amount was raised on 27 September 2013 — but still only in those 53 districts.",
    sourceUrl: "https://indianexpress.com/article/explained/maternity-benefit-scheme-what-pm-modi-said-where-things-stand-now-4459269/",
    sourceLabel: "The Indian Express — Maternity benefit scheme: what PM Modi said, where things stand now (5 Jan 2017)",
    tags: ["distribution"],
    outcome: "In 2015 the WCD ministry told the Supreme Court it would widen the scheme to 200 districts in 2016-17; the Indian Express found that commitment unmet in January 2017.",
  },
  {
    id: "hdb016",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "Janani Suraksha Yojana: Lancet evaluation",
    kind: "scheme",
    difficulty: "extreme",
    year: 2010,
    asOf: "2026-09",
    govt: "UPA",
    question: "A 2010 Lancet evaluation of Janani Suraksha Yojana found that in 2007-08 the share of women giving birth who got JSY cash varied by state from under 5% to what?",
    options: ["18%", "44%", "71%", "93%"],
    correctIndex: 1,
    explanation: "The IHME team (Lim and others) used district household surveys from 2002-04 and 2007-09. JSY raised antenatal care and births in facilities, and payment was associated with about 3.7 fewer perinatal deaths per 1,000 pregnancies — but the poorest and least-educated women did not always have the best odds of being paid.",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/20569841/",
    sourceLabel: "The Lancet (PubMed abstract) — India's Janani Suraksha Yojana: an impact evaluation, Lim et al. (5 Jun 2010)",
    tags: ["distribution"],
    outcome: "The authors called the results encouraging but urged better targeting of the poorest women and attention to the quality of obstetric care in health facilities.",
  },
  {
    id: "hdb017",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "LPG cash transfer (DBTL, 2013)",
    kind: "scheme",
    difficulty: "expert",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "The UPA's transfer of the LPG subsidy straight into bank accounts was to start on 1 June 2013 in 18 districts. How much was a consumer to get for each refill booked?",
    options: ["₹200", "₹1,000", "₹150", "₹435"],
    correctIndex: 3,
    explanation: "Oil Minister M. Veerappa Moily was to launch it at Tumkur, Karnataka. Consumers in the chosen districts, which had high Aadhaar coverage, were to get ₹435 per refill, for up to nine subsidised cylinders a year; launches in Mysore and Mandi were put off by a month because of bypolls. The government expected annual savings of ₹8,000–10,000 crore.",
    sourceUrl: "https://www.thehindu.com/business/Economy/lpg-subsidy-to-be-credited-directly-in-bank-accounts-from-june-1-in-18-districts/article4762963.ece",
    sourceLabel: "The Hindu — LPG subsidy to be credited directly in bank accounts from June 1 in 18 districts (29 May 2013)",
    sources: [
      "https://www.thehindu.com/news/national/Government-launches-modified-DBTL-scheme-in-54-districts/article60099500.ece",
      "https://www.indiabudget.gov.in/budget2014-2015(I)/ub2014-15/bs/bs.pdf",
      "https://energy.economictimes.indiatimes.com/news/pahal-enters-guinness-book-of-world-records-as-the-largest-cash-transfer-program/48470924",
    ],
    tags: ["distribution"],
    enactedBy: [{ name: "M. Veerappa Moily", role: "Union Petroleum & Natural Gas Minister", party: "INC" }],
    outcome: "Launched on 1 June 2013, it reached 291 districts. By the February 2014 interim budget ₹3,370 crore had gone to 2.1 crore LPG consumers, but the transfer was on hold; the NDA relaunched it as PAHAL in November 2014.",
  },
  {
    id: "hdb018",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "National Food Security Act: passage",
    kind: "scheme",
    difficulty: "expert",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "The UPA promulgated a food security ordinance on 5 July 2013, a month before Parliament met. When the Lok Sabha passed the Bill on 26 August 2013, which party alone opposed it?",
    options: ["BJP", "CPI(M)", "AIADMK", "Samajwadi Party"],
    correctIndex: 2,
    explanation: "Frontline reported that no party except the AIADMK opposed the Bill, though many moved amendments and the BJP and the Left pressed for universal coverage. Opposition MPs questioned the need for an ordinance, and SP leader Mulayam Singh Yadav said it was moved with the 2014 polls in mind. Minister of State for food K.V. Thomas conceded 18 states would get less grain but promised their past offtake would be protected.",
    sourceUrl: "https://frontline.thehindu.com/the-nation/food-for-security/article5085111.ece",
    sourceLabel: "Frontline — Food for security (4 Sep 2013)",
    sources: [
      "https://www.thehindu.com/news/national/lok-sabha-passes-food-security-bill/article5062126.ece",
      "https://indianexpress.com/article/explained/maternity-benefit-scheme-what-pm-modi-said-where-things-stand-now-4459269/",
      "https://indianexpress.com/article/political-pulse/india-goes-to-poll-in-9-phases-from-april-7-to-may-12-vote-count-on-may-16/",
      "https://www.dw.com/en/india-election-whats-behind-the-bjps-poll-upset/a-69277403",
    ],
    people: ["Mulayam Singh Yadav", "K.V. Thomas", "Sonia Gandhi"],
    status: "Political remarks in the Lok Sabha debate (Aug 2013); no allegation of wrongdoing. The Bill passed and the Act took effect on 10 Sep 2013.",
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "K.V. Thomas", role: "Minister of State, Consumer Affairs, Food & Public Distribution", party: "INC" }],
    outcome: "The law entitled up to 75% of rural and 50% of urban people (67% overall) to 5 kg of subsidised grain a month. At the 2014 polls, 276 days after the ordinance, Congress fell to 44 seats.",
    otherSide: "Sonia Gandhi told the Lok Sabha the Bill fulfilled her party's promise to 'wipe out hunger and malnutrition', calling it a 'big message' about India's capacity to feed its citizens (The Hindu).",
    poll: { label: "Lok Sabha 2014", month: "2014-04", gapDays: 276, result: "BJP 282 of 543; INC 44" },
  },
  {
    id: "hdb019",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "National Food Security Act: prices",
    kind: "scheme",
    difficulty: "simple",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "The 2013 food security law guaranteed each eligible person 5 kg of grain a month. At what prices per kg for rice, wheat and coarse grains?",
    options: ["₹3, ₹2 and ₹1", "₹5, ₹4 and ₹3", "₹2, ₹3 and free", "₹1 each for all three"],
    correctIndex: 0,
    explanation: "Frontline noted the Bill fixed 5 kg a month at ₹3 (rice), ₹2 (wheat) and ₹1 (coarse grains), for three years before review. From 1 January 2023 the NDA made the entitlement free under PMGKAY, and in November 2023 extended free grain for five years from January 2024.",
    sourceUrl: "https://frontline.thehindu.com/the-nation/food-for-security/article5085111.ece",
    sourceLabel: "Frontline — Food for security (4 Sep 2013)",
    sources: ["https://www.thehindu.com/news/national/distribution-of-5-kg-foodgrains-to-poor-under-pmgkay-extended-for-5-years-anurag-thakur/article67586389.ece"],
    tags: ["distribution"],
    outcome: "The ₹3/₹2/₹1 prices held until grain was made free from January 2023; the Centre put the five-year free-grain extension from 2024 at about ₹11.80 lakh crore.",
  },
  {
    id: "hdb020",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "NFSA maternity entitlement",
    kind: "scheme",
    difficulty: "expert",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "Section 4(b) of the 2013 food security law entitles every pregnant and lactating mother to a maternity benefit of at least how much?",
    options: ["₹4,000", "₹5,000", "₹12,000", "₹6,000"],
    correctIndex: 3,
    explanation: "The Indian Express points out that the Act, in force from 10 September 2013, promises 'not less than Rupees six thousand'. The NDA's PMMVY pays ₹5,000 for a first child (₹6,000 for a second child if a girl); the WCD ministry says that with Janani Suraksha Yojana a woman gets ₹6,000 on average.",
    sourceUrl: "https://indianexpress.com/article/explained/maternity-benefit-scheme-what-pm-modi-said-where-things-stand-now-4459269/",
    sourceLabel: "The Indian Express — Maternity benefit scheme: what PM Modi said, where things stand now (5 Jan 2017)",
    sources: ["https://www.pib.gov.in/PressReleasePage.aspx?PRID=2302092"],
    tags: ["distribution"],
    outcome: "Universal coverage lagged: by 2015 the benefit ran only in 53 pilot districts, and PUCL went to the Supreme Court over flawed implementation of the food law.",
  },
  {
    id: "hdb021",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Farm debt waiver 2008: CAG audit",
    kind: "scheme",
    difficulty: "extreme",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "CAG's 2013 audit of the 2008 farm debt waiver found a private bank had been reimbursed ₹164.60 crore, against the scheme's rules, for loans it had made to whom?",
    options: ["Cooperative sugar mills", "Microfinance institutions", "Fertiliser dealers", "Farm-produce exporters"],
    correctIndex: 1,
    explanation: "The CAG also found eligible small farmers left out and ineligible borrowers paid, prima facie evidence of tampering with and overwriting of records, and no record of how many farmers got fresh loans, the waiver's stated purpose. The BJP sought a CBI probe; the finance ministry had asked RBI and NABARD to take immediate corrective measures.",
    sourceUrl: "https://www.thehindu.com/news/national/sloppy-loan-waiver-edges-out-deserving-farmers-cag/article4478433.ece",
    sourceLabel: "The Hindu — Sloppy loan waiver edges out deserving farmers: CAG (5 Mar 2013)",
    sources: ["https://www.thehindu.com/news/national/manmohan-promises-strict-action-against-irregularities-in-loan-waiver-scheme/article4481565.ece"],
    status: "CAG audit findings against lending institutions (report tabled 5 Mar 2013); no person or bank is named in this item. The finance ministry asked RBI and NABARD to take corrective measures.",
    tags: ["distribution"],
    outcome: "The CAG called monitoring 'deficient': RBI and NABARD relied on lenders' own data without checking it. Of 9,334 accounts test-checked, 13.46% were eligible but had been left out.",
    otherSide: "The PM told the Rajya Sabha on 6 Mar 2013 the report should go to the PAC and promised 'stringent' action against defaulters if irregularities were found; RBI and NABARD had been told to take corrective steps.",
  },
  {
    id: "hdb022",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Education & Exams",
    subtopic: "Education-loan interest relief (2014)",
    kind: "spend",
    difficulty: "extreme",
    year: 2014,
    asOf: "2026-09",
    govt: "UPA",
    question: "Weeks before the 2014 polls, P. Chidambaram's interim budget took over unpaid interest on pre-April 2009 education loans. About how many student borrowers did he say would benefit?",
    options: ["90,000", "90 lakh", "9 lakh", "2.6 crore"],
    correctIndex: 2,
    explanation: "On 17 February 2014 Chidambaram said the Centre would take over interest outstanding on 31 December 2013 on education loans taken up to 31 March 2009, helping nearly 9 lakh borrowers to the tune of about ₹2,600 crore, to be paid to Canara Bank that year. The same interim budget accepted One Rank One Pension in principle with ₹500 crore.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2014-2015(I)/ub2014-15/bs/bs.pdf",
    sourceLabel: "indiabudget.gov.in — Interim Budget Speech 2014-15, P. Chidambaram (17 Feb 2014)",
    sources: [
      "https://indianexpress.com/article/political-pulse/india-goes-to-poll-in-9-phases-from-april-7-to-may-12-vote-count-on-may-16/",
      "https://www.dw.com/en/india-election-whats-behind-the-bjps-poll-upset/a-69277403",
    ],
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "P. Chidambaram", role: "Union Finance Minister", party: "INC" }],
    outcome: "Polling began 49 days later; the UPA lost office and Congress won 44 seats.",
    poll: { label: "Lok Sabha 2014", month: "2014-04", gapDays: 49, result: "BJP 282 of 543; INC 44" },
  },

  // ───────────────────────────── 2015–2019 ─────────────────────────────
  {
    id: "hdb023",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PAHAL (LPG DBT)",
    kind: "scheme",
    difficulty: "simple",
    year: 2015,
    asOf: "2026-09",
    govt: "NDA",
    question: "PAHAL, the LPG subsidy transfer relaunched in November 2014, entered Guinness World Records in August 2015 as what?",
    options: ["Largest cash transfer programme by households", "Fastest bank-account opening drive", "Largest cooking-gas distributor", "Biggest single-day fuel subsidy payout"],
    correctIndex: 0,
    explanation: "The government said PAHAL began in 54 districts on 15 November 2014 and nationwide on 1 January 2015, and that 13.9 crore LPG consumers had joined by 13 August 2015, when Guinness recognised it as the largest cash transfer programme (households). The ministry said it helped block 3.34 crore duplicate, fake or inactive connections.",
    sourceUrl: "https://energy.economictimes.indiatimes.com/news/pahal-enters-guinness-book-of-world-records-as-the-largest-cash-transfer-program/48470924",
    sourceLabel: "ET EnergyWorld — 'Pahal' enters Guinness Book of World Records as the largest cash transfer program (13 Aug 2015)",
    sources: [
      "https://www.thehindu.com/news/national/Government-launches-modified-DBTL-scheme-in-54-districts/article60099500.ece",
      "https://energy.economictimes.indiatimes.com/news/oil-and-gas/dharmendra-pradhan-presents-pahals-guinness-world-record-certificate-to-pm-modi/50054171",
      "https://www.thehindu.com/news/national/Govt.-defends-LPG-subsidy-calculations/article14499390.ece",
    ],
    tags: ["distribution"],
    enactedBy: [{ name: "Dharmendra Pradhan", role: "Union Petroleum & Natural Gas Minister", party: "BJP" }],
    outcome: "A 2016 CAG audit found most of the drop in LPG subsidy spending came from lower global prices rather than PAHAL; the ministry defended its savings estimates.",
    otherSide: "Answering the CAG's concerns, the government said PAHAL let it block 3.34 crore duplicate, fake or inactive connections, saving ₹21,261 crore over 2014-16 (The Hindu, Jul 2016).",
  },
  {
    id: "hdb024",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "Atal Pension Yojana co-contribution",
    kind: "scheme",
    difficulty: "extreme",
    year: 2015,
    asOf: "2026-09",
    govt: "NDA",
    question: "To draw people into Atal Pension Yojana, Budget 2015-16 promised the Centre would pay half a new subscriber's contribution for five years, up to what yearly cap?",
    options: ["₹500", "₹2,000", "₹5,000", "₹1,000"],
    correctIndex: 3,
    explanation: "Arun Jaitley's 28 February 2015 budget said the government would contribute 50% of the premium, limited to ₹1,000 a year for five years, for new accounts opened before 31 December 2015. APY gives a guaranteed pension of ₹1,000–₹5,000 a month from age 60, depending on contributions.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2015-2016/ub2015-16/bs/bs.pdf",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2015-16, Arun Jaitley (28 Feb 2015)",
    sources: ["https://ddnews.gov.in/en/atal-pension-yojana-crosses-9-crore-enrolments-records-highest-annual-subscriber-addition/"],
    tags: ["distribution"],
    enactedBy: [{ name: "Arun Jaitley", role: "Union Finance Minister", party: "BJP" }],
    outcome: "Gross enrolments crossed 9 crore by 21 April 2026, with a record 1.35 crore added in 2025-26, DD News reported.",
  },
  {
    id: "hdb025",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PAHAL: CAG audit",
    kind: "spend",
    difficulty: "extreme",
    year: 2016,
    asOf: "2026-09",
    govt: "NDA",
    question: "CAG found LPG subsidy spending in April–December 2015 was ₹23,316 crore lower than a year earlier. How much of that did it attribute to consumers buying fewer subsidised cylinders?",
    options: ["About ₹1,764 crore", "About ₹9,211 crore", "About ₹14,818 crore", "About ₹21,552 crore"],
    correctIndex: 0,
    explanation: "The CAG report, tabled in Parliament in August 2016, credited ₹1,763.93 crore to lower offtake under PAHAL and 'Give It Up' and ₹21,552.28 crore to lower subsidy rates after crude prices fell. The government had claimed about ₹22,000 crore in savings; the petroleum ministry said blocking 3.34 crore duplicate or inactive connections saved ₹21,261 crore over two years.",
    sourceUrl: "https://www.thehindu.com/news/national/LPG-subsidy-savings-largely-due-to-falling-oil-prices-CAG/article60481131.ece",
    sourceLabel: "The Hindu — LPG subsidy savings largely due to falling oil prices: CAG (13 Aug 2016)",
    sources: ["https://www.thehindu.com/news/national/Govt.-defends-LPG-subsidy-calculations/article14499390.ece"],
    tags: ["distribution"],
    outcome: "CAG said the ministry's ₹9,211 crore estimate of PAHAL savings for 2015-16 assumed 12 cylinders per blocked consumer; at the 2014-15 national average of 6.27 cylinders it fell to about ₹4,813 crore.",
    otherSide: "The government defended its figures, saying blocking 3.34 crore bogus or inactive connections saved ₹21,261 crore over two years and citing a 39.3% rise in commercial LPG sales in 2015-16.",
  },
  {
    id: "hdb026",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PM Ujjwala Yojana launch (Ballia)",
    kind: "scheme",
    difficulty: "expert",
    year: 2016,
    asOf: "2026-09",
    govt: "NDA",
    question: "PM Modi launched Ujjwala, the ₹8,000-crore free LPG connection scheme for 5 crore BPL families, on 1 May 2016 in which Uttar Pradesh district, under a year before the state's polls?",
    options: ["Varanasi", "Gorakhpur", "Ballia", "Mahoba"],
    correctIndex: 2,
    explanation: "India Today reported the launch in Ballia on Labour Day, with Petroleum Minister Dharmendra Pradhan present; the BJP's state in-charge spoke of repeating its 2014 showing in the 2017 Assembly polls. Modi said the visit was not to sound the poll bugle. Ujjwala 2.0 was later launched from Mahoba, also in UP.",
    sourceUrl: "https://www.indiatoday.in/india/uttar-pradesh/story/bjp-kickstarts-its-mission-up-with-pm-modis-ballia-visit-321006-2016-05-01",
    sourceLabel: "India Today — BJP kick-starts its Mission UP with PM Modi's Ballia visit (1 May 2016)",
    sources: [
      "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1744400",
      "https://www.thehindu.com/elections/uttar-pradesh-2017/bjp-rides-modi-wave-to-win-big-in-up/article17449593.ece",
      "https://www.rediff.com/news/report/up-election-voting-for-first-phase-of-up-polls-begins/20170211.htm",
    ],
    tags: ["distribution", "pre-election"],
    enactedBy: [
      { name: "Narendra Modi", role: "Prime Minister", party: "BJP" },
      { name: "Dharmendra Pradhan", role: "Union Petroleum & Natural Gas Minister", party: "BJP" },
    ],
    outcome: "Phase one gave free connections to 8 crore families (PIB, 2021). In the UP polls that began 286 days after the launch the BJP won 312 of 403 seats; no cited study links the result to Ujjwala.",
    poll: { label: "UP Assembly 2017", month: "2017-02", gapDays: 286, result: "BJP won 312 of 403 seats" },
  },
  {
    id: "hdb027",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "PMMVY: the announcement",
    kind: "scheme",
    difficulty: "simple",
    year: 2016,
    asOf: "2026-09",
    govt: "NDA",
    question: "In which address did PM Narendra Modi promise ₹6,000 to pregnant women across India, the pledge that became the Pradhan Mantri Matru Vandana Yojana?",
    options: ["His 2016 Independence Day speech", "His New Year's Eve address, 31 Dec 2016", "The Union Budget speech, Feb 2017", "A Mann Ki Baat radio episode"],
    correctIndex: 1,
    explanation: "In his 31 December 2016 address the PM said pregnant women would get ₹6,000 for hospital stay, vaccination and nutrition. The Indian Express noted a similar UPA pilot, IGMSY, already ran in 53 districts and that the 2013 food law already required a maternity benefit. PMMVY runs nationwide from 1 January 2017, paying ₹5,000 for a first child.",
    sourceUrl: "https://indianexpress.com/article/explained/maternity-benefit-scheme-what-pm-modi-said-where-things-stand-now-4459269/",
    sourceLabel: "The Indian Express — Maternity benefit scheme: what PM Modi said, where things stand now (5 Jan 2017)",
    sources: ["https://www.pib.gov.in/PressReleasePage.aspx?PRID=2302092"],
    tags: ["distribution"],
    enactedBy: [
      { name: "Narendra Modi", role: "Prime Minister", party: "BJP" },
      { name: "Maneka Gandhi", role: "Union Women & Child Development Minister", party: "BJP" },
    ],
    outcome: "The WCD ministry first estimated 51.70 lakh beneficiaries a year and ₹7,932 crore till 2019, with states bearing 40% of the cost.",
  },
  {
    id: "hdb028",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PM-KISAN: the interim budget",
    kind: "spend",
    difficulty: "expert",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "Announcing PM-KISAN in the 1 February 2019 interim budget, Piyush Goyal made the ₹6,000-a-year farm income support effective retrospectively from which date?",
    options: ["1 April 2018", "1 January 2019", "1 April 2019", "1 December 2018"],
    correctIndex: 3,
    explanation: "Goyal's speech said support for landholding families with up to 2 hectares would run from 1 December 2018, with the first ₹2,000 instalment, for the period up to 31 March 2019, paid in that financial year. He provided ₹20,000 crore in the 2018-19 revised estimates and ₹75,000 crore for 2019-20, for about 12 crore families.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2019-20(I)/ub2019-20/bs/bs.pdf",
    sourceLabel: "indiabudget.gov.in — Interim Budget Speech 2019-20, Piyush Goyal (1 Feb 2019)",
    sources: [
      "https://www.hindustantimes.com/india-news/lok-sabha-elections-2019-pm-modi-launches-direct-cash-benefit-scheme-for-farmers/story-pMWZuh8iPInFUJFjZXiWqI.html",
      "https://www.thehindu.com/news/national/general-election-2019-full-schedule-with-phases-dates-and-state-wise-list-of-seats/article26487747.ece",
      "https://www.dw.com/en/india-election-whats-behind-the-bjps-poll-upset/a-69277403",
    ],
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "Piyush Goyal", role: "Union Finance Minister (interim charge)", party: "BJP" }],
    outcome: "The first instalment went out on 24 February 2019. Polling began 69 days after the budget and the BJP won 303 seats; the cited sources make no causal claim.",
    poll: { label: "Lok Sabha 2019", month: "2019-04", gapDays: 69, result: "BJP 303 of 543; INC 52" },
  },
  {
    id: "hdb029",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PM-KISAN: first instalment",
    kind: "scheme",
    difficulty: "simple",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "PM Modi paid PM-KISAN's first ₹2,000 instalment to about 1.01 crore farmers on 24 February 2019 at an event in which city?",
    options: ["Varanasi", "Gorakhpur", "Lucknow", "Ranchi"],
    correctIndex: 1,
    explanation: "At Gorakhpur, Modi contrasted the scheme with loan waivers he called 'lollypops' and said it was not just an election promise. Congress leader P. Chidambaram called it a 'bribe for votes' and said the Election Commission could not stop it; the Model Code of Conduct applies only once polls are announced, which came on 10 March 2019.",
    sourceUrl: "https://www.hindustantimes.com/india-news/lok-sabha-elections-2019-pm-modi-launches-direct-cash-benefit-scheme-for-farmers/story-pMWZuh8iPInFUJFjZXiWqI.html",
    sourceLabel: "Hindustan Times — PM Modi launches direct cash benefit scheme for farmers (24 Feb 2019)",
    sources: [
      "https://www.newindianexpress.com/india/2019/Feb/24/pm-modi-did-not-do-anything-for-farmers-remembering-them-before-polls-congress-on-pm-kisan-scheme-1943181.html",
      "https://scroll.in/latest/915713/2019-general-elections-voting-to-be-held-in-seven-phases-to-start-on-april-11",
      "https://www.dw.com/en/india-election-whats-behind-the-bjps-poll-upset/a-69277403",
    ],
    people: ["Narendra Modi", "P. Chidambaram"],
    status: "Political criticism only (Feb 2019), not an allegation before any authority: no complaint, case or ECI action appears in the cited reports. The first instalment was paid before the Model Code took effect on 10 Mar 2019.",
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "Polling began 46 days after the first payment and the BJP won 303 seats. PM-KISAN payments continued after the election; the cited sources make no causal claim.",
    otherSide: "Modi said PM-KISAN was not just an 'election promise' and told farmers the money would not be taken back; the first instalment was paid before the Model Code took effect.",
    poll: { label: "Lok Sabha 2019", month: "2019-04", gapDays: 46, result: "BJP 303 of 543; INC 52" },
  },
  {
    id: "hdb030",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PM Shram Yogi Maandhan",
    kind: "scheme",
    difficulty: "expert",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "Piyush Goyal's 2019 interim budget said PM Shram Yogi Maandhan, a ₹3,000-a-month pension for informal workers, would reach how many workers within five years?",
    options: ["At least 10 crore", "At least 1 crore", "At least 50 lakh", "At least 25 crore"],
    correctIndex: 0,
    explanation: "Workers earning up to ₹15,000 a month pay ₹55–₹200 a month, matched by the Centre, for a ₹3,000 pension from 60. Goyal called it potentially one of the world's largest pension schemes and allocated ₹500 crore. By 29 July 2026 just over 54 lakh had enrolled, the labour ministry told the Lok Sabha.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2019-20(I)/ub2019-20/bs/bs.pdf",
    sourceLabel: "indiabudget.gov.in — Interim Budget Speech 2019-20, Piyush Goyal (1 Feb 2019)",
    sources: [
      "https://www.thehindubusinessline.com/news/national/pm-sym-pension-scheme-women-outnumber-men-account-for-over-53-of-subscribers/article71301476.ece",
      "https://www.thehindu.com/news/national/general-election-2019-full-schedule-with-phases-dates-and-state-wise-list-of-seats/article26487747.ece",
      "https://www.dw.com/en/india-election-whats-behind-the-bjps-poll-upset/a-69277403",
    ],
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "Piyush Goyal", role: "Union Finance Minister (interim charge)", party: "BJP" }],
    outcome: "54 lakh enrolled by July 2026 (53.1% women); the Centre's matching contributions totalled ₹2,011.01 crore. Pensions start no earlier than February 2039.",
    poll: { label: "Lok Sabha 2019", month: "2019-04", gapDays: 69, result: "BJP 303 of 543; INC 52" },
  },
  {
    id: "hdb031",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PM Kisan Maandhan",
    kind: "scheme",
    difficulty: "simple",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "Launched in Ranchi on 12 September 2019, PM Kisan Maandhan promises enrolled small and marginal farmers what from the age of 60?",
    options: ["₹6,000 a year income support", "₹10,000 a month pension", "₹3,000 a month pension", "A one-time ₹1 lakh payout"],
    correctIndex: 2,
    explanation: "Farmers aged 18–40 with up to 2 hectares pay ₹55–₹200 a month, matched by the Centre, for a ₹3,000 monthly pension from 60. The Times of India reported a three-year outlay of ₹10,774 crore at the launch; PIB's seven-year review counted 24,96,252 enrolments by 6 February 2026, led by Haryana with 5.75 lakh.",
    sourceUrl: "https://timesofindia.indiatimes.com/business/india-business/pm-launches-kisan-maandhan-yojana-pension-scheme-for-traders-self-employed-things-to-know/articleshow/71095633.cms",
    sourceLabel: "The Times of India — PM launches 'Kisan Maan-dhan Yojana', pension scheme for traders & self-employed (12 Sep 2019)",
    sources: ["https://www.pib.gov.in/PressNoteDetails.aspx?id=159959&NoteId=159959&ModuleId=3"],
    tags: ["distribution"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "Against a ₹10,774-crore three-year outlay, ₹540.66 crore had been utilised and 24.96 lakh farmers enrolled by February 2026, per PIB.",
  },

  // ───────────────────────────── 2020–2026 ─────────────────────────────
  {
    id: "hdb032",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PMGKY cash to women (Jan Dhan)",
    kind: "scheme",
    difficulty: "extreme",
    year: 2020,
    asOf: "2026-09",
    govt: "NDA",
    question: "Under the March 2020 Garib Kalyan package, women Jan Dhan account holders got ₹500 a month for three months. How much was credited in all, per the government in Parliament?",
    options: ["About ₹3,097 crore", "About ₹10,029 crore", "About ₹1.7 lakh crore", "About ₹30,975 crore"],
    correctIndex: 3,
    explanation: "Finance Minister Nirmala Sitharaman announced the transfer on 26 March 2020 in the ₹1.7 lakh crore package. The government told Parliament in March 2021 that ₹30,975 crore reached 20.65 crore women over three instalments, and that 8.72 crore (44%) had used their accounts after the first instalment.",
    sourceUrl: "https://factly.in/data-what-is-the-state-wise-coverage-of-women-pmjdy-account-holders-under-pmgky/",
    sourceLabel: "Factly — Data: state-wise coverage of women PMJDY account holders under PMGKY (23 Sep 2021)",
    sources: ["https://www.livemint.com/news/india/woman-jan-dhan-account-holders-to-get-rs-500-per-month-for-next-3-months-11585210124179.html"],
    tags: ["distribution", "relief"],
    enactedBy: [{ name: "Nirmala Sitharaman", role: "Union Finance Minister", party: "BJP" }],
    outcome: "UP (3.18 crore), Bihar (2.33 crore) and West Bengal (1.9 crore) had the most recipients; coverage of women account holders ranged from over 95% in Karnataka to 35.5% in Mizoram, Factly found.",
  },
  {
    id: "hdb033",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "NSAP in the pandemic year",
    kind: "spend",
    difficulty: "extreme",
    year: 2020,
    asOf: "2026-09",
    govt: "NDA",
    question: "The National Social Assistance Programme was budgeted ₹9,197 crore for 2020-21. What did the Centre actually spend through it in that pandemic year?",
    options: ["₹8,152 crore", "₹18,394 crore", "₹42,443 crore", "₹96,000 crore"],
    correctIndex: 2,
    explanation: "PRS's analysis of the rural development budget shows NSAP actuals of ₹42,443 crore in 2020-21 — 461% of the budget estimate — because special Covid transfers to women, old people and widows were routed through it. In the other years from 2015-16 to 2021-22, utilisation ran between 84% and 95%.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2025/DFG_Analysis_2025-26_Rural_Development.pdf",
    sourceLabel: "PRS Legislative Research — Demand for Grants 2025-26 Analysis: Rural Development (4 Feb 2025)",
    tags: ["distribution", "relief"],
    outcome: "Spending fell back to ₹8,152 crore in 2021-22; NSAP's 2025-26 allocation is ₹9,652 crore, of which ₹6,646 crore is for old-age pensions.",
  },
  {
    id: "hdb034",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "Ujjwala 2.0 (Mahoba)",
    kind: "scheme",
    difficulty: "expert",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "Launching Ujjwala 2.0 from Mahoba, Uttar Pradesh, on 10 August 2021, PM Modi said migrant workers could now get a free LPG connection with what?",
    options: ["A self-declaration of their address", "A BPL ration card only", "An employer's certificate", "A domicile certificate from home"],
    correctIndex: 0,
    explanation: "PIB's account of the launch says migrants who struggled to produce address proof would only need to self-declare it. The PM, speaking by video conference, said phase one had given free connections to 8 crore families and that the first phase had also been launched from Uttar Pradesh, in 2016.",
    sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1744400",
    sourceLabel: "PIB — PM launches Ujjwala 2.0 from Mahoba, Uttar Pradesh (10 Aug 2021)",
    sources: [
      "https://indianexpress.com/elections/assembly-election-dates-full-schedule-punjab-uttar-pradesh-uttarakhand-goa-manipur-7713017/",
      "https://indianexpress.com/article/political-pulse/yogi-adityanath-uttar-predash-polls-2027-sp-congress-seats-10867666/",
    ],
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "In the UP Assembly polls that began 184 days later, the BJP won 255 of 403 seats and the SP 111; the cited sources make no causal claim about Ujjwala.",
    poll: { label: "UP Assembly 2022", month: "2022-02", gapDays: 184, result: "BJP won 255 of 403 seats; SP 111" },
  },
  {
    id: "hdb035",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PMGKAY free grain: five-year extension",
    kind: "scheme",
    difficulty: "simple",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "Where did PM Modi announce, on 4 November 2023, that free grain for about 80 crore people would be extended for five more years?",
    options: ["In a Cabinet briefing in New Delhi", "In his Independence Day speech", "In the Union Budget speech", "At an election rally in Durg, Chhattisgarh"],
    correctIndex: 3,
    explanation: "Modi made the announcement at rallies in Durg and Ratlam, three days before Chhattisgarh's first phase. Congress's Jairam Ramesh called it a 'blatant violation' of the Model Code and asked the ECI to act; Modi replied he would accept any punishment. The Cabinet formally approved the extension on 29 November, at about ₹11.80 lakh crore over five years.",
    sourceUrl: "https://www.hindustantimes.com/india-news/freeration-scheme-will-be-extended-for-next-5-years-pm-modi-in-poll-bound-chhattisgarh-madhya-pradesh-101699099169144.html",
    sourceLabel: "Hindustan Times — Free-ration scheme will be extended for next 5 years: PM Modi in poll-bound Chhattisgarh, MP (4 Nov 2023)",
    sources: [
      "https://www.hindustantimes.com/india-news/do-whatever-you-want-pm-modi-hits-back-at-congress-on-poll-code-violation-claim-101699424770854.html",
      "https://www.thehindu.com/news/national/distribution-of-5-kg-foodgrains-to-poor-under-pmgkay-extended-for-5-years-anurag-thakur/article67586389.ece",
      "https://theprint.in/elections/how-bjp-snatched-chhattisgarhs-tribal-belts-bastar-surguja-from-congress/1871726/",
      "https://theprint.in/india/bjp-retains-madhya-pradesh-with-two-thirds-majority-wins-163-of-230-assembly-seats/1870542/",
    ],
    people: ["Narendra Modi", "Jairam Ramesh"],
    status: "Alleged Model Code violation, raised by Congress's Jairam Ramesh (Nov 2023); no ECI finding on it appears in reporting checked to Sep 2026. The Cabinet approved the extension on 29 Nov 2023.",
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "The BJP won Chhattisgarh with 54 of 90 seats (Congress 35) and Madhya Pradesh with 163 of 230; no cited study attributes the results to the announcement.",
    otherSide: "Modi told a Damoh rally: 'Do whatever you want, I will accept whatever punishment comes in my way', vowing not to leave his work for the poor; no ECI finding on the complaint was reported.",
    poll: { label: "Chhattisgarh Assembly 2023", month: "2023-11", gapDays: 3, result: "BJP won 54 of 90 seats; INC 35" },
  },
  {
    id: "hdb036",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "Ujjwala LPG subsidy (2023)",
    kind: "spend",
    difficulty: "simple",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "On 4 October 2023, five days before the ECI announced polls in five states, the Cabinet raised the targeted LPG subsidy for Ujjwala households from ₹200 to what per cylinder?",
    options: ["₹250", "₹300", "₹400", "₹500"],
    correctIndex: 1,
    explanation: "I&B Minister Anurag Thakur announced the rise from ₹200 to ₹300 per cylinder. In late August the Cabinet had cut the LPG price by ₹200 for all consumers, which Thakur announced 'on the occasion of Rakshabandhan and Onam' as a gift from the PM to women. The ECI announced the Assembly schedule on 9 October; voting ran from 7 to 30 November.",
    sourceUrl: "https://newsonair.gov.in/union-cabinet-approves-govts-decision-to-increase-lpg-subsidy-per-cylinder-by-rs-100-for-ujjwala-yojana-beneficiaries-ib-minister-anurag-singh-thakur/",
    sourceLabel: "All India Radio News — Cabinet raises LPG subsidy per cylinder by ₹100 for Ujjwala beneficiaries (4 Oct 2023)",
    sources: [
      "https://timesofindia.indiatimes.com/india/union-cabinet-approves-cutting-lpg-prices-under-ujjwala-scheme-by-rs-200-per-cylinder-sources/articleshow/103170266.cms",
      "https://www.thehindu.com/news/national/election-commission-announces-dates-for-assembly-polls-in-5-states/article67400079.ece",
      "https://indianexpress.com/article/india/pm-modi-international-womens-day-lpg-cylinder-price-cut-9202370/",
      "https://frontline.thehindu.com/news/bjp-3-1-assembly-election-results-in-madhya-pradesh-rajasthan-chhattisgarh-telangana-congress-2024-challenges/article67601613.ece",
    ],
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "Anurag Singh Thakur", role: "Union I&B Minister (announced the Cabinet decision)", party: "BJP" }],
    outcome: "In March 2024 the ₹300 subsidy was extended to 2024-25 at about ₹12,000 crore for up to 12 refills a year. Of the four states counted on 3 December 2023, the BJP won three; no cited source links the results to the subsidy.",
    poll: { label: "Assembly polls in 5 states, Nov 2023", month: "2023-11", gapDays: 34, result: "BJP won MP, Rajasthan and Chhattisgarh; INC won Telangana" },
  },
  {
    id: "hdb037",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "PM Vishwakarma",
    kind: "scheme",
    difficulty: "expert",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "PM Vishwakarma, launched on 17 September 2023 for artisans in 18 traditional trades, gives eligible beneficiaries a modern toolkit worth up to how much?",
    options: ["₹5,000", "₹50,000", "₹15,000", "₹1 lakh"],
    correctIndex: 2,
    explanation: "PIB says the ₹13,000-crore scheme (2023-24 to 2027-28) offers a ₹500-a-day training stipend, toolkits of up to ₹15,000 and collateral-free loans of up to ₹3 lakh at 5%. By 15 September 2026, 24.37 lakh artisans had been trained, 18.16 lakh had received toolkits and 6.19 lakh loans worth about ₹5,316 crore had been sanctioned.",
    sourceUrl: "https://pib.gov.in/PressNoteDetails.aspx?NoteId=159998&ModuleId=3&reg=3&lang=1",
    sourceLabel: "PIB Backgrounder — PM Vishwakarma nears three years (Sep 2026)",
    sources: ["https://newsonair.gov.in/pm-vishwakarma-scheme-completes-three-years-with-30-lakh-beneficiaries-registered/"],
    tags: ["distribution"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "The 30-lakh registration target was met by September 2026; 6.19 lakh loans (about ₹5,316 crore) had been sanctioned and over ₹42 crore in digital-payment incentives disbursed.",
  },
  {
    id: "hdb038",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "LPG price cut (March 2024)",
    kind: "spend",
    difficulty: "simple",
    year: 2024,
    asOf: "2026-09",
    govt: "NDA",
    question: "On International Women's Day, 8 March 2024, eight days before the Lok Sabha schedule was announced, PM Modi announced what cut in the price of an LPG cylinder?",
    options: ["₹100", "₹50", "₹200", "₹300"],
    correctIndex: 0,
    explanation: "Modi posted on X that the cut would 'significantly ease the financial burden' on households, 'especially benefiting our Nari Shakti'. A day earlier the Cabinet had extended the targeted Ujjwala subsidy to 2024-25. The ECI announced the seven-phase schedule on 16 March; polling began on 19 April.",
    sourceUrl: "https://indianexpress.com/article/india/pm-modi-international-womens-day-lpg-cylinder-price-cut-9202370/",
    sourceLabel: "The Indian Express — On International Women's Day, PM Modi announces cut in LPG cylinder prices by Rs 100 (8 Mar 2024)",
    sources: [
      "https://www.thehindu.com/elections/lok-sabha/2024-lok-sabha-and-assembly-poll-date-announcement-by-election-commission/article67953554.ece",
      "https://www.dw.com/en/india-election-whats-behind-the-bjps-poll-upset/a-69277403",
    ],
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "The BJP won 240 of 543 seats, short of a majority on its own, and the NDA 293; the cited sources make no causal claim about the price cut.",
    poll: { label: "Lok Sabha 2024", month: "2024-04", gapDays: 42, result: "BJP 240 of 543; NDA 293; INC 99" },
  },
  {
    id: "hdb039",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "VB-G RAM G Act: passage",
    kind: "scheme",
    difficulty: "simple",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "Which Union Rural Development Minister piloted the December 2025 Bill that replaced MGNREGA, passed by the Rajya Sabha by voice vote amid an opposition walkout?",
    options: ["Giriraj Singh", "Narendra Singh Tomar", "Nitin Gadkari", "Shivraj Singh Chouhan"],
    correctIndex: 3,
    explanation: "Parliament passed the VB-G RAM G Bill on 18 December 2025, the Rajya Sabha sitting till midnight. Chouhan said it would fix the old scheme's shortcomings and accused the Congress of using Gandhi's name for political gain; opposition members demanded its withdrawal and walked out. The law guarantees 125 days but provides for a 60-day pause in peak farm seasons.",
    sourceUrl: "https://www.hindustantimes.com/india-news/parliament-passes-new-vb-g-ram-g-bill-to-replace-mgnrega-amid-opposition-walkout-101766086029025.html",
    sourceLabel: "Hindustan Times — Parliament passes new VB-G RAM G Bill to replace MGNREGA amid Opposition walkout (19 Dec 2025)",
    sources: [
      "https://www.pib.gov.in/PressNoteDetails.aspx?NoteId=156634&ModuleId=3&reg=3&lang=1",
      "https://newsonair.gov.in/parliament-passes-viksit-bharat-g-ram-g-bill-2025-rajya-sabha-gives-approval/",
      "https://www.manoramayearbook.in/current-affairs/india/2026/07/01/vb-g-ram-g-act-upsc-explained.html",
    ],
    tags: ["distribution"],
    enactedBy: [{ name: "Shivraj Singh Chouhan", role: "Union Rural Development Minister", party: "BJP" }],
    outcome: "The Centre puts the annual requirement at ₹1,51,282 crore, of which ₹95,692 crore is its share; most states now pay 40% and bear the unemployment allowance. The Act took effect on 1 July 2026.",
  },
  {
    id: "hdb040",
    domain: "civics",
    region: "India",
    state: "WB",
    topic: "Jobs & Economy",
    subtopic: "MGNREGA funds to West Bengal",
    kind: "scheme",
    difficulty: "expert",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "The Centre stopped MGNREGA funds to West Bengal from March 2022, citing non-compliance. What did the Supreme Court do on 27 Oct 2025 with its appeal against a High Court order to restart the scheme?",
    options: ["Stayed the restart until dues were recovered", "Dismissed it, leaving the restart order in place", "Referred it to a five-judge bench", "Ordered a fresh CAG audit first"],
    correctIndex: 1,
    explanation: "The Calcutta High Court ruled on 18 June 2025 that the scheme could not be kept in 'cold storage for eternity' and ordered it implemented from 1 August 2025, while letting the Centre continue its inquiry into alleged irregularities. A bench of Justices Vikram Nath and Sandeep Mehta declined to interfere; on 6 December the Centre resumed it with special conditions, including 100% e-KYC of workers.",
    sourceUrl: "https://www.livelaw.in/top-stories/supreme-court-dismisses-centres-plea-against-high-court-direction-to-resume-mgnrega-scheme-in-west-bengal-307952",
    sourceLabel: "LiveLaw — Supreme Court dismisses Centre's plea against HC direction to resume MGNREGA in West Bengal (27 Oct 2025)",
    sources: [
      "https://indianexpress.com/article/india/after-3-years-centre-resumes-mgnrega-in-bengal-but-with-special-conditions-10412048/",
      "https://www.thehindu.com/news/national/west-bengal/mamata-tears-up-centres-note-imposing-conditions-on-mgnrega-resumption-in-wb/article70376895.ece",
      "https://www.business-standard.com/economy/news/central-schemes-likely-to-get-fresh-push-after-bjp-s-west-bengal-win-126050401441_1.html",
      "https://www.thehindu.com/news/national/west-bengal/implementation-of-vb-g-ram-g-begins-in-west-bengal/article71171210.ece",
      "https://www.deccanherald.com/india/west-bengal/supreme-court-order-on-mgnrega-supreme-blow-to-centre-victory-for-poor-people-of-bengal-tmc-3777655",
    ],
    people: ["Mamata Banerjee", "Vikram Nath", "Sandeep Mehta", "Pradip Mazumdar"],
    status: "Allegation, not a finding: the Centre halted funds in Mar 2022 citing non-compliance and alleged irregularities in the state's implementation; no person is accused here. The HC let its inquiry continue (Jun 2025); the SC dismissed its appeal (27 Oct 2025).",
    tags: ["distribution"],
    outcome: "Then-CM Mamata Banerjee tore up the Centre's conditions note on 9 Dec 2025. After the BJP won the 2026 Assembly election, the jobs guarantee resumed in Bengal, as VB-G RAM G, on 1 July 2026, after almost four years.",
    otherSide: "Bengal's rural development minister Pradip Mazumdar said the state had complied with guidelines, called the freeze 'politically motivated', and said the state paid workers' wages from its own funds.",
  },
  {
    id: "hdb041",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "MGNREGA: lifetime spend",
    kind: "spend",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "By December 2025, when Parliament voted to replace it, about how much had been spent under MGNREGA since its inception?",
    options: ["About ₹1.2 lakh crore", "About ₹4.9 lakh crore", "About ₹11.7 lakh crore", "About ₹48 lakh crore"],
    correctIndex: 2,
    explanation: "The Indian Express, citing official data, reported total spending of ₹11,74,692.69 crore and 4,872.16 crore person-days of work since 2005. PRS notes that spending jumped 55% in 2020-21, when 389 crore person-days were generated as migrants returned home during the pandemic.",
    sourceUrl: "https://indianexpress.com/article/india/100-to-125-days-mnrega-scheme-to-get-name-change-10417717/",
    sourceLabel: "The Indian Express — 100 to 125 days: MGNREGA scheme to get name change (13 Dec 2025)",
    sources: ["https://prsindia.org/files/budget/budget_parliament/2025/DFG_Analysis_2025-26_Rural_Development.pdf"],
    tags: ["distribution"],
    outcome: "Delays persisted to the end: in 2024-25 only 26% of approved compensation for late wage payments had been paid by January 2025, PRS found.",
  },
  {
    id: "hdb042",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "PM Internship Scheme",
    kind: "scheme",
    difficulty: "extreme",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "The PM Internship Scheme, announced in Budget 2024-25 to place 1 crore youth over five years, drew over 1.65 lakh offers in its first two pilot rounds. How many candidates joined?",
    options: ["16,068", "58,400", "1.2 lakh", "4,500"],
    correctIndex: 0,
    explanation: "The corporate affairs ministry's 2025-26 annual report counts 8,760 joinings in round one and 7,308 in round two. Those interns got ₹5,000 a month (₹4,500 from the Centre, ₹500 from company CSR funds) plus a one-time ₹6,000. Round three, from April 2026, raised the stipend to ₹9,000 and had 10,195 joinings by July, the minister told the Lok Sabha.",
    sourceUrl: "https://cfo.economictimes.indiatimes.com/news/policy/pm-internship-scheme-over-165-lakh-offers-round-iii-sees-10195-joinings/132572654",
    sourceLabel: "ETCFO — PM Internship Scheme sees 1.65 lakh-plus offers in first two rounds, just 16,068 join (23 Jul 2026)",
    sources: ["https://indianexpress.com/article/business/economy/8000-candidates-join-pm-internship-scheme-in-4-months-since-its-launch-9819930/"],
    tags: ["distribution"],
    outcome: "The ₹2,000 crore allocated in Budget 2024-25 was cut to ₹380 crore at the revised stage; 2025-26 budgeted ₹10,831 crore.",
  },
  {
    id: "hdb043",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "NSAP old-age pension rate",
    kind: "scheme",
    difficulty: "simple",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "What is the Centre's monthly contribution to the old-age pension of a poor person aged 60–79 under the National Social Assistance Programme, unchanged since 2012?",
    options: ["₹500", "₹1,000", "₹3,000", "₹200"],
    correctIndex: 3,
    explanation: "The rates — ₹200 for ages 60–79, ₹300 for widows and disabled persons, ₹500 for those 80 and above — were last revised in 2012. A 2026 study commissioned by the Rural Development Ministry found inflation had cut their real value by about 45%; in July 2026 the ministry told the Lok Sabha there was no proposal to raise them.",
    sourceUrl: "https://indianexpress.com/article/india/nsap-pension-inflation-impact-report-india-10685019/",
    sourceLabel: "The Indian Express — Centre's old age pension at Rs 200 since 2012 'significantly eroded': ministry study (12 May 2026)",
    sources: ["https://kashmirlife.net/jammu-kashmir-among-lowest-pension-providers-as-centre-refuses-to-raise-nsap-assistance-444188/"],
    tags: ["distribution"],
    outcome: "The study urged an inflation-linked National Floor Pension; the Centre said state top-ups of ₹50 to ₹5,700 bring the average pension to about ₹1,100 a month in several states.",
  },
  {
    id: "hdb044",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "PMMVY: reach",
    kind: "scheme",
    difficulty: "expert",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "About how many mothers had received PM Matru Vandana Yojana maternity cash since it began nationwide in January 2017, per the WCD ministry in August 2026?",
    options: ["46 lakh", "1.2 crore", "4.6 crore", "12 crore"],
    correctIndex: 2,
    explanation: "The ministry told MPs that over 4.60 crore beneficiaries had received more than ₹21,343 crore. PMMVY pays ₹5,000 in two instalments for a first child and ₹6,000 for a second child if a girl. Aadhaar-based biometric authentication has been mandatory since 21 May 2025.",
    sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2302092",
    sourceLabel: "PIB — Annpurna Devi chairs Consultative Committee meeting of the WCD ministry on Mission Shakti (21 Aug 2026)",
    sources: ["https://www.aninews.in/news/national/general-news/426-crore-beneficiaries-paid-total-rs-20060-cr-in-pmmvy20260109215213"],
    tags: ["distribution"],
    outcome: "In 2025-26 (to 8 January 2026) 59.19 lakh beneficiaries were paid ₹2,022 crore, per ANI; 64.65 lakh had been enrolled through biometric authentication by August 2026, the minister said.",
  },
  {
    id: "hdb045",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Antyodaya entitlement (2026 draft)",
    kind: "scheme",
    difficulty: "expert",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "A draft National Food Security (Amendment) Bill, 2026 proposes replacing Antyodaya households' flat per-household monthly grain ration with what?",
    options: ["5 kg per person, with no cap", "7 kg per person, capped at 35 kg", "50 kg per household", "Cash in lieu of grain"],
    correctIndex: 1,
    explanation: "The food ministry told the Rajya Sabha on 28 July 2026 that the draft was with states for pre-legislative consultation. It says the flat entitlement causes inequities, leaving big AAY families with less per head than priority households. An op-ed in The Hindu calculated that households of one to four would get 20–80% less and none would get more; Tamil Nadu asked the Centre to keep the flat household ration.",
    sourceUrl: "https://kashmirlife.net/draft-nfsa-amendment-bill-proposes-7-kg-foodgrain-per-aay-beneficiary-445301/",
    sourceLabel: "Kashmir Life — Draft NFSA Amendment Bill proposes 7 kg foodgrain per AAY beneficiary (28 Jul 2026)",
    sources: [
      "https://www.dailyexcelsior.com/govt-proposes-per-person-7kg-ration-for-aay-households-caps-entitlement-at-35-kg/",
      "https://www.thehindu.com/opinion/lead/a-timely-reset-for-the-food-security-act/article71337424.ece",
      "https://www.thehindu.com/news/national/tamil-nadu/tamil-nadu-drew-lower-quantity-of-rice-than-its-share-underantyodayaannayojana-in-five-of-the-last-seven-years/article71193040.ece",
    ],
    tags: ["distribution"],
    outcome: "Still a draft under consultation in the latest reports (August 2026); the minister said the Centre was aware of states' objections and committed to consensus.",
  },
]);
