// HISAAB DO — Distribution, East & North-East (ids hdb300–hdb399).
// Cash and in-kind transfers in West Bengal, Odisha, Assam, Mizoram, Tripura, Sikkim, Nagaland,
// Meghalaya and Arunachal Pradesh, 2001–2026: who passed them, which party, what they cost and what
// happened next. Every item is tagged 'distribution'; items announced or paid in the run-up to a poll
// are also tagged 'pre-election' and carry `poll` (gapDays = days from announcement/first payment to
// the first day of polling in that state). Research notes: docs/hisaab/research/dist-east-notes.md.
// Every sourceUrl was fetched and read in September 2026 (asOf '2026-09').

export const HISAAB_DIST_EAST = Object.freeze([
  // ───────────────────────── West Bengal ─────────────────────────
  {
    id: 'hdb300',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Farm & Food',
    subtopic: 'Rs 2-a-kg rice (2009)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2009,
    asOf: '2026-09',
    govt: 'CPI(M)',
    question:
      'Subsidised rice at ₹2 a kg was introduced in West Bengal in 2009 by the Centre and the Left Front government. About how many people below the poverty line did it cover?',
    options: ['2.64 crore', '64 lakh', '26 lakh', '6.4 lakh'],
    correctIndex: 0,
    explanation:
      "The Indian Express reported the 2009 scheme covered 2.64 crore people below the poverty line and was one of several incentives offered in Maoist-affected Jangalmahal. A right-to-food adviser to Supreme Court commissioners told the paper rations under the Left government had been irregular; the TMC government that followed reworked the scheme.",
    sourceUrl:
      'https://indianexpress.com/article/india/india-news-india/west-bengal-assembly-elections-2016-in-jangalmahal-village-that-once-went-hungry-parivartan-takes-the-form-of-affordable-rice/',
    sourceLabel:
      "The Indian Express — In Jangalmahal village that once went hungry, 'parivartan' takes the form of affordable rice (28 Mar 2016)",
    tags: ['distribution'],
    outcome:
      'The Left Front lost power in 2011 after 34 years. The new TMC government raised the number of beneficiaries by about 20% to 3.2 crore, and by 2016 ration dealers in Jangalmahal described supply as regular (The Indian Express).',
  },
  {
    id: 'hdb301',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Education & Exams',
    subtopic: 'Kanyashree Prakalpa (2013)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2013,
    asOf: '2026-09',
    govt: 'TMC',
    question:
      "Launched by Mamata Banerjee's government in October 2013, Kanyashree pays girls to stay in school and delay marriage. What one-time grant does a girl get on turning 18?",
    options: ['₹10,000', '₹25,000', '₹50,000', '₹1 lakh'],
    correctIndex: 1,
    explanation:
      'Kanyashree is a conditional cash transfer: a yearly grant for girls aged 13–18 (₹750, raised to ₹1,000 in 2018) and a one-time ₹25,000 at 18. It won the UN Public Service Award in 2017. In January 2018 the CM said it cost ₹1,250 crore a year and ₹5,000 crore had been spent; the 2023-24 budget said it had covered 81 lakh girls.',
    sourceUrl:
      'https://www.thehindu.com/news/national/why-is-child-marriage-still-high-in-west-bengal-explained/article67716959.ece',
    sourceLabel: 'The Hindu — Why is child marriage still high in West Bengal? | Explained (7 Jan 2024)',
    sources: ['https://www.thehindu.com/news/national/bengal-assistance-for-marriage-of-poor-women/article22613215.ece'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Mamata Banerjee', role: 'Chief Minister, West Bengal', party: 'TMC' }],
    outcome:
      'Girls outnumbered boys in the 2023 Class 12 exam, but NFHS-5 (2019-20) found 41.6% of Bengal women aged 20–24 married before 18, unchanged from NFHS-4 and far above the national 23.3% (The Hindu).',
  },
  {
    id: 'hdb302',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Welfare & Subsidies',
    subtopic: 'Rupashree Prakalpa (2018)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2018,
    asOf: '2026-09',
    govt: 'TMC',
    question:
      "Announced in West Bengal's January 2018 budget, the Rupashree scheme gives families earning under ₹1.5 lakh a year a one-time grant of ₹25,000. What is the grant for?",
    options: ["A girl's college fees", "A newborn girl's savings deposit", "A daughter's marriage", "A woman's first business"],
    correctIndex: 2,
    explanation:
      "Finance Minister Amit Mitra announced it on 31 Jan 2018; Mamata Banerjee said ₹1,500 crore would be set aside and that it was separate from Kanyashree. The Hindu reported in 2024 that some families use both schemes to fund a daughter's marriage, sometimes soon after the Kanyashree payout.",
    sourceUrl: 'https://www.thehindu.com/news/national/bengal-assistance-for-marriage-of-poor-women/article22613215.ece',
    sourceLabel: 'The Hindu — Bengal assistance for marriage of poor women (31 Jan 2018)',
    sources: [
      'https://www.newindianexpress.com/thesundaystandard/2022/Jan/30/bengal-governments-rupashree-scheme-provides-25-lakh-poor-brides-with-financial-assistance-2412871.html',
      'https://indianexpress.com/article/cities/kolkata/how-mamata-govt-is-offsetting-spending-hike-in-cash-transfer-schemes-for-women-10521772/',
      'https://www.thehindu.com/news/national/why-is-child-marriage-still-high-in-west-bengal-explained/article67716959.ece',
    ],
    tags: ['distribution'],
    enactedBy: [
      { name: 'Amit Mitra', role: 'Finance Minister, West Bengal', party: 'TMC' },
      { name: 'Mamata Banerjee', role: 'Chief Minister, West Bengal', party: 'TMC' },
    ],
    outcome:
      'By January 2022 the state said 11.71 lakh girls had been paid, costing ₹2,895 crore (NIE). The 2025-26 revised allocation was ₹693.76 crore (The Indian Express).',
  },
  {
    id: 'hdb303',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Farm & Food',
    subtopic: 'Krishak Bandhu (2019)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2018,
    asOf: '2026-09',
    govt: 'TMC',
    question:
      'Mamata Banerjee announced Krishak Bandhu on 31 Dec 2018, about 100 days before the Lok Sabha poll began. What yearly support did it promise farmers?',
    options: ['₹2,000 an acre', '₹3,000 an acre', '₹4,000 an acre', '₹5,000 an acre'],
    correctIndex: 3,
    explanation:
      'It paid ₹5,000 an acre a year in two instalments (pro rata for smaller plots) and ₹2 lakh to the family of a farmer aged 18–60 who died. It was rolled out on 15 Feb 2019 with ₹1,000 crore budgeted. Bengal did not then implement the Centre\'s PM-KISAN; its agriculture minister said the state had its own scheme.',
    sourceUrl:
      'https://indianexpress.com/article/cities/kolkata/krishak-bandhu-scheme-rs-500-crore-disbursed-to-37-lakh-farmers-in-eight-months-6079520/',
    sourceLabel: 'The Indian Express — Krishak Bandhu Scheme: Rs 500 crore disbursed to 37 lakh farmers in eight months (21 Oct 2019)',
    sources: [
      'https://timesofindia.indiatimes.com/city/kolkata/didi-launches-krishak-bandhu-2-0-doubles-assistance-for-all-farmers/articleshow/83619016.cms',
      'https://www.thehindu.com/elections/lok-sabha/trinamool-wins-big-in-west-bengal-bags-29-seats-restricts-bjp-to-12/article68251342.ece',
      'https://www.thehindu.com/news/national/west-bengal/in-its-first-budget-west-bengal-bjp-government-pushes-for-jobs-industries-and-welfarism/article71133177.ece',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Mamata Banerjee', role: 'Chief Minister, West Bengal', party: 'TMC' }],
    outcome:
      'By Sept 2019, 37.7 lakh farmers had got ₹478 crore. The TMC won 22 of 42 seats in 2019 (BJP 18). It doubled the aid to ₹10,000 an acre in June 2021. The BJP government\'s June 2026 budget offered ₹3,000 a year on top of PM-KISAN.',
    poll: { label: 'Lok Sabha 2019 (West Bengal)', month: '2019-04', gapDays: 101, result: 'TMC won 22 of 42 seats; BJP 18' },
  },
  {
    id: 'hdb304',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Education & Exams',
    subtopic: 'Sabooj Sathi bicycles',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2020,
    asOf: '2026-09',
    govt: 'TMC',
    question:
      "West Bengal's Sabooj Sathi scheme, started in 2015, gives bicycles to Class 9–12 students of government and aided schools. By 2020, about how many students had got one, per the state?",
    options: ['85 lakh', '27 lakh', '8.5 lakh', '2.7 lakh'],
    correctIndex: 0,
    explanation:
      'The state said about 85 lakh students had received cycles at an estimated cost of over ₹2,700 crore; the aim was to cut dropouts, especially in rural Bengal. In Sept 2020 it won the World Summit on the Information Society prize in the e-government category, chosen from about 800 projects.',
    sourceUrl:
      'https://indianexpress.com/article/cities/kolkata/had-contested-with-800-projects-after-kanyashree-bengal-govt-bags-wsis-award-for-its-sabuj-sathi-scheme-6589951/',
    sourceLabel: 'The Indian Express — After Kanyashree, Bengal govt bags WSIS award for its Sabuj Sathi scheme (10 Sep 2020)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Mamata Banerjee', role: 'Chief Minister, West Bengal', party: 'TMC' }],
    outcome: "About 85 lakh cycles for over ₹2,700 crore between 2015 and 2020, by the government's own count; the WSIS prize was its second global award after Kanyashree's UN prize.",
  },
  {
    id: 'hdb305',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Welfare & Subsidies',
    subtopic: 'Duare Sarkar camps (2020)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2020,
    asOf: '2026-09',
    govt: 'TMC',
    question:
      "Bengal's 'Duare Sarkar' camps, where people could sign up for state welfare schemes, opened on 1 Dec 2020. How many people did the CM say visited in the first two weeks?",
    options: ['About 25 lakh', 'Over 1 crore', 'Over 3 crore', 'Over 5 crore'],
    correctIndex: 1,
    explanation:
      'Mamata Banerjee said over 1 crore people visited more than 10,000 camps in two weeks; 64 lakh enrolled in the first phase (1–11 Dec). The camps offered at least 11 schemes, including Kanyashree, Khadya Sathi food security, Rupashree and pensions for Scheduled Caste citizens (Taposili Bandhu).',
    sourceUrl:
      'https://www.livemint.com/news/india/bengal-s-duare-sarkar-reached-over-1-crore-people-in-2-weeks-cm-mamata-11608367316616.html',
    sourceLabel: "Mint — Bengal's 'Duare Sarkar' reached over 1 crore people in 2 weeks: CM Mamata (19 Dec 2020)",
    sources: [
      'https://www.thehindu.com/news/cities/kolkata/west-bengal-elections-in-final-tally-tmc-bags-213-bjp-77-isf-and-independent-1-each/article34471551.ece',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Mamata Banerjee', role: 'Chief Minister, West Bengal', party: 'TMC' }],
    outcome:
      'Polling began 116 days later. The TMC won 213 of the 292 seats polled in 2021, its best tally, with 47.9% of the vote; the BJP won 77 (The Hindu). No study cited here ties the result to the camps.',
    poll: { label: 'West Bengal Assembly 2021', month: '2021-03', gapDays: 116, result: 'TMC won 213 of 292 seats polled; BJP 77' },
  },
  {
    id: 'hdb306',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Welfare & Subsidies',
    subtopic: 'Lakshmir Bhandar hike (2024)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'TMC',
    question:
      "Ten weeks before the 2024 Lok Sabha poll began, Bengal's budget doubled the Lakshmir Bhandar payment for general-category women. From ₹500 a month to what?",
    options: ['₹600', '₹750', '₹1,000', '₹1,200'],
    correctIndex: 2,
    explanation:
      'Minister of State (Finance) Chandrima Bhattacharya\'s budget of 8 Feb 2024 raised general-category payments from ₹500 to ₹1,000 and SC/ST payments from ₹1,000 to ₹1,200, allotting ₹14,400 crore for about 2.11 crore women. The TMC had started the scheme in Sept 2021 after promising it before that year\'s Assembly poll.',
    sourceUrl: 'https://www.thehindu.com/news/national/other-states/west-bengal-state-budget-2024/article67824908.ece',
    sourceLabel: 'The Hindu — Sops galore in West Bengal Budget 2024-25 ahead of Lok Sabha polls (8 Feb 2024)',
    sources: [
      'https://www.thehindu.com/elections/lok-sabha/trinamool-wins-big-in-west-bengal-bags-29-seats-restricts-bjp-to-12/article68251342.ece',
      'https://indianexpress.com/article/cities/kolkata/ahead-of-bengal-2026-assembly-elections-tmc-govt-announces-rs-500-hike-for-lakshmir-bhandar-beneficiaries-10515653/',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [
      { name: 'Chandrima Bhattacharya', role: 'Minister of State (Finance), West Bengal', party: 'TMC' },
      { name: 'Mamata Banerjee', role: 'Chief Minister, West Bengal', party: 'TMC' },
    ],
    outcome:
      'The TMC won 29 of Bengal\'s 42 Lok Sabha seats, up from 22 in 2019, with about 46% of the vote; the BJP fell from 18 seats to 12 (The Hindu).',
    poll: { label: 'Lok Sabha 2024 (West Bengal)', month: '2024-04', gapDays: 71, result: 'TMC won 29 of 42 seats; BJP fell from 18 to 12' },
  },
  {
    id: 'hdb307',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Welfare & Subsidies',
    subtopic: 'Lakshmir Bhandar hike (2026)',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2026,
    asOf: '2026-09',
    govt: 'TMC',
    question:
      "In its February 2026 vote on account, 11 weeks before polling began, Bengal's TMC government added ₹500 a month to Lakshmir Bhandar. What had the scheme cost in its first 50 months?",
    options: ['About ₹7,400 crore', 'About ₹24,000 crore', 'About ₹45,000 crore', 'About ₹74,000 crore'],
    correctIndex: 3,
    explanation:
      'Government sources told The Indian Express ₹74,000 crore had gone to 2,20,25,342 women since Sept 2021. The 5 Feb 2026 hike took payments to ₹1,500 (general) and ₹1,700 (SC/ST) a month; the same speech offered jobless youth ₹1,500 a month under Banglar Yuba Sathi and a 4% DA rise.',
    sourceUrl:
      'https://indianexpress.com/article/cities/kolkata/ahead-of-bengal-2026-assembly-elections-tmc-govt-announces-rs-500-hike-for-lakshmir-bhandar-beneficiaries-10515653/',
    sourceLabel:
      'The Indian Express — Ahead of Bengal 2026 Assembly elections, TMC govt announces Rs 500 hike for Lakshmir Bhandar beneficiaries (5 Feb 2026)',
    sources: [
      'https://www.thehindu.com/elections/west-bengal-assembly/day-after-landslide-victory-bjps-bengal-tally-climbs-to-207-with-recount-win/article70942946.ece',
      'https://newsonair.gov.in/polling-to-be-held-in-single-phase-in-tamilnadu-on-23rd-april-two-phase-polling-in-west-bengal-to-be-held-on-23rd-and-29th-of-next-month/',
      'https://www.thehindu.com/news/national/west-bengal/in-its-first-budget-west-bengal-bjp-government-pushes-for-jobs-industries-and-welfarism/article71133177.ece',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Chandrima Bhattacharya', role: 'Minister of State (Finance), West Bengal', party: 'TMC' }],
    outcome:
      'Officials said total spending since launch would pass ₹1 lakh crore that year. The BJP won 207 of 294 seats (after a recount), ending 15 years of TMC rule; its first budget set aside ₹36,000 crore for Annapurna, a ₹3,000-a-month women\'s scheme.',
    poll: { label: 'West Bengal Assembly 2026', month: '2026-04', gapDays: 77, result: 'BJP won 207 of 294 seats; TMC about 80' },
  },
  {
    id: 'hdb308',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Welfare & Subsidies',
    subtopic: 'Cash schemes vs other spending',
    kind: 'spend',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'TMC',
    question:
      "Bengal's 2025-26 revised estimates showed cash-transfer schemes over budget. Which programme spent only about ₹156 crore of its ₹820 crore allocation that year?",
    options: ['Mid-day meals in schools', 'Kanyashree scholarships', 'Rupashree marriage grants', 'Widow pensions'],
    correctIndex: 0,
    explanation:
      "Budget papers reported by The Indian Express: Lakshmir Bhandar was revised from ₹26,700 crore to ₹28,615 crore and Kanyashree from ₹816 crore to ₹1,058 crore, while mid-day meals spent 19% of their allocation and Samagra Shiksha under half. A finance official said the state spends over ₹50,000 crore on cash transfers, so 'we had to curtail' other projects.",
    sourceUrl:
      'https://indianexpress.com/article/cities/kolkata/how-mamata-govt-is-offsetting-spending-hike-in-cash-transfer-schemes-for-women-10521772/',
    sourceLabel: 'The Indian Express — How Mamata govt is offsetting spending hike in cash transfer schemes for women (9 Feb 2026)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Chandrima Bhattacharya', role: 'Minister of State (Finance), West Bengal', party: 'TMC' }],
    outcome:
      'Rural drinking water was revised from ₹5,504 crore to ₹1,444 crore, and child-budget schemes spent ₹320 crore of ₹1,673 crore, per the state\'s own Gender and Child Budget papers.',
  },
  {
    id: 'hdb309',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Education & Exams',
    subtopic: 'Kanyashree renamed (2026)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "In August 2026 West Bengal's new BJP government renamed the TMC-era Kanyashree cash scheme for schoolgirls. What is it called now?",
    options: ['Annapurna Kanya', 'Kanya Ratna', 'Beti Bachao Beti Padhao', 'Lakshmi Kanya'],
    correctIndex: 1,
    explanation:
      "On Kanya Ratna Divas (14 Aug), formerly Kanyashree Divas, CM Suvendu Adhikari said the yearly scholarship doubles from ₹1,000 to ₹2,000 from the next session, while the one-time ₹25,000 grant at 18 stays. The same day Bengal joined the Centre's Beti Bachao Beti Padhao, which the TMC government had not implemented.",
    sourceUrl: 'https://indianexpress.com/article/cities/kolkata/bengal-joins-beti-bachao-beti-padhao-suvendu-adhikari-10834375/',
    sourceLabel: "The Indian Express — Bengal joins 'Beti Bachao, Beti Padhao'; Rs 2k aid for schoolgirls from 2027 (15 Aug 2026)",
    sources: ['https://timesofindia.indiatimes.com/city/kolkata/kanyashree-now-kanya-ratna-grant-doubles/articleshow/133248582.cms'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Suvendu Adhikari', role: 'Chief Minister, West Bengal', party: 'BJP' }],
    outcome: 'On 14 Aug 2026, 9.48 lakh of 10.77 lakh eligible schoolgirls got ₹1,000 and 1.29 lakh got ₹25,000, ₹418 crore in all (IE). The ₹2,000 yearly grant starts with the 2027 session.',
  },
  {
    id: 'hdb310',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Health',
    subtopic: 'Swasthya Sathi to Ayushman Bharat',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Before Bengal's BJP government began moving to the Centre's Ayushman Bharat in July 2026, the TMC-era Swasthya Sathi gave up to ₹5 lakh a year of hospital cover to about how many families?",
    options: ['45 lakh', '1.43 crore', '2.45 crore', '4.5 crore'],
    correctIndex: 2,
    explanation:
      "The Indian Express put Swasthya Sathi at about 2.45 crore families; Ayushman Bharat's own list in Bengal is about 1.43 crore families, and officials said the rest would be onboarded with the state paying the whole premium. CM Suvendu Adhikari announced the 1 July roll-out after a meeting with Union Health Minister J.P. Nadda, ending a long Centre–state impasse.",
    sourceUrl:
      'https://indianexpress.com/article/explained/ayushman-bharat-launch-swasthya-sathi-west-bengal-suvendu-adhikari-10730450/',
    sourceLabel: 'The Indian Express — With Ayushman Bharat roll-out in Bengal, what happens to Swasthya Sathi beneficiaries? (9 Jun 2026)',
    sources: [
      'https://www.thehindu.com/news/national/west-bengal/west-bengal-gets-3000-crore-for-healthcare-revamp-ayushman-bharat-card-rollout-from-july-cm-suvendu-adhikari/article71014164.ece',
    ],
    tags: ['distribution'],
    enactedBy: [{ name: 'Suvendu Adhikari', role: 'Chief Minister, West Bengal', party: 'BJP' }],
    outcome:
      'Swasthya Sathi families are to get cards usable in more than 36,000 Ayushman-empanelled hospitals across India; whether the cards will be co-branded was undecided in June 2026.',
  },

  // ───────────────────────── Odisha ─────────────────────────
  {
    id: 'hdb311',
    domain: 'civics',
    region: 'India',
    state: 'OD',
    topic: 'Farm & Food',
    subtopic: 'Kashipur and cheap rice (2001)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2001,
    asOf: '2026-09',
    govt: 'BJD',
    question:
      "After at least 20 deaths in Odisha's Kashipur block in 2001 among people who had eaten mango-kernel gruel, the state ensured poor families 16 kg of rice a month at what price?",
    options: ['₹1 a kg', '₹2 a kg', '₹3 a kg', '₹4.75 a kg'],
    correctIndex: 3,
    explanation:
      'Frontline records that a year after Naveen Patnaik became Chief Minister, the Kashipur deaths in Rayagada district made headlines, and the government ensured families below the poverty line 16 kg of rice a month at ₹4.75 a kg. It later paid above the central subsidy to cut the price to ₹2 (2008) and ₹1 a kg (2013).',
    sourceUrl:
      'https://frontline.thehindu.com/the-nation/naveen-odisha-state-witnesses-transformation-under-cm-naveen-patnaik/article38482544.ece',
    sourceLabel: 'Frontline — Naveen Odisha: State witnesses transformation under CM Naveen Patnaik (6 May 2022)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Naveen Patnaik', role: 'Chief Minister, Odisha', party: 'BJD' }],
    outcome: 'Frontline reported in 2022 that there had been no starvation deaths in the state for many years.',
  },
  {
    id: 'hdb312',
    domain: 'civics',
    region: 'India',
    state: 'OD',
    topic: 'Jobs & Economy',
    subtopic: "Odisha's Mission Shakti (2001)",
    kind: 'scheme',
    difficulty: 'expert',
    year: 2001,
    asOf: '2026-09',
    govt: 'BJD',
    question:
      "Odisha's Mission Shakti programme, which funds and organises women's self-help groups, was launched by Naveen Patnaik's government in which year?",
    options: ['2001', '2005', '2009', '2014'],
    correctIndex: 0,
    explanation:
      "Frontline: launched in 2001, it had more than six lakh women's SHGs with over 70 lakh members, and got its own department in 2021. The state provides seed money and revolving funds, links groups to credit and pays interest subvention. Not to be confused with the Union women and child development ministry's Mission Shakti.",
    sourceUrl:
      'https://frontline.thehindu.com/the-nation/naveen-odisha-state-witnesses-transformation-under-cm-naveen-patnaik/article38482544.ece',
    sourceLabel: 'Frontline — Naveen Odisha: State witnesses transformation under CM Naveen Patnaik (6 May 2022)',
    sources: ['https://frontline.thehindu.com/cover-story/article27321197.ece'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Naveen Patnaik', role: 'Chief Minister, Odisha', party: 'BJD' }],
    outcome: 'By 2019–22 the network counted over six lakh groups and 70 lakh members (Frontline); a separate Mission Shakti department was created in 2021.',
  },
  {
    id: 'hdb313',
    domain: 'civics',
    region: 'India',
    state: 'OD',
    topic: 'Farm & Food',
    subtopic: 'Rs 2-a-kg rice (2008)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2008,
    asOf: '2026-09',
    govt: 'BJD',
    question:
      "Odisha's '₹2 a kg rice' scheme began on 1 Aug 2008, about eight months before the 2009 Assembly poll. How many of the 147 seats did Naveen Patnaik's BJD win in that poll?",
    options: ['78', '103', '112', '117'],
    correctIndex: 1,
    explanation:
      'Frontline notes the state bore cost above the central subsidy to sell rice to the poor at ₹2 a kg from 1 Aug 2008. The Indian Express recorded the BJD\'s 103 seats in 2009, which it bettered with 117 in 2014. No study cited here links either result to the rice scheme.',
    sourceUrl: 'https://indianexpress.com/article/political-pulse/naveen-is-orissa-cm-for-record-fourth-time/',
    sourceLabel: 'The Indian Express — Naveen is Orissa CM for record fourth time (22 May 2014)',
    sources: ['https://frontline.thehindu.com/the-nation/naveen-odisha-state-witnesses-transformation-under-cm-naveen-patnaik/article38482544.ece'],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Naveen Patnaik', role: 'Chief Minister, Odisha', party: 'BJD' }],
    outcome: 'The BJD returned with 103 of 147 seats in April 2009. The rice price was cut again to ₹1 a kg from February 2013.',
    poll: { label: 'Odisha Assembly 2009', month: '2009-04', gapDays: 258, result: 'BJD won 103 of 147 seats' },
  },
  {
    id: 'hdb314',
    domain: 'civics',
    region: 'India',
    state: 'OD',
    topic: 'Farm & Food',
    subtopic: 'Re 1-a-kg rice (2013)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2013,
    asOf: '2026-09',
    govt: 'BJD',
    question: 'From February 2013, what did the BJD government charge poor families in Odisha for a kilo of subsidised rice?',
    options: ['Nothing', '50 paise', '₹1', '₹2'],
    correctIndex: 2,
    explanation:
      'Odisha had sold rice at ₹2 a kg since August 2008, paying above the central subsidy, and lowered the price to ₹1 a kg in February 2013. In October 2018 it added its own food security scheme for 25 lakh people left out of the National Food Security Act (Frontline).',
    sourceUrl:
      'https://frontline.thehindu.com/the-nation/naveen-odisha-state-witnesses-transformation-under-cm-naveen-patnaik/article38482544.ece',
    sourceLabel: 'Frontline — Naveen Odisha: State witnesses transformation under CM Naveen Patnaik (6 May 2022)',
    sources: ['https://indianexpress.com/article/political-pulse/naveen-is-orissa-cm-for-record-fourth-time/'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Naveen Patnaik', role: 'Chief Minister, Odisha', party: 'BJD' }],
    outcome: 'In the 2014 Assembly poll the BJD won 117 of 147 seats, up from 103 in 2009, and Naveen Patnaik began a record fourth term (The Indian Express).',
  },
  {
    id: 'hdb315',
    domain: 'civics',
    region: 'India',
    state: 'OD',
    topic: 'Farm & Food',
    subtopic: 'KALIA announced (2018)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2018,
    asOf: '2026-09',
    govt: 'BJD',
    question:
      "Announcing the KALIA farm-aid scheme on 21 Dec 2018, months before the 2019 polls, Naveen Patnaik rejected what the Congress and BJP were offering Odisha's farmers. What was it?",
    options: ['Free farm electricity', 'A bonus over the paddy MSP', 'Zero-premium crop insurance', 'A farm-loan waiver'],
    correctIndex: 3,
    explanation:
      "KALIA budgeted ₹10,180 crore over three years: ₹10,000 a year for small and marginal farm families, ₹12,500 for landless households and interest-free crop loans up to ₹50,000. Patnaik said loan waivers 'will not pay in the future'. The BJP and Congress called KALIA a poll gimmick; the state said the Finance Commission had praised it.",
    sourceUrl: 'https://indianexpress.com/article/india/odisha-cm-skips-loan-waiver-declares-financial-aide-for-farmers-5504787/',
    sourceLabel: 'The Indian Express — Odisha CM skips loan waiver, declares financial aid for farmers (22 Dec 2018)',
    sources: [
      'https://timesofindia.indiatimes.com/city/bhubaneswar/1st-instalment-under-kalia-by-jan-26-govt/articleshow/67505981.cms',
      'https://frontline.thehindu.com/cover-story/article27321197.ece',
      'https://indianexpress.com/article/india/782-crore-went-to-ineligible-beneficiaries-kalia-scheme-9565567/',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Naveen Patnaik', role: 'Chief Minister, Odisha', party: 'BJD' }],
    outcome:
      'More than 37 lakh farmers, sharecroppers and labourers were paid before the model code of conduct halted payments (Frontline). The BJD won 112 of 146 seats polled in 2019. After PM-KISAN began, KALIA\'s payment was cut to ₹4,000 (IE).',
    poll: { label: 'Odisha Assembly 2019', month: '2019-04', gapDays: 111, result: 'BJD won 112 of 146 seats polled; BJP 23, Congress 9' },
  },
  {
    id: 'hdb316',
    domain: 'civics',
    region: 'India',
    state: 'OD',
    topic: 'Farm & Food',
    subtopic: 'KALIA audit (CAG, 2024)',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'BJD',
    question:
      "A CAG audit released in Sept 2024 found that how many ineligible beneficiaries had received money under Odisha's KALIA farm-aid scheme during 2019–21?",
    options: ['12.72 lakh', '6.36 lakh', '3.18 lakh', '1.06 lakh'],
    correctIndex: 0,
    explanation:
      "The CAG said 12.72 lakh ineligible people got ₹782.26 crore, with 'remote chances of recovery', and ₹107.64 crore went to 1.28 lakh accounts whose names did not match. In 2020 the BJD government had served refund notices on about 3.41 lakh farmers; the BJP, then in opposition, urged farmers not to repay and blamed officials.",
    sourceUrl: 'https://indianexpress.com/article/india/782-crore-went-to-ineligible-beneficiaries-kalia-scheme-9565567/',
    sourceLabel: "The Indian Express — Rs 782 crore went to 'ineligible beneficiaries': CAG on farmers support scheme (13 Sep 2024)",
    sources: [
      'https://www.newindianexpress.com/states/odisha/2020/Jul/27/dont-refund-money-received-under-kalia-scheme-bjp-tells-odisha-farmers-2175337.html',
    ],
    tags: ['distribution'],
    enactedBy: [{ name: 'Naveen Patnaik', role: 'Chief Minister, Odisha', party: 'BJD' }],
    outcome:
      'Of ₹9,333 crore disbursed, ₹2,060 crore for 2021-22 could not be checked because data was not provided. The new BJP government repackaged the scheme as CM-KISAN.',
  },
  {
    id: 'hdb317',
    domain: 'civics',
    region: 'India',
    state: 'OD',
    topic: 'Welfare & Subsidies',
    subtopic: 'Madhu Babu pension hike (2024)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'BJD',
    question:
      "About three months before the 2024 polls, Naveen Patnaik raised Odisha's social-security pensions by ₹500 a month. What became the rate for beneficiaries aged up to 79?",
    options: ['₹700', '₹1,000', '₹1,500', '₹2,000'],
    correctIndex: 1,
    explanation:
      'Madhu Babu Pension Yojana (2008) rates rose from ₹500 to ₹1,000 up to age 79, from ₹700 to ₹1,200 for those 80 and over, and from ₹900 to ₹1,400 for the severely disabled over 80, for 36.75 lakh people, paid 20–25 Feb 2024. Yearly cost rose from ₹2,685 crore to ₹3,683 crore. Pensions had also been raised by ₹200 before the 2019 polls.',
    sourceUrl:
      'https://www.business-standard.com/finance/personal-finance/odisha-cm-raises-pension-for-beneficiaries-under-social-security-schemes-124021000951_1.html',
    sourceLabel: 'Business Standard (PTI) — Odisha CM raises pension for beneficiaries under social security schemes (10 Feb 2024)',
    sources: ['https://www.outlookindia.com/elections/odisha-vidhan-sabha-result-2024-updates-bjp-majority-bjd-rule-to-end-full-list-of-winners'],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Naveen Patnaik', role: 'Chief Minister, Odisha', party: 'BJD' }],
    outcome: 'The BJD lost the 2024 Assembly poll after 24 years in power: BJP 78, BJD 51, Congress 14 of 147 seats (Outlook).',
    poll: { label: 'Odisha Assembly 2024', month: '2024-05', gapDays: 93, result: 'BJP won 78 of 147 seats; BJD 51' },
  },
  {
    id: 'hdb318',
    domain: 'civics',
    region: 'India',
    state: 'OD',
    topic: 'Health',
    subtopic: 'BSKY renamed; Ayushman Bharat joins',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "In its first budget in July 2024, Odisha's BJP government renamed the BJD's Biju Swasthya Kalyan Yojana health cover. What is the scheme called now?",
    options: ['Mukhya Mantri Swasthya Yojana', 'Subhadra Arogya Yojana', 'Gopabandhu Jan Arogya Yojana', 'Odisha Ayushman Yojana'],
    correctIndex: 2,
    explanation:
      "The 2024-25 budget gave GJAY ₹5,450 crore, the largest health line, and ₹500 crore to start the Centre's Ayushman Bharat PM-JAY, which the BJD government had not implemented. Union Health Minister J.P. Nadda launched both at Cuttack on 11 April 2025 with CM Mohan Charan Majhi; the state said 3.5 crore people in 1.3 crore families would be covered.",
    sourceUrl:
      'https://www.newindianexpress.com/states/odisha/2024/Jul/26/gjay-replaces-biju-swasthya-kalyan-yojana-as-health-takes-8-per-cent-of-odishas-budget',
    sourceLabel: 'The New Indian Express — GJAY replaces Biju Swasthya Kalyan Yojana as health takes 8 per cent of Odisha\'s budget (26 Jul 2024)',
    sources: ['https://health.economictimes.indiatimes.com/news/policy/j-p-nadda-to-launch-ayushman-bharat-scheme-in-odisha-on-april-11/120048927'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Mohan Charan Majhi', role: 'Chief Minister, Odisha', party: 'BJP' }],
    outcome: 'Health spending was budgeted at ₹21,200 crore for 2024-25, up about 32% and roughly 8% of the budget (NIE).',
  },

  // ───────────────────────── Assam ─────────────────────────
  {
    id: 'hdb319',
    domain: 'civics',
    region: 'India',
    state: 'AS',
    topic: 'Welfare & Subsidies',
    subtopic: "Gogoi's pre-poll package (2015)",
    kind: 'scheme',
    difficulty: 'expert',
    year: 2015,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'In Sept 2015 Assam CM Tarun Gogoi announced a package of cash and in-kind benefits to be handed out before the 2016 Assembly poll. What was it worth?',
    options: ['₹86 crore', '₹286 crore', '₹620 crore', '₹862 crore'],
    correctIndex: 3,
    explanation:
      "Gogoi said about 25 schemes would give yarn to weavers, laptops to students, seeds, blankets and pensions to 76.41 lakh people from November, funded by the state. Asked if it was for the polls, he said: 'Who doesn't do politics?… If this helps me, why will I not do it?' He denied BJP charges that development funds were being diverted.",
    sourceUrl: 'https://www.thehindu.com/news/national/gogoi-announces-rs-862crore-largesse-for-assam/article7692497.ece',
    sourceLabel: 'The Hindu — Gogoi announces Rs. 862-crore largesse for Assam (26 Sep 2015)',
    sources: [
      'https://www.cnbctv18.com/india/politics/assam-exit-polls-2026-a-look-at-how-predictions-fared-against-results-in-2016-2021-assembly-elections-ws-l-19895036.htm',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Tarun Gogoi', role: 'Chief Minister, Assam', party: 'INC' }],
    outcome:
      'The Congress lost in April 2016 after 15 years in power: the BJP won 60 of 126 seats and formed the government with allies; the Congress fell to 26 (CNBC-TV18).',
    poll: { label: 'Assam Assembly 2016', month: '2016-04', gapDays: 191, result: 'BJP won 60 of 126 and formed govt with allies; Congress 26' },
  },
  {
    id: 'hdb320',
    domain: 'civics',
    region: 'India',
    state: 'AS',
    topic: 'Welfare & Subsidies',
    subtopic: 'Arundhati gold scheme (2020)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2020,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "At its first payouts in Sept 2020, how much did Assam's Arundhati scheme give each eligible newly-wed couple to buy one tola (10 g) of gold for the bride?",
    options: ['₹40,000', '₹25,000', '₹15,000', '₹10,000'],
    correctIndex: 0,
    explanation:
      'Approved in Nov 2019 at ₹30,000, it needs a registered marriage, a bride of at least 18 who has passed Class 10, and a groom of at least 21. At the 24 Sept 2020 launch, 587 of the first 1,121 couples to apply were found eligible. Then Finance Minister Himanta Biswa Sarma said it would push up marriage registration.',
    sourceUrl:
      'https://www.indiatoday.in/india/story/assam-eligible-newlyweds-to-get-rs-40-000-as-aid-under-arundhati-gold-scheme-1725083-2020-09-24',
    sourceLabel: "India Today — Assam: Eligible newlyweds to get Rs 40,000 as aid under 'Arundhati Gold Scheme' (24 Sep 2020)",
    sources: [
      'https://www.business-standard.com/article/news-ani/assam-under-arundhati-scheme-bride-to-get-10-gram-gold-if-she-is-18-and-matriculate-119112001746_1.html',
      'https://m.economictimes.com/news/politics-and-nation/assam-government-provides-rs-40000-to-newly-married-couples-for-purchasing-gold/articleshow/78299767.cms',
      'https://www.cnbctv18.com/india/politics/assam-exit-polls-2026-a-look-at-how-predictions-fared-against-results-in-2016-2021-assembly-elections-ws-l-19895036.htm',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [
      { name: 'Sarbananda Sonowal', role: 'Chief Minister, Assam', party: 'BJP' },
      { name: 'Himanta Biswa Sarma', role: 'Finance Minister, Assam', party: 'BJP' },
    ],
    outcome: 'Payouts began six months before the 2021 poll, in which the BJP-led NDA kept power with 75 of 126 seats (CNBC-TV18).',
    poll: { label: 'Assam Assembly 2021', month: '2021-03', gapDays: 184, result: 'BJP-led NDA won 75 of 126 seats' },
  },
  {
    id: 'hdb321',
    domain: 'civics',
    region: 'India',
    state: 'AS',
    topic: 'Welfare & Subsidies',
    subtopic: 'Orunodoi: the 2021 promise',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2021,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Assam's Orunodoi paid women ₹830 a month when it started in 2020. At a February 2021 rally before the Assembly poll, what monthly amount did Himanta Biswa Sarma say it would rise to?",
    options: ['₹2,000', '₹3,000', '₹4,000', '₹5,000'],
    correctIndex: 1,
    explanation:
      'Announced in the 2020-21 budget by Finance Minister Sarma and launched with CM Sarbananda Sonowal, Orunodoi pays women heads of poor households (income under ₹2 lakh) by bank transfer. 18 lakh families were identified at launch and about 22 lakh by early 2021 (The Indian Express).',
    sourceUrl: 'https://indianexpress.com/article/explained/assam-orunudoi-scheme-explained-7230383/',
    sourceLabel: 'The Indian Express — Explained: Orunudoi — A woman-centric scheme as game-changer (16 Mar 2021)',
    sources: [
      'https://indianexpress.com/article/political-pulse/the-asoni-election-schemes-for-women-may-decide-assam-contest-but-price-rise-remains-a-worry-10614409/',
      'https://www.cnbctv18.com/india/politics/assam-exit-polls-2026-a-look-at-how-predictions-fared-against-results-in-2016-2021-assembly-elections-ws-l-19895036.htm',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [
      { name: 'Himanta Biswa Sarma', role: 'Finance Minister, Assam', party: 'BJP' },
      { name: 'Sarbananda Sonowal', role: 'Chief Minister, Assam', party: 'BJP' },
    ],
    outcome:
      'The NDA won 75 of 126 seats and Sarma became CM. By April 2026 Orunodoi reached about 40 lakh women at ₹1,250 a month, not the ₹3,000 mentioned in 2021 (The Indian Express).',
    poll: { label: 'Assam Assembly 2021', month: '2021-03', result: 'BJP-led NDA won 75 of 126 seats' },
  },
  {
    id: 'hdb322',
    domain: 'civics',
    region: 'India',
    state: 'AS',
    topic: 'Education & Exams',
    subtopic: 'Nijut Moina stipend (2024)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'BJP',
    question: "Under Assam's Nijut Moina monthly stipend for girl students, launched in 2024, what makes a girl lose the payment?",
    options: ['Failing a single exam', 'Family income above ₹2 lakh', 'Marrying before finishing her degree', 'Moving to a government college'],
    correctIndex: 2,
    explanation:
      "CM Himanta Biswa Sarma paid the first instalment on 6 Oct 2024: ₹1,000 a month in higher secondary, ₹1,250 for degree and ₹2,500 for postgraduate students, for 10 months a year; private-college students are excluded. The Congress said the government was 'creating beneficiaries'; Sarma said dropouts would otherwise rise.",
    sourceUrl:
      'https://www.thehindu.com/news/national/assam/nijut-moina-scheme-first-instalment-of-monthly-stipend-handed-over-to-girl-students-in-assam/article68724539.ece',
    sourceLabel: "The Hindu — 'Nijut Moina' scheme: First instalment of monthly stipend handed over to girl students in Assam (6 Oct 2024)",
    sources: ['https://frontline.thehindu.com/politics/assam-election-cash-transfer-schemes-stagnant-incomes/article70834407.ece'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Himanta Biswa Sarma', role: 'Chief Minister, Assam', party: 'BJP' }],
    outcome:
      'Assam budgeted it for 4.3 lakh girls in 2025-26 and over 5.5 lakh in 2026-27 (Frontline). A version for male postgraduates, Nijut Babu Asoni, followed.',
  },
  {
    id: 'hdb323',
    domain: 'civics',
    region: 'India',
    state: 'AS',
    topic: 'Jobs & Economy',
    subtopic: 'Mahila Udyamita Abhiyaan (2025)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Assam's Mukhya Mantri Mahila Udyamita Abhiyaan, which had approved over 28.5 lakh women by the 2026 poll, offers each self-help-group member up to how much seed capital over three years?",
    options: ['₹15,000', '₹40,000', '₹60,000', '₹85,000'],
    correctIndex: 3,
    explanation:
      "Members get ₹10,000 first, then ₹25,000 and ₹50,000 if the money is used productively. Sarma handed out cheques across constituencies from late 2025 and called it 'not a vote-centric scheme'. He also said Bihar's ₹10,000 women's scheme, paid before its November 2025 poll, followed Assam's model.",
    sourceUrl:
      'https://indianexpress.com/article/political-pulse/the-asoni-election-schemes-for-women-may-decide-assam-contest-but-price-rise-remains-a-worry-10614409/',
    sourceLabel: "The Indian Express — The 'asoni' election: Schemes for women may decide Assam contest (2 Apr 2026)",
    sources: [
      'https://timesofindia.indiatimes.com/city/guwahati/born-in-assam-tested-in-bihar-women-self-employment-scheme-sets-template-for-state-polls/articleshow/125333702.cms',
      'https://newsonair.gov.in/bjp-set-to-form-government-in-west-bengal-and-assam-nda-retains-puducherry/',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Himanta Biswa Sarma', role: 'Chief Minister, Assam', party: 'BJP' }],
    outcome:
      'Lakhs of women had received the first ₹10,000 before voting on 9 April 2026 (IE). The BJP won 82 of 126 seats on its own as its alliance won a third term (All India Radio).',
    poll: { label: 'Assam Assembly 2026', month: '2026-04', result: 'BJP won 82 of 126 seats; NDA third straight term' },
  },

  // ───────────────────────── Mizoram ─────────────────────────
  {
    id: 'hdb324',
    domain: 'civics',
    region: 'India',
    state: 'MZ',
    topic: 'Farm & Food',
    subtopic: 'Mizoram Intodelhna Programme (2002)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2002,
    asOf: '2026-09',
    govt: 'MNF',
    question:
      "Mizoram's MNF government replaced the old land-use scheme with the Mizoram Intodelhna Programme in 2002. How much did each of its 53,288 beneficiary families get?",
    options: ['₹11,000', '₹5,500', '₹3,000', '₹1,100'],
    correctIndex: 0,
    explanation:
      "Frontline reports that Zoramthanga's government discontinued the New Land Use Policy, first run in four blocks from 1985, and gave ₹11,000 each to 53,288 families under MIP, ₹30.38 crore in all. The Congress's later NLUP offered ₹1.26 lakh per beneficiary over five years.",
    sourceUrl: 'https://frontline.thehindu.com/politics/playing-the-piper/article5389646.ece',
    sourceLabel: 'Frontline — Playing the Piper (27 Nov 2013)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Zoramthanga', role: 'Chief Minister, Mizoram', party: 'MNF' }],
    outcome: 'The MNF lost the 2008 election: the Congress won 32 of 40 seats on its promise of a new land-use policy, and the MNF three (Frontline).',
  },
  {
    id: 'hdb325',
    domain: 'civics',
    region: 'India',
    state: 'MZ',
    topic: 'Farm & Food',
    subtopic: 'New Land Use Policy (2011)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2011,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Mizoram's New Land Use Policy, launched in January 2011 to wean farmers off jhum (slash-and-burn) cultivation, was the flagship of which chief minister?",
    options: ['Zoramthanga (MNF)', 'Lal Thanhawla (Congress)', 'Lalduhoma (ZPM)', 'Laldenga (MNF)'],
    correctIndex: 1,
    explanation:
      'Lal Thanhawla said in Aug 2013 that the ₹2,873.13-crore NLUP had met its target of 1.2 lakh farmers in three years, at ₹1.26 lakh per beneficiary over five years. The Congress had won 32 of 40 seats in 2008 on the promise, after the mautam bamboo flowering destroyed crops of 1.3 lakh families.',
    sourceUrl: 'https://frontline.thehindu.com/politics/playing-the-piper/article5389646.ece',
    sourceLabel: 'Frontline — Playing the Piper (27 Nov 2013)',
    sources: [
      'https://www.newindianexpress.com/elections/mizoram-elections/2018/Dec/12/mnf-bounces-back-to-power-in-mizoram-congress-loses-last-bastion-in-northeast-1910214.html',
    ],
    tags: ['distribution'],
    enactedBy: [{ name: 'Lal Thanhawla', role: 'Chief Minister, Mizoram', party: 'INC' }],
    outcome: 'The Congress was re-elected in Nov 2013 with 34 of 40 seats, then fell to five in 2018 as the MNF won 26 (NIE).',
  },
  {
    id: 'hdb326',
    domain: 'civics',
    region: 'India',
    state: 'MZ',
    topic: 'Jobs & Economy',
    subtopic: 'SEDP family assistance',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2023,
    asOf: '2026-09',
    govt: 'MNF',
    question:
      "Mizoram's MNF had promised families up to ₹3 lakh under its Socio-Economic Development Programme. By 2023, how much had each of the first 60,000 families got, per the deputy CM?",
    options: ['₹10,000', '₹25,000', '₹50,000', '₹1 lakh'],
    correctIndex: 2,
    explanation:
      "Deputy CM Tawnluia said about 60,000 families got ₹50,000 each and another 60,000 got ₹25,000 in a second phase; the government blamed the pandemic for the missing third phase. CM Zoramthanga's Aug 2022 'family-oriented SEDP' was to give ₹50,000 each to 1,500 beneficiaries in each of the 40 constituencies, in ₹25,000 instalments.",
    sourceUrl: 'https://www.thequint.com/opinion/mizoram-will-zpm-break-the-pattern-of-governments-changing-after-two-terms',
    sourceLabel: 'The Quint — Mizoram: Will ZPM break the pattern of governments changing after two terms? (6 Nov 2023)',
    sources: [
      'https://www.indiatodayne.in/mizoram/story/mizoram-cm-launches-family-oriented-sedp-cover-60000-beneficiaries-437764-2022-08-20',
      'https://www.newindianexpress.com/india/2023/Dec/05/mizoram-zpm-govt-to-be-sworn-in-on-december-8-ex-cm-zoramthanga-quits-as-mnf-chief-2638866.html',
    ],
    tags: ['distribution'],
    enactedBy: [{ name: 'Zoramthanga', role: 'Chief Minister, Mizoram', party: 'MNF' }],
    outcome:
      'The MNF lost the 7 Nov 2023 election: the ZPM won 27 of 40 seats and the MNF 10, and Zoramthanga resigned as party president (NIE).',
  },
  {
    id: 'hdb327',
    domain: 'civics',
    region: 'India',
    state: 'MZ',
    topic: 'Farm & Food',
    subtopic: "Bana Kaih ('handholding', 2024)",
    kind: 'scheme',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'ZPM',
    question:
      "Mizoram's ZPM government launched its flagship 'Bana Kaih' (handholding) scheme in Sept 2024. Which crops did it start buying from farmers at state support prices?",
    options: [
      'Rice, maize, soybean and mustard',
      'Tea, rubber, coffee and areca nut',
      'Pineapple, orange, banana and passion fruit',
      'Ginger, turmeric, Mizo chilli and broomsticks',
    ],
    correctIndex: 3,
    explanation:
      "CM Lalduhoma, who also holds finance, raised Bana Kaih's allocation 75%, from ₹200 crore in 2024-25 to ₹350 crore in 2025-26. It backs farmers and small entrepreneurs ('progress partners'), including loans of up to ₹50 lakh through partner banks.",
    sourceUrl: 'https://www.thehindu.com/news/national/mizoram/mizoram-govt-presents-budget-allocation-for-flagship-scheme/article69290190.ece',
    sourceLabel: 'The Hindu — Mizoram Government presents ₹15,198 crore budget, allocates 75% more in flagship scheme (4 Mar 2025)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Lalduhoma', role: 'Chief Minister, Mizoram', party: 'ZPM' }],
    outcome: '₹350 crore budgeted for 2025-26 and a promise to keep buying the four crops; the same budget announced ₹5 lakh universal health insurance from April 2025.',
  },

  // ───────────────────────── Tripura ─────────────────────────
  {
    id: 'hdb328',
    domain: 'civics',
    region: 'India',
    state: 'TR',
    topic: 'Jobs & Economy',
    subtopic: 'MGNREGA work days (Left era)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2016,
    asOf: '2026-09',
    govt: 'CPI(M)',
    question:
      'Until 2015-16, Left-ruled Tripura led all states in average MGNREGA work days per rural household. For how many consecutive years had it held the top spot?',
    options: ['Seven', 'Ten', 'Five', 'Three'],
    correctIndex: 0,
    explanation:
      'A Union Rural Development Ministry report (via IANS) showed Tripura slipping to second in 2016-17 with 79.88 days per household, behind Mizoram\'s 88.43; the national average was 45.21. CM Manik Sarkar accused the Centre of trying to scuttle the scheme; a ministry official denied it.',
    sourceUrl: 'https://www.thequint.com/news/india/mgnrega-northeast-mizoram-tripura-sikkim-manipur-assam',
    sourceLabel: 'The Quint (IANS) — MGNREGA Mystery: 3 NE States Among Top Performers, 2 at Bottom (6 Apr 2017)',
    sources: ['https://indianexpress.com/article/north-east-india/tripura/tripura-election-results-2018-full-list-of-winners-5084676/'],
    tags: ['distribution'],
    outcome:
      'Sarkar said central allocations for 2017-18 would allow only 38–42 days per household. The Left Front lost power in March 2018 after 25 years.',
  },
  {
    id: 'hdb329',
    domain: 'civics',
    region: 'India',
    state: 'TR',
    topic: 'Farm & Food',
    subtopic: 'Ration-card clean-up (2018)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2018,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Months after taking office in 2018, Tripura's BJP–IPFT government said its digitisation of the public distribution system had found about how many fake ration cards?",
    options: ['6,234', '62,340', '1.24 lakh', '3.1 lakh'],
    correctIndex: 1,
    explanation:
      'Law Minister Ratan Lal Nath said 62,340 cards and 2,80,776 PDS consumers were fake: genuine cards stood at 8,99,706 against 9,62,046 registered under the Left Front, and beneficiaries fell from 39.4 lakh to 36.6 lakh. New social-pension enrolments were paused during checks. These are the government\'s figures; the report carried no response from the Left.',
    sourceUrl:
      'https://indianexpress.com/article/north-east-india/tripura/tripura-identifies-60000-fake-ration-card-holders-detects-ineligible-social-security-pension-beneficiaries-5355053/',
    sourceLabel: "The Indian Express — Tripura govt identifies 60,000 fake ration card holders, detects 'ineligible' pension beneficiaries (13 Sep 2018)",
    tags: ['distribution'],
    enactedBy: [{ name: 'Biplab Kumar Deb', role: 'Chief Minister, Tripura', party: 'BJP' }],
    outcome: 'Social-security pensioners paid fell from 4.19 lakh registered to 4.14 lakh by July 2018, while the BJP said it would still raise pensions from ₹700 to ₹2,000 as promised.',
  },
  {
    id: 'hdb330',
    domain: 'civics',
    region: 'India',
    state: 'TR',
    topic: 'Welfare & Subsidies',
    subtopic: 'Social pension to ₹2,000 (2022)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2022,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Tripura's BJP government raised social pensions to ₹2,000 a month in September 2022, about five months before the Assembly poll. What had they paid under the Left Front in 2018?",
    options: ['₹300', '₹500', '₹700', '₹1,000'],
    correctIndex: 2,
    explanation:
      "The BJP's 2018 Vision Document promised to lift pensions from ₹700 to ₹2,000 (The Indian Express, 2018). In Dec 2024 the Congress alleged 40,622 people had been wrongly excluded, that pensioners fell from 4.19 lakh to 3.78 lakh and that the rise was paid for by cutting names; the government had said in 2018 it was removing fake beneficiaries.",
    sourceUrl:
      'https://timesofindia.indiatimes.com/city/guwahati/tripura-congress-slams-bjp-for-excluding-thousands-from-pension-benefits/articleshow/116148200.cms',
    sourceLabel: 'The Times of India — Cong accuses BJP govt in Tripura of depriving poor of social benefits (9 Dec 2024)',
    sources: [
      'https://indianexpress.com/article/north-east-india/tripura/tripura-identifies-60000-fake-ration-card-holders-detects-ineligible-social-security-pension-beneficiaries-5355053/',
      'https://frontline.thehindu.com/politics/tripura-assembly-election-2023-bjp-returns-as-tipra-motha-plays-spoilsport-for-left-congress-combine/article66576255.ece',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Manik Saha', role: 'Chief Minister, Tripura', party: 'BJP' }],
    outcome: 'The BJP–IPFT kept Tripura on 16 Feb 2023 with 33 of 60 seats (BJP 32), down from 44 in 2018; TIPRA Motha won 13 and the Left–Congress 14 (Frontline).',
    poll: { label: 'Tripura Assembly 2023', month: '2023-02', result: 'BJP–IPFT won 33 of 60 seats; TIPRA Motha 13, Left–Congress 14' },
  },

  // ───────────────────────── Sikkim, Nagaland, Meghalaya, Arunachal ─────────────────────────
  {
    id: 'hdb331',
    domain: 'civics',
    region: 'India',
    state: 'SK',
    topic: 'Jobs & Economy',
    subtopic: "'One Family, One Job' (2019)",
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2019,
    asOf: '2026-09',
    govt: 'Other',
    question:
      "Sikkim's SDF government launched 'One Family, One Job' on 12 Jan 2019, 89 days before the Assembly poll. How many temporary appointment letters were issued that day?",
    options: ['1,772', '3,200', '7,500', '11,772'],
    correctIndex: 3,
    explanation:
      'CM Pawan Chamling handed letters to two people from each of the 32 constituencies before officials issued the rest. The government had promised 20,000 temporary jobs, mostly Group C and D posts, to families with no government job, and said farm loans would be waived. Salaries were budgeted for only 89 days of 2018-19.',
    sourceUrl:
      'https://www.indiatoday.in/education-today/gk-%26-current-affairs/story/sikkim-launches-one-family-one-job-scheme-1430035-2019-01-13',
    sourceLabel: "India Today — Sikkim launches 'One Family, One Job' scheme (13 Jan 2019)",
    sources: [
      'https://www.indiatodayne.in/sikkim/story/sikkim-only-43-employees-regularised-in-2022-23-under-the-one-family-one-job-scheme-560029-2023-05-18',
      'https://www.indiatodayne.in/sikkim/story/sikkim-cm-announces-regularisation-policy-2024-20000-job-vacancies-to-be-regularised-by-february-25-886473-2024-02-14',
      'https://www.newindianexpress.com/india/2024/Jun/02/bjp-capitalises-on-weakened-opposition-in-arunachal-welfare-schemes-do-wonders-for-skm-in-sikkim',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Pawan Kumar Chamling', role: 'Chief Minister, Sikkim', party: 'SDF' }],
    outcome:
      'The SDF lost in April 2019 (SKM 17, SDF 15). Under the SKM only 191 of these staff were regularised in 2021-22 and 43 in 2022-23; in Feb 2024, before the next poll, it announced regularising 20,000 temporary workers including them.',
    poll: { label: 'Sikkim Assembly 2019', month: '2019-04', gapDays: 89, result: 'SKM won 17 of 32 seats; SDF 15, ending 25 years of SDF rule' },
  },
  {
    id: 'hdb332',
    domain: 'civics',
    region: 'India',
    state: 'NL',
    topic: 'Health',
    subtopic: "CM's Health Insurance Scheme (2022)",
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDPP',
    question:
      "Nagaland's Chief Minister's Health Insurance Scheme, launched in October 2022, covers government employees, pensioners and MLAs for up to how much per family a year?",
    options: ['₹20 lakh', '₹10 lakh', '₹7.5 lakh', '₹5 lakh'],
    correctIndex: 0,
    explanation:
      "Other residents not covered by Ayushman Bharat get ₹5 lakh per family, as under Ayushman Bharat. The state budgeted ₹69 crore in premium for the first year with Oriental Insurance. The National Health Authority's CEO said Nagaland became the second north-eastern state with universal health cover.",
    sourceUrl: 'https://bfsi.economictimes.indiatimes.com/news/insurance/nagaland-launches-universal-health-insurance-scheme/94871385',
    sourceLabel: 'ET BFSI (PTI) — Nagaland launches universal health insurance scheme (15 Oct 2022)',
    sources: [
      'https://ipr.nagaland.gov.in/nagaland-launches-chief-ministers-health-insurance-scheme',
      'https://frontline.thehindu.com/politics/nagaland-assembly-election-2023-neiphiu-rio-back-for-record-fifth-term-as-ndpp-bjp-alliance-emerges-stronger/article66579700.ece',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Neiphiu Rio', role: 'Chief Minister, Nagaland', party: 'NDPP' }],
    outcome:
      'Four months later the NDPP–BJP alliance won 37 of 60 seats; the NDPP rose from 18 to 25 and Neiphiu Rio began a record fifth term (Frontline).',
    poll: { label: 'Nagaland Assembly 2023', month: '2023-02', gapDays: 136, result: 'NDPP–BJP won 37 of 60 seats (NDPP 25, BJP 12)' },
  },
  {
    id: 'hdb333',
    domain: 'civics',
    region: 'India',
    state: 'ML',
    topic: 'Jobs & Economy',
    subtopic: 'CM-Elevate (2023)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2023,
    asOf: '2026-09',
    govt: 'NPP',
    question:
      "Under Meghalaya's CM-Elevate scheme for young entrepreneurs, launched in October 2023, up to what share of a venture's cost can the state give as grant or subsidy?",
    options: ['50%', '75%', '90%', '100%'],
    correctIndex: 1,
    explanation:
      'CM Conrad K. Sangma launched it to back 20,000 beneficiaries with ₹300 crore over five years; the rest of each project is financed by bank loans. He said over 70,000 young people enter the workforce each year and the government cannot absorb everyone: close to 1,500 are employed through the MPSC and district committees.',
    sourceUrl:
      'https://m.economictimes.com/jobs/government-jobs/meghalaya-cm-launches-cm-elevate-program-to-address-youth-unemployment/articleshow/104502176.cms',
    sourceLabel: "The Economic Times — Meghalaya CM launches 'CM Elevate' program to address youth unemployment (17 Oct 2023)",
    sources: [
      'https://government.economictimes.indiatimes.com/news/policy/meghalaya-govt-on-mission-to-promote-entrepreneurship-through-cm-elevate-initiative-says-chief-minister-sangma/107583190',
    ],
    tags: ['distribution'],
    enactedBy: [{ name: 'Conrad K. Sangma', role: 'Chief Minister, Meghalaya', party: 'NPP' }],
    outcome: 'The first cheques went to about 40 beneficiaries in February 2024; the target is 20,000-plus entrepreneurs in three to four years (ET Government).',
  },
  {
    id: 'hdb334',
    domain: 'civics',
    region: 'India',
    state: 'AR',
    topic: 'Welfare & Subsidies',
    subtopic: 'Dulari Kanya revamp (2025)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Arunachal Pradesh's cabinet revamped the Dulari Kanya scheme for girls in February 2025. What is the total benefit now, counting the birth deposit and the Class 11 payment?",
    options: ['₹20,000', '₹30,000', '₹50,000', '₹1 lakh'],
    correctIndex: 2,
    explanation:
      "The fixed deposit for a girl born in a hospital or health centre rose from ₹20,000 to ₹30,000, maturing at 18, plus a new ₹20,000 paid by direct transfer on admission to Class 11, the CM's office said after Pema Khandu's cabinet met at Nyapin on 17 Feb 2025.",
    sourceUrl:
      'https://www.aninews.in/news/national/general-news/arunachal-cabinet-approves-schemes-for-women-youth-and-state-development20250218095929',
    sourceLabel: 'ANI — Arunachal cabinet approves schemes for Women, Youth, and State Development (18 Feb 2025)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Pema Khandu', role: 'Chief Minister, Arunachal Pradesh', party: 'BJP' }],
  },
]);
