// HISAAB DO — Distribution, North & Hindi belt (ids hdb100–hdb199).
// Cash and in-kind transfers in UP, Uttarakhand, HP, Punjab, Haryana, Delhi, J&K, Rajasthan, Bihar and
// Jharkhand, 2002–2026: who passed them, which party, what they cost and what happened next.
// Every item is tagged 'distribution'; items announced or paid in the run-up to a poll are also tagged
// 'pre-election' and carry `poll`. Research notes: docs/hisaab/research/dist-north-notes.md.
// Status of every item verified September 2026 (asOf '2026-09').

export const HISAAB_DIST_NORTH = Object.freeze([
  // ───────────────────────── 2000–2004 ─────────────────────────
  {
    id: 'hdb100',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Energy & Mining',
    subtopic: 'Free farm power suspended (2002–05)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2002,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'Free electricity for all Punjab farmers, extended by the Badal government in 1997, was discontinued from October 2002 to November 2005. Who was chief minister then?',
    options: ['Parkash Singh Badal (SAD)', 'Amarinder Singh (Congress)', 'Rajinder Kaur Bhattal (Congress)', 'Sukhbir Singh Badal (SAD)'],
    correctIndex: 1,
    explanation:
      'Congress CM Rajinder Kaur Bhattal began the farm-power subsidy in January 1997 for farmers with up to seven acres; Parkash Singh Badal (SAD) extended it to all after taking over that year. It was discontinued from October 2002 to November 2005 under Amarinder Singh, then restored, and has run without a break since Badal returned in 2007.',
    sourceUrl: 'https://indianexpress.com/article/cities/chandigarh/power-subsidy-social-security-architect-populist-schemes-8576206/',
    sourceLabel: 'The Indian Express — Power subsidy to social security: Parkash Singh Badal, the architect of populist schemes (26 Apr 2023)',
    sources: ['https://indianexpress.com/article/cities/chandigarh/punjab-budget-2026-women-monthly-assistance-mawan-dhiyan-satikar-yojana-10571040/'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Amarinder Singh', role: 'Chief Minister, Punjab', party: 'INC' }],
    outcome:
      'Free farm power was restored in November 2005 and has continued since 2007; Punjab’s 2026-27 budget still sets aside ₹7,715 crore for the agricultural power subsidy.',
  },
  {
    id: 'hdb101',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Welfare & Subsidies',
    subtopic: 'Old Age Samman Allowance — 2004 hike',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2004,
    asOf: '2026-09',
    govt: 'Other',
    question:
      'Haryana raised its old-age allowance from ₹200 to ₹300 a month from November 2004, about three months before the February 2005 Assembly poll. Which party was in power?',
    options: ['Indian National Lok Dal (INLD)', 'Congress', 'BJP', 'Haryana Vikas Party'],
    correctIndex: 0,
    explanation:
      'The state’s own rate table shows ₹100 a month until Oct 1999, ₹200 from Nov 1999 and ₹300 from Nov 2004 — both rises under Om Prakash Chautala’s INLD government. Every later government kept raising it: ₹1,000 (2014), ₹3,000 (2024) and ₹3,200 (Nov 2025).',
    sourceUrl: 'https://socialjusticehry.gov.in/old-age-samman-allowance-scheme/',
    sourceLabel: 'Government of Haryana, Social Justice & Empowerment — Old Age Samman Allowance Scheme (rate history, updated Jul 2026)',
    sources: [
      'https://www.rediff.com/news/report/haryana-election-inld-puts-up-worst-ever-show-in-haryana/20191024.htm',
      'https://www.newindianexpress.com/india/2024/Sep/23/congress-on-course-to-sweep-haryana-polls-set-to-repeat-2005-performance-surjewala',
      'https://en.wikipedia.org/wiki/2005_Haryana_Legislative_Assembly_election',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Om Prakash Chautala', role: 'Chief Minister, Haryana', party: 'INLD' }],
    outcome:
      'The INLD lost the 3 Feb 2005 poll: Congress won 67 of 90 seats and the INLD fell to 9. The next government, under Bhupinder Singh Hooda, raised the allowance again to ₹500–700 from March 2009.',
    poll: { label: 'Haryana Assembly 2005', month: '2005-02', gapDays: 94, result: 'Congress won 67 of 90 seats; INLD 9' },
  },

  // ───────────────────────── 2005–2009 ─────────────────────────
  {
    id: 'hdb102',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Welfare & Subsidies',
    subtopic: 'Rakshak Yojana (girl child)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2005,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'A review done for the Planning Commission found that Punjab’s girl-child cash scheme, launched in 2005 with a lot of publicity, had how many beneficiaries by March 2010?',
    options: ['3.06 lakh', '30,600', '3,060', '306'],
    correctIndex: 3,
    explanation:
      'T.V. Sekher of the International Institute for Population Sciences, working with UNFPA as an input to the 12th Plan, reviewed 15 girl-child cash-transfer schemes. Frontline reported he found Punjab’s Rakshak Yojana had just 306 beneficiaries up to March 2010, and that paperwork and conditions blunted such schemes; Rajasthan’s Rajalakshmi had been discontinued.',
    sourceUrl: 'https://frontline.thehindu.com/other/article30164012.ece',
    sourceLabel: 'Frontline — Off target (27 Jan 2012)',
    tags: ['distribution'],
    outcome:
      'About 306 beneficiaries in roughly five years, per the IIPS–UNFPA review, which said the effect of such schemes on parents’ attitudes to daughters “cannot be fully established”.',
  },
  {
    id: 'hdb103',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Jobs & Economy',
    subtopic: 'Unemployment allowance (2006)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2006,
    asOf: '2026-09',
    govt: 'SP',
    question:
      'In his February 2006 budget, Mulayam Singh Yadav promised unemployed graduates registered at UP’s employment exchanges an allowance of how much a month?',
    options: ['₹300', '₹1,000', '₹500', '₹1,500'],
    correctIndex: 2,
    explanation:
      'Hindustan Times reported the SP government estimated ₹250 crore a year, and that the Prime Minister had turned down a request for central funds. Registrations surged — Agra’s graduate sign-ups rose about tenfold in a month. The BSP government later scrapped the dole; Akhilesh Yadav revived it at ₹1,000 a month in 2012.',
    sourceUrl: 'https://www.hindustantimes.com/india/unemployment-dole/story-4nNvKmDAYGRN0MfOx1iDKP.html',
    sourceLabel: 'Hindustan Times — Unemployment dole (26 Mar 2006)',
    sources: [
      'https://www.bhaskar.com/news/up-luck-bjp-alleges-against-akhilesh-yadav-government-by-cag-report-5601325-pho.html',
      'https://www.newindianexpress.com/india/2012/Sep/10/unemployment-dole-in-up-404601.html',
    ],
    tags: ['distribution'],
    enactedBy: [{ name: 'Mulayam Singh Yadav', role: 'Chief Minister, Uttar Pradesh', party: 'SP' }],
    outcome:
      'Registrations jumped (Agra: 153 graduates in Jan 2006, about 1,500 in Feb). Scrapped by the BSP after 2007 and revived by the SP in 2012 — when the CAG later faulted how the cheques were handed out.',
  },
  {
    id: 'hdb104',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Education & Exams',
    subtopic: 'Mukhyamantri Cycle Yojana',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2006,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      'Bihar’s Mukhyamantri Cycle Yojana, launched in 2006 by Nitish Kumar’s JD(U)–BJP government, gave each Class 9 girl how much to buy a bicycle?',
    options: ['₹1,000', '₹2,000', '₹3,500', '₹5,000'],
    correctIndex: 1,
    explanation:
      'The state paid cash (later by DBT) instead of buying cycles, with a 75% attendance rule, and opened it to boys in 2009-10. It counts 1.56 lakh girls paid in 2007-08 and 6.03 lakh girls plus 5.26 lakh boys in 2024-25. Some students told The Indian Express in 2025 that recent payments had not reached them; officials pointed to the eligibility checks.',
    sourceUrl: 'https://indianexpress.com/article/long-reads/two-decades-ago-nitish-distributed-cycles-to-girls-in-class-9-where-are-they-now-10360460/',
    sourceLabel: 'The Indian Express — Two decades ago, Nitish distributed cycles to girls in Class 9. Where are they now? (Nov 2025)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Nitish Kumar', role: 'Chief Minister, Bihar', party: 'JD(U)' }],
    outcome:
      'Beneficiaries grew from 1.56 lakh girls (2007-08) to about 11.3 lakh students (2024-25); the model was copied by other states and by seven African countries, including Zambia.',
  },
  {
    id: 'hdb105',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Farm & Food',
    subtopic: 'Atta-dal scheme (2007)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2007,
    asOf: '2026-09',
    govt: 'Other',
    question:
      'Punjab’s atta-dal scheme, launched by the SAD–BJP government on Independence Day 2007, first sold wheat to poor families at what price?',
    options: ['₹1 a kg', '₹2 a kg', '₹10 a kg', '₹4 a kg'],
    correctIndex: 3,
    explanation:
      'The Tribune records wheat at ₹4 a kg and chana dal at ₹20 a kg under Parkash Singh Badal’s 2007 scheme. It was revised several times and folded into the National Food Security Act; wheat has been free since Covid. In Feb 2026 the AAP government added free quarterly ration kits (Meri Rasoi) for about 40 lakh NFSA families.',
    sourceUrl: 'https://www.tribuneindia.com/news/top-headlines/mann-govt-to-provide-free-ration-kits-to-40l-families-ahead-of-poll/',
    sourceLabel: 'The Tribune — Mann govt to provide free ration kits to 40L families ahead of poll (24 Feb 2026)',
    sources: ['https://indianexpress.com/article/cities/chandigarh/power-subsidy-social-security-architect-populist-schemes-8576206/'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Parkash Singh Badal', role: 'Chief Minister, Punjab', party: 'SAD' }],
    outcome:
      'Still running as free NFSA wheat. The Tribune reports about 23 lakh NFSA beneficiaries were weeded out as ineligible in two years, and ₹1,000 crore was set aside for the new ration kits.',
  },
  {
    id: 'hdb106',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Welfare & Subsidies',
    subtopic: 'Mahamaya Garib Balika Ashirvad Yojana',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2009,
    asOf: '2026-09',
    govt: 'BSP',
    question:
      'Announced on her birthday in January 2009, Mayawati’s Mahamaya Garib Balika Ashirvad Yojana put what in the name of each girl born to a poor family?',
    options: [
      'A ₹22,000 savings certificate meant to grow to ₹1 lakh at 18',
      'A ₹5,000 cash grant at birth',
      'A ₹500 monthly stipend until she turns 18',
      'A housing plot in her mother’s name',
    ],
    correctIndex: 0,
    explanation:
      'The Indian Express reported both of Mayawati’s birthday schemes were running within 20 days “in the run-up to the Lok Sabha polls”, at about ₹2,000 crore: a ₹22,000 NSC for BPL girls born on or after 15 Jan 2009 (paid at 18 if schooled and unmarried), and ₹25,000 plus a bicycle for BPL girls in Classes 11–12.',
    sourceUrl: 'https://indianexpress.com/article/cities/lucknow/announced-on-maya-s-birthday-schemes-execut/',
    sourceLabel: 'The Indian Express — Announced on Maya’s birthday, schemes executed in 20 days (5 Feb 2009)',
    sources: ['https://frontline.thehindu.com/cover-story/article30187061.ece'],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Mayawati', role: 'Chief Minister, Uttar Pradesh', party: 'BSP' }],
    outcome:
      'Both schemes cost about ₹2,000 crore. In the 2009 Lok Sabha poll the ruling BSP won 20 of UP’s 80 seats, behind the SP (23) and just ahead of the Congress (21).',
    poll: { label: 'Lok Sabha 2009 (Uttar Pradesh)', month: '2009-04', gapDays: 91, result: 'BSP won 20 of UP’s 80 seats; SP 23, Congress 21, BJP 10' },
  },
  {
    id: 'hdb107',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Welfare & Subsidies',
    subtopic: 'Old Age Samman Allowance — 2009 hike',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2009,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'Months before the October 2009 Assembly poll, Bhupinder Singh Hooda’s government raised Haryana’s old-age allowance from ₹300 to what, from 1 March 2009?',
    options: ['₹400 a month', '₹1,000 a month', '₹500–700 a month', '₹1,200 a month'],
    correctIndex: 2,
    explanation:
      'The Social Justice department’s rate history shows ₹300 from Nov 2004, ₹500–700 from 1 Mar 2009 and ₹1,000 from 1 Jan 2014, both hikes under Hooda’s Congress government. Rules have since been eased: anyone 60 or older whose own and spouse’s income is up to ₹3 lakh a year now qualifies.',
    sourceUrl: 'https://socialjusticehry.gov.in/old-age-samman-allowance-scheme/',
    sourceLabel: 'Government of Haryana, Social Justice & Empowerment — Old Age Samman Allowance Scheme (rate history, updated Jul 2026)',
    sources: [
      'https://frontline.thehindu.com/cover-story/article30185748.ece',
      'https://en.wikipedia.org/wiki/2009_Haryana_Legislative_Assembly_election',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Bhupinder Singh Hooda', role: 'Chief Minister, Haryana', party: 'INC' }],
    outcome:
      'The Congress won 40 of 90 seats on 13 Oct 2009 and Hooda formed the next government; the allowance rose again to ₹1,000 a month from January 2014.',
    poll: { label: 'Haryana Assembly 2009', month: '2009-10', gapDays: 226, result: 'Congress won 40 of 90 seats and formed the government; INLD 31' },
  },

  // ───────────────────────── 2010–2014 ─────────────────────────
  {
    id: 'hdb108',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Welfare & Subsidies',
    subtopic: 'Mahamaya Garib Arthik Madad Yojana',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2010,
    asOf: '2026-09',
    govt: 'BSP',
    question:
      'Mayawati’s Mahamaya Garib Arthik Madad Yojana, launched in November 2010 for about 31 lakh people in poor (BPL) families, promised each beneficiary how much a month?',
    options: ['₹150', '₹300', '₹500', '₹1,000'],
    correctIndex: 1,
    explanation:
      'It was paid in two half-yearly instalments of ₹1,800 into accounts opened in the name of the woman head of each BPL family. Mayawati said it targeted poor families left out of central benefits, and would cost about ₹535 crore in its first phase; it was launched in all 72 districts at once.',
    sourceUrl: 'https://www.thehindu.com/news/national/other-states/Mayawati-launches-welfare-scheme-for-poor/article15672368.ece',
    sourceLabel: 'The Hindu — Mayawati launches welfare scheme for poor (2 Nov 2010)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Mayawati', role: 'Chief Minister, Uttar Pradesh', party: 'BSP' }],
    outcome:
      'Aimed at about 31 lakh people in BPL families, with ₹535 crore set aside for the first phase; the first ₹1,800 instalment covered October 2010 to March 2011.',
  },
  {
    id: 'hdb109',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Health',
    subtopic: 'Mukhyamantri Nishulk Dawa Yojana',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2011,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'Which chief minister launched Rajasthan’s scheme of free essential drugs at government health centres on 2 October 2011?',
    options: ['Vasundhara Raje (BJP)', 'Bhairon Singh Shekhawat (BJP)', 'Bhajan Lal Sharma (BJP)', 'Ashok Gehlot (Congress)'],
    correctIndex: 3,
    explanation:
      'Gehlot’s Congress government set up the Rajasthan Medical Services Corporation in May 2011 to buy generic drugs centrally, began free medicines on 2 Oct 2011 and added free tests from April 2013. It ran through the BJP’s 2013–18 term: by Dec 2017 the state counted 52.4 crore beneficiary visits, repeat visits included.',
    sourceUrl: 'https://indianexpress.com/article/explained/explained-rajasthan-free-medicine-scheme-5827614/',
    sourceLabel: 'The Indian Express — Explained: What is Rajasthan’s free medicine scheme (13 Jul 2019)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Ashok Gehlot', role: 'Chief Minister, Rajasthan', party: 'INC' }],
    outcome:
      '52.4 crore free-medicine beneficiaries and 9.41 crore free tests logged from Oct 2011 to Dec 2017; the 2019 budget widened the list from 608 to 712 medicines and from 70 to 90 tests.',
  },
  {
    id: 'hdb110',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Jobs & Economy',
    subtopic: 'Berozgari bhatta — CAG audit',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2012,
    asOf: '2026-09',
    govt: 'SP',
    question:
      'The CAG found UP’s Samajwadi Party government spent ₹15.06 crore in 2012-13 on functions to hand out unemployment-allowance cheques. What were the cheques worth in all?',
    options: ['₹5.2 crore', '₹75 crore', '₹20.58 crore', '₹150 crore'],
    correctIndex: 2,
    explanation:
      'The audit, tabled in May 2017, said the scheme required deposits straight into bank accounts, yet ₹8.07 crore went on seating and refreshments and ₹6.99 crore on bussing about 1.26 lakh beneficiaries to events, many with CM Akhilesh Yadav. The government accepted the figures but argued payment through bank accounts was “not binding”.',
    status:
      'CAG audit finding (report tabled in the UP Assembly, May 2017), not a court finding; no case against any person reported in sources checked (Sept 2026). The then government’s reply is recorded in the report.',
    people: ['Akhilesh Yadav'],
    sourceUrl: 'https://indianexpress.com/article/india/to-distribute-rs-20-crore-akhilesh-govt-splurged-rs-15-crore-on-functions-cag-4662910/',
    sourceLabel: 'The Indian Express — To distribute Rs 20 crore, Akhilesh govt splurged Rs 15 crore on functions: CAG (19 May 2017)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Akhilesh Yadav', role: 'Chief Minister, Uttar Pradesh', party: 'SP' }],
    outcome:
      'The CAG called ₹15.06 crore in 69 districts “avoidable” against ₹20.58 crore actually paid out; the allowance had been revived in May 2012 at ₹1,000 a month.',
  },
  {
    id: 'hdb111',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Education & Exams',
    subtopic: 'Free laptops (2012–14) — CAG audit',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2013,
    asOf: '2026-09',
    govt: 'SP',
    question:
      'Per a CAG report tabled in March 2015, about how many eligible Class 12 students were left without a laptop under the SP government’s 2012–14 free-laptop scheme?',
    options: ['4.55 lakh', '15,000', '1.2 lakh', '14.35 lakh'],
    correctIndex: 0,
    explanation:
      'HP supplied 14.81 lakh laptops for ₹2,822.71 crore and 14.35 lakh were handed out, the CAG said, while ₹598.33 crore lay unspent and three CM-attended distribution events cost ₹7.47 crore against ₹1.50 crore allowed. A companion free-tablet plan was dropped despite ₹604.78 crore budgeted.',
    status:
      'CAG audit finding (tabled in the UP Assembly, Mar 2015), not a court finding; no case against any person and no SP response reported in sources checked (Sept 2026).',
    sourceUrl: 'https://indianexpress.com/article/cities/lucknow/free-laptops-cag-punches-holes-says-excessively-funded-yet-short-of-target/',
    sourceLabel: 'The Indian Express — Free laptops: CAG punches holes, says excessively funded yet short of target (27 Mar 2015)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Akhilesh Yadav', role: 'Chief Minister, Uttar Pradesh', party: 'SP' }],
    outcome:
      '14.35 lakh laptops distributed for a supply bill of ₹2,822.71 crore; 4.55 lakh eligible students missed out and the mandatory 5% beneficiary check was not done, per the CAG.',
  },
  {
    id: 'hdb112',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Banking & Finance',
    subtopic: 'Bhamashah card (relaunch 2014)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2014,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'Relaunched by Vasundhara Raje on 15 August 2014, Rajasthan’s Bhamashah card promised families free health insurance worth how much for major illnesses?',
    options: ['₹50,000', '₹3 lakh', '₹1 lakh', '₹5 lakh'],
    correctIndex: 1,
    explanation:
      'Business Standard (via Rediff): cover of ₹30,000 for routine and ₹3 lakh for major illnesses, with pensions, rations and scholarships paid into an account only the woman head of the family could operate. Raje said the idea began in her 2003–08 term, when about 50 lakh people were covered, before her Congress successor Ashok Gehlot discontinued it.',
    sourceUrl: 'https://www.rediff.com/business/slide-show/slide-show-1-bhamashah-a-scheme-to-trump-aadhaar-in-rajasthan/20140818.htm',
    sourceLabel: 'Rediff / Business Standard — Bhamashah: A scheme to trump Aadhaar in Rajasthan (18 Aug 2014)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Vasundhara Raje', role: 'Chief Minister, Rajasthan', party: 'BJP' }],
    outcome:
      'Relaunched in Udaipur after the BJP won 163 of 200 seats in 2013; the state aimed to finish enrolling biometrics by March 2015, with an optional individual card for ₹20–25.',
  },

  // ───────────────────────── 2015–2019 ─────────────────────────
  {
    id: 'hdb113',
    domain: 'civics',
    region: 'India',
    state: 'JK',
    topic: 'Welfare & Subsidies',
    subtopic: 'Ladli Beti scheme',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2015,
    asOf: '2026-09',
    govt: 'Other',
    question:
      'Under J&K’s Ladli Beti scheme, launched by Mufti Mohammad Sayeed in September 2015, about how much is paid out when a beneficiary girl turns 21?',
    options: ['₹1 lakh', '₹2.5 lakh', '₹10 lakh', '₹6.5 lakh'],
    correctIndex: 3,
    explanation:
      'At launch the state said it would deposit ₹1,000 a month for 14 years for each eligible girl (family income under ₹75,000 a year), and she would get about ₹6.5 lakh at 21 (The Tribune, 2015). Minister Sakina Itoo said 2.03 lakh girls were enrolled by March 2026; in Aug 2026 banks had paused new accounts pending a renewed MoU and funds (ETV Bharat).',
    sourceUrl: 'https://www.etvbharat.com/en/bharat/funding-delays-and-missing-mou-stall-ladli-beti-scheme-in-jammu-kashmir-enn26080704343',
    sourceLabel: 'ETV Bharat — Funding delays and missing MoU stall Ladli Beti scheme in Jammu Kashmir (7 Aug 2026)',
    sources: ['https://www.tribuneindia.com/news/archive/community/ladli-beti-scheme-to-be-implemented-in-six-districts-130107/'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Mufti Mohammad Sayeed', role: 'Chief Minister, Jammu & Kashmir', party: 'PDP' }],
    outcome:
      'Coverage rose from 16,095 girls in 2017 to about 1.92 lakh in 2025 (CM Omar Abdullah’s 2026 budget speech), with ₹450 crore provided in 2025-26; new enrolments stalled in 2026 over funds.',
  },
  {
    id: 'hdb114',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Welfare & Subsidies',
    subtopic: 'Water bill waiver (2016)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2016,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      'Marking a year in office in February 2016, Arvind Kejriwal waived pending Delhi water bills in full for households in which property-tax categories?',
    options: ['A and B', 'C and D', 'E, F, G and H', 'All categories'],
    correctIndex: 2,
    explanation:
      'The Hindu reported a sliding waiver on pending bills: 25% for categories A and B, 50% for C, 75% for D and 100% for E to H. Free water and cheaper power were AAP’s two main 2015 poll planks; Kejriwal said the Delhi Jal Board still had a ₹176 crore surplus despite the subsidy.',
    sourceUrl: 'https://www.thehindu.com/news/cities/Delhi/One-year-of-AAP-Kejriwal-waives-Delhi-water-bills-till-November/article60580066.ece',
    sourceLabel: 'The Hindu — One year of AAP: Kejriwal waives Delhi water bills till November (14 Feb 2016)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Arvind Kejriwal', role: 'Chief Minister, Delhi', party: 'AAP' }],
    outcome:
      'Dues waived on a scale tied to property category; the government also said ₹840 crore would go to the Jal Board to lay pipelines to every colony.',
  },
  {
    id: 'hdb115',
    domain: 'civics',
    region: 'India',
    state: 'UT',
    topic: 'Welfare & Subsidies',
    subtopic: '“CM for a night” cabinet decisions (2016)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2016,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'Restored by the Uttarakhand High Court for about a day in April 2016, Harish Rawat’s cabinet took how many decisions — higher welfare pensions among them — before the Supreme Court stayed the order?',
    options: ['11', '3', '7', '25'],
    correctIndex: 0,
    explanation:
      'The Times of India reported two cabinet meetings within hours on 21–22 April 2016 that, among 11 decisions, raised social-welfare pension amounts and regularised guest teachers at ₹15,000 a month. All lapsed when the Supreme Court stayed the High Court order. Rawat said the proposals had been stuck by his government’s fall and were in the state’s interest.',
    sourceUrl: 'https://timesofindia.indiatimes.com/india/cm-for-a-night-harish-rawat-clears-11-schemes-in-2-cabinet-meets/articleshow/51950982.cms',
    sourceLabel: 'The Times of India — CM for a night, Harish Rawat clears 11 schemes in 2 cabinet meets (23 Apr 2016)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Harish Rawat', role: 'Chief Minister, Uttarakhand', party: 'INC' }],
    outcome:
      'The 11 decisions lapsed within hours when the Supreme Court stayed the High Court’s order and central rule resumed.',
  },
  {
    id: 'hdb116',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Education & Exams',
    subtopic: 'Kanya Vidya Dhan (2016)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2016,
    asOf: '2026-09',
    govt: 'SP',
    question:
      'In August 2016, six months before the UP poll, the SP government handed meritorious Class 12-pass girls how much each under the amended Kanya Vidya Dhan scheme?',
    options: ['₹10,000', '₹20,000', '₹50,000', '₹30,000'],
    correctIndex: 3,
    explanation:
      'TOI reported ₹267.30 crore released for 89,100 girls, with cheques handed out on Raksha Bandhan. Begun under Mulayam Singh Yadav, the scheme had been left out of the 2014-15 budget after the SP’s 2014 Lok Sabha defeat, along with laptops and the jobless allowance. In Sept 2026 Akhilesh Yadav promised to revive it at ₹50,000 if the SP wins in 2027.',
    sourceUrl: 'https://timesofindia.indiatimes.com/uttar-pradesh/meritorious-girl-students-to-be-given-rs-30000-in-up/articleshow/53718793.cms',
    sourceLabel: 'The Times of India — Meritorious girl students to be given Rs 30,000 in UP (16 Aug 2016)',
    sources: [
      'https://www.bhaskar.com/news/up-luck-budget-laptop-unemployment-kanya-vidya-schemes-lok-sabha-elections-4653612-nor.html',
      'https://www.prabhatkhabar.com/state/uttar-pradesh/up-akhilesh-yadav-kanya-vidya-dhan-yojana-50000-12th-pass-girls-students-scheme-benefit-2026',
      'https://www.rediff.com/news/report/up-election-bjp-sweeps-assembly-sp-cong-bsp-decimated/20170311.htm',
      'https://en.wikipedia.org/wiki/2017_Uttar_Pradesh_Legislative_Assembly_election',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Akhilesh Yadav', role: 'Chief Minister, Uttar Pradesh', party: 'SP' }],
    outcome:
      '₹267.30 crore for 89,100 girls in 2016. The SP lost the 2017 poll (BJP 312 of 403 seats); in 2026 the SP is promising to restart the scheme at ₹50,000.',
    poll: { label: 'UP Assembly 2017', month: '2017-02', gapDays: 179, result: 'BJP won 312 of 403 seats; SP 47' },
  },
  {
    id: 'hdb117',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Farm & Food',
    subtopic: 'Farm loan waiver (2017)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2017,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'At its first cabinet meeting in April 2017, Yogi Adityanath’s UP government waived small and marginal farmers’ crop loans up to what limit per farmer?',
    options: ['₹50,000', '₹1 lakh', '₹2 lakh', 'No limit'],
    correctIndex: 1,
    explanation:
      'The Hindu: ₹30,729 crore of loans up to ₹1 lakh plus about ₹6,000 crore to settle bad loans of 7 lakh farmers — about ₹36,000 crore for over 86 lakh farmers, a BJP poll promise. Akhilesh Yadav called the cap a “betrayal”. In Sept 2017 some certificates waived as little as 19 paise; the agriculture minister said the promise was being kept.',
    sourceUrl: 'https://www.thehindu.com/news/national/other-states/yogi-waives-farm-loans-up-to-rs-1-lakh/article61798537.ece',
    sourceLabel: 'The Hindu — Yogi waives farm loans up to Rs. 1 lakh (4 Apr 2017)',
    sources: ['https://www.hindustantimes.com/india-news/in-loan-waiver-shocker-farmers-of-uttar-pradesh-get-relief-of-19-paise/story-NEf9hMl6AUmBwjrUQOtL7I.html'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Yogi Adityanath', role: 'Chief Minister, Uttar Pradesh', party: 'BJP' }],
    outcome:
      'About 86 lakh farmers and ₹36,000 crore targeted. Certificate camps in Sept 2017 showed waivers of a few rupees where little was outstanding; the opposition called it a fiasco.',
  },
  {
    id: 'hdb118',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Education & Exams',
    subtopic: 'Cycle scheme — impact study',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2017,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      'A 2017 IGC working paper on Bihar’s cycle scheme found that girls who got a cycle were how much more likely to complete Class 10?',
    options: ['5%', '12%', '27.5%', '60%'],
    correctIndex: 2,
    explanation:
      'Shabana Mitra (IIM Bangalore) and Kalle Moene (University of Oslo) surveyed 20,000+ people in Bihar, Jharkhand and UP in 2016; earlier work they cite found enrolment rose over 30% in the first year. They found recipients 22.9% more likely to finish school, 5% more likely to finish college, 4.17% less likely to work in farming, and married about six months later.',
    sourceUrl: 'https://www.ideasforindia.in/topics/social-identity/wheels-of-power-long-term-effects-of-the-bihar-cycle-programme',
    sourceLabel: 'Ideas for India — Wheels of power: Long-term effects of the Bihar Cycle Programme (5 Mar 2019)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Nitish Kumar', role: 'Chief Minister, Bihar', party: 'JD(U)' }],
    outcome:
      'Named study (Mitra & Moene, IGC 2017): +27.5% Class 10 completion, +22.9% school completion and +5% college completion among girls who got the grant.',
  },
  {
    id: 'hdb119',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Farm & Food',
    subtopic: 'Crop loan waiver (Budget 2018-19)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2018,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'In her February 2018 budget, ten months before the Assembly poll, Vasundhara Raje announced a one-time crop-loan waiver for small and marginal farmers of up to how much?',
    options: ['₹50,000', '₹25,000', '₹1 lakh', '₹2 lakh'],
    correctIndex: 0,
    explanation:
      'The Times of India reported the waiver covered overdue short-term cooperative-bank loans at a cost of ₹8,000 crore, alongside a permanent farmers’ debt-relief commission and a land-revenue exemption. Congress members, demanding a complete waiver, called it a betrayal and briefly disrupted the House.',
    sourceUrl: 'https://timesofindia.indiatimes.com/india/rajasthan-announces-loan-waiver-for-farmers-to-cost-rs-8000-crore/articleshow/62887502.cms',
    sourceLabel: 'The Times of India — Rajasthan announces loan waiver for farmers, to cost Rs 8,000 crore (12 Feb 2018)',
    sources: [
      'https://indianexpress.com/article/political-pulse/in-2018-rajasthan-cong-won-by-much-higher-margins-than-bjp-swept-rural-seats-9009374/',
      'https://en.wikipedia.org/wiki/2018_Rajasthan_Legislative_Assembly_election',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Vasundhara Raje', role: 'Chief Minister, Rajasthan', party: 'BJP' }],
    outcome: 'Cost put at ₹8,000 crore. The BJP lost the 7 Dec 2018 poll: the Congress won 100 of 199 seats and the BJP 73.',
    poll: { label: 'Rajasthan Assembly 2018', month: '2018-12', gapDays: 298, result: 'Congress won 100 of 199 seats and formed the government; BJP 73' },
  },
  {
    id: 'hdb120',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Farm & Food',
    subtopic: 'Farm debt waiver (2018)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2018,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'Launching Punjab’s farm debt waiver at Mansa in January 2018, Amarinder Singh’s government offered relief on loans up to what for small and marginal farmers?',
    options: ['₹50,000', '₹1 lakh', '₹5 lakh', '₹2 lakh'],
    correctIndex: 3,
    explanation:
      'HT: 5.63 lakh farmers with about ₹2,700 crore of cooperative loans were picked for the first phase, with commercial-bank loans to follow. The BKU, saying the Congress had promised a complete waiver, called it “fake”; AAP’s Sukhpal Khaira cited certificates for ₹7–12. Officials said 3.2 lakh cases had been verified.',
    sourceUrl: 'https://www.hindustantimes.com/punjab/punjab-begins-farm-debt-waiver-farmers-aap-protest/story-tm9rhL84ScLBmyBoD19BFL.html',
    sourceLabel: 'Hindustan Times — Punjab begins farm debt waiver, farmers, AAP protest (7 Jan 2018)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Amarinder Singh', role: 'Chief Minister, Punjab', party: 'INC' }],
    outcome:
      '5.63 lakh farmers in phase one (about ₹2,700 crore of cooperative loans); ₹167.39 crore of relief certificates went to about 47,000 farmers at the launch.',
  },
  {
    id: 'hdb121',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Energy & Mining',
    subtopic: 'Free power slab (2019)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2019,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      'On 1 August 2019, about six months before the Delhi poll, the AAP government waived power bills for homes consuming up to how many units a month?',
    options: ['100 units', '200 units', '300 units', '400 units'],
    correctIndex: 1,
    explanation:
      'The Hindu: homes using 201–400 units got about a 50% subsidy. Kejriwal said about 35% of consumers use under 200 units in summer and 70% in winter, and that it was not possible earlier because the power companies’ finances were weak. The BJP and Congress called it an “election gimmick”.',
    sourceUrl: 'https://www.thehindu.com/news/national/other-states/free-electricity-for-delhiites-using-up-to-200-units/article28789468.ece',
    sourceLabel: 'The Hindu — Free electricity for Delhiites using up to 200 units (2 Aug 2019)',
    sources: [
      'https://www.thehindu.com/elections/delhi-assembly/delhi-assembly-elections-2020-aap-sweeps-delhi-with-62-seats/article30790189.ece',
      'https://en.wikipedia.org/wiki/2020_Delhi_Legislative_Assembly_election',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Arvind Kejriwal', role: 'Chief Minister, Delhi', party: 'AAP' }],
    outcome: 'Free up to 200 units, about half-price up to 400. The AAP won 62 of 70 seats on 8 Feb 2020.',
    poll: { label: 'Delhi Assembly 2020', month: '2020-02', gapDays: 191, result: 'AAP won 62 of 70 seats; BJP 8' },
  },
  {
    id: 'hdb122',
    domain: 'civics',
    region: 'India',
    state: 'JH',
    topic: 'Farm & Food',
    subtopic: 'Mukhya Mantri Krishi Ashirwad Yojana',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2019,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'Raghubar Das said in Feb 2019 that, with PM-KISAN plus Jharkhand’s ₹5,000-an-acre Krishi Ashirwad scheme, farmers would get from ₹11,000 up to what a year?',
    options: ['₹21,000', '₹41,000', '₹31,000', '₹51,000'],
    correctIndex: 2,
    explanation:
      'Speaking at the PM-KISAN launch in Ranchi, Das said the state scheme would start in April with cash in May, on top of the Centre’s ₹6,000 a year — “double benefits” of a “double engine” government. The first state instalment was actually paid on 10 August 2019: ₹482 crore to 13.6 lakh farmers (Dainik Bhaskar).',
    sourceUrl: 'https://www.hindustantimes.com/ranchi/jharkhand-s-5-2-lakh-farmers-get-first-instalment-of-centre-s-kisan-income-scheme/story-wMrzBDMWDr8FokdH7914dK.html',
    sourceLabel: 'Hindustan Times — Jharkhand’s 5.2 lakh farmers get first instalment of Centre’s Kisan income scheme (25 Feb 2019)',
    sources: [
      'https://www.bhaskar.com/jharkhand/ranchi/news/raghubar-das-says-farmers-are-the-axis-of-the-culture-of-jharkhand-state-01662467.html',
      'https://indianexpress.com/article/india/jharkhand-to-vote-in-five-phases-from-november-30-6098807/',
      'https://indianexpress.com/elections/jharkhand-assembly-election-results-hemant-soren-raghubar-das-bjp-jmm-congress-rjd-6181900/',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Raghubar Das', role: 'Chief Minister, Jharkhand', party: 'BJP' }],
    outcome:
      'About ₹900 crore reached 26 lakh farmers by 11 Oct 2019 (Dainik Bhaskar). The BJP lost the Nov–Dec 2019 poll: the JMM–Congress–RJD alliance won 47 of 81 seats, and Das lost Jamshedpur East to BJP rebel Saryu Roy.',
    poll: { label: 'Jharkhand Assembly 2019', month: '2019-11', gapDays: 112, result: 'JMM–Congress–RJD won 47 of 81 seats; BJP 25' },
  },

  // ───────────────────────── 2020–2026 ─────────────────────────
  {
    id: 'hdb123',
    domain: 'civics',
    region: 'India',
    state: 'HP',
    topic: 'Energy & Mining',
    subtopic: 'Grihini Suvidha Yojana (free LPG)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2020,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'By July 2020, about how many families had received free LPG connections under Himachal’s Grihini Suvidha Yojana, meant for homes left out of the Centre’s Ujjwala?',
    options: ['About 2.76 lakh', 'About 36,000', 'About 1.36 lakh', 'About 12 lakh'],
    correctIndex: 0,
    explanation:
      'CM Jai Ram Thakur said 2,76,243 families got free connections under the state scheme, besides 1.36 lakh under Ujjwala, and claimed Himachal had become the first state where every household had an LPG connection. The government pitched it as sparing women firewood collection and kitchen smoke.',
    sourceUrl: 'https://energy.economictimes.indiatimes.com/news/oil-and-gas/himachal-becomes-first-state-where-cent-pc-households-have-gas-connection-cm/76815307',
    sourceLabel: 'ET EnergyWorld — Himachal becomes first state where cent pc households have gas connection: CM (6 Jul 2020)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Jai Ram Thakur', role: 'Chief Minister, Himachal Pradesh', party: 'BJP' }],
    outcome:
      '2,76,243 families connected under the state scheme; the government declared full household LPG coverage in July 2020 (its own claim).',
  },
  {
    id: 'hdb124',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Energy & Mining',
    subtopic: '₹3-a-unit power tariff cut (2021)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2021,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'Punjab’s Channi government cut domestic power tariffs by ₹3 a unit in November 2021, months before the poll. What did the AAP government do with that cut in September 2024?',
    options: ['Doubled it to ₹6 a unit', 'Withdrew it, keeping 300 free units a month', 'Extended it to shops', 'Made it permanent by law'],
    correctIndex: 1,
    explanation:
      'The cut covered homes with loads up to 7 kW; in 2021 AAP’s Raghav Chadha had called it an “election stunt”. Finance Minister Harpal Singh Cheema said ending it would yield ₹1,500–1,800 crore a year and that the 300 free units a month would continue. Punjab Congress chief Amrinder Singh Raja Warring called the withdrawal a “blatant betrayal”.',
    sourceUrl: 'https://www.business-standard.com/india-news/punjab-cabinet-withdraws-previous-cong-govt-s-decision-of-subsidised-power-124090500693_1.html',
    sourceLabel: 'Business Standard (PTI) — Punjab Cabinet withdraws previous Cong govt’s decision of subsidised power (5 Sep 2024)',
    sources: [
      'https://www.indiatoday.in/india/story/power-rates-reduced-unit-punjab-chief-minister-charanjit-channi-1872043-2021-11-01',
      'https://www.thehindu.com/elections/punjab-assembly/aap-sweeps-punjab-with-92-seats-congress-akali-dal-decimated/article65211989.ece',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Charanjit Singh Channi', role: 'Chief Minister, Punjab', party: 'INC' }],
    outcome:
      'Channi said the cut covered about 69 lakh of 71 lakh domestic consumers. The Congress lost the 20 Feb 2022 poll (AAP 92 of 117, Congress 18); the AAP withdrew the cut in Sept 2024, saving ₹1,500–1,800 crore a year.',
    poll: { label: 'Punjab Assembly 2022', month: '2022-02', gapDays: 111, result: 'AAP won 92 of 117 seats; Congress 18' },
  },
  {
    id: 'hdb125',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Education & Exams',
    subtopic: 'Mukhyamantri Kanya Utthan Yojana',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2021,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      'From 2021-22, Bihar doubled its Mukhyamantri Kanya Utthan grant for girls who complete graduation. To how much?',
    options: ['₹25,000', '₹75,000', '₹1 lakh', '₹50,000'],
    correctIndex: 3,
    explanation:
      'The state cabinet raised the graduation grant from ₹25,000 to ₹50,000 and the Class 12 (intermediate) grant from ₹10,000 to ₹25,000, citing child marriage and girls’ access to higher education. India Today put the scheme’s potential reach at 1.6 crore girls.',
    sourceUrl: 'https://www.indiatoday.in/education-today/news/story/bihar-govt-to-give-rs-50-000-to-graduate-girls-rs-25-000-to-those-who-passed-class-12-1765555-2021-02-03',
    sourceLabel: 'India Today — Bihar govt to give Rs 50,000 to graduate girls, Rs 25,000 to those who passed class 12 (3 Feb 2021)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Nitish Kumar', role: 'Chief Minister, Bihar', party: 'JD(U)' }],
    outcome: 'Grants of ₹25,000 (Class 12) and ₹50,000 (graduation) from 2021-22; potential reach put at 1.6 crore girls.',
  },
  {
    id: 'hdb126',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Education & Exams',
    subtopic: 'Free smartphones and tablets (2021)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2021,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'UP began handing out free smartphones and tablets on 25 December 2021, 47 days before polling began. How much had an August 2021 supplementary budget earmarked for the devices?',
    options: ['₹300 crore', '₹1,000 crore', '₹3,000 crore', '₹7,301 crore'],
    correctIndex: 2,
    explanation:
      'Hindustan Times: the main 2021-22 budget had no provision; the ₹7,301.52-crore supplementary budget of 18 Aug 2021 set aside ₹3,000 crore to reach about one crore young people. Yogi Adityanath planned to hand 60,000 phones and 40,000 tablets to final-year students at the Lucknow launch on Vajpayee’s birth anniversary.',
    sourceUrl: 'https://www.hindustantimes.com/cities/lucknow-news/up-govt-to-start-distribution-of-free-tablets-smartphones-today-101640371641503.html',
    sourceLabel: 'Hindustan Times — UP govt to start distribution of free tablets, smartphones today (25 Dec 2021)',
    sources: [
      'https://scroll.in/latest/1019252/we-showed-bjps-seats-can-be-reduced-akhilesh-yadav-on-up-poll-results',
      'https://en.wikipedia.org/wiki/2022_Uttar_Pradesh_Legislative_Assembly_election',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Yogi Adityanath', role: 'Chief Minister, Uttar Pradesh', party: 'BJP' }],
    outcome:
      'Target of one crore devices; one lakh at the launch. The BJP kept power, winning 255 of 403 seats in polls held 10 Feb–7 Mar 2022.',
    poll: { label: 'UP Assembly 2022', month: '2022-02', gapDays: 47, result: 'BJP won 255 of 403 seats; SP 111' },
  },
  {
    id: 'hdb127',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Welfare & Subsidies',
    subtopic: 'Mukhya Mantri Parivar Samridhi Yojana',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2021,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'IAS officer Ashok Khemka wrote in 2021 that Haryana’s Parivar Samridhi Yojana, promising poor families ₹6,000 a year, had paid how much per family on average over two years?',
    options: ['₹3,086', '₹1,200', '₹6,000', '₹12,000'],
    correctIndex: 0,
    explanation:
      'Reviewing Nuh district, Khemka noted ₹270.84 crore had reached 8,77,538 families — about ₹3,086 each against ₹12,000 due for 2019-20 and 2020-21 — and that richer districts dominated (Karnal 10.4% of beneficiaries, Nuh 2.4%), suggesting incomes were not verified. The Indian Express report carried no government reply.',
    status:
      'An officer’s internal review of government data (June 2021), not an audit or court finding; no government reply and no case against any person found in sources checked (Sept 2026).',
    sourceUrl: 'https://indianexpress.com/article/cities/chandigarh/haryanas-mukhya-mantri-parivar-samridhi-yojana-maximum-poor-families-availing-benefits-are-from-richest-districts-7369790/',
    sourceLabel: 'The Indian Express — Haryana’s Mukhya Mantri Parivar Samridhi Yojana: ‘Maximum poor families availing benefits are from richest districts’ (22 Jun 2021)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Manohar Lal Khattar', role: 'Chief Minister, Haryana', party: 'BJP' }],
    outcome:
      '13.51 lakh families enrolled; ₹270.84 crore paid to 8.78 lakh by mid-2021 — roughly a quarter of their two-year entitlement, per government data cited by the IE.',
  },
  {
    id: 'hdb128',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Welfare & Subsidies',
    subtopic: 'Ladli scheme — CAG audit',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2022,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      'A CAG audit, reported in February 2025, found how much lying unclaimed under Delhi’s Ladli scheme for girls, launched by Sheila Dikshit’s government in 2008?',
    options: ['₹61.8 crore', '₹220 crore', '₹1,168 crore', '₹618.38 crore'],
    correctIndex: 3,
    explanation:
      'Per TNIE, 4.9 lakh of 8.84 lakh active beneficiaries (55%) had not received their dues as of Dec 2022; 16,546 duplicate registrations were found; Aadhaar checks began only in May 2023; and yearly enrolments fell 69% between 2009-10 and 2020-21. The WCD department said it had issued public notices — the audit counted two.',
    status:
      'CAG audit finding as reported by TNIE (Feb 2025), not a court finding; no case against any person reported in sources checked (Sept 2026).',
    sourceUrl: 'https://www.newindianexpress.com/cities/delhi/2025/Feb/27/ladli-scheme-audit-finds-rs-61838-crore-unclaimed-reveals-massive-irregularities',
    sourceLabel: 'The New Indian Express — ‘Duplicate registrations’: CAG exposes Rs 220 crore irregularities in Ladli scheme (27 Feb 2025)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Sheila Dikshit', role: 'Chief Minister, Delhi', party: 'INC' }],
    outcome:
      '₹618.38 crore unclaimed and 55% of active beneficiaries unpaid (Dec 2022); about ₹41 crore in excess payments flagged on duplicate or mismatched records.',
  },
  {
    id: 'hdb129',
    domain: 'civics',
    region: 'India',
    state: 'HP',
    topic: 'Energy & Mining',
    subtopic: 'Free power up to 60 units (2022)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2022,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'On Statehood Day in January 2022, with polls due that year, Jai Ram Thakur made power free for Himachal homes using up to how many units a month?',
    options: ['125 units', '60 units', '200 units', '300 units'],
    correctIndex: 1,
    explanation:
      'The Indian Express: homes using up to 60 units a month pay nothing and those up to 125 units pay ₹1 a unit, from April 2022 — about 11 lakh consumers, at ₹60 crore extra; farm power fell from 50 to 30 paise a unit. The same day he raised the income limit for welfare pensions from ₹35,000 to ₹50,000.',
    sourceUrl: 'https://indianexpress.com/article/cities/shimla/himachal-pradesh-statehood-day-jai-ram-thakur-announcement-free-power-7741486/',
    sourceLabel: 'The Indian Express — Himachal Statehood Day: CM Jai Ram Thakur announces free power to households consuming 60 units per month (25 Jan 2022)',
    sources: [
      'https://www.livemint.com/elections/assembly-elections/election-results-2022-bjp-sets-gujarat-record-congress-wins-himachal-pradesh-11670495701908.html',
      'https://en.wikipedia.org/wiki/2022_Himachal_Pradesh_Legislative_Assembly_election',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Jai Ram Thakur', role: 'Chief Minister, Himachal Pradesh', party: 'BJP' }],
    outcome:
      'About 11 lakh consumers covered at ₹60 crore a year. The BJP lost the 12 Nov 2022 poll: the Congress won 40 of 68 seats.',
    poll: { label: 'Himachal Assembly 2022', month: '2022-11', gapDays: 291, result: 'Congress won 40 of 68 seats; BJP 25' },
  },
  {
    id: 'hdb130',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Welfare & Subsidies',
    subtopic: 'Indira Gandhi Smartphone Yojana',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2023,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'Rajasthan’s Indira Gandhi smartphone scheme for women, launched on 10 August 2023, had given out about how many phones when the model code of conduct halted it?',
    options: ['24.56 lakh', '7 lakh', '40 lakh', '1.33 crore'],
    correctIndex: 0,
    explanation:
      'Minister Rajyavardhan Rathore told the Assembly in Jan 2024 that 24,56,001 women got phones with data, at ₹1,670.08 crore, by 9 Oct 2023. Phase one aimed at 40 lakh; the 2022-23 plan was a phone for each of 1.33 crore Chiranjeevi families. The new BJP government put the scheme on hold to “examine” it.',
    sourceUrl: 'https://indianexpress.com/article/cities/jaipur/rajasthan-puts-gehlots-free-smartphone-scheme-on-hold-9124729/',
    sourceLabel: 'The Indian Express — Rajasthan puts Gehlot’s free smartphone scheme on hold (24 Jan 2024)',
    sources: [
      'https://www.thehindu.com/news/national/poll-bound-rajasthan-distributes-smartphones-for-women/article67241167.ece',
      'https://www.livemint.com/elections/assembly-elections/bjp-emerges-victorious-in-rajasthan-assembly-election-securing-115-seats-a-recap-10-points-11701651737789.html',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Ashok Gehlot', role: 'Chief Minister, Rajasthan', party: 'INC' }],
    outcome:
      '24.56 lakh phones for ₹1,670.08 crore. The Congress lost the 25 Nov 2023 poll (BJP 115 of 199, Congress 69), and the scheme was put on hold in Jan 2024.',
    poll: { label: 'Rajasthan Assembly 2023', month: '2023-11', gapDays: 107, result: 'BJP won 115 of 199 seats; Congress 69' },
  },
  {
    id: 'hdb131',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Energy & Mining',
    subtopic: '₹450 LPG cylinder (2024)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2023,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'Rajasthan’s Congress government capped LPG at ₹500 a cylinder for poor families in 2023. From 1 January 2024, what price did the new BJP government set for Ujjwala households?',
    options: ['₹300', '₹400', '₹450', '₹550'],
    correctIndex: 2,
    explanation:
      'Announcing it in Tonk, CM Bhajan Lal Sharma called it a BJP manifesto promise (₹50 cheaper). The Hindu said about 76 lakh BPL families would get the subsidy in their accounts for up to 12 cylinders a year; Ashok Gehlot’s scheme had paid a ₹650 subsidy per cylinder, with ₹750 crore approved for 2023-24.',
    sourceUrl: 'https://www.thehindu.com/news/national/other-states/rajasthan-announces-ujjwala-yojanas-lpg-cylinder-supply-at-450/article67680668.ece',
    sourceLabel: 'The Hindu — Rajasthan announces Ujjwala Yojana’s LPG cylinder supply at ₹450 (28 Dec 2023)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Bhajan Lal Sharma', role: 'Chief Minister, Rajasthan', party: 'BJP' }],
    outcome:
      'Subsidy for about 76 lakh BPL families, up to 12 cylinders a year, per the state; the Ujjwala cylinder had cost ₹1,150 at its 2022 peak.',
  },
  {
    id: 'hdb132',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Welfare & Subsidies',
    subtopic: 'Mukhyamantri Kanya Sumangala Yojana',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2023,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'UP’s Kanya Sumangala Yojana pays a girl’s family in six stages, from birth to college. From 2024-25 the total was raised from ₹15,000 to what?',
    options: ['₹20,000', '₹30,000', '₹51,000', '₹25,000'],
    correctIndex: 3,
    explanation:
      'Yogi Adityanath announced the rise on Raksha Bandhan 2023: ₹5,000 at birth, ₹2,000 at age one, ₹3,000 each on entering Classes 1 and 6, ₹5,000 at Class 9 and ₹7,000 for a degree, diploma or certificate course. About 16.24 lakh girls were enrolled at the time.',
    sourceUrl: 'https://indianexpress.com/article/cities/lucknow/mukhyamantri-kanya-sumangla-yojana-rakhi-gift-underprivileged-girls-to-get-rs-10000-more-8917022/',
    sourceLabel: 'The Indian Express — Mukhyamantri Kanya Sumangla Yojana: Underprivileged girls to get Rs 10,000 more (31 Aug 2023)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Yogi Adityanath', role: 'Chief Minister, Uttar Pradesh', party: 'BJP' }],
    outcome: 'About 16.24 lakh girls covered in 2023; ₹5.82 crore went to 29,523 beneficiaries at the announcement event.',
  },
  {
    id: 'hdb133',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Welfare & Subsidies',
    subtopic: 'Old-age pension bids (2024 poll)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'Ahead of Haryana’s October 2024 poll, with the old-age pension at ₹3,000 a month, what monthly pension did the INLD promise if elected?',
    options: ['₹5,100', '₹7,500', '₹6,000', '₹3,500'],
    correctIndex: 1,
    explanation:
      'TOI listed the bids: the Congress’s Bhupinder Hooda ₹6,000, the INLD ₹7,500 and the JJP ₹5,100. About 17.85 lakh people drew the pension, at a 2023-24 cost of ₹5,538 crore. Political scientists quoted called it “competitive populism” aimed at rural opinion-makers.',
    sourceUrl: 'https://timesofindia.indiatimes.com/city/chandigarh/handful-still-handy-why-haryana-parties-love-wooing-the-old/articleshow/112710215.cms',
    sourceLabel: 'The Times of India — Handful, still handy: Why Haryana parties love wooing the old (22 Aug 2024)',
    sources: [
      'https://socialjusticehry.gov.in/old-age-samman-allowance-scheme/',
      'https://www.newindianexpress.com/india/2024/Sep/23/congress-on-course-to-sweep-haryana-polls-set-to-repeat-2005-performance-surjewala',
      'https://scroll.in/latest/1074176/haryana-election-result-counting-of-votes-to-begin-at-8-am',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Manohar Lal Khattar', role: 'Chief Minister, Haryana', party: 'BJP' }],
    outcome:
      'The BJP, which had raised the pension to ₹3,000 from 1 Jan 2024, won 48 of 90 seats; it added ₹200 from 1 Nov 2025, taking the pension to ₹3,200.',
    poll: { label: 'Haryana Assembly 2024', month: '2024-10', gapDays: 278, result: 'BJP won 48 of 90 seats; Congress 37' },
  },
  {
    id: 'hdb134',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Welfare & Subsidies',
    subtopic: 'Mukhyamantri Mahila Samman Yojana',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      'In December 2024, what did public notices from Delhi’s own Women and Child Development department say about AAP’s drive to register women for ₹2,100 a month?',
    options: [
      'No such scheme was notified, and collecting forms was “fraudulent”',
      'Registration would open online the next week',
      'The ECI had barred the scheme until after the poll',
      'The L-G had approved ₹2,100 in place of ₹1,000',
    ],
    correctIndex: 0,
    explanation:
      'The cabinet had cleared ₹1,000 a month for non-taxpaying women on 12 Dec (first announced in the March 2024 budget), and Kejriwal promised ₹2,100 if re-elected. The notices called form collection by any party “without authority”. CM Atishi called them false, blamed BJP pressure and promised action against the officers. On a Congress complaint, the L-G then ordered an inquiry into the form drive.',
    status:
      'L-G ordered an inquiry through the divisional commissioner into form collection by non-government persons (28 Dec 2024); no outcome, FIR or charge against any named person reported in sources checked (Sept 2026). AAP called the notices false.',
    people: ['Atishi', 'Arvind Kejriwal'],
    sourceUrl: 'https://indianexpress.com/article/cities/delhi/delhi-departments-notices-aap-schemes-kejriwal-9743477/',
    sourceLabel: 'The Indian Express — Schemes launched by Kejriwal, Atishi disowned by Delhi govt’s own departments (25 Dec 2024)',
    sources: [
      'https://www.business-standard.com/elections/delhi-elections/kejriwal-promises-rs-2-100-monthly-aid-to-women-ahead-of-delhi-elections-124121200580_1.html',
      'https://www.thehindu.com/news/cities/Delhi/aap-scheme-faces-probe-over-illegal-data-collection-charge/article69036595.ece',
      'https://frontline.thehindu.com/news/delhi-election-results-2025-bjp-wins-46-seats-ends-aap-rule/article69195445.ece',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [
      { name: 'Atishi', role: 'Chief Minister, Delhi', party: 'AAP' },
      { name: 'Arvind Kejriwal', role: 'AAP national convenor (former CM)', party: 'AAP' },
    ],
    outcome:
      'The official portal was not working when the notices appeared. The BJP won the 5 Feb 2025 poll (48 of 70, AAP 22), and its own ₹2,500 scheme launched only in August 2026.',
    poll: { label: 'Delhi Assembly 2025', month: '2025-02', gapDays: 55, result: 'BJP won 48 of 70 seats; AAP 22' },
  },
  {
    id: 'hdb135',
    domain: 'civics',
    region: 'India',
    state: 'JH',
    topic: 'Welfare & Subsidies',
    subtopic: 'Maiya Samman hike to ₹2,500',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'JMM',
    question:
      'Jharkhand’s cabinet approved a steep rise in the monthly Maiya Samman payment to women how long before the ECI announced the 2024 poll schedule on 15 October?',
    options: ['One week', 'One month', 'One day', 'Three months'],
    correctIndex: 2,
    explanation:
      'Business Standard: the scheme began on 3 Aug 2024 at ₹1,000 for women aged 18–50; after the BJP promised ₹2,100 under ‘Gogo Didi’, the cabinet approved ₹2,500 from December, estimated to add ₹9,000 crore a year. The Indian Express described allegations and counter-allegations between the JMM and BJP of misusing election law to woo women.',
    sourceUrl: 'https://www.business-standard.com/elections/jharkhand-elections/jharkhand-polls-how-maiya-samman-yojana-strengthened-soren-s-grip-in-state-124112300422_1.html',
    sourceLabel: 'Business Standard — Jharkhand polls: How Maiya Samman Yojana strengthened Soren’s grip in state (23 Nov 2024)',
    sources: [
      'https://indianexpress.com/article/india/jharkhand-assembly-election-jmm-bjp-sops-9613054/',
      'https://frontline.thehindu.com/politics/jharkhand-election-results-2024-jmm-alliance-wins-majority-bjp-tribal-strategy-fails/article68902569.ece',
      'https://www.newindianexpress.com/india/2025/Mar/20/maiyan-samman-yojana-jharkhand-government-to-release-list-of-deleted-beneficiaries',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Hemant Soren', role: 'Chief Minister, Jharkhand', party: 'JMM' }],
    outcome:
      'The JMM-led alliance won 56 of 81 seats in the 13 and 20 Nov polls, the first time Jharkhand re-elected a sitting government; the 2025-26 budget then set aside ₹13,363 crore for the scheme.',
    poll: { label: 'Jharkhand Assembly 2024', month: '2024-11', gapDays: 30, result: 'JMM-led alliance won 56 of 81 seats; JMM alone 34' },
  },
  {
    id: 'hdb136',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Welfare & Subsidies',
    subtopic: 'Social security pension hike (2025)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      'In June 2025, months before the Bihar poll, Nitish Kumar raised the monthly social security pension for the elderly, widows and disabled people from ₹400 to what?',
    options: ['₹700', '₹1,500', '₹2,000', '₹1,100'],
    correctIndex: 3,
    explanation:
      'The Indian Express: about 1.09 crore pensioners, from July 2025. Tejashwi Yadav called it copying the RJD’s ₹1,500 promise; Prashant Kishor said Jan Suraaj’s ₹2,000 pledge had forced it. On 11 July Nitish transferred ₹1,227.27 crore to 1.11 crore pensioners.',
    sourceUrl: 'https://indianexpress.com/article/india/bihar-govt-increases-old-age-widow-pension-by-rs-700-per-month-10080035/',
    sourceLabel: 'The Indian Express — Cometh the polls, cometh the doles: Nitish announces three-fold hike in social security pension (21 Jun 2025)',
    sources: [
      'https://www.thehindu.com/elections/bihar-assembly/in-poll-bound-bihar-cm-nitish-kumar-transfers-122727-crore-to-over-111-crore-beneficiaries-under-pension-schemes/article69800557.ece',
      'https://www.hindustantimes.com/india-news/nda-mahagathbandhan-bjp-jdu-rjd-congress-ljp-jan-suraaj-prashant-kishore-tejashwi-seat-tally-101763169862862.html',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Nitish Kumar', role: 'Chief Minister, Bihar', party: 'JD(U)' }],
    outcome:
      'Pensions nearly tripled for about 1.11 crore people from July 2025. The NDA won 202 of 243 seats in November 2025.',
    poll: { label: 'Bihar Assembly 2025', month: '2025-11', gapDays: 138, result: 'NDA won 202 of 243 seats; BJP 89, JD(U) 85' },
  },
  {
    id: 'hdb137',
    domain: 'civics',
    region: 'India',
    state: 'JH',
    topic: 'Welfare & Subsidies',
    subtopic: 'Maiyan Samman — names deleted',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'JMM',
    question:
      'By March 2025, about how many women’s names had been deleted from Jharkhand’s Maiyan Samman beneficiary list after verification, prompting BJP demands for reasons?',
    options: ['About 18 lakh', 'About 1.8 lakh', 'About 5 lakh', 'About 50 lakh'],
    correctIndex: 0,
    explanation:
      'TNIE: government sources blamed mismatched bank details, bank accounts not seeded with Aadhaar and pending KYC, plus irregularities found in physical checks after reports of fraud by form-filling operators. Minister Chamra Linda told the Assembly the government would consider publishing the deleted names with reasons, as BJP MLA Neera Yadav demanded.',
    sourceUrl: 'https://www.newindianexpress.com/india/2025/Mar/20/maiyan-samman-yojana-jharkhand-government-to-release-list-of-deleted-beneficiaries',
    sourceLabel: 'The New Indian Express — Maiyan Samman Yojana: Jharkhand government to release list of deleted beneficiaries (20 Mar 2025)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Hemant Soren', role: 'Chief Minister, Jharkhand', party: 'JMM' }],
    outcome: 'More than 18 lakh names removed by March 2025, even as the 2025-26 budget allocated ₹13,363 crore to the scheme.',
  },
  {
    id: 'hdb138',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Welfare & Subsidies',
    subtopic: 'Lado Lakshmi — first instalment',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'The BJP promised monthly cash to all Haryana women before the 2024 poll. When the first Lado Lakshmi instalment was paid on 1 November 2025, about how many women received it?',
    options: ['20 lakh', '5.22 lakh', '52 lakh', '76.7 lakh'],
    correctIndex: 1,
    explanation:
      'ThePrint: notified on 28 Aug 2025, the scheme is limited to women over 23 in families earning up to ₹1 lakh a year, with 15 years’ residence; 6.98 lakh had registered by 31 Oct. AIDWA’s Jagmati Sangwan said the payout reached under 4% of adult women. CM Nayab Saini counts it among the poll promises his government has fulfilled.',
    sourceUrl: 'https://theprint.in/politics/in-haryanas-cash-transfers-for-women-eligibility-riders-a-repeat-of-the-promise-delivery-gap/2776584/',
    sourceLabel: 'ThePrint — In Haryana’s cash transfers for women & eligibility riders, a repeat of the promise-delivery gap (4 Nov 2025)',
    sources: ['https://www.tribuneindia.com/news/haryana/haryana-government-hikes-monthly-old-age-pension-from-rs-3000-to-rs-3200/'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Nayab Singh Saini', role: 'Chief Minister, Haryana', party: 'BJP' }],
    outcome: 'About 5.22 lakh women paid ₹2,100 in the first instalment; 6.98 lakh had registered by 31 Oct 2025.',
  },
  {
    id: 'hdb139',
    domain: 'civics',
    region: 'India',
    state: 'JK',
    topic: 'Welfare & Subsidies',
    subtopic: 'Social pensions (Budget 2025-26)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'Other',
    question:
      'Omar Abdullah’s first budget (March 2025) raised social pensions for over 10 lakh people in J&K. How much a month did it set for recipients above 80?',
    options: ['₹1,000', '₹1,250', '₹2,000', '₹1,500'],
    correctIndex: 2,
    explanation:
      'The cabinet approved the budget promises in late March 2025 (All India Radio): ₹1,250 for under-60s, ₹1,500 for ages 60–80 and ₹2,000 above 80, for the elderly, widows, divorcees and disabled; 200 free units of power and 10 kg free ration per person for Antyodaya families; and marriage aid for AAY girls raised from ₹50,000 to ₹75,000.',
    sourceUrl: 'https://newsonair.gov.in/jk-cabinet-approves-key-budget-announcements-free-power-ration-for-aay-families-pension-hike/',
    sourceLabel: 'All India Radio — J&K cabinet approves key budget announcements: free power, ration for AAY families, pension hike (28 Mar 2025)',
    sources: ['https://indianexpress.com/article/india/omar-abdullah-unveils-jk-budget-200-units-free-power-other-benefits-9874871/'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Omar Abdullah', role: 'Chief Minister, Jammu & Kashmir', party: 'NC' }],
    outcome:
      'Approved for rollout from April 2025 alongside free power and rations for Antyodaya families — all National Conference manifesto promises, per The Indian Express.',
  },
  {
    id: 'hdb140',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Welfare & Subsidies',
    subtopic: 'Mahila Rojgar Yojana — Supreme Court plea',
    kind: 'institution',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      'In February 2026, what became of Jan Suraaj’s Supreme Court plea against cash payments to women under Bihar’s Mahila Rojgar Yojana during the 2025 poll?',
    options: [
      'The Court froze further payments',
      'The Court ordered the ECI to recount votes',
      'It was referred to a Constitution Bench',
      'It was withdrawn, with liberty to approach the Patna High Court',
    ],
    correctIndex: 3,
    explanation:
      'The bench of CJI Surya Kant and Justice Joymalya Bagchi questioned treating a government policy as a corrupt practice — “It’s for the people to vote out their policy” — but said freebies were being examined seriously. Jan Suraaj argued ₹15,600 crore was paid pre-poll and 25–35 lakh women enrolled after the model code began; in March 2026 it said it had filed in the Patna HC.',
    status:
      'Supreme Court plea withdrawn with liberty on 6 Feb 2026 (no ruling on merits); Jan Suraaj said on 23 Mar 2026 it had petitioned the Patna High Court; no HC ruling reported in sources checked (Sept 2026).',
    sourceUrl: 'https://www.verdictum.in/court-updates/supreme-court/prashant-kishore-refuses-jan-suraaj-party-plea-scheme-providing-10k-women-during-bihar-election-1606691',
    sourceLabel: 'Verdictum — Supreme Court refuses to entertain Jan Suraaj plea on ₹10,000 scheme for women during Bihar election (6 Feb 2026)',
    sources: [
      'https://www.livehindustan.com/bihar/jansuraj-files-petition-in-high-court-to-against-bihar-assembly-election-results-had-setback-in-supreme-court-201774285355680.html',
      'https://www.hindustantimes.com/cities/patna-news/25mn-more-bihar-women-get-10k-each-as-grant-for-establishing-startups-101771252968341.html',
      'https://timesofindia.indiatimes.com/city/patna/tejashwi-slams-nda-govt-over-unfulfilled-mmry-promise/articleshow/130563169.cms',
      'https://navbharattimes.indiatimes.com/government-schemes/bihar/raksha-bandhan-gift-for-women-in-bihar-600-crore-transferred-to-accounts-of-5-lakh-jeevika-didi/articleshow/133561915.cms',
      'https://www.pmindia.gov.in/en/news_updates/pm-launches-bihars-mukhyamantri-mahila-rojgar-yojana/',
      'https://theprint.in/india/rjd-leader-writes-to-ec-says-bihar-govt-violated-mcc-by-transferring-money-to-women-ahead-of-poll/2774961/',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [
      { name: 'Nitish Kumar', role: 'Chief Minister, Bihar', party: 'JD(U)' },
      { name: 'Narendra Modi', role: 'Prime Minister (launched the scheme)', party: 'BJP' },
    ],
    outcome:
      'By Feb 2026, ₹10,000 each had gone to 1.81 crore women (₹18,100 crore), 1.56 crore of them from 26 Sep to 28 Nov 2025. The RJD said in April 2026 later instalments were unpaid; in Aug 2026 one lakh women got a ₹20,000 second instalment.',
    poll: { label: 'Bihar Assembly 2025', month: '2025-11', gapDays: 41, result: 'NDA won 202 of 243 seats; Jan Suraaj won none' },
  },
  {
    id: 'hdb141',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Welfare & Subsidies',
    subtopic: 'Mukh Mantri Mawan Dhiyan Satikar Yojana',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      'Punjab’s 2026-27 budget, presented on Women’s Day, funded AAP’s 2022 promise of monthly cash for women. How much did it earmark for the scheme?',
    options: ['₹9,300 crore', '₹930 crore', '₹3,500 crore', '₹20,500 crore'],
    correctIndex: 0,
    explanation:
      'Finance Minister Harpal Singh Cheema announced the Mukh Mantri Mawan Dhiyan Satikar Yojana — ₹1,000 a month for adult women, more for some groups — and said about 97% of women qualify; only government employees, MPs/MLAs and income-tax payers are left out. It came nearly four years after the AAP’s 2022 win.',
    status:
      'A PIL challenging the scheme’s mandatory voter-ID clause was listed in the Punjab and Haryana High Court for 5 Oct 2026; no ruling as of Sept 2026.',
    sourceUrl: 'https://indianexpress.com/article/cities/chandigarh/punjab-budget-2026-women-monthly-assistance-mawan-dhiyan-satikar-yojana-10571040/',
    sourceLabel: 'The Indian Express — Punjab Budget 2026: AAP fulfills pre-poll guarantee with monthly cash for 97% women (8 Mar 2026)',
    sources: [
      'https://www.hindustantimes.com/cities/chandigarh-news/punjab-76l-women-registered-under-mawan-dheeyan-satkar-yojana-says-mann-101787767970675.html',
      'https://www.tribuneindia.com/news/punjab/mawan-dheeyan-scheme-challenged-in-high-court-as-vote-buying-move-over-mandatory-voter-id-clause/',
    ],
    tags: ['distribution'],
    enactedBy: [
      { name: 'Bhagwant Mann', role: 'Chief Minister, Punjab', party: 'AAP' },
      { name: 'Harpal Singh Cheema', role: 'Finance Minister, Punjab', party: 'AAP' },
    ],
    outcome:
      '₹9,300 crore budgeted inside an ₹18,304 crore welfare package; Mann said 76.11 lakh women had registered by Aug 2026. A PIL listed for 5 Oct 2026 alleges its voter-ID requirement is meant to secure votes. Punjab votes by early 2027.',
  },
  {
    id: 'hdb142',
    domain: 'civics',
    region: 'India',
    state: 'UT',
    topic: 'Welfare & Subsidies',
    subtopic: 'Nanda Gaura Yojana',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'Uttarakhand’s Nanda Gaura Yojana pays ₹11,000 when a girl is born in an eligible family. How much does it pay after she passes Class 12?',
    options: ['₹21,000', '₹51,000', '₹31,000', '₹1 lakh'],
    correctIndex: 1,
    explanation:
      'In March 2026 CM Pushkar Singh Dhami transferred ₹145.93 crore by DBT to 33,251 girls for 2025-26 — 5,913 newborns and 27,338 who had passed Class 12. The state says ₹1,168.49 crore has gone to 3,77,784 girls since the scheme began.',
    sourceUrl: 'https://garhwalpost.in/cm-transfers-rs-145-93-crores-to-beneficiaries-under-nanda-gaura-yojana-through-dbt/',
    sourceLabel: 'Garhwal Post — CM transfers Rs 145.93 crores to beneficiaries under Nanda Gaura Yojana through DBT (2 Mar 2026)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Pushkar Singh Dhami', role: 'Chief Minister, Uttarakhand', party: 'BJP' }],
    outcome: '₹1,168.49 crore to 3,77,784 girls since inception, per the state; ₹145.93 crore to 33,251 girls for 2025-26.',
  },
  {
    id: 'hdb143',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Welfare & Subsidies',
    subtopic: 'Delhi Lakshmi Yojana — endorsement rule',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'Delhi’s BJP government launched its ₹2,500-a-month scheme for poor women in August 2026. Applicants must upload what — a condition now challenged in the High Court?',
    options: ['A police verification certificate', 'Proof of 20 years’ residence', 'An endorsement letter from their MP or MLA', 'A bank guarantee'],
    correctIndex: 2,
    explanation:
      'In PILs, petitioners say the rule adds an unguided political step between the state and poor women. The High Court asked the government to explain it, remarking the problem was that it is the only route. A 15 Sep affidavit said similar schemes elsewhere need lawmakers’ recommendations and the rule is not arbitrary; about 7.33 lakh endorsed applications had come in.',
    status:
      'PILs pending in the Delhi High Court (listed 17 Sep 2026 after the government’s 15 Sep affidavit); no ruling reported in sources checked (Sept 2026).',
    sourceUrl: 'https://www.hindustantimes.com/cities/delhi-news/not-the-only-state-govt-defends-mla-nod-in-aid-scheme-101789580916570.html',
    sourceLabel: 'Hindustan Times — ‘Not the only state’: Delhi defends MLA nod in Lakshmi Yojana scheme (17 Sep 2026)',
    sources: [
      'https://www.livelaw.in/high-court/delhi-high-court/delhi-lakshmi-yojana-benefits-mpmla-endorsement-letter-challenged-548283',
      'https://thenewsmill.com/2026/09/delhi-government-urges-high-court-to-dismiss-challenge-to-mp-mla-endorsements-in-lakshmi-yojana/',
      'https://www.newindianexpress.com/cities/delhi/2026/Aug/31/delhi-lakshmi-yojana-rd-maturity-set-for-july-31-2029',
    ],
    tags: ['distribution'],
    enactedBy: [{ name: 'Rekha Gupta', role: 'Chief Minister, Delhi', party: 'BJP' }],
    outcome:
      'Aimed at up to 17 lakh women: ₹1,500 a month goes to a recurring deposit locked till 31 July 2029 and ₹1,000 to a digital-rupee wallet. Launched on 26 Aug 2026 with payments scheduled from 1 Sep; the PILs were pending in September.',
  },
  {
    id: 'hdb144',
    domain: 'civics',
    region: 'India',
    state: 'HP',
    topic: 'Welfare & Subsidies',
    subtopic: 'Indira Gandhi Pyari Behna Sukh Samman Nidhi',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'Himachal notified its ₹1,500-a-month Pyari Behna scheme for women weeks before the 2024 Lok Sabha poll. When the cabinet extended it in May 2026, which women did it cover?',
    options: [
      'All women aged 18–60, with no income limit',
      'Only widows and single women over 40',
      'Only women who head BPL households',
      'Women aged 18–59 in families earning under ₹2 lakh',
    ],
    correctIndex: 3,
    explanation:
      'CM Sukhvinder Sukhu announced it on 4 Mar 2024 (₹800 crore for 5 lakh women) and it was notified on 14 Mar, but was then extended area by area (Kinnaur in April 2026). ET: about 2 lakh women in phase one, no outlay announced. The BJP called the May 2026 decision a breach of the panchayat-poll code; minister Harshwardhan Chauhan called it routine.',
    status:
      'BJP complaint to the State Election Commission over the May 2026 cabinet decisions; the SEC said it would place it before the Commission; no finding reported in sources checked (Sept 2026).',
    sourceUrl: 'https://m.economictimes.com/news/india/himachal-pradesh-clears-rs-1500-aid-for-women-in-4th-year-of-power/articleshow/131284831.cms',
    sourceLabel: 'The Economic Times — Himachal Pradesh clears Rs 1,500 aid for women in 4th year of power (24 May 2026)',
    sources: [
      'https://www.hindustantimes.com/cities/chandigarh-news/himachal-issues-notification-for-granting-1-500-monthly-financial-aid-to-women-101710436971845.html',
      'https://www.business-standard.com/india-news/parties-gear-up-for-iwd-delhi-hp-govts-announce-honorariums-for-women-124030401106_1.html',
      'https://www.thehindu.com/news/national/himachal-pradesh/himachal-cm-sukhu-announces-1500-monthly-aid-for-eligible-women-in-kinnaur/article70864775.ece',
      'https://www.aninews.in/news/national/general-news/himachal-bjp-alleges-mcc-violation-over-state-cabinet-meeting-amid-pri-polls-congress-rejects-charges20260523030700',
      'https://indianexpress.com/article/political-pulse/lotus-bloom-in-himachal-as-bjp-wins-all-4-ls-seats-9372291/',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Sukhvinder Singh Sukhu', role: 'Chief Minister, Himachal Pradesh', party: 'INC' }],
    outcome:
      'The BJP swept Himachal’s four Lok Sabha seats on 1 June 2024; statewide payments for families under ₹2 lakh were cleared only in May 2026, in the government’s fourth year.',
    poll: { label: 'Lok Sabha 2024 (Himachal Pradesh)', month: '2024-06', gapDays: 89, result: 'BJP won all 4 seats' },
  },
  {
    id: 'hdb145',
    domain: 'civics',
    region: 'India',
    state: 'UT',
    topic: 'Welfare & Subsidies',
    subtopic: 'Free Roadways travel for women 60+',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'On Raksha Bandhan 2026, Pushkar Singh Dhami made Uttarakhand Roadways buses free for women from what age, down from the earlier senior-citizen limit of 65?',
    options: ['60 years', '50 years', '55 years', '62 years'],
    correctIndex: 0,
    explanation:
      'The Times of India: the same announcements set aside 10 of Dehradun’s 100 PM e-Bus Sewa buses as Pink e-Buses for women and raised the loan limit under the women’s self-employment scheme from ₹2 lakh to ₹2.5 lakh. Dhami cited 3.09 lakh women who had become ‘Lakhpati Didis’.',
    sourceUrl: 'https://timesofindia.indiatimes.com/india/uttarakhand-cm-dhami-announces-free-bus-travel-pink-e-buses-for-women-on-raksha-bandhan/articleshow/133593963.cms',
    sourceLabel: 'The Times of India — Uttarakhand CM Dhami announces free bus travel, Pink e-Buses for women on Raksha Bandhan (28 Aug 2026)',
    tags: ['distribution'],
    enactedBy: [{ name: 'Pushkar Singh Dhami', role: 'Chief Minister, Uttarakhand', party: 'BJP' }],
    outcome: 'Free travel extended to women aged 60–64 (announced 28 Aug 2026); Uttarakhand’s next Assembly poll is due by early 2027.',
  },
]);
