// HISAAB DO — lane: Elections & money (prefix `hel`). See docs/hisaab/CHARTER.md §2–§5.
// Research notes, sources, drops and stale-risk items: docs/hisaab/research/elections-notes.md
// Every item was checked against the page in `sourceUrl` in September 2026.

const SC_EB_JUDGMENT =
  'https://api.sci.gov.in/supremecourt/2017/27935/27935_2017_1_1501_50573_Judgement_15-Feb-2024.pdf';
const SCO_EB_TIMELINE = 'https://www.scobserver.in/journal/a-complete-timeline-of-the-electoral-bond-scheme/';
const BS_EB_PARTIES =
  'https://www.business-standard.com/elections/lok-sabha-election/electoral-bonds-bjp-received-more-funds-than-the-next-6-parties-combined-124031500434_1.html';
const PRINT_ADR_TOP_DONORS = 'https://theprint.in/india/electoral-bond-future-gaming-biggest-donor-to-tmc-dmk-ysrcp/2019061/';
const ADR_LS2024 = 'https://adrindia.org/content/record-46-of-newly-elected-lok-sabha-mps-facing-criminal-cases';
const ADR_LS2024_ASSETS = 'https://adrindia.org/content/criminals-and-crorepatis-meet-the-new-mps-of-lok-sabha-2024';

export const HISAAB_ELECTIONS = Object.freeze([
  // ── Electoral bonds: the law ────────────────────────────────────────────────
  {
    id: 'hel001',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds',
    kind: 'funding',
    difficulty: 'simple',
    year: 2017,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Electoral bonds were made possible by amendments to the RBI Act, Income Tax Act, Representation of the People Act and Companies Act, all carried in which one law?',
    options: [
      'The Finance Act, 2017',
      'The Election Laws (Amendment) Act, 2021',
      'The Companies (Amendment) Act, 2015',
      'The Foreign Contribution (Regulation) Act, 2010',
    ],
    correctIndex: 0,
    explanation:
      'The Finance Act, 2017 amended all four laws to create the bonds and to let parties skip naming bond donors. The Supreme Court struck down the scheme and these amendments on 15 Feb 2024 (ADR v. Union of India). The Union had defended it as a way to move political donations into banking channels.',
    sourceUrl: SC_EB_JUDGMENT,
    sourceLabel: 'Supreme Court of India — ADR v. Union of India, judgment (15 Feb 2024)',
    sources: [SCO_EB_TIMELINE],
  },
  {
    id: 'hel002',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds',
    kind: 'funding',
    difficulty: 'extreme',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'On what date did the Union Finance Ministry notify the Electoral Bond Scheme, 2018?',
    options: ['1 February 2017', '2 January 2018', '12 April 2019', '7 November 2022'],
    correctIndex: 1,
    explanation:
      'It was notified on 2 Jan 2018 under Section 31(3) of the RBI Act. 1 Feb 2017 was the Budget speech announcing it; 12 Apr 2019 was the SC interim order asking parties for sealed-cover donor details; 7 Nov 2022 was an amendment adding a sale window. The SC struck the scheme down in Feb 2024.',
    sourceUrl: SC_EB_JUDGMENT,
    sourceLabel: 'Supreme Court of India — ADR v. Union of India, judgment (15 Feb 2024)',
    sources: [SCO_EB_TIMELINE],
  },
  {
    id: 'hel003',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds verdict',
    kind: 'institution',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'When the Supreme Court struck down electoral bonds in February 2024, which right did it hold the scheme violated?',
    options: [
      'Freedom of religion, Article 25',
      'Right to property, Article 300A',
      "Voters' right to information, Article 19(1)(a)",
      'Protection from double jeopardy, Article 20(2)',
    ],
    correctIndex: 2,
    explanation:
      "A unanimous five-judge Constitution Bench held on 15 Feb 2024 that anonymous bonds violated voters' right to information under Article 19(1)(a), and that lifting the cap on company donations was manifestly arbitrary under Article 14. The Union had argued donor confidentiality protected donors from retribution.",
    sourceUrl: SC_EB_JUDGMENT,
    sourceLabel: 'Supreme Court of India — ADR v. Union of India, judgment (15 Feb 2024)',
    sources: [SCO_EB_TIMELINE],
  },
  {
    id: 'hel004',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Corporate donation cap',
    kind: 'funding',
    difficulty: 'extreme',
    year: 2017,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "Before the Finance Act 2017 removed it, a company's political donations in a year were capped at what share of its average net profit of the previous three years?",
    options: ['2%', '5%', '10%', '7.5%'],
    correctIndex: 3,
    explanation:
      'Section 182 of the Companies Act 2013 capped it at 7.5% (5% under the 1956 Act). The 2017 change allowed unlimited giving; in 2024 the SC held the removal manifestly arbitrary, noting it let loss-making firms donate without limit. The Union had said lifting the cap would discourage shell companies.',
    sourceUrl: SC_EB_JUDGMENT,
    sourceLabel: 'Supreme Court of India — ADR v. Union of India, judgment (15 Feb 2024)',
  },
  {
    id: 'hel005',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds',
    kind: 'institution',
    difficulty: 'expert',
    year: 2017,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'In September 2017, which body warned that letting a commercial bank issue electoral bonds could hurt the credibility of the financial system and the central bank?',
    options: [
      'The Reserve Bank of India',
      'The Comptroller and Auditor General',
      'The Securities and Exchange Board of India',
      'The Law Commission of India',
    ],
    correctIndex: 0,
    explanation:
      "Per the SC judgment, the RBI objected by letter on 14 Sept 2017; earlier, on 26 May 2017, the ECI warned the Finance Act changes would have a 'serious impact on transparency'. The government went ahead and authorised SBI to sell the bonds, defending the scheme as moving donations into banking channels.",
    sourceUrl: SC_EB_JUDGMENT,
    sourceLabel: 'Supreme Court of India — ADR v. Union of India, judgment (15 Feb 2024)',
    sources: [SCO_EB_TIMELINE],
  },
  {
    id: 'hel006',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds',
    kind: 'funding',
    difficulty: 'extreme',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Under the 2018 scheme, a registered party could receive electoral bonds only if it had won at least what share of votes in the last Lok Sabha or Assembly election?',
    options: ['0.5%', '1%', '2%', '6%'],
    correctIndex: 1,
    explanation:
      "The scheme required registration under Section 29A of the RP Act and not less than 1% of votes polled in the last Lok Sabha or Assembly election. Bonds were valid for 15 days; any bond not encashed in time went to the Prime Minister's Relief Fund.",
    sourceUrl: SC_EB_JUDGMENT,
    sourceLabel: 'Supreme Court of India — ADR v. Union of India, judgment (15 Feb 2024)',
    sources: [SCO_EB_TIMELINE],
  },
  {
    id: 'hel007',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds case',
    kind: 'institution',
    difficulty: 'expert',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Which political party was the only one to challenge the electoral bond scheme in the Supreme Court in its own name?',
    options: ['INC', 'AAP', 'CPI(M)', 'TMC'],
    correctIndex: 2,
    explanation:
      'CPI(M) filed its writ petition on 19 Jan 2018, alongside the NGOs ADR and Common Cause. The Union argued the scheme kept donations in banking channels and shielded donors from retribution; the SC struck it down in Feb 2024.',
    sourceUrl: SCO_EB_TIMELINE,
    sourceLabel: 'Supreme Court Observer — A complete timeline of the Electoral Bond Scheme (14 May 2024)',
  },
  {
    id: 'hel008',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds disclosure',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'After the February 2024 verdict, SBI asked the Supreme Court for time until when to disclose bond details, a plea the court dismissed on 11 March 2024?',
    options: ['15 March 2024', '31 December 2024', '31 March 2025', '30 June 2024'],
    correctIndex: 3,
    explanation:
      "SBI said matching buyer and encashment data kept in separate 'silos' was complex. The five-judge bench dismissed the plea, saying the information was readily available, and ordered disclosure by close of business on 12 March; the ECI published the data on 14 March 2024.",
    sourceUrl: 'https://thefederal.com/category/news/electoral-bonds-case-supreme-court-hearing-sbi-plea-dismissed-113272',
    sourceLabel: 'The Federal — Electoral bonds case: SC junks plea, asks SBI to submit details by tomorrow (11 Mar 2024)',
    sources: [SCO_EB_TIMELINE],
  },
  {
    id: 'hel009',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds disclosure',
    kind: 'institution',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "What did the Supreme Court order SBI to disclose on 18 March 2024, which finally let the public match each bond's buyer to the party that encashed it?",
    options: [
      "Each bond's unique alphanumeric number",
      "Buyers' income-tax returns",
      "Parties' audited balance sheets",
      'Branch-wise CCTV footage',
    ],
    correctIndex: 0,
    explanation:
      "SBI's first release listed purchases and encashments separately. On 18 March the court told SBI to disclose 'all' details, including alphanumeric numbers, with its chairman's affidavit by 21 March; SBI complied. SBI's counsel had argued donors bought bonds on an assurance of anonymity.",
    sourceUrl: SCO_EB_TIMELINE,
    sourceLabel: 'Supreme Court Observer — A complete timeline of the Electoral Bond Scheme (14 May 2024)',
    sources: [
      'https://www.scconline.com/blog/post/2024/03/18/supreme-court-directs-sbi-disclose-conceivable-details-electoral-bonds-including-alphanumeric-number/',
    ],
  },

  // ── Electoral bonds: who got, who gave ──────────────────────────────────────
  {
    id: 'hel010',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds data',
    kind: 'funding',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'In the SBI data the ECI published in March 2024 (bonds encashed 12 April 2019 to 24 January 2024), which party encashed the largest amount?',
    options: ['TMC', 'BJP', 'INC', 'BRS'],
    correctIndex: 1,
    explanation:
      'The BJP encashed Rs 6,060.5 crore, about 47.5% of the total, followed by TMC (Rs 1,609.5 cr) and INC (Rs 1,421.9 cr). The Union Home Minister argued the BJP got about Rs 6,000 crore with 303 MPs while other parties together got more; fact-checkers disputed his overall total.',
    sourceUrl: BS_EB_PARTIES,
    sourceLabel: 'Business Standard — Electoral bonds: BJP received more funds than the next 6 parties combined (15 Mar 2024)',
    sources: [
      'https://www.tribuneindia.com/news/india/bonds-not-black-money-whats-the-ruckus-all-about-asks-shah-601010',
      'https://scroll.in/article/1065281/home-minister-amit-shah-cited-wrong-data-to-underplay-bjps-share-of-electoral-bonds',
    ],
  },
  {
    id: 'hel011',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds data',
    kind: 'funding',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Which party was the second-largest encasher of electoral bonds in the SBI data released in March 2024, with about Rs 1,609.5 crore?',
    options: ['INC', 'BJD', 'TMC', 'DMK'],
    correctIndex: 2,
    explanation:
      "TMC encashed Rs 1,609.5 crore (12.6%), ahead of the Congress (Rs 1,421.9 cr, 11.1%). Its biggest donor, per ADR's later matching of bond numbers, was lottery firm Future Gaming (Rs 542 cr). Receiving bonds was legal under the scheme then in force.",
    sourceUrl: BS_EB_PARTIES,
    sourceLabel: 'Business Standard — Electoral bonds: BJP received more funds than the next 6 parties combined (15 Mar 2024)',
    sources: [PRINT_ADR_TOP_DONORS],
  },
  {
    id: 'hel012',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds data',
    kind: 'funding',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Which regional party ranked fourth among bond encashers in the March 2024 SBI data, with Rs 1,214.7 crore?',
    options: ['BJD', 'DMK', 'YSRCP', 'BRS'],
    correctIndex: 3,
    explanation:
      "After the BJP, TMC and Congress came BRS (Rs 1,214.7 cr), then Odisha's BJD (Rs 775.5 cr). The Wire noted BRS encashed nothing after losing the Telangana Assembly election in December 2023. Per ADR, its top bond donor was Megha Engineering (Rs 195 cr).",
    sourceUrl:
      'https://m.thewire.in/article/politics/top-five-political-parties-saw-electoral-bonds-fortunes-turning-with-election-wins-and-losses',
    sourceLabel: 'The Wire — Top five political parties saw electoral bonds fortunes turning with election wins and losses (Mar 2024)',
    sources: [PRINT_ADR_TOP_DONORS],
  },
  {
    id: 'hel013',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds donors',
    kind: 'funding',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'The single biggest buyer of electoral bonds bought Rs 1,368 crore worth between 2020 and 2024. What business is it in?',
    options: ['Lotteries', 'Telecom', 'Steel', 'Pharmaceuticals'],
    correctIndex: 0,
    explanation:
      'Future Gaming and Hotel Services, a Coimbatore lottery firm, was the top buyer. Scroll (Project Electoral Bond) reported the ED had attached its assets in 2022–23 in a money-laundering probe begun in 2019. Buying bonds was legal under the scheme; the SC in Aug 2024 declined to order a court-monitored probe into alleged quid pro quo.',
    status:
      'ED money-laundering probe reported by Scroll (Mar 2024); no conviction of the company; bond purchases were legal under the scheme then in force.',
    sourceUrl: 'https://scroll.in/article/1065267/after-raids-by-central-agencies-these-21-companies-purchased-electoral-bonds',
    sourceLabel: 'Scroll (Project Electoral Bond) — After raids by central agencies, these companies bought electoral bonds (15 Mar 2024)',
    sources: [BS_EB_PARTIES],
  },
  {
    id: 'hel014',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds donors',
    kind: 'funding',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "Per ADR's matching of bond numbers, which party got the most (Rs 542 crore) from the top buyer, lottery firm Future Gaming?",
    options: ['DMK', 'TMC', 'YSRCP', 'BJP'],
    correctIndex: 1,
    explanation:
      'Future Gaming gave TMC Rs 542 cr, DMK Rs 503 cr and YSRCP Rs 154 cr, and was the top bond donor to all three; the BJP also received Rs 100 cr from it. Such donations were legal under the scheme then in force.',
    sourceUrl: PRINT_ADR_TOP_DONORS,
    sourceLabel: 'ThePrint (PTI) — Electoral bond: Future Gaming biggest donor to TMC, DMK, YSRCP (28 Mar 2024)',
    sources: [
      'https://www.business-standard.com/elections/lok-sabha-election/electoral-bonds-data-here-s-how-much-the-bjp-congress-and-tmc-received-124032200760_1.html',
    ],
  },
  {
    id: 'hel015',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds donors',
    kind: 'funding',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Hyderabad-based Megha Engineering, the second-biggest bond buyer, was the top bond donor to which two parties, according to ADR?',
    options: ['INC and TMC', 'DMK and YSRCP', 'BJP and BRS', 'BJD and TDP'],
    correctIndex: 2,
    explanation:
      "ADR's analysis (PTI, 28 Mar 2024) found MEIL gave the BJP Rs 584 cr and BRS Rs 195 cr, and was the second-largest donor to DMK, YSRCP and TDP. A Megha-group firm also gave the Congress Rs 110 cr (Business Standard). Donations were legal under the scheme then in force.",
    sourceUrl: PRINT_ADR_TOP_DONORS,
    sourceLabel: 'ThePrint (PTI) — Electoral bond: Future Gaming biggest donor to TMC, DMK, YSRCP (28 Mar 2024)',
    sources: [
      'https://www.business-standard.com/elections/lok-sabha-election/electoral-bonds-data-here-s-how-much-the-bjp-congress-and-tmc-received-124032200760_1.html',
    ],
  },
  {
    id: 'hel016',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds donors',
    kind: 'funding',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Qwik Supply Chain, the third-largest bond buyer (Rs 410 crore), is linked in filings to which business group, which said Qwik is not its subsidiary?',
    options: ['Tata', 'Adani', 'Vedanta', 'Reliance'],
    correctIndex: 3,
    explanation:
      "PTI reported Qwik's registered address is in Navi Mumbai's Dhirubhai Ambani Knowledge City and that it has links to Reliance Industries. A Reliance spokesperson said: 'Qwik Supply Chain Pvt Ltd is not a subsidiary of any Reliance entity.' Per ADR, the BJP received Rs 375 cr from Qwik.",
    sourceUrl:
      'https://theprint.in/economy/reliance-linked-qwik-supply-third-largest-electoral-bond-buyer-reliance-says-co-not-its-subsidiary/2002057/',
    sourceLabel: 'ThePrint (PTI) — Reliance-linked Qwik Supply third largest electoral bond buyer; Reliance says co not its subsidiary (15 Mar 2024)',
    sources: [PRINT_ADR_TOP_DONORS],
  },
  {
    id: 'hel017',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds and raids',
    kind: 'funding',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'A March 2024 analysis by Project Electoral Bond (Scroll, Newslaundry and others) found several companies bought bonds soon after what?',
    options: [
      'Action by agencies such as the ED, I-T or CBI',
      'Launching a public share offer',
      'Opening offices abroad',
      'Signing CSR pledges with states',
    ],
    correctIndex: 0,
    explanation:
      "The analysis listed buyers, including Future Gaming and Megha Engineering, that bought bonds after raids or probes; critics alleged quid pro quo. The Union Finance Minister called linking ED searches to purchases a 'huge assumption', and the SC in Aug 2024 declined to order a court-monitored probe.",
    status:
      'Allegation by media analysts and critics; no court finding of quid pro quo; SC dismissed pleas for a court-monitored SIT (2 Aug 2024).',
    sourceUrl: 'https://scroll.in/article/1065267/after-raids-by-central-agencies-these-21-companies-purchased-electoral-bonds',
    sourceLabel: 'Scroll (Project Electoral Bond) — After raids by central agencies, these companies bought electoral bonds (15 Mar 2024)',
    sources: [
      'https://www.thehindu.com/news/national/huge-assumption-to-link-ed-raids-with-electoral-bond-purchases-says-finance-minister-nirmala-sitharaman/article67955597.ece',
      'https://www.livelaw.in/top-stories/supreme-court-dismisses-pleas-for-sit-investigation-into-electoral-bonds-quid-pro-quo-says-ordinary-remedies-not-invoked-265451',
    ],
  },
  {
    id: 'hel018',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Bonds probe plea',
    kind: 'institution',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'In August 2024, what did the Supreme Court do with petitions seeking a court-monitored SIT probe into alleged electoral-bond quid pro quo?',
    options: [
      'Ordered a CBI probe',
      'Dismissed them; said ordinary legal remedies must be tried first',
      'Referred them to a seven-judge bench',
      'Ordered parties to refund all bond money',
    ],
    correctIndex: 1,
    explanation:
      "On 2 Aug 2024 the court dismissed pleas by Common Cause and CPIL, calling a court-monitored SIT 'premature' and 'inappropriate' while remedies under criminal procedure law had not been invoked. It also refused to order recovery of bond money or reopening of parties' tax assessments.",
    status: 'Court dismissed the petitions (2 Aug 2024); no court finding on the alleged quid pro quo.',
    sourceUrl:
      'https://www.livelaw.in/top-stories/supreme-court-dismisses-pleas-for-sit-investigation-into-electoral-bonds-quid-pro-quo-says-ordinary-remedies-not-invoked-265451',
    sourceLabel: "LiveLaw — Supreme Court dismisses pleas for SIT investigation into electoral bonds 'quid pro quo' (2 Aug 2024)",
  },

  // ── Other money rules: cash, foreign money, trusts ─────────────────────────
  {
    id: 'hel019',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Cash donations',
    kind: 'funding',
    difficulty: 'extreme',
    year: 2017,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Since the Finance Act 2017, a party may accept a donation above what amount only by cheque, bank draft or electronic transfer (or, until 2024, a bond)?',
    options: ['Rs 500', 'Rs 20,000', 'Rs 2,000', 'Rs 1 lakh'],
    correctIndex: 2,
    explanation:
      'The 2017 amendment to Section 13A of the Income Tax Act requires donations over Rs 2,000 to come through banking channels. Separately, parties must report to the ECI only donations above Rs 20,000. The SC noted in 2024 that cash funding up to Rs 2,000 remains permitted.',
    sourceUrl: SC_EB_JUDGMENT,
    sourceLabel: 'Supreme Court of India — ADR v. Union of India, judgment (15 Feb 2024)',
  },
  {
    id: 'hel020',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'FCRA and party funds',
    kind: 'funding',
    difficulty: 'simple',
    year: 2014,
    asOf: '2026-09',
    govt: 'UPA',
    question:
      "In March 2014, the Delhi High Court held that which parties had prima facie taken donations from 'foreign sources' (Vedanta group firms) in breach of FCRA?",
    options: ['INC only', 'BJP only', 'CPI(M) and TMC', 'BJP and INC'],
    correctIndex: 3,
    explanation:
      'On a petition by ADR, the court held donations from Sterlite and Sesa (Vedanta subsidiaries) to both parties fell foul of the FCRA 1976 and told the Centre and ECI to act within six months. The Congress said no law was broken; Vedanta said the donations followed company law. Finance Act changes in 2016 and 2018 later altered the law retrospectively.',
    sourceUrl: 'https://www.business-standard.com/article/elections-2014/sterlite-sesa-funding-of-cong-bjp-illegal-hc-114032900025_1.html',
    sourceLabel: 'Business Standard — Sterlite, Sesa funding of Cong, BJP illegal: HC (29 Mar 2014)',
  },
  {
    id: 'hel021',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'FCRA and party funds',
    kind: 'funding',
    difficulty: 'extreme',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "The Finance Act 2018 made a 2016 change to FCRA's definition of 'foreign source' retrospective from which date?",
    options: ['5 August 1976', '26 September 2010', '1 April 2014', '26 January 1950'],
    correctIndex: 0,
    explanation:
      "The 2018 Finance Bill moved the start date from 26 Sept 2010 to 5 Aug 1976, when FCRA 1976 took effect. The Home Ministry said the aim was to keep 'foreign source' consistent with FDI policy; critics said it shielded the BJP and Congress from the 2014 Delhi HC ruling. The Lok Sabha passed it without debate.",
    sourceUrl: 'https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=1522983',
    sourceLabel: 'PIB (Ministry of Home Affairs) — Amendment in FCRA (7 Mar 2018)',
    sources: [
      'https://www.business-standard.com/article/economy-policy/lok-sabha-passes-bill-to-prevent-scrutiny-of-foreign-poll-funds-to-parties-118031800292_1.html',
    ],
  },
  {
    id: 'hel022',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Trusts',
    kind: 'funding',
    difficulty: 'extreme',
    year: 2013,
    asOf: '2026-09',
    govt: 'UPA',
    question:
      "Under the Electoral Trusts Scheme notified in 2013, what minimum share of a year's contributions must a trust pass on to registered parties?",
    options: ['50%', '95%', '75%', '100%'],
    correctIndex: 1,
    explanation:
      'Notified by the UPA-2 government on 31 Jan 2013, the scheme lets companies form trusts that must donate at least 95% of each year\'s contributions, keeping up to 5% for expenses. Unlike bonds, trusts report both donors and recipient parties to the ECI.',
    sourceUrl:
      'https://indianexpress.com/article/explained/explained-politics/what-are-electoral-trusts-and-how-are-they-funded-explained-10433139/',
    sourceLabel: 'The Indian Express — Explained: What are electoral trusts and how are they funded? (22 Dec 2025)',
    sources: [SC_EB_JUDGMENT],
  },
  {
    id: 'hel023',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Electoral Trusts',
    kind: 'funding',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'According to ADR, what share of the Rs 3,826 crore that electoral trusts gave to parties in FY 2024-25 went to the BJP?',
    options: ['About 17%', 'About 47%', 'About 83%', 'About 97%'],
    correctIndex: 2,
    explanation:
      "ADR's Feb 2026 analysis: the BJP got Rs 3,157.65 cr (82.52%), mostly from Prudent (Rs 2,180.7 cr) and Progressive (Rs 757.6 cr) trusts. 21 other parties, including INC, TMC, YSRCP, TDP, AAP and BJD, shared Rs 668.7 cr (17.48%); Prudent gave the Congress Rs 216.3 cr.",
    sourceUrl: 'https://adrindia.org/content/Analysis_of_Contribution_reports_of_Electoral_trusts_FY_2024-25',
    sourceLabel: 'ADR — Analysis of Contribution Reports of Electoral Trusts for FY 2024-25 (13 Feb 2026)',
  },

  // ── Party income (ADR analyses of filings with the ECI) ─────────────────────
  {
    id: 'hel024',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Party income (ADR)',
    kind: 'funding',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'According to ADR, which national party declared the second-highest income in FY 2024-25, about Rs 918 crore?',
    options: ['CPI(M)', 'AAP', 'BSP', 'INC'],
    correctIndex: 3,
    explanation:
      'Six national parties declared Rs 7,960 cr in total. The BJP declared Rs 6,769.14 cr (85.03%) and the Congress Rs 918.28 cr (11.53%), down 25% on FY 2023-24; the Congress spent about Rs 1,112 cr, 21% more than its income. CPI(M) declared Rs 172.6 cr.',
    sourceUrl:
      'https://adrindia.org/content/bjp-declares-rs-6769-crore-income-highest-among-national-parties-says-association-for-democratic-reforms',
    sourceLabel: 'ADR (via PTI/Telegraph) — BJP declares Rs 6,769 crore income, highest among national parties (Mar 2026)',
  },
  {
    id: 'hel025',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Party income (ADR)',
    kind: 'funding',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'According to ADR, which national party reported no donations at all in FY 2024-25, with 100% of its Rs 58.58 crore income from other sources?',
    options: ['BSP', 'AAP', 'CPI(M)', 'NPEP'],
    correctIndex: 0,
    explanation:
      "ADR's analysis of parties' filings with the ECI: the BSP showed no donations, while AAP got 99.85% and NPEP 97.74% of income from contributions; CPI(M) got 48.77%. The BSP's spending (Rs 106.30 cr) exceeded its income by 81.45%.",
    sourceUrl:
      'https://adrindia.org/content/bjp-declares-rs-6769-crore-income-highest-among-national-parties-says-association-for-democratic-reforms',
    sourceLabel: 'ADR (via PTI/Telegraph) — BJP declares Rs 6,769 crore income, highest among national parties (Mar 2026)',
  },

  // ── Who sits in the Lok Sabha (ADR, 2024) ───────────────────────────────────
  {
    id: 'hel026',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Lok Sabha 2024 (ADR)',
    kind: 'institution',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'According to ADR, what share of the 543 MPs elected in 2024 declared criminal cases against themselves in their affidavits?',
    options: ['34%', '46%', '23%', '58%'],
    correctIndex: 1,
    explanation:
      '251 of 543 winners (46%) declared criminal cases, up from 43% in 2019 and 34% in 2014; 170 (31%) declared serious cases such as murder or crimes against women. Declared cases are not convictions; ADR said 27 of the 251 had been convicted in some case.',
    sourceUrl: ADR_LS2024,
    sourceLabel: 'ADR — Record 46% of newly-elected Lok Sabha MPs facing criminal cases (Jun 2024)',
  },
  {
    id: 'hel027',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Lok Sabha 2024 (ADR)',
    kind: 'institution',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Among these four parties, which had the highest share of 2024 Lok Sabha winners declaring criminal cases, according to ADR?',
    options: ['BJP', 'INC', 'DMK', 'TMC'],
    correctIndex: 2,
    explanation:
      'DMK: 13 of 22 winners (59%); INC 49 of 99 (49%); TMC 13 of 29 (45%); BJP 94 of 240 (39%). Among smaller groups, Shiv Sena had 5 of 7 (71%). Declared cases in affidavits are not findings of guilt.',
    sourceUrl: ADR_LS2024,
    sourceLabel: 'ADR — Record 46% of newly-elected Lok Sabha MPs facing criminal cases (Jun 2024)',
  },
  {
    id: 'hel028',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Lok Sabha 2024 (ADR)',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'What share of the 543 Lok Sabha MPs elected in 2024 were crorepatis by their own declared assets, according to ADR?',
    options: ['58%', '72%', '82%', '93%'],
    correctIndex: 3,
    explanation:
      '504 of 543 winners (93%) declared assets above Rs 1 crore, up from 88% in 2019, 82% in 2014 and 58% in 2009. ADR found a crorepati candidate had a 19.6% chance of winning, against 0.7% for a candidate with assets under Rs 1 crore.',
    sourceUrl: ADR_LS2024_ASSETS,
    sourceLabel: "ADR — 'Criminals and crorepatis': Meet the new MPs of Lok Sabha 2024 (Jun 2024)",
  },
  {
    id: 'hel029',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Lok Sabha 2024 (ADR)',
    kind: 'institution',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'The richest MP elected in 2024, with declared assets of Rs 5,705 crore, belongs to which party?',
    options: ['TDP', 'BJP', 'INC', 'BRS'],
    correctIndex: 0,
    explanation:
      "ADR's analysis of affidavits put a TDP MP at the top with Rs 5,705 cr, followed by two BJP MPs with Rs 4,568 cr and Rs 1,241 cr. All 16 TDP winners and all 12 JD(U) winners were crorepatis. Declared wealth is not an allegation of wrongdoing.",
    sourceUrl: ADR_LS2024_ASSETS,
    sourceLabel: "ADR — 'Criminals and crorepatis': Meet the new MPs of Lok Sabha 2024 (Jun 2024)",
  },

  // ── Referees: courts, ECI, rolls, machines ──────────────────────────────────
  {
    id: 'hel030',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Chandigarh mayor poll',
    kind: 'institution',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'In Feb 2024 the Supreme Court declared a new Chandigarh mayor after finding that 8 ballots the presiding officer had marked invalid were validly cast for whom?',
    options: [
      'The BJP candidate',
      'The AAP-Congress alliance candidate',
      'A nominated councillor',
      "The city's MP",
    ],
    correctIndex: 1,
    explanation:
      "Using Article 142 on 20 Feb 2024, a three-judge bench quashed the 30 Jan result and declared the AAP candidate (backed by Congress) mayor: 12 + 8 = 20 votes to the BJP candidate's 16. It issued a Section 340 CrPC show-cause notice to the presiding officer over a false statement to the court; he tendered an unconditional apology in April 2024.",
    status:
      'SC quashed the declared result (20 Feb 2024); presiding officer issued a Section 340 CrPC show-cause notice and apologised (Apr 2024); later outcome not verified.',
    sourceUrl: 'https://api.sci.gov.in/supremecourt/2024/4999/4999_2024_1_15_50631_Judgement_20-Feb-2024.pdf',
    sourceLabel: 'Supreme Court of India — Kuldeep Kumar v. U.T. Chandigarh, judgment (20 Feb 2024)',
    sources: [
      'https://www.livelaw.in/top-stories/chandigarh-mayor-election-returning-officer-anil-masih-tenders-unconditional-apology-to-suprme-court-254389',
    ],
  },
  {
    id: 'hel031',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'CEC appointments law',
    kind: 'institution',
    difficulty: 'simple',
    year: 2023,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'The 2023 law on appointing the CEC and Election Commissioners replaced which member of the selection panel the Supreme Court had set in the Anoop Baranwal case?',
    options: ['The Prime Minister', 'The Leader of Opposition', 'The Chief Justice of India', 'The Lok Sabha Speaker'],
    correctIndex: 2,
    explanation:
      'Anoop Baranwal (Mar 2023) set a PM–LoP–CJI panel until Parliament made a law. The 2023 Act swapped the CJI for a Union Cabinet minister nominated by the PM. The judgment itself said its panel applied until Parliament legislated; petitioners say the Act gives the executive dominant control. The challenge is pending (Sept 2026).',
    sourceUrl: 'https://www.scobserver.in/reports/sc-delivers-split-verdict-sends-eci-appointments-law-challenge-to-larger-bench/',
    sourceLabel: 'Supreme Court Observer — SC delivers split verdict, sends ECI appointments law challenge to larger bench (23 Sep 2026)',
  },
  {
    id: 'hel032',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'CEC appointments law',
    kind: 'institution',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'In September 2026, what did a two-judge Supreme Court bench do with the challenges to the 2023 law on appointing the CEC and Election Commissioners?',
    options: [
      'Struck the law down',
      'Upheld the law',
      'Stayed all appointments made under it',
      'Split, and sent the case to the CJI for a larger bench',
    ],
    correctIndex: 3,
    explanation:
      "On 23 Sept 2026 one judge rejected the Union's plea for a larger bench and said a Cabinet minister on the panel prima facie fails the 'perception test'; the other held a substantial question of law arose. Both sent the papers to the CJI. The Union had sought the reference and compared the process with the judges' collegium. The law remains in force.",
    sourceUrl: 'https://www.scobserver.in/reports/sc-delivers-split-verdict-sends-eci-appointments-law-challenge-to-larger-bench/',
    sourceLabel: 'Supreme Court Observer — SC delivers split verdict, sends ECI appointments law challenge to larger bench (23 Sep 2026)',
    sources: [
      'https://www.thehindu.com/news/national/minister-in-cec-ec-selection-panel-fails-perception-test-says-justice-datta-in-split-verdict/article71499280.ece',
    ],
  },
  {
    id: 'hel033',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'EVM-VVPAT',
    kind: 'institution',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In April 2024, what did the Supreme Court decide on pleas for counting 100% of VVPAT slips?',
    options: [
      'Rejected them, but let runners-up seek checks of 5% of EVMs',
      'Ordered 100% VVPAT slip counting',
      'Ordered a return to paper ballots',
      'Let voters take their VVPAT slips home',
    ],
    correctIndex: 0,
    explanation:
      "On 26 Apr 2024 a two-judge bench dismissed ADR's pleas for paper ballots, voter handling of slips or full counts. It ordered symbol loading units sealed for 45 days and let 2nd- or 3rd-placed candidates seek, at their cost and within 7 days of results, a check of burnt memory in 5% of EVMs per constituency.",
    sourceUrl: 'https://www.scobserver.in/reports/vvpat-vote-verification-judgement-summary/',
    sourceLabel: 'Supreme Court Observer — VVPAT Verification: Judgement Summary (9 May 2024)',
  },
  {
    id: 'hel034',
    domain: 'civics',
    region: 'India',
    state: 'KA',
    topic: 'Elections & Funding',
    subtopic: 'Aland voter deletions',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2023,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "A Karnataka SIT alleges a racket tried to delete how many voters from the Aland constituency's roll through the ECI's online services in 2022–23?",
    options: ['598', '5,994', '59,940', '6 lakh'],
    correctIndex: 1,
    explanation:
      'The case began in Feb 2023 on an ECI official\'s complaint. The SIT chargesheeted a former BJP MLA and six others (Dec 2025); on 1 Sept 2026 the Karnataka HC declined to quash it and the trial court fixed charge framing. The ex-MLA denies the charges; the accused are on bail. The ECI later added Aadhaar-based OTP checks.',
    status:
      'Chargesheet filed (Dec 2025); Karnataka HC refused to quash (1 Sep 2026); at charge-framing stage; accused on bail; former MLA denies charges; no conviction.',
    sourceUrl:
      'https://indianexpress.com/article/legal-news/aland-vote-theft-karnataka-high-court-bjp-guttedar-plea-chargesheet-10858727/',
    sourceLabel: "The Indian Express — Aland 'vote theft': Karnataka High Court rejects former BJP MLA's plea to scrap chargesheet (1 Sep 2026)",
    sources: [
      'https://indianexpress.com/article/cities/bangalore/karnataka-aland-vote-theft-trial-subhash-guttedar-sit-chargesheet-10611427/',
      'https://www.thehindu.com/news/national/karnataka/aland-voter-fraud-chargesheet-names-former-bjp-mla-and-his-son-as-prime-accused/article70389221.ece',
    ],
  },
  {
    id: 'hel035',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Elections & Funding',
    subtopic: 'Bihar SIR 2025',
    kind: 'institution',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "About how many names were left out of Bihar's draft electoral roll of 1 August 2025, published during the Special Intensive Revision?",
    options: ['3.66 lakh', '21.5 lakh', '65 lakh', '1.5 crore'],
    correctIndex: 2,
    explanation:
      'Bihar had 7.89 crore electors on 24 June 2025; the draft had 7.24 crore, with about 65 lakh removed. The final roll (30 Sept 2025) had 7.42 crore after 21.53 lakh additions and 3.66 lakh deletions. Petitioners challenged the exercise; in May 2026 the SC upheld it as aimed at restoring the accuracy of the rolls.',
    sourceUrl:
      'https://www.thehindu.com/elections/bihar-assembly/bihar-assembly-polls-final-voter-list-sir-election-commission/article70112730.ece',
    sourceLabel: "The Hindu — 7.42 crore voters on Bihar's final electoral rolls at the end of SIR (30 Sep 2025)",
  },
  {
    id: 'hel036',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Elections & Funding',
    subtopic: 'Bihar SIR 2025',
    kind: 'institution',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "In May 2026, how did the Supreme Court rule on challenges to the ECI's Special Intensive Revision of Bihar's electoral rolls?",
    options: [
      'Quashed it as arbitrary',
      'Ordered a fresh revision using Aadhaar only',
      'Referred the question to Parliament',
      "Upheld it as within the ECI's powers",
    ],
    correctIndex: 3,
    explanation:
      'On 27 May 2026 a two-judge bench led by the CJI held the SIR valid under Article 324 and Section 21(3) of the RP Act 1950, and proportionate given its safeguards. It rejected the argument that listed voters enjoy a presumption of citizenship; during hearings it had ordered Aadhaar accepted as a 12th identity document.',
    sourceUrl:
      'https://www.scobserver.in/reports/supreme-court-backs-bihar-sir-exercise-upholds-ecis-powers-to-purify-electoral-rolls/',
    sourceLabel: "Supreme Court Observer — Supreme Court backs Bihar SIR exercise, upholds ECI's powers (27 May 2026)",
    sources: [
      'https://www.scobserver.in/reports/revision-of-electoral-rolls-in-bihar-day-8-sc-directs-the-inclusion-of-aadhaar-as-document-under-the-sir-exercise/',
    ],
  },

  // ── Defections and toppled governments: facts and court outcomes ───────────
  {
    id: 'hel037',
    domain: 'civics',
    region: 'India',
    state: 'KA',
    topic: 'Elections & Funding',
    subtopic: 'Anti-defection: Karnataka 2019',
    kind: 'institution',
    difficulty: 'simple',
    year: 2019,
    asOf: '2026-09',
    govt: 'Other',
    question:
      'In November 2019 the Supreme Court upheld the disqualification of 17 dissident Congress and JD(S) MLAs in Karnataka, but ruled what?',
    options: [
      'They could contest the bypolls',
      'They were barred until the term ended',
      'They had to repay their salaries',
      'They were restored as MLAs',
    ],
    correctIndex: 0,
    explanation:
      'The court upheld the Speaker\'s disqualification under the Tenth Schedule but held he could not bar them from contesting until the end of the term: "neither under the Constitution nor under the statutory scheme" is disqualification a bar to re-election. They were disqualified by the then Speaker.',
    sourceUrl:
      'https://www.thehindu.com/news/national/supreme-court-upholds-speakers-disqualification-of-17-karnataka-mlas/article61619826.ece',
    sourceLabel: "The Hindu — Supreme Court upholds Speaker's disqualification of 17 Karnataka MLAs (13 Nov 2019)",
  },
  {
    id: 'hel038',
    domain: 'civics',
    region: 'India',
    state: 'MP',
    topic: 'Elections & Funding',
    subtopic: 'Madhya Pradesh 2020',
    kind: 'institution',
    difficulty: 'expert',
    year: 2020,
    asOf: '2026-09',
    govt: 'INC',
    question: "Madhya Pradesh's Congress government fell in March 2020 after how many of the party's MLAs resigned?",
    options: ['16', '22', '10', '30'],
    correctIndex: 1,
    explanation:
      'Twenty-two Congress MLAs, including six ministers, resigned after a senior leader quit the party and joined the BJP. After the Supreme Court ordered a floor test, the chief minister resigned on 20 March 2020, clearing the way for a BJP government.',
    sourceUrl: 'https://theprint.in/politics/kamal-nath-resigns-as-madhya-pradesh-chief-minister-ahead-of-floor-test/384364/',
    sourceLabel: 'ThePrint — Kamal Nath resigns as Madhya Pradesh chief minister ahead of floor test (20 Mar 2020)',
  },
  {
    id: 'hel039',
    domain: 'civics',
    region: 'India',
    state: 'MH',
    topic: 'Elections & Funding',
    subtopic: 'Maharashtra 2022 crisis',
    kind: 'institution',
    difficulty: 'expert',
    year: 2023,
    asOf: '2026-09',
    govt: 'SS',
    question:
      "In May 2023 the Supreme Court called the Governor's 2022 floor-test call unjustified. Why did it say it could not restore the MVA government?",
    options: [
      'The Assembly had been dissolved',
      'Fresh elections had been held',
      'The CM had resigned without facing the floor test',
      'The Governor had since retired',
    ],
    correctIndex: 2,
    explanation:
      'A five-judge bench held on 11 May 2023 that the Governor had no objective material to doubt the government\'s majority, but status quo ante was impossible because the chief minister resigned before the vote; inviting the rebel faction\'s leader, backed by the BJP, was therefore justified.',
    sourceUrl: 'https://indianexpress.com/article/india/sc-shiv-sena-uddhav-thackeray-eknath-shinde-maharashtra-8603495/',
    sourceLabel: "The Indian Express — Governor Koshyari's decision 'unjustified' but cannot restore Uddhav government: SC (11 May 2023)",
    sources: [
      'https://theprint.in/india/sc-resumes-hearing-shiv-sena-split-case-shinde-faction-defends-ecs-organisational-majority-test/3043484/',
    ],
  },
  {
    id: 'hel040',
    domain: 'civics',
    region: 'India',
    state: 'GA',
    topic: 'Elections & Funding',
    subtopic: 'Goa defections 2022',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2022,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "In September 2022, how many of Goa's 11 Congress MLAs merged with the BJP, claiming the anti-defection law's two-thirds exemption?",
    options: ['5', '6', '11', '8'],
    correctIndex: 3,
    explanation:
      "The eight declared the merger on 14 Sept 2022, saying they were two-thirds of the legislature party as the Tenth Schedule requires. Goa's Speaker dismissed the Congress's disqualification plea in Nov 2024; in July 2026 the SC agreed to examine a challenge before a three-judge bench.",
    sourceUrl:
      'https://timesofindia.indiatimes.com/india/goa-speaker-dismisses-disqualification-plea-against-8-congress-mlas-who-joined-bjp-in-2022/articleshow/114852008.cms',
    sourceLabel: 'The Times of India — Goa speaker dismisses disqualification plea against 8 Congress MLAs (1 Nov 2024)',
    sources: [
      'https://www.etvbharat.com/en/state/sc-to-examine-goa-cong-leaders-plea-against-defection-of-mlas-to-bjp-enn26072305951',
    ],
  },
  {
    id: 'hel041',
    domain: 'civics',
    region: 'India',
    state: 'GA',
    topic: 'Elections & Funding',
    subtopic: 'Goa defections 2019',
    kind: 'institution',
    difficulty: 'simple',
    year: 2019,
    asOf: '2026-09',
    govt: 'BJP',
    question: "In July 2019, 10 of Goa's 15 Congress MLAs switched in a single evening to which party?",
    options: ['BJP', 'MGP', 'Goa Forward Party', 'AAP'],
    correctIndex: 0,
    explanation:
      'Led by the then Leader of Opposition, the 10 joined the ruling BJP, taking its strength to 27 in the 40-seat House and leaving the Congress, which had won 17 seats in 2017, with five. A merger by two-thirds of a legislature party is exempt from disqualification.',
    sourceUrl:
      'https://indianexpress.com/article/india/goa-meltdown-congress-mlas-join-bjp-pramod-sawant-kavlekar-karnataka-crisis-5824462/',
    sourceLabel: 'The Indian Express — Meanwhile, a Goa meltdown: 10 of 15 Congress MLAs join BJP (11 Jul 2019)',
  },
  {
    id: 'hel042',
    domain: 'civics',
    region: 'India',
    state: 'AR',
    topic: 'Elections & Funding',
    subtopic: 'Arunachal 2016 (Nabam Rebia)',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2016,
    asOf: '2026-09',
    govt: 'Other',
    question:
      "On what date did a Supreme Court Constitution Bench restore the ousted Congress government in Arunachal Pradesh, calling the Governor's decisions unconstitutional?",
    options: ['26 January 2016', '13 July 2016', '19 February 2016', '16 December 2015'],
    correctIndex: 1,
    explanation:
      "The bench ordered status quo ante as on 15 Dec 2015, reinstating the Congress government — the first time the court restored a government after a new one had taken office. The Centre had defended President's Rule, citing a breakdown of law and order. In 2023 the SC referred part of this ruling to a larger bench.",
    sourceUrl: 'https://indianexpress.com/article/political-pulse/arunachal-case-sc-maharashtra-order-8605516/',
    sourceLabel: 'The Indian Express — Looking back at the landmark Arunachal case referred to in the SC Maharashtra order (12 May 2023)',
  },
  {
    id: 'hel043',
    domain: 'civics',
    region: 'India',
    state: 'TG',
    topic: 'Elections & Funding',
    subtopic: 'Telangana defections',
    kind: 'institution',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'In September 2026 the SC upheld the disqualification of a Telangana MLA who won on a BRS ticket in 2023 and then contested the 2024 Lok Sabha polls for which party?',
    options: ['BJP', 'AIMIM', 'INC', 'TDP'],
    correctIndex: 2,
    explanation:
      "The Speaker had rejected BRS and BJP petitions; the Telangana HC disqualified the Khairatabad MLA on 18 Sept 2026 and a CJI-led bench declined to interfere on 24 Sept. His counsel argued the Tenth Schedule allows a party to condone a member's switch. The Indian Express called it a setback for the ruling Congress.",
    sourceUrl:
      'https://indianexpress.com/article/legal-news/supreme-court-upholds-telangana-mla-danam-nagender-disqualification-10892090/',
    sourceLabel: "The Indian Express — 'Phir aaya Ram': Supreme Court upholds Telangana MLA's disqualification (24 Sep 2026)",
  },

  // ── What elections cost, and the rules being rewritten ─────────────────────
  {
    id: 'hel044',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Cost of elections',
    kind: 'spend',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'The Centre for Media Studies estimated total spending on the 2024 Lok Sabha election, by parties, candidates, government and ECI, at about how much?',
    options: ['Rs 13,500 crore', 'Rs 60,000 crore', 'Rs 5 lakh crore', 'Rs 1.35 lakh crore'],
    correctIndex: 3,
    explanation:
      'CMS put it at Rs 1.35 lakh crore, more than double the Rs 60,000 crore it estimated for 2019, calling it the costliest election anywhere. It is a think-tank estimate covering direct and indirect spending, not an audited figure; CMS said the BJP accounted for 45% of 2019 spending.',
    sourceUrl:
      'https://m.economictimes.com/news/elections/lok-sabha/india/2024-ls-polls-pegged-as-costliest-ever-expenditure-may-touch-rs-1-35-lakh-crore-expert/articleshow/109591713.cms',
    sourceLabel: 'The Economic Times (PTI) — 2024 LS polls pegged as costliest ever, expenditure may touch Rs 1.35 lakh crore (25 Apr 2024)',
  },
  {
    id: 'hel045',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Candidate spending limit',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'What is the most a Lok Sabha candidate may spend in the larger states, under the limit revised in January 2022?',
    options: ['Rs 95 lakh', 'Rs 70 lakh', 'Rs 40 lakh', 'Rs 2 crore'],
    correctIndex: 0,
    explanation:
      'The Law Ministry raised it from Rs 70 lakh to Rs 95 lakh (from Rs 54 lakh to Rs 75 lakh in smaller states and some UTs); Assembly limits rose to Rs 40 lakh and Rs 28 lakh. The SC\'s Feb 2024 bonds judgment cites the same Rs 95 lakh cap.',
    sourceUrl: 'https://www.thehindu.com/news/national/expenditure-limit-for-lok-sabha-assembly-candidates-revised/article38161846.ece',
    sourceLabel: 'The Hindu — Expenditure limit for Lok Sabha, Assembly candidates revised (7 Jan 2022)',
    sources: [SC_EB_JUDGMENT],
  },
  {
    id: 'hel046',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: "Women's reservation & delimitation",
    kind: 'institution',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "In April 2026, why did the Constitution (131st Amendment) Bill, meant to enlarge the Lok Sabha and operationalise women's reservation, fail?",
    options: [
      'The President withheld assent',
      'It fell short of the two-thirds majority',
      'The Rajya Sabha rejected it first',
      'The Supreme Court stayed it',
    ],
    correctIndex: 1,
    explanation:
      "On 17 Apr 2026 it got 298 votes to 230 of 528 voting, short of two-thirds, and the Centre withdrew the linked Delimitation Bill. The government said expansion was needed to give women 33% without cutting seats; the Opposition said using 2011 Census data would shrink southern and north-eastern states' share.",
    sourceUrl: 'https://www.livelaw.in/top-stories/lok-sabha-rejects-constitution-131st-bill-2026-on-delimitation-530736',
    sourceLabel: 'LiveLaw — Lok Sabha rejects Constitution (131st) Amendment Bill 2026; Centre withdraws Delimitation Bill (17 Apr 2026)',
    sources: [
      'https://lawbeat.in/top-stories/womens-reservation-push-stalls-as-lok-sabha-rejects-131st-constitution-amendment-bill-1582102',
    ],
  },
  {
    id: 'hel047',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'One Nation One Election',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "The 'One Nation, One Election' Constitution (129th Amendment) Bill was introduced in the Lok Sabha in December 2024 after a division vote of what?",
    options: ['352 for, 0 against', '303 for, 150 against', '269 for, 198 against', '240 for, 234 against'],
    correctIndex: 2,
    explanation:
      'It was introduced on 17 Dec 2024 over Opposition objections and sent to a Joint Parliamentary Committee. The government says simultaneous polls cut costs; the INDIA bloc opposed the Bill. In July 2026 the Lok Sabha extended the JPC\'s deadline to the last week of the 2026 winter session.',
    sourceUrl:
      'https://www.business-standard.com/politics/one-nation-one-election-bill-tabled-division-vote-269-198-124121700784_1.html',
    sourceLabel: 'Business Standard — Govt tables One Nation, One Election Bill after 269-198 division vote (17 Dec 2024)',
    sources: [
      'https://kashmirobserver.net/2026/07/29/lok-sabha-extends-one-nation-one-election-panel-till-winter-session/',
    ],
  },
  {
    id: 'hel048',
    domain: 'civics',
    region: 'India',
    state: 'GJ',
    topic: 'Elections & Funding',
    subtopic: 'Surat 2024',
    kind: 'institution',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "In April 2024 the BJP won Surat's Lok Sabha seat unopposed after the Congress nominee's papers were rejected. On what ground?",
    options: [
      'He was under 25',
      'He filed after the deadline',
      'He had a criminal conviction',
      "His proposers' signatures were found not genuine",
    ],
    correctIndex: 3,
    explanation:
      "The returning officer rejected the Congress nominee's and his substitute's papers after proposers filed affidavits denying their signatures; the other candidates withdrew or were rejected, and the BJP candidate was declared elected on 22 April 2024. The Congress alleged the proposers were coerced and approached the EC.",
    sourceUrl:
      'https://www.thehindu.com/news/national/why-was-mukesh-dalal-bjp-candidate-declared-winner-in-surat/article68103379.ece',
    sourceLabel: 'The Hindu — Why was the BJP candidate declared winner in Surat? Explained (25 Apr 2024)',
  },
  {
    id: 'hel049',
    domain: 'civics',
    region: 'India',
    state: 'MP',
    topic: 'Elections & Funding',
    subtopic: 'NOTA record, Indore 2024',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "In 2024 Indore set India's record for NOTA votes in a Lok Sabha seat, after the Congress nominee withdrew. How many voters chose NOTA?",
    options: ['2,18,674', '51,660', '1,02,000', '46,559'],
    correctIndex: 0,
    explanation:
      'NOTA took 16.28% of valid votes, beating Gopalganj\'s 51,660 (2019). The Congress urged a NOTA vote after its candidate withdrew at the last moment and later joined the BJP; the BJP won the seat by 11,75,092 votes.',
    sourceUrl:
      'https://www.newindianexpress.com/india/2024/Jun/04/indore-script-twin-electoral-histories-with-218674-nota-votes-bjps-1175-lakh-ballot-gap-win',
    sourceLabel: "The New Indian Express (PTI) — Indore scripts electoral history with 2,18,674 NOTA votes (4 Jun 2024)",
  },
  {
    id: 'hel050',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Elections & Funding',
    subtopic: 'Criminal records disclosure',
    kind: 'institution',
    difficulty: 'expert',
    year: 2021,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "In August 2021 the Supreme Court fined which two parties Rs 5 lakh each for not publishing candidates' criminal records in the 2020 Bihar polls?",
    options: ['BJP and INC', 'CPI(M) and NCP', 'RJD and JD(U)', 'LJP and CPI'],
    correctIndex: 1,
    explanation:
      'It fined INC, BJP, JD(U), RJD, LJP, CPI and RLSP Rs 1 lakh each, and CPI(M) and NCP Rs 5 lakh each for not complying at all with its Feb 2020 order. It also required parties to publish candidates\' criminal cases within 48 hours of selecting them.',
    sourceUrl:
      'https://indianexpress.com/article/india/sc-fines-8-political-parties-for-non-disclosure-of-criminal-info-of-candidates-in-bihar-polls-7447429/',
    sourceLabel: 'The Indian Express — SC fines political parties for non-disclosure of criminal info of candidates in Bihar polls (10 Aug 2021)',
  },
]);
