// HISAAB DO — Forward Court lane (hfw001–hfw040).
// Viral claims about Indian politics, public money and schemes, and what professional
// fact-checkers found. Claims are drawn from every side: see docs/hisaab/research/forwards-notes.md
// for the side each claim served, sources and drops. Every sourceUrl is the fact-check (or the
// official clarification) that states the answer. Statuses verified as of 2026-09.

export const HISAAB_FORWARDS = Object.freeze([
  {
    id: 'hfw001',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: '₹2,000 note ‘GPS nano-chip’',
    kind: 'forward',
    difficulty: 'simple',
    year: 2016,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "Viral forward, November 2016: 'The new ₹2,000 note carries a GPS nano-chip so the government can track hoarded cash.' What did the RBI say?",
    options: [
      'True — the chip only activates when notes are stacked in bulk',
      'Partly true — only notes printed after 2017 carry the chip',
      'False — its spokesperson said no such technology exists',
      'Unverified — the RBI declined to discuss security features',
    ],
    correctIndex: 2,
    explanation:
      "False. Days after demonetisation was announced, an RBI spokesperson told reporters: 'Such a technology does not exist at the moment in the world, then how can we introduce such a feature?' The rumour, which made the note sound like an anti-black-money weapon, spread on WhatsApp within hours of the announcement.",
    sourceUrl: 'https://www.thenewsminute.com/news/rbi-rubbishes-rumours-gps-tracking-chip-rs-2000-note-52652',
    sourceLabel: 'The News Minute — RBI rubbishes rumours of GPS tracking chip in Rs 2000 note (9 Nov 2016)',
  },
  {
    id: 'hfw002',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'UNESCO ‘best PM’ hoax',
    kind: 'forward',
    difficulty: 'simple',
    year: 2016,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "WhatsApp forward, viral since 2016 and revived often: 'UNESCO has declared Narendra Modi the best Prime Minister in the world.' What did fact-checkers find?",
    options: [
      'False — UNESCO says it does not rank political leaders at all',
      'True — it was a 2016 UNESCO education-leadership award',
      'Misleading — the ranking came from a UNESCO staff survey',
      'True — UNESCO ranked him first among G20 heads of government',
    ],
    correctIndex: 0,
    explanation:
      "False. BOOM traced the message to 2016; its photo was a 2013 India Today picture from his Gujarat CM office. UNESCO's press office told AFP in 2019 it 'does not establish rankings of political leaders'. The same hoax template has credited UNESCO with naming Jana Gana Mana the 'best anthem' and CPI(M) the 'most honest party'.",
    status: 'Message rated fake by BOOM (Nov 2022) and AFP (2019); no legal matter involved',
    people: ['Narendra Modi'],
    sourceUrl: 'https://www.boomlive.in/fact-check/unesco-calls-pm-modi-as-worlds-best-prime-minister-fake-claim-revived-20193',
    sourceLabel: "BOOM — UNESCO Calls PM Modi As World's Best Prime Minister? Fake Claim Revived (27 Nov 2022)",
    sources: ['https://factly.in/indias-jana-gana-mana-was-not-declared-as-the-worlds-best-anthem-by-unesco/'],
  },
  {
    id: 'hfw003',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Energy & Mining',
    subtopic: "'NASA Diwali photo' of India",
    kind: 'forward',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "Every Diwali a glowing multicoloured map of India is forwarded as 'NASA's satellite photo of India on Diwali night'. What is the image really?",
    options: [
      'A real NASA photo from Diwali 2012, colour-enhanced by ISRO',
      "A 2019 ISRO night image of the national power grid",
      'An AI-generated image first posted during Diwali 2023',
      'A 2003 NOAA composite showing city lights growing over years',
    ],
    correctIndex: 3,
    explanation:
      "Not a Diwali photo. Factly found it was made in 2003 by NOAA scientist Chris Elvidge, combining years of satellite data to show population growth through city lights: white marks lights seen before 1992, and blue, green and red mark lights that appeared by 1992, 1998 and 2003. It has resurfaced every Diwali since at least 2011.",
    sourceUrl: 'https://factly.in/this-viral-photo-does-not-show-a-satellite-image-of-india-on-diwali-night/',
    sourceLabel: 'Factly — This viral photo does not show a satellite image of India on Diwali night (23 Oct 2025)',
  },
  {
    id: 'hfw004',
    domain: 'civics',
    region: 'India',
    state: 'GJ',
    topic: 'Farm & Food',
    subtopic: "Rahul Gandhi 'potato-gold' clip",
    kind: 'forward',
    difficulty: 'simple',
    year: 2017,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "A viral clip from the 2017 Gujarat campaign shows Rahul Gandhi promising a machine that turns potatoes into gold. What does his full Patan speech show?",
    options: [
      'He was describing a Congress scheme for Gujarat potato farmers',
      "He attributed the promise to Modi — 'not my words' — which the clip cut",
      'The clip was a deepfake; he never mentioned potatoes at all',
      'The full speech matches the clip; he later withdrew the remark',
    ],
    correctIndex: 1,
    explanation:
      "Clipped. In the 12 Nov 2017 Patan speech Gandhi said Modi had told potato farmers he would install such a machine, adding 'these are not my words but Narendra Modi's words'. Alt News found the clip, shared in 2017 by the BJP's IT cell head, dropped that line. Alt News also noted there is no public record of Modi making such a promise.",
    status: 'Clip rated out of context by Alt News (Sep 2020); no legal matter involved',
    people: ['Rahul Gandhi', 'Narendra Modi'],
    sourceUrl: 'https://www.altnews.in/potato-gold-machine-remark-revived-to-mock-rahul-gandhi/',
    sourceLabel: "Alt News — 'Potato-gold' machine remark revived to mock Rahul Gandhi (22 Sep 2020)",
  },
  {
    id: 'hfw005',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Farm & Food',
    subtopic: "Modi 'potato-gold' edited clip",
    kind: 'forward',
    difficulty: 'expert',
    year: 2020,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'In 2020 opposition supporters shared a clip of PM Modi himself apparently promising a machine that turns potatoes into gold. What did Alt News find?',
    options: [
      'True — he said it at a 2014 campaign rally in Uttar Pradesh',
      'True — it was from a 2017 speech to potato farmers in Gujarat',
      'Unverified — the original footage could not be traced anywhere',
      "Edited — it cut a speech where Modi was mocking Rahul Gandhi's line",
    ],
    correctIndex: 3,
    explanation:
      "Edited. Congress supporters trimmed a clip of Modi mocking Gandhi's 'potato-gold' jibe so the words looked like Modi's own promise. Alt News rated it false and said there is no public record of Modi claiming such a machine exists — the same misleading-clip trick earlier used against Gandhi, now turned the other way.",
    status: 'Clip rated false by Alt News (Sep 2020); no legal matter involved',
    people: ['Narendra Modi', 'Rahul Gandhi'],
    sourceUrl:
      'https://www.altnews.in/fact-check-edited-video-is-being-shared-to-falsely-claim-that-aaloo-sona-machine-remarks-belongs-to-pm-modi/',
    sourceLabel: "Alt News — PM Modi's edited clip shared to claim he made the 'potato-gold' machine remark (25 Sep 2020)",
  },
  {
    id: 'hfw006',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: "'₹15 lakh in every account'",
    kind: 'forward',
    difficulty: 'expert',
    year: 2019,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "Oft-shared line: 'Modi promised to deposit ₹15 lakh in every Indian's bank account.' What does the record of his 2013–14 campaign show?",
    options: [
      'Misleading — he said recovered black money could give each poor Indian ₹15–20 lakh',
      "True — it was a written pledge in the BJP's 2014 manifesto on black money",
      'False — he never mentioned any rupee figure at any rally in 2013 or 2014',
      'True — the PMO confirmed in a 2016 RTI reply that such deposits were planned',
    ],
    correctIndex: 0,
    explanation:
      "Misleading. At a Nov 2013 rally in Kanker (Chhattisgarh) Modi said that if black money stashed abroad were brought back, every poor Indian would get ₹15–20 lakh — BOOM calls it an illustration of the sum abroad, not a deposit pledge, and it is not in the 2014 manifesto. Amit Shah later called it a 'jumla' in an interview.",
    status: 'Speech of Nov 2013; BOOM fact-check (Jan 2019); no legal matter involved',
    people: ['Narendra Modi', 'Amit Shah'],
    sourceUrl: 'https://www.boomlive.in/did-modi-promise-to-deposit-rs-15-lakh-in-every-account-a-factcheck',
    sourceLabel: 'BOOM — Did Modi Promise To Deposit Rs 15 Lakh In Every Account?: A FactCheck (22 Jan 2019)',
  },
  {
    id: 'hfw007',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Amit Shah reservation video',
    kind: 'forward',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'April 2024: a viral video showed Amit Shah saying a BJP government would end SC, ST and OBC reservations. What did fact-checkers find?',
    options: [
      'True — it was from a 2024 rally in Bihar, reported live',
      'Misleading — he said it about private-sector jobs only',
      'Doctored — a 2023 Telangana speech about a different quota was edited',
      "Deepfake — the face was AI-generated on an actor's body",
    ],
    correctIndex: 2,
    explanation:
      "Doctored. BOOM traced it to an April 2023 speech in Chevella, Telangana, where Shah spoke of scrapping a religion-based state quota; the audio was edited to make it about SC/ST/OBC quotas. Delhi Police registered an FIR on 28 April 2024; a Congress social-media coordinator was arrested in May 2024 and granted bail. No verdict has been reported.",
    status:
      'Video found doctored by BOOM (Apr 2024); Delhi Police FIR (Apr 2024); one arrest (May 2024), bail granted; no verdict reported as of 2026-09',
    people: ['Amit Shah'],
    sourceUrl:
      'https://www.boomlive.in/fact-check/fact-check-amit-shah-end-reservation-sc-st-obc-old-video-doctored-muslim-reservation-telangana-fake-news-25083',
    sourceLabel: 'BOOM — Video Of Amit Shah Promising To Scrap SC/ST/OBC Reservation Is Doctored (29 Apr 2024)',
    sources: [
      'https://scroll.in/latest/1067194/delhi-police-registers-fir-in-connection-with-doctored-video-of-amit-shah-on-ending-reservations',
      'https://www.ndtv.com/india-news/congress-leader-arun-reddy-gets-bail-in-amit-shah-fake-video-case-5655818',
    ],
  },
  {
    id: 'hfw008',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: 'Aamir Khan AI voice-clone ad',
    kind: 'forward',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "April 2024: a video of actor Aamir Khan mocking the '₹15 lakh' promise and ending 'Vote for justice, vote for Congress' went viral. What was it?",
    options: [
      'Authentic — an unaired 2014 segment from his TV show',
      'Fake — an AI voice clone over a 2014 show promo; he filed an FIR',
      'Authentic — recorded at a 2024 Congress event in Mumbai',
      "Satire — a comedy channel's labelled parody, shared without the label",
    ],
    correctIndex: 1,
    explanation:
      "Fake. BOOM found the visuals came from a 2014 promo for his show Satyamev Jayate; IIT Jodhpur's Itisaar tool flagged the audio as an AI voice swap. Congress functionaries shared it. Khan's spokesperson said he has never endorsed a party and that an FIR was filed with Mumbai Police's Cyber Crime Cell. A similar deepfake of Ranveer Singh followed.",
    status:
      "Deepfake per BOOM (Apr 2024); FIR filed by the actor's team with Mumbai Police against unnamed persons; no outcome reported as of 2026-09",
    people: ['Aamir Khan', 'Ranveer Singh'],
    sourceUrl: 'https://www.boomlive.in/fact-check/aamir-khan-jhumla-congress-bjp-old-video-fact-check-24920',
    sourceLabel: 'BOOM — Congress Functionaries Share AI Voice Clone Of Aamir Khan Targeting PM Modi (16 Apr 2024)',
    sources: [
      'https://www.tribuneindia.com/news/entertainment/aamir-khan-lodges-fir-against-congress-for-alleged-deep-fake-video-used-in-poll-advertisement-611383',
      'https://www.thenewsminute.com/news/ranveer-singh-files-fir-over-deepfake-video-where-he-is-seen-criticising-pm-modi',
    ],
  },
  {
    id: 'hfw009',
    domain: 'civics',
    region: 'India',
    state: 'MP',
    topic: 'Welfare & Subsidies',
    subtopic: 'Kamal Nath Ladli Behna deepfake',
    kind: 'forward',
    difficulty: 'expert',
    year: 2023,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Before the Nov 2023 Madhya Pradesh polls, a clip showed Kamal Nath vowing to shut the state's Ladli Behna cash scheme if Congress won. What was it?",
    options: [
      'Genuine — from his manifesto launch in Bhopal',
      'Genuine but old — a 2018 remark about a different scheme',
      'Misheard — he actually said he would expand the scheme',
      'Fake audio laid over footage of an October 2023 speech',
    ],
    correctIndex: 3,
    explanation:
      "Fake. BOOM found the audio was overlaid on footage of his 26 Oct 2023 Chhindwara speech, livestreamed by MP Congress, in which he never mentioned the scheme. Ladli Behna, launched by the BJP state government, then paid ₹1,250 a month. MP Police registered FIRs over election deepfakes, including one on this video (The Quint).",
    status: 'Audio found fake by BOOM (Nov 2023); FIR registered by MP Police (Nov 2023); no verdict reported as of 2026-09',
    people: ['Kamal Nath'],
    sourceUrl:
      'https://www.boomlive.in/fact-check/madhya-pradesh-elections-kamal-nath-congress-to-cancel-laadli-behna-scheme-fact-check-23512',
    sourceLabel: "BOOM — Madhya Pradesh Polls: Video of Kamal Nath's Speech Viral With Fake Audio (3 Nov 2023)",
    sources: ['https://www.thequint.com/news/india/madhya-pradesh-police-registers-fir-deepfakes-pm-modi-kamal-nath'],
  },
  {
    id: 'hfw010',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Defence & Security',
    subtopic: "'Russia paused the war' for Indians",
    kind: 'forward',
    difficulty: 'expert',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "March 2022 forwards: 'Russia halted the war for six hours at Modi's request so Indian students could leave Kharkiv.' What did India's MEA say?",
    options: [
      'Confirmed — Moscow announced a six-hour ceasefire for India',
      "Denied — calling it a halt in bombing was 'absolutely inaccurate'",
      'Confirmed — both armies paused for Operation Ganga flights',
      'No comment — the MEA said such talks are confidential',
    ],
    correctIndex: 1,
    explanation:
      "Denied. The MEA spokesperson said India received inputs that a route was available and passed them to citizens, 'and I am happy that many could make it', but 'extrapolating that to say that somebody is holding off bombing or this is something we were coordinating is absolutely inaccurate' (The Quint, 3 Mar 2022).",
    status: 'Claim denied by the MEA (3 Mar 2022); no legal matter involved',
    people: ['Narendra Modi'],
    sourceUrl: 'https://www.thequint.com/news/india/mea-denies-claim-russia-stopped-war-six-hours-ukraine-kharkiv-evacuation-of-indians',
    sourceLabel: "The Quint — MEA Denies Claim Russia 'Stopped' War for 6 Hours to Evacuate Indians From Kharkiv (3 Mar 2022)",
  },
  {
    id: 'hfw011',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: "Nobel 'biggest contender' misquote",
    kind: 'forward',
    difficulty: 'expert',
    year: 2023,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "March 2023: TV tickers said Nobel committee deputy leader Asle Toje called Modi 'the biggest contender' for the Peace Prize. What happened next?",
    options: [
      'Toje confirmed it in a written statement to Indian media',
      'Toje said Modi was nominated but declined to rank him',
      "Toje called it 'fake news' and denied saying anything like it",
      'The Nobel Institute confirmed Modi was on the 2023 shortlist',
    ],
    correctIndex: 2,
    explanation:
      "False. Asked if Modi was a contender, Toje had said he hoped 'every leader in every nation is inspired to do the work' needed to win. He then told ANI a 'fake news tweet' had been sent out and denied saying anything resembling it. Alt News listed many outlets that ran the misquote; it resurfaced again in 2025.",
    status: 'Quote denied by Asle Toje (Mar 2023); rated false by Alt News and BOOM; no legal matter involved',
    people: ['Asle Toje', 'Narendra Modi'],
    sourceUrl: 'https://www.altnews.in/media-misreport-nobel-committee-member-did-not-say-modi-biggest-contender-for-peace-prize/',
    sourceLabel: 'Alt News — Media misreport: Nobel committee member did not say Modi biggest contender for Peace Prize (17 Mar 2023)',
    sources: [
      'https://www.boomlive.in/fact-check/peace-prize-asle-toje-deputy-leader-of-nobel-committee-pm-modi-biggest-contender-claim-fact-check-29474',
    ],
  },
  {
    id: 'hfw012',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: "RBI gold 'moved to Switzerland'",
    kind: 'forward',
    difficulty: 'extreme',
    year: 2019,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "May 2019: an article shared by Congress said the Modi government 'secretly' shipped 200 tonnes of RBI gold to Switzerland in 2014. What did the RBI say?",
    options: [
      'Normal practice: central banks keep some gold with others, like the Bank of England',
      'Confirmed — the gold was moved to Zurich in 2014 to back a currency swap line',
      'It denied holding any gold abroad; all its reserves sit in vaults in India',
      'It declined to comment on where reserves are held, citing national security',
    ],
    correctIndex: 0,
    explanation:
      "The Quint rated the claim false. On 3 May 2019 the RBI said it is normal practice for central banks worldwide to keep part of their gold reserves overseas with other central banks, such as the Bank of England, for safe custody — nothing about it was secret. The claim came from an election candidate and was amplified by Congress's official handle.",
    status: "Claim rated false by The Quint (May 2019) after the RBI's clarification; no legal matter involved",
    people: ['Narendra Modi'],
    sourceUrl: 'https://www.thequint.com/news/webqoof/rbi-transported-200-tonnes-of-gold-to-switzerland-is-fake-news',
    sourceLabel: "The Quint WebQoof — RBI Didn't 'Secretly' Transfer 200 Tonnes of Gold Overseas in 2014 (5 May 2019)",
  },
  {
    id: 'hfw013',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Jobs & Economy',
    subtopic: "'18% GST on cremation'",
    kind: 'forward',
    difficulty: 'extreme',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "July 2022 posts: 'The Modi government now charges 18% GST on cremation services.' What did the GST Council change actually cover?",
    options: [
      'Works contracts to build or repair crematoria, raised from 12% to 18%',
      'Cremation and funeral services themselves, raised from 12% to 18%',
      'Only services at electric crematoria run by private companies',
      'Wood and fuel sold at crematoria, raised from 5% to 18%',
    ],
    correctIndex: 0,
    explanation:
      "Misleading. The 47th GST Council raised the rate on works contracts for roads, bridges, railways, metro, crematoria and similar projects from 12% to 18%. Funeral, burial and crematorium services themselves sit outside GST under Schedule III of the CGST Act. PIB Fact Check also called the claim misleading.",
    status: 'Claim called misleading by PIB Fact Check and Newschecker (Jul 2022); no legal matter involved',
    people: ['Narendra Modi'],
    sourceUrl: 'https://newschecker.in/fact-check/gst-on-crematorium-services-misleading',
    sourceLabel: "Newschecker — Central Govt Imposed 18% GST On Crematorium Services? No, It's Untrue (22 Jul 2022)",
  },
  {
    id: 'hfw014',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: "'GST on UPI above ₹2,000'",
    kind: 'forward',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "April 2025 posts: 'The government will levy GST on UPI payments above ₹2,000.' What did the Finance Ministry say?",
    options: [
      'Confirmed — 18% GST on the transaction value from 1 July',
      'Confirmed — but only on person-to-merchant payments',
      'Deferred — the GST Council will decide at its next meeting',
      'False — no such proposal; UPI carries no MDR, so no GST applies',
    ],
    correctIndex: 3,
    explanation:
      "False. On 18 April 2025 the Finance Ministry called the claims 'completely false, misleading, and without any basis'. GST applies to charges such as the merchant discount rate, and the MDR on person-to-merchant UPI payments was removed from January 2020, so no GST arises. Alt News found finance influencers and firms among those sharing it.",
    sourceUrl: 'https://www.altnews.in/false-claim-of-gst-on-upi-payments-above-rs-2000-goes-viral/',
    sourceLabel: 'Alt News — No GST on UPI transactions above Rs 2,000; finance ministry calls social media claims baseless (23 Apr 2025)',
    sources: ['https://www.pib.gov.in/PressReleasePage.aspx?PRID=2122747'],
  },
  {
    id: 'hfw015',
    domain: 'civics',
    region: 'India',
    state: 'MH',
    topic: 'Infrastructure',
    subtopic: "Atal Setu 'cracks'",
    kind: 'forward',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "June 2024: Maharashtra Congress chief Nana Patole said Atal Setu, the sea bridge opened that January, had cracked because of corruption. What did the record show?",
    options: [
      'Cracks in the bridge deck; one lane shut for months',
      'Minor asphalt cracks on an approach-road ramp, not the bridge',
      'No cracks at all — the photos were of a bridge abroad',
      'Cracks in the pillars, found by an audit MMRDA ordered',
    ],
    correctIndex: 1,
    explanation:
      "Misleading. The cracks were on an approach road leading to the Mumbai Trans Harbour Link, not on the sea bridge. MMRDA said there was no structural defect and the cracks were minor surface cracks. The state Congress blamed corruption by the ruling coalition in the state and at the Centre (The Hindu, 21 Jun 2024).",
    status: 'Allegation by the state Congress chief (Jun 2024); MMRDA said no structural defect; no inquiry finding reported',
    people: ['Nana Patole'],
    sourceUrl:
      'https://www.thehindu.com/news/national/within-six-months-of-opening-road-to-indias-longest-sea-bridge-develops-cracks/article68317030.ece',
    sourceLabel: "The Hindu — Road to India's longest sea bridge, Atal Setu, develops cracks after 6 months (21 Jun 2024)",
    sources: ['https://www.ndtv.com/india-news/cracks-on-atal-setu-alleges-mumbai-congress-chief-bjp-hits-back-5939975'],
  },
  {
    id: 'hfw016',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: "London 'EVM hacking' event",
    kind: 'forward',
    difficulty: 'expert',
    year: 2019,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Jan 2019: at a London event, a man claiming to be an ex-ECIL engineer said EVMs were hacked in the 2014 Lok Sabha polls. What did checks find?',
    options: [
      'ECIL confirmed he worked on EVMs but disputed the hack',
      'An ECI technical panel found tampering in two states',
      'ECIL said he was never on its rolls; the ECI sought a police FIR',
      'A UK court accepted his demonstration as evidence',
    ],
    correctIndex: 2,
    explanation:
      "Unsupported. ECIL said he had 'neither been in the rolls of the ECIL as a regular employee nor… associated in the design and development of EVMs'. The Election Commission reiterated that its machines cannot be tampered with and asked Delhi Police to register an FIR against him (Scroll, 23 Jan 2019).",
    sourceUrl:
      'https://scroll.in/article/910462/fact-check-claims-of-cyber-expert-who-alleged-that-evms-can-be-hacked-do-not-withstand-scrutiny',
    sourceLabel: "Scroll — Fact check: Do claims of 'cyber expert' who alleged that EVMs can be hacked withstand scrutiny? (23 Jan 2019)",
  },
  {
    id: 'hfw017',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: "Fake 'BBC survey' — BJP win",
    kind: 'forward',
    difficulty: 'simple',
    year: 2019,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "April 2019 forward: 'BBC pre-poll survey: the BJP will win between 323 and 380 Lok Sabha seats.' What did fact-checkers find?",
    options: [
      'Fake — the BBC said it does not do pre-election surveys in India',
      'Real — but it was a BBC Hindi reader poll, not a survey',
      'Real — the BBC ran it jointly with a US pollster in March',
      'Misleading — the BBC gave 323 seats to the NDA, not the BJP',
    ],
    correctIndex: 0,
    explanation:
      "Fake. A BBC spokesperson told Alt News: 'it is fake and does not come from the BBC. The BBC does not support pre-election surveys in India.' The BBC's name had also been misused for fake polls before the 2018 Karnataka and Rajasthan elections — and a mirror-image fake in April 2019 showed Congress winning.",
    sourceUrl: 'https://www.altnews.in/fake-pre-poll-survey-by-bbc-predicts-thumping-win-for-bjp-in-lok-sabha-2019/',
    sourceLabel: 'Alt News — Fake: Pre-poll survey by BBC predicts thumping win for BJP in Lok Sabha 2019 (9 Apr 2019)',
  },
  {
    id: 'hfw018',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Elections & Funding',
    subtopic: "Fake 'BBC survey' — Congress win",
    kind: 'forward',
    difficulty: 'expert',
    year: 2019,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "April 2019 forward: 'BBC survey says the BJP will lose seats and the Congress party will win the general election.' What did Factly find?",
    options: [
      'Real — BBC Hindi published it with an Indian polling partner',
      'Real — but it covered only 12 states, not the whole country',
      "Fake — the BBC does no Indian pre-poll surveys; a pro-BJP fake ran too",
      'Unverified — the BBC declined to confirm or deny the survey',
    ],
    correctIndex: 2,
    explanation:
      "Fake. Factly noted the BBC has confirmed it does not conduct pre-election surveys in India and is 'always at the center of fake surveys during every election'. Days earlier a similar post citing the BBC had predicted a BJP win. Both sides' supporters borrowed the same trusted logo for opposite results.",
    sourceUrl: 'https://factly.in/fake-bbc-survey-predicts-congress-win/',
    sourceLabel: 'Factly — Fake BBC survey predicts Congress win (13 Apr 2019)',
  },
  {
    id: 'hfw019',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Media & Speech',
    subtopic: 'PIB Chennai floods photo',
    kind: 'forward',
    difficulty: 'extreme',
    year: 2015,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Dec 2015: PIB tweeted a photo of PM Modi viewing flooded Chennai from an aircraft window. Critics said it was doctored. What did the government later say?',
    options: [
      "It denied any editing and released the photographer's raw camera file",
      'It said a private agency had shot and edited the image without approval',
      'It blamed a hacked account and filed a complaint with Delhi Police',
      "It withdrew it as an 'error of judgement'; an RTI reply cited 'standard practice'",
    ],
    correctIndex: 3,
    explanation:
      "The image was merged. PIB deleted it and on 4 Dec 2015 called it an 'error of judgement'. Answering a journalist's RTI, the I&B ministry later said two images were merged 'as per previous standard practice' (The Quint, Apr 2018). The aerial survey itself was real; the flooded view in the window was superimposed.",
    status: 'PIB withdrew the image (Dec 2015); I&B RTI reply (2018); no legal matter involved',
    people: ['Narendra Modi'],
    sourceUrl: 'https://www.thequint.com/news/india/pib-says-photos-merged-in-photoshop-stunt',
    sourceLabel: "The Quint — PM Modi's Morphed Chennai Floods Photo a 'Standard Practice': PIB (4 Apr 2018)",
  },
  {
    id: 'hfw020',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Energy & Mining',
    subtopic: 'UPA oil bonds and fuel prices',
    kind: 'forward',
    difficulty: 'extreme',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "Viral in 2021–22: 'Petrol is costly because the Modi govt must repay UPA-era oil bonds.' Per Factly, what did FY15–FY21 bond payments total vs fuel taxes?",
    options: [
      'About ₹73,700 crore paid vs over ₹25 lakh crore in fuel taxes',
      'About ₹7.4 lakh crore paid vs about ₹9 lakh crore in fuel taxes',
      'About ₹1.3 lakh crore paid vs about ₹2 lakh crore in fuel taxes',
      'About ₹25 lakh crore paid vs about ₹73,700 crore in fuel taxes',
    ],
    correctIndex: 0,
    explanation:
      "Misleading. Using the government's reply in Parliament, Factly found the Centre paid ₹73,695.72 crore in oil-bond principal and interest in 2014-15 to 2020-21, while collecting over ₹25 lakh crore in taxes on petroleum products. The bonds were a real UPA-era liability (₹1,34,423 crore pending in 2014), but a small fraction of fuel tax revenue.",
    status: 'Claim rated misleading by Factly (Apr 2022); no legal matter involved',
    people: ['Narendra Modi'],
    sourceUrl: 'https://factly.in/the-current-increase-in-petrol-prices-has-nothing-to-do-with-the-oil-bonds-issued-during-the-congress-rule/',
    sourceLabel: "Factly — Pending dues for 'Oil Bonds' issued during the UPA are only a fraction of the Taxes collected on Petrol & Diesel (8 Apr 2022)",
  },
  {
    id: 'hfw021',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Jobs & Economy',
    subtopic: "'World's 4th-largest economy'",
    kind: 'forward',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "May 2025: NITI Aayog's CEO said 'We are the fourth-largest economy as I speak… this is IMF data.' What did the IMF figures actually show?",
    options: [
      'Confirmed — India passed Japan in calendar 2024 at $4.2 trillion',
      "A projection for FY26; India was 5th, and IMF's April 2026 data put it 6th",
      'Confirmed — India passed both Germany and Japan that year',
      'Wrong list — the IMF ranks by GDP per head, where India was 4th',
    ],
    correctIndex: 1,
    explanation:
      "Premature. Alt News showed the IMF's 2025 figure for India meant FY2025-26 and was an estimate; on actual 2024 data India was 5th, behind Japan. The IMF's April 2026 outlook then placed India 6th, below the UK, partly due to the rupee's fall, and projects it reaching 4th only in 2028 (The Wire, Apr 2026).",
    sourceUrl:
      'https://www.altnews.in/india-is-not-the-fourth-largest-or-a-4-trillion-economy-yet-niti-aayog-ceos-claim-citing-imf-data-misleading/',
    sourceLabel: "Alt News — India is not the fourth-largest or a $4-trillion economy yet; NITI Aayog CEO's claim citing IMF data misleading (27 May 2025)",
    sources: ['https://m.thewire.in/article/economy/far-from-being-the-fourth-largest-india-slips-to-number-six-on-global-gdp-rankings'],
  },
  {
    id: 'hfw022',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Jobs & Economy',
    subtopic: "'4th most equal country' claim",
    kind: 'forward',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "July 2025: PIB said a World Bank report 'ranks India fourth globally in income equality' with a Gini score of 25.5. What did Alt News find?",
    options: [
      "Accurate — the World Bank's income ranking put India 4th of 167",
      'Misleading — 25.5 is a consumption Gini; income Gini (WID) was 62 in 2023',
      'Wrong number — the World Bank score was 52, ranking India 40th',
      'Accurate — but the ranking covered only G20 countries',
    ],
    correctIndex: 1,
    explanation:
      "Misleading. The World Bank's April 2025 brief said India's consumption-based Gini improved from 28.8 (2011-12) to 25.5 (2022-23), adding inequality 'may be underestimated due to data limitations'. The same brief cited the World Inequality Database's income Gini rising from 52 (2004) to 62 (2023). Several outlets repeated PIB's framing.",
    sourceUrl: 'https://www.altnews.in/pibs-claim-that-india-is-fourth-most-equal-country-citing-world-bank-data-is-misleading/',
    sourceLabel: "Alt News — PIB's claim that India is fourth most equal country citing World Bank data is misleading (10 Jul 2025)",
  },
  {
    id: 'hfw023',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Infrastructure',
    subtopic: 'Singapore metro photo as India',
    kind: 'forward',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "May 2024: official BJP state-unit handles posted a photo of an elevated metro as proof of India's metro growth under BJP rule. What did BOOM find?",
    options: [
      "It was Delhi Metro's Magenta Line, photographed in 2023",
      'It was an AI render of a planned metro line in Pune',
      "It was Bengaluru's Yellow Line, shot before its launch",
      "It was Singapore's Jurong East MRT, from a Singapore government site",
    ],
    correctIndex: 3,
    explanation:
      "Misattributed. BOOM traced the photo, posted by the BJP's West Bengal and Tripura X handles, to a Singapore government page promoting the city's transport; the Straits Times had used matching visuals identified as Jurong East MRT. The picture shows Singapore, not an Indian project.",
    sourceUrl: 'https://www.boomlive.in/fact-check/viral-photo-bjp-metro-railway-development-india-claim-social-media-25331',
    sourceLabel: 'BOOM — BJP Shares Photo From Singapore As Development Of Indian Metro Services (19 May 2024)',
  },
  {
    id: 'hfw024',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Defence & Security',
    subtopic: "'Karachi port destroyed' reports",
    kind: 'forward',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Night of 8–9 May 2025: several Indian TV channels announced that the Indian Navy had struck and wrecked Karachi port. What did Alt News find?',
    options: [
      'The Navy confirmed it next morning and released satellite images',
      "No such strike was confirmed; 'Karachi' visuals were old, unrelated clips",
      'True — but it was an Air Force strike, not a Navy operation',
      "True — Pakistan's government later confirmed damage to two berths",
    ],
    correctIndex: 1,
    explanation:
      "Unfounded. Alt News documented channels declaring the port 'in shambles' with no official confirmation; one image used was from a 2020 airstrike in another conflict. Some outlets later swapped images without issuing a correction. BOOM logged similar misreporting by Indian outlets during the India-Pakistan conflict.",
    sourceUrl: 'https://www.altnews.in/the-fictional-strikes-on-the-karachi-port-and-what-it-says-about-indian-media/',
    sourceLabel: 'Alt News — The fictional strikes on the Karachi port and what it says about Indian media (17 May 2025)',
    sources: ['https://www.boomlive.in/fact-check/indian-media-misreporting-operation-sindoor-pakistan-pahalgam-kashmir-jammu-army-28517'],
  },
  {
    id: 'hfw025',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: "Fake 'BBC' corrupt-parties list",
    kind: 'forward',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "A graphic credited to the BBC, viral since 2017 and revived in 2025, lists Congress as the world's fourth most corrupt political party. What is it?",
    options: [
      'Real — from a 2017 BBC World Service global survey',
      'Real — the BBC was citing a Transparency International index',
      "Fake — it traces to 'BBC News Point', a site not linked to the BBC",
      'Real — but the BBC ranked Congress 14th, not 4th',
    ],
    correctIndex: 2,
    explanation:
      "Fake. The Quint's WebQoof, which also debunked it in 2017 and 2018, traced the graphic to a website called 'BBC News Point', unconnected to the BBC; the BBC never published such a list. Its mirror image — a fake 'CNN survey' naming the BJP fourth most corrupt — went viral in January 2026.",
    sourceUrl: 'https://www.thequint.com/news/webqoof/bbc-graphic-congress-top-10-most-corrupt-parties-fake-fact-check',
    sourceLabel: 'The Quint WebQoof — Did BBC Find Congress To Be One of the Most Corrupt Parties in the World? No! (3 Oct 2025)',
  },
  {
    id: 'hfw026',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: "Fake 'CNN' corrupt-parties survey",
    kind: 'forward',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "Jan 2026: a news clip claiming 'a CNN survey ranks the BJP as the world's fourth most corrupt political party' went viral. What did Factly find?",
    options: [
      'Real — CNN aired it citing a Transparency International study',
      'Real — but CNN ranked the BJP 14th, not 4th',
      'Unverified — CNN neither confirmed nor denied the survey',
      'Fake — CNN did no such survey; the clip was digitally edited',
    ],
    correctIndex: 3,
    explanation:
      "Fake. Factly found CNN had conducted no survey on corrupt political parties and the viral clip was digitally edited and fabricated. It reuses an older template — a fake 'BBC' graphic that listed Congress fourth — showing how the same hoax gets pointed at whichever party is the target.",
    sourceUrl: 'https://factly.in/cnn-did-not-conduct-any-survey-ranking-the-bjp-as-the-fourth-most-corrupt-political-party-in-the-world/',
    sourceLabel: 'Factly — CNN did not conduct any survey ranking the BJP as the fourth most corrupt political party in the world (5 Jan 2026)',
  },
  {
    id: 'hfw027',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Health',
    subtopic: "'Red zone is green zone' clip",
    kind: 'forward',
    difficulty: 'expert',
    year: 2020,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "May 2020: BJP spokesperson Sambit Patra shared a 6-second clip of Rahul Gandhi saying 'the red zone is actually the green zone'. What had been cut?",
    options: [
      'Nothing — Gandhi repeated the line twice in the full clip',
      "'National level' — he said centrally marked zones may not match the ground",
      'That he was reading out a WHO statement on Covid zones',
      'That he was talking about traffic signals in his constituency',
    ],
    correctIndex: 1,
    explanation:
      "Clipped. In his full remarks Gandhi said zones decided at the national level might not match conditions on the ground, and argued district magistrates and chief ministers should help draw them. Alt News found 'national level' was cropped out to make the line sound absurd; the clip drew over 5 lakh views.",
    status: 'Clip rated false by Alt News (May 2020); no legal matter involved',
    people: ['Sambit Patra', 'Rahul Gandhi'],
    sourceUrl: 'https://www.altnews.in/red-is-green-green-is-red-sambit-patra-shares-clipped-video-to-mock-rahul-gandhi/',
    sourceLabel: "Alt News — 'Red is green, green is red'? Sambit Patra shares clipped video to mock Rahul Gandhi (11 May 2020)",
  },
  {
    id: 'hfw028',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Health',
    subtopic: 'Mohalla clinic garbage photo',
    kind: 'forward',
    difficulty: 'expert',
    year: 2022,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      "May 2022: BJP MPs shared a photo of an 'Aam Aadmi Mohalla Clinic' board above a garbage heap as the reality of Delhi's clinics. What did Alt News find?",
    options: [
      'The board was a roadside sign; the clinic itself runs nearby',
      'The photo was an AI image made by a meme page',
      'The clinic had shut in 2021 and the site became a dump',
      'The photo was from Punjab, where AAP had just won',
    ],
    correctIndex: 0,
    explanation:
      "Misleading. Alt News found the board in Niti Vihar, Kirari was put up on the main road for people's convenience, pointing to the clinic, which is located close by; the garbage heap was not the clinic. Delhi was then governed by AAP, and the photo was shared by opposition BJP leaders.",
    sourceUrl: 'https://www.altnews.in/bjp-leaders-shared-a-photo-of-garbage-dump-with-mohalla-clinic-hordings-targetting-aap-false-claim/',
    sourceLabel: 'Alt News — Fact-check: Piles of garbage in front of a mohalla clinic in Delhi? (12 May 2022)',
  },
  {
    id: 'hfw029',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: "Red Fort 'sold' to Dalmia",
    kind: 'forward',
    difficulty: 'expert',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "April 2018 outrage: 'The Modi government has sold the Red Fort to the Dalmia group.' What did the MoU under the Adopt a Heritage scheme cover?",
    options: [
      'A 25-year lease giving the company the right to set entry fees',
      "Outright sale of the fort's non-core land to the group for ₹25 crore",
      'Five years of tourist amenities on CSR funds; no handover of the monument',
      'Transfer of all conservation duties from the ASI to the company',
    ],
    correctIndex: 2,
    explanation:
      "Misleading. Dalmia Bharat signed an MoU with the tourism ministry to spend ₹25 crore over five years on amenities around the fort as a 'Monument Mitra'. The ministry said it involved 'no handing over of monument', no profit-making and ASI oversight. Congress, TMC, CPI(M) and some historians still objected (TOI; ThePrint published the MoU).",
    status: 'MoU under the Adopt a Heritage scheme (Apr 2018); tourism ministry denied any handover; no court finding',
    people: ['Narendra Modi'],
    sourceUrl: 'https://timesofindia.indiatimes.com/city/delhi/no-profit-making-or-touching-of-monument-govt/articleshow/63957340.cms',
    sourceLabel: "Times of India — Opposition sees 'red' over alleged 'auction' of Red Fort, government says charges false (29 Apr 2018)",
    sources: ['https://theprint.in/politics/fact-check-heres-the-red-fort-dalmia-agreement-that-everyone-is-talking-about/54522/'],
  },
  {
    id: 'hfw030',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Health',
    subtopic: "'Bhajans cure malnutrition' claim",
    kind: 'forward',
    difficulty: 'expert',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'Aug 2022: posts said PM Modi, in Mann Ki Baat, suggested that singing bhajans could solve malnutrition. What did BOOM find?',
    options: [
      'True — he urged states to replace take-home rations with kirtan sessions',
      'Misleading — he cited MP events pairing bhajans with nutrition drives and meals',
      'False — that Mann Ki Baat episode never mentioned malnutrition at all',
      'True — but the remark was about mental health, not child nutrition',
    ],
    correctIndex: 1,
    explanation:
      "Misleading. In the 28 Aug 2022 episode Modi described bhajan-kirtan gatherings in Madhya Pradesh that were combined with malnutrition awareness and 'balbhoj' meals for children. BOOM found no statement that singing itself would solve malnutrition; many posts drew on an opinion piece critical of the framing.",
    status: 'Claim rated misleading by BOOM (Sep 2022); no legal matter involved',
    people: ['Narendra Modi'],
    sourceUrl: 'https://www.boomlive.in/fact-check/modi-bhajan-malnutrition-mann-ki-baat-wire-19100',
    sourceLabel: 'BOOM — No, Modi Did Not Say Bhajans Can Solve Malnutrition (1 Sep 2022)',
  },
  {
    id: 'hfw031',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Farm & Food',
    subtopic: 'Old protest photos as farm strike',
    kind: 'forward',
    difficulty: 'extreme',
    year: 2020,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "Dec 2020 posts said 250 million Indians struck work in support of the farmers' protest, with four huge-crowd photos. What did BOOM find about the photos?",
    options: [
      'They were from the Delhi border protest camps, taken in November 2020',
      'They were AI-generated images made for a social-media campaign',
      'They were from Punjab tractor rallies against the farm laws, Sept 2020',
      'They were from earlier Left and trade-union protests of 2018 and Jan 2020',
    ],
    correctIndex: 3,
    explanation:
      "Out of context. BOOM's reverse image searches traced all four pictures to earlier protests organised by Left parties and trade unions in 2018 and January 2020, including an AP photo shot on 8 Jan 2020 — none were from the 2020 farmers' agitation against the farm laws.",
    sourceUrl: 'https://www.boomlive.in/fake-news/images-from-old-cpi-protests-viral-as-ongoing-farmers-agitation-11162',
    sourceLabel: "BOOM — Images From Old CPI Protests Viral As Ongoing Farmers' Agitation (16 Dec 2020)",
  },
  {
    id: 'hfw032',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: "Adani '₹120 lakh crore loans' chart",
    kind: 'forward',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "Nov 2024 infographic: 'Adani Group owes ₹39.2 lakh crore to SBI and ₹120 lakh crore in all to Indian banks.' What did India Today Fact Check find?",
    options: [
      "Accurate — the figures came from SBI's own annual report",
      'Overstated — the true total was ₹12 lakh crore, a decimal slip',
      "The figures were the banks' total lending, not their Adani exposure",
      'Accurate for SBI, but the ₹120 lakh crore total was doubled',
    ],
    correctIndex: 2,
    explanation:
      "False. The numbers were each lender's entire loan book as of September 2024; the Adani Group's borrowings from these banks are a fraction of that. India Today traced the confusion to a Moneycontrol chart titled 'Lenders exposure to Adani Group companies' that was misread and shared widely.",
    sourceUrl:
      'https://www.indiatoday.in/fact-check/story/fact-check-adani-group-rs-120-lakh-crore-loan-indian-banks-data-goof-up-infographic-2637875-2024-11-22',
    sourceLabel: "India Today — Fact Check: Adani Group DIDN'T get Rs 120 lakh crore loan from Indian banks (22 Nov 2024)",
  },
  {
    id: 'hfw033',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Welfare & Subsidies',
    subtopic: "'Free recharge for third term' scam",
    kind: 'forward',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "June 2024 forwards: 'To celebrate Modi's third term, BJP is giving every Indian a free 3-month mobile recharge — click to claim.' What was it?",
    options: [
      'A fake offer; the links led to dubious websites, per Factly',
      'A real party offer, limited to the first 10 lakh users',
      'A real offer by telecom companies, credited to the party',
      'A real TRAI scheme, wrongly credited to the party',
    ],
    correctIndex: 0,
    explanation:
      "Fake. Factly found neither the BJP nor the PM was offering any free recharge; the links led to dubious websites, and cybercriminals use such messages to steal data. Near-identical 'free recharge' bait has also misused company names. Rule of thumb: a real scheme never asks you to forward a link to claim it.",
    status: 'Scam message rated fake by Factly (Jun 2024); no official scheme existed',
    people: ['Narendra Modi'],
    sourceUrl: 'https://factly.in/neither-bjp-nor-pm-modi-is-offering-any-free-recharge-on-the-occasion-of-forming-the-government-for-the-third-term/',
    sourceLabel: 'Factly — Neither BJP nor PM Modi is offering any free recharge on the occasion of forming the government for the third term (7 Jun 2024)',
    sources: ['https://factly.in/reliance-jio-is-not-offering-any-free-recharge-on-the-occasion-of-mukesh-ambanis-birthday-and-anant-ambanis-wedding/'],
  },
  {
    id: 'hfw034',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Education & Exams',
    subtopic: "'Free laptops for students' link",
    kind: 'forward',
    difficulty: 'simple',
    year: 2020,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'A 2020 forward said the government was giving students free laptops during Covid school closures: register via the link, then share it with 10 people. What was it?',
    options: [
      'A real Education Ministry scheme run through CBSE',
      'A real scheme, but only for Class 12 toppers',
      'A real state scheme, wrongly credited to the Centre',
      'Fraud — the link led to a blog harvesting personal details',
    ],
    correctIndex: 3,
    explanation:
      "Fraudulent. Factly found the link opened a blogspot page asking for personal details and 10 shares to 'complete registration' — something no government scheme does. PIB Fact Check had flagged similar fake laptop, smartphone and scholarship links earlier in 2020, and variants keep resurfacing.",
    sourceUrl: 'https://factly.in/beware-of-bogus-websites-offering-free-laptops-smartphones-and-scholarships-in-the-name-of-government/',
    sourceLabel: 'Factly — Beware of bogus websites offering free laptops, smartphones, and scholarships in the name of Government (24 Sep 2020)',
  },
  {
    id: 'hfw035',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'FM investment-platform deepfake',
    kind: 'forward',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "2026 video: a TV anchor reports that FM Nirmala Sitharaman launched a platform turning ₹21,000 into ₹5.5 lakh within a week. What did Factly find?",
    options: [
      'Real — a SEBI-approved pilot for retail investors',
      'Real — but the returns were per year, not per week',
      'Deepfake — built from footage of her Nov 2025 SBI conclave speech',
      'Satire — from a comedy show, clearly labelled as parody',
    ],
    correctIndex: 2,
    explanation:
      "Deepfake. Factly traced the visuals to her address at the 12th SBI Banking & Economics Conclave in Mumbai (footage posted in November 2025), where no such scheme was announced; lip-sync mismatches pointed to manipulation. 'Minister endorses investment app' videos are a common fraud template.",
    status: 'Deepfake per Factly (Feb 2026); the minister is the target of the fake, not accused of anything',
    people: ['Nirmala Sitharaman'],
    sourceUrl: 'https://factly.in/this-viral-video-of-nirmala-sitharaman-endorsing-a-hyper-profitable-investment-project-is-a-deepfake/',
    sourceLabel: 'Factly — This viral video of Nirmala Sitharaman, endorsing a hyper-profitable investment project, is a deepfake (13 Feb 2026)',
  },
  {
    id: 'hfw036',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Swiss bank funds of Indians',
    kind: 'forward',
    difficulty: 'extreme',
    year: 2021,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "June 2021 headlines: 'Indians' money in Swiss banks jumps to ₹20,700 crore, a 13-year high.' What did the Finance Ministry say the Swiss data showed?",
    options: [
      'Figure right, but customer deposits fell; the rise was bonds and securities',
      'Figure wrong — the Swiss data showed a fall to ₹6,625 crore',
      'Figure right, and it confirmed ₹20,700 crore of black money',
      'Figure right, but it mostly counted accounts of foreign nationals',
    ],
    correctIndex: 0,
    explanation:
      "True, with context. The ministry accepted the SNB figure (CHF 2.55 billion, up from CHF 899 million) but said it does 'not indicate the quantum' of alleged black money: customer deposits actually fell, fiduciary funds more than halved, and the jump came from bonds, securities and other instruments (PIB, 19 Jun 2021).",
    sourceUrl: 'https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=1728429',
    sourceLabel: 'PIB (Ministry of Finance) — Finance Ministry refutes news media reports of alleged black money held by Indians in Switzerland (19 Jun 2021)',
  },
  {
    id: 'hfw037',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Infrastructure',
    subtopic: 'New Parliament rain leak',
    kind: 'forward',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      'July 31, 2024: videos showed rainwater dripping into a bucket inside the new Parliament building. What did the Lok Sabha Secretariat say?',
    options: [
      'Fake — the video was shot in the old Parliament House',
      'True — the roof needs replacing, with repairs of ₹120 crore',
      'Fake — the water came from a burst pipe in a canteen',
      'True — adhesive on the lobby glass domes shifted in heavy rain; fixed',
    ],
    correctIndex: 3,
    explanation:
      "True, with context. The Secretariat said the adhesive fixing the glass domes over the lobby — installed to let in natural light — was slightly displaced in heavy rain, causing a 'minor leakage' that was detected in time and fixed. Opposition MPs, who shared the video, questioned the building's durability (Hindustan Times, 1 Aug 2024).",
    sourceUrl:
      'https://www.hindustantimes.com/india-news/why-was-water-leaking-in-the-new-parliament-building-lok-sabha-secretariat-explains-101722509671410.html',
    sourceLabel: 'Hindustan Times — Why was water leaking in the new Parliament building? Lok Sabha Secretariat explains (1 Aug 2024)',
    sources: ['https://scroll.in/latest/1071492/congress-moves-adjournment-motion-in-lok-sabha-over-water-leakage-in-parliament-amid-heavy-rain'],
  },
  {
    id: 'hfw038',
    domain: 'civics',
    region: 'India',
    state: 'HP',
    topic: 'Jobs & Economy',
    subtopic: 'Himachal salary-date shift',
    kind: 'forward',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Sept 2024 posts: 'Himachal's Congress government can't pay salaries on time.' What did CM Sukhvinder Singh Sukhu tell the Assembly?",
    options: [
      'False — salaries were paid on the 1st as always',
      'True — salaries were withheld for three months',
      'True — pay would now come on the 5th and pensions on the 10th',
      'True — only contract staff were paid late, by a week',
    ],
    correctIndex: 2,
    explanation:
      "True, with context. Sukhu said pay would come on the 5th and pensions on the 10th because the ₹520 crore revenue-deficit grant arrives on the 6th and the ₹740 crore tax share on the 10th; paying on the 1st meant borrowing at about 7.5%. He was replying to the BJP Leader of Opposition, who raised the delays (The Hindu, 4 Sep 2024).",
    status: "CM's statement in the Assembly (Sep 2024); no wrongdoing alleged",
    people: ['Sukhvinder Singh Sukhu'],
    sourceUrl:
      'https://www.thehindu.com/news/national/himachal-pradesh/himachal-govt-to-pay-employee-salaries-on-5th-pension-on-10th-per-month-for-fiscal-prudence/article68605272.ece',
    sourceLabel: "The Hindu — Himachal govt. to pay employee salaries on 5th, pension on 10th per month for 'fiscal prudence' (4 Sep 2024)",
  },
  {
    id: 'hfw039',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: "'World's most popular leader' tracker",
    kind: 'forward',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "March 2026 headlines: 'Modi is the world's most popular leader with 68% approval — Morning Consult.' What is the fair verdict?",
    options: [
      'False — Morning Consult had him 9th, behind European leaders',
      "True per the firm's tracker — but it's a non-random online panel survey",
      "True — it is the UN's official global leader index",
      'False — the survey covered only Indian diaspora voters',
    ],
    correctIndex: 1,
    explanation:
      "True, with context. Morning Consult's Global Leader Approval tracker did put Modi top at 68% (Akashvani, Mar 2026). The Wire notes it is a US firm's proprietary tracker using non-probability online panels weighted to demographics, so it reflects India's online population, and cross-country league tables built from it are shaky.",
    status: "Approval figure from a private firm's tracker (Mar 2026); no legal matter involved",
    people: ['Narendra Modi'],
    sourceUrl: 'https://m.thewire.in/article/politics/whats-wrong-with-modi-is-the-worlds-most-popular-leader-survey-claim',
    sourceLabel: "The Wire — What's Wrong With 'Modi is the World's Most Popular Leader' Survey Claim? (26 Mar 2026)",
    sources: ['https://newsonair.gov.in/pm-modi-tops-global-popularity-rankings-with-68-approval-says-morning-consult-survey/'],
  },
  {
    id: 'hfw040',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Infrastructure',
    subtopic: 'Six airports to one bidder',
    kind: 'forward',
    difficulty: 'extreme',
    year: 2023,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "Claim in the Lok Sabha, Feb 2023, then viral: 'Rules were bent so Adani got six airports.' What had the government's own appraisal notes said?",
    options: [
      'A Finance Ministry note urged not more than two airports per bidder',
      'Nothing — the six airports actually went to six different bidders',
      'NITI Aayog had recommended that one bidder take all six airports',
      'The CAG had audited and cleared the bids in advance, in 2018',
    ],
    correctIndex: 0,
    explanation:
      "True, with context. The DEA's appraisal note suggested 'not more than two airports will be awarded to the same bidder' and NITI Aayog raised capacity concerns; the PPP panel overruled them and Adani Enterprises won all six (Ahmedabad, Lucknow, Mangaluru, Jaipur, Guwahati, Thiruvananthapuram) for 50 years. The government says the bidding was transparent.",
    status: 'Allegation made in the Lok Sabha (Feb 2023); government says the process was transparent (Dec 2024); no wrongdoing established',
    people: ['Rahul Gandhi', 'Narendra Modi'],
    sourceUrl:
      'https://scroll.in/article/1043531/explained-why-rahul-gandhi-accused-modi-government-of-bending-rules-to-hand-over-airports-to-adani',
    sourceLabel: 'Scroll — Explainer: Why Rahul Gandhi accused Modi government of bending rules to hand over airports to Adani (9 Feb 2023)',
    sources: ['https://www.deccanherald.com/india/six-airports-leased-out-to-adani-group-through-transparent-process-says-naidu-3304836'],
  },
]);
