// HISAAB DO — Before the vote: the States (ids hpe100–hpe199).
// Transfers, sops, budgets, bills and promises in the months before Assembly (and two civic) polls,
// 2000–2026, across every party that governed — and each official result. Every item is tagged
// 'pre-election' (plus 'distribution' or 'relief' where money or goods were handed out) and carries
// `poll` { label, month, gapDays?, result }. gapDays = days from the announcement / first payment to the
// first polling day, given only where both dates are on the record. Results are the official tallies as
// reported by the cited outlets (ECI pages where still online; Wikipedia only as a second source).
// Timing is fact; motive is opinion — words like 'poll sop' or 'election ploy' appear only in quotes
// attributed to whoever said them. Research notes: docs/hisaab/research/poll-states-notes.md.
// Every item was checked against its fetched source in September 2026 (asOf '2026-09').

const W = (t) => `https://en.wikipedia.org/wiki/${t}`;

export const HISAAB_POLL_STATES = Object.freeze([
  // ───────────────────────── 2000–2004 ─────────────────────────
  {
    id: 'hpe100',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Energy & Mining',
    subtopic: 'Power-dues waiver promise (2000)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2002,
    asOf: '2026-09',
    govt: 'Other',
    question:
      "Om Prakash Chautala's INLD won Haryana in February 2000 after promising to waive farmers' pending electricity dues. What did his government offer instead in April 2002?",
    options: [
      'A full waiver, paid out over five years',
      "A waiver of 75% of each farmer's dues",
      'A waiver only for dues older than 1995',
      'A year of free power but no waiver',
    ],
    correctIndex: 1,
    explanation:
      "Frontline reported that in the run-up to the 2000 poll Chautala promised to waive all pending power dues. In April 2002 he said the state would waive 75% of each farmer's dues and farmers must pay the rest. The Bharatiya Kisan Union resumed its agitation, and power connections of defaulting small farmers were cut.",
    sourceUrl: 'https://frontline.thehindu.com/other/article30245094.ece',
    sourceLabel: 'Frontline — Farmer power (8 Jun 2002)',
    sources: [W('2000_Haryana_Legislative_Assembly_election')],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Om Prakash Chautala', role: 'Chief Minister, Haryana', party: 'INLD' }],
    outcome:
      'The farmers\' protests over power dues spread across Jind and nearby districts; police firings on 19 and 29 May 2002 left three people dead, Frontline reported.',
    poll: { label: 'Haryana Assembly 2000', month: '2000-02', result: 'INLD won 47 of 90 seats; Congress 21' },
  },
  {
    id: 'hpe101',
    domain: 'civics',
    region: 'India',
    state: 'AP',
    topic: 'Welfare & Subsidies',
    subtopic: "YSR's pension promise (2004)",
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2004,
    asOf: '2026-09',
    govt: 'TDP',
    question:
      "Campaigning against Chandrababu Naidu's TDP before the 2004 poll, Y.S. Rajasekhara Reddy promised to raise pensions for widows, the aged and the disabled from ₹75 a month to what?",
    options: ['₹150 a month', '₹300 a month', '₹500 a month', '₹200 a month'],
    correctIndex: 3,
    explanation:
      "India Today listed YSR's promises: restore free power to farmers, lift the pensions from ₹75 to ₹200 a month and build eight lakh houses a year. Naidu had dissolved the Assembly in November 2003, a year early, and had raised farm power tariffs; TDP leaders blamed the rout on anti-incumbency after nine years.",
    sourceUrl:
      'https://www.indiatoday.in/magazine/cover-story/story/20040524-andhra-pradeshs-new-chief-minister-congress-leader-rajasekhara-reddy-replaces-n-chandrababu-naidu-789947-2004-05-23',
    sourceLabel: 'India Today — Mega byte victory (24 May 2004)',
    sources: ['https://www.rediff.com/news/report/tdp/20040527.htm'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Y.S. Rajasekhara Reddy', role: 'Leader of the Opposition, Andhra Pradesh', party: 'INC' }],
    outcome:
      "The Congress won 185 of 294 seats (226 with the TRS and the Left); the TDP's 47 was its lowest ever. Naidu later admitted opting for early polls was a mistake (Rediff).",
    poll: { label: 'Andhra Pradesh Assembly 2004', month: '2004-04', result: 'Congress won 185 of 294 (alliance 226); TDP 47' },
  },
  {
    id: 'hpe102',
    domain: 'civics',
    region: 'India',
    state: 'KA',
    topic: 'Farm & Food',
    subtopic: 'Farm-distress compensation (2004)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2004,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Before Karnataka's 2004 poll, S.M. Krishna's government offered ₹1 lakh to families of indebted farmers who had died by suicide. What share of needy families got it, per Frontline?",
    options: ['Nearly all of them', 'About half', 'Barely 10%', 'About a quarter'],
    correctIndex: 2,
    explanation:
      "Frontline wrote that the eligibility criteria were so unrealistic that barely 10% of needy families were paid, after officials first disputed the toll (650 in ten months, per a March 2004 release). Krishna blamed his defeat on holding the poll with the Lok Sabha's and on drought in four of five years; Frontline called the pre-poll sops 'too little, too late'.",
    sourceUrl: 'https://frontline.thehindu.com/cover-story/article30223009.ece',
    sourceLabel: 'Frontline — The rural anger in Karnataka (18 Jun 2004)',
    sources: [W('2004_Karnataka_Legislative_Assembly_election')],
    tags: ['pre-election', 'relief'],
    enactedBy: [{ name: 'S.M. Krishna', role: 'Chief Minister, Karnataka', party: 'INC' }],
    outcome:
      'A hung Assembly: the BJP won 79 of 224 seats, the Congress 65 and the JD(S) 58. Krishna said drought had always been a cause for people to vote against a government.',
    poll: { label: 'Karnataka Assembly 2004', month: '2004-04', result: 'Hung: BJP 79, Congress 65, JD(S) 58 of 224' },
  },

  {
    id: 'hpe150',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Jobs & Economy',
    subtopic: 'Drought-relief wages (2003)',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2003,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Months before Rajasthan's December 2003 poll, Ashok Gehlot said the daily wage his government paid on drought-relief works was the highest in the country. How much was it?",
    options: ['₹30', '₹45', '₹100', '₹60'],
    correctIndex: 3,
    explanation:
      "Frontline (May 2003): a fifth straight drought had hit 40,990 villages in all 32 districts and 4.48 crore people. Gehlot said the BJP could not make drought an election issue because the state was doing all it could. Frontline also heard that in one Bikaner tehsil most workers were paid between ₹15 and ₹60, and a goshala employee said the ₹60 was not paid in full.",
    sourceUrl: 'https://frontline.thehindu.com/the-nation/article30216871.ece',
    sourceLabel: 'Frontline — From bad to worse in Rajasthan (9 May 2003)',
    sources: ['https://www.rediff.com/news/report/rajasthan-raje-dethroned-in-rajasthan/20081209.htm'],
    tags: ['pre-election', 'relief'],
    enactedBy: [{ name: 'Ashok Gehlot', role: 'Chief Minister, Rajasthan', party: 'INC' }],
    outcome:
      'In the December 2003 poll the BJP under Vasundhara Raje won 120 of 200 seats and the Congress lost power (Rediff).',
    poll: { label: 'Rajasthan Assembly 2003', month: '2003-12', result: 'BJP won 120 of 200; Congress lost power' },
  },

  // ───────────────────────── 2005–2009 ─────────────────────────
  {
    id: 'hpe103',
    domain: 'civics',
    region: 'India',
    state: 'TN',
    topic: 'Welfare & Subsidies',
    subtopic: 'Free colour TV promise: the cost row (2006)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2006,
    asOf: '2026-09',
    govt: 'AIADMK',
    question:
      "Defending the DMK's manifesto before Tamil Nadu's May 2006 poll, Karunanidhi said free colour TVs would need ₹530 crore a year for two years. What cost had Jayalalithaa claimed?",
    options: ['₹15,000 crore', '₹1,500 crore', '₹5,300 crore', '₹50,000 crore'],
    correctIndex: 0,
    explanation:
      "Frontline: the 29 March manifesto offered ₹2-a-kg rice, colour TVs 'to provide recreation and general knowledge to women', gas stoves and ₹1,000 a month for six months to pregnant women. At a 5 April rally Karunanidhi said the TV money could come from stopping liquor-label fraud; Jayalalithaa called it promising the moon, and her ally Vaiko called the rice offer 'fraudulent'.",
    sourceUrl: 'https://frontline.thehindu.com/politics/article30209101.ece',
    sourceLabel: 'Frontline — Promising start (21 Apr 2006)',
    sources: ['https://frontline.thehindu.com/cover-story/article30209583.ece'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'M. Karunanidhi', role: 'DMK president (manifesto)', party: 'DMK' }],
    outcome:
      'The DMK-led front won 163 of 234 seats (DMK 96) and Karunanidhi formed a minority government; on 17 May he said TV distribution would begin on 15 September, Annadurai\'s birth anniversary.',
    poll: { label: 'Tamil Nadu Assembly 2006', month: '2006-05', gapDays: 40, result: 'DMK-led front won 163 of 234 (DMK 96); AIADMK front 69' },
  },
  {
    id: 'hpe104',
    domain: 'civics',
    region: 'India',
    state: 'TN',
    topic: 'Farm & Food',
    subtopic: 'Co-operative loan waiver (2006)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2006,
    asOf: '2026-09',
    govt: 'DMK',
    question:
      "Sworn in on 13 May 2006, Karunanidhi at once signed a file waiving farmers' co-operative loans, as the DMK manifesto had promised. What did he say it would cost the exchequer?",
    options: ['₹686 crore', '₹3,433 crore', '₹12,110 crore', '₹6,866 crore'],
    correctIndex: 3,
    explanation:
      "Frontline: of three files signed on stage, the first gave 20 kg of rice a month at ₹2 a kg from 3 June, the second waived co-operative loans taken up to 31 March 2006 at a cost of ₹6,866 crore, and the third doubled eggs in the noon meal to two a week. P. Chidambaram had called the manifesto the 'hero' of the election.",
    sourceUrl: 'https://frontline.thehindu.com/cover-story/article30209583.ece',
    sourceLabel: 'Frontline — Promises to keep (2 Jun 2006)',
    sources: [W('2006_Tamil_Nadu_Legislative_Assembly_election')],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'M. Karunanidhi', role: 'Chief Minister, Tamil Nadu', party: 'DMK' }],
    outcome:
      'The DMK-led alliance won 163 of 234 seats; the DMK alone won 96, short of a majority, and governed with outside support from the Congress, PMK and the Left.',
    poll: { label: 'Tamil Nadu Assembly 2006', month: '2006-05', result: 'DMK-led front won 163 of 234 (DMK 96); AIADMK front 69' },
  },
  {
    id: 'hpe105',
    domain: 'civics',
    region: 'India',
    state: 'CT',
    topic: 'Farm & Food',
    subtopic: 'Cheap rice and salt (2008)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2008,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "After starting ₹3-a-kg rice for BPL families about ten months before campaigning for the 2008 poll, Raman Singh's BJP government added what to the scheme?",
    options: ['Salt at 25 paise a kg', 'Wheat at ₹2 a kg', 'Kerosene at ₹5 a litre', 'Sugar at ₹10 a kg'],
    correctIndex: 0,
    explanation:
      "Frontline (Dec 2008) described 'this exercise of offering sops' as starting with ₹3 rice for BPL families, followed soon after by salt at 25 paise a kg, and 'a scramble followed to obtain cards' marking families eligible. By 2013 Frontline found even his adversaries crediting the cheap-rice scheme as a success.",
    sourceUrl: 'https://frontline.thehindu.com/politics/article30198426.ece',
    sourceLabel: 'Frontline — Ticket troubles (5 Dec 2008)',
    sources: [
      'https://frontline.thehindu.com/politics/food-and-vote/article5338647.ece',
      'https://scroll.in/article/901189/scroll-explainer-everything-you-need-to-know-about-chhattisgarh-assembly-elections',
      W('2008_Chhattisgarh_Legislative_Assembly_election'),
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Raman Singh', role: 'Chief Minister, Chhattisgarh', party: 'BJP' }],
    outcome: 'The BJP kept power in November 2008 with 50 of 90 seats to the Congress\'s 38, and won a third term in 2013.',
    poll: { label: 'Chhattisgarh Assembly 2008', month: '2008-11', result: 'BJP retained power with 50 of 90 seats; Congress 38' },
  },
  {
    id: 'hpe106',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Welfare & Subsidies',
    subtopic: 'Bhamashah, first version (2008)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2008,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "In 2008, her poll year, Vasundhara Raje's first Bhamashah scheme opened bank accounts for women heads of families. About how much had reached 10 lakh of those accounts?",
    options: ['About ₹16 crore', 'About ₹160 crore', 'About ₹600 crore', 'About ₹1,600 crore'],
    correctIndex: 1,
    explanation:
      "The Hindu (2014) recorded that in 2008 the biometrics of 44 lakh families were collected, 26 lakh accounts opened with Punjab National Bank and about ₹160 crore transferred to 10 lakh of them. The next Congress government discontinued the scheme; Raje relaunched it on 15 August 2014 aiming at 1.5 crore women, with ₹600 crore set aside.",
    sourceUrl: 'https://www.thehindu.com/news/national/other-states/vasundhara-to-relaunch-scheme-to-empower-women/article6319335.ece',
    sourceLabel: 'The Hindu — Vasundhara to re-launch scheme to empower women (15 Aug 2014)',
    sources: ['https://www.rediff.com/news/report/rajasthan-raje-dethroned-in-rajasthan/20081209.htm'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Vasundhara Raje', role: 'Chief Minister, Rajasthan', party: 'BJP' }],
    outcome:
      'The Congress won 96 of 200 seats in December 2008 to the BJP\'s 78, down from 120 in 2003 (Rediff), and dropped the scheme; it returned under Raje in 2014.',
    poll: { label: 'Rajasthan Assembly 2008', month: '2008-12', result: 'Congress won 96 of 200; BJP 78' },
  },
  {
    id: 'hpe151',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Welfare & Subsidies',
    subtopic: 'Ladli scheme launch (2008)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2008,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Sheila Dikshit's government launched the Ladli scheme for girls in 2008, the year Delhi next voted. Up to what lump sum did it promise a girl on turning 18?",
    options: ['₹25,000', '₹50,000', '₹2 lakh', '₹1 lakh'],
    correctIndex: 3,
    explanation:
      "The New Indian Express: Ladli paid instalments at stages of a girl's schooling plus a lump sum of up to ₹1 lakh at 18. A CAG audit reported in 2025 found 16,546 duplicate registrations, and about 9% of beneficiaries enrolled after turning 18, the maturity age, costing ₹180.92 crore.",
    otherSide:
      "When the Congress cited the audit in January 2025, an AAP spokesperson called its charges baseless and 'BJP-manufactured lies'.",
    sourceUrl: 'https://www.newindianexpress.com/cities/delhi/2025/Feb/27/ladli-scheme-audit-finds-rs-61838-crore-unclaimed-reveals-massive-irregularities',
    sourceLabel: "The New Indian Express — 'Duplicate registrations': CAG exposes Rs 220 crore irregularities in Ladli scheme (27 Feb 2025)",
    sources: [
      "https://www.tribuneindia.com/news/delhi/cong-accuses-aap-of-stalling-funds-under-ladli-yojana",
      'https://timesofindia.indiatimes.com/education/news/delhi-replaces-ladli-scheme-with-lakhpati-bitiya-yojana-promises-1-lakh-support-for-girls-education/articleshow/128196828.cms',
      W('2008_Delhi_Legislative_Assembly_election'),
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Sheila Dikshit', role: 'Chief Minister, Delhi', party: 'INC' }],
    outcome:
      'The Congress won a third straight term in November 2008 with 43 of 70 seats to the BJP\'s 23. In February 2026 CM Rekha Gupta announced Lakhpati Bitiya Yojana to replace Ladli from April (TOI).',
    poll: { label: 'Delhi Assembly 2008', month: '2008-11', result: 'Congress won 43 of 70; BJP 23' },
  },
  {
    id: 'hpe107',
    domain: 'civics',
    region: 'India',
    state: 'AP',
    topic: 'Welfare & Subsidies',
    subtopic: "TDP's Cash Transfer Scheme promise (2009)",
    kind: 'scheme',
    difficulty: 'simple',
    year: 2009,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "The TDP's April 2009 manifesto promised a 'Cash Transfer Scheme' for Andhra Pradesh's poor families. What minimum monthly transfer did Chandrababu Naidu pledge?",
    options: ['₹2,000', '₹500', '₹1,000', '₹5,000'],
    correctIndex: 0,
    explanation:
      "The New Indian Express: the 64-page manifesto also offered a free colour TV to every 'common man'. Naidu called it 'revolutionary', not populist, said controlling corruption would free the money, and claimed TV sales had dropped as people waited for his sets.",
    sourceUrl: 'https://www.newindianexpress.com/states/andhra-pradesh/2009/Apr/03/tdp-launches-manifesto-38060.html',
    sourceLabel: 'The New Indian Express — TDP launches manifesto (3 Apr 2009)',
    sources: ['https://frontline.thehindu.com/politics/article30187377.ece'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'N. Chandrababu Naidu', role: 'TDP president, Leader of the Opposition', party: 'TDP' }],
    outcome:
      "The promise was never tested: the Congress kept power with 156 of 294 seats in the April 2009 poll, and Chiranjeevi's new Praja Rajyam won 18 (Frontline).",
    poll: { label: 'Andhra Pradesh Assembly 2009', month: '2009-04', result: 'Congress retained power with 156 of 294; Praja Rajyam 18' },
  },

  // ───────────────────────── 2010–2014 ─────────────────────────
  {
    id: 'hpe108',
    domain: 'civics',
    region: 'India',
    state: 'TN',
    topic: 'Elections & Funding',
    subtopic: 'Free TVs halted by the model code (2011)',
    kind: 'institution',
    difficulty: 'simple',
    year: 2011,
    asOf: '2026-09',
    govt: 'DMK',
    question:
      "A day after the ECI announced Tamil Nadu's 2011 poll schedule, the state's Chief Electoral Officer ordered collectors to stop which ruling-DMK handout at once?",
    options: [
      'Free colour television sets',
      'Rice at ₹1 a kg in ration shops',
      'Old-age pension payments',
      'Free bus passes for students',
    ],
    correctIndex: 0,
    explanation:
      "The Hindu: CEO Praveen Kumar ordered distribution stopped 'till the elections process is over' and warned of severe action against officials. The government had recently ordered 10 lakh more sets and tokens had already been issued. Ministers were also told not to announce financial grants or promise roads and drinking water.",
    otherSide:
      "No reply from the DMK government to the order was reported as of Sep 2026; the order paused the handout only until the election process was over.",
    sourceUrl: 'https://www.thehindu.com/news/national/tamil-nadu/EC-orders-stoppage-of-free-colour-TV-distribution-in-TN/article14944523.ece',
    sourceLabel: 'The Hindu — EC orders stoppage of free colour TV distribution in TN (2 Mar 2011)',
    sources: ['https://www.thehindu.com/news/Jayalalithaa-rides-wave-decimates-DMK-led-front/article13606860.ece', W('2011_Tamil_Nadu_Legislative_Assembly_election')],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'M. Karunanidhi', role: 'Chief Minister, Tamil Nadu (scheme)', party: 'DMK' }],
    outcome:
      "The AIADMK won 150 seats on its own and its front 203 of 234; the DMK fell to 23, and Jayalalithaa returned as chief minister.",
    poll: { label: 'Tamil Nadu Assembly 2011', month: '2011-04', gapDays: 42, result: 'AIADMK won 150 of 234 (front 203); DMK 23' },
  },
  {
    id: 'hpe109',
    domain: 'civics',
    region: 'India',
    state: 'KL',
    topic: 'Farm & Food',
    subtopic: '₹2 rice for APL card holders (2011)',
    kind: 'institution',
    difficulty: 'simple',
    year: 2011,
    asOf: '2026-09',
    govt: 'LDF',
    question:
      "Kerala's LDF government extended ₹2-a-kg rice to above-poverty-line card holders in 2011. In April, its food minister said the rice would reach shops 'in a day or two'. What had held it up?",
    options: [
      'A delay in printing new APL cards',
      "The Election Commission's ban during the poll",
      'The Centre refusing extra rice',
      "A ration dealers' strike",
    ],
    correctIndex: 1,
    explanation:
      "Speaking on 19 April, six days after polling, Food Minister C. Divakaran said the scheme was resuming after the Election Commission lifted its ban; APL cards would get 6–10 kg at ₹2 a kg, and ₹250 crore was in the Budget. He rejected Opposition Leader Oommen Chandy's charge that there was no allocation, saying the UDF had once run ₹3 rice without any budget provision.",
    otherSide:
      "Food Minister C. Divakaran rejected Oommen Chandy's charge, saying ₹250 crore was in the Budget and the only delay followed the Election Commission's ban.",
    sourceUrl: 'https://www.thehindu.com/news/national/kerala/Rice-at-Rs.-2-a-kg-in-a-day-or-two/article14689272.ece',
    sourceLabel: 'The Hindu — Rice at Rs. 2 a kg in a day or two (19 Apr 2011)',
    sources: ['https://www.indiatoday.in/assembly-elections-2011/kerala/story/kerala-assembly-elections-udf-wins-in-72-seats-against-ldfs-68-133693-2011-05-12'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'C. Divakaran', role: 'Food and Civil Supplies Minister, Kerala', party: 'CPI' }],
    outcome:
      'The UDF won 72 of 140 seats to the LDF\'s 68, a two-seat majority in the closest Kerala contest in three decades, India Today reported.',
    poll: { label: 'Kerala Assembly 2011', month: '2011-04', result: 'UDF won 72 of 140; LDF 68' },
  },
  {
    id: 'hpe110',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Jobs & Economy',
    subtopic: 'Unemployment allowance, day one (2012)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2012,
    asOf: '2026-09',
    govt: 'SP',
    question:
      "At its first cabinet meeting in March 2012, Akhilesh Yadav's government approved an SP poll promise: ₹1,000 a month for registered jobseekers above what age?",
    options: ['21', '25', '35', '30'],
    correctIndex: 2,
    explanation:
      "The Hindu: the dole was for registered unemployed people over 35 with at least a high-school pass; the Chief Secretary put them at about 9 lakh and the cost at ₹1,100 crore a year. The same meeting cleared free tablets and laptops for Class 10 and 12 passouts, estimated at about ₹3,000 crore.",
    sourceUrl: 'https://www.thehindu.com/news/national/slew-of-populist-measures-by-akhilesh-on-day-1/article2998039.ece',
    sourceLabel: 'The Hindu — Slew of populist measures by Akhilesh on Day 1 (15 Mar 2012)',
    sources: ['https://www.indiatoday.in/assembly-elections-2012/uttar-pradesh/story/election-results-uttar-pradesh-sp-mulayam-akhilesh-95236-2012-03-06'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Akhilesh Yadav', role: 'Chief Minister, Uttar Pradesh', party: 'SP' }],
    outcome:
      'The SP had won 224 of 403 seats, ending five years of BSP rule under Mayawati, who had won 206 seats in 2007.',
    poll: { label: 'UP Assembly 2012', month: '2012-02', result: 'SP won 224 of 403; BSP had won 206 in 2007' },
  },
  {
    id: 'hpe111',
    domain: 'civics',
    region: 'India',
    state: 'CT',
    topic: 'Farm & Food',
    subtopic: 'Chhattisgarh Food Security Act (2012)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2012,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Chhattisgarh's BJP government passed its own food security law on 22 December 2012, ahead of the Centre's. About how many families was it meant to cover?",
    options: ['About 5 lakh', 'About 20 lakh', 'About 1.5 crore', 'About 50 lakh'],
    correctIndex: 3,
    explanation:
      "Mint: the law gave a legal food guarantee to almost 90% of the state's people, about 5 million families, at a cost of over ₹2,311 crore. Backers of the UPA's pending national bill admired it but dismissed it as an election ploy before the 2013 polls; the state BJP said the law made food a right. Analyst Jai Mrug called passing it before the polls 'smart'.",
    sourceUrl: 'https://www.livemint.com/Politics/bS3giFXXxO7vUaLtUmJLBK/Chhattisgarh-food-security-Bill-puts-UPA-under-pressure.html',
    sourceLabel: 'Mint — Chhattisgarh food security Bill puts UPA under pressure (26 Dec 2012)',
    sources: ['https://scroll.in/article/901189/scroll-explainer-everything-you-need-to-know-about-chhattisgarh-assembly-elections'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Raman Singh', role: 'Chief Minister, Chhattisgarh', party: 'BJP' }],
    outcome:
      'In the November 2013 poll the BJP won a third straight term with 49 of 90 seats; the Congress took 39, per Scroll.',
    poll: { label: 'Chhattisgarh Assembly 2013', month: '2013-11', gapDays: 324, result: 'BJP won 49 of 90; Congress 39' },
  },
  {
    id: 'hpe112',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Welfare & Subsidies',
    subtopic: 'Dilli Annashree Yojana (2012)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2012,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Launching Dilli Annashree in December 2012, a year before the Delhi poll, Sheila Dikshit said its monthly cash transfer could buy 'dal, roti and chawal' for a family of five. How much?",
    options: ['₹600', '₹300', '₹1,000', '₹1,500'],
    correctIndex: 0,
    explanation:
      "India Today: Sonia Gandhi launched the scheme, which paid ₹600 a month into the Aadhaar-linked account of the senior-most woman in about 2 lakh poor families not covered by other schemes, backdated to April 2012. BJP leader Mukhtar Abbas Naqvi said it insulted the poor, as ₹600 would not buy a single meal.",
    sourceUrl: 'https://www.indiatoday.in/india/north/story/sheila-dikshit-rs-600-per-month-dal-roti-chawal-family-of-five-india-today-124449-2012-12-15',
    sourceLabel: 'India Today — Rs 600 per month enough to support a family of five, says Sheila Dikshit (16 Dec 2012)',
    sources: [W('2013_Delhi_Legislative_Assembly_election')],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Sheila Dikshit', role: 'Chief Minister, Delhi', party: 'INC' }],
    outcome:
      "In the December 2013 poll the Congress fell to 8 of 70 seats; the BJP won 31 and the first-time AAP 28.",
    poll: { label: 'Delhi Assembly 2013', month: '2013-12', gapDays: 354, result: 'BJP 31, AAP 28, Congress 8 of 70' },
  },
  {
    id: 'hpe113',
    domain: 'civics',
    region: 'India',
    state: 'TN',
    topic: 'Welfare & Subsidies',
    subtopic: 'Fans, mixies and grinders in the Supreme Court (2013)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2011,
    asOf: '2026-09',
    govt: 'AIADMK',
    question:
      "Defending its free fans, mixies and grinders in the Supreme Court's 2013 freebies case, Tamil Nadu said how many women would get them in phases after the AIADMK's 2011 win?",
    options: ['About 18 lakh', 'About 80 lakh', 'About 1.83 crore', 'About 3.5 crore'],
    correctIndex: 2,
    explanation:
      "The judgment records the state's submission: a 3 June 2011 order for 25 lakh packages of fans, mixies and grinders in 2011-12, with about 1.83 crore women to be covered in phases. The court held that manifesto promises are not a corrupt practice under the election law, but asked the ECI to frame manifesto guidelines with recognised parties.",
    sourceUrl: 'https://indiankanoon.org/doc/106854428/',
    sourceLabel: 'Supreme Court of India — S. Subramaniam Balaji v. Govt of T. Nadu (5 Jul 2013), via Indian Kanoon',
    sources: ['https://www.thehindu.com/news/national/sc-agrees-to-re-examine-verdict-limiting-corrupt-practice-to-candidate-and-not-party-under-election-law/article65805670.ece'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'J. Jayalalithaa', role: 'Chief Minister, Tamil Nadu', party: 'AIADMK' }],
    outcome:
      'The AIADMK had promised the appliances before the April 2011 poll. In August 2022 the Supreme Court said a three-judge bench would reconsider the 2013 ruling that such promises are not a corrupt practice (The Hindu).',
    poll: { label: 'Tamil Nadu Assembly 2011', month: '2011-04', result: 'AIADMK won 150 of 234 (front 203); DMK 23' },
  },
  {
    id: 'hpe114',
    domain: 'civics',
    region: 'India',
    state: 'CT',
    topic: 'Farm & Food',
    subtopic: 'Paddy price promise (2013)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2013,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Campaigning in Chhattisgarh in 2013, the Congress promised farmers what price for paddy, per quintal, when the minimum support price was ₹1,310?",
    options: ['₹1,500', '₹2,500', '₹3,100', '₹2,000'],
    correctIndex: 3,
    explanation:
      "Frontline: the Congress also promised 35 kg of free rice to every card holder and free power to farmers; a BJP election manager dismissed the offers as 'hogwash'. Frontline found even Raman Singh's adversaries crediting his ₹2-a-kg rice. Ten years later the BJP's own manifesto made a paddy-price promise too.",
    sourceUrl: 'https://frontline.thehindu.com/politics/food-and-vote/article5338647.ece',
    sourceLabel: 'Frontline — Food and vote (13 Nov 2013)',
    sources: [
      'https://scroll.in/article/901189/scroll-explainer-everything-you-need-to-know-about-chhattisgarh-assembly-elections',
      'https://www.thehindu.com/elections/chhattisgarh-assembly/chhattisgarh-polls-bjp-promises-sops-for-married-women-landless-farm-labourers-lpg-cylinder-at-500/article67493270.ece',
    ],
    tags: ['pre-election', 'distribution'],
    outcome:
      'The BJP won a third straight term with 49 of 90 seats; the Congress won 39, a vote-share gap of 0.7 percentage points, per Scroll.',
    poll: { label: 'Chhattisgarh Assembly 2013', month: '2013-11', result: 'BJP won 49 of 90; Congress 39' },
  },
  {
    id: 'hpe115',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Welfare & Subsidies',
    subtopic: "AAP's first water promise (2013)",
    kind: 'scheme',
    difficulty: 'expert',
    year: 2013,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "The Aam Aadmi Party's first manifesto, for Delhi's December 2013 poll, promised each household free water up to what limit?",
    options: ['70 litres a day', '200 litres a day', '700 litres a day', '1,000 litres a day'],
    correctIndex: 2,
    explanation:
      "Down To Earth: the AAP also promised to halve power bills through audits of the distribution companies, which it said were inflating bills. Households using more than 700 litres a day would pay for the entire quantity. Some analysts warned free water could encourage wastage and burden the government.",
    sourceUrl: 'https://www.downtoearth.org.in/environment/aam-aadmi-party-manifesto-promises-free-water-electricity-42868',
    sourceLabel: 'Down To Earth — Aam Aadmi Party manifesto promises free water, electricity (29 Nov 2013)',
    sources: [W('2013_Delhi_Legislative_Assembly_election')],
    tags: ['pre-election', 'distribution'],
    outcome:
      'The AAP won 28 of 70 seats on its debut; the BJP won 31 and the Congress, which had governed Delhi, only 8.',
    poll: { label: 'Delhi Assembly 2013', month: '2013-12', result: 'BJP 31, AAP 28, Congress 8 of 70' },
  },
  {
    id: 'hpe116',
    domain: 'civics',
    region: 'India',
    state: 'AP',
    topic: 'Farm & Food',
    subtopic: 'Loan waiver ceiling (2014)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2014,
    asOf: '2026-09',
    govt: 'TDP',
    question:
      "Loan waiver was the TDP's big 2014 promise. In July 2014 Naidu's cabinet fixed a per-family ceiling above the ₹1 lakh an expert panel had advised. What was it?",
    options: ['₹50,000', '₹1.5 lakh', '₹2 lakh', '₹3 lakh'],
    correctIndex: 1,
    explanation:
      "Down To Earth: the 21 July decision covered about ₹43,000 crore of farm, gold, self-help-group and weaver loans. The Kotaiah panel's ₹1 lakh cap would have fully covered 87% of borrowers; ₹1.5 lakh covered 96.27% of over 80 lakh, at an extra ₹8,000 crore, despite a ₹16,000 crore deficit and an RBI 'not favourably disposed'.",
    sourceUrl: 'https://www.downtoearth.org.in/environment/andhra-pradesh-announces-rs-43000-crore-loan-waiver-45418',
    sourceLabel: 'Down To Earth — Andhra Pradesh announces Rs 43,000 crore loan waiver (22 Jul 2014)',
    sources: [
      'https://www.deccanchronicle.com/140517/nation-politics/article/election-2014-results-kcr-creates-history-telangana-naidu-makes',
      'https://www.thehindu.com/news/national/andhra-pradesh/5000-cr-allocated-for-annadata-sukhibhava/article26187674.ece',
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'N. Chandrababu Naidu', role: 'Chief Minister, Andhra Pradesh', party: 'TDP' }],
    outcome:
      "By February 2019 the finance minister said ₹24,000 crore of farm loans had been waived, with the last two instalments still to be credited. The TDP had won 102 of 175 seats in 2014.",
    poll: { label: 'Andhra Pradesh Assembly 2014', month: '2014-05', result: 'TDP won 102 of 175 (106 with BJP); YSRCP 67; Congress 0' },
  },
  {
    id: 'hpe117',
    domain: 'civics',
    region: 'India',
    state: 'TG',
    topic: 'Farm & Food',
    subtopic: 'Loan waiver cut-off (2014)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2014,
    asOf: '2026-09',
    govt: 'BRS',
    question:
      "Weeks after his TRS won Telangana's first election in 2014, having promised a ₹1 lakh farm-loan waiver, K. Chandrasekhar Rao told bankers the waiver would cover crop loans from when?",
    options: ['2009-10 to 2013-14', 'Only the 2013-14 season', 'All loans taken before 2014', 'Only the 2014-15 season'],
    correctIndex: 1,
    explanation:
      "Down To Earth: at a 4 June meeting the government said only 2013-14 crop loans up to ₹1 lakh would be waived — ₹14,897 crore, pared to ₹7,840 crore by leaving out gold, post-harvest, sugarcane and tobacco loans. Farmers protested in Adilabad, Nizamabad and Medak; the finance minister said no final decision had been taken.",
    sourceUrl: 'https://www.downtoearth.org.in/environment/farmers-in-telangana-protest-cap-on-farm-loan-waiver-44651',
    sourceLabel: 'Down To Earth — Farmers in Telangana protest cap on farm loan waiver (6 Jun 2014)',
    sources: [
      'https://www.deccanchronicle.com/140517/nation-politics/article/election-2014-results-kcr-creates-history-telangana-naidu-makes',
      'https://www.thenewsminute.com/telangana/did-trs-welfare-schemes-help-kcr-storm-back-power-telangana-93274',
      'https://www.thenewsminute.com/telangana/trs-manifesto-will-develop-hyd-global-city-unemployment-allowance-rs-3016-92615',
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'K. Chandrasekhar Rao', role: 'Chief Minister, Telangana', party: 'TRS (now BRS)' }],
    outcome:
      'The TRS had won 63 of 119 seats in 2014. By its 2018 re-election the waiver had cost about ₹17,000 crore (The News Minute), and its 2018 manifesto promised another waiver of up to ₹1 lakh.',
    poll: { label: 'Telangana Assembly 2014', month: '2014-04', result: 'TRS won 63 of 119; Congress 21; TDP 15' },
  },

  // ───────────────────────── 2015–2019 ─────────────────────────
  {
    id: 'hpe118',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Infrastructure',
    subtopic: 'Special package for Bihar (2015)',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2015,
    asOf: '2026-09',
    govt: 'NDA',
    question:
      "Announcing a special package for poll-bound Bihar at Arrah on 18 August 2015, PM Modi also launched road, bridge and skill projects worth how much?",
    options: ['₹970 crore', '₹4,500 crore', '₹9,700 crore', '₹25,000 crore'],
    correctIndex: 2,
    explanation:
      "India Today: the package was ₹1.25 lakh crore, or ₹1.65 lakh crore counting ₹40,000 crore of earlier unspent funds, and the projects launched that day were worth ₹9,700 crore. Nitish Kumar's government called it a 'repackaging of old schemes'; Finance Minister Arun Jaitley said it should ask the Congress, Nitish's new ally, why those projects were not implemented.",
    sourceUrl:
      'https://www.indiatoday.in/assembly-elections-2015/bihar-polls/photo/bihar-celebrates-as-pm-modi-declares-special-package-worth-rs-125-lakh-crore-375906-2015-08-18',
    sourceLabel: "India Today — Bihar celebrates Modi's special package worth Rs 1.25 lakh crore (18 Aug 2015)",
    sources: [
      'https://indianexpress.com/article/political-pulse/the-era-of-special-status-is-over-jaitley-shoots-down-nitishs-persistent-demand/',
      'https://indianexpress.com/article/india/india-news-india/bihar-election-results-live-nda-grand-alliance/',
    ],
    tags: ['pre-election'],
    enactedBy: [{ name: 'Narendra Modi', role: 'Prime Minister', party: 'BJP' }],
    outcome:
      'The JD(U)–RJD–Congress alliance won 178 of 243 seats (RJD 80, JD(U) 71) in October–November 2015, and Nitish Kumar stayed chief minister.',
    poll: { label: 'Bihar Assembly 2015', month: '2015-10', gapDays: 55, result: 'JD(U)–RJD–Congress won 178 of 243; RJD 80, JD(U) 71' },
  },
  {
    id: 'hpe119',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Farm & Food',
    subtopic: 'Khadya Sathi (2016)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2016,
    asOf: '2026-09',
    govt: 'TMC',
    question:
      "Mamata Banerjee launched Khadya Sathi on 27 January 2016, about ten weeks before Bengal began voting. At what price did it offer rice and wheat to over 7 crore people?",
    options: ['₹1 a kg', '₹2 a kg', '₹5 a kg', 'Free of cost'],
    correctIndex: 1,
    explanation:
      "The Indian Express: the scheme covered almost 80% of the state's people with 5 kg of grain a month, and TMC leaders believed it would prove vital in the coming election. Mamata said 15 lakh tonnes of rice had been procured and accused the CPI(M) of being 'blind to the state's development'.",
    sourceUrl: 'https://indianexpress.com/article/cities/kolkata/mamatas-masterstroke-ahead-of-polls-foodgrain-at-rs-2kg-for-80-of-bengal-population/',
    sourceLabel: "The Indian Express — Mamata's masterstroke ahead of polls: foodgrain at Rs 2/kg for 80% of Bengal population (28 Jan 2016)",
    sources: ['https://www.bbc.com/news/world-asia-india-36319405', W('2016_West_Bengal_Legislative_Assembly_election')],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Mamata Banerjee', role: 'Chief Minister, West Bengal', party: 'TMC' }],
    outcome: 'The TMC won a second term with 211 of 294 seats in the April–May 2016 poll, the BBC reported.',
    poll: { label: 'West Bengal Assembly 2016', month: '2016-04', gapDays: 68, result: 'TMC won 211 of 294' },
  },
  {
    id: 'hpe120',
    domain: 'civics',
    region: 'India',
    state: 'TN',
    topic: 'Energy & Mining',
    subtopic: '100 free power units (2016)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2016,
    asOf: '2026-09',
    govt: 'AIADMK',
    question:
      "On taking oath in May 2016, Jayalalithaa signed a poll-promise file giving every household 100 units of free electricity. What did Business Standard put its cost at?",
    options: ['About ₹160 crore', 'About ₹1,607 crore', 'About ₹5,780 crore', 'About ₹16,070 crore'],
    correctIndex: 1,
    explanation:
      "Business Standard: her five first-day files waived small and medium farmers' co-operative loans (about ₹5,780 crore), gave 100 free units to domestic users, raised wedding gold for eligible brides from 4 g to 8 g, raised free power for weavers and closed 500 state liquor shops — all AIADMK manifesto promises.",
    sourceUrl: 'https://www.business-standard.com/article/politics/jayalalithaa-keeps-five-poll-promises-on-day-1-116052300523_1.html',
    sourceLabel: 'Business Standard — Jayalalithaa keeps five poll promises on Day 1 (24 May 2016)',
    sources: ['https://www.thehindu.com/news/national/tamil-nadu/tn-cm-announces-12110-crore-crop-loan-waiver/article33759653.ece'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'J. Jayalalithaa', role: 'Chief Minister, Tamil Nadu', party: 'AIADMK' }],
    outcome:
      'The AIADMK had won 134 of the 232 seats polled, a rare second straight term. In 2021 Palaniswami said the 2016 loan waiver came to ₹5,318.73 crore for 12.02 lakh farmers.',
    poll: { label: 'Tamil Nadu Assembly 2016', month: '2016-05', result: 'AIADMK won 134 of 232 seats polled; second straight term' },
  },
  {
    id: 'hpe121',
    domain: 'civics',
    region: 'India',
    state: 'KA',
    topic: 'Farm & Food',
    subtopic: 'Indira Canteens (2017)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2017,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Siddaramaiah's Congress government opened Bengaluru's first Indira Canteens with Rahul Gandhi in August 2017, nine months before the poll. What did lunch or dinner cost there?",
    options: ['₹5', '₹1', '₹20', '₹10'],
    correctIndex: 3,
    explanation:
      "The Indian Express: breakfast was ₹5; 101 of the planned 198 ward canteens opened on 16 August, modelled on Tamil Nadu's Amma canteens. The paper wrote that the Congress used the launch to kick off its Assembly campaign; Siddaramaiah said the BJP opposed the canteens because it was 'opposed to the poor'.",
    sourceUrl: 'https://indianexpress.com/article/india/karnataka-gets-indira-canteens-breakfast-for-rs-5-lunch-for-rs-10-4800143/',
    sourceLabel: 'The Indian Express — Karnataka gets Indira Canteens: Breakfast for Rs 5, lunch for Rs 10 (17 Aug 2017)',
    sources: ['https://www.indiatoday.in/elections/karnataka-election-2018/story/final-karnataka-election-results-2018-bjp-wins-104-congress-wins-78-jd-s-wins-37-1234135-2018-05-15'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Siddaramaiah', role: 'Chief Minister, Karnataka', party: 'INC' }],
    outcome:
      'The May 2018 poll gave a hung Assembly — BJP 104, Congress 78, JD(S) 37 — and the Congress offered to back a JD(S)-led government under H.D. Kumaraswamy (India Today).',
    poll: { label: 'Karnataka Assembly 2018', month: '2018-05', gapDays: 269, result: 'Hung: BJP 104, Congress 78, JD(S) 37 of 224' },
  },
  {
    id: 'hpe122',
    domain: 'civics',
    region: 'India',
    state: 'GJ',
    topic: 'Elections & Funding',
    subtopic: 'Poll dates and flood relief (2017)',
    kind: 'institution',
    difficulty: 'expert',
    year: 2017,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "When the ECI announced Himachal's poll dates but not Gujarat's on 12 October 2017, what did Chief Election Commissioner A.K. Joti cite besides avoiding a long model code?",
    options: [
      'A pending Supreme Court case on EVMs',
      'Security needs along the border',
      "A Gujarat request citing flood-relief work",
      'Clashes with the festival season',
    ],
    correctIndex: 2,
    explanation:
      "The Indian Express: Gujarat's Chief Secretary had written that the model code would disrupt flood relief. Former CEC S.Y. Quraishi said the break from simultaneous announcements 'raises some serious questions', and the Congress alleged the BJP had pushed for the delay; Joti said voting would still end before Himachal's count.",
    otherSide:
      "CEC A.K. Joti said the decision avoided an unreasonably long model code in Gujarat, and that its voting would wind up before Himachal's results were declared.",
    sourceUrl:
      'https://indianexpress.com/article/india/election-commission-himachal-pradesh-elections-17-gujarat-elections-date-schedule-congress-bjp-virbhadra-singh-vijay-rupani-4887853/',
    sourceLabel: 'The Indian Express — Election Omission: EC announces poll dates for Himachal Pradesh but not for Gujarat (13 Oct 2017)',
    sources: [W('2017_Gujarat_Legislative_Assembly_election')],
    tags: ['pre-election', 'relief'],
    outcome: 'Gujarat voted on 9 and 14 December 2017; the BJP won 99 of 182 seats and the Congress 77.',
    poll: { label: 'Gujarat Assembly 2017', month: '2017-12', gapDays: 58, result: 'BJP won 99 of 182; Congress 77' },
  },
  {
    id: 'hpe123',
    domain: 'civics',
    region: 'India',
    state: 'CT',
    topic: 'Welfare & Subsidies',
    subtopic: 'Sanchar Kranti smartphones (2018)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2018,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "At an event with President Kovind in July 2018, Chhattisgarh handed out the first phones under its Sanchar Kranti Yojana. How many smartphones did Raman Singh's government plan to give?",
    options: ['About 50 lakh', 'About 5 lakh', 'About 10 lakh', 'About 1.5 crore'],
    correctIndex: 0,
    explanation:
      "The Indian Express: the ₹1,467.90 crore scheme targeted 40 lakh rural women, 5 lakh poor urban women and 5 lakh college students, with Micromax handsets bought at about ₹2,510 and ₹4,143. On Opposition doubts about a Jio tie-up, officials said the phones were dual-SIM and any SIM could be used.",
    sourceUrl: 'https://indianexpress.com/article/india/dual-sim-smartphones-for-50-lakh-chhattisgarh-beneficiaries-under-sanchar-kranti-yojana-5280052/',
    sourceLabel: 'The Indian Express — Chhattisgarh: 50 lakh people to get smartphones under Sanchar Kranti Yojana (27 Jul 2018)',
    sources: [
      'https://www.hindustantimes.com/india-news/raman-singh-s-smartphone-scheme-stopped-by-new-chhattisgarh-cm/story-Fx0zTv6JlqTQcYU5vfm45H.html',
      W('2018_Chhattisgarh_Legislative_Assembly_election'),
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Raman Singh', role: 'Chief Minister, Chhattisgarh', party: 'BJP' }],
    outcome:
      "The Congress won 68 of 90 seats. On 19 Dec 2018 the new Baghel government postponed distribution, with about 20 lakh phones still undelivered, citing tender questions (HT); the BJP said the Congress did not want progress.",
    poll: { label: 'Chhattisgarh Assembly 2018', month: '2018-11', gapDays: 109, result: 'Congress won 68 of 90; BJP 15' },
  },
  {
    id: 'hpe124',
    domain: 'civics',
    region: 'India',
    state: 'TG',
    topic: 'Welfare & Subsidies',
    subtopic: 'TRS manifesto: Aasara pensions (2018)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2018,
    asOf: '2026-09',
    govt: 'BRS',
    question:
      "Five days before Telangana voted in December 2018, the TRS manifesto promised to raise Aasara pensions for the elderly and widows from ₹1,000 a month to what?",
    options: ['₹1,500', '₹2,500', '₹3,016', '₹2,016'],
    correctIndex: 3,
    explanation:
      "The News Minute: caretaker CM K. Chandrasekhar Rao's manifesto also raised pensions for disabled people from ₹1,500 to ₹3,016, cut the old-age pension age from 65 to 57, promised a ₹3,016 unemployment allowance, lifted Rythu Bandhu from ₹8,000 to ₹10,000 an acre a year and pledged a crop-loan waiver up to ₹1 lakh.",
    sourceUrl: 'https://www.thenewsminute.com/telangana/trs-manifesto-will-develop-hyd-global-city-unemployment-allowance-rs-3016-92615',
    sourceLabel: 'The News Minute — TRS manifesto: unemployment allowance of Rs 3,016 (2 Dec 2018)',
    sources: ['https://www.thenewsminute.com/telangana/did-trs-welfare-schemes-help-kcr-storm-back-power-telangana-93274', W('2018_Telangana_Legislative_Assembly_election')],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'K. Chandrasekhar Rao', role: 'Caretaker Chief Minister, Telangana', party: 'TRS (now BRS)' }],
    outcome:
      'The TRS, which had called the poll early, won 88 of 119 seats with nearly 47% of the vote. The Congress and BJP had offered a ₹2 lakh loan waiver.',
    poll: { label: 'Telangana Assembly 2018', month: '2018-12', gapDays: 5, result: 'TRS won 88 of 119; Congress 19' },
  },
  {
    id: 'hpe125',
    domain: 'civics',
    region: 'India',
    state: 'MP',
    topic: 'Energy & Mining',
    subtopic: 'Sambal flat power bill (2018)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2018,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Approved by his cabinet in June 2018, about six months before the poll, Shivraj Singh Chouhan's Sambal scheme capped power bills for unorganised workers and BPL families at how much a month?",
    options: ['₹100', '₹200', '₹500', 'Nothing — power was free'],
    correctIndex: 1,
    explanation:
      "ET EnergyWorld: the cabinet approved the flat ₹200 bill on 5 June for homes drawing under 1,000 watts, alongside a waiver of such families' power dues as of 1 June. Officials expected 88 lakh families to benefit; 38.9 lakh registered in the first ten days.",
    otherSide:
      "No reply from the Madhya Pradesh government to the CAG finding was reported as of Sep 2026.",
    sourceUrl: 'https://energy.economictimes.indiatimes.com/news/power/mp-power-schemes-over-38-lakh-people-register-in-10-days/64946133',
    sourceLabel: 'ET EnergyWorld — Madhya Pradesh power schemes: Over 38 lakh people register in 10 days (11 Jul 2018)',
    sources: [
      'https://m.thewire.in/article/government/madhya-pradesh-rs-416-33-cr-from-construction-workers-welfare-fund-diverted-to-populist-schemes-cag-report',
      'https://www.thehindu.com/elections/madhya-pradesh-assembly-elections-2018/madhya-pradesh-assembly-election-results-congress-wins-114-seats/article62017163.ece',
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Shivraj Singh Chouhan', role: 'Chief Minister, Madhya Pradesh', party: 'BJP' }],
    outcome:
      "The Congress won 114 of 230 seats to the BJP's 109. A CAG audit reported in April 2025 found the state's construction-workers' welfare board paid ₹416.33 crore in 2021 to offset subsidy under the 2018 dues waiver and a 2020 scheme.",
    poll: { label: 'Madhya Pradesh Assembly 2018', month: '2018-11', gapDays: 176, result: 'Congress won 114 of 230; BJP 109' },
  },
  {
    id: 'hpe126',
    domain: 'civics',
    region: 'India',
    state: 'MP',
    topic: 'Farm & Food',
    subtopic: 'Loan waiver on oath day (2018)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2018,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "The Congress had promised Madhya Pradesh farmers a loan waiver within ten days of taking power. Hours after his oath on 17 December 2018, what limit did Kamal Nath's order set?",
    options: ['Crop loans up to ₹50,000', 'Crop loans up to ₹1 lakh', 'Crop loans up to ₹2 lakh', 'All farm loans, with no limit'],
    correctIndex: 2,
    explanation:
      "The Hindu: the order wrote off eligible farmers' short-term crop loans up to ₹2 lakh outstanding on 31 March 2018 with nationalised and co-operative banks. The waiver had been a campaign promise to be met within 10 days of forming the government.",
    sourceUrl: 'https://www.thehindu.com/news/national/mp-cm-kamal-nath-waives-off-farm-loans-up-to-2-lakh/article62015750.ece',
    sourceLabel: 'The Hindu — Madhya Pradesh CM Kamal Nath waives off farm loans up to ₹2 lakh (17 Dec 2018)',
    sources: ['https://www.thehindu.com/elections/madhya-pradesh-assembly-elections-2018/madhya-pradesh-assembly-election-results-congress-wins-114-seats/article62017163.ece'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Kamal Nath', role: 'Chief Minister, Madhya Pradesh', party: 'INC' }],
    outcome: 'The Congress had won 114 of 230 seats to the BJP\'s 109 (The Hindu); Kamal Nath was sworn in as the state\'s 18th chief minister on 17 December 2018.',
    poll: { label: 'Madhya Pradesh Assembly 2018', month: '2018-11', result: 'Congress won 114 of 230; BJP 109' },
  },
  {
    id: 'hpe127',
    domain: 'civics',
    region: 'India',
    state: 'AP',
    topic: 'Farm & Food',
    subtopic: 'Annadata Sukhibhava (2019)',
    kind: 'spend',
    difficulty: 'expert',
    year: 2019,
    asOf: '2026-09',
    govt: 'TDP',
    question:
      "Andhra's February 2019 vote on account gave ₹5,000 crore to Naidu's new Annadata Sukhibhava farm-aid scheme. What did the new YSRCP government do with it in June 2019?",
    options: [
      'Doubled its payout per acre',
      'Paid the pending first instalment',
      'Merged it into PM-KISAN',
      'Scrapped it for YSR Rythu Bharosa',
    ],
    correctIndex: 3,
    explanation:
      "The Hindu: Finance Minister Yanamala Ramakrishnudu announced the allocation on 5 February and said ₹24,000 crore of farm loans had been waived. Hindustan Times reported that elections were announced before the first instalment reached farmers, and that Jagan Mohan Reddy replaced it with YSR Rythu Bharosa, launching on 15 October with ₹12,500 into each farmer's account.",
    sourceUrl: 'https://www.hindustantimes.com/india-news/jagan-reddy-scraps-chandrababu-naidu-s-farmer-scheme-unveils-new-plan/story-nW2TalpA9nXev1sh7MRobN.html',
    sourceLabel: "Hindustan Times — Jagan Reddy scraps Chandrababu Naidu's farmer scheme, unveils new plan (6 Jun 2019)",
    sources: [
      'https://www.thehindu.com/news/national/andhra-pradesh/5000-cr-allocated-for-annadata-sukhibhava/article26187674.ece',
      'https://www.newindianexpress.com/states/andhra-pradesh/2024/Jun/06/tdp-garners-4560-vote-share',
      W('2019_Andhra_Pradesh_Legislative_Assembly_election'),
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Yanamala Ramakrishnudu', role: 'Finance Minister, Andhra Pradesh', party: 'TDP' }],
    outcome: 'In the 11 April 2019 poll the YSRCP won 151 of 175 seats with 49.95% of the vote; the TDP was reduced to 23.',
    poll: { label: 'Andhra Pradesh Assembly 2019', month: '2019-04', gapDays: 65, result: 'YSRCP won 151 of 175; TDP 23' },
  },

  // ───────────────────────── 2020–2026 ─────────────────────────
  {
    id: 'hpe128',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Education & Exams',
    subtopic: 'Punjab Smart Connect phones (2020)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2020,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "With about 18 months left before the 2022 poll, Punjab's Congress government began giving free smartphones to Class 12 students, a 2017 promise. How many were in phase one?",
    options: ['About 17,400', 'About 1.74 lakh', 'About 17.4 lakh', 'About 50 lakh'],
    correctIndex: 1,
    explanation:
      "The New Indian Express: the ₹92-crore Punjab Smart Connect scheme covered 1,74,015 government-school students, to be completed by November. The phones carried an engraving of Chief Minister Amarinder Singh with the words 'Captain Smart Connect'. He said it was his duty to keep manifesto promises and that phones were vital for online classes.",
    sourceUrl:
      'https://www.newindianexpress.com/india/2020/Aug/12/amarinder-launches-punjab-smart-connect-174015-class-xii-students-to-benefit-in-phase-1-2182526.html',
    sourceLabel: "The New Indian Express — Amarinder launches 'Punjab Smart Connect', 174015 Class XII students to benefit in Phase 1 (12 Aug 2020)",
    sources: [W('2022_Punjab_Legislative_Assembly_election')],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Amarinder Singh', role: 'Chief Minister, Punjab', party: 'INC' }],
    outcome: 'In the February 2022 poll the AAP won 92 of 117 seats; the Congress, by then led by Charanjit Singh Channi, fell to 18.',
    poll: { label: 'Punjab Assembly 2022', month: '2022-02', gapDays: 557, result: 'AAP won 92 of 117; Congress 18' },
  },
  {
    id: 'hpe129',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Health',
    subtopic: 'Free vaccine promise (2020)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2020,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      "Releasing the BJP's Bihar manifesto on 22 October 2020, six days before voting began, Nirmala Sitharaman unveiled which pledge, the first of its 11 resolutions?",
    options: [
      'Free Covid-19 vaccination for everyone in Bihar',
      'Restoring the old pension scheme',
      'Free electricity up to 100 units',
      '₹2,000 a month for farm families',
    ],
    correctIndex: 0,
    explanation:
      "Times of India: opposition parties called it politicising the pandemic, and CPI(M) leader Sitaram Yechury called it a brazen violation of the model code. BJP IT cell head Amit Malviya said health is a state subject and Bihar's BJP had chosen to make the vaccine free; the manifesto also promised 19 lakh jobs.",
    sourceUrl: 'https://timesofindia.indiatimes.com/elections/assembly-elections/bihar/bihar-polls-bjp-promise-of-free-covid-vaccine-in-manifesto-stirs-row/articleshow/78818536.cms',
    sourceLabel: 'Times of India — Bihar polls: BJP promise of free Covid vaccine in manifesto stirs row (23 Oct 2020)',
    sources: [W('2020_Bihar_Legislative_Assembly_election')],
    tags: ['pre-election'],
    enactedBy: [{ name: 'Nirmala Sitharaman', role: 'Union Finance Minister (released manifesto)', party: 'BJP' }],
    outcome: 'The NDA kept power in Bihar; the RJD was the largest party with 75 seats, the BJP won 74 and the JD(U) 43 of 243.',
    poll: { label: 'Bihar Assembly 2020', month: '2020-10', gapDays: 6, result: 'NDA retained power: BJP 74, JD(U) 43; RJD largest with 75 of 243' },
  },
  {
    id: 'hpe130',
    domain: 'civics',
    region: 'India',
    state: 'KL',
    topic: 'Farm & Food',
    subtopic: 'Free food kits (2020–21)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2020,
    asOf: '2026-09',
    govt: 'LDF',
    question:
      "Kerala's LDF government began giving free food kits to every ration-card holder in April 2020 and extended them into the 2021 poll season. How many families got them, per the CM?",
    options: ['About 8.7 lakh', 'About 40 lakh', 'About 2 crore', 'Over 87 lakh'],
    correctIndex: 3,
    explanation:
      "The News Minute: Pinarayi Vijayan said over 87 lakh families received the 17-item kits; distribution began on 10 April 2020 with 47,000 kits on the first day. In December 2020 the government extended the kits for four more months; some felt that was done with the elections in mind, while others said the pandemic's hit to jobs justified it.",
    sourceUrl: 'https://www.thenewsminute.com/kerala/pinarayi-government-s-pandemic-food-kits-have-struck-chord-people-145620',
    sourceLabel: "The News Minute — Pinarayi government's pandemic food kits have struck a chord with people (20 Mar 2021)",
    sources: [
      'https://m.economictimes.com/news/elections/assembly-elections/kerala/ldf-shatters-keralas-40-year-record-pinarayi-vijayan-now-the-marxist-helmsman/articleshow/82359214.cms',
      W('2021_Kerala_Legislative_Assembly_election'),
    ],
    tags: ['pre-election', 'distribution', 'relief'],
    enactedBy: [{ name: 'Pinarayi Vijayan', role: 'Chief Minister, Kerala', party: 'CPI(M)' }],
    outcome:
      'In the 6 April 2021 poll the LDF won 99 of 140 seats to the UDF\'s 41, breaking Kerala\'s 40-year pattern of voting out every government (Economic Times).',
    poll: { label: 'Kerala Assembly 2021', month: '2021-04', gapDays: 361, result: 'LDF re-elected with 99 of 140; UDF 41' },
  },
  {
    id: 'hpe131',
    domain: 'civics',
    region: 'India',
    state: 'TN',
    topic: 'Farm & Food',
    subtopic: 'Crop loan waiver (2021)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2021,
    asOf: '2026-09',
    govt: 'AIADMK',
    question:
      "Two months before Tamil Nadu voted in April 2021, Edappadi K. Palaniswami told the Assembly the state would waive co-operative crop loans. How much?",
    options: ['₹1,211 crore', '₹12,110 crore', '₹5,318 crore', '₹24,000 crore'],
    correctIndex: 1,
    explanation:
      "The Hindu: the 5 February statement covered 16.43 lakh farmers. Palaniswami said the DMK had forgotten its own 2019 promise of a waiver and that the AIADMK alone kept its word, citing Jayalalithaa's 2016 waiver of ₹5,318.73 crore for 12.02 lakh farmers.",
    sourceUrl: 'https://www.thehindu.com/news/national/tamil-nadu/tn-cm-announces-12110-crore-crop-loan-waiver/article33759653.ece',
    sourceLabel: 'The Hindu — TN CM announces ₹12,110 crore crop loan waiver (5 Feb 2021)',
    sources: ['https://www.cnbctv18.com/india/politics/ahead-of-tamil-nadu-exit-poll-results-a-look-at-how-2016-2021-predictions-compared-with-actual-results-ws-el-19894843.htm'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Edappadi K. Palaniswami', role: 'Chief Minister, Tamil Nadu', party: 'AIADMK' }],
    outcome: 'In the 6 April 2021 poll the DMK-led alliance won 159 of 234 seats, the DMK alone 133, and M.K. Stalin became chief minister.',
    poll: { label: 'Tamil Nadu Assembly 2021', month: '2021-04', gapDays: 60, result: 'DMK-led alliance won 159 of 234; DMK alone 133' },
  },
  {
    id: 'hpe132',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Welfare & Subsidies',
    subtopic: 'Lakshmir Bhandar launch (2021)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2021,
    asOf: '2026-09',
    govt: 'TMC',
    question:
      "Promised in the TMC's 2021 manifesto, Lakshmir Bhandar started bank transfers on 1 September 2021 to women without a government job in which age group?",
    options: ['18 to 40', '21 to 65', '25 to 60', '30 to 70'],
    correctIndex: 2,
    explanation:
      "Times of India: beneficiaries were to get ₹500 a month at the base rate, more in some categories. More than 1.1 crore women had applied, and officials said the first estimate of 1.6 crore beneficiaries could rise to nearly 2 crore; money would move only after forms were verified.",
    sourceUrl: 'https://timesofindia.indiatimes.com/city/kolkata/lakshmir-bhandar-bank-transfer-from-today/articleshow/85816832.cms',
    sourceLabel: 'Times of India — Lakshmir Bhandar bank transfer from today (1 Sep 2021)',
    sources: [
      'https://www.thehindu.com/news/cities/kolkata/west-bengal-elections-in-final-tally-tmc-bags-213-bjp-77-isf-and-independent-1-each/article34471551.ece',
      'https://timesofindia.indiatimes.com/city/kolkata/west-bengal-voa-yuba-sathi-debuts-social-schemes-get-fund-boost-in-poll-year/articleshow/127972109.cms',
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Mamata Banerjee', role: 'Chief Minister, West Bengal', party: 'TMC' }],
    outcome:
      'The TMC had won 213 seats to the BJP\'s 77 in the 2021 poll. By February 2026 the scheme reached over 2.2 crore women and the payment rose to ₹1,500 (TOI).',
    poll: { label: 'West Bengal Assembly 2021', month: '2021-03', result: 'TMC won 213 of 292 seats polled; BJP 77' },
  },
  {
    id: 'hpe133',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Energy & Mining',
    subtopic: 'Power-bill waiver for small connections (2021)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2021,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "In September 2021, about five months before Punjab voted, Charanjit Singh Channi's cabinet waived pending power bills for which consumers, at a cost of about ₹1,200 crore?",
    options: [
      'Connections with a load of up to 2 kW',
      'All farm tube-well connections',
      'Industrial units in border districts',
      'Homes using under 300 units a month',
    ],
    correctIndex: 0,
    explanation:
      "Business Standard: the 29 September decision covered 53 lakh consumers with loads up to 2 kW, about 80% of the total, and restored cut connections without penalty. TOI (Jan 2022) put Punjab's power subsidy bill for the year at ₹20,016 crore, of which only ₹7,800 crore had been paid, and said the Congress government had defaulted on subsidy dues every year since 2017.",
    sourceUrl:
      'https://www.business-standard.com/article/economy-policy/punjab-to-waive-pending-power-bills-of-those-having-connection-of-upto-2-kw-121092901283_1.html',
    sourceLabel: 'Business Standard — Punjab to waive pending power bills of those having connection of upto 2 kW (29 Sep 2021)',
    sources: [
      'https://timesofindia.indiatimes.com/business/india-business/explained-punjab-and-up-govt-are-doling-out-free-electricity-ahead-of-elections-but-who-will-bear-this-cost/articleshow/88804306.cms',
      'https://www.business-standard.com/article/elections/kejriwal-promises-300-units-of-free-electricity-ahead-of-punjab-polls-121062900911_1.html',
      W('2022_Punjab_Legislative_Assembly_election'),
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Charanjit Singh Channi', role: 'Chief Minister, Punjab', party: 'INC' }],
    outcome: 'In June 2021 the AAP had promised 300 free units and a waiver of all pending domestic bills (Business Standard). In the 20 February 2022 poll it won 92 of 117 seats; the Congress won 18.',
    poll: { label: 'Punjab Assembly 2022', month: '2022-02', gapDays: 144, result: 'AAP won 92 of 117; Congress 18' },
  },
  {
    id: 'hpe134',
    domain: 'civics',
    region: 'India',
    state: 'GA',
    topic: 'Welfare & Subsidies',
    subtopic: 'Free water (2021)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2021,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Goa's BJP government made household water free from 1 September 2021, about five months before the poll. Up to how many litres a month?",
    options: ['6,000 litres', '10,000 litres', '20,000 litres', '16,000 litres'],
    correctIndex: 3,
    explanation:
      "The Indian Express: Chief Minister Pramod Sawant said Goa was the first state to do this and about 60% of people would get zero bills; households using more pay for their entire use. He announced it on 15 August, a month after AAP chief Arvind Kejriwal promised Goa 300 free power units a month if his party won.",
    sourceUrl: 'https://indianexpress.com/article/india/goa-free-water-scheme-to-begin-today-first-state-to-do-so-pramod-sawant-7481239/',
    sourceLabel: 'The Indian Express — Goa free water scheme to begin today, first state to do so: Pramod Sawant (1 Sep 2021)',
    sources: [
      'https://timesofindia.indiatimes.com/city/goa/using-over-16k-litres-water-a-month-pay-for-entire-usage/articleshow/85848708.cms',
      'https://m.thewire.in/article/politics/goa-assembly-election-results-2022',
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Pramod Sawant', role: 'Chief Minister, Goa', party: 'BJP' }],
    outcome: 'In the 14 February 2022 poll the BJP won 20 of 40 seats and three independents pledged support; the Congress won 11 (The Wire).',
    poll: { label: 'Goa Assembly 2022', month: '2022-02', gapDays: 166, result: 'BJP won 20 of 40; Congress 11' },
  },
  {
    id: 'hpe135',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Energy & Mining',
    subtopic: 'Tube-well power bill cut (2022)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2022,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Days after Akhilesh Yadav promised 300 free power units in January 2022, what did Yogi Adityanath's government announce for farmers' tube-well electricity bills?",
    options: ['A 50% cut', 'A full waiver', 'A 25% cut', 'A freeze at 2017 rates'],
    correctIndex: 0,
    explanation:
      "Times of India: the cut would benefit over 13 lakh users in rural and semi-rural areas; the SP had also promised free irrigation power. Crisil Research's Hetal Gandhe warned that discoms usually recover such losses by raising industrial tariffs, which deepens their debt.",
    sourceUrl:
      'https://timesofindia.indiatimes.com/business/india-business/explained-punjab-and-up-govt-are-doling-out-free-electricity-ahead-of-elections-but-who-will-bear-this-cost/articleshow/88804306.cms',
    sourceLabel: "Times of India — Assembly elections: Parties are promising 'free' power. Who will bear this cost? (10 Jan 2022)",
    sources: [
      'https://timesofindia.indiatimes.com/india/free-ration-scheme-extended-for-3-more-months-in-up-15-crore-people-to-be-benefitted/articleshow/90455925.cms',
      W('2022_Uttar_Pradesh_Legislative_Assembly_election'),
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Yogi Adityanath', role: 'Chief Minister, Uttar Pradesh', party: 'BJP' }],
    outcome:
      'The BJP won 255 of 403 seats; the SP 111. The re-elected government\'s first cabinet extended its free-ration scheme for 15 crore people by three months at ₹3,270 crore.',
    poll: { label: 'UP Assembly 2022', month: '2022-02', result: 'BJP won 255 of 403; SP 111' },
  },
  {
    id: 'hpe136',
    domain: 'civics',
    region: 'India',
    state: 'KA',
    topic: 'Farm & Food',
    subtopic: "Bommai's last budget (2023)",
    kind: 'spend',
    difficulty: 'extreme',
    year: 2023,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "In his last budget before Karnataka's May 2023 poll, Basavaraj Bommai raised the limit on interest-free short-term farm loans from ₹3 lakh to what?",
    options: ['₹4 lakh', '₹5 lakh', '₹6 lakh', '₹10 lakh'],
    correctIndex: 1,
    explanation:
      "The South First: the 17 February budget also offered 'Bhoo Siri', a ₹10,000 top-up for Kisan Credit Card holders (₹2,500 from the state, ₹7,500 from NABARD) for about 50 lakh farmers, free tuition in government pre-university and degree colleges, and a rise in weavers' aid from ₹3,000 to ₹5,000.",
    sourceUrl: 'https://thesouthfirst.com/karnataka/free-bus-passes-waivers-grants-incentives-revdi-by-bjp-government-in-karnataka-budget-2023/',
    sourceLabel: "The South First — Free bus passes, waivers, grants, incentives: 'Revdi' by BJP government in Karnataka budget 2023 (17 Feb 2023)",
    sources: [W('2023_Karnataka_Legislative_Assembly_election')],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Basavaraj Bommai', role: 'Chief Minister and Finance Minister, Karnataka', party: 'BJP' }],
    outcome: 'In the 10 May 2023 poll the Congress, campaigning on five "guarantees", won 135 of 224 seats; the BJP fell to 66 and the JD(S) to 19.',
    poll: { label: 'Karnataka Assembly 2023', month: '2023-05', gapDays: 82, result: 'Congress won 135 of 224; BJP 66; JD(S) 19' },
  },
  {
    id: 'hpe137',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Jobs & Economy',
    subtopic: 'Minimum Guaranteed Income Act (2023)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2023,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Rajasthan's Minimum Guaranteed Income law, passed in July 2023 four months before the poll, set a ₹1,000 minimum monthly pension. By how much must it rise each year?",
    options: ['8%', '12%', '20%', '15%'],
    correctIndex: 3,
    explanation:
      "The Hindu: passed by voice vote on 21 July, the law also guarantees 125 days of work a year per family (25 beyond MGNREGS in villages). The pension, for the elderly, disabled people, widows and single women, rises 5% each July and 10% each January from 2024-25. BJP MLAs wanted it circulated for public opinion; Gehlot likened it to the Congress's 2019 NYAY pledge.",
    sourceUrl: 'https://www.thehindu.com/news/national/rajasthan-assembly-passes-bills-on-minimum-income-higher-punishment-for-paper-leaks/article67106940.ece',
    sourceLabel: 'The Hindu — Rajasthan Assembly passes Bills on minimum income, higher punishment for paper leaks (22 Jul 2023)',
    sources: ['https://www.livemint.com/elections/assembly-elections/bjp-emerges-victorious-in-rajasthan-assembly-election-securing-115-seats-a-recap-10-points-11701651737789.html'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Ashok Gehlot', role: 'Chief Minister, Rajasthan', party: 'INC' }],
    outcome: 'In the 25 November 2023 poll the BJP won 115 of 199 seats and the Congress 69, keeping Rajasthan\'s three-decade habit of voting out the incumbent (Mint).',
    poll: { label: 'Rajasthan Assembly 2023', month: '2023-11', gapDays: 127, result: 'BJP won 115 of 199; Congress 69' },
  },
  {
    id: 'hpe138',
    domain: 'civics',
    region: 'India',
    state: 'CT',
    topic: 'Farm & Food',
    subtopic: "BJP's paddy promise (2023)",
    kind: 'scheme',
    difficulty: 'simple',
    year: 2023,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Released four days before Chhattisgarh's first phase of voting in 2023, the BJP's manifesto promised to buy paddy from farmers at what price per quintal?",
    options: ['₹2,500', '₹3,100', '₹2,640', '₹3,600'],
    correctIndex: 1,
    explanation:
      "The Hindu: Amit Shah released it on 3 November, offering 21 quintals an acre under a 'Krishi Unnati' scheme, paid in one go, LPG cylinders at ₹500, and aid to married women and landless labourers. It made no farm-loan waiver promise, which the ruling Congress had announced.",
    sourceUrl:
      'https://www.thehindu.com/elections/chhattisgarh-assembly/chhattisgarh-polls-bjp-promises-sops-for-married-women-landless-farm-labourers-lpg-cylinder-at-500/article67493270.ece',
    sourceLabel: 'The Hindu — BJP Chhattisgarh manifesto promises Ayodhya pilgrimage, financial assistance for women et al (3 Nov 2023)',
    sources: ['https://www.aljazeera.com/news/2023/12/3/indias-bjp-leads-in-3-of-4-states-in-key-regional-elections'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Amit Shah', role: 'Union Home Minister (released manifesto)', party: 'BJP' }],
    outcome:
      'The BJP won 54 of 90 seats to the Congress\'s 35 in the November 2023 poll, taking back the state it had lost in 2018 (Al Jazeera).',
    poll: { label: 'Chhattisgarh Assembly 2023', month: '2023-11', gapDays: 4, result: 'BJP won 54 of 90; Congress 35' },
  },
  {
    id: 'hpe139',
    domain: 'civics',
    region: 'India',
    state: 'TG',
    topic: 'Farm & Food',
    subtopic: 'Finishing the loan waiver (2023)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2023,
    asOf: '2026-09',
    govt: 'BRS',
    question:
      "Four months before Telangana's 2023 poll, K. Chandrasekhar Rao ordered ₹19,000 crore released to banks to complete which 2018 promise by mid-September?",
    options: [
      'Rythu Bandhu at ₹15,000 an acre',
      'The crop-loan waiver of up to ₹1 lakh',
      'Dalit Bandhu for every SC family',
      'Free electricity for all homes',
    ],
    correctIndex: 1,
    explanation:
      "The Indian Express: payments resumed on 3 August after an almost four-year pause. KCR blamed demonetisation, Covid-19 and the Centre withholding FRBM and other funds for the delay. State Congress chief Revanth Reddy called it a 'poll gimmick' and the BJP said KCR remembered farmers only before elections.",
    sourceUrl: 'https://indianexpress.com/article/political-pulse/kcr-2018-farm-loan-waiver-promise-polls-bjp-cry-foul-8874277/',
    sourceLabel: 'The Indian Express — KCR clears 2018 farm loan waiver promise just before polls; Cong, BJP cry foul (3 Aug 2023)',
    sources: [
      'https://telanganatoday.com/cm-kcr-orders-release-of-rs-19000-crore-for-crop-loan-waiver',
      'https://www.livemint.com/elections/telangana-election-result-recap-congress-ends-10-year-rule-of-brs-secures-64-seats-10-points-to-know-11701664939720.html',
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'K. Chandrasekhar Rao', role: 'Chief Minister, Telangana', party: 'BRS' }],
    outcome: 'In the 30 November 2023 poll the Congress won 64 of 119 seats, ending ten years of BRS rule; the BRS won 39 and the BJP 8 (Mint).',
    poll: { label: 'Telangana Assembly 2023', month: '2023-11', gapDays: 120, result: 'Congress won 64 of 119; BRS 39; BJP 8' },
  },
  {
    id: 'hpe140',
    domain: 'civics',
    region: 'India',
    state: 'TG',
    topic: 'Welfare & Subsidies',
    subtopic: "Congress's six guarantees (2023)",
    kind: 'scheme',
    difficulty: 'simple',
    year: 2023,
    asOf: '2026-09',
    govt: 'BRS',
    question:
      "Launching the Congress's Telangana campaign near Hyderabad on 17 September 2023, Sonia Gandhi promised women how much a month under 'Mahalakshmi'?",
    options: ['₹1,000', '₹1,500', '₹2,500', '₹3,000'],
    correctIndex: 2,
    explanation:
      "The Indian Express: the six guarantees also offered LPG at ₹500, free bus travel for women, ₹15,000 an acre per season for farmers, ₹12,000 for tenant farmers and farm labourers, ₹10 lakh health cover and ₹5 lakh housing grants. Rahul Gandhi said all six would be implemented on the day the party came to power.",
    sourceUrl:
      'https://indianexpress.com/article/india/congress-telangana-rally-telangana-assembly-elections-bjp-rishtedar-samithi-sonia-gandhi-rahul-gandhi-8944525/',
    sourceLabel: "The Indian Express — Congress's Telangana Rally: Sonia lists out six guarantees (18 Sep 2023)",
    sources: [
      'https://www.livemint.com/elections/telangana-election-result-recap-congress-ends-10-year-rule-of-brs-secures-64-seats-10-points-to-know-11701664939720.html',
      'https://timesofindia.indiatimes.com/city/hyderabad/telangana-women-saves-10000-cr-through-mahalakshmi-free-bus-scheme-rtc/articleshow/130025980.cms',
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Sonia Gandhi', role: 'Congress leader (announced the guarantees)', party: 'INC' }],
    outcome: 'The Congress won 64 of 119 seats and formed the government; the BRS won 39. Free bus travel for women began on 9 December 2023, and by early 2026 TGSRTC counted over 290 crore zero-fare trips (TOI).',
    poll: { label: 'Telangana Assembly 2023', month: '2023-11', gapDays: 74, result: 'Congress won 64 of 119; BRS 39; BJP 8' },
  },
  {
    id: 'hpe141',
    domain: 'civics',
    region: 'India',
    state: 'AP',
    topic: 'Elections & Funding',
    subtopic: 'ECI holds back DBT credits (2024)',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'YSRCP',
    question:
      "On 9 May 2024, four days before Andhra Pradesh voted, the ECI told the state not to credit money under six DBT schemes whose 'buttons' were pressed from January to March. How much?",
    options: ['About ₹1,416 crore', 'About ₹4,200 crore', 'About ₹14,166 crore', 'About ₹41,000 crore'],
    correctIndex: 2,
    explanation:
      "Hindustan Times: the ECI listed ₹14,165.66 crore announced at 'button-press' events before the model code began on 16 March, the largest ₹6,394 crore under YSR Asara on 23 January, but not yet sent to banks. Crediting it so close to polling could tilt the level playing field, it said; transfers should follow 13 May. YSRCP leaders blamed a TDP complaint (Hans India).",
    otherSide:
      "YSRCP leaders alleged the TDP had conspired to stop welfare money by complaining to the Election Commission; the state had asked a court to allow the transfers.",
    sourceUrl:
      'https://www.hindustantimes.com/india-news/dont-disburse-14-000cr-among-beneficiaries-before-polling-eci-tells-andhra-cm-101715253041498.html',
    sourceLabel: 'Hindustan Times — Don’t disburse ₹14,000cr among beneficiaries before polling: ECI tells Andhra CM (9 May 2024)',
    sources: [
      'https://www.thehansindia.com/news/cities/vijayawada/ap-government-releases-funds-to-welfare-schemes-878844',
      'https://www.newindianexpress.com/states/andhra-pradesh/2024/Jun/06/tdp-garners-4560-vote-share',
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Y.S. Jagan Mohan Reddy', role: 'Chief Minister, Andhra Pradesh (announced the releases)', party: 'YSRCP' }],
    outcome:
      'A court let the money go only after polling; two days after the vote the state released ₹1,480 crore for Asara and ₹502 crore for fee reimbursement (Hans India). The TDP won 135 seats, the Jana Sena 21 and the BJP 8; the YSRCP fell from 151 to 11 (NIE).',
    poll: { label: 'Andhra Pradesh Assembly 2024', month: '2024-05', gapDays: 111, result: 'TDP 135, Jana Sena 21, BJP 8 of 175; YSRCP 11' },
  },
  {
    id: 'hpe142',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Welfare & Subsidies',
    subtopic: 'Har Ghar Har Grihini LPG (2024)',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "About eight weeks before Haryana's October 2024 poll, Nayab Singh Saini's government launched LPG cylinders at ₹500 for about how many Antyodaya families?",
    options: ['About 5 lakh', 'About 15 lakh', 'About 50 lakh', 'About 1.5 crore'],
    correctIndex: 2,
    explanation:
      "All India Radio: Saini had announced it at a Hariyali Teej event in Jind; the 'Har Ghar-Har Grihini' portal opened on 12 August. Families could buy up to 12 cylinders a year, with the amount above ₹500 refunded to their accounts; the state put the benefit at ₹1,500 crore a year.",
    sourceUrl: 'https://newsonair.gov.in/haryana-cm-nayab-singh-saini-launches-har-ghar-har-grihini-yojana/',
    sourceLabel: "News On AIR — Haryana CM Nayab Singh Saini launches 'Har Ghar-Har Grihini Yojana' (12 Aug 2024)",
    sources: ['https://www.babushahi.com/full-news.php?id=189390', W('2024_Haryana_Legislative_Assembly_election')],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Nayab Singh Saini', role: 'Chief Minister, Haryana', party: 'BJP' }],
    outcome: 'In the 5 October 2024 poll the BJP won 48 of 90 seats, a third straight term; the Congress won 37.',
    poll: { label: 'Haryana Assembly 2024', month: '2024-10', gapDays: 54, result: 'BJP won 48 of 90; Congress 37' },
  },
  {
    id: 'hpe143',
    domain: 'civics',
    region: 'India',
    state: 'JH',
    topic: 'Farm & Food',
    subtopic: 'Farm-loan waiver raised (2024)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'JMM',
    question:
      "About three months before Jharkhand's November 2024 poll, Hemant Soren's cabinet raised the farm-loan waiver limit from ₹50,000 to what?",
    options: ['₹75,000', '₹1 lakh', '₹3 lakh', '₹2 lakh'],
    correctIndex: 3,
    explanation:
      "India Today: the 7 August decision applied to 2024-25, with a 31 March 2020 cut-off and a likely cost of about ₹750 crore. From 2020-21 to 2023-24 the scheme had waived ₹1,900.35 crore for 4.73 lakh farmers. The same meeting doubled honoraria for traditional village heads.",
    sourceUrl:
      'https://www.indiatoday.in/india/story/jharkhand-cabinet-meeting-hemant-soren-jharkhand-agricultural-loan-waiver-scheme-farmers-2578777-2024-08-08',
    sourceLabel: 'India Today — Jharkhand cabinet increases loan waivers limit for farmers upto Rs 2 lakh (8 Aug 2024)',
    sources: ['https://eng.ruralvoice.in/state/jharkhand-government-waives-farm-loans-up-to-rs-2-lakh-for-1.76-lakh-farmers.html', W('2024_Jharkhand_Legislative_Assembly_election')],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Hemant Soren', role: 'Chief Minister, Jharkhand', party: 'JMM' }],
    outcome:
      'On 26 September Soren transferred ₹400.66 crore to clear loans of 1.76 lakh farmers (RuralVoice). The JMM-led alliance was re-elected: JMM 34, Congress 16; BJP 21 of 81.',
    poll: { label: 'Jharkhand Assembly 2024', month: '2024-11', gapDays: 98, result: 'JMM-led alliance re-elected: JMM 34, Congress 16; BJP 21 of 81' },
  },
  {
    id: 'hpe144',
    domain: 'civics',
    region: 'India',
    state: 'MH',
    topic: 'Welfare & Subsidies',
    subtopic: 'Ladki Bahin paid ahead of the code (2024)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'SS',
    question:
      "Before the model code took effect on 15 October 2024, Maharashtra had paid Ladki Bahin benefits to about 2.34 crore women up to which month?",
    options: ['September 2024', 'October 2024', 'November 2024', 'December 2024'],
    correctIndex: 2,
    explanation:
      "The Asian Age: officials said everyone identified by then was paid till November because the government expected difficulty under the code; more than 10 lakh later applicants had to wait, as new beneficiaries needed ECI permission. Scroll cited a Lokniti-CSDS and MIT-SOG survey that found eight in ten voters knew of the scheme.",
    sourceUrl: 'https://www.asianage.com/nation/new-applicants-for-ladki-bahin-scheme-will-not-get-benefits-till-elections-are-over-1831453',
    sourceLabel: "The Asian Age — New applicants for 'Ladki Bahin' scheme will not get benefits till elections are over (20 Oct 2024)",
    sources: [
      'https://scroll.in/article/1075462/can-the-ladki-bahin-scheme-prove-to-be-a-gamechanger-in-maharashtra-elections',
      'https://www.thehindu.com/elections/maharashtra-assembly/csds-lokniti-survey-women-sided-with-mahayuti-for-ladki-bahin-yojanas-monthly-dole/article68905679.ece',
      W('2024_Maharashtra_Legislative_Assembly_election'),
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Eknath Shinde', role: 'Chief Minister, Maharashtra', party: 'Shiv Sena' }],
    outcome: 'In the 20 November 2024 poll the ruling alliance swept: BJP 132, Shiv Sena 57, NCP 41 of 288. A Lokniti-CSDS post-poll survey found more women than men backed it, more so women who had applied for the scheme (The Hindu).',
    poll: { label: 'Maharashtra Assembly 2024', month: '2024-11', result: 'BJP 132, Shiv Sena 57, NCP 41 of 288: ruling Mahayuti swept' },
  },
  {
    id: 'hpe145',
    domain: 'civics',
    region: 'India',
    state: 'OD',
    topic: 'Welfare & Subsidies',
    subtopic: 'Subhadra: the manifesto version (2024)',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'BJD',
    question:
      "Before Odisha's 2024 poll, the BJP manifesto promised every woman a ₹50,000 cash voucher under 'Subhadra'. Over how long did it say the voucher could be encashed?",
    options: ['Two years', 'One year', 'Five years', 'Ten years'],
    correctIndex: 0,
    explanation:
      "The Hindu: as rolled out by Mohan Majhi's government, Subhadra pays ₹50,000 over five years to women aged 21–60, leaving out income-tax payers, those drawing ₹1,500 a month from other schemes, owners of over 5 irrigated acres or four-wheelers, and elected members. The BJD and Congress protested in the Assembly.",
    sourceUrl: 'https://www.thehindu.com/news/national/odisha/changes-to-subhadra-yojana-bjps-poll-promise-sparks-a-row-in-odisha/article68597761.ece',
    sourceLabel: "The Hindu — Changes to 'Subhadra Yojana', BJP's poll promise, sparks a row in Odisha (3 Sep 2024)",
    sources: [
      'https://www.newindianexpress.com/states/odisha/2024/May/06/bjp-promises-rs-50k-voucher-for-women-in-its-manifesto',
      'https://www.thehindu.com/elections/odisha-assembly/odisha-assembly-elections-2024-at-a-glance/article68246879.ece',
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'J.P. Nadda', role: 'BJP national president (released manifesto)', party: 'BJP' }],
    outcome: 'The BJP won 78 of 147 seats, ending 24 years of BJD rule; the BJD won 51 and the Congress 14 (The Hindu).',
    poll: { label: 'Odisha Assembly 2024', month: '2024-05', result: 'BJP won 78 of 147; BJD 51; Congress 14' },
  },
  {
    id: 'hpe146',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Energy & Mining',
    subtopic: '125 free units (2025)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      "On 17 July 2025, less than four months before Bihar voted, Nitish Kumar announced free electricity for domestic consumers up to how many units a month?",
    options: ['125 units', '100 units', '200 units', '300 units'],
    correctIndex: 0,
    explanation:
      "The New Indian Express: the cabinet approved it the next day, from 1 August, covering 1.67 crore of Bihar's 1.86 crore domestic consumers with no fixed charges up to 125 units. It also approved full subsidy for rooftop solar for 58.89 lakh Kutir Jyoti (BPL) consumers.",
    sourceUrl:
      'https://www.newindianexpress.com/india/2025/Jul/18/bihar-cabinet-gives-nod-for-free-electricity-upto-125-units-167-crore-power-consumers-to-benefit',
    sourceLabel: 'The New Indian Express — Bihar cabinet gives nod for free electricity upto 125 units (18 Jul 2025)',
    sources: [
      'https://timesofindia.indiatimes.com/india/bihar-election-results-2025-nitish-does-it-again-alliance-returns-with-crushing-202-seats/articleshow/125339199.cms',
      'https://www.hindustantimes.com/india-news/nda-mahagathbandhan-bjp-jdu-rjd-congress-ljp-jan-suraaj-prashant-kishore-tejashwi-seat-tally-101763169862862.html',
      'https://www.thehindu.com/elections/bihar-assembly/bihar-assembly-election-first-phase-sees-over-64-voter-turnout/article70249590.ece',
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'Nitish Kumar', role: 'Chief Minister, Bihar', party: 'JD(U)' }],
    outcome: 'The NDA returned with 202 of 243 seats in November 2025 — BJP 89, JD(U) 85 — while the RJD fell to 25.',
    poll: { label: 'Bihar Assembly 2025', month: '2025-11', gapDays: 112, result: 'NDA won 202 of 243: BJP 89, JD(U) 85; RJD 25' },
  },
  {
    id: 'hpe147',
    domain: 'civics',
    region: 'India',
    state: 'MH',
    topic: 'Elections & Funding',
    subtopic: 'Ladki Bahin and the civic-poll code (2026)',
    kind: 'institution',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Days before Maharashtra's 15 January 2026 municipal polls, what did the State Election Commission bar the government from paying under the Ladki Bahin scheme?",
    options: [
      'Any instalment until results',
      'The regular December instalment',
      'An advance January instalment',
      'Arrears to women over 60',
    ],
    correctIndex: 2,
    explanation:
      "The Hindu: a BJP minister had posted that women would get ₹3,000 for December and January before 14 January, a day before polling; the Congress complained on 10 January. CM Devendra Fadnavis said it was a continuing scheme. The SEC said ongoing benefits could continue under the code, but not in advance, and no new beneficiaries could be added.",
    otherSide:
      "The Chief Minister said Ladki Bahin was a continuing scheme launched before the polls and did not fall under the model code.",
    sourceUrl: 'https://www.thehindu.com/news/national/maharashtra/ladki-bahin-scheme-maharashtra-election-commission-model-code-polls/article70501117.ece',
    sourceLabel: "The Hindu — 'Ladki Bahin' scheme: State Election Commission bars Maharashtra govt from releasing advance installment (12 Jan 2026)",
    sources: ['https://timesofindia.indiatimes.com/india/hotel-politics-returns-to-mumbai-mahayutis-musical-chairs-over-mayor-after-bmc-win-10-things-to-know/articleshow/126639765.cms'],
    tags: ['pre-election', 'distribution'],
    enactedBy: [
      { name: 'Girish Mahajan', role: 'Minister, Maharashtra (announced the advance)', party: 'BJP' },
      { name: 'Devendra Fadnavis', role: 'Chief Minister, Maharashtra', party: 'BJP' },
    ],
    outcome: 'In Mumbai the BJP won 89 of 227 BMC wards, and with the Shinde Sena\'s 29 the allies crossed the majority mark of 114 (TOI).',
    poll: { label: 'Maharashtra municipal polls (incl. BMC), Jan 2026', month: '2026-01', result: 'BJP won 89 of 227 BMC wards; with Shinde Sena (29) the allies hold 118' },
  },
  {
    id: 'hpe148',
    domain: 'civics',
    region: 'India',
    state: 'WB',
    topic: 'Jobs & Economy',
    subtopic: 'Banglar Yuba-Sathi (2026)',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2026,
    asOf: '2026-09',
    govt: 'TMC',
    question:
      "Bengal's February 2026 vote on account launched Banglar Yuba-Sathi, ₹1,500 a month for jobless Madhyamik-pass youth aged 21–40. How much did it set aside for 2026-27?",
    options: ['₹5,000 crore', '₹500 crore', '₹15,000 crore', '₹50,000 crore'],
    correctIndex: 0,
    explanation:
      "Times of India: Finance Minister Chandrima Bhattacharya's 5 February speech set a 15 August start, for up to five years or until a job; BJP MLA Ashok Lahiri said the vote on account looked 'more like the Trinamool manifesto'. Mamata Banerjee then advanced the start to 1 April, and on 7 March said transfers would begin that day (Millennium Post).",
    sourceUrl:
      'https://timesofindia.indiatimes.com/city/kolkata/west-bengal-voa-yuba-sathi-debuts-social-schemes-get-fund-boost-in-poll-year/articleshow/127972109.cms',
    sourceLabel: 'Times of India — West Bengal VOA: Yuba-Sathi debuts, social schemes get fund boost in poll year (6 Feb 2026)',
    sources: [
      'https://timesofindia.indiatimes.com/city/kolkata/yuva-sathi-will-roll-out-on-apr-1-instead-of-aug-15/articleshow/128173264.cms',
      'https://www.millenniumpost.in/bengal/mamata-announces-start-of-yuba-sathi-fund-transfers-to-beneficiaries-south-24-pgns-reported-highest-number-of-applications-650901',
      'https://results.eci.gov.in/ResultAcGenMay2026/partywiseresult-S25.htm',
      'https://newsonair.gov.in/polling-to-be-held-in-single-phase-in-tamilnadu-on-23rd-april-two-phase-polling-in-west-bengal-to-be-held-on-23rd-and-29th-of-next-month/',
      'https://www.thehindu.com/news/national/west-bengal/in-its-first-budget-west-bengal-bjp-government-pushes-for-jobs-industries-and-welfarism/article71133177.ece',
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [
      { name: 'Chandrima Bhattacharya', role: 'Finance Minister, West Bengal', party: 'TMC' },
      { name: 'Mamata Banerjee', role: 'Chief Minister, West Bengal (advanced the start)', party: 'TMC' },
    ],
    outcome: "Mamata said 90 lakh to 1 crore youths applied. Bengal voted on 23 and 29 April; the BJP won 207 seats and the TMC 80 (ECI). The BJP government's June 2026 budget offered jobless youth ₹3,000 a month under a scheme called Bhorsa Karmasathi (The Hindu).",
    poll: { label: 'West Bengal Assembly 2026', month: '2026-04', gapDays: 77, result: 'BJP won 207 of 294; TMC 80 (ECI)' },
  },
  {
    id: 'hpe149',
    domain: 'civics',
    region: 'India',
    state: 'TN',
    topic: 'Welfare & Subsidies',
    subtopic: 'Pongal cash gift (2026)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'DMK',
    question:
      "In January 2026, months before the Assembly poll, Tamil Nadu's DMK government announced a Pongal cash gift for every rice ration card. How much?",
    options: ['₹3,000', '₹1,000', '₹2,500', '₹5,000'],
    correctIndex: 0,
    explanation:
      "The New Indian Express: about 2.23 crore cards qualified and ₹6,936.18 crore was sanctioned, with cash handed out at ration shops. It was the largest Pongal cash gift since the practice began in 2014 at ₹100; the AIADMK had given ₹2,500 before the 2021 poll.",
    sourceUrl:
      'https://www.newindianexpress.com/states/tamil-nadu/2026/Jan/04/tamil-nadu-government-announces-rs-3000-cash-assistance-per-ration-card-ahead-of-pongal',
    sourceLabel: 'The New Indian Express — Tamil Nadu government announces Rs 3,000 cash assistance per ration card ahead of Pongal (4 Jan 2026)',
    sources: [
      'https://results.eci.gov.in/ResultAcGenMay2026/partywiseresult-S22.htm',
      'https://www.bbc.com/news/articles/c8xwjx54zggo',
      'https://newsonair.gov.in/polling-to-be-held-in-single-phase-in-tamilnadu-on-23rd-april-two-phase-polling-in-west-bengal-to-be-held-on-23rd-and-29th-of-next-month/',
    ],
    tags: ['pre-election', 'distribution'],
    enactedBy: [{ name: 'M.K. Stalin', role: 'Chief Minister, Tamil Nadu', party: 'DMK' }],
    outcome:
      "In the 23 April 2026 poll actor Vijay's two-year-old TVK won 108 of 234 seats; the DMK fell to 59 and the AIADMK won 47 (ECI), breaking the DMK–AIADMK pattern.",
    poll: { label: 'Tamil Nadu Assembly 2026', month: '2026-04', gapDays: 109, result: 'TVK won 108 of 234; DMK 59; AIADMK 47 (ECI)' },
  },
]);
