// HISAAB DO — Before the vote: Union lane (hpe001–hpe099), money-trail mode "Chunav Se Pehle".
// Contract: docs/hisaab/CHARTER.md §2–§5, §3a and §4a–§4b; editions/hisaab/bank/schema.mjs.
// Research notes, sources, dropped items and stale-risk list: docs/hisaab/research/poll-union-notes.md.
// Every figure was read on the item's sourceUrl (or a listed source) in September 2026 (asOf).
// enactedBy records who announced, presented or passed a measure — a public act, not an allegation.
// gapDays = days from the announcement, first payment or vote to the first day of polling in that election;
// it is left out where the polling date could not be confirmed from a fetched source.
// govt = the government at the Centre that took the decision; items about one state's share of a Union
// budget carry that state's code in `state` (same convention as dist-centre.mjs).

export const HISAAB_POLL_UNION = Object.freeze([
  // ───────────────────────────── 2000–2004 ─────────────────────────────
  {
    id: "hpe001",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Elections & Funding",
    subtopic: "'India Shining' ads (2004)",
    kind: "spend",
    difficulty: "simple",
    year: 2004,
    asOf: "2026-09",
    govt: "NDA",
    question: "After the Congress complained in 2004, what did the Election Commission do about the government-funded 'India Shining' advertisements?",
    options: ["Barred their broadcast until polling ended", "Fined the BJP the full cost of the ads", "Ordered the ministry to recover the money", "Let them run with a disclaimer"],
    correctIndex: 0,
    explanation: "Reuters, carried by Rediff on 2 April 2004, reported that the EC banned the slogan's broadcast until voting ended on 10 May, after the Congress said it gave the BJP an unfair boost at taxpayers' expense. Grey Worldwide coined it for a ₹65-crore government campaign; BJP leaders kept using it on the stump.",
    otherSide:
      "No reply from the NDA government to the EC ban was reported as of Sep 2026; the ad agency's creative director said the slogan 'was not (meant) to be political' (AFP).",
    sourceUrl: "https://www.rediff.com/business/special/shining/20040402.htm",
    sourceLabel: "Rediff (Reuters) — The man behind 'India Shining' slogan (2 Apr 2004)",
    sources: [
      "https://indianexpress.com/article/political-pulse/bjp-india-shining-rajnath-singh-8925418/",
      "https://www.thehindu.com/news/national/congress-upa-india-elections-2004-2009-politics-explainer-sonia-manmohan-vajpayee-nada-coalition-alliance/article68023875.ece",
    ],
    tags: ["pre-election"],
    outcome: "Four-phase polling ran 20 April–10 May. The NDA lost office: the Congress won 145 seats to the BJP's 138 (The Hindu). The Indian Express (2023) put the BJP's estimated spend on the ad blitz at about ₹150 crore.",
    poll: { label: "Lok Sabha 2004", month: "2004-04", result: "INC 145, BJP 138 seats; the Congress-led UPA formed the government" },
  },
  {
    id: "hpe002",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Jaswant Singh's 'mini-budget' (Jan 2004)",
    kind: "spend",
    difficulty: "expert",
    year: 2004,
    asOf: "2026-09",
    govt: "NDA",
    question: "In a surprise 'mini-budget' on 8 January 2004, with early polls in the air, Jaswant Singh cut customs duties on phones and electronics and abolished which levy?",
    options: ["The long-term capital gains tax", "The income-tax surcharge", "The domestic and foreign travel tax", "Stamp duty on share trades"],
    correctIndex: 2,
    explanation: "Rediff reported the cuts on customs duties for non-farm goods, cell phones, IT and electronics took effect on 9 January, 'with an eye on early Lok Sabha elections', and the Sensex closed at 6,109. His interim budget of 3 February called the 8 January steps 'timely and necessary' and did not repeat them.",
    sourceUrl: "https://www.rediff.com/business/report/bud12/20040108.htm",
    sourceLabel: "Rediff — Markets likely to zoom up on Friday (8 Jan 2004)",
    sources: ["https://www.indiabudget.gov.in/budget_archive/ub2004-05(I)/bs/speecha.htm"],
    tags: ["pre-election"],
    enactedBy: [{ name: "Jaswant Singh", role: "Union Finance Minister", party: "BJP" }],
    outcome: "Polling began 103 days later; the NDA lost office as the Congress won 145 seats to the BJP’s 138.",
    poll: { label: "Lok Sabha 2004", month: "2004-04", result: "INC 145, BJP 138 seats; the Congress-led UPA formed the government", gapDays: 103 },
  },
  {
    id: "hpe003",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "DA merger for central staff (2004)",
    kind: "spend",
    difficulty: "extreme",
    year: 2004,
    asOf: "2026-09",
    govt: "NDA",
    question: "With dearness allowance at 59% of pay, what did the interim budget of 3 February 2004 decide for central government employees from 1 April 2004?",
    options: ["Set up the Sixth Pay Commission at once", "Merge DA of up to 50% of pay into basic pay", "Freeze DA at 59% until 2005", "Pay a one-time bonus of 10% of pay"],
    correctIndex: 1,
    explanation: "Jaswant Singh said the Fifth Pay Commission had advised merging DA into pay once it crossed 50%. Having 're-examined' this, the government merged DA 'to the extent of 50 per cent of pay' into basic pay from 1 April 2004. The same speech set up a non-lapsable ₹25,000-crore Defence Modernisation Fund.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2004-05(I)/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Interim Budget 2004-05 speech, Jaswant Singh (3 Feb 2004)",
    sources: ["https://www.thehindu.com/news/national/congress-upa-india-elections-2004-2009-politics-explainer-sonia-manmohan-vajpayee-nada-coalition-alliance/article68023875.ece"],
    tags: ["pre-election"],
    enactedBy: [{ name: "Jaswant Singh", role: "Union Finance Minister", party: "BJP" }],
    outcome: "Polling began 77 days later. The Congress won 145 seats to the BJP’s 138 and the NDA left office (The Hindu).",
    poll: { label: "Lok Sabha 2004", month: "2004-04", result: "INC 145, BJP 138 seats; the Congress-led UPA formed the government", gapDays: 77 },
  },
  {
    id: "hpe004",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "PMSSY: six AIIMS-like hospitals",
    kind: "scheme",
    difficulty: "expert",
    year: 2004,
    asOf: "2026-09",
    govt: "NDA",
    question: "The February 2004 interim budget provided for six AIIMS-like hospitals Vajpayee had promised in August 2003. When did regular MBBS batches begin at them?",
    options: ["2005", "2008", "2010", "2012"],
    correctIndex: 3,
    explanation: "The six—Bhopal, Bhubaneswar, Jodhpur, Patna, Raipur, Rishikesh—fall under the Pradhan Mantri Swasthya Suraksha Yojana. Alt News notes the NDA lost power months later, the UPA Cabinet approved them in March 2006 and MBBS classes began in 2012; work ran under both governments. A 2011 NIE report called the NDA's push 'election-oriented'.",
    otherSide:
      "The Union health ministry has said the six AIIMS are functional, with 16 more at various stages of construction (Alt News, 2021).",
    sourceUrl: "https://www.altnews.in/did-upa-govt-build-only-one-aiims-institute-during-their-tenure-false-claim-viral/",
    sourceLabel: "Alt News — Did UPA govt build only one AIIMS during their tenure? (25 Apr 2021)",
    sources: ["https://www.indiabudget.gov.in/budget_archive/ub2004-05(I)/bs/speecha.htm"],
    tags: ["pre-election"],
    enactedBy: [{ name: "Atal Bihari Vajpayee", role: "Prime Minister", party: "BJP" }, { name: "Jaswant Singh", role: "Union Finance Minister", party: "BJP" }],
    outcome: "Vajpayee's 2003 promise was three years; nursing courses began in 2013. A 2019 CAG report, cited by Alt News, said infrastructure at the six was still pending and they were not yet fully functional like AIIMS Delhi.",
    poll: { label: "Lok Sabha 2004", month: "2004-04", result: "INC 145, BJP 138 seats; the Congress-led UPA formed the government", gapDays: 77 },
  },
  {
    id: "hpe005",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Farm Income Insurance Scheme (2004)",
    kind: "scheme",
    difficulty: "extreme",
    year: 2004,
    asOf: "2026-09",
    govt: "NDA",
    question: "The 2004 interim budget said the pilot Farm Income Insurance Scheme, then running in 20 districts, would be extended to how many districts from the coming kharif season?",
    options: ["50", "100", "200", "All districts"],
    correctIndex: 1,
    explanation: "Jaswant Singh left the details to the Agriculture Ministry. The same rural package promised Kisan Credit Cards to all eligible farmers by 31 March 2004, ATM-enabled cards on request, and a plan of about ₹15,000 crore, shared by the Centre and states, to revive cooperative credit.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2004-05(I)/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Interim Budget 2004-05 speech, Jaswant Singh (3 Feb 2004)",
    sources: ["https://m.economictimes.com/news/economy/policy/government-to-introduce-farm-income-insurance-scheme-agriculture-minister/articleshow/41716346.cms"],
    tags: ["pre-election"],
    enactedBy: [{ name: "Jaswant Singh", role: "Union Finance Minister", party: "BJP" }],
    outcome: "The Economic Times (2014) says the pilot ran in 2003-04 in 22 districts of 14 states and was discontinued in 2004. The NDA lost the 2004 poll; in 2014 Agriculture Minister Radha Mohan Singh proposed reviving farm income insurance.",
    poll: { label: "Lok Sabha 2004", month: "2004-04", result: "INC 145, BJP 138 seats; the Congress-led UPA formed the government", gapDays: 77 },
  },
  {
    id: "hpe006",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Elections & Funding",
    subtopic: "Early Lok Sabha poll (2004)",
    kind: "institution",
    difficulty: "simple",
    year: 2004,
    asOf: "2026-09",
    govt: "NDA",
    question: "Buoyed by Assembly wins in late 2003, the Vajpayee government advanced the 14th Lok Sabha election. Roughly how far ahead of schedule was it held?",
    options: ["About two weeks", "About two months", "Nearly six months", "More than a year"],
    correctIndex: 2,
    explanation: "The 1999 election was held in September–October, so the next was due in late 2004. The Indian Express says the NDA dissolved the House early, encouraged by Assembly wins (The Hindu names Madhya Pradesh, Rajasthan and Chhattisgarh), and voting took place in April–May, nearly six months early. President Kalam dissolved the 13th Lok Sabha on 6 February 2004 (The Hindu).",
    sourceUrl: "https://indianexpress.com/article/political-pulse/bjp-india-shining-rajnath-singh-8925418/",
    sourceLabel: "The Indian Express — Why Rajnath called INDIA name khatarnaak: BJP's 'India Shining' dark spot (5 Sep 2023)",
    sources: ["https://www.thehindu.com/news/national/congress-upa-india-elections-2004-2009-politics-explainer-sonia-manmohan-vajpayee-nada-coalition-alliance/article68023875.ece"],
    tags: ["pre-election"],
    enactedBy: [{ name: "Atal Bihari Vajpayee", role: "Prime Minister", party: "BJP" }],
    outcome: "Polling began 74 days after the dissolution. Counting on 13 May gave the Congress 145 seats (26.53% of the vote) to the BJP’s 138 (22.16%); the Congress-led UPA formed the government (The Hindu).",
    poll: { label: "Lok Sabha 2004", month: "2004-04", result: "INC 145, BJP 138 seats; the Congress-led UPA formed the government", gapDays: 74 },
  },
  // ───────────────────────────── 2005–2009 ─────────────────────────────
  {
    id: "hpe007",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Income-tax exemption limit (2008)",
    kind: "spend",
    difficulty: "expert",
    year: 2008,
    asOf: "2026-09",
    govt: "UPA",
    question: "In the UPA's last full budget before the 2009 polls (29 Feb 2008), P. Chidambaram raised the basic income-tax exemption limit from ₹1.1 lakh to what?",
    options: ["₹1.25 lakh", "₹1.4 lakh", "₹1.75 lakh", "₹1.5 lakh"],
    correctIndex: 3,
    explanation: "He said taxpayers had made a persuasive case for relief; every assessee gained at least ₹4,000. The limit for women rose from ₹1.45 lakh to ₹1.8 lakh and for senior citizens from ₹1.95 lakh to ₹2.25 lakh. The same budget announced the farm debt waiver and a health cover scheme for poor workers.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2008-09/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2008-09, P. Chidambaram (29 Feb 2008)",
    sources: ["https://www.thehindu.com/news/national/congress-upa-india-elections-2004-2009-politics-explainer-sonia-manmohan-vajpayee-nada-coalition-alliance/article68023875.ece"],
    tags: ["pre-election"],
    enactedBy: [{ name: "P. Chidambaram", role: "Union Finance Minister", party: "INC" }],
    outcome: "Polling began 412 days later; the Congress won 206 seats, its best since 1991, and the UPA returned (The Hindu). The cited sources make no causal claim.",
    poll: { label: "Lok Sabha 2009", month: "2009-04", result: "INC won 206 seats, its best since 1991; the Congress-led UPA returned to power", gapDays: 412 },
  },
  {
    id: "hpe008",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "Rashtriya Swasthya Bima Yojana (2008)",
    kind: "scheme",
    difficulty: "simple",
    year: 2008,
    asOf: "2026-09",
    govt: "UPA",
    question: "Budget 2008-09 said the new Rashtriya Swasthya Bima Yojana would give the family of each BPL worker in the unorganised sector health cover of how much?",
    options: ["₹30,000", "₹1 lakh", "₹5 lakh", "₹10,000"],
    correctIndex: 0,
    explanation: "Chidambaram said most states had agreed to join and it would launch in Delhi, Haryana and Rajasthan on 1 April 2008, with ₹205 crore as the Centre's share of premiums in 2008-09. Beneficiaries could use a list of hospitals that included private ones.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2008-09/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2008-09, P. Chidambaram (29 Feb 2008)",
    sources: ["https://www.indiabudget.gov.in/budget_archive/ub2009-10/bs/speecha.htm"],
    tags: ["pre-election", "distribution"],
    enactedBy: [{ name: "P. Chidambaram", role: "Union Finance Minister", party: "INC" }],
    outcome: "By the July 2009 budget, more than 46 lakh BPL families in 18 states and UTs held RSBY biometric smart cards, and its 2009-10 allocation rose 40% to ₹350 crore.",
    poll: { label: "Lok Sabha 2009", month: "2009-04", result: "INC won 206 seats, its best since 1991; the Congress-led UPA returned to power", gapDays: 412 },
  },
  {
    id: "hpe009",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Sixth Pay Commission award",
    kind: "spend",
    difficulty: "extreme",
    year: 2009,
    asOf: "2026-09",
    govt: "UPA",
    question: "Pranab Mukherjee's interim budget of Feb 2009 said the Sixth Pay Commission award, accepted in Aug 2008, benefited over 45 lakh central employees and how many pensioners?",
    options: ["Over 12 lakh", "Over 38 lakh", "Over 80 lakh", "Over 1 crore"],
    correctIndex: 1,
    explanation: "The speech said the government 'considered and improved upon' the Commission's March 2008 recommendations, covering the defence and paramilitary forces too. Mint notes the award, accepted in August 2008, revised pay from 1 January 2006 and set the minimum monthly pay at ₹7,000.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2009-10(I)/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Interim Budget 2009-10 speech, Pranab Mukherjee (16 Feb 2009)",
    sources: [
      "https://www.livemint.com/money/personal-finance/8th-pay-commission-to-be-implemented-by-2028-here-s-how-previous-commissions-were-rolled-out-11758981893461.html",
      "https://www.indiabudget.gov.in/budget_archive/ub2009-10/bs/speecha.htm",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Pranab Mukherjee", role: "Union Finance Minister", party: "INC" }],
    outcome: "The July 2009 budget said non-plan spending rose mainly because of the pay award, food subsidy and higher interest. The UPA had returned that May with the Congress at 206 seats.",
    poll: { label: "Lok Sabha 2009", month: "2009-04", result: "INC won 206 seats, its best since 1991; the Congress-led UPA returned to power" },
  },
  {
    id: "hpe010",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "Interim Railway Budget 2009",
    kind: "spend",
    difficulty: "expert",
    year: 2009,
    asOf: "2026-09",
    govt: "UPA",
    question: "Two months before the 2009 polls, Lalu Prasad's interim Railway Budget cut passenger fares across the board by how much?",
    options: ["1%", "5%", "2%", "10%"],
    correctIndex: 2,
    explanation: "The Indian Express said the across-the-board cut would lower passenger earnings by about ₹700 crore, against ₹250 crore forgone on his flexible cuts of 2008-09, and called it his only contribution to the stimulus. He refused freight cuts and cited a five-year cash surplus of about ₹90,000 crore.",
    sourceUrl: "https://indianexpress.com/article/india/india-others/2-fare-cut-is-the-only-lalu-stimulus/",
    sourceLabel: "The Indian Express — 2% fare cut is the only Lalu stimulus (13 Feb 2009)",
    sources: ["https://www.thehindu.com/news/national/congress-upa-india-elections-2004-2009-politics-explainer-sonia-manmohan-vajpayee-nada-coalition-alliance/article68023875.ece"],
    tags: ["pre-election"],
    enactedBy: [{ name: "Lalu Prasad", role: "Union Railway Minister", party: "RJD" }],
    outcome: "Polling began 62 days later; the UPA returned to power with the Congress at 206 seats (The Hindu).",
    poll: { label: "Lok Sabha 2009", month: "2009-04", result: "INC won 206 seats, its best since 1991; the Congress-led UPA returned to power", gapDays: 62 },
  },
  {
    id: "hpe011",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Excise cuts and stimulus (2008–09)",
    kind: "spend",
    difficulty: "extreme",
    year: 2009,
    asOf: "2026-09",
    govt: "UPA",
    question: "Between 7 Dec 2008 and 24 Feb 2009, the UPA cut the ad valorem central excise (CENVAT) rate on non-petroleum goods by how many percentage points in all?",
    options: ["2", "4", "8", "6"],
    correctIndex: 3,
    explanation: "The July 2009 budget speech records a 4-point cut across the board on 7 Dec 2008 and a further 2-point cut in the mean CENVAT rate on 24 Feb 2009, 51 days before polling. With the other stimulus steps, the fiscal deficit rose from 2.7% of GDP in 2007-08 to 6.2% in 2008-09, a stimulus of ₹1,86,000 crore.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2009-10/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2009-10, Pranab Mukherjee (6 Jul 2009)",
    sources: ["https://www.indiabudget.gov.in/budget_archive/ub2009-10(I)/bs/speecha.htm"],
    tags: ["pre-election"],
    outcome: "Pranab Mukherjee told Parliament the measures helped arrest the slowdown, with growth of 6.7% in 2008-09. The UPA had been re-elected in May with the Congress at 206 seats.",
    poll: { label: "Lok Sabha 2009", month: "2009-04", result: "INC won 206 seats, its best since 1991; the Congress-led UPA returned to power", gapDays: 51 },
  },
  {
    id: "hpe012",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "NREGS allocation (interim 2009)",
    kind: "scheme",
    difficulty: "extreme",
    year: 2009,
    asOf: "2026-09",
    govt: "UPA",
    question: "Pranab Mukherjee's interim budget of 16 February 2009 allocated how much to the rural jobs guarantee scheme (NREGS) for 2009-10?",
    options: ["₹30,100 crore", "₹11,700 crore", "₹60,000 crore", "₹1 lakh crore"],
    correctIndex: 0,
    explanation: "He said NREGS, launched in February 2006 and now extended to every district, had generated 138.76 crore person-days of work for 3.51 crore households in 2008-09. The same speech gave ₹12,070 crore to the National Rural Health Mission.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2009-10(I)/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Interim Budget 2009-10 speech, Pranab Mukherjee (16 Feb 2009)",
    sources: ["https://www.thehindu.com/news/national/congress-upa-india-elections-2004-2009-politics-explainer-sonia-manmohan-vajpayee-nada-coalition-alliance/article68023875.ece"],
    tags: ["pre-election", "distribution"],
    enactedBy: [{ name: "Pranab Mukherjee", role: "Union Finance Minister", party: "INC" }],
    outcome: "Polling began 59 days later and the UPA returned, with the Congress at 206 seats (The Hindu); the cited sources make no causal claim.",
    poll: { label: "Lok Sabha 2009", month: "2009-04", result: "INC won 206 seats, its best since 1991; the Congress-led UPA returned to power", gapDays: 59 },
  },
  // ───────────────────────────── 2010–2014 ─────────────────────────────
  {
    id: "hpe013",
    domain: "civics",
    region: "India",
    state: "WB",
    topic: "Education & Exams",
    subtopic: "IIT Kharagpur grant (Budget 2011)",
    kind: "spend",
    difficulty: "expert",
    year: 2011,
    asOf: "2026-09",
    govt: "UPA",
    question: "Pranab Mukherjee's Budget 2011-12, presented weeks before West Bengal voted, made a one-time grant of ₹200 crore to which institution?",
    options: ["IIM Calcutta", "Visva-Bharati", "IIT Kharagpur", "Jadavpur University"],
    correctIndex: 2,
    explanation: "The same list gave ₹20 crore to IIM Kolkata for a trading lab and ₹10 crore for a Kolkata centre of the Wardha Hindi university; the budget also promised aid for Kolkata's metro and ₹400 crore more for the eastern green-revolution programme for rice farming in Assam, West Bengal and five others. The Indian Express (2026) lists the grant among UPA sops for poll-bound states.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2011-2012/ub2011-12/bs/bs.pdf",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2011-12, Pranab Mukherjee (28 Feb 2011)",
    sources: [
      "https://indianexpress.com/article/political-pulse/no-big-ticket-sops-poll-bound-states-budget-2026-unlike-previous-years-10507670/",
      "https://www.aljazeera.com/opinions/2011/5/18/the-end-of-an-era-in-west-bengal-and-india",
      "https://www.bbc.com/news/world-south-asia-13374646",
      "https://m.economictimes.com/news/elections/assembly-elections/west-bengal/west-bengal-2026-election-bjp-tmc-mamata-banerjee-modi-political-shift-didi-down-but-not-out/articleshow/130780575.cms",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Pranab Mukherjee", role: "Union Finance Minister", party: "INC" }],
    outcome: "Voting ran over April and May (BBC). Mamata Banerjee's Trinamool Congress won 184 of 294 seats and the Left Front fell from 235 to 61, ending 34 years of Left rule (Al Jazeera, Economic Times). No cited source ties the result to the budget.",
    poll: { label: "West Bengal Assembly 2011", month: "2011-04", result: "Trinamool Congress won 184 of 294 seats; Left Front fell to 61, ending 34 years in power" },
  },
  {
    id: "hpe014",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Elections & Funding",
    subtopic: "Budget 2012 held back for state polls",
    kind: "institution",
    difficulty: "expert",
    year: 2012,
    asOf: "2026-09",
    govt: "UPA",
    question: "The UPA presented the 2012 Union Budget on 16 March, after Assembly polls in five states. According to then-CEC S.Y. Quraishi, who decided to hold it back?",
    options: ["The Election Commission, by order", "The government, on its own", "The Supreme Court", "The Lok Sabha Speaker"],
    correctIndex: 1,
    explanation: "Quraishi told Scroll in 2017 that the UPA moved the Budget to 16 March 'on its own', ostensibly after Opposition demands, without the EC coming into the picture; he said it relieved the EC because some phases fell in early March. In 2017 the NDA kept its 1 February date despite five state polls.",
    sourceUrl: "https://scroll.in/article/826287/i-am-hopeful-that-the-prime-minister-will-postpone-the-budget-sy-quraishi",
    sourceLabel: "Scroll — 'I am hopeful that prime minister will postpone the Budget': SY Quraishi (10 Jan 2017)",
    sources: [
      "https://frontline.thehindu.com/cover-story/article30164875.ece",
      "https://www.thehindu.com/elections/uttar-pradesh-2017/bjp-rides-modi-wave-to-win-big-in-up/article17449593.ece",
      "https://e-pao.net/GP.asp?src=18..251211.dec11",
    ],
    tags: ["pre-election"],
    outcome: "UP's seven-phase poll opened in February (e-pao, Dec 2011) and ran into early March (Quraishi). The Samajwadi Party won outright with 224 seats in the 403-member House (Frontline; The Hindu); the Budget followed on 16 March, after the results.",
    poll: { label: "Uttar Pradesh Assembly 2012", month: "2012-02", result: "SP won Uttar Pradesh with 224 of 403 seats" },
  },
  {
    id: "hpe015",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Elections & Funding",
    subtopic: "Freebies ruling and manifesto code (2013)",
    kind: "institution",
    difficulty: "expert",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "In July 2013 the Supreme Court said poll freebies 'shake the root of free and fair elections to a large degree'. What did it direct the Election Commission to do?",
    options: ["Disqualify parties that promise freebies", "Cap state spending on welfare schemes", "Audit every state welfare budget", "Frame guidelines on manifestos with the parties"],
    correctIndex: 3,
    explanation: "In S. Subramaniam Balaji v Tamil Nadu, over colour TVs first promised in the DMK's 2006 manifesto, Justices P. Sathasivam and Ranjan Gogoi asked the EC to frame manifesto guidelines in consultation with parties 'as early as possible' and recorded the need for a separate law governing parties.",
    sourceUrl: "https://indiankanoon.org/doc/106854428/",
    sourceLabel: "Indian Kanoon — S. Subramaniam Balaji vs Govt of Tamil Nadu, Supreme Court (5 Jul 2013)",
    sources: [
      "https://www.hindustantimes.com/analysis/legally-speaking-can-political-parties-be-held-legally-accountable-for-unfulfilled-manifestos-101713972832571.html",
      "https://indianexpress.com/article/political-pulse/india-goes-to-poll-in-9-phases-from-april-7-to-may-12-vote-count-on-may-16/",
    ],
    tags: ["pre-election"],
    outcome: "The EC added Part VIII to the Model Code, asking manifestos to explain the rationale for promises and how they will be funded. Hindustan Times notes the guidelines are not law and cannot be enforced.",
    poll: { label: "Lok Sabha 2014", month: "2014-04", result: "BJP won 282 of 543 seats; the UPA lost office", gapDays: 276 },
  },
  {
    id: "hpe016",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Farm debt waiver 2008: CAG audit",
    kind: "scheme",
    difficulty: "extreme",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "The CAG's March 2013 audit of the UPA's 2008 farm debt waiver found what share of 80,299 test-checked beneficiary accounts were not eligible?",
    options: ["About 8.5%", "About 1.5%", "About 3.5%", "About 40%"],
    correctIndex: 0,
    explanation: "The audit also found that 13.46% of 9,334 test-checked accounts were eligible but left out by lenders, and prima facie evidence of tampering with records. Finance Minister P. Chidambaram said action would follow against erring banks and ineligible recipients after inquiries, calling it 'unfortunate that some deserving farmers did not get benefit'.",
    status: "CAG audit findings on lenders' and the Finance Ministry's implementation (tabled 5 Mar 2013); no finding against any named person. The ministry said erring banks and ineligible beneficiaries would face action after inquiries.",
    people: ["P. Chidambaram"],
    otherSide:
      "Finance Minister P. Chidambaram said action would follow against erring banks and ineligible recipients after inquiries, calling it 'unfortunate that some deserving farmers did not get benefit'.",
    sourceUrl: "https://www.thehindu.com/news/national/sloppy-loan-waiver-edges-out-deserving-farmers-cag/article4478433.ece",
    sourceLabel: "The Hindu — Sloppy loan waiver edges out deserving farmers: CAG (5 Mar 2013)",
    sources: [
      "https://m.economictimes.com/news/politics-and-nation/cag-finds-scam-in-rs-52000-crore-farm-loan-waiver-scheme/articleshow/18810542.cms",
      "https://www.indiabudget.gov.in/budget_archive/ub2008-09/bs/speecha.htm",
    ],
    tags: ["pre-election", "distribution"],
    enactedBy: [{ name: "P. Chidambaram", role: "Union Finance Minister", party: "INC" }],
    outcome: "The Hindu called it a ₹52,000-crore scheme. RBI and NABARD told banks to identify errors and act against erring banks and ineligible beneficiaries (Economic Times).",
    poll: { label: "Lok Sabha 2009", month: "2009-04", result: "INC won 206 seats, its best since 1991; the Congress-led UPA returned to power", gapDays: 412 },
  },
  {
    id: "hpe017",
    domain: "civics",
    region: "India",
    state: "CT",
    topic: "Farm & Food",
    subtopic: "Budget 2013: Raipur institute",
    kind: "spend",
    difficulty: "extreme",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "Budget 2013-14, presented in a year Chhattisgarh went to the polls, said a new National Institute of Biotic Stress Management would be set up in which city?",
    options: ["Bhopal", "Raipur", "Ranchi", "Bilaspur"],
    correctIndex: 1,
    explanation: "P. Chidambaram also sited an Indian Institute of Agricultural Biotechnology at Ranchi and gave ₹1,000 crore to keep supporting the eastern 'green revolution' states, which he said included Chhattisgarh. The Indian Express (2026) counts Chhattisgarh as a focus of the UPA's last full budget, in a year with nine state elections.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2013-2014/ub2013-14/bs/bs.pdf",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2013-14, P. Chidambaram (28 Feb 2013)",
    sources: [
      "https://indianexpress.com/article/political-pulse/no-big-ticket-sops-poll-bound-states-budget-2026-unlike-previous-years-10507670/",
      "https://www.rediff.com/news/report/assembly-poll-chhattisgarh-bastar-stands-by-congress-plains-back-bjp-in-chhattisgarh/20131209.htm",
      "https://www.thehindu.com/news/national/other-states/chhattisgarh-polls-1-jawan-for-31-civilians-in-bastar/article5221275.ece",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "P. Chidambaram", role: "Union Finance Minister", party: "INC" }],
    outcome: "In a two-phase poll that November (The Hindu), the BJP retained Chhattisgarh with 49 of 90 seats to the Congress's 39, giving Raman Singh a third term (Rediff).",
    poll: { label: "Chhattisgarh Assembly 2013", month: "2013-11", result: "BJP retained power with 49 of 90 seats; Congress 39" },
  },
  {
    id: "hpe018",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Seventh Pay Commission announced (2013)",
    kind: "spend",
    difficulty: "expert",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "Announcing the Seventh Pay Commission on 25 September 2013, months before the Lok Sabha poll, P. Chidambaram said its award would likely take effect from when?",
    options: ["1 April 2014", "1 January 2017", "1 January 2016", "1 April 2018"],
    correctIndex: 2,
    explanation: "The Economic Times reported the announcement came 'ahead of elections', raising prospects of rises for nearly 80 lakh employees and pensioners. Chidambaram said PM Manmohan Singh had approved it and that pay panels took about two years to report; five states were to vote that November.",
    sourceUrl: "https://m.economictimes.com/news/economy/policy/government-announces-seventh-central-pay-commission/articleshow/23038399.cms",
    sourceLabel: "The Economic Times — Government announces Seventh Central Pay Commission (26 Sep 2013)",
    sources: [
      "https://www.livemint.com/money/personal-finance/8th-pay-commission-to-be-implemented-by-2028-here-s-how-previous-commissions-were-rolled-out-11758981893461.html",
      "https://www.dw.com/en/india-election-whats-behind-the-bjps-poll-upset/a-69277403",
      "https://indianexpress.com/article/political-pulse/india-goes-to-poll-in-9-phases-from-april-7-to-may-12-vote-count-on-may-16/",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "P. Chidambaram", role: "Union Finance Minister", party: "INC" }, { name: "Manmohan Singh", role: "Prime Minister", party: "INC" }],
    outcome: "The UPA lost the 2014 poll. The NDA government approved the Commission’s report in June 2016 with effect from January 2016, as Chidambaram had projected (Mint).",
    poll: { label: "Lok Sabha 2014", month: "2014-04", result: "BJP won 282 of 543 seats; the UPA lost office", gapDays: 194 },
  },
  {
    id: "hpe019",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Energy & Mining",
    subtopic: "LPG cylinder cap raised (2014)",
    kind: "scheme",
    difficulty: "simple",
    year: 2014,
    asOf: "2026-09",
    govt: "UPA",
    question: "On 30 January 2014, a fortnight after Rahul Gandhi said 'nine cylinders are not enough', the UPA raised the yearly cap on subsidised LPG cylinders from nine to how many?",
    options: ["10", "15", "No cap", "12"],
    correctIndex: 3,
    explanation: "Oil Minister M. Veerappa Moily put the extra subsidy at ₹5,000 crore a year. The same day the Aadhaar-linked cash transfer of the LPG subsidy (DBTL) in 289 districts was put on hold pending review, after complaints from consumers without linked accounts. Minister Manish Tewari said: 'It's not an election-related decision.'",
    sourceUrl: "https://indianexpress.com/article/india/india-others/cabinet-accepts-rahul-gandhis-lpg-subsidy-demand-increases-cap-from-9-to-12/",
    sourceLabel: "The Indian Express — Govt suspends LPG subsidy transfer scheme; hikes cylinder quota from 9 to 12 (30 Jan 2014)",
    sources: [
      "https://www.livemint.com/Politics/tN6NwWEqhsuQA65pdZDHWI/LPG-subsidy-cap-raised-from-9-to-12.html",
      "https://www.dw.com/en/india-election-whats-behind-the-bjps-poll-upset/a-69277403",
      "https://indianexpress.com/article/political-pulse/india-goes-to-poll-in-9-phases-from-april-7-to-may-12-vote-count-on-may-16/",
    ],
    tags: ["pre-election", "distribution"],
    enactedBy: [{ name: "M. Veerappa Moily", role: "Union Petroleum Minister", party: "INC" }],
    outcome: "Mint called it another 'bow to populism' with the general election three months away. Polling began 67 days later and the BJP won 282 of 543 seats.",
    poll: { label: "Lok Sabha 2014", month: "2014-04", result: "BJP won 282 of 543 seats; the UPA lost office", gapDays: 67 },
  },
  {
    id: "hpe020",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Interim Budget 2014: excise cuts",
    kind: "spend",
    difficulty: "extreme",
    year: 2014,
    asOf: "2026-09",
    govt: "UPA",
    question: "P. Chidambaram's interim budget of 17 Feb 2014 cut excise on small cars, motorcycles and scooters from 12% to what, for the period up to 30 June 2014?",
    options: ["8%", "10%", "6%", "4%"],
    correctIndex: 0,
    explanation: "Citing 'unprecedented negative growth' in the auto industry, he also cut excise on SUVs from 30% to 24% and on large and mid-segment cars from 27/24% to 24/20%, and on capital goods and consumer non-durables from 12% to 10%, leaving the rates to be reviewed in the regular budget.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2014-2015(I)/ub2014-15/bs/bs.pdf",
    sourceLabel: "indiabudget.gov.in — Interim Budget 2014-15 speech, P. Chidambaram (17 Feb 2014)",
    sources: [
      "https://www.dw.com/en/india-election-whats-behind-the-bjps-poll-upset/a-69277403",
      "https://indianexpress.com/article/political-pulse/india-goes-to-poll-in-9-phases-from-april-7-to-may-12-vote-count-on-may-16/",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "P. Chidambaram", role: "Union Finance Minister", party: "INC" }],
    outcome: "Polling began 49 days later; the UPA lost office and the BJP won 282 of 543 seats (DW).",
    poll: { label: "Lok Sabha 2014", month: "2014-04", result: "BJP won 282 of 543 seats; the UPA lost office", gapDays: 49 },
  },
  // ───────────────────────────── 2015–2019 ─────────────────────────────
  {
    id: "hpe021",
    domain: "civics",
    region: "India",
    state: "BR",
    topic: "Infrastructure",
    subtopic: "Bihar special package: Nitish's challenge (2015)",
    kind: "spend",
    difficulty: "extreme",
    year: 2015,
    asOf: "2026-09",
    govt: "NDA",
    question: "Writing to Arun Jaitley in September 2015, how much of Modi's ₹1.25-lakh-crore Bihar package did CM Nitish Kumar say was money already promised to the state?",
    options: ["₹60,000 crore", "₹1.08 lakh crore", "₹25,000 crore", "₹85,000 crore"],
    correctIndex: 1,
    explanation: "Nitish called it a 'packaged myth' of old schemes devised to influence people and asked when the money would arrive. Announcing it at Ara on 18 August, Modi said it would change Bihar's 'face and fate', put the total at ₹1.65 lakh crore with ₹40,000 crore of ongoing projects, and faulted Nitish's government for poorly using central funds (The Hindu).",
    sourceUrl: "https://www.thehindu.com/elections/bihar2015/PM%E2%80%99s-package-a-myth-to-influence-people-Nitish-to-Jaitley/article60210557.ece",
    sourceLabel: "The Hindu — PM’s package a myth: Nitish (8 Sep 2015)",
    sources: [
      "https://www.thehindu.com/news/national/other-states/modi-at-bihar-rally/article7553558.ece",
      "https://indianexpress.com/article/india/india-news-india/bihar-election-results-live-nda-grand-alliance/",
      "https://www.bbc.com/news/world-asia-india-34483506",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "The JD(U)–RJD–Congress alliance won 178 of 243 seats; the BJP-led NDA got 58 despite Modi addressing more than 30 rallies (The Indian Express).",
    poll: { label: "Bihar Assembly 2015", month: "2015-10", gapDays: 55, result: "JD(U)–RJD–Congress alliance won 178 of 243 seats; BJP 53" },
  },
  {
    id: "hpe022",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Defence & Security",
    subtopic: "One Rank One Pension (2015)",
    kind: "scheme",
    difficulty: "expert",
    year: 2015,
    asOf: "2026-09",
    govt: "NDA",
    question: "Announcing One Rank One Pension on 5 September 2015, weeks before Bihar voted, Defence Minister Manohar Parrikar said pensions would be re-fixed how often?",
    options: ["Every year", "Every two years", "Every three years", "Every five years"],
    correctIndex: 3,
    explanation: "Effective from 1 July 2014 on a 2013 base, Parrikar put its cost at ₹8,000–10,000 crore, rising in future, with arrears of ₹10,000–12,000 crore; Parrikar said the UPA had budgeted a 'mere ₹500 crore'. Agitating veterans wanted revision every two years and cover for premature retirees; their leader called the move a 'gimmick' ahead of the Bihar polls.",
    sourceUrl: "https://www.rediff.com/news/report/government-announces-one-rank-one-pension-for-ex-servicemen/20150905.htm",
    sourceLabel: "Rediff — Govt announces OROP but unhappy veterans to continue agitation (5 Sep 2015)",
    sources: [
      "https://indianexpress.com/article/india/india-news-india/bihar-election-results-live-nda-grand-alliance/",
      "https://www.bbc.com/news/world-asia-india-34483506",
    ],
    tags: ["pre-election", "distribution"],
    enactedBy: [{ name: "Manohar Parrikar", role: "Union Defence Minister", party: "BJP" }],
    outcome: "About 26 lakh retired service personnel and over 6 lakh war widows were to benefit, but the veterans kept up their agitation. Polling began 37 days later and the NDA won only 58 of 243 seats.",
    poll: { label: "Bihar Assembly 2015", month: "2015-10", result: "JD(U)–RJD–Congress alliance won 178 of 243 seats; BJP 53", gapDays: 37 },
  },
  {
    id: "hpe023",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Elections & Funding",
    subtopic: "Budget 2017 and the five-state polls",
    kind: "institution",
    difficulty: "simple",
    year: 2017,
    asOf: "2026-09",
    govt: "NDA",
    question: "Hours after the Supreme Court refused to stop the 1 February 2017 Union Budget, days before five states began voting, what did the Election Commission tell the government?",
    options: ["Postpone the Budget to March", "Clear the Budget speech with the EC first", "Announce no schemes specific to those states", "Make no tax changes at all"],
    correctIndex: 2,
    explanation: "The EC said no state-specific scheme that could sway voters in the five poll-bound states should be announced, and the government's achievements there should not be highlighted in the speech. Citing its 2009 advisory, it also advised the poll-bound states themselves to take votes on account. Ex-CEC S.Y. Quraishi had urged a postponement.",
    sourceUrl: "https://timesofindia.indiatimes.com/elections/news/dont-announce-any-scheme-for-poll-bound-states-in-union-budget-ec-tells-government/articleshow/56742740.cms",
    sourceLabel: "Times of India — Don't announce any scheme for poll-bound states in Union Budget, EC tells government (23 Jan 2017)",
    sources: [
      "https://scroll.in/article/826287/i-am-hopeful-that-the-prime-minister-will-postpone-the-budget-sy-quraishi",
      "https://www.thehindu.com/elections/uttar-pradesh-2017/bjp-rides-modi-wave-to-win-big-in-up/article17449593.ece",
    ],
    tags: ["pre-election"],
    outcome: "Polling began three days after the Budget. The BJP took 312 of 403 seats in Uttar Pradesh and 57 of 70 in Uttarakhand, while Punjab returned the Congress to power (The Hindu).",
    poll: { label: "Assembly polls in UP, Punjab and 3 other states, 2017", month: "2017-02", gapDays: 3, result: "BJP won UP with 312 of 403 seats; Congress won Punjab" },
  },
  {
    id: "hpe024",
    domain: "civics",
    region: "India",
    state: "GJ",
    topic: "Health",
    subtopic: "Budget 2017: new AIIMS",
    kind: "spend",
    difficulty: "simple",
    year: 2017,
    asOf: "2026-09",
    govt: "NDA",
    question: "Arun Jaitley's Budget 2017-18, presented in the year Gujarat went to the polls, announced two new All India Institutes of Medical Sciences. In which two states?",
    options: ["Gujarat and Jharkhand", "Gujarat and Assam", "Bihar and Jharkhand", "Gujarat and Odisha"],
    correctIndex: 0,
    explanation: "The speech of 1 February 2017 said the two new AIIMS would come up in Jharkhand and Gujarat. The Indian Express (2026) notes Gujarat was the only one of the seven states voting that year to get a special mention in the Budget.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2017-2018/ub2017-18/bs/bs.pdf",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2017-18, Arun Jaitley (1 Feb 2017)",
    sources: [
      "https://indianexpress.com/article/political-pulse/no-big-ticket-sops-poll-bound-states-budget-2026-unlike-previous-years-10507670/",
      "https://frontline.thehindu.com/cover-story/distress-vote/article9997561.ece",
      "https://www.pib.gov.in/newsite/printrelease.aspx?relid=173944",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Arun Jaitley", role: "Union Finance Minister", party: "BJP" }],
    outcome: "The BJP kept Gujarat but fell to 99 of 182 seats, below the 105–110 most surveys predicted, as the Congress won 77 (Frontline).",
    poll: { label: "Gujarat Assembly 2017", month: "2017-12", gapDays: 311, result: "BJP won 99 of 182 seats; Congress 77" },
  },
  {
    id: "hpe025",
    domain: "civics",
    region: "India",
    state: "KA",
    topic: "Infrastructure",
    subtopic: "Bengaluru suburban rail (Budget 2018)",
    kind: "spend",
    difficulty: "extreme",
    year: 2018,
    asOf: "2026-09",
    govt: "NDA",
    question: "Arun Jaitley's Budget 2018-19, about 100 days before Karnataka voted, planned a 160-km suburban rail network for Bengaluru at an estimated cost of how much?",
    options: ["₹5,000 crore", "₹11,000 crore", "₹17,000 crore", "₹40,000 crore"],
    correctIndex: 2,
    explanation: "The same paragraph planned 150 km more of Mumbai's suburban network at over ₹40,000 crore. The Indian Express (2026) says the Bengaluru line was that Budget's allocation 'ahead of the Karnataka elections', with no announcements for the eight other states voting that year.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2018-2019/ub2018-19/bs/bs.pdf",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2018-19, Arun Jaitley (1 Feb 2018)",
    sources: [
      "https://indianexpress.com/article/political-pulse/no-big-ticket-sops-poll-bound-states-budget-2026-unlike-previous-years-10507670/",
      "https://www.thehindu.com/elections/karnataka-2018/cong-backs-jds-as-bjp-falls-short-in-karnataka/article61835741.ece",
      "https://www.thehindu.com/elections/karnataka-2018/2018-karnataka-assembly-election-voting-live-updates/article23854998.ece",
      "https://www.deccanherald.com/india/karnataka/bengaluru/bengaluru-suburban-rail-faces-march-2030-deadline-with-just-1995-work-done-2-4109191",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Arun Jaitley", role: "Union Finance Minister", party: "BJP" }],
    outcome: "Karnataka returned a hung House with the BJP largest on 104 seats (The Hindu). By August 2026 the suburban line was 19.95% built against a March 2030 deadline (Deccan Herald).",
    poll: { label: "Karnataka Assembly 2018", month: "2018-05", gapDays: 100, result: "Hung House: BJP 104 of 224, Congress 78, JD(S) 37" },
  },
  {
    id: "hpe026",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "Ayushman Bharat PM-JAY launch (2018)",
    kind: "scheme",
    difficulty: "simple",
    year: 2018,
    asOf: "2026-09",
    govt: "NDA",
    question: "In which city did PM Narendra Modi launch Ayushman Bharat PM-JAY on 23 September 2018, seven weeks before five states began voting?",
    options: ["Varanasi", "Raipur", "Bhopal", "Ranchi"],
    correctIndex: 3,
    explanation: "At the city's Prabhat Tara ground he said the scheme's yearly family health cover, usable in government or empanelled private hospitals, would reach 10.74 crore families, about 50 crore people. Chhattisgarh voted from 12 November; four other states followed.",
    sourceUrl: "https://www.thehindu.com/news/national/pm-modi-launches-ayushman-bharat-scheme/article25020146.ece",
    sourceLabel: "The Hindu — PM Modi launches Ayushman Bharat healthcare scheme (23 Sep 2018)",
    sources: [
      "https://scroll.in/article/901189/scroll-explainer-everything-you-need-to-know-about-chhattisgarh-assembly-elections",
      "https://scroll.in/latest/905381/assembly-election-results-congress-wins-114-seats-in-mp-party-expected-to-pick-rajasthan-cm-today",
    ],
    tags: ["pre-election", "distribution"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "In December the Congress won Madhya Pradesh (114 of 230), Rajasthan (99 of 199) and Chhattisgarh from the BJP (Scroll). No cited source links the result to PM-JAY.",
    poll: { label: "Assembly polls in 5 states, Nov–Dec 2018", month: "2018-11", gapDays: 50, result: "Congress won Madhya Pradesh (114 of 230), Rajasthan (99 of 199) and Chhattisgarh" },
  },
  {
    id: "hpe027",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "10% EWS quota amendment (2019)",
    kind: "institution",
    difficulty: "extreme",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "The 10% quota bill for economically weaker sections cleared the Lok Sabha on 8 January 2019, three months before the general election. How many MPs voted against it?",
    options: ["None", "3", "17", "44"],
    correctIndex: 1,
    explanation: "It passed 323–3, and the Rajya Sabha approved it 165–7 a day later, with the DMK and IUML opposed. Social Justice Minister Thaawarchand Gehlot replied to the debate; the Congress's K.V. Thomas said the aim was the coming polls after the BJP's recent state defeats. Gehlot said the government's intention was good.",
    sourceUrl: "https://www.livemint.com/Politics/f8v46qvKEfV9lKm4QUmfHI/Lok-Sabha-clears-quota-bill-with-nearfull-majority.html",
    sourceLabel: "Mint — Quota bill passed in Lok Sabha with near unanimous vote (8 Jan 2019)",
    sources: [
      "https://timesofindia.indiatimes.com/india/quota-bill-gets-rajya-sabha-nod-too-set-to-become-law/articleshow/67462415.cms",
      "https://timesofindia.indiatimes.com/india/lok-sabha-passes-bill-to-provide-10-quota-to-general-category-poor/articleshow/67443212.cms",
      "https://frontline.thehindu.com/news/supreme-court-holds-103rd-constitution-amendment-providing-10-per-cent-ews-reservation-valid/article66106637.ece",
      "https://scroll.in/latest/915713/2019-general-elections-voting-to-be-held-in-seven-phases-to-start-on-april-11",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Thaawarchand Gehlot", role: "Union Social Justice Minister", party: "BJP" }],
    outcome: "Polling began 93 days after the Lok Sabha vote and the BJP won 303 seats. On 7 November 2022 the Supreme Court upheld the 103rd Amendment by 3:2 (Frontline).",
    poll: { label: "Lok Sabha 2019", month: "2019-04", result: "BJP won 303 of 543 seats", gapDays: 93 },
  },
  {
    id: "hpe028",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Interim Budget 2019: tax rebate",
    kind: "spend",
    difficulty: "simple",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "Setting aside the convention that interim budgets leave taxes alone, Piyush Goyal's February 2019 speech gave a full rebate on taxable income up to what level?",
    options: ["₹3 lakh", "₹5 lakh", "₹7 lakh", "₹10 lakh"],
    correctIndex: 1,
    explanation: "Goyal said the main tax proposals normally wait for the regular budget but small taxpayers needed certainty. He put the benefit at ₹18,500 crore for about 3 crore taxpayers, and raised the standard deduction from ₹40,000 to ₹50,000, worth ₹4,700 crore more. The same speech launched PM-KISAN.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2019-20(I)/ub2019-20/bs/bs.pdf",
    sourceLabel: "indiabudget.gov.in — Interim Budget 2019-20 speech, Piyush Goyal (1 Feb 2019)",
    sources: [
      "https://www.dw.com/en/india-election-whats-behind-the-bjps-poll-upset/a-69277403",
      "https://scroll.in/latest/915713/2019-general-elections-voting-to-be-held-in-seven-phases-to-start-on-april-11",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Piyush Goyal", role: "Union Finance Minister (interim budget)", party: "BJP" }],
    outcome: "Polling began 69 days later and the BJP won 303 of 543 seats (DW). The cited sources make no causal claim.",
    poll: { label: "Lok Sabha 2019", month: "2019-04", result: "BJP won 303 of 543 seats", gapDays: 69 },
  },
  {
    id: "hpe029",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Corporate tax cut timing (2019)",
    kind: "spend",
    difficulty: "expert",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "Nirmala Sitharaman announced the 2019 corporate tax cut in Panaji on Friday, 20 September. What did the Election Commission announce the next day?",
    options: ["Polls in Maharashtra and Haryana", "Polls in Delhi and Jharkhand", "Polls in Bihar and Assam", "A freeze on new state schemes"],
    correctIndex: 0,
    explanation: "Cutting corporate tax by ordinance, she put the annual revenue cost at ₹1.45 lakh crore (Times of India). On Saturday the EC announced single-phase polls in Maharashtra and Haryana for 21 October, with counting on 24 October (The Indian Express).",
    sourceUrl: "https://indianexpress.com/article/india/how-parties-fared-in-haryana-and-maharashtra-assembly-polls-in-2014-6015815/",
    sourceLabel: "The Indian Express — How parties fared in Haryana and Maharashtra polls in 2014 (21 Sep 2019)",
    sources: [
      "https://timesofindia.indiatimes.com/business/india-business/mini-budget-after-budget-govt-slashes-corp-tax-rates-to-boost-economy-investments/articleshow/71214427.cms",
      "https://timesofindia.indiatimes.com/india/bjp-dips-17-in-maharashtra-alliance-majority-falls-short-of-220-target/articleshow/71748653.cms",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Nirmala Sitharaman", role: "Union Finance Minister", party: "BJP" }],
    outcome: "In Maharashtra the BJP fell from 122 seats to 105 and the Shiv Sena from 63 to 56; their 161 was a majority but short of a 220-plus target (Times of India).",
    poll: { label: "Maharashtra & Haryana Assembly 2019", month: "2019-10", gapDays: 31, result: "Maharashtra: BJP 105, Shiv Sena 56, NCP 54 of 288" },
  },
  // ───────────────────────────── 2020–2026 ─────────────────────────────
  {
    id: "hpe030",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Free grain extended to Nov 2020",
    kind: "scheme",
    difficulty: "extreme",
    year: 2020,
    asOf: "2026-09",
    govt: "NDA",
    question: "Extending free rations for 80 crore people to the end of November in his address of 30 June 2020, PM Modi put the extra cost at more than how much?",
    options: ["₹20,000 crore", "₹60,000 crore", "₹90,000 crore", "₹2 lakh crore"],
    correctIndex: 2,
    explanation: "Modi said PM Garib Kalyan Anna Yojana would run 'up to Diwali and Chhath Puja', giving 5 kg of wheat or rice and 1 kg of pulses free a month for five more months. The Times of India said total spending would near ₹1.5 lakh crore with the first three months. Bihar began voting 120 days later.",
    sourceUrl: "https://timesofindia.indiatimes.com/business/india-business/pm-modi-announces-extension-of-free-ration-scheme-says-govt-working-on-one-nation-one-ration-card/articleshow/76710523.cms",
    sourceLabel: "Times of India — PM Modi announces extension of free ration scheme (30 Jun 2020)",
    sources: [
      "https://www.livemint.com/elections/assembly-elections/bihar-last-election-result-2020-how-many-seats-did-bjp-jd-u-and-rjd-win-a-look-back-at-nail-biting-battle-11763043021082.html",
      "https://indianexpress.com/article/india/bihar-assembly-elections-2020-voting-dates-results-6610549/",
    ],
    tags: ["pre-election", "distribution", "relief"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "The NDA kept Bihar with 125 of 243 seats, three above the majority mark, on a near-tied vote; the RJD was the largest single party with 75 (Mint).",
    poll: { label: "Bihar Assembly 2020", month: "2020-10", gapDays: 120, result: "NDA won 125 of 243 seats; Mahagathbandhan 110" },
  },
  {
    id: "hpe031",
    domain: "civics",
    region: "India",
    state: "TN",
    topic: "Infrastructure",
    subtopic: "Budget 2021: highways for poll states",
    kind: "spend",
    difficulty: "simple",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "Budget 2021-22, presented weeks before four states voted, proposed 3,500 km of national highway works worth ₹1.03 lakh crore in which state?",
    options: ["Kerala", "West Bengal", "Assam", "Tamil Nadu"],
    correctIndex: 3,
    explanation: "Nirmala Sitharaman also listed 1,100 km in Kerala for ₹65,000 crore, 675 km in West Bengal for ₹25,000 crore and more than ₹34,000 crore of new works in Assam. The Indian Express (2026) called it a bumper Budget for those poll-bound states, which also included ₹63,246 crore for Chennai Metro phase two.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2021-22/doc/Budget_Speech.pdf",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2021-22, Nirmala Sitharaman (1 Feb 2021)",
    sources: [
      "https://www.thehindu.com/business/budget/union-budget-2021-new-highway-projects-announced-for-poll-bound-states/article33714696.ece",
      "https://indianexpress.com/article/political-pulse/no-big-ticket-sops-poll-bound-states-budget-2026-unlike-previous-years-10507670/",
      "https://timesofindia.indiatimes.com/india/mamata-powers-tmc-to-win-west-bengal-for-third-term-bjp-returns-in-assam-and-ldf-in-kerala/articleshow/82358436.cms",
      "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1708118",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Nirmala Sitharaman", role: "Union Finance Minister", party: "BJP" }],
    outcome: "The BJP kept Assam, but the TMC won a third term in West Bengal, the LDF returned in Kerala and the DMK-led alliance took Tamil Nadu (Times of India).",
    poll: { label: "Assembly polls in 4 states and Puducherry, 2021", month: "2021-03", gapDays: 54, result: "TMC kept West Bengal, BJP Assam, LDF Kerala; DMK-led alliance won Tamil Nadu" },
  },
  {
    id: "hpe032",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Energy & Mining",
    subtopic: "Fuel excise cut (Nov 2021)",
    kind: "spend",
    difficulty: "simple",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "On 3 November 2021, the eve of Diwali, the Centre cut excise duty on diesel by ₹10 a litre. By how much did it cut excise on petrol?",
    options: ["₹2 a litre", "₹5 a litre", "₹8 a litre", "₹12 a litre"],
    correctIndex: 1,
    explanation: "BJP-ruled states including Uttar Pradesh, Uttarakhand, Goa and Manipur, all due to vote in early 2022, followed with VAT cuts (Times of India). The Congress's Randeep Surjewala called it a 'jumla', saying petrol had risen ₹28 and diesel ₹26 a litre in 2021 and that the BJP had just lost 14 bypolls.",
    sourceUrl: "https://timesofindia.indiatimes.com/business/india-business/excise-duty-slashed-by-rs-10-on-diesel-rs-5-on-petrol/articleshow/87515788.cms",
    sourceLabel: "Times of India — Centre slashes excise duty on diesel by Rs 10, petrol Rs 5 (3 Nov 2021)",
    sources: [
      "https://www.hindustantimes.com/india-news/after-losing-14-bypolls-congress-says-petrol-diesel-duty-cut-not-diwali-gift-but-jumla-101635956361055.html",
      "https://indianexpress.com/article/political-pulse/yogi-adityanath-uttar-predash-polls-2027-sp-congress-seats-10867666/",
      "https://www.thehindu.com/elections/punjab-assembly/aap-sweeps-punjab-with-92-seats-congress-akali-dal-decimated/article65211989.ece",
      "https://timesofindia.indiatimes.com/uttar-pradesh-assembly-elections-2022-seven-phase-polling-in-state-to-begin-on-february-10/articleshow/88775529.cms",
    ],
    tags: ["pre-election"],
    outcome: "Polling began 99 days later. The BJP kept Uttar Pradesh with 255 of 403 seats, while the AAP swept Punjab with 92 of 117.",
    poll: { label: "Assembly polls in UP, Punjab and 3 other states, 2022", month: "2022-02", result: "BJP kept UP with 255 of 403 seats; AAP won Punjab with 92 of 117", gapDays: 99 },
  },
  {
    id: "hpe033",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Farm laws repeal (2021)",
    kind: "institution",
    difficulty: "expert",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "PM Modi announced on 19 November 2021 that the three farm laws would be repealed. When Parliament passed the repeal Bill on 29 November, how long did the Rajya Sabha take?",
    options: ["Under five minutes", "About two hours", "A full day of debate", "Three sittings"],
    correctIndex: 0,
    explanation: "It passed by voice vote after lunch; the Lok Sabha had cleared it earlier that day without discussion amid Opposition protests. Agriculture Minister Narendra Singh Tomar said a debate was not needed as the Opposition also wanted repeal. Announcing it, Modi apologised, saying there 'must have been some deficiency in our efforts'.",
    sourceUrl: "https://www.thehindu.com/news/national/farm-laws-repeal-bill-passed-in-rajya-sabha-by-voice-vote-in-less-than-five-minutes/article37747790.ece",
    sourceLabel: "The Hindu — Farm Laws Repeal Bill passed in Rajya Sabha by voice vote in less than five minutes (29 Nov 2021)",
    sources: [
      "https://www.thehindu.com/news/national/lok-sabha-clears-farm-laws-repeal-bill-without-discussion/article37746792.ece",
      "https://indianexpress.com/article/india/three-farm-laws-repealed-pm-modi-7630405/",
      "https://indianexpress.com/article/political-pulse/yogi-adityanath-uttar-predash-polls-2027-sp-congress-seats-10867666/",
      "https://www.thehindu.com/elections/punjab-assembly/aap-sweeps-punjab-with-92-seats-congress-akali-dal-decimated/article65211989.ece",
      "https://timesofindia.indiatimes.com/uttar-pradesh-assembly-elections-2022-seven-phase-polling-in-state-to-begin-on-february-10/articleshow/88775529.cms",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }, { name: "Narendra Singh Tomar", role: "Union Agriculture Minister", party: "BJP" }],
    outcome: "Polling began 83 days after the announcement. The BJP kept Uttar Pradesh with 255 of 403 seats; the AAP won Punjab with 92 of 117.",
    poll: { label: "Assembly polls in UP, Punjab and 3 other states, 2022", month: "2022-02", result: "BJP kept UP with 255 of 403 seats; AAP won Punjab with 92 of 117", gapDays: 83 },
  },
  {
    id: "hpe034",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Elections & Funding",
    subtopic: "Freebies PIL: EC affidavit (2022)",
    kind: "institution",
    difficulty: "expert",
    year: 2022,
    asOf: "2026-09",
    govt: "NDA",
    question: "The Supreme Court issued notice on a PIL against poll freebies on 25 January 2022, weeks before five states voted. What did the Election Commission tell the court in April?",
    options: ["It can ban them under the Model Code", "They amount to corrupt practices", "Offering them is a party's policy call it cannot regulate", "Only the Finance Commission may judge them"],
    correctIndex: 2,
    explanation: "The EC's affidavit said offering freebies before or after polls is a party's policy decision, that it cannot regulate policies a winning party adopts in government, and that it cannot deregister parties for this. Issuing notice, the bench of CJI N.V. Ramana had observed that it was undoubtedly a serious issue (LiveLaw).",
    sourceUrl: "https://www.livelaw.in/top-stories/cant-de-register-political-parties-for-offering-freebies-election-commission-tells-supreme-court-196273",
    sourceLabel: "LiveLaw — Can’t de-register political parties for offering freebies: EC tells Supreme Court (10 Apr 2022)",
    sources: [
      "https://m.economictimes.com/news/india/sc-urged-to-hear-pil-against-promise-distribution-of-freebies-by-political-parties/articleshow/132456118.cms",
      "https://www.thenewsminute.com/news/election-commission-wants-parties-explain-financial-viability-poll-promises-168576",
      "https://indianexpress.com/article/political-pulse/in-reply-to-ec-on-freebies-bjp-draws-welfare-dole-line-congress-left-call-it-ec-overreach-sad-backs-move-8234191/",
      "https://indianexpress.com/article/political-pulse/yogi-adityanath-uttar-predash-polls-2027-sp-congress-seats-10867666/",
      "https://www.thehindu.com/elections/punjab-assembly/aap-sweeps-punjab-with-92-seats-congress-akali-dal-decimated/article65211989.ece",
      "https://timesofindia.indiatimes.com/uttar-pradesh-assembly-elections-2022-seven-phase-polling-in-state-to-begin-on-february-10/articleshow/88775529.cms",
    ],
    tags: ["pre-election"],
    outcome: "In Oct 2022 the EC proposed that parties disclose how promises would be funded; the Congress and Left called it overreach. The PIL was still unheard in July 2026, when CJI Surya Kant said 'This matter can wait' (PTI).",
    poll: { label: "Assembly polls in UP, Punjab and 3 other states, 2022", month: "2022-02", result: "BJP kept UP with 255 of 403 seats; AAP won Punjab with 92 of 117", gapDays: 16 },
  },
  {
    id: "hpe035",
    domain: "civics",
    region: "India",
    state: "KA",
    topic: "Farm & Food",
    subtopic: "Upper Bhadra aid (Budget 2023)",
    kind: "spend",
    difficulty: "expert",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "Budget 2023-24, about 14 weeks before Karnataka voted, promised central assistance of ₹5,300 crore to which irrigation project in the state's drought-prone central region?",
    options: ["Mekedatu", "Yettinahole", "Kalasa-Banduri", "Upper Bhadra"],
    correctIndex: 3,
    explanation: "Nirmala Sitharaman said the aid would fund sustainable micro-irrigation and fill surface tanks for drinking water. The Indian Express (2026) lists it, with a millet centre of excellence in Hyderabad, as that Budget’s only special mentions for the nine states voting in 2023.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2023-24/doc/Budget_Speech.pdf",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2023-24, Nirmala Sitharaman (1 Feb 2023)",
    sources: [
      "https://indianexpress.com/article/political-pulse/no-big-ticket-sops-poll-bound-states-budget-2026-unlike-previous-years-10507670/",
      "https://www.thehindu.com/elections/karnataka-assembly/congress-surge-topples-bjp-in-karnataka/article66847235.ece",
      "https://www.thehindu.com/news/national/karnataka/karnataka-petitions-centre-again-on-pending-approvals-and-funds-for-yettinahole-kalasa-banduri-upper-bhadra-projects/article69787926.ece",
      "https://thefederal.com/the-federal-focus/karnataka-cm-siddaramaiah-on-bhadra-upper-canal-funds-238882",
      "https://timesofindia.indiatimes.com/city/bengaluru/karnataka-government-threatens-supreme-court-action-over-central-fund-delays-for-upper-bhadra-project/articleshow/113236420.cms",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Nirmala Sitharaman", role: "Union Finance Minister", party: "BJP" }],
    outcome: "The Congress won 135 of 224 seats. In Sept 2024 the Jal Shakti ministry said release needed updated cost and spending details and depended on available resources (TOI); in July 2025 and April 2026 the state government said the ₹5,300 crore was still unreleased.",
    poll: { label: "Karnataka Assembly 2023", month: "2023-05", gapDays: 98, result: "Congress won 135 of 224 seats; BJP 66, JD(S) 19" },
  },
  {
    id: "hpe036",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "Women's reservation law (2023)",
    kind: "institution",
    difficulty: "extreme",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "The Lok Sabha passed the women's reservation Constitution amendment on 20 September 2023, seven weeks before five states began voting. What was the vote?",
    options: ["454–2", "381–12", "298–230", "520–0"],
    correctIndex: 0,
    explanation: "Introduced by Law Minister Arjun Ram Meghwal, it reserves a third of seats in the Lok Sabha, state Assemblies and Delhi's Assembly for women; the Rajya Sabha passed it unanimously, 214–0, the next day. It takes effect only after the first census after enactment and a fresh delimitation.",
    sourceUrl: "https://legal.economictimes.indiatimes.com/news/law-policy/womens-reservation-bill-passed-with-215-0-majority-in-rajya-sabha/103845840",
    sourceLabel: "ETLegalWorld — Rajya Sabha passes Women Reservation Bill (21 Sep 2023)",
    sources: [
      "https://www.livelaw.in/top-stories/lok-sabha-rejects-constitution-131st-bill-2026-on-delimitation-530736",
      "https://frontline.thehindu.com/news/bjp-3-1-assembly-election-results-in-madhya-pradesh-rajasthan-chhattisgarh-telangana-congress-2024-challenges/article67601613.ece",
      "https://www.thehindu.com/news/national/election-commission-announces-dates-for-assembly-polls-in-5-states/article67400079.ece",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Arjun Ram Meghwal", role: "Union Law Minister", party: "BJP" }],
    outcome: "Not yet in force: in April 2026 a follow-up amendment to enlarge the Lok Sabha and operationalise the quota fell short of a two-thirds majority (LiveLaw).",
    poll: { label: "Assembly polls in 5 states, Nov 2023", month: "2023-11", gapDays: 48, result: "BJP won Madhya Pradesh, Rajasthan and Chhattisgarh; Congress won Telangana" },
  },
  {
    id: "hpe037",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Elections & Funding",
    subtopic: "EC halts 'Viksit Bharat' messages (2024)",
    kind: "institution",
    difficulty: "simple",
    year: 2024,
    asOf: "2026-09",
    govt: "NDA",
    question: "After the 2024 Model Code took effect, which ministry did the Election Commission order to stop 'Viksit Bharat Sampark' WhatsApp messages carrying a letter from the PM?",
    options: ["Information and Broadcasting", "Home Affairs", "Electronics and IT (MeitY)", "Rural Development"],
    correctIndex: 2,
    explanation: "On 21 March 2024 the EC ordered MeitY to halt delivery at once and file a compliance report, after complaints that the messages kept arriving. MeitY said the letters were sent before the Model Code took effect but some were delayed by 'systemic and network constraints' (BOOM).",
    otherSide:
      "MeitY told the EC the letters were sent before the Model Code took effect and that some were delayed by 'systemic and network constraints'.",
    sourceUrl: "https://www.thehindu.com/elections/lok-sabha/ec-asks-meity-to-stop-viksit-bharat-whatsapp-messages/article67975397.ece",
    sourceLabel: "The Hindu — Election Commission asks MeitY to stop Viksit Bharat WhatsApp messages (21 Mar 2024)",
    sources: [
      "https://www.boomlive.in/news/the-viksit-bharat-whatsapp-message-that-you-got-eci-asks-govt-to-stop-24667",
      "https://www.dw.com/en/india-election-whats-behind-the-bjps-poll-upset/a-69277403",
      "https://www.thehindu.com/elections/lok-sabha/2024-lok-sabha-polls-begin-on-april-19-2024-16-crore-voters-on-the-rolls-in-102-seats-in-first-phase/article68080299.ece",
    ],
    tags: ["pre-election"],
    outcome: "Polling began 29 days later; the BJP won 240 of 543 seats, down from 303, and formed the government with NDA allies (DW).",
    poll: { label: "Lok Sabha 2024", month: "2024-04", result: "BJP 240 of 543, short of a majority; the NDA formed the government", gapDays: 29 },
  },
  {
    id: "hpe038",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Eighth Pay Commission approved (2025)",
    kind: "spend",
    difficulty: "simple",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "The Union Cabinet approved setting up the Eighth Pay Commission on 16 January 2025. Which election was then 20 days away?",
    options: ["Bihar Assembly", "Delhi Assembly", "Jharkhand Assembly", "Maharashtra Assembly"],
    correctIndex: 1,
    explanation: "The Hindu noted the decision came days before the Delhi poll, and that Delhi is home to about four lakh Union government employees; the Commission covers about 50 lakh employees and 65 lakh pensioners. Minister Ashwini Vaishnaw said PM Modi had taken the decision.",
    sourceUrl: "https://www.thehindu.com/news/national/government-announces-8th-pay-commission-for-central-govt-employees/article69104291.ece",
    sourceLabel: "The Hindu — Cabinet announces 8th Pay Commission for central government employees (16 Jan 2025)",
    sources: [
      "https://indianexpress.com/article/india/cabinet-tor-of-8th-pay-commission-january-2026-10331921/",
      "https://frontline.thehindu.com/news/delhi-election-results-2025-bjp-wins-46-seats-ends-aap-rule/article69195445.ece",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }, { name: "Ashwini Vaishnaw", role: "Union Information & Broadcasting Minister", party: "BJP" }],
    outcome: "The BJP won Delhi with 48 of 70 seats. Terms of reference came only on 28 Oct 2025, with Justice Ranjana Prakash Desai as chair and 18 months to report; revisions are expected from 1 Jan 2026 (Indian Express).",
    poll: { label: "Delhi Assembly 2025", month: "2025-02", result: "BJP won 48 of 70 seats; AAP 22", gapDays: 20 },
  },
  {
    id: "hpe039",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Budget 2025 and the Delhi poll",
    kind: "spend",
    difficulty: "expert",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "Four days before Delhi voted, Budget 2025 made income up to ₹12 lakh tax-free. How did PM Modi describe the budget at a Delhi campaign rally the next day?",
    options: ["A budget for a Viksit Delhi", "The biggest tax cut in world history", "A budget for the poor and farmers", "The friendliest ever for the middle class"],
    correctIndex: 3,
    explanation: "At the 2 February rally Modi said the whole middle class was calling it 'the friendliest for the middle class in the history of India', and attacked the AAP-led Delhi government; the AAP replied that the BJP had 'no vision for Delhi'. Mint noted that Delhi voted on 5 February, four days after Nirmala Sitharaman's Budget speech.",
    sourceUrl: "https://www.hindustantimes.com/india-news/at-delhi-rally-modi-hails-friendliest-budget-ever-101738521936250.html",
    sourceLabel: "Hindustan Times — PM Modi hails 'friendliest budget' ever at Delhi election rally (3 Feb 2025)",
    sources: [
      "https://www.livemint.com/elections/delhi-election-results-did-nirmala-sitharaman-s-income-tax-cuts-fuel-bjp-s-capital-gains-11738990221509.html",
      "https://frontline.thehindu.com/news/delhi-election-results-2025-bjp-wins-46-seats-ends-aap-rule/article69195445.ece",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Nirmala Sitharaman", role: "Union Finance Minister", party: "BJP" }],
    outcome: "The BJP won 48 of 70 seats; its last Delhi chief minister had served in 1998 (Mint). Mint asked whether the tax cut helped, but cited no study showing it did.",
    poll: { label: "Delhi Assembly 2025", month: "2025-02", result: "BJP won 48 of 70 seats; AAP 22", gapDays: 4 },
  },
  {
    id: "hpe040",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "GST rate overhaul (Sept 2025)",
    kind: "spend",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "The GST Council's two-slab overhaul took effect on 22 September 2025, 45 days before Bihar began voting. What annual revenue cost did the Revenue Secretary put on it?",
    options: ["About ₹48,000 crore", "About ₹12,000 crore", "About ₹1.45 lakh crore", "About ₹2.5 lakh crore"],
    correctIndex: 0,
    explanation: "Announcing the change on 3 September, Nirmala Sitharaman said the four main slabs of 5%, 12%, 18% and 28% would become 5% and 18%, plus 40% for sin and luxury goods, from the first day of Navratri. Revenue Secretary Arvind Shrivastava hoped higher consumption would offset the cost. PM Modi called the rollout a 'GST Bachat Utsav'.",
    sourceUrl: "https://www.hindustantimes.com/business/new-two-tier-gst-structure-to-kick-in-from-22-september-nirmala-sitharaman-101756917458027.html",
    sourceLabel: "Hindustan Times — New GST rates from 22 September (4 Sep 2025)",
    sources: [
      "https://www.livemint.com/news/india/pm-modis-open-letter-to-nation-as-navratri-begins-pm-hails-gst-bachat-utsav-pitches-swadeshi-full-message-11758541472241.html",
      "https://www.hindustantimes.com/india-news/nda-mahagathbandhan-bjp-jdu-rjd-congress-ljp-jan-suraaj-prashant-kishore-tejashwi-seat-tally-101763169862862.html",
      "https://www.thehindu.com/elections/bihar-assembly/bihar-assembly-election-first-phase-sees-over-64-voter-turnout/article70249590.ece",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Nirmala Sitharaman", role: "Union Finance Minister", party: "BJP" }],
    outcome: "The NDA swept Bihar with 202 of 243 seats; the cited sources make no claim that the tax cuts drove the result.",
    poll: { label: "Bihar Assembly 2025", month: "2025-11", gapDays: 45, result: "NDA won 202 of 243 seats; BJP 89, JD(U) 85" },
  },
  {
    id: "hpe041",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Energy & Mining",
    subtopic: "Budget 2026 and the poll-bound states",
    kind: "spend",
    difficulty: "expert",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "Budget 2026 made few specific announcements for the states voting that April. Which two poll-bound states did it name for dedicated rare-earth corridors?",
    options: ["West Bengal and Assam", "Assam and Kerala", "Kerala and Tamil Nadu", "Tamil Nadu and West Bengal"],
    correctIndex: 2,
    explanation: "Nirmala Sitharaman named Odisha, Kerala, Andhra Pradesh and Tamil Nadu for Rare Earth Corridors and listed seven high-speed rail corridors, including Chennai–Bengaluru, Hyderabad–Chennai and Varanasi–Siliguri. The Indian Express said the poll-bound mentions were muted next to 2021 and carried no specific allocations.",
    sourceUrl: "https://www.indiabudget.gov.in/doc/Budget_Speech.pdf",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2026-27, Nirmala Sitharaman (1 Feb 2026)",
    sources: [
      "https://indianexpress.com/article/political-pulse/no-big-ticket-sops-poll-bound-states-budget-2026-unlike-previous-years-10507670/",
      "https://frontline.thehindu.com/the-nation/assembly-results-bjp-vijay-udf-surge/article70937836.ece",
      "https://www.thehindu.com/elections/record-voter-turnout-in-assam-puducherry-high-polling-rates-in-kerala-too/article70844099.ece",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Nirmala Sitharaman", role: "Union Finance Minister", party: "BJP" }],
    outcome: "Polling began 67 days later. The BJP-led alliance took West Bengal with 207 of 294 seats and kept Assam; Vijay's TVK emerged largest in Tamil Nadu (108 of 234) and the UDF won Kerala (102), per Frontline.",
    poll: { label: "Assembly polls in 4 states and Puducherry, 2026", month: "2026-04", result: "BJP-led alliance won West Bengal (207 of 294) and Assam; TVK largest in Tamil Nadu (108 of 234); UDF won Kerala", gapDays: 67 },
  },
  {
    id: "hpe042",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Elections & Funding",
    subtopic: "Budget sops for poll-bound states: tally",
    kind: "spend",
    difficulty: "extreme",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "An Indian Express count on Budget day 2026 found Union Budgets since 2014 made specific allocations or announcements for how many of 72 poll-bound states?",
    options: ["9", "21", "45", "60"],
    correctIndex: 1,
    explanation: "For the UPA years it counted 24 of 70 poll-bound states. Its examples include an IIT for Rajasthan (2008-09) and a Raipur institute (2013-14) under the UPA, and Bengaluru's suburban rail (2018-19), Karnataka's Upper Bhadra aid (2023-24) and a Makhana Board for Bihar (2025-26) under the NDA.",
    sourceUrl: "https://indianexpress.com/article/political-pulse/no-big-ticket-sops-poll-bound-states-budget-2026-unlike-previous-years-10507670/",
    sourceLabel: "The Indian Express — No big-ticket sops for poll-bound states in Budget 2026, unlike previous years (1 Feb 2026)",
    sources: [
      "https://www.indiabudget.gov.in/budget2025-26/doc/budget_speech.pdf",
      "https://frontline.thehindu.com/the-nation/assembly-results-bjp-vijay-udf-surge/article70937836.ece",
      "https://www.thehindu.com/elections/record-voter-turnout-in-assam-puducherry-high-polling-rates-in-kerala-too/article70844099.ece",
    ],
    tags: ["pre-election"],
    outcome: "Budget 2026 itself gave the four states voting from 9 April few specific announcements; the BJP-led alliance won West Bengal and Assam, the TVK emerged largest in Tamil Nadu and the UDF won Kerala (Frontline).",
    poll: { label: "Assembly polls in 4 states and Puducherry, 2026", month: "2026-04", result: "BJP-led alliance won West Bengal (207 of 294) and Assam; TVK largest in Tamil Nadu (108 of 234); UDF won Kerala", gapDays: 67 },
  },
]);
