// HISAAB DO — Relief funds, States (ids hrf100–hrf199).
// Relief money in the states, 2001–2026: CM relief funds and who gave to them, disaster packages and cash
// relief, Centre–state fights over NDRF/SDRF money (asked vs released), and what auditors, courts and
// police later found. Every item is tagged 'relief'; items paid out in the run-up to a poll are also tagged
// 'pre-election' and carry `poll` (gapDays = days from announcement/first payment to the first polling day).
// `govt` records who governed the STATE at the time; the explanation names the Centre where it is the actor.
// Research notes, sources, drops and stale-risk statuses: docs/hisaab/research/relief-states-notes.md.
// Every item was checked against its fetched source in September 2026 (asOf '2026-09').

export const HISAAB_RELIEF_STATES = Object.freeze([
  // ───────────────────────── 2000–2004 ─────────────────────────
  {
    id: "hrf100",
    domain: "civics",
    region: "India",
    state: "GJ",
    topic: "Welfare & Subsidies",
    subtopic: "Kutch earthquake cash doles (2001)",
    kind: "spend",
    difficulty: "extreme",
    year: 2001,
    asOf: "2026-09",
    govt: "BJP",
    question:
      "After the January 2001 Kutch earthquake, India Today described a blundering response by Keshubhai Patel's government on cash doles for survivors. How many government orders on the doles came in 10 days?",
    options: ["3", "11", "25", "40"],
    correctIndex: 1,
    explanation:
      "India Today (March 2001) counted 11 government orders on cash doles in 10 days, and three IAS officers rotated through quake-hit Gandhidham in 20 days. Patel promised a room for each of eight lakh uprooted families by 30 June and said power and drinking water had been restored in the shortest possible time; some international agencies praised the government's effort.",
    sourceUrl:
      "https://www.indiatoday.in/magazine/states/story/20010305-gujarat-cm-keshubhai-patel-fitness-to-rule-grows-after-failure-to-provide-quake-relief-775615-2001-03-04",
    sourceLabel: "India Today — Leader in paralysis (5 Mar 2001)",
    sources: ["https://frontline.thehindu.com/other/article30252182.ece"],
    tags: ["relief"],
    enactedBy: [{ name: "Keshubhai Patel", role: "Chief Minister, Gujarat", party: "BJP" }],
    outcome:
      "Frontline wrote that bungled relief after the Bhuj earthquake was seen as the Patel government's most striking failure. After by-election defeats the BJP high command replaced him with Narendra Modi in October 2001.",
  },
  {
    id: "hrf101",
    domain: "civics",
    region: "India",
    state: "OD",
    topic: "Infrastructure",
    subtopic: "Cyclone shelters after the 1999 super cyclone",
    kind: "spend",
    difficulty: "extreme",
    year: 2001,
    asOf: "2026-09",
    govt: "BJD",
    question:
      "Frontline reported in March 2001 that coastal Orissa needed at least 512 cyclone shelters after the 1999 super cyclone. How many were actually standing then?",
    options: ["23", "240", "489", "1,200"],
    correctIndex: 0,
    explanation:
      "The leader of the UN inter-sectoral team in Bhubaneswar told Frontline only 23 existed for people within 10 km of the coast; work on 489 had not begun, though money for 240 had been allocated. The two 1999 cyclones destroyed about 1.6 million homes (UNICEF). Naveen Patnaik's BJD-led government, in office since March 2000, was drawing up district disaster plans with the UNDP.",
    sourceUrl: "https://frontline.thehindu.com/other/article30249961.ece",
    sourceLabel: "Frontline — Some lessons from Orissa (3 Mar 2001)",
    sources: [
      "https://www.thehindu.com/news/national/other-states/odisha-cm-naveen-patnaik-equals-former-west-bengal-cm-jyoti-basus-record-of-second-longest-serving-cm-of-india/article67108902.ece",
    ],
    tags: ["relief"],
  },
  {
    id: "hrf102",
    domain: "civics",
    region: "India",
    state: "AP",
    topic: "Farm & Food",
    subtopic: "Drought relief rice (2002–03)",
    kind: "spend",
    difficulty: "expert",
    year: 2003,
    asOf: "2026-09",
    govt: "TDP",
    question:
      "In the 2002–03 drought, Chandrababu Naidu's government sought 2.5 million tonnes of rice for relief work under the Centre's SGRY scheme. How much had been released by May 2003, per Frontline?",
    options: ["0.2 million tonnes", "0.5 million tonnes", "1.5 million tonnes", "2.5 million tonnes"],
    correctIndex: 1,
    explanation:
      "Frontline reported only 0.5 million tonnes released against 2.5 million sought, leaving the poor 'exposed to starvation'; the state had also asked for ₹2,373.44 crore from the National Calamity Contingency Fund. Government estimates said 1.38 crore farm labourers had lost work. Naidu had got central teams to visit twice, in Sept 2002 and Feb 2003.",
    sourceUrl: "https://frontline.thehindu.com/the-nation/article30217066.ece",
    sourceLabel: "Frontline — Elusive relief in Andhra Pradesh (23 May 2003)",
    tags: ["relief"],
  },
  {
    id: "hrf103",
    domain: "civics",
    region: "India",
    state: "RJ",
    topic: "Jobs & Economy",
    subtopic: "Drought relief work (2002–03)",
    kind: "spend",
    difficulty: "expert",
    year: 2003,
    asOf: "2026-09",
    govt: "INC",
    question:
      "In the 2002–03 drought, Rajasthan first offered its most vulnerable families 15 days of relief work a month. What did Ashok Gehlot's government cut it to, citing a shortfall of central funds?",
    options: ["5 days a month", "8 days a month", "10 days a month", "20 days a month"],
    correctIndex: 2,
    explanation:
      "All 32 districts were drought-notified. The Centre's calamity relief committee paid the cash wage component only for 20.80 lakh BPL families (₹188.82 crore), while the state put its May–July 2003 need at ₹1,530 crore. The BJP questioned how central drought funds were used; Gehlot said the drought would not become an election issue as the state was doing all it could.",
    sourceUrl: "https://frontline.thehindu.com/the-nation/article30216871.ece",
    sourceLabel: "Frontline — From bad to worse in Rajasthan (9 May 2003)",
    tags: ["relief"],
    enactedBy: [{ name: "Ashok Gehlot", role: "Chief Minister, Rajasthan", party: "INC" }],
    outcome:
      "By May 2003 only 29.10 lakh of the 56 lakh tonnes of foodgrain the state needed had arrived, a senior official told Frontline, and no funds had been allocated for gratuitous relief to 4.5 lakh destitute people.",
  },
  {
    id: "hrf104",
    domain: "civics",
    region: "India",
    state: "TN",
    topic: "Farm & Food",
    subtopic: "Drought aid demand (2003)",
    kind: "spend",
    difficulty: "extreme",
    year: 2003,
    asOf: "2026-09",
    govt: "AIADMK",
    question:
      "Seeking drought aid in early 2003, Jayalalithaa asked the Vajpayee government for at least ₹2,027 crore more. How much had the Centre given Tamil Nadu by then, according to the All India Kisan Sabha?",
    options: ["₹228 crore", "₹1,434 crore", "₹2,280 crore", "₹5,388 crore"],
    correctIndex: 0,
    explanation:
      "The Kisan Sabha's Tamil Nadu unit told Frontline the Centre had given only ₹228 crore though ₹13,000 crore sat in the National Calamity Fund, and accused the AIADMK government of not pressing hard enough. Jayalalithaa's ₹2,027 crore and 9 lakh tonnes of rice were over and above ₹1,434 crore sought earlier; the state put crop losses at ₹5,388 crore.",
    sourceUrl: "https://frontline.thehindu.com/other/article30215779.ece",
    sourceLabel: "Frontline — A worsening drought (28 Feb 2003)",
    sources: ["https://frontline.thehindu.com/other/article30215502.ece"],
    tags: ["relief"],
  },

  // ───────────────────────── 2005–2009 ─────────────────────────
  {
    id: "hrf105",
    domain: "civics",
    region: "India",
    state: "TN",
    topic: "Welfare & Subsidies",
    subtopic: "Tsunami relief package (2004–05)",
    kind: "scheme",
    difficulty: "expert",
    year: 2005,
    asOf: "2026-09",
    govt: "AIADMK",
    question:
      "After the December 2004 tsunami, the Tamil Nadu government began handing out a relief package of clothes, rice, kerosene and how much cash for food, utensils and a temporary shelter, per Frontline?",
    options: ["₹400", "₹4,000", "₹10,000", "₹1 lakh"],
    correctIndex: 0,
    explanation:
      "Frontline (Jan 2005) reported the ₹400 package plus separate cash to restore fishing boats. The Jayalalithaa government asked the Centre for ₹4,800 crore and 54,000 tonnes of rice, ₹750 crore more for fishing families, and another ₹4,800 crore for 40 km of sea walls. Across the national relief effort, Frontline noted lapses such as relief foodgrain leaking into the open market.",
    sourceUrl: "https://frontline.thehindu.com/cover-story/article30203386.ece",
    sourceLabel: "Frontline — Rebuilding lives (28 Jan 2005)",
    tags: ["relief"],
    enactedBy: [{ name: "J. Jayalalithaa", role: "Chief Minister, Tamil Nadu", party: "AIADMK" }],
  },
  {
    id: "hrf106",
    domain: "civics",
    region: "India",
    state: "KL",
    topic: "Environment & Land",
    subtopic: "Tsunami Rehabilitation Programme funds",
    kind: "spend",
    difficulty: "expert",
    year: 2006,
    asOf: "2026-09",
    govt: "LDF",
    question:
      "A 2013 CAG report said Kerala told the Centre in October 2006 that ₹284 crore of its tsunami rehabilitation money had been moved to coastal housing. Which component was it taken from?",
    options: ["Schools and health centres", "Fisheries livelihoods", "Roads and bridges", "Environment and coastal protection"],
    correctIndex: 3,
    explanation:
      "Of ₹432.18 crore meant for 'Environment and Coastal Protection', ₹284.08 crore went to a coastal housing project — far more than the ₹45.54 crore sanctioned for housing. The CAG found 72 of 228 chosen villages were not on the coast and over 4,000 houses within 10 m of the high-tide line, and said this matched the Kerala High Court's 2012 observations on diversion.",
    sourceUrl:
      "https://www.newindianexpress.com/states/kerala/2013/Mar/20/grave-lapses-in-tsunami-rehabilitation-programme-460171.html",
    sourceLabel: "The New Indian Express — 'Grave lapses in Tsunami Rehabilitation Programme' (20 Mar 2013)",
    sources: ["https://www.hindustantimes.com/india/achuthanandan-sworn-in-as-kerala-cm/story-uePPLpTvN7JMm0gE1xlXzH.html"],
    tags: ["relief"],
    outcome:
      "Under the ₹1,441.75 crore centrally approved programme, Kerala had built 8,549 of the 11,000 tsunami houses due by 2009-10 by July 2012, the CAG found.",
  },
  {
    id: "hrf107",
    domain: "civics",
    region: "India",
    state: "TN",
    topic: "Governance & Institutions",
    subtopic: "Chennai flood-relief stampede (2005)",
    kind: "institution",
    difficulty: "simple",
    year: 2006,
    asOf: "2026-09",
    govt: "AIADMK",
    question:
      "In January 2006 the Supreme Court said the stampede that killed 42 people at a Chennai flood-relief camp in December 2005 happened chiefly because of what?",
    options: [
      "A wall collapse at the school used as the camp",
      "Negligence of state officers in arranging relief",
      "Relief tokens being sold on the black market",
      "A power failure at the camp before dawn",
    ],
    correctIndex: 1,
    explanation:
      "Justices K.G. Balakrishnan and P.P. Naolekar refused Tamil Nadu's plea to cancel a DMK councillor's bail, rejecting the state's claim that rumours he allegedly spread about relief tokens caused the crush: 'This is because of your sheer negligence.' Over 2,000 people had gathered at a K.K. Nagar school camp on 18 Dec 2005; six had died near another relief camp on 6 Nov.",
    sourceUrl: "https://www.rediff.com/news/report/stampede/20060127.htm",
    sourceLabel: "Rediff (PTI) — TN govt responsible for December 2005 stampede: SC (27 Jan 2006)",
    sources: ["https://www.thehindu.com/news/national/tamil-nadu/karur-stampede-when-50-people-died-in-two-sunday-stampedes-in-chennai/article70112589.ece"],
    tags: ["relief"],
  },
  {
    id: "hrf108",
    domain: "civics",
    region: "India",
    state: "MH",
    topic: "Welfare & Subsidies",
    subtopic: "July 2005 floods relief",
    kind: "spend",
    difficulty: "expert",
    year: 2005,
    asOf: "2026-09",
    govt: "INC",
    question:
      "After the July 2005 deluge damaged over 1.87 lakh houses across Maharashtra, Vilasrao Deshmukh's government released ₹500 crore for relief work. What did the Centre do, per Frontline?",
    options: [
      "Declined, saying the state had enough funds",
      "Gave ₹50 crore from the PM's relief fund",
      "Sanctioned a ₹5,000 crore soft loan",
      "Cleared an additional ₹500 crore",
    ],
    correctIndex: 3,
    explanation:
      "Frontline (Aug 2005) reported the state's ₹500 crore and a further ₹500 crore cleared by the Centre. Official figures put damaged houses above 1.87 lakh, affecting eight lakh families, with about 50,000 people in relief camps; the public works minister said national highway repairs alone would exceed ₹4,100 crore.",
    sourceUrl: "https://frontline.thehindu.com/cover-story/article30206092.ece",
    sourceLabel: "Frontline — High water and hell (26 Aug 2005)",
    sources: ["https://www.rediff.com/news/special/spec1/20050801.htm"],
    tags: ["relief"],
    enactedBy: [{ name: "Vilasrao Deshmukh", role: "Chief Minister, Maharashtra", party: "INC" }],
  },
  {
    id: "hrf109",
    domain: "civics",
    region: "India",
    state: "KA",
    topic: "Welfare & Subsidies",
    subtopic: "Aasare flood houses (2009)",
    kind: "scheme",
    difficulty: "simple",
    year: 2009,
    asOf: "2026-09",
    govt: "BJP",
    question:
      "After the Sept–Oct 2009 floods in north Karnataka, CM B.S. Yeddyurappa promised new houses for victims, each costing ₹1 lakh, later built under the 'Aasare' scheme. How many did he announce?",
    options: ["10,000", "25,000", "1,00,000", "5,00,000"],
    correctIndex: 2,
    explanation:
      "Frontline (Nov 2009) reported the 1,00,000-house promise and a plan to relocate 219 flood-prone villages. Yeddyurappa led a walkathon in Bengaluru to raise donations, proposed extra taxes to raise ₹2,000 crore and sought ₹10,000 crore from the Centre's calamity fund; losses were first estimated at ₹20,000 crore.",
    sourceUrl: "https://frontline.thehindu.com/the-nation/article30188800.ece",
    sourceLabel: "Frontline — After the deluge (6 Nov 2009)",
    sources: [
      "https://www.thehindu.com/news/national/karnataka/aasare-scheme-wide-gap-between-claims-and-reality/article5168286.ece",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "B.S. Yeddyurappa", role: "Chief Minister, Karnataka", party: "BJP" }],
    outcome:
      "In Raichur district, 11,123 of 12,241 planned Aasare houses had been built by Sept 2013, but many stood empty for want of water and power, and some were cracked, The Hindu found.",
  },

  // ───────────────────────── 2010–2014 ─────────────────────────
  {
    id: "hrf110",
    domain: "civics",
    region: "India",
    state: "BR",
    topic: "Governance & Institutions",
    subtopic: "Gujarat's Kosi aid returned (2010)",
    kind: "spend",
    difficulty: "simple",
    year: 2010,
    asOf: "2026-09",
    govt: "JDU",
    question:
      "In June 2010 newspaper ads in Patna thanked Gujarat CM Narendra Modi for ₹5 crore given for the 2008 Kosi flood victims. What did Bihar CM Nitish Kumar do with that money?",
    options: [
      "Sent it back to the Gujarat government",
      "Moved it to the PM's National Relief Fund",
      "Spent it on repairing Kosi embankments",
      "Handed it to relief camps in Supaul",
    ],
    correctIndex: 0,
    explanation:
      "Nitish, then heading a JD(U)-BJP government, objected to the ads, called off a dinner for BJP leaders and returned the cheque. BJP president Nitin Gadkari countered that the money was meant for Bihar's people, not for Nitish. Campaigning in Bihar in 2015, Modi called the return 'arrogant' and said it hurt him.",
    sourceUrl: "https://www.rediff.com/news/slide-show/slide-show-1-when-nitish-cancelled-the-modi-dinner/20140228.htm",
    sourceLabel: "Rediff — When Nitish cancelled the Modi dinner (book excerpt, 28 Feb 2014)",
    sources: [
      "https://www.oneindia.com/india/nitish-kumar-returned-rs-5-crore-aid-narendra-modi-in-bihar-1842056.html",
      "https://www.newindianexpress.com/india/2015/Oct/02/bihar-polls-pm-modi-attacks-nitish-calls-him-arrogant-823696.html",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Nitish Kumar", role: "Chief Minister, Bihar", party: "JD(U)" }],
    outcome:
      "In the excerpt, JD(U) president Sharad Yadav tells Gadkari that, from what he knew, Gujarat had cashed the returned cheque the day it arrived. Modi raised the episode at Saharsa (Aug 2015) and Banka (Oct 2015).",
  },
  {
    id: "hrf111",
    domain: "civics",
    region: "India",
    state: "UT",
    topic: "Welfare & Subsidies",
    subtopic: "CM's relief fund after Kedarnath (2013)",
    kind: "funding",
    difficulty: "expert",
    year: 2013,
    asOf: "2026-09",
    govt: "INC",
    question:
      "Within three weeks of the June 2013 Uttarakhand floods, donations to CM Vijay Bahuguna's relief fund crossed ₹181 crore. Which company was the biggest donor, with ₹50 crore?",
    options: ["ONGC", "State Bank of India", "BHEL", "Coal India"],
    correctIndex: 3,
    explanation:
      "Business Standard (5 July 2013) listed Coal India's ₹50 crore as the largest corporate gift. Uttar Pradesh sent ₹25 crore, the most of any state; Delhi, Punjab, Haryana and the BSF gave ₹10 crore each, and ONGC, SBI and BHEL ₹1–2 crore each. More than 370 were confirmed dead and 3,000 missing at the time.",
    sourceUrl: "https://www.business-standard.com/article/specials/uttarakhand-donations-top-rs-180-crore-113070500577_1.html",
    sourceLabel: "Business Standard — Uttarakhand donations top Rs 180 crore (5 Jul 2013)",
    sources: [
      "https://m.economictimes.com/news/politics-and-nation/vijay-bahuguna-quits-as-uttarakhand-chief-minister/articleshow/29653269.cms",
    ],
    tags: ["relief"],
    outcome:
      "Bahuguna resigned on the Congress high command's direction on 31 Jan 2014, after months of criticism that rescue began four to five days after the disaster; Harish Rawat was named the front-runner to succeed him (ET).",
  },
  {
    id: "hrf112",
    domain: "civics",
    region: "India",
    state: "OD",
    topic: "Governance & Institutions",
    subtopic: "Phailin advance request (2013)",
    kind: "spend",
    difficulty: "extreme",
    year: 2013,
    asOf: "2026-09",
    govt: "BJD",
    question:
      "Days after Cyclone Phailin in October 2013, Naveen Patnaik wrote to PM Manmohan Singh for a ₹1,000 crore advance. How much did Odisha's State Disaster Response Fund hold for 2013-14?",
    options: ["₹52 crore", "₹523 crore", "₹2,500 crore", "₹4,242 crore"],
    correctIndex: 1,
    explanation:
      "Patnaik's letter of 16 Oct 2013 sought ₹1,000 crore over the ₹523 crore SDRF corpus, saying Ganjam's power network alone needed over ₹900 crore. The state's memorandum to the Union home secretary put damage at ₹4,242.41 crore. Frontline, critical of the relief effort, reported protests over slow aid; BJD ministers accused the UPA Centre of apathy.",
    sourceUrl: "https://frontline.thehindu.com/environment/after-phailin/article5281245.ece",
    sourceLabel: "Frontline — After Phailin (30 Oct 2013)",
    tags: ["relief"],
  },
  {
    id: "hrf113",
    domain: "civics",
    region: "India",
    state: "MH",
    topic: "Farm & Food",
    subtopic: "Drought fodder camps (2012–13)",
    kind: "spend",
    difficulty: "extreme",
    year: 2013,
    asOf: "2026-09",
    govt: "INC",
    question:
      "By March 2013 Maharashtra had set up 553 fodder camps for 4.52 lakh cattle in its drought districts. How much had Prithviraj Chavan's government distributed to run them?",
    options: ["₹74.9 crore", "₹749.29 crore", "₹2,000 crore", "₹7,492 crore"],
    correctIndex: 1,
    explanation:
      "Down To Earth listed ₹749.29 crore for the camps among relief measures that also sent water tankers to 1,663 villages; the relief secretary said the state had spent ₹2,000 crore on relief, with ₹1,000 crore more sanctioned for the summer. DTE argued villages with the most sugarcane were among the worst hit for drinking water, with cane even fed to cattle.",
    sourceUrl: "https://www.downtoearth.org.in/environment/drought-of-equity-40606",
    sourceLabel: "Down To Earth — Drought of equity (15 Mar 2013)",
    tags: ["relief"],
    enactedBy: [{ name: "Prithviraj Chavan", role: "Chief Minister, Maharashtra", party: "INC" }],
  },
  {
    id: "hrf114",
    domain: "civics",
    region: "India",
    state: "JK",
    topic: "Welfare & Subsidies",
    subtopic: "Kashmir floods relief package (2014)",
    kind: "scheme",
    difficulty: "expert",
    year: 2014,
    asOf: "2026-09",
    govt: "Other",
    question:
      "Announcing ₹200 crore from J&K's distress relief fund after the September 2014 floods, Omar Abdullah said it should be paid the way it was after the 2005 Uri earthquake. How?",
    options: [
      "In cash to the affected people",
      "As interest-free bank loans",
      "Through ration-card coupons",
      "As building material only",
    ],
    correctIndex: 0,
    explanation:
      "The Hindu (12 Sep 2014): ₹100 crore each for the Jammu and Kashmir divisions, paid in cash as after the Uri quake and the Ladakh cloudburst, plus six months' free ration including 50 kg of rice, without insisting on documents. Omar also asked the Centre to clear a ₹22,000 crore flood-management plan.",
    sourceUrl:
      "https://www.thehindu.com/news/national/Jammu-and-Kahsmir-floods-Omar-Abdullah-announces-relief-package/article60345806.ece",
    sourceLabel: "The Hindu — J&K floods: Omar announces relief package (12 Sep 2014)",
    sources: [
      "https://m.economictimes.com/news/politics-and-nation/rs-1102-crore-flood-relief-package-for-jammu-and-kashmir/articleshow/46827535.cms",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Omar Abdullah", role: "Chief Minister, Jammu & Kashmir", party: "JKNC" }],
    outcome:
      "In April 2015 the next government told the Assembly the Centre had approved only ₹1,102 crore against a requirement of ₹2,600 crore under SDRF norms, and that the state had made ₹1,044 crore available from its own SDRF (ET).",
  },

  // ───────────────────────── 2015–2019 ─────────────────────────
  {
    id: "hrf115",
    domain: "civics",
    region: "India",
    state: "UT",
    topic: "Governance & Institutions",
    subtopic: "Kedarnath relief bills (RTI, 2015)",
    kind: "scam",
    difficulty: "expert",
    year: 2015,
    asOf: "2026-09",
    govt: "INC",
    question:
      "RTI records released in 2015 alleged that officials on Uttarakhand's 2013 flood relief billed ₹194 for half a litre of milk. What did the state's own inquiry by the chief secretary conclude?",
    options: [
      "Referred the bills to the CBI",
      "Ordered recovery from 40 officers",
      "Found no irregularities — a clean chit",
      "Suspended the district magistrate",
    ],
    correctIndex: 2,
    explanation:
      "The RTI replies also showed hotel stays billed at over ₹6,700 a day and ₹25.19 lakh paid by Rudraprayag for officials' food and lodging. Information Commissioner Anil Kumar Sharma forwarded a plea for a CBI or independent probe; CM Harish Rawat instead ordered a chief secretary's inquiry, which found 'no irregularities anywhere'. The BJP kept demanding a CBI probe.",
    status:
      "Allegations from RTI records (May 2015); a committee headed by the chief secretary gave officials a clean chit (17 Jul 2015); the state did not take up the BJP's demand for a CBI probe (The Tribune, Dec 2015). No later proceedings found (checked Sep 2026).",
    otherSide:
      "The chief secretary's inquiry ordered by CM Harish Rawat found 'no irregularities anywhere' and gave the officials a clean chit (July 2015).",
    people: ["Harish Rawat", "Anil Kumar Sharma"],
    sourceUrl:
      "https://www.tribuneindia.com/news/archive/uttarakhand/security-breach-at-ias-academy-relief-scam-kept-state-in-news-176430/",
    sourceLabel: "The Tribune — Security breach at IAS academy, relief scam kept state in news (29 Dec 2015)",
    sources: [
      "https://www.indiatoday.in/mail-today/story/uttarakhand-floods-kedarnath-relief-fund-party-rti-291756-2015-05-30",
      "https://indianexpress.com/article/india/india-others/bjp-demands-cbi-probe-into-misuse-of-uttarakhand-flood-relief-funds/",
    ],
    tags: ["relief"],
  },
  {
    id: "hrf116",
    domain: "civics",
    region: "India",
    state: "UT",
    topic: "Governance & Institutions",
    subtopic: "CAG audit of the 2013 floods",
    kind: "institution",
    difficulty: "extreme",
    year: 2015,
    asOf: "2026-09",
    govt: "INC",
    question:
      "A CAG report tabled in November 2015 said ₹7,981 crore had been committed for relief and restoration after Uttarakhand's 2013 floods. About how much had actually been spent?",
    options: ["₹734 crore", "₹2,100 crore", "₹3,700 crore", "₹7,300 crore"],
    correctIndex: 0,
    explanation:
      "The CAG put spending at about ₹733.53 crore of the package for 2013–16, found delays in paying assistance in 92% of cases, and called the state disaster management authority 'virtually non-functional' before the disaster, which killed more than 4,000 people. The report was tabled in the Assembly on 3 Nov 2015.",
    sourceUrl: "https://www.livemint.com/Politics/F94DyJe65ya152ypFp15gO/CAG-report-slams-Uttarakhand-govt.html",
    sourceLabel: "Mint — CAG report slams Uttarakhand govt (6 Nov 2015)",
    tags: ["relief"],
  },
  {
    id: "hrf117",
    domain: "civics",
    region: "India",
    state: "TN",
    topic: "Welfare & Subsidies",
    subtopic: "Chennai floods relief stickers (2015)",
    kind: "scam",
    difficulty: "simple",
    year: 2015,
    asOf: "2026-09",
    govt: "AIADMK",
    question:
      "During the December 2015 Chennai floods, volunteers alleged they were made to paste what on relief material before they could hand it out?",
    options: [
      "Aadhaar numbers of the recipients",
      "Price tags for later resale",
      "Stickers of CM Jayalalithaa",
      "Logos of the donor companies",
    ],
    correctIndex: 2,
    explanation:
      "Relief workers told the BBC they were pressed to paste 'Amma' stickers on aid and in places made to wait for a minister before handing it out. The AIADMK denied the reports, asked for proof and promised action against 'errant' party workers. On 7 Dec 2015 Jayalalithaa announced ₹5,000 cash for flood-hit families and ₹10,000 for those who lost huts.",
    status:
      "Allegations by relief volunteers (Dec 2015); the AIADMK denied them and promised action against errant workers; no case is recorded in the cited reports.",
    otherSide:
      "The AIADMK denied the reports, asked for proof and promised action against any 'errant' party workers.",
    people: ["J. Jayalalithaa"],
    sourceUrl: "https://www.bbc.com/news/world-asia-india-35024134",
    sourceLabel: "BBC News — Chennai floods: India anger over Jayalalitha stickers on aid (7 Dec 2015)",
    sources: [
      "https://indianexpress.com/article/india/india-news-india/chennai-floods-aiadmk-men-paste-jaya-stickers-on-flood-relief-material/",
      "https://m.economictimes.com/news/politics-and-nation/tamil-nadu-cm-jayalalithaa-announces-relief-package-10000-houses-aid-to-farmers/articleshow/50078510.cms",
    ],
    tags: ["relief"],
    outcome:
      "Jayalalithaa's 7 Dec 2015 package added 10 kg of rice, a dhoti and a saree per family, with cash paid into bank accounts, and 10,000 tenements for families who lost homes on the Adyar and Cooum banks (ET).",
  },
  {
    id: "hrf118",
    domain: "civics",
    region: "India",
    state: "TN",
    topic: "Governance & Institutions",
    subtopic: "CAG on the 2015 Chennai floods",
    kind: "institution",
    difficulty: "expert",
    year: 2018,
    asOf: "2026-09",
    govt: "AIADMK",
    question:
      "A CAG report tabled in July 2018 called the 2015 Chennai floods 'man-made'. How many times had Tamil Nadu's disaster management authority, headed by the CM from 2013, met by April 2017?",
    options: ["Not once", "Twice", "Six times", "Every quarter"],
    correctIndex: 0,
    explanation:
      "The CAG said the authority was put under the CM only in November 2013, eight years after the Disaster Management Act, and did not meet once till April 2017. It also faulted releases from Chembarambakkam reservoir and the CMDA for allowing building on water bodies. Minister D. Jayakumar said he 'completely' disagreed and the department would reply.",
    sourceUrl:
      "https://www.indiatoday.in/india/story/cag-report-reveals-tamil-nadu-disaster-management-authority-did-not-meet-even-once-in-4-years-1283293-2018-07-11",
    sourceLabel: "India Today — CAG report reveals TN disaster management authority did not meet even once in 4 years (12 Jul 2018)",
    sources: ["https://www.thenewsminute.com/tamil-nadu/cag-report-slams-chennai-administration-2015-floods-says-govt-was-unprepared-84476"],
    tags: ["relief"],
  },
  {
    id: "hrf119",
    domain: "civics",
    region: "India",
    state: "KL",
    topic: "Governance & Institutions",
    subtopic: "Kerala 'salary challenge' (2018)",
    kind: "funding",
    difficulty: "expert",
    year: 2018,
    asOf: "2026-09",
    govt: "LDF",
    question:
      "Kerala asked its employees to give a month's salary to the CM's Distress Relief Fund after the 2018 floods. What did the Supreme Court do in October 2018?",
    options: [
      "Made the salary deduction compulsory",
      "Ordered the relief fund audited by the CAG",
      "Capped donations at one day's pay",
      "Dismissed Kerala's appeal against a High Court stay",
    ],
    correctIndex: 3,
    explanation:
      "The Kerala High Court had stayed the clause requiring staff unwilling to donate to file a 'letter of dissent', seeing an element of compulsion. Justices Arun Mishra and Vineet Saran dismissed the state's plea, saying donations need a voluntary spirit; the state remained free to collect from willing donors.",
    sourceUrl: "https://www.thehindu.com/news/national/kerala/sc-junks-kerala-order-on-salary-challenge/article25362589.ece",
    sourceLabel: "The Hindu — SC junks Kerala order on Salary Challenge (29 Oct 2018)",
    sources: [
      "https://www.newindianexpress.com/states/kerala/2018/Oct/10/salary-challenge-kerala-high-court-stays-government-mandate-on-letter-of-dissent-1883390.html",
      "https://www.indiatoday.in/magazine/interview/story/20180910-need-everyone-s-support-to-rebuild-kerala-cm-pinarayi-vijayan-1327249-2018-09-01",
      "https://www.onmanorama.com/news/kerala/2023/11/28/cmdrf-portal-revises-figures-related-flood-funds-following-manorama-report.html",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Pinarayi Vijayan", role: "Chief Minister, Kerala", party: "CPI(M)" }],
    outcome:
      "The CMDRF portal later showed ₹4,970.29 crore received for the 2018 and 2019 floods and ₹4,724.43 crore allotted — figures revised in Nov 2023 after a Malayala Manorama report had put spending at ₹4,140 crore.",
  },
  {
    id: "hrf120",
    domain: "civics",
    region: "India",
    state: "AP",
    topic: "Governance & Institutions",
    subtopic: "Cyclone Titli loss claim (2018)",
    kind: "spend",
    difficulty: "extreme",
    year: 2018,
    asOf: "2026-09",
    govt: "TDP",
    question:
      "In October 2018 Andhra CM Chandrababu Naidu told a visiting central team that Cyclone Titli had caused losses of about how much, and said the Centre had not replied to his letter?",
    options: ["₹367 crore", "₹1,200 crore", "₹3,673 crore", "₹36,730 crore"],
    correctIndex: 2,
    explanation:
      "Naidu put the loss at ₹3,673.10 crore; the cyclone had uprooted coconut and cashew trees in Srikakulam's Uddanam region. He complained that the Union Home Minister had visited Andhra for a party event but not the cyclone-hit areas. The team's leader, MHA joint secretary Sanjeev Kumar Jindal, said it was satisfied with the state's rescue and relief work.",
    sourceUrl: "https://www.thenewsminute.com/andhra-pradesh/cyclone-titli-central-team-meets-andhra-cm-naidu-urges-quick-release-aid-90642",
    sourceLabel: "The News Minute — Cyclone Titli: Central team meets Andhra CM, Naidu urges quick release of aid (27 Oct 2018)",
    sources: ["https://www.newindianexpress.com/states/kerala/2018/Dec/06/centre-approves-additional-rs-3048-crore-flood-relief-for-kerala-1908097.html"],
    tags: ["relief"],
    outcome:
      "Naidu said the state had arranged for victims to receive compensation within 20 days of the cyclone; a central high-level committee approved additional NDRF aid for Andhra in December 2018.",
  },
  {
    id: "hrf121",
    domain: "civics",
    region: "India",
    state: "OD",
    topic: "Welfare & Subsidies",
    subtopic: "Cyclone Fani relief package (2019)",
    kind: "scheme",
    difficulty: "simple",
    year: 2019,
    asOf: "2026-09",
    govt: "BJD",
    question:
      "After Cyclone Fani made landfall at Puri on 3 May 2019, Naveen Patnaik's relief package gave food-security families in the worst-hit areas 50 kg of rice, polythene sheets and how much cash?",
    options: ["₹100", "₹250", "₹500", "₹2,000"],
    correctIndex: 3,
    explanation:
      "Families in Puri and the worst-hit parts of Khurda got ₹2,000; the rest of Khurda ₹1,000 and a month's rice; Cuttack, Kendrapara and Jagatsinghpur ₹500. Fully damaged houses were to get ₹95,100. Officials said about 1.08 crore people in 14,835 villages were affected and 13.41 lakh had been evacuated in 24 hours.",
    sourceUrl:
      "https://timesofindia.indiatimes.com/india/cyclone-fani-toll-jumps-to-34-in-odisha-cm-naveen-patnaik-announces-relief-package/articleshow/69190600.cms",
    sourceLabel: "The Times of India — Cyclone Fani toll jumps to 34, CM Naveen Patnaik announces relief package (5 May 2019)",
    sources: ["https://indianexpress.com/article/india/cyclone-fani-news-contribution-of-states-to-odisha-5711627/"],
    tags: ["relief"],
    enactedBy: [{ name: "Naveen Patnaik", role: "Chief Minister, Odisha", party: "BJD" }],
  },
  {
    id: "hrf122",
    domain: "civics",
    region: "India",
    state: "KA",
    topic: "Governance & Institutions",
    subtopic: "Karnataka floods central aid (2019)",
    kind: "spend",
    difficulty: "expert",
    year: 2019,
    asOf: "2026-09",
    govt: "BJP",
    question:
      "BJP-ruled Karnataka put its August 2019 flood losses at ₹35,160 crore. How much did the BJP-led Centre release on 4 October 2019, after weeks of criticism over the delay?",
    options: ["₹120 crore", "₹3,500 crore", "₹12,000 crore", "₹1,200 crore"],
    correctIndex: 3,
    explanation:
      "Frontline reported the ₹1,200 crore release under the SDRF and NDRF. The Congress said Karnataka was 'humiliated'; its Krishna Byre Gowda said ₹303 crore of it was SDRF money, leaving ₹897 crore from the NDRF. A BJP state general secretary called it a first instalment and said Karnataka was the first of 13 flood-hit states to get aid.",
    sourceUrl: "https://frontline.thehindu.com/the-nation/article29766585.ece",
    sourceLabel: "Frontline — Protests in Karnataka over Centre's flood relief aid (25 Oct 2019)",
    tags: ["relief"],
    outcome:
      "A state disaster official said six lakh people were relocated; the BJP state general secretary said the state had already spent ₹3,100 crore on relief. The loss estimate was cut from ₹38,451 crore after the Centre said private property was not covered by NDRF norms.",
  },

  // ───────────────────────── 2020–2026 ─────────────────────────
  {
    id: "hrf123",
    domain: "civics",
    region: "India",
    state: "WB",
    topic: "Governance & Institutions",
    subtopic: "Cyclone Amphan relief audit",
    kind: "scam",
    difficulty: "extreme",
    year: 2020,
    asOf: "2026-09",
    govt: "TMC",
    question:
      "The CAG's audit of Cyclone Amphan relief, tabled in July 2026, found house-building grants credited more than once — up to nine times — to how many beneficiaries?",
    options: ["926", "9,226", "92,260", "1.9 lakh"],
    correctIndex: 1,
    explanation:
      "Checking 19.38 lakh beneficiaries in six districts, the CAG found 18,891 repeat transactions to 9,226 people, identical photos in 3,126 claims, and 71% of the house grant in two districts parked in commercial bank accounts. It asked the state to probe and recover the money. TMC leader Kunal Ghosh questioned the report's neutrality.",
    status:
      "CAG audit findings (tabled 25 Jul 2026; audit ordered by the Calcutta High Court, Dec 2020); an audit does not establish criminal liability. The BJP state government said it would seek FIRs; police complaints over Amphan relief have been filed since May 2026, but no chargesheet was reported as of Sep 2026.",
    otherSide:
      "TMC leader Kunal Ghosh questioned the report's neutrality; an audit finding does not establish criminal liability.",
    people: ["Kunal Ghosh"],
    sourceUrl: "https://indianexpress.com/article/political-pulse/cag-flags-cyclone-amphan-2020-relief-irregularities-tmc-west-bengal-10811195/",
    sourceLabel: "The Indian Express — 'Same photos, many claims': the CAG's Amphan relief audit (31 Jul 2026)",
    sources: [
      "https://english.mathrubhumi.com/news/money/cag-report-west-bengal-amphan-relief-irregularities-viy5s90w",
      "https://www.newindianexpress.com/india/2021/Jan/21/calcutta-hc-junks-mamata-governmentplea-over-amphan-relief-audit-2252865.html",
      "https://courtbook.in/posts/calcutta-high-court-protects-abhishek-banerjee-from-coercive-action-in-three-firs",
    ],
    tags: ["relief"],
    outcome:
      "The CAG said the TMC government's damage claims to the Centre were inflated by nearly ₹32,000 crore; the MHA had released ₹2,250.28 crore from the NDRF after adjusting the state's SDRF balance.",
  },
  {
    id: "hrf124",
    domain: "civics",
    region: "India",
    state: "TG",
    topic: "Welfare & Subsidies",
    subtopic: "Hyderabad flood relief ₹10,000 (2020)",
    kind: "scheme",
    difficulty: "simple",
    year: 2020,
    asOf: "2026-09",
    govt: "BRS",
    question:
      "In November 2020 Telangana's State Election Commission ordered a halt, citing the Model Code of Conduct for the Hyderabad civic poll. What did it stop?",
    options: [
      "Free drinking-water connections",
      "Bathukamma saree distribution",
      "Rythu Bandhu farm transfers",
      "₹10,000 flood-relief payments to families",
    ],
    correctIndex: 3,
    explanation:
      "KCR announced ₹10,000 for each flood-hit family on 19 Oct 2020; by 18 Nov, 6.64 lakh families had got ₹664 crore. The Congress alleged TRS agents handed out the cash as a 'vote bank' ploy. The SEC paused registration and payments until the 1 Dec poll; they resumed after the results, and about 1.3 lakh applicants were still unpaid in mid-December.",
    sourceUrl: "https://www.thehindu.com/news/cities/Hyderabad/ec-slams-brakes-on-flood-relief-grant/article33127742.ece",
    sourceLabel: "The Hindu — EC slams brakes on flood relief grant (18 Nov 2020)",
    sources: [
      "https://timesofindia.indiatimes.com/city/hyderabad/telangana-govt-announces-rs-10000-financial-assistance-to-rain-affected-families/articleshow/78749285.cms",
      "https://www.thenewsminute.com/telangana/cong-alleges-trs-used-flood-relief-funds-propaganda-136922",
      "https://www.deccanchronicle.com/nation/in-other-news/141220/13-lakh-flood-victims-fail-to-get-rs-10000-relief-in-telangana.html",
      "https://timesofindia.indiatimes.com/city/hyderabad/hyderabad-municipal-election-results-2020-highlights/articleshow/79557664.cms",
      "https://newsmeter.in/politics/trs-gets-one-more-seat-meena-upendra-reddy-wins-from-neredmet-671540",
    ],
    tags: ["relief", "pre-election"],
    enactedBy: [{ name: "K. Chandrasekhar Rao", role: "Chief Minister, Telangana", party: "TRS (now BRS)" }],
    outcome:
      "In the GHMC poll the TRS won 56 of 150 wards (its 56th after a withheld count in Neredmet), the BJP 48, the AIMIM 44 and the Congress 2.",
    poll: {
      label: "GHMC (Hyderabad) civic poll 2020",
      month: "2020-12",
      gapDays: 43,
      result: "TRS 56 of 150 wards, BJP 48, AIMIM 44, Congress 2",
    },
  },
  {
    id: "hrf125",
    domain: "civics",
    region: "India",
    state: "MH",
    topic: "Health",
    subtopic: "CM's Covid-19 Relief Fund (Maharashtra)",
    kind: "funding",
    difficulty: "expert",
    year: 2021,
    asOf: "2026-09",
    govt: "SS",
    question:
      "An RTI reply in November 2021 showed Maharashtra's CM Covid-19 Relief Fund held ₹799 crore. What was its single biggest spend?",
    options: [
      "Oxygen plants in district hospitals",
      "Ventilators for Mumbai's jumbo centres",
      "Train fares for migrant workers",
      "Vaccines for the 18–44 age group",
    ],
    correctIndex: 2,
    explanation:
      "Only ₹192 crore (24%) had been spent, leaving ₹606.3 crore unused. The largest item was ₹82.4 crore for migrant labourers' rail fares across 36 districts, followed by ₹49.8 crore for Covid care for sex workers. The CM's office told TOI it could not yet say whether fresh donations would stop, and TOI found no stated plan for the unspent balance.",
    sourceUrl: "https://timesofindia.indiatimes.com/city/mumbai/only-24-of-rs-799cr-in-cms-covid-fund-has-been-used-rti/articleshow/87857043.cms",
    sourceLabel: "The Times of India — Only 24% of Rs 799 crore in CM's Covid fund has been used: RTI (23 Nov 2021)",
    tags: ["relief"],
    enactedBy: [{ name: "Uddhav Thackeray", role: "Chief Minister, Maharashtra", party: "Shiv Sena" }],
  },
  {
    id: "hrf126",
    domain: "civics",
    region: "India",
    state: "DL",
    topic: "Welfare & Subsidies",
    subtopic: "Covid-19 family aid scheme (Delhi, 2021)",
    kind: "scheme",
    difficulty: "simple",
    year: 2021,
    asOf: "2026-09",
    govt: "AAP",
    question:
      "Delhi's Covid-19 family aid scheme, notified in June 2021, paid ₹50,000 to each family that lost a member to Covid. What else did it pay if the sole breadwinner had died?",
    options: ["₹2,500 a month", "₹10 lakh insurance cover", "Free rations for five years", "A ₹5 lakh fixed deposit"],
    correctIndex: 0,
    explanation:
      "Announced by Arvind Kejriwal on 18 May 2021, the Mukhyamantri Covid-19 Pariwar Aarthik Sahayata Yojana had no income limit; children who lost a parent also get ₹2,500 a month till 25. When the Supreme Court approved a national ₹50,000 ex gratia in Oct 2021, it said that sum came over and above state schemes.",
    sourceUrl: "https://www.livemint.com/news/india/rs-50k-ex-gratia-monthly-pension-delhi-govt-notifies-scheme-for-covid-victims-kin-11624405671692.html",
    sourceLabel: "Mint — ₹50K ex-gratia, monthly pension: Delhi govt notifies scheme for Covid victims' kin (23 Jun 2021)",
    sources: [
      "https://timesofindia.indiatimes.com/city/delhi/delhi-govt-provides-rs-50000-to-21235-people-under-covid-scheme/articleshow/88262297.cms",
      "https://indianexpress.com/article/india/supreme-court-covid-19-compensation-7550935/",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Arvind Kejriwal", role: "Chief Minister, Delhi", party: "AAP" }],
    outcome:
      "By 13 Dec 2021, 21,235 of 25,100 applicants had got the ₹50,000; about 2,000 declined it and 7,955 were receiving the ₹2,500 monthly aid, the social welfare minister said (TOI).",
  },
  {
    id: "hrf127",
    domain: "civics",
    region: "India",
    state: "GJ",
    topic: "Health",
    subtopic: "Covid ex gratia claims (Gujarat)",
    kind: "institution",
    difficulty: "extreme",
    year: 2021,
    asOf: "2026-09",
    govt: "BJP",
    question:
      "Paying the Supreme Court-ordered Covid ex gratia, Gujarat told the court in December 2021 it had approved how many claims — against an official toll of 10,099 deaths?",
    options: ["8,450", "16,175", "40,000", "2.81 lakh"],
    correctIndex: 1,
    explanation:
      "Its affidavit, reported by Reuters, listed 22,557 applications and 16,175 approvals; an official said applications had since passed 40,000. The Congress said its surveys showed at least 55,000 deaths; the revenue minister did not respond. In March 2022 the court allowed random checks of 5% of claims in Gujarat, Andhra, Kerala and Maharashtra, where claims far exceeded recorded deaths.",
    sourceUrl: "https://www.aljazeera.com/news/2021/12/14/india-gujarat-covid-deaths-official-tally",
    sourceLabel: "Al Jazeera (Reuters) — India's Gujarat admits to more COVID deaths than official tally (14 Dec 2021)",
    sources: [
      "https://www.rediff.com/news/report/covid-deaths-govt-can-verify-5-ex-gratia-claims-in-4-states-says-sc/20220324.htm",
      "https://indianexpress.com/article/explained/explained-gujarat-covid-19-deaths-disbursal-ex-gratia-7643454/",
    ],
    tags: ["relief"],
  },
  {
    id: "hrf128",
    domain: "civics",
    region: "India",
    state: "KL",
    topic: "Governance & Institutions",
    subtopic: "Ernakulam flood-fund diversion case",
    kind: "scam",
    difficulty: "extreme",
    year: 2021,
    asOf: "2026-09",
    govt: "LDF",
    question:
      "In February 2021 Kerala's Crime Branch chargesheeted seven people, including a collectorate clerk and two local CPI(M) functionaries, over 2018 flood relief from the CM's fund. How much did it say was diverted?",
    options: ["₹2.77 lakh", "₹27.73 lakh", "₹2.77 crore", "₹27.7 crore"],
    correctIndex: 1,
    explanation:
      "The 1,267-page chargesheet at the Muvattupuzha vigilance court said the clerk altered flood victims' lists and bank details to route ₹27.73 lakh to co-accused. The accused got statutory bail after delays, which the Opposition said were meant to shield CPI(M) leaders; other bank and collectorate staff got a clean chit.",
    status:
      "Chargesheeted (Feb 2021) before the Muvattupuzha vigilance court; accused on statutory bail; no verdict or conviction reported in sources checked (Sep 2026).",
    otherSide:
      "The CPI(M) expelled its local members among the accused in March 2020; other bank and collectorate staff got a clean chit, and no court has ruled on the case.",
    sourceUrl: "https://www.newindianexpress.com/cities/kochi/2021/Feb/09/flood-fund-case-crime-branch-chargesheets-seven-persons-2261442.html",
    sourceLabel: "The New Indian Express — Flood fund case: Crime Branch chargesheets seven persons (9 Feb 2021)",
    sources: [
      "https://www.thenewsminute.com/kerala/rs-23-lakh-misappropriated-kerala-cm-s-flood-relief-fund-says-crime-branch-120275",
      "https://www.thehindu.com/news/cities/Kochi/flood-relief-scam-cpim-expels-party-workers/article31004642.ece",
    ],
    tags: ["relief"],
    outcome:
      "The CPI(M) expelled its local members among the accused in March 2020, after they were arraigned in the case (The Hindu). By Feb 2021 the Crime Branch had recovered ₹10.58 lakh of the ₹27.73 lakh.",
  },
  {
    id: "hrf129",
    domain: "civics",
    region: "India",
    state: "AP",
    topic: "Governance & Institutions",
    subtopic: "SDRF money diverted (Andhra, 2022)",
    kind: "spend",
    difficulty: "expert",
    year: 2022,
    asOf: "2026-09",
    govt: "YSRCP",
    question:
      "After Supreme Court criticism during the Covid ex gratia hearings, Andhra Pradesh agreed in July 2022 to return ₹1,100 crore to its SDRF. Where had the money been moved?",
    options: [
      "A deposit account of the Agriculture Commissioner",
      "The Amma Vodi school scheme",
      "The CM's Relief Fund",
      "A state road development corporation",
    ],
    correctIndex: 0,
    explanation:
      "Justices M.R. Shah and B.V. Nagarathna had said SDRF money cannot be diverted for other purposes. The state's counsel said the ₹1,100 crore would go back from the Agriculture Commissioner's personal deposit account within two weeks; the bench said it could then be used for Covid compensation under the Disaster Management Act.",
    sourceUrl: "https://www.livelaw.in/top-stories/supreme-court-covid-19-ex-gratia-compensation-andhra-pradesh-state-disaster-relief-fund-204099",
    sourceLabel: "LiveLaw — After SC's criticism, Andhra Pradesh agrees to revert Rs 1,100 crore to SDRF (18 Jul 2022)",
    tags: ["relief"],
  },
  {
    id: "hrf130",
    domain: "civics",
    region: "India",
    state: "AS",
    topic: "Welfare & Subsidies",
    subtopic: "Assam floods cash relief (2022)",
    kind: "scheme",
    difficulty: "simple",
    year: 2022,
    asOf: "2026-09",
    govt: "BJP",
    question:
      "After the 2022 floods, which CM Himanta Biswa Sarma called Assam's worst ever for casualties, how much did his government pay each of 1.81 lakh affected families?",
    options: ["₹1,000", "₹3,800", "₹15,000", "₹38,000"],
    correctIndex: 1,
    explanation:
      "Sarma said 195 people died and about 90 lakh were affected. Besides ₹3,800 per family, 1.01 lakh students got ₹1,000 each for textbooks, and he said about ₹400 crore would be spent rebuilding damaged houses (3.04 lakh were hit). He said there was 'no package as such' but the Centre was bearing 90% of the cost.",
    sourceUrl: "https://www.newindianexpress.com/india/2022/Jul/16/recent-assam-floods-worst-ever-has-highest-ever-casualties-says-cm-himanta-as-toll-touches-195-2477299.html",
    sourceLabel: "The New Indian Express — Recent Assam floods worst ever, says CM Himanta as toll touches 195 (16 Jul 2022)",
    sources: ["https://assamtribune.com/assam/assam-floods-rs-15000-relief-falls-far-short-as-rebuilding-costs-soar-1617232"],
    tags: ["relief"],
    enactedBy: [{ name: "Himanta Biswa Sarma", role: "Chief Minister, Assam", party: "BJP" }],
    outcome:
      "After the 2026 floods in Upper Assam the state paid ₹15,000 as initial relief to 1.17 lakh families; some families told The Assam Tribune in Sept 2026 they had yet to receive it, and others said it fell far short of rebuilding costs.",
  },
  {
    id: "hrf131",
    domain: "civics",
    region: "India",
    state: "HP",
    topic: "Governance & Institutions",
    subtopic: "Himachal flood relief 'bandarbant' row (2024)",
    kind: "spend",
    difficulty: "extreme",
    year: 2024,
    asOf: "2026-09",
    govt: "INC",
    question:
      "At May 2024 rallies PM Modi alleged 'bandarbant' of Centre-sent flood relief in Himachal. How much had the state received under the SDRF and NDRF across 2023 and 2024, per official records?",
    options: ["₹148 crore", "₹4,500 crore", "₹9,900 crore", "₹1,148 crore"],
    correctIndex: 3,
    explanation:
      "Records cited by The Indian Express: ₹360.80 crore via the SDRF and ₹787.25 crore via the NDRF. The BJP's Jai Ram Thakur alleged cash handouts through Congress MLAs, but no formal complaint had been filed. CM Sukhvinder Singh Sukhu's media adviser called the charge baseless; Sukhu said the Centre had not approved the state's ₹9,900 crore demand.",
    status:
      "Political allegation (May 2024); no official complaint had been filed (The Indian Express, 30 May 2024); the Himachal government called it baseless. No later complaint or probe found (checked Sep 2026).",
    people: ["Narendra Modi", "Jai Ram Thakur", "Sukhvinder Singh Sukhu"],
    sourceUrl: "https://indianexpress.com/article/political-pulse/decode-politics-why-pm-modi-is-talking-of-bandarbant-in-himachal-9360120/",
    sourceLabel: "The Indian Express — Decode politics: Why PM Modi is talking of 'bandarbant' in Himachal (30 May 2024)",
    sources: ["https://www.hindustantimes.com/cities/chandigarh-news/year-after-monsoon-mayhem-himachal-still-on-long-road-to-recovery-101720193123856.html"],
    tags: ["relief"],
    outcome:
      "After the 2023 monsoon disaster (441 deaths), Himachal raised compensation for a fully destroyed house from ₹1.3 lakh to ₹7 lakh and set aside ₹4,500 crore; a year on, a Mandi councillor said families who lost houses had got only ₹3 lakh (HT).",
  },
  {
    id: "hrf132",
    domain: "civics",
    region: "India",
    state: "TN",
    topic: "Welfare & Subsidies",
    subtopic: "Cyclone Michaung ₹6,000 relief (2023)",
    kind: "scheme",
    difficulty: "simple",
    year: 2023,
    asOf: "2026-09",
    govt: "DMK",
    question:
      "How did Tamil Nadu hand out its ₹6,000 cash relief to families hit by Cyclone Michaung in Chennai and three neighbouring districts in December 2023?",
    options: [
      "By bank transfer only",
      "Through post offices",
      "At ward councillors' offices",
      "At ration (fair-price) shops",
    ],
    correctIndex: 3,
    explanation:
      "Announced by M.K. Stalin on 9 Dec 2023 with ₹1,486.94 crore set aside, the cash went to 24.25 lakh eligible ration cardholders, and 5.28 lakh more families could apply. Officials said 90–96% of listed beneficiaries were paid within days, and 5.56 lakh fresh applications came in.",
    sourceUrl: "https://www.newindianexpress.com/states/tamil-nadu/2023/Dec/22/567-lakh-families-applyfor-rs-6000-michaungrelief-in-tn-92-receive-aid-2643834.html",
    sourceLabel: "The New Indian Express — 5.67 lakh families apply for Rs 6,000 Michaung relief in TN (22 Dec 2023)",
    sources: [
      "https://www.indiatoday.in/india/story/tamil-nadu-chief-minister-mk-stalin-announces-rs-6000-cash-aid-to-people-affected-by-cyclone-michaung-2474035-2023-12-09",
      "https://www.newindianexpress.com/states/tamil-nadu/2024/Apr/28/centre-gives-tn-rs-276cr-flood-relief-cm-stalin-slams-bjp-for-meagre-sum",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "M.K. Stalin", role: "Chief Minister, Tamil Nadu", party: "DMK" }],
    outcome:
      "The state sought ₹37,907 crore for Michaung and the southern floods and went to the Supreme Court. In April 2024 the Centre released ₹276.10 crore: ₹682.67 crore approved minus half the state's SDRF balance.",
  },
  {
    id: "hrf133",
    domain: "civics",
    region: "India",
    state: "KA",
    topic: "Governance & Institutions",
    subtopic: "Drought relief after SC petition (2024)",
    kind: "spend",
    difficulty: "expert",
    year: 2024,
    asOf: "2026-09",
    govt: "INC",
    question:
      "Karnataka moved the Supreme Court in 2024 after seeking ₹18,171 crore in NDRF drought aid. How much did the Centre approve on 26 April, the day half the state voted in the Lok Sabha poll?",
    options: ["₹345 crore", "₹3,454 crore", "₹9,000 crore", "₹18,171 crore"],
    correctIndex: 1,
    explanation:
      "A committee chaired by Amit Shah approved ₹3,454 crore after the Centre told the court the Election Commission had cleared the decision. CM Siddaramaiah said it was not even a quarter of what NDRF norms required, vowed to fight on, and said the court had asked both sides to settle the amount. The state had paid ₹2,000 each to over 33 lakh farmers.",
    sourceUrl: "https://www.thenewsminute.com/karnataka/union-government-releases-rs-3454-crore-as-drought-relief-to-karnataka",
    sourceLabel: "The News Minute — Union government releases Rs 3,454 crore as drought relief to Karnataka (27 Apr 2024)",
    sources: [
      "https://www.thehindu.com/news/national/karnataka/centres-drought-relief-is-not-even-a-quarter-of-amount-required-to-be-paid-as-per-ndrf-norms-siddaramaiah/article68114472.ece",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Amit Shah", role: "Union Home Minister", party: "BJP" }],
    outcome:
      "Karnataka had declared 223 taluks drought-hit and put crop losses at ₹35,162 crore on 48 lakh hectares. The rest of the state voted on 7 May 2024.",
  },
  {
    id: "hrf134",
    domain: "civics",
    region: "India",
    state: "MP",
    topic: "Governance & Institutions",
    subtopic: "Sheopur flood-compensation fraud case",
    kind: "scam",
    difficulty: "extreme",
    year: 2026,
    asOf: "2026-09",
    govt: "BJP",
    question:
      "Police in Madhya Pradesh's Sheopur district allege 2021 flood compensation meant for 794 residents of Baroda tehsil was diverted. Into how many fake or unrelated bank accounts, per an audit?",
    options: ["At least 12", "At least 127", "At least 480", "At least 1,270"],
    correctIndex: 1,
    explanation:
      "Investigators allege a ₹2–2.5 crore fraud and have named over 100 people, including more than two dozen patwaris. A former tehsildar was arrested on 26 March 2026 after the MP High Court and the Supreme Court refused her anticipatory bail; her lawyers say she was falsely implicated, only signed files prepared by others and received no money.",
    status:
      "FIR (Sep 2023) widened to Prevention of Corruption Act offences in Mar 2026; a former tehsildar arrested (26 Mar 2026) denies the charges; by May 2026 police had arrested at least 30 of 110 accused and prosecution was sanctioned for her and 18 patwaris. No chargesheet or verdict reported (checked Sep 2026).",
    otherSide:
      "The arrested former tehsildar denies the charges: her lawyers say she was falsely implicated, only signed files prepared by others and received no money.",
    sourceUrl: "https://indianexpress.com/article/india/from-kbc-fame-to-corruption-arrest-tehsildar-who-sat-opposite-amitabh-bachchan-in-2019-lands-in-jail-10603907/",
    sourceLabel: "The Indian Express — From KBC fame to 'corruption' arrest, tehsildar lands in jail (27 Mar 2026)",
    sources: [
      "https://www.hindustantimes.com/india-news/kaun-banega-crorepati-fame-woman-tehsildar-held-in-relation-to-flood-relief-scam-in-mps-sheopur-101774593787911.html",
      "https://indianexpress.com/article/india/in-madhya-pradesh-a-kbc-winning-tehsildar-a-flood-relief-scam-and-hundreds-of-farmers-in-limbo-10664818/",
      "https://m.economictimes.com/news/new-updates/gwalior-govt-babu-who-won-rs-50-lakh-in-kbc-arrested-in-rs-2-5-crore-flood-relief-scam/articleshow/129844665.cms",
    ],
    tags: ["relief"],
  },
  {
    id: "hrf135",
    domain: "civics",
    region: "India",
    state: "KL",
    topic: "Governance & Institutions",
    subtopic: "Wayanad relief memorandum row (2024)",
    kind: "spend",
    difficulty: "simple",
    year: 2024,
    asOf: "2026-09",
    govt: "LDF",
    question:
      "In September 2024 the Opposition attacked Kerala's Wayanad relief memorandum to the Centre for estimating ₹75,000 per what?",
    options: [
      "Funeral of a landslide victim",
      "Week of meals for a volunteer",
      "Night in a relief camp",
      "Helicopter sortie",
    ],
    correctIndex: 0,
    explanation:
      "The memo estimated ₹1,202 crore for relief, including ₹2.76 crore for 359 funerals. Then Opposition leader V.D. Satheesan said volunteers and families had done the burials; the BJP's K. Surendran alleged the state was exploiting the disaster. The CM's office said the figures were estimates under NDRF norms, not money spent, and that misreporting hurt Kerala's bid for central aid.",
    status:
      "Political allegations (Sep 2024); the government said the figures were NDRF-norm estimates, not expenditure; no case or inquiry found (checked Sep 2026).",
    people: ["V.D. Satheesan", "K. Surendran", "Pinarayi Vijayan"],
    sourceUrl: "https://www.thenewsminute.com/kerala/wayanad-landslides-kerala-govts-memo-estimating-financial-aid-triggers-controversy",
    sourceLabel: "The News Minute — Wayanad landslides: Kerala govt's memo estimating financial aid triggers controversy (17 Sep 2024)",
    sources: [
      "https://www.thehindu.com/news/national/kerala/cost-estimation-and-expenses-of-wayanad-relief-measures-trigger-a-controversy/article68648560.ece",
      "https://timesofindia.indiatimes.com/city/thiruvananthapuram/kerala-government-reveals-actual-cremation-costs-after-wayanad-landslide-controversy/articleshow/114321335.cms",
    ],
    tags: ["relief"],
    outcome:
      "In October 2024 Revenue Minister K. Rajan told the Assembly that actual cremation spending was ₹19.67 lakh; CM Pinarayi Vijayan said the memorandum followed national norms (TOI).",
  },
  {
    id: "hrf136",
    domain: "civics",
    region: "India",
    state: "BR",
    topic: "Welfare & Subsidies",
    subtopic: "Flood gratuitous relief ₹7,000 (2025)",
    kind: "scheme",
    difficulty: "expert",
    year: 2025,
    asOf: "2026-09",
    govt: "JDU",
    question:
      "On 20 August 2025, 78 days before Bihar's Assembly poll began, Nitish Kumar transferred ₹456 crore to 6.51 lakh flood-hit families. How much did each family get?",
    options: ["₹2,500", "₹6,000", "₹10,000", "₹7,000"],
    correctIndex: 3,
    explanation:
      "The CM's office said ₹456.12 crore went directly into the bank accounts of 6,51,602 families in 12 districts as gratuitous relief, after Nitish raised the per-family amount from ₹6,000 to ₹7,000. Polling followed on 6 and 11 November 2025.",
    sourceUrl: "https://m.economictimes.com/news/india/bihar-cm-transfers-rs-456-cr-to-bank-accounts-of-flood-hit-families/articleshow/123404600.cms",
    sourceLabel: "The Economic Times (PTI) — Bihar CM transfers Rs 456 cr to bank accounts of flood-hit families (20 Aug 2025)",
    sources: [
      "https://www.thehindu.com/elections/bihar-assembly/bihar-assembly-elections-2025-when-will-bihar-vote-key-dates-phases-and-counting-schedule/article70192841.ece",
      "https://m.thewire.in/article/politics/six-key-takeaways-nda-bihar-sweep-bjp-largest-party",
    ],
    tags: ["relief", "pre-election"],
    enactedBy: [{ name: "Nitish Kumar", role: "Chief Minister, Bihar", party: "JD(U)" }],
    outcome:
      "The NDA won 202 of 243 seats; the BJP (89) became the largest party and the JD(U) won 85, up from 43 in 2020 (The Wire).",
    poll: {
      label: "Bihar Assembly 2025",
      month: "2025-11",
      gapDays: 78,
      result: "NDA won 202 of 243 seats (BJP 89, JD(U) 85); RJD 25",
    },
  },
  {
    id: "hrf137",
    domain: "civics",
    region: "India",
    state: "PB",
    topic: "Governance & Institutions",
    subtopic: "Punjab floods SDRF dispute (2025)",
    kind: "spend",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "AAP",
    question:
      "As Punjab pressed for more flood aid in September 2025, the Union Home Ministry said the state's disaster response fund already held how much?",
    options: ["₹1,600 crore", "₹5,012 crore", "₹12,589 crore", "₹20,000 crore"],
    correctIndex: 2,
    explanation:
      "The MHA said Punjab had ₹12,589.59 crore in its SDRF and had not yet sent a damage memorandum. CM Bhagwant Mann said only ₹5,012 crore had come into the fund since 2010, of which ₹3,820 crore was spent. The Assembly condemned PM Modi's ₹1,600 crore announcement as 'meagre'; the MHA said ₹805 crore of it had been released.",
    sourceUrl: "https://indianexpress.com/article/cities/chandigarh/punjab-flood-relief-mann-says-shah-promised-more-mha-utlise-rs-12589-cr-sdrf-10281114/",
    sourceLabel: "The Indian Express — Punjab flood relief: Mann says Shah promised more; MHA: 'utilise Rs 12,589 cr SDRF' (1 Oct 2025)",
    sources: [
      "https://timesofindia.indiatimes.com/city/chandigarh/got-rs-5012cr-in-sdrf-since-2010-cm-refutes-bjps-rs-12000cr-claim/articleshow/123873654.cms",
    ],
    tags: ["relief"],
  },
  {
    id: "hrf138",
    domain: "civics",
    region: "India",
    state: "PB",
    topic: "Farm & Food",
    subtopic: "Flood crop compensation ₹20,000/acre (2025)",
    kind: "scheme",
    difficulty: "simple",
    year: 2025,
    asOf: "2026-09",
    govt: "AAP",
    question:
      "What per-acre compensation did Punjab's AAP government announce in September 2025 for farmers who lost 75–100% of their crop to floods, calling it the state's highest ever?",
    options: ["₹6,800", "₹12,000", "₹20,000", "₹50,000"],
    correctIndex: 2,
    explanation:
      "Farmers told The Indian Express that after the 2023 floods they got only ₹6,800 an acre (the Centre's share), capped at five acres; some called the new sum 'peanuts' against their losses, recalling that Bhagwant Mann had spoken of ₹50,000. Payments began by bank transfer on 13 Oct 2025 after a special crop-loss survey.",
    sourceUrl: "https://indianexpress.com/article/cities/chandigarh/punjab-flood-compensation-farmers-aid-10238014/",
    sourceLabel: "The Indian Express — Punjab announces 'highest-ever' flood compensation of Rs 20,000 per acre (8 Sep 2025)",
    sources: [
      "https://timesofindia.indiatimes.com/india/punjab-flood-relief-aap-government-begins-compensating-farmers-rs-20000/acre-aid-transferred-directly-via-online-portal/articleshow/124526483.cms",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Bhagwant Mann", role: "Chief Minister, Punjab", party: "AAP" }],
    outcome:
      "Crops were damaged on about 3.5 lakh acres in 2,508 villages. Aid for partly damaged houses rose from ₹6,500 to ₹40,000 and ₹4 lakh was fixed per death (TOI, Oct 2025).",
  },
  {
    id: "hrf139",
    domain: "civics",
    region: "India",
    state: "KL",
    topic: "Governance & Institutions",
    subtopic: "CMDRF misuse complaint (Lokayukta)",
    kind: "scam",
    difficulty: "expert",
    year: 2023,
    asOf: "2026-09",
    govt: "LDF",
    question:
      "A 2018 complaint alleged Pinarayi Vijayan's first cabinet misused the CM's Distress Relief Fund by paying the families of a late MLA and an NCP leader. What did the Kerala Lokayukta rule in 2023?",
    options: [
      "Misuse proved; recovery ordered",
      "Case referred to the CBI",
      "No evidence of corruption or nepotism; plea dismissed",
      "Chief minister disqualified from office",
    ],
    correctIndex: 2,
    explanation:
      "A three-member bench held on 13 Nov 2023 that the CM may grant up to ₹3 lakh from the fund and found no proof of political motive; one member said cabinet decisions lie outside the Lokayukta Act, while the Lokayukta called the decision-making defective. Then Opposition leader V.D. Satheesan called the verdict biased.",
    status:
      "Lokayukta dismissed the complaint (13 Nov 2023); the Kerala High Court admitted the complainant's challenge and issued notice (Jan 2024); no High Court ruling found (checked Sep 2026).",
    otherSide:
      "The Lokayukta found no proof of political motive and held that the CM may grant up to ₹3 lakh from the fund; one member said cabinet decisions lie outside the Lokayukta Act.",
    people: ["Pinarayi Vijayan", "V.D. Satheesan"],
    sourceUrl: "https://www.onmanorama.com/news/kerala/2023/11/13/cmdrf-misuse-lokayukta-verdict.html",
    sourceLabel: "Onmanorama — No evidence to prove CMDRF was misused: Lokayukta rejects petition against Kerala CM (13 Nov 2023)",
    sources: [
      "https://www.indiatoday.in/law/story/kerala-lokayukta-dismiss-plea-against-pinarayi-vijayan-misuse-chief-minister-disaster-relief-fund-2462399-2023-11-13",
      "https://www.hindustantimes.com/india-news/relief-for-kerala-cm-as-lokayukta-dismisses-petition-in-cmdrf-case-101699901861804.html",
      "https://keralakaumudi.com/en/kerala/general/relief-fund-hc-sends-notice-to-cm-former-ministers-action-on-petition-challenging-lokayukta-verdict-1224696",
      "https://www.livelaw.in/high-court/kerala-high-court/kerala-high-court-cmdrf-misappropriation-case-admits-issues-letter-chief-minister-notice-former-ministers-246097",
    ],
    tags: ["relief"],
    outcome:
      "The grants in question: ₹25 lakh for the education of an NCP leader's children, ₹8.5 lakh to a late MLA's son, and ₹20 lakh to the widow of a police officer killed on escort duty.",
  },
]);
