// HISAAB DO — Relief funds: Centre lane (hrf001–hrf099), money-trail mode "Rahat Kosh".
// Contract: docs/hisaab/CHARTER.md §2–§5, §3a and §4a–§4b; editions/hisaab/bank/schema.mjs.
// Research notes, sources, dropped items and stale-risk list: docs/hisaab/research/relief-centre-notes.md.
// Every figure was read on the item's sourceUrl (or a listed source) in September 2026 (asOf).
// enactedBy records who announced, presented or passed a measure — a public act, not an allegation.
// Convention (same as dist-centre): `govt` is the government at the Centre that took the decision; `state`
// is the affected state when an item is about one state's disaster, so it also appears in that Rajya Round.
// Timing facts (gapDays) are days from the announcement to the first day of polling.

export const HISAAB_RELIEF_CENTRE = Object.freeze([
  // ───────────────────────────── 2000–2004 ─────────────────────────────
  {
    id: "hrf001",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "National Calamity Contingency Fund",
    kind: "institution",
    difficulty: "extreme",
    year: 2000,
    asOf: "2026-09",
    govt: "NDA",
    question: "For 2000–05 the 11th Finance Commission replaced an exhausted national relief fund with the National Calamity Contingency Fund. What initial corpus did it give the new fund?",
    options: ["₹500 crore", "₹100 crore", "₹2,000 crore", "₹5,000 crore"],
    correctIndex: 0,
    explanation: "A Rajya Sabha committee's 2026 report on disaster management records that the 11th FC dissolved the National Fund for Calamity Relief, whose corpus ran out within three years, and created the NCCF with ₹500 crore, to be recouped through a special surcharge on central taxes. The 12th Finance Commission kept it running alongside the states' Calamity Relief Funds.",
    sourceUrl: "https://bucketapi.rajyasabha.digital/public-bucket/uploads/committee/2026_08_21_committee_3339_976_6a881941b462a.pdf",
    sourceLabel: "Rajya Sabha Standing Committee on Home Affairs — 261st Report: Disaster Management (presented 7 Aug 2026), para 2.13.4",
    sources: [
      "https://www.indiabudget.gov.in/budget_archive/ub2001-02/bs/gujarat.htm",
      "https://www.indiabudget.gov.in/budget_archive/es2002-03/chapt2003/chap83.pdf",
    ],
    tags: ["relief"],
    outcome: "₹500 crore went from it to quake-hit Gujarat at once in 2001; it paid ₹1,018 crore for the 2002 drought; the 13th Finance Commission folded it into the NDRF from 2010-11.",
  },
  {
    id: "hrf002",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "National Calamity Contingent Duty (2001)",
    kind: "institution",
    difficulty: "expert",
    year: 2001,
    asOf: "2026-09",
    govt: "NDA",
    question: "The Finance Act of 2001, passed in the year of the Gujarat earthquake, created a calamity levy that the Finance Bill of 2026 was still amending. Which levy?",
    options: ["Swachh Bharat cess", "National Calamity Contingent Duty", "Krishi Kalyan cess", "Road and infrastructure cess"],
    correctIndex: 1,
    explanation: "The 2026 Finance Bill memo defines NCCD as a duty 'levied under Finance Act, 2001'. In his 28 Feb 2001 budget Yashwant Sinha proposed the special excise levy on cigarettes and other tobacco to refill the national calamity fund, as the 11th Finance Commission urged, and kept a separate 2% income-tax surcharge for Gujarat quake relief. The 2003 budget said NCCD money had not been enough.",
    sourceUrl: "https://www.indiabudget.gov.in/doc/memo.pdf",
    sourceLabel: "indiabudget.gov.in — Memorandum explaining the provisions in the Finance Bill, 2026 (Feb 2026)",
    sources: [
      "https://www.indiabudget.gov.in/budget_archive/ub2001-02/bs/speech_b.htm",
      "https://www.rediff.com/money/2001/feb/28bud.htm",
      "https://www.indiabudget.gov.in/budget_archive/ub2003-04/bs/speecha.htm",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Yashwant Sinha", role: "Union Finance Minister", party: "BJP" }],
    outcome: "Still on the books 25 years on: Finance Bill 2026 raised NCCD's schedule rate on chewing tobacco from 25% to 60% from 1 May 2026, keeping the effective rate at 25%.",
  },
  {
    id: "hrf003",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Drought relief 2002 (NCCF)",
    kind: "spend",
    difficulty: "extreme",
    year: 2002,
    asOf: "2026-09",
    govt: "NDA",
    question: "During the 2002 drought, how much did the Centre release from the National Calamity Contingency Fund, according to the Economic Survey 2002-03?",
    options: ["₹3,806 crore", "₹227 crore", "₹1,018 crore", "₹10,180 crore"],
    correctIndex: 2,
    explanation: "Box 8.1 of the Survey lists ₹1,018 crore from the NCCF, including cattle camps in Rajasthan; ₹1,227 crore of the Centre's Calamity Relief Fund share for 13 states, including advance instalments; and 27.74 lakh tonnes of foodgrains given free to affected states under a special component of the Sampoorna Grameen Rozgar Yojana for relief work.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/es2002-03/chapt2003/chap83.pdf",
    sourceLabel: "Economic Survey 2002-03, ch. 8 (Agriculture) — Box 8.1: Drought relief measures",
    sources: ["https://www.indiabudget.gov.in/budget_archive/es2002-03/chapt2003/chap14.htm"],
    tags: ["relief"],
    outcome: "Grain off-take under welfare schemes rose to 5.48 million tonnes in Apr–Oct 2002 from 3.15 million a year earlier; the 2003 budget added new calamity levies.",
  },
  {
    id: "hrf004",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Drought Task Force 2002",
    kind: "institution",
    difficulty: "expert",
    year: 2002,
    asOf: "2026-09",
    govt: "NDA",
    question: "Who chaired the Task Force the Centre set up to monitor the 2002 drought and issue relief directions to the states?",
    options: ["The Prime Minister", "The Agriculture Minister", "The Cabinet Secretary", "The Deputy Prime Minister"],
    correctIndex: 3,
    explanation: "The Economic Survey 2002-03 says the Task Force was chaired by the Deputy Prime Minister, with the Finance, Rural Development and Food ministers and the Planning Commission's deputy chairman as members. It ordered early calamity-fund releases under relaxed norms, free grain for relief work, loan deferments and free rail transport of fodder and water.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/es2002-03/chapt2003/chap83.pdf",
    sourceLabel: "Economic Survey 2002-03, ch. 8 (Agriculture) — para 8.5, Task Force on drought",
    tags: ["relief"],
    outcome: "Measures included a one-time drought relief price of ₹20 a quintal on paddy and 435 cattle camps for 1.62 lakh animals in Rajasthan (₹11.66 crore).",
  },
  {
    id: "hrf005",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Energy & Mining",
    subtopic: "NCCD on crude oil (2003)",
    kind: "institution",
    difficulty: "expert",
    year: 2003,
    asOf: "2026-09",
    govt: "NDA",
    question: "After the 2002 drought, Jaswant Singh's 2003 budget put a calamity duty of ₹50 a tonne on crude oil, 'limited to one year only'. What had become of it by January 2026?",
    options: ["Scrapped in 2004 as promised", "Merged into GST in 2017", "Raised to ₹500 a tonne", "Still levied on domestic crude"],
    correctIndex: 3,
    explanation: "Budget 2003-04 imposed a 1% NCCD on polyester filament yarn, cars, MUVs and two-wheelers and ₹50 a tonne on crude because earlier NCCD funds were 'not sufficient', promising one year. In January 2026 the Economic Times reported the crude levy, originally valid to 29 Feb 2004, still applied; the oil industry asked for its removal.",
    sourceUrl: "https://economictimes.indiatimes.com/industry/energy/oil-gas/budget-2026-oil-industry-seeks-abolition-or-review-of-oid-cess-on-pre-nelp-and-nomination-blocks/articleshow/126545404.cms",
    sourceLabel: "Economic Times — Budget 2026: Oil industry seeks abolition or review of OID cess (15 Jan 2026)",
    sources: [
      "https://www.indiabudget.gov.in/budget_archive/ub2003-04/bs/speecha.htm",
      "https://www.indiabudget.gov.in/doc/memo.pdf",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Jaswant Singh", role: "Union Finance Minister", party: "BJP" }],
    outcome: "Over two decades on, producers still paid ₹50 a tonne; the February 2026 Finance Bill's NCCD changes touched only tobacco products.",
  },
  {
    id: "hrf006",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "Foreign disaster aid policy (2004)",
    kind: "institution",
    difficulty: "simple",
    year: 2004,
    asOf: "2026-09",
    govt: "UPA",
    question: "India took foreign governments' aid after the 2001 Gujarat earthquake. What did Manmohan Singh's government decide after the December 2004 tsunami?",
    options: ["To accept aid only from UN agencies", "To cope without foreign-government aid", "To route all aid through PMNRF", "To accept foreign aid only as loans"],
    correctIndex: 1,
    explanation: "Singh said India could cope on its own and would take help if needed. That became policy: India had accepted foreign-government aid for Uttarkashi (1991), Latur (1993), Gujarat (2001) and the Bihar floods of July 2004, but declined it afterwards. Money from NRIs and charities could still come in through remittances.",
    sourceUrl: "https://indianexpress.com/article/india/kerala-floods-on-foreign-aid-india-follows-policy-set-in-tsunami-aftermath-5318338/",
    sourceLabel: "Indian Express — Kerala floods: On foreign aid, India follows policy set in tsunami aftermath (22 Aug 2018)",
    sources: ["https://indianexpress.com/article/india/govt-will-do-whatever-it-takes-to-meet-needs-of-people-foreign-secretary-harsh-vardhan-shringla-7296040/"],
    tags: ["relief"],
    enactedBy: [{ name: "Manmohan Singh", role: "Prime Minister", party: "INC" }],
    outcome: "Offers were declined for Kashmir (2005), Uttarakhand (2013), J&K (2014) and Kerala (2018), until India accepted Covid-19 aid in April 2021.",
  },

  // ───────────────────────────── 2005–2009 ─────────────────────────────
  {
    id: "hrf007",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Environment & Land",
    subtopic: "Tsunami relief packages (2005)",
    kind: "spend",
    difficulty: "expert",
    year: 2005,
    asOf: "2026-09",
    govt: "UPA",
    question: "Presenting the budget in February 2005, how much did P. Chidambaram say the Centre had approved so far in tsunami relief packages?",
    options: ["₹364 crore", "₹10,216 crore", "₹3,644 crore", "₹36,440 crore"],
    correctIndex: 2,
    explanation: "The 2005-06 budget speech put approved relief packages at ₹3,644 crore and the Planning Commission's reconstruction programme at ₹10,216 crore. The package became the Rajiv Gandhi Rehabilitation Package for tsunami-affected areas (₹3,644.05 crore) covering Tamil Nadu, Kerala, Andhra Pradesh, Puducherry and the Andaman and Nicobar Islands.",
    sourceUrl: "https://www.indiabudget.gov.in/budget_archive/ub2005-06/bs/speecha.htm",
    sourceLabel: "indiabudget.gov.in — Budget Speech 2005-06, P. Chidambaram (28 Feb 2005), para 4",
    sources: ["https://frontline.thehindu.com/the-nation/article30183601.ece"],
    tags: ["relief"],
    enactedBy: [{ name: "P. Chidambaram", role: "Union Finance Minister", party: "INC" }],
    outcome: "Frontline reported in 2009 that ₹11,907.29 crore had been mobilised in all, yet only 250 of 10,000 targeted houses had been built in the Andaman and Nicobar Islands.",
  },
  {
    id: "hrf008",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "Disaster Management Act, 2005",
    kind: "institution",
    difficulty: "simple",
    year: 2005,
    asOf: "2026-09",
    govt: "UPA",
    question: "Under the Disaster Management Act of December 2005, who is the ex officio chairperson of the National Disaster Management Authority?",
    options: ["The Union Home Minister", "The Cabinet Secretary", "The President of India", "The Prime Minister"],
    correctIndex: 3,
    explanation: "Act No. 53 of 2005, dated 23 December 2005, makes the Prime Minister chair of the NDMA and each Chief Minister chair of the state authority. Sections 46 to 48 provide for the National Disaster Response Fund, a National Disaster Mitigation Fund and state funds.",
    sourceUrl: "https://prsindia.org/files/bills_acts/bills_parliament/2024/Disaster_Management_Act_2005.pdf",
    sourceLabel: "PRS Legislative Research — The Disaster Management Act, 2005 (Act No. 53 of 2005), text",
    tags: ["relief"],
    outcome: "The Section 47 mitigation fund came only after the 15th Finance Commission (guidelines Feb 2022); Parliament amended the Act in March 2025.",
  },
  {
    id: "hrf009",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Environment & Land",
    subtopic: "12th Finance Commission disaster list",
    kind: "institution",
    difficulty: "expert",
    year: 2005,
    asOf: "2026-09",
    govt: "UPA",
    question: "The 12th Finance Commission (2005–10) widened the list of disasters that calamity funds could pay for. Which did it add?",
    options: ["Heatwaves and lightning", "Fire and hailstorms", "Landslides, avalanches, cloudbursts and pest attacks", "Chemical and nuclear accidents"],
    correctIndex: 2,
    explanation: "The Rajya Sabha committee's 2026 report traces the funds: the 8th Finance Commission added fire, the 12th continued the Calamity Relief Fund and NCCF and added landslides, avalanches, cloudbursts and pest attacks, and the 16th has recommended adding heatwave and lightning.",
    sourceUrl: "https://bucketapi.rajyasabha.digital/public-bucket/uploads/committee/2026_08_21_committee_3339_976_6a881941b462a.pdf",
    sourceLabel: "Rajya Sabha Standing Committee on Home Affairs — 261st Report: Disaster Management (Aug 2026), paras 2.13.2–2.13.4",
    tags: ["relief"],
    outcome: "Central releases to the state calamity funds rose from ₹2,623 crore in 2005-06 to ₹3,792 crore in 2009-10, per MHA data in the same report.",
  },
  {
    id: "hrf010",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "Tsunami funds: PAC findings (2008)",
    kind: "spend",
    difficulty: "extreme",
    year: 2008,
    asOf: "2026-09",
    govt: "UPA",
    question: "Parliament's Public Accounts Committee reported in April 2008 that tsunami relief money had been diverted to other purposes. About how much did the diversion and related irregularities involve?",
    options: ["About ₹23 crore", "About ₹230 crore", "About ₹2,300 crore", "About ₹3,644 crore"],
    correctIndex: 1,
    explanation: "The PAC's 2007-08 report (25 April 2008) found diversion of tsunami funds and lapses in Andhra Pradesh, Kerala, Tamil Nadu, Andaman and Nicobar and Puducherry — improper verification, missed targets and relief to unaffected or ineligible people — involving about ₹230 crore. A 2006 CAG performance audit had flagged wrong assessments of fund needs and compensation norms.",
    status: "Findings of Parliament's Public Accounts Committee report of 25 April 2008 on state and UT administrations; no individual named.",
    sourceUrl: "https://frontline.thehindu.com/the-nation/article30183601.ece",
    sourceLabel: "Frontline — Homeless still (13 Feb 2009)",
    tags: ["relief"],
    outcome: "Four years after the tsunami, Frontline found thousands of survivors in Tamil Nadu and the Andamans still waiting for permanent homes.",
  },
  {
    id: "hrf011",
    domain: "civics",
    region: "India",
    state: "BR",
    topic: "Environment & Land",
    subtopic: "Kosi floods 2008",
    kind: "spend",
    difficulty: "simple",
    year: 2008,
    asOf: "2026-09",
    govt: "UPA",
    question: "After his aerial survey of the Kosi breach on 28 August 2008, how did Manmohan Singh classify the Bihar floods?",
    options: ["As a 'national disaster'", "As a 'state calamity'", "As a 'regional emergency'", "As a 'drought-flood emergency'"],
    correctIndex: 0,
    explanation: "He also announced ₹1,000 crore and 1.25 lakh tonnes of grain, a day after the Bihar government sought ₹1,000 crore and one lakh tonnes of rice. The Kosi had breached its embankment at Kusaha in Nepal and changed course, displacing nearly 20 lakh people in north Bihar.",
    sourceUrl: "https://economictimes.indiatimes.com/news/politics-and-nation/pm-sanctions-rs-1000-crore-declares-bihar-flood-national-disaster/articleshow/3419064.cms",
    sourceLabel: "Economic Times — PM sanctions Rs 1,000 crore, declares Bihar flood national disaster (29 Aug 2008)",
    sources: ["https://timesofindia.indiatimes.com/city/patna/when-manmohan-declared-bihar-floods-a-national-disaster-in-2008/articleshow/116723160.cms"],
    tags: ["relief"],
    enactedBy: [{ name: "Manmohan Singh", role: "Prime Minister", party: "INC" }],
    outcome: "The Centre met Bihar's ₹1,000 crore request in full and topped its grain request; 242 panchayats and 671 villages lay on the river's new course.",
  },
  {
    id: "hrf012",
    domain: "civics",
    region: "India",
    state: "KA",
    topic: "Environment & Land",
    subtopic: "Karnataka–Andhra floods 2009",
    kind: "spend",
    difficulty: "expert",
    year: 2009,
    asOf: "2026-09",
    govt: "UPA",
    question: "Granting ₹1,000 crore each to flood-hit Karnataka and Andhra Pradesh in October 2009, what did Manmohan Singh assure Karnataka's BJP government?",
    options: ["Aid would flow only via central agencies", "The Centre would not discriminate by party", "Karnataka must match the grant", "Special-category status would follow"],
    correctIndex: 1,
    explanation: "Winding up a two-day aerial survey on 10 October 2009, he announced interim relief of ₹1,000 crore for each state and ₹1 lakh for the kin of each of the 226 people killed in Karnataka, saying the Centre would never discriminate against states on the basis of political affiliation and assuring full support.",
    sourceUrl: "https://www.thehindu.com/news/national/Manmohan-winds-up-survey-announces-Rs.-2000-cr.-relief/article16885881.ece",
    sourceLabel: "The Hindu (IANS) — Manmohan winds up survey; announces Rs. 2,000 cr. relief (10 Oct 2009)",
    tags: ["relief"],
    enactedBy: [{ name: "Manmohan Singh", role: "Prime Minister", party: "INC" }],
    outcome: "₹2,000 crore of interim aid across the two states, with more promised once central teams assessed the state memoranda.",
  },

  // ───────────────────────────── 2010–2014 ─────────────────────────────
  {
    id: "hrf013",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "13th Finance Commission: SDRF and NDRF",
    kind: "institution",
    difficulty: "extreme",
    year: 2010,
    asOf: "2026-09",
    govt: "UPA",
    question: "The 13th Finance Commission (2010–15) merged the old calamity funds into the SDRF and NDRF. What total allocation did it make?",
    options: ["₹17,559 crore", "₹61,219 crore", "₹1,60,153 crore", "₹33,581 crore"],
    correctIndex: 3,
    explanation: "The Rajya Sabha committee report says the 13th FC aligned the funds with the 2005 Act for the first time, folding the Calamity Relief Fund into State Disaster Response Funds and the NCCF into the NDRF, with the Centre paying 75% (90% for special-category states). Its ₹33,581 crore was still set entirely by past spending.",
    sourceUrl: "https://bucketapi.rajyasabha.digital/public-bucket/uploads/committee/2026_08_21_committee_3339_976_6a881941b462a.pdf",
    sourceLabel: "Rajya Sabha Standing Committee on Home Affairs — 261st Report: Disaster Management (Aug 2026), para 2.13.4",
    tags: ["relief"],
    outcome: "From 2010-11 to 2014-15 the Centre released ₹25,488 crore to state funds and ₹17,559 crore from the NDRF (MHA data, Table 2.3).",
  },
  {
    id: "hrf014",
    domain: "civics",
    region: "India",
    state: "SK",
    topic: "Environment & Land",
    subtopic: "Sikkim earthquake 2011",
    kind: "spend",
    difficulty: "expert",
    year: 2011,
    asOf: "2026-09",
    govt: "UPA",
    question: "Seeking relief 'under national calamity' after the 18 September 2011 earthquake, what did Sikkim's government estimate the damage at?",
    options: ["About ₹1,000 crore", "About ₹10,000 crore", "About ₹1 lakh crore", "About ₹10 lakh crore"],
    correctIndex: 2,
    explanation: "Sikkim's Chief Minister had estimated damage at about ₹1 lakh crore and handed the visiting Prime Minister a memorandum. Manmohan Singh announced ₹1,000 crore for relief and rehabilitation, stressed rebuilding monasteries, schools, houses and roads, and urged the state to adopt earthquake-safe building by-laws.",
    sourceUrl: "https://www.thehindu.com/news/national/rs1000crore-central-aid-for-quakehit-sikkim/article2497796.ece",
    sourceLabel: "The Hindu — Rs.1,000-crore Central aid for quake-hit Sikkim (29 Sep 2011)",
    tags: ["relief"],
    enactedBy: [{ name: "Manmohan Singh", role: "Prime Minister", party: "INC" }],
    outcome: "Interim central aid of ₹1,000 crore against a damage estimate a hundred times larger; an expert team on quake-resistant rebuilding was to follow.",
  },
  {
    id: "hrf015",
    domain: "civics",
    region: "India",
    state: "AS",
    topic: "Environment & Land",
    subtopic: "Assam floods 2012",
    kind: "spend",
    difficulty: "simple",
    year: 2012,
    asOf: "2026-09",
    govt: "UPA",
    question: "Surveying Assam's floods in July 2012, how much ad hoc assistance did Manmohan Singh, himself a Rajya Sabha member from Assam, announce for the state?",
    options: ["₹50 crore", "₹1,000 crore", "₹5,000 crore", "₹500 crore"],
    correctIndex: 3,
    explanation: "On 2 July 2012, after an aerial survey of Jorhat, North Lakhimpur and Dhemaji with the UPA chairperson and the Chief Minister, he announced ₹500 crore. Floods and landslides had killed 81 people; 4.84 lakh were sheltering in 768 relief camps.",
    sourceUrl: "https://www.rediff.com/news/slide-show/slide-show-1-assam-floods-77-dead-pm-announces-rs-500-crore-aid/20120702.htm",
    sourceLabel: "Rediff (PTI) — Assam floods: PM announces Rs 500 crore aid (2 Jul 2012)",
    sources: ["https://www.indiatoday.in/magazine/glass-house/story/20120716-pm-manmmohan-singh-visits-assam-after-floods-758995-2012-07-05"],
    tags: ["relief"],
    enactedBy: [{ name: "Manmohan Singh", role: "Prime Minister", party: "INC" }],
    outcome: "Nearly 20 lakh people in over 2,000 villages were affected and 6.58 lakh hectares of cropland submerged when the aid was announced.",
  },
  {
    id: "hrf016",
    domain: "civics",
    region: "India",
    state: "UT",
    topic: "Welfare & Subsidies",
    subtopic: "Uttarakhand 2013: PMNRF ex gratia",
    kind: "spend",
    difficulty: "simple",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "After the June 2013 Uttarakhand floods, what ex gratia did the Prime Minister announce from the PM's National Relief Fund for the family of each person killed?",
    options: ["₹50,000", "₹1 lakh", "₹2 lakh", "₹5 lakh"],
    correctIndex: 2,
    explanation: "On 19 June 2013 Manmohan Singh announced ₹1,000 crore for Uttarakhand (₹145 crore at once) and, from PMNRF, ₹2 lakh per death, ₹50,000 per injured person, ₹1 lakh per destroyed house and ₹50,000 per damaged house. The Centre announced the same ₹2 lakh per death after the J&K floods (2014) and Cyclone Fani (2019).",
    sourceUrl: "https://www.thehindu.com/news/national/other-states/pm-announces-rs-1000-cr-relief-for-uttarakhand/article4829561.ece",
    sourceLabel: "The Hindu — PM announces Rs. 1000 cr. relief for Uttarakhand (19 Jun 2013)",
    sources: [
      "https://www.thehindu.com/news/national/Modi-reviews-flood-situation-in-Jammu-with-Omar-Abdullah/article60346187.ece",
      "https://www.pmindia.gov.in/en/news_updates/pm-undertakes-aerial-survey-of-cyclone-fani-affected-areas-in-odisha-reviews-the-situation/",
      "https://www.thehindu.com/news/national/other-states/centre-approves-rs-7346-crore-compensation-package-for-uttarakhand/article5444877.ece",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Manmohan Singh", role: "Prime Minister", party: "INC" }],
    outcome: "By December 2013 PMNRF had given Uttarakhand ₹154 crore, and the Centre had released ₹1,090 crore of ₹1,114 crore sanctioned, state officials said.",
  },
  {
    id: "hrf017",
    domain: "civics",
    region: "India",
    state: "UT",
    topic: "Infrastructure",
    subtopic: "Uttarakhand reconstruction package 2013",
    kind: "spend",
    difficulty: "extreme",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "In December 2013 the Cabinet Committee on Uttarakhand approved a ₹7,346 crore reconstruction package. What was its largest component?",
    options: ["Special Plan Assistance", "Centrally sponsored schemes", "NDRF assistance", "Externally aided projects"],
    correctIndex: 3,
    explanation: "Chaired by Manmohan Singh, the committee split the package as ₹3,161 crore for externally aided projects, ₹1,885 crore through centrally sponsored schemes, ₹1,200 crore from the NDRF and ₹1,100 crore as special plan assistance, plus ₹100 crore for compensation outside NDRF norms, such as ₹50,000 per mule lost.",
    sourceUrl: "https://www.thehindu.com/news/national/other-states/centre-approves-rs-7346-crore-compensation-package-for-uttarakhand/article5444877.ece",
    sourceLabel: "The Hindu — Centre approves Rs. 7,346 crore compensation package for Uttarakhand (11 Dec 2013)",
    tags: ["relief"],
    enactedBy: [{ name: "Manmohan Singh", role: "Prime Minister (chair, Cabinet Committee on Uttarakhand)", party: "INC" }],
    outcome: "Externally aided projects made up 43% of the package; the NDRF share was ₹1,200 crore (16%).",
  },
  {
    id: "hrf018",
    domain: "civics",
    region: "India",
    state: "JK",
    topic: "Environment & Land",
    subtopic: "J&K floods 2014: the ask",
    kind: "spend",
    difficulty: "extreme",
    year: 2014,
    asOf: "2026-09",
    govt: "NDA",
    question: "Meeting Narendra Modi on 23 September 2014 after the J&K floods, what compensation package did Chief Minister Omar Abdullah seek from the Centre?",
    options: ["₹4,400 crore", "₹1,100 crore", "₹44,000 crore", "₹4.4 lakh crore"],
    correctIndex: 2,
    explanation: "HT reported the ₹44,000 crore request for the worst floods in a century. On 7 September Modi had called the floods a 'national-level disaster' and announced ₹1,000 crore over the ₹1,100 crore already available to the state through its disaster fund, plus ₹2 lakh ex gratia per death.",
    status: "Named for a public request made as Chief Minister; no allegation against him.",
    people: ["Omar Abdullah"],
    sourceUrl: "https://www.hindustantimes.com/india/pm-modi-visits-siachen-spends-time-with-soldiers-on-diwali/story-QdGzHCfbWY9FYglkYdGUbL.html",
    sourceLabel: "Hindustan Times — PM Modi visits Siachen, spends time with soldiers on Diwali (23 Oct 2014)",
    sources: ["https://www.thehindu.com/news/national/Modi-reviews-flood-situation-in-Jammu-with-Omar-Abdullah/article60346187.ece"],
    tags: ["relief"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "Central help came in tranches: ₹1,000 crore in September, more on Diwali, and a flood component in the November 2015 J&K package.",
  },
  {
    id: "hrf019",
    domain: "civics",
    region: "India",
    state: "JK",
    topic: "Environment & Land",
    subtopic: "J&K flood aid, Diwali 2014",
    kind: "spend",
    difficulty: "expert",
    year: 2014,
    asOf: "2026-09",
    govt: "NDA",
    question: "On Diwali 2014 in Srinagar, Modi announced ₹570 crore for flood-hit housing and ₹175 crore for six hospitals. How long was that before the first phase of J&K's Assembly polls?",
    options: ["33 days", "3 days", "93 days", "183 days"],
    correctIndex: 0,
    explanation: "The PMO recorded the 23 October 2014 announcements, over the ₹1,000 crore given in September; Modi also said paying house-rebuilding aid straight into bank accounts would be considered. Polling ran in five phases from 25 November to 20 December 2014.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/pm-meets-various-groups-of-flood-affected-people-in-srinagar-listens-to-their-problems-and-suggestions/",
    sourceLabel: "PMO India — PM meets various groups of flood-affected people in Srinagar (23 Oct 2014)",
    sources: [
      "https://www.rediff.com/news/report/pix-jammu-kashmir-votes-amid-ring-of-security/20141202.htm",
      "https://www.newindianexpress.com/india/2014/Dec/21/at-66-per-cent-jammu-and-kashmir-records-highest-polling-in-25-years-696746.html",
      "https://www.thequint.com/news/politics/bjp-pdp-alliance-split-timeline",
    ],
    tags: ["relief", "pre-election"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "₹745 crore announced 33 days before polling. The Assembly was hung and a PDP–BJP coalition took office on 1 March 2015; no cited source ties the aid to the vote.",
    poll: { label: "J&K Assembly 2014", month: "2014-11", gapDays: 33, result: "Hung: PDP 28, BJP 25, NC 15, INC 12 of 87; PDP–BJP coalition from Mar 2015" },
  },
  {
    id: "hrf020",
    domain: "civics",
    region: "India",
    state: "AP",
    topic: "Environment & Land",
    subtopic: "Cyclone Hudhud 2014 and the ₹1,000 crore habit",
    kind: "spend",
    difficulty: "simple",
    year: 2014,
    asOf: "2026-09",
    govt: "NDA",
    question: "Manmohan Singh after the Kosi floods (2008) and Uttarakhand (2013), and Modi in Andhra Pradesh after Cyclone Hudhud (2014): what interim aid did each announce after an aerial survey?",
    options: ["₹1,000 crore", "₹100 crore", "₹500 crore", "₹5,000 crore"],
    correctIndex: 0,
    explanation: "On 14 October 2014 in Visakhapatnam Modi announced ₹1,000 crore interim aid for Hudhud — Singh's figure for Kosi and Uttarakhand, and for Karnataka, Andhra Pradesh (2009) and Sikkim (2011). Modi repeated it after Cyclone Fani in Odisha (2019) and Cyclone Amphan in West Bengal (2020).",
    sourceUrl: "https://indianexpress.com/article/india/india-others/pm-arrives-in-visakhapatnam-to-survey-cyclone-hit-areas/",
    sourceLabel: "Indian Express — Modi surveys Vizag after cyclone Hudhud; announces interim assistance of Rs 1000 crore (14 Oct 2014)",
    sources: [
      "https://economictimes.indiatimes.com/news/politics-and-nation/pm-sanctions-rs-1000-crore-declares-bihar-flood-national-disaster/articleshow/3419064.cms",
      "https://www.thehindu.com/news/national/other-states/pm-announces-rs-1000-cr-relief-for-uttarakhand/article4829561.ece",
      "https://scroll.in/latest/962646/cyclone-amphan-narendra-modi-announces-rs-1000-crore-as-immediate-relief-for-west-bengal",
    ],
    tags: ["relief"],
    enactedBy: [
      { name: "Narendra Modi", role: "Prime Minister", party: "BJP" },
      { name: "Manmohan Singh", role: "Prime Minister (2004–14)", party: "INC" },
    ],
    outcome: "These are interim sums, not final awards: further NDRF aid follows a central team's assessment of each state's memorandum.",
  },

  // ───────────────────────────── 2015–2019 ─────────────────────────────
  {
    id: "hrf021",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "14th Finance Commission: local disasters",
    kind: "institution",
    difficulty: "expert",
    year: 2015,
    asOf: "2026-09",
    govt: "NDA",
    question: "The 14th Finance Commission (2015–20) let states spend up to what share of their disaster response fund on local disasters missing from the national list?",
    options: ["10%", "5%", "25%", "50%"],
    correctIndex: 0,
    explanation: "The Rajya Sabha committee calls it the first acknowledgement that a single national list cannot fit every state's risks. The 14th FC also raised the allocation to ₹61,219 crore from ₹33,581 crore under the 13th.",
    sourceUrl: "https://bucketapi.rajyasabha.digital/public-bucket/uploads/committee/2026_08_21_committee_3339_976_6a881941b462a.pdf",
    sourceLabel: "Rajya Sabha Standing Committee on Home Affairs — 261st Report: Disaster Management (Aug 2026), para 2.13.5",
    tags: ["relief"],
    outcome: "Central releases to state disaster funds rose from ₹8,756 crore in 2015-16 to ₹10,938 crore in 2019-20 (MHA data).",
  },
  {
    id: "hrf022",
    domain: "civics",
    region: "India",
    state: "JK",
    topic: "Infrastructure",
    subtopic: "PM's Development Package for J&K (2015)",
    kind: "spend",
    difficulty: "extreme",
    year: 2015,
    asOf: "2026-09",
    govt: "NDA",
    question: "Of Modi's ₹80,068 crore development package for J&K, announced on 7 November 2015, how much was for flood relief, reconstruction and flood management?",
    options: ["₹837 crore", "₹2,241 crore", "₹42,611 crore", "₹7,854 crore"],
    correctIndex: 3,
    explanation: "The PMO's breakdown lists ₹7,854 crore for flood relief, reconstruction and Jhelum flood management, against ₹42,611 crore for roads and highways and ₹11,708 crore for power. It was over and above ₹837 crore already committed from PMNRF and ₹1,000 crore given after the 2014 floods.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/highlights-of-prime-ministers-development-package-for-jammu-and-kashmir/",
    sourceLabel: "PMO India — Highlights of PM's development package for Jammu and Kashmir (7 Nov 2015)",
    tags: ["relief"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "Flood items were under a tenth of the headline; roads and highways took over half of the ₹80,068 crore.",
  },
  {
    id: "hrf023",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "Swaraj Abhiyan drought ruling (2016)",
    kind: "institution",
    difficulty: "expert",
    year: 2016,
    asOf: "2026-09",
    govt: "NDA",
    question: "Ruling on a drought PIL in May 2016, the Supreme Court gave the Centre three months to set up which fund provided for in the 2005 disaster law?",
    options: ["National Disaster Mitigation Fund", "PM CARES Fund", "National Calamity Contingency Fund", "Prime Minister's National Relief Fund"],
    correctIndex: 0,
    explanation: "In Swaraj Abhiyan v Union of India the court also ordered a specialist disaster response force within six months and a new drought manual, faulted Bihar, Gujarat and Haryana for their hesitancy in acknowledging drought, and told the Centre not to lean on federalism to limit itself to funding. Section 47 of the 2005 Act allowed a mitigation fund, but none existed.",
    sourceUrl: "https://www.thehindu.com/news/national/Declaration-of-drought-Define-time-limit-Supreme-Court-tells-Centre/article60512906.ece",
    sourceLabel: "The Hindu — SC pulls up Centre, States for failing to tackle drought (11 May 2016)",
    sources: [
      "https://www.livemint.com/Politics/K40mUpuaDEctugrfHpYyNJ/SC-verdict-on-drought-case-today.html",
      "https://bucketapi.rajyasabha.digital/public-bucket/uploads/committee/2026_08_21_committee_3339_976_6a881941b462a.pdf",
    ],
    tags: ["relief"],
    outcome: "NDMF guidelines came only on 28 Feb 2022, after the 15th Finance Commission; by July 2025 ₹5,685 crore of projects were approved and ₹741.8 crore released.",
  },
  {
    id: "hrf024",
    domain: "civics",
    region: "India",
    state: "KL",
    topic: "Governance & Institutions",
    subtopic: "Kerala floods 2018: UAE offer",
    kind: "institution",
    difficulty: "simple",
    year: 2018,
    asOf: "2026-09",
    govt: "NDA",
    question: "In August 2018 Kerala's Chief Minister said the UAE had offered ₹700 crore for flood relief. What did the Centre do?",
    options: ["Accepted it through PMNRF", "Accepted it as a soft loan", "Declined foreign-government aid", "Referred it to the Finance Commission"],
    correctIndex: 2,
    explanation: "Officials cited the policy followed since the 2004 tsunami of not accepting aid from foreign governments, while allowing money from NRIs and charities; the Maldives' ₹35 lakh was also turned down. The CM argued there was no blanket ban on goodwill aid; UAE embassy officials later said no amount had been finalised officially.",
    sourceUrl: "https://indianexpress.com/article/india/kerala-floods-on-foreign-aid-india-follows-policy-set-in-tsunami-aftermath-5318338/",
    sourceLabel: "Indian Express — Kerala floods: On foreign aid, India follows policy set in tsunami aftermath (22 Aug 2018)",
    sources: ["https://www.newindianexpress.com/states/kerala/2018/Aug/24/kerala-flood-relief-no-aid-finalised-officially-says-uae-official-1862250.html"],
    tags: ["relief"],
    outcome: "The Centre later approved NDRF aid for Kerala; India accepted foreign-government aid again only for Covid-19 in April 2021.",
  },
  {
    id: "hrf025",
    domain: "civics",
    region: "India",
    state: "KL",
    topic: "Environment & Land",
    subtopic: "Kerala floods 2018: NDRF award",
    kind: "spend",
    difficulty: "extreme",
    year: 2018,
    asOf: "2026-09",
    govt: "NDA",
    question: "Kerala sought ₹4,700 crore after its 2018 floods. How much additional central aid did the Home Minister's High Level Committee approve that December?",
    options: ["₹600 crore", "₹3,048 crore", "₹4,700 crore", "₹31,000 crore"],
    correctIndex: 1,
    explanation: "The committee headed by Rajnath Singh approved ₹3,048.39 crore for Kerala on 6 December 2018, alongside ₹131.16 crore for Nagaland and ₹539.52 crore for Andhra Pradesh after Cyclone Titli. At least 488 people died in Kerala's floods, called the worst in a century.",
    sourceUrl: "https://www.thehindu.com/news/national/kerala-to-get-3048-crore-as-flood-relief/article25682123.ece",
    sourceLabel: "The Hindu — Kerala to get ₹3,048 crore as flood relief (6 Dec 2018)",
    tags: ["relief"],
    enactedBy: [{ name: "Rajnath Singh", role: "Union Home Minister (chair, High Level Committee)", party: "BJP" }],
    outcome: "About 65% of what Kerala asked for, approved nearly four months after the August floods.",
  },
  {
    id: "hrf026",
    domain: "civics",
    region: "India",
    state: "OD",
    topic: "Environment & Land",
    subtopic: "Cyclone Fani 2019",
    kind: "spend",
    difficulty: "simple",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "As Cyclone Fani neared Odisha in the 2019 poll season, what did the Election Commission do in 11 coastal districts?",
    options: ["Postponed the vote count there", "Took charge of relief camps", "Lifted the Model Code of Conduct for relief work", "Banned all political rallies"],
    correctIndex: 2,
    explanation: "On 30 April the EC lifted the Model Code in Puri, Ganjam, Khordha, Cuttack and seven other districts so relief could proceed; Odisha's joint Lok Sabha and Assembly votes were cast but not yet counted, and the EC let polled EVMs in two districts be moved. The Centre released ₹341 crore on 29 April; after a 6 May aerial survey Modi announced ₹1,000 crore more and ₹2 lakh per death.",
    sourceUrl: "https://scroll.in/latest/921936/cyclone-fani-tourists-told-to-leave-puri-by-tomorrow-ec-lifts-model-code-in-11-odisha-districts",
    sourceLabel: "Scroll — Cyclone Fani: EC lifts model code in 11 Odisha districts (1 May 2019)",
    sources: ["https://www.pmindia.gov.in/en/news_updates/pm-undertakes-aerial-survey-of-cyclone-fani-affected-areas-in-odisha-reviews-the-situation/"],
    tags: ["relief"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "Odisha moved over a million people to safety before the 3 May landfall, which the PM credited, with IMD forecasts, for limiting deaths.",
  },
  {
    id: "hrf027",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "NDRF releases, 2005–2025",
    kind: "spend",
    difficulty: "extreme",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "MHA data in a 2026 Rajya Sabha committee report show central releases from the National Disaster Response Fund peaked in which year?",
    options: ["2013-14", "2015-16", "2019-20", "2023-24"],
    correctIndex: 2,
    explanation: "NDRF releases hit ₹18,531 crore in 2019-20, against ₹12,452 crore in 2015-16 and ₹4,650 crore in 2013-14. They fell to ₹869 crore in 2023-24, while central releases to state funds climbed to a record ₹20,264 crore in 2024-25.",
    sourceUrl: "https://bucketapi.rajyasabha.digital/public-bucket/uploads/committee/2026_08_21_committee_3339_976_6a881941b462a.pdf",
    sourceLabel: "Rajya Sabha Standing Committee on Home Affairs — 261st Report (Aug 2026), Table 2.3: Release of funds from SDRF and NDRF",
    sources: ["https://factly.in/india-scales-up-disaster-funding-but-local-preparedness-lags/"],
    tags: ["relief"],
    outcome: "Factly read the series as a shift toward state-level financing; the Centre allocated ₹54,770 crore to the NDRF for 2021-26.",
  },

  // ───────────────────────────── 2020–2026 ─────────────────────────────
  {
    id: "hrf028",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "PMGKP insurance for health workers",
    kind: "scheme",
    difficulty: "extreme",
    year: 2020,
    asOf: "2026-09",
    govt: "NDA",
    question: "The PMGKP scheme gave about 22 lakh health workers ₹50 lakh Covid insurance cover (March 2020–October 2022). How many claims had been paid by February 2025?",
    options: ["About 250", "About 22,000", "About 2 lakh", "About 2,500"],
    correctIndex: 3,
    explanation: "Nirmala Sitharaman announced the cover in the ₹1.70 lakh crore Garib Kalyan package on 26 March 2020. The Health Ministry told Lok Sabha in February 2025 that 2,545 claims of ₹50 lakh each had been paid; it keeps no profession-wise Covid death data and there is no 'martyr' status for health workers.",
    sourceUrl: "https://www.newindianexpress.com/india/2025/Feb/07/profession-wise-covid-19-death-data-not-maintained-centrally-no-martyrs-status-centre-tells-lok-sabha",
    sourceLabel: "New Indian Express — Profession-wise COVID-19 death data not maintained centrally, Centre tells Lok Sabha (7 Feb 2025)",
    sources: ["https://pib.gov.in/PressReleasePage.aspx?PRID=1608345"],
    tags: ["relief"],
    enactedBy: [{ name: "Nirmala Sitharaman", role: "Union Finance Minister", party: "BJP" }],
    outcome: "2,545 claims at ₹50 lakh each come to about ₹1,272 crore; India recorded 5,33,662 Covid deaths by 3 February 2025.",
  },
  {
    id: "hrf029",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Atmanirbhar package: headline vs spend",
    kind: "spend",
    difficulty: "expert",
    year: 2020,
    asOf: "2026-09",
    govt: "NDA",
    question: "Modi billed the May 2020 Atmanirbhar package at ₹20 lakh crore, about 10% of GDP. Most calculations put its actual new government spending at roughly what share of GDP?",
    options: ["About 1 per cent", "About 5 per cent", "About 10 per cent", "About 15 per cent"],
    correctIndex: 0,
    explanation: "The Finance Ministry's ₹20,97,053 crore total counted ₹8,01,603 crore of RBI liquidity measures and ₹1,92,800 crore from the earlier Garib Kalyan package. The Indian Express's analysis said most calculations put actual spending near 1% of GDP; Sitharaman described it as reforms covering land, labour, liquidity and laws.",
    sourceUrl: "https://indianexpress.com/article/explained/explainspeaking-why-the-atmanirbhar-bharat-abhiyan-economic-package-is-being-criticised-6414905/",
    sourceLabel: "Indian Express — ExplainSpeaking: Why the Atmanirbhar Bharat Abhiyan economic package is being criticised (18 May 2020)",
    sources: ["https://indianexpress.com/article/india/economic-relief-package-break-up-five-tranches-6414076/"],
    tags: ["relief"],
    enactedBy: [
      { name: "Narendra Modi", role: "Prime Minister", party: "BJP" },
      { name: "Nirmala Sitharaman", role: "Union Finance Minister", party: "BJP" },
    ],
    outcome: "RBI measures alone were 38% of the ₹20.97 lakh crore headline, by the Finance Ministry's own breakdown.",
  },
  {
    id: "hrf030",
    domain: "civics",
    region: "India",
    state: "WB",
    topic: "Environment & Land",
    subtopic: "Cyclone Amphan 2020: NDRF award",
    kind: "spend",
    difficulty: "extreme",
    year: 2020,
    asOf: "2026-09",
    govt: "NDA",
    question: "West Bengal sought ₹35,018 crore from the NDRF after Cyclone Amphan in May 2020. How much assistance from the fund was cleared, subject to adjusting its SDRF balance?",
    options: ["₹270.77 crore", "₹27,077 crore", "₹1,02,442 crore", "₹2,707.7 crore"],
    correctIndex: 3,
    explanation: "₹2,707.7 crore was cleared subject to adjusting half of the state's SDRF balance, a CAG report tabled in July 2026 records; the central team had first proposed ₹2,500.29 crore. Modi had announced ₹1,000 crore in advance after a 22 May 2020 aerial survey with the Chief Minister; Bengal put damage at about ₹1.02 lakh crore in June 2020.",
    sourceUrl: "https://timesofindia.indiatimes.com/city/kolkata/bengal-inflated-amphan-relief-claim-by-32000-cr-says-cag-report/articleshow/132629782.cms",
    sourceLabel: "Times of India — Bengal inflated Amphan relief claim by ₹32,000 cr, says CAG report (25 Jul 2026)",
    sources: [
      "https://indianexpress.com/article/political-pulse/cag-flags-cyclone-amphan-2020-relief-irregularities-tmc-west-bengal-10811195/",
      "https://scroll.in/latest/962646/cyclone-amphan-narendra-modi-announces-rs-1000-crore-as-immediate-relief-for-west-bengal",
      "https://indianexpress.com/article/cities/kolkata/cyclone-amphan-damage-aftermath-6446544/",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister", party: "BJP" }],
    outcome: "After adjusting the state's SDRF balance, the Home Ministry released ₹2,250.28 crore from the NDRF, the Indian Express reported from the CAG audit.",
  },
  {
    id: "hrf031",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "Covid death ex gratia",
    kind: "institution",
    difficulty: "simple",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "After the Supreme Court held in June 2021 that the NDMA had failed its duty, what ex gratia per Covid death did the NDMA recommend?",
    options: ["₹4 lakh", "₹50,000", "₹2 lakh", "₹10,000"],
    correctIndex: 1,
    explanation: "The PIL petitioners had sought ₹4 lakh; the Centre argued Section 12 of the 2005 Act was only recommendatory. The court called ex gratia a statutory duty but left the sum to the NDMA. In October 2021 it approved ₹50,000 per death, paid by states from their disaster response funds within 30 days, and barred refusals just because a death certificate did not say Covid.",
    sourceUrl: "https://www.livelaw.in/top-stories/states-should-not-deny-ex-gratia-for-covid-deaths-on-ground-that-death-certificate-does-not-mention-covid-as-cause-of-death-supreme-court-183028",
    sourceLabel: "LiveLaw — States should not deny ex-gratia for COVID deaths on ground that death certificate does not mention COVID (4 Oct 2021)",
    sources: [
      "https://www.thehindu.com/news/national/covid-19-compensation-sc-pulls-up-ndma-for-failing-to-perform-its-duty/article35049248.ece",
      "https://www.thehindu.com/news/national/covid-19-sc-expresses-concern-over-fake-claims-to-get-aid-meant-for-families-dead/article65223660.ece",
    ],
    tags: ["relief"],
    outcome: "In March 2022 the court voiced concern over fake claims and mooted a CAG inquiry; the Centre asked it to set a deadline for new claims.",
  },
  {
    id: "hrf032",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "Foreign aid accepted (2021)",
    kind: "institution",
    difficulty: "expert",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "Facing oxygen shortages in April 2021, India began accepting help from foreign governments. About how many countries had announced supplies by the end of that month?",
    options: ["About 4", "About 12", "About 120", "About 40"],
    correctIndex: 3,
    explanation: "The Indian Express called it a major shift from the policy of the previous 16 years. The Foreign Secretary said the government would 'do whatever it takes', noting India had itself sent about 6.5 crore vaccine doses to more than 80 countries; officials said India had made no appeal and was accepting gifts with gratitude.",
    sourceUrl: "https://indianexpress.com/article/india/govt-will-do-whatever-it-takes-to-meet-needs-of-people-foreign-secretary-harsh-vardhan-shringla-7296040/",
    sourceLabel: "Indian Express — Govt will do whatever it takes to meet needs of people: Foreign Secretary (30 Apr 2021)",
    sources: ["https://indianexpress.com/article/india/kerala-floods-on-foreign-aid-india-follows-policy-set-in-tsunami-aftermath-5318338/"],
    tags: ["relief"],
    outcome: "Donors included the US, Russia, Japan, France, Germany and the UK; states were also left free to buy oxygen equipment and medicines abroad.",
  },
  {
    id: "hrf033",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "PM CARES oxygen plants",
    kind: "spend",
    difficulty: "expert",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "By October 2021, how many PSA oxygen plants had been funded under PM CARES, with one per district as the aim?",
    options: ["1,224", "162", "5,000", "12,240"],
    correctIndex: 0,
    explanation: "When Modi dedicated 35 plants on 7 October 2021, officials said 1,224 PSA plants had been funded under PM CARES and more than 1,100 commissioned, with over 7,000 people trained to run them, after the second wave's oxygen shortage.",
    sourceUrl: "https://timesofindia.indiatimes.com/india/pm-inaugurates-35-psa-oxygen-plants-including-four-in-odisha/articleshow/86839363.cms",
    sourceLabel: "Times of India — PM inaugurates 35 PSA oxygen plants including four in Odisha (7 Oct 2021)",
    sources: ["https://economictimes.indiatimes.com/news/india/over-half-of-pm-cares-csr-funded-oxygen-plants-in-bengal-remained-non-functional-after-covid-cag/articleshow/132638269.cms"],
    tags: ["relief"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister (chair, PM CARES Fund)", party: "BJP" }],
    outcome: "A CAG audit tabled in West Bengal in July 2026 found 23 of 46 PM CARES plants there working in Dec 2023; the state body said installation was the Centre's and CSR agencies' job.",
  },
  {
    id: "hrf034",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "PM CARES trustees and advisers (2022)",
    kind: "institution",
    difficulty: "expert",
    year: 2022,
    asOf: "2026-09",
    govt: "NDA",
    question: "When PM CARES named new trustees and an advisory board in September 2022, the advisory board included a former holder of which constitutional office?",
    options: ["Chief Election Commissioner", "Comptroller and Auditor General", "Chief Justice of India", "Attorney General of India"],
    correctIndex: 1,
    explanation: "The PMO named Ratan Tata, former Supreme Court judge K.T. Thomas and former Lok Sabha Deputy Speaker Kariya Munda as trustees, and former CAG Rajiv Mehrishi and Sudha Murty to the advisory board. The fund's own accounts are audited by a chartered-accountant firm, not the CAG.",
    status: "Appointments announced by the PMO on 21 Sept 2022; no allegation against anyone named.",
    people: ["Ratan Tata", "K.T. Thomas", "Kariya Munda", "Rajiv Mehrishi", "Sudha Murty"],
    sourceUrl: "https://www.thehindu.com/news/national/modi-chairs-meeting-of-board-of-trustees-of-pm-cares-fund/article65917530.ece",
    sourceLabel: "The Hindu — Ratan Tata, Justice K.T. Thomas, Kariya Munda appointed trustees of PM CARES Fund (21 Sep 2022)",
    sources: ["https://frontline.thehindu.com/politics/pm-cares-fund-audit-transparency-questions/article71373611.ece"],
    tags: ["relief"],
    outcome: "The trustees were told PM CARES for Children supported 4,345 children; the fund spent ₹346 crore on that scheme in 2022-23, its audited accounts show (Frontline).",
  },
  {
    id: "hrf035",
    domain: "civics",
    region: "India",
    state: "KL",
    topic: "Governance & Institutions",
    subtopic: "Wayanad 2024: 'national calamity' plea",
    kind: "institution",
    difficulty: "simple",
    year: 2024,
    asOf: "2026-09",
    govt: "NDA",
    question: "Kerala asked the Centre to declare the July 2024 Wayanad landslides a 'national calamity'. What did the Centre tell Parliament?",
    options: ["It had declared one in August 2024", "Disaster fund rules have no such category", "Only the President can make that call", "Kerala must first spend its CM fund"],
    correctIndex: 1,
    explanation: "The Minister of State for Home told Rajya Sabha on 27 November 2024 that SDRF and NDRF guidelines do not provide for declaring any calamity 'national'; the central team had judged Wayanad a 'disaster of severe nature', which opens NDRF top-ups. Past PMs had publicly called the Kosi (2008) and J&K (2014) floods national disasters.",
    sourceUrl: "https://www.thehindu.com/news/national/kerala/inter-ministerial-central-team-considers-wayanad-landslides-a-disaster-of-severe-nature-centre-informs-kerala/article69044241.ece",
    sourceLabel: "The Hindu — IMCT considers Wayanad landslides a 'disaster of severe nature', Centre informs Kerala (30 Dec 2024)",
    sources: [
      "https://economictimes.indiatimes.com/news/politics-and-nation/pm-sanctions-rs-1000-crore-declares-bihar-flood-national-disaster/articleshow/3419064.cms",
      "https://www.thehindu.com/news/national/Modi-reviews-flood-situation-in-Jammu-with-Omar-Abdullah/article60346187.ece",
    ],
    tags: ["relief"],
    outcome: "The Centre confirmed the 'severe nature' view in a 30 December 2024 letter; its first dedicated NDRF grant for rebuilding Wayanad came in October 2025.",
  },
  {
    id: "hrf036",
    domain: "civics",
    region: "India",
    state: "KL",
    topic: "Environment & Land",
    subtopic: "Wayanad 2025: NDRF award",
    kind: "spend",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "Kerala's post-disaster assessment sought ₹2,221 crore to rebuild Wayanad. How much did the High Level Committee under Amit Shah approve from the NDRF in October 2025?",
    options: ["₹76.16 crore", "₹529.50 crore", "₹1,270.78 crore", "₹260.56 crore"],
    correctIndex: 3,
    explanation: "About 11% of the ask, approved on 1 October 2025, 14 months after the landslides. In February 2025 the Centre had lent ₹529.50 crore interest-free for 50 years under a capital-investment scheme, to be spent by 31 March 2025, which Kerala's finance minister called hard to meet. Shah has said aid follows Finance Commission norms without bias.",
    sourceUrl: "https://www.thenewsminute.com/kerala/union-govt-grants-rs-26056-crore-for-rebuilding-wayanad-hit-by-landslide",
    sourceLabel: "The News Minute — Union govt grants Rs 260.56 crore for rebuilding Wayanad (2 Oct 2025)",
    sources: [
      "https://www.newindianexpress.com/states/kerala/2025/Feb/15/centre-sanctions-rs-5295-crore-loan-for-wayanad-landslide-rehabilitation",
      "https://www.thenewsminute.com/news/cag-report-says-not-even-half-of-emergency-disaster-fund-transferred-to-states",
      "https://indianexpress.com/article/india/no-centralisation-of-power-no-bias-in-funds-amit-shah-as-bill-on-disasters-passed-9906187/",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Amit Shah", role: "Union Home Minister (chair, High Level Committee)", party: "BJP" }],
    outcome: "A first instalment of ₹76.16 crore was released; the Kerala High Court asked Kerala for utilisation certificates and reminded the Centre of cooperative federalism.",
  },
  {
    id: "hrf037",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "Disaster Management (Amendment) Act, 2025",
    kind: "institution",
    difficulty: "simple",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "Replying in Rajya Sabha on the Disaster Management (Amendment) Bill in March 2025, Amit Shah said disaster funds could not be used to pay for what?",
    options: ["Freebies handed out by states", "Salaries of state officials", "Relief to foreign nationals", "Army rescue operations"],
    correctIndex: 0,
    explanation: "'Freebies' was Shah's word: he asked states to seek aid under set norms and denied any centralisation or bias, saying any bias would come from the UPA's 2005 law. TMC's Ritabrata Banerjee said states were 'left at the mercy' of the Union; CPI(M)'s A.A. Rahim said the Centre gave disaster-prone Kerala 'petty amounts'.",
    status: "Statements made in the Rajya Sabha debate of 25 March 2025; no allegation of wrongdoing against anyone named.",
    people: ["Amit Shah", "Ritabrata Banerjee", "A.A. Rahim"],
    sourceUrl: "https://indianexpress.com/article/india/no-centralisation-of-power-no-bias-in-funds-amit-shah-as-bill-on-disasters-passed-9906187/",
    sourceLabel: "Indian Express — No centralisation of power, no bias in funds: Amit Shah as Bill on disasters passed (26 Mar 2025)",
    sources: [
      "https://prsindia.org/billtrack/the-disaster-management-amendment-bill-2024",
      "https://bucketapi.rajyasabha.digital/public-bucket/uploads/committee/2026_08_21_committee_3339_976_6a881941b462a.pdf",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Amit Shah", role: "Union Home Minister", party: "BJP" }],
    outcome: "Passed Rajya Sabha on 25 Mar and Lok Sabha on 27 Mar 2025, allowing urban disaster authorities; a Rajya Sabha committee said in Aug 2026 that only Karnataka had set one up (for Bengaluru).",
  },
  {
    id: "hrf038",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Environment & Land",
    subtopic: "16th Finance Commission disaster funds",
    kind: "institution",
    difficulty: "expert",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "The 16th Finance Commission recommended adding which two hazards to the national list of disasters that the funds can pay for?",
    options: ["Drought and floods", "Heatwave and lightning", "Pandemics and epidemics", "Coastal erosion and fog"],
    correctIndex: 1,
    explanation: "It also recommended a record ₹2,83,807 crore disaster corpus for 2026–31 — ₹2,04,401 crore for state funds and ₹79,406 crore for national funds, against ₹1,60,153 crore and ₹68,463 crore under the 15th — and proposed capping SDRF releases where unspent balances exceed three years' allocations.",
    sourceUrl: "https://bucketapi.rajyasabha.digital/public-bucket/uploads/committee/2026_08_21_committee_3339_976_6a881941b462a.pdf",
    sourceLabel: "Rajya Sabha Standing Committee on Home Affairs — 261st Report (Aug 2026), paras 2.13.21–2.13.25",
    sources: ["https://factly.in/india-scales-up-disaster-funding-but-local-preparedness-lags/"],
    tags: ["relief"],
    outcome: "Lightning caused 35.8% of natural-hazard deaths in 2022 (2,887 of 8,060), the committee noted, urging the MHA to notify both hazards nationally.",
  },
  {
    id: "hrf039",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "CAG: unspent NDRF money (2024-25)",
    kind: "spend",
    difficulty: "extreme",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "The CAG's report on the Union's 2024-25 accounts found how much of ₹11,474 crore meant as NDRF aid to states was actually transferred?",
    options: ["About ₹1,147 crore", "About ₹5,356 crore", "About ₹9,800 crore", "All of it"],
    correctIndex: 1,
    explanation: "The other ₹6,117.97 crore (about 53%) was booked as savings. Only ₹719.72 crore of ₹2,868 crore for mitigation and ₹3,350 crore of ₹20,000 crore in special assistance reached states. NDRF aid needs a state memorandum, a central team's assessment and HLC approval; the coverage carried no ministry reply.",
    sourceUrl: "https://www.thenewsminute.com/news/cag-report-says-not-even-half-of-emergency-disaster-fund-transferred-to-states",
    sourceLabel: "The News Minute — CAG report says not even half of emergency disaster funds transferred to states (16 Aug 2026)",
    sources: ["https://english.mathrubhumi.com/news/kerala/centre-disaster-funds-unspent-kerala-wayanad-compensation-pending-kjwl88re"],
    tags: ["relief"],
    outcome: "The CAG flagged 'persistent savings' in transfers to states across schemes — ₹67,882 crore, ₹46,013 crore and ₹36,219 crore in 2022-23 to 2024-25 — despite its past audit reports.",
  },
  {
    id: "hrf040",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "PMO note on Parliament questions (2026)",
    kind: "institution",
    difficulty: "simple",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "Why did the PMO tell the Lok Sabha Secretariat in January 2026 that questions on PM CARES, PMNRF and the National Defence Fund were not admissible?",
    options: ["They were sub judice", "Their money is donations, not from the Consolidated Fund", "The CAG already audits them", "They are secret defence matters"],
    correctIndex: 1,
    explanation: "The PMO's 30 January note cited Lok Sabha Rules 41(2)(viii) and (xvii) — matters not primarily the Government of India's concern, or controlled by bodies not primarily responsible to it — because the corpus is entirely voluntary contributions. The PM chairs all three funds. The Congress and RTI campaigners said it blocked scrutiny.",
    sourceUrl: "https://indianexpress.com/article/explained/why-pmo-says-no-question-on-pm-cares-two-other-funds-10521976/",
    sourceLabel: "Indian Express — PMO says no question on PM CARES, two other funds admissible in Lok Sabha: Reasons it gave (9 Feb 2026)",
    sources: [
      "https://m.thewire.in/article/government/parliament-questions-and-matters-related-to-pm-cares-not-admissible-pmo-tells-lok-sabha-secretariat-report",
      "https://thefederal.com/category/news/pm-cares-parliament-questions-ban-pmo-rules-229160",
      "https://www.etvbharat.com/en/bharat/congress-attacks-pmo-over-bar-on-questions-on-pm-cares-fund-pmnrf-ndf-enn26020902964",
    ],
    tags: ["relief"],
    outcome: "The reasoning echoes the Centre's January 2023 Delhi High Court affidavit that PM CARES is not a 'public authority' under the RTI Act.",
  },
  {
    id: "hrf041",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "PMNRF audit and balance",
    kind: "institution",
    difficulty: "simple",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "Who audits the Prime Minister's National Relief Fund, set up in 1948 and now used mainly to help families of those killed in disasters?",
    options: ["The Comptroller and Auditor General", "Parliament's Public Accounts Committee", "An independent CA firm outside government", "The Income Tax Department"],
    correctIndex: 2,
    explanation: "PMNRF's FAQ says an independent auditor outside the government audits it — currently KKC & Associates LLP, Mumbai — with no statutory deadline for the audit. The fund takes only voluntary donations, gets no budgetary support, is not constituted by Parliament, and disburses at the Prime Minister's discretion.",
    sourceUrl: "https://pmnrf.gov.in/en/faqs/pmnrf",
    sourceLabel: "PMNRF — FAQs (pmnrf.gov.in, accessed Sep 2026)",
    sources: ["https://pmnrf.gov.in/en/about"],
    tags: ["relief"],
    outcome: "It closed 2024-25 with ₹6,852.19 crore after ₹695 crore of income and ₹282.43 crore of spending, up from ₹2,637.03 crore in 2015-16.",
  },
]);
