// HISAAB DO — engine placeholder lane (ids hzz001–hzz016).
//
// Sixteen simple, central-scheme facts that let the edition build, route, deal and duel before the
// nine content lanes land. Every fact below was read on the cited official page in September 2026
// (the scheme portals of the ministries that run them); nothing names a person or alleges wrongdoing.
// The lead may retire this lane once the real lanes are registered in index.mjs.
export const HISAAB_SAMPLE = Object.freeze([
  {
    id: 'hzz001',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Farm & Food',
    subtopic: 'PM-KISAN',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'Under PM-KISAN, how much income support does an eligible land-holding farmer family get in a year?',
    options: ['₹6,000', '₹10,000', '₹12,000', '₹4,000'],
    correctIndex: 0,
    explanation:
      'PM-KISAN pays ₹6,000 a year to land-holding farmer families, transferred directly to their bank accounts. States and UTs identify the eligible families; higher-income categories such as institutional land holders are excluded.',
    sourceUrl: 'https://pmkisan.gov.in/',
    sourceLabel: 'PM-KISAN portal, Ministry of Agriculture & Farmers Welfare — scheme overview (accessed Sep 2026)',
  },
  {
    id: 'hzz002',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Farm & Food',
    subtopic: 'PM-KISAN',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question: "PM-KISAN's yearly income support reaches farmer families in how many equal instalments?",
    options: ['Two', 'Three', 'Four', 'Twelve'],
    correctIndex: 1,
    explanation:
      'The official portal says the ₹6,000 a year is provided in three equal instalments to all land-holding farmer families, with the money transferred directly to the beneficiaries’ bank accounts.',
    sourceUrl: 'https://pmkisan.gov.in/',
    sourceLabel: 'PM-KISAN portal, Ministry of Agriculture & Farmers Welfare — scheme overview (accessed Sep 2026)',
  },
  {
    id: 'hzz003',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Farm & Food',
    subtopic: 'PM-KISAN',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'According to its official portal, from which date did PM-KISAN become operational?',
    options: ['1 February 2019', '24 February 2019', '1 December 2018', '15 August 2018'],
    correctIndex: 2,
    explanation:
      'The PM-KISAN portal states that the scheme became operational from 1 December 2018. It is a Central Sector scheme, fully funded by the Government of India.',
    sourceUrl: 'https://pmkisan.gov.in/',
    sourceLabel: 'PM-KISAN portal, Ministry of Agriculture & Farmers Welfare — scheme overview (accessed Sep 2026)',
  },
  {
    id: 'hzz004',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Farm & Food',
    subtopic: 'PM-KISAN',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question: "What share of PM-KISAN's funding comes from the Government of India?",
    options: ['60%', '75%', '50%', '100%'],
    correctIndex: 3,
    explanation:
      'PM-KISAN is a Central Sector scheme with 100% funding from the Government of India. State Governments and UT administrations identify the farmer families eligible under the scheme guidelines.',
    sourceUrl: 'https://pmkisan.gov.in/',
    sourceLabel: 'PM-KISAN portal, Ministry of Agriculture & Farmers Welfare — scheme overview (accessed Sep 2026)',
  },
  {
    id: 'hzz005',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Farm & Food',
    subtopic: 'National Food Security Act',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2013,
    asOf: '2026-09',
    govt: 'UPA',
    question: "The National Food Security Act, 2013 entitles up to what share of India's rural population to subsidised foodgrains?",
    options: ['75%', '50%', '90%', '60%'],
    correctIndex: 0,
    explanation:
      'The Act covers up to 75% of the rural and 50% of the urban population — about two-thirds of the country — through the Targeted Public Distribution System, per the Department of Food and Public Distribution.',
    sourceUrl: 'https://nfsa.gov.in/portal/nfsa-act',
    sourceLabel: 'NFSA portal, Department of Food & Public Distribution — National Food Security Act (accessed Sep 2026)',
  },
  {
    id: 'hzz006',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Farm & Food',
    subtopic: 'National Food Security Act',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2013,
    asOf: '2026-09',
    govt: 'UPA',
    question: 'Under the National Food Security Act, how much foodgrain is an Antyodaya Anna Yojana household entitled to each month?',
    options: ['5 kg per family', '35 kg per family', '20 kg per family', '50 kg per family'],
    correctIndex: 1,
    explanation:
      'Antyodaya Anna Yojana households, the poorest of the poor, are entitled to 35 kg of foodgrains per family per month; priority households get 5 kg per person per month.',
    sourceUrl: 'https://nfsa.gov.in/portal/nfsa-act',
    sourceLabel: 'NFSA portal, Department of Food & Public Distribution — National Food Security Act (accessed Sep 2026)',
  },
  {
    id: 'hzz007',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Welfare & Subsidies',
    subtopic: 'PM Ujjwala Yojana',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2016,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'The Pradhan Mantri Ujjwala Yojana, which gives LPG connections to deprived households, was launched on 1 May 2016 in which town?',
    options: ['Varanasi', 'Gorakhpur', 'Ballia', 'Lucknow'],
    correctIndex: 2,
    explanation:
      'PMUY was launched on 1 May 2016 in Ballia, Uttar Pradesh, to make clean cooking fuel such as LPG available to rural and deprived households that had been cooking with firewood, coal or cow-dung cakes.',
    sourceUrl: 'https://www.pmuy.gov.in/about.html',
    sourceLabel: 'PMUY, Ministry of Petroleum & Natural Gas — About PMUY (accessed Sep 2026)',
  },
  {
    id: 'hzz008',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Welfare & Subsidies',
    subtopic: 'PM Ujjwala Yojana',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2016,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'Which ministry introduced the Pradhan Mantri Ujjwala Yojana in May 2016?',
    options: ['Rural Development', 'Women and Child Development', 'Consumer Affairs, Food and Public Distribution', 'Petroleum and Natural Gas'],
    correctIndex: 3,
    explanation:
      'The Ministry of Petroleum and Natural Gas introduced PMUY as a flagship scheme, citing the harm traditional cooking fuels did to the health of rural women and to the environment.',
    sourceUrl: 'https://www.pmuy.gov.in/about.html',
    sourceLabel: 'PMUY, Ministry of Petroleum & Natural Gas — About PMUY (accessed Sep 2026)',
  },
  {
    id: 'hzz009',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Welfare & Subsidies',
    subtopic: 'PM Ujjwala Yojana',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2016,
    asOf: '2026-09',
    govt: 'NDA',
    question: "What was Ujjwala's original target for LPG connections to deprived households, to be met by March 2020?",
    options: ['8 crore', '5 crore', '10 crore', '3 crore'],
    correctIndex: 0,
    explanation:
      'The target was to release 8 crore LPG connections to deprived households by March 2020. The scheme site records the 8th crore connection being handed over on 7 September 2019.',
    sourceUrl: 'https://www.pmuy.gov.in/about.html',
    sourceLabel: 'PMUY, Ministry of Petroleum & Natural Gas — About PMUY (accessed Sep 2026)',
  },
  {
    id: 'hzz010',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Welfare & Subsidies',
    subtopic: 'PM Ujjwala Yojana',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2019,
    asOf: '2026-09',
    govt: 'NDA',
    question: "In which city was Ujjwala's 8th crore LPG connection handed over, on 7 September 2019?",
    options: ['Nagpur', 'Aurangabad', 'Nashik', 'Pune'],
    correctIndex: 1,
    explanation:
      'The 8th crore connection was handed over in Aurangabad, Maharashtra, on 7 September 2019, meeting the scheme’s first target of 8 crore connections ahead of its March 2020 deadline.',
    sourceUrl: 'https://www.pmuy.gov.in/about.html',
    sourceLabel: 'PMUY, Ministry of Petroleum & Natural Gas — About PMUY (accessed Sep 2026)',
  },
  {
    id: 'hzz011',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Welfare & Subsidies',
    subtopic: 'PM Ujjwala Yojana',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2021,
    asOf: '2026-09',
    govt: 'NDA',
    question: "The Ujjwala site puts India's LPG coverage at 62% on 1 May 2016. What figure does it give for 1 April 2021?",
    options: ['89.5%', '94.2%', '97.1%', '99.8%'],
    correctIndex: 3,
    explanation:
      'The scheme site credits the release of 8 crore connections with helping raise LPG coverage from 62% on 1 May 2016 to 99.8% as on 1 April 2021. Both figures are the ministry’s own.',
    sourceUrl: 'https://www.pmuy.gov.in/about.html',
    sourceLabel: 'PMUY, Ministry of Petroleum & Natural Gas — About PMUY (accessed Sep 2026)',
  },
  {
    id: 'hzz012',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Welfare & Subsidies',
    subtopic: 'PM Ujjwala Yojana',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'After Ujjwala 2.0 met its target in December 2022, how many LPG connections had the scheme released overall?',
    options: ['7.2 crore', '9.6 crore', '12 crore', '8.8 crore'],
    correctIndex: 1,
    explanation:
      'Ujjwala 2.0 added 1.6 crore connections, with a special facility for migrant households; meeting that target in December 2022 took the overall total to 9.6 crore. A further 75 lakh were allocated for FY 2023-24 to 2025-26.',
    sourceUrl: 'https://www.pmuy.gov.in/about.html',
    sourceLabel: 'PMUY, Ministry of Petroleum & Natural Gas — About PMUY (accessed Sep 2026)',
  },
  {
    id: 'hzz013',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'PM Jan Dhan Yojana',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2014,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'What minimum balance must a Pradhan Mantri Jan Dhan Yojana account holder keep in the account?',
    options: ['None at all', '₹500', '₹1,000', '₹100'],
    correctIndex: 0,
    explanation:
      'PMJDY accounts are basic savings bank deposit accounts with no requirement to maintain a minimum balance. They earn interest and come with a RuPay debit card, per the Department of Financial Services.',
    sourceUrl: 'https://pmjdy.gov.in/scheme',
    sourceLabel: 'PMJDY, Department of Financial Services — Scheme details (accessed Sep 2026)',
  },
  {
    id: 'hzz014',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'PM Jan Dhan Yojana',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'For Jan Dhan accounts opened after 28 August 2018, what accident insurance cover comes with the RuPay card?',
    options: ['₹1 lakh', '₹50,000', '₹2 lakh', '₹5 lakh'],
    correctIndex: 2,
    explanation:
      'The accident insurance cover of ₹1 lakh that came with the RuPay card was enhanced to ₹2 lakh for PMJDY accounts opened after 28 August 2018, per the scheme details published by the Department of Financial Services.',
    sourceUrl: 'https://pmjdy.gov.in/scheme',
    sourceLabel: 'PMJDY, Department of Financial Services — Scheme details (accessed Sep 2026)',
  },
  {
    id: 'hzz015',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'PM Jan Dhan Yojana',
    kind: 'scheme',
    difficulty: 'extreme',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'Up to what amount can an eligible Jan Dhan account holder draw as an overdraft?',
    options: ['₹5,000', '₹25,000', '₹50,000', '₹10,000'],
    correctIndex: 3,
    explanation:
      'An overdraft facility of up to ₹10,000 is available to eligible PMJDY account holders. The accounts are also eligible for Direct Benefit Transfer and for the government’s insurance and pension schemes.',
    sourceUrl: 'https://pmjdy.gov.in/scheme',
    sourceLabel: 'PMJDY, Department of Financial Services — Scheme details (accessed Sep 2026)',
  },
  {
    id: 'hzz016',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Infrastructure',
    subtopic: 'Jal Jeevan Mission',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2019,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'According to its official site, by what year was the Jal Jeevan Mission envisioned to give every rural household a tap connection?',
    options: ['2022', '2030', '2024', '2026'],
    correctIndex: 2,
    explanation:
      'The Jal Jeevan Mission was envisioned to provide safe and adequate drinking water through individual household tap connections to all rural households by 2024, with source sustainability measures such as rainwater harvesting as mandatory elements.',
    sourceUrl: 'https://jaljeevanmission.gov.in/',
    sourceLabel: 'Jal Jeevan Mission, Ministry of Jal Shakti — mission overview (accessed Sep 2026)',
  },
]);
