// HISAAB DO — lane: National scams, frauds & accountability institutions (prefix hgh).
// Contract: editions/hisaab/bank/schema.mjs and docs/hisaab/CHARTER.md §2–§5.
// Every item was checked against the page in sourceUrl; statuses were re-verified in Sept 2026
// (see docs/hisaab/research/scams-notes.md for sources, drops and items at risk of going stale).
// Stems say "was named in / arrested by / alleged by / the court held"; no item implies the guilt
// of anyone not convicted, and no distractor names a real person.

export const HISAAB_SCAMS = Object.freeze([
  {
    id: 'hgh001',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'PNB fraud',
    kind: 'scam',
    difficulty: 'expert',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question: "The CBI says the PNB fraud's Letters of Undertaking, issued from 2011 and exposed in 2018, escaped notice for years mainly because of what?",
    options: ['RBI had exempted diamond traders from bank audits', "Entries were not made in the bank's core banking software", 'The LoUs were issued by an overseas branch outside RBI rules', "PNB's auditors were barred from the Mumbai branch"],
    correctIndex: 1,
    explanation: "Per the CBI (The Hindu, 2022), suspect transactions began in 2011 and stayed hidden because major entries were not made in PNB's Core Banking Software; the first case was filed on Jan 31, 2018 and the fraud is put at about ₹13,578 crore. Accused jewellers Nirav Modi and Mehul Choksi deny the charges and are fighting extradition from the UK and Belgium.",
    status: 'Nirav Modi and Mehul Choksi: accused in CBI/ED cases, not tried; both abroad contesting extradition and deny the charges (as of Sept 2026).',
    people: ['Nirav Modi', 'Mehul Choksi'],
    sourceUrl: 'https://www.thehindu.com/news/national/the-case-against-mehul-choksi/article65447372.ece',
    sourceLabel: 'The Hindu — Explained: The case against Mehul Choksi (May 2022)',
    sources: ['https://www.cnn.com/2026/08/09/india/india-nirav-modi-extradition-intl-hnk', 'https://m.thewire.in/article/diplomacy/belgium-says-it-only-updated-modi-on-choksi-extradition-during-pm-de-wevers-visit'],
  },
  {
    id: 'hgh002',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Nirav Modi extradition',
    kind: 'scam',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'As of August 2026, where was diamantaire Nirav Modi, wanted in India in the PNB fraud case?',
    options: ["In Mumbai's Arthur Road jail, facing trial", 'Free on bail in Belgium', 'In a London prison, awaiting extradition after losing appeals', 'Living in Antigua as its citizen'],
    correctIndex: 2,
    explanation: 'Arrested in London in March 2019, he lost his UK appeals; in March 2026 the UK High Court refused to reopen the case and in July 2026 Indian media reported the European Court of Human Rights had turned him down (the ECHR told CNN nothing was pending in his name). He denies the allegations and says he owes the bank far less.',
    status: 'Accused in CBI/ED PNB cases; in UK custody since March 2019 awaiting extradition; not tried; denies the charges (Aug 2026).',
    people: ['Nirav Modi'],
    sourceUrl: 'https://www.cnn.com/2026/08/09/india/india-nirav-modi-extradition-intl-hnk',
    sourceLabel: 'CNN — The rapid unraveling of a billionaire diamond dealer to the stars (9 Aug 2026)',
    sources: ['https://www.businesstoday.in/india/story/nirav-modi-extradition-echr-rejects-final-plea-uk-starts-transfer-process-541227-2026-07-06', 'https://www.newsonair.gov.in/nirav-modi-faces-setback-as-uk-high-court-rejects-plea-to-reopen-extradition-case', 'https://www.tribuneindia.com/news/india/nirav-modis-extradition-to-happen-after-ongoing-legal-proceedings-end-mea/'],
  },
  {
    id: 'hgh003',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Mehul Choksi extradition',
    kind: 'scam',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'Mehul Choksi, an accused in the PNB fraud case, was arrested in April 2025 at the CBI’s request in which European country?',
    options: ['Belgium', 'United Kingdom', 'Switzerland', 'Netherlands'],
    correctIndex: 0,
    explanation: "He was held in Antwerp. A Belgian appeals court cleared extradition on Oct 17, 2025, rejecting his claim that he risked torture, and the Court of Cassation dismissed his appeal in Dec 2025. As of Sept 2026 Belgium's justice minister had not decided and Belgium said it had only 'updated' India. Choksi denies the charges.",
    status: 'Accused in CBI/ED cases; in Belgian custody since April 2025; courts cleared extradition, executive decision pending; not tried; denies charges (Sept 2026).',
    people: ['Mehul Choksi'],
    sourceUrl: 'https://www.newsonair.gov.in/belgiums-top-court-rejects-indian-fugitive-mehul-choksis-appeal-against-arrest',
    sourceLabel: "Akashvani News — Belgium's top court rejects Mehul Choksi's appeal (10 Dec 2025)",
    sources: ['https://m.thewire.in/article/diplomacy/belgium-says-it-only-updated-modi-on-choksi-extradition-during-pm-de-wevers-visit', 'https://newsonair.gov.in/belgium-police-arrest-fugitive-diamond-trader-mehul-choksi'],
  },
  {
    id: 'hgh004',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Mehul Choksi extradition',
    kind: 'scam',
    difficulty: 'simple',
    year: 2021,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In May 2021 PNB-fraud accused Mehul Choksi went missing from Antigua and was detained days later in which Caribbean country?',
    options: ['Jamaica', 'Barbados', 'Trinidad and Tobago', 'Dominica'],
    correctIndex: 3,
    explanation: 'He was detained in Dominica for illegal entry; his family and lawyers alleged he was abducted by boat. Dominica let him return to Antigua on bail and in 2022 dropped all charges. He had moved to Antigua in Jan 2018, days before the first CBI case. He denies the PNB charges and now contests extradition from Belgium.',
    status: 'Accused in CBI/ED cases, not tried; in Belgian custody contesting extradition; denies charges (Sept 2026).',
    people: ['Mehul Choksi'],
    sourceUrl: 'https://www.thehindu.com/news/national/the-case-against-mehul-choksi/article65447372.ece',
    sourceLabel: 'The Hindu — Explained: The case against Mehul Choksi (May 2022)',
    sources: ['https://m.thewire.in/article/diplomacy/belgium-says-it-only-updated-modi-on-choksi-extradition-during-pm-de-wevers-visit'],
  },
  {
    id: 'hgh005',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Vijay Mallya',
    kind: 'scam',
    difficulty: 'simple',
    year: 2019,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In January 2019 a special PMLA court in Mumbai made Vijay Mallya the first person to be declared what under a 2018 law?',
    options: ['A benami property holder', 'A fugitive economic offender', 'A habitual bank defaulter', 'An undischarged insolvent'],
    correctIndex: 1,
    explanation: "On the ED's plea, the court declared him an FEO under the Fugitive Economic Offenders Act, 2018, allowing confiscation of his assets. Mallya, in the UK since 2016, has denied fleeing and says he offered to repay. In Dec 2025 the Bombay HC said it would hear his challenge to the Act only once he says when he will return.",
    status: 'Declared FEO (Jan 2019); CBI/ED cases pending, not tried; in the UK; denies wrongdoing (Dec 2025).',
    people: ['Vijay Mallya'],
    sourceUrl: 'https://www.onmanorama.com/news/india/2019/01/05/mumbai-fugitive-economic-offender.html',
    sourceLabel: 'Manorama — Mumbai court declares Vijay Mallya fugitive economic offender (5 Jan 2019)',
    sources: ['https://www.india.com/news/india/special-pmla-court-declares-vijay-mallya-a-fugitive-economic-offender-3511907/', 'https://www.etvbharat.com/en/bharat/bombay-hc-instructs-fugitive-economic-offender-vijay-mallya-to-return-to-india-enn25122304949'],
  },
  {
    id: 'hgh006',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Vijay Mallya',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In December 2024 the Finance Minister told Lok Sabha that public sector banks had recovered how much from the sale of Vijay Mallya’s assets?',
    options: ['₹14,131.6 crore', '₹9,000 crore', '₹3,560 crore', '₹22,280 crore'],
    correctIndex: 0,
    explanation: "Nirmala Sitharaman said ₹14,131.6 crore of Mallya's assets went back to PSBs, part of ₹22,280 crore the ED restored in economic-offence cases. Mallya replied that the Debt Recovery Tribunal had fixed the Kingfisher debt at ₹6,203 crore, so banks had taken more than double, and said he would seek relief.",
    status: 'Declared FEO; CBI/ED cases pending, not tried; disputes the dues (Dec 2024; Bombay HC hearing Dec 2025).',
    people: ['Vijay Mallya', 'Nirmala Sitharaman'],
    sourceUrl: 'https://www.business-standard.com/india-news/vijay-mallya-assets-recovered-nirmala-sitharaman-ed-124121800573_1.html',
    sourceLabel: "Business Standard — Rs 14,131.6 crore recovered from Vijay Mallya's asset sales: FM (18 Dec 2024)",
    sources: ['https://www.deccanherald.com/amp/story/india%2Fmallya-slams-fm-s-statement-on-seized-assets-says-will-seek-relief-3323716', 'https://www.etvbharat.com/en/bharat/bombay-hc-instructs-fugitive-economic-offender-vijay-mallya-to-return-to-india-enn25122304949'],
  },
  {
    id: 'hgh007',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Vijay Mallya',
    kind: 'scam',
    difficulty: 'expert',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In July 2022 the Supreme Court sentenced Vijay Mallya to four months in prison for contempt of court. What was the contempt about?',
    options: ['Skipping hearings in the Kingfisher insolvency case', 'Criticising judges in a London interview', 'Selling Kingfisher House without court approval', 'Moving US$40 million to his children despite court orders'],
    correctIndex: 3,
    explanation: "The Court had found him guilty in 2017 of transferring $40 million to his children in breach of orders in the SBI-led banks' case. It added a ₹2,000 fine, noted he showed no remorse, and ordered the money redeposited with 8% interest. This is a contempt sentence, not a verdict in the loan-fraud cases, which remain untried.",
    status: 'Convicted of contempt (SC 2017, sentenced July 2022); fraud and PMLA cases not tried; in the UK (Dec 2025).',
    people: ['Vijay Mallya'],
    sourceUrl: 'https://www.livelaw.in/top-stories/supreme-court-sentences-vijay-mallya-to-4-months-imprisonment-for-contempt-of-court-asks-him-to-deposit-40-million-us-dollars-203407',
    sourceLabel: 'LiveLaw — Supreme Court sentences Vijay Mallya to 4 months for contempt (11 Jul 2022)',
    sources: ['https://factly.in/vijay-mallya-was-sentenced-to-imprisonment-in-the-contempt-of-court-case-not-in-the-9000-crore-bank-loan-default-case/', 'https://www.etvbharat.com/en/bharat/bombay-hc-instructs-fugitive-economic-offender-vijay-mallya-to-return-to-india-enn25122304949'],
  },
  {
    id: 'hgh008',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'Fugitive economic offenders',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: "As of Oct 31, 2025, how many people had special courts declared 'fugitive economic offenders' under the 2018 Act, per the Centre?",
    options: ['5', '42', '15', '108'],
    correctIndex: 2,
    explanation: 'MoS Finance Pankaj Chaudhary told Lok Sabha (Dec 1, 2025) that 15 persons, including Vijay Mallya and Nirav Modi, had been declared FEOs; together they owed ₹58,082 crore (₹26,645 crore principal plus ₹31,437 crore interest) to 12 public sector banks, and about ₹19,187 crore had been recovered. Two had negotiated one-time settlements.',
    status: 'FEO is a declaration that a person has fled prosecution, not a conviction; the named individuals have not been tried (Dec 2025).',
    people: ['Vijay Mallya', 'Nirav Modi', 'Pankaj Chaudhary'],
    sourceUrl: 'https://www.deccanherald.com/india/centre-says-15-fugitive-economic-offenders-including-vijay-mallya-nirav-modi-owe-rs-58000-cr-to-banks-3816219',
    sourceLabel: 'Deccan Herald (PTI) — 15 fugitive economic offenders owe Rs 58,000 cr to banks (1 Dec 2025)',
  },
  {
    id: 'hgh009',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'DHFL bank fraud',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDA',
    question: "In the CBI's DHFL bank-fraud case, the company's books allegedly showed loan money going to roughly how many fictitious retail borrowers?",
    options: ['About 26,000', 'About 2.6 lakh', 'About 26 lakh', 'About 2,600'],
    correctIndex: 1,
    explanation: "CBI's June 2022 FIR alleges promoters Kapil and Dheeraj Wadhawan cheated a 17-bank consortium (loss ₹34,926 crore) via 87 shell firms, with 2,60,315 fictitious borrowers and a virtual 'Bandra branch-001'. In Dec 2025 the Supreme Court granted them bail, noting 736 witnesses meant trial could not end soon. The charges are unproven.",
    status: 'Kapil and Dheeraj Wadhawan: chargesheeted by CBI; granted bail by the Supreme Court (Dec 2025); trial pending; not convicted.',
    people: ['Kapil Wadhawan', 'Dheeraj Wadhawan'],
    sourceUrl: 'https://lawbeat.in/top-stories/34926-crores-dhfl-bank-fraud-case-supreme-court-grants-bail-to-kapil-and-dheeraj-wadhwan-1548046',
    sourceLabel: 'LawBeat — DHFL bank fraud case: Supreme Court grants bail to Wadhawan brothers (17 Dec 2025)',
    sources: ['https://www.scconline.com/blog/post/2025/08/08/dhc-denies-bail-to-dhf-promoter-kapil-wadhawan-in-bank-fraud-case/'],
  },
  {
    id: 'hgh010',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'ABG Shipyard fraud',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'The ABG Shipyard case, registered by the CBI in Feb 2022, alleged a ₹22,842-crore fraud on a consortium of how many banks?',
    options: ['8', '17', '45', '28'],
    correctIndex: 3,
    explanation: "SBI's complaint said a 28-bank consortium led by ICICI Bank was cheated. The CBI chargesheeted the company, its ex-chairman and 23 others in Nov 2022, alleging diversion via related parties; no verdict has been reported. In data given to Parliament for March 2025, ABG Shipyard topped India's wilful defaulters at ₹6,695 crore.",
    status: 'Company and former executives chargesheeted by CBI (Nov 2022); trial pending, no verdict reported (checked Sept 2026).',
    sourceUrl: 'https://www.business-standard.com/article/companies/cbi-files-chargesheet-in-rs-22-000-crore-abg-shipyard-loan-fraud-case-122112000043_1.html',
    sourceLabel: 'Business Standard (IANS) — CBI files chargesheet in ABG Shipyard loan fraud case (20 Nov 2022)',
    sources: ['https://www.moneylife.in/article/from-39369-crore-to-383264-crore-in-10-years-indias-wilful-default-crisis-laid-bare-in-parliament-abg-shipyard-leads-at-6695-crore/79963.html'],
  },
  {
    id: 'hgh011',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Yes Bank rescue',
    kind: 'institution',
    difficulty: 'simple',
    year: 2020,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'When the RBI placed Yes Bank under a moratorium in March 2020, what was the normal withdrawal cap per depositor?',
    options: ['₹10,000', '₹50,000', '₹1 lakh', '₹25,000'],
    correctIndex: 1,
    explanation: 'RBI superseded the board and capped withdrawals at ₹50,000 (up to ₹5 lakh for medical, education or wedding needs), saying the bank had failed to find a credible revival plan. An SBI-led rescue followed and full services resumed on March 18, 2020.',
    sourceUrl: 'https://timesofindia.indiatimes.com/business/india-business/rbi-supersedes-yes-bank-board-caps-withdrawals-at-rs-50000/articleshow/74502162.cms',
    sourceLabel: 'Times of India — RBI supersedes Yes Bank board, caps withdrawals at Rs 50,000 (6 Mar 2020)',
    sources: ['https://www.newindianexpress.com/business/2020/Mar/18/yes-bank-resumes-operations-all-banking-services-available-for-customers-now-2118411.html'],
  },
  {
    id: 'hgh012',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Yes Bank cases',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'Yes Bank co-founder Rana Kapoor, arrested by the ED in March 2020, left jail in April 2024 after bail in all eight cases. Roughly how long was he held?',
    options: ['About six months', 'About ten years', 'About eighteen months', 'About four years'],
    correctIndex: 3,
    explanation: "A Mumbai special court granted bail in the last pending CBI case on April 19, 2024, noting the trial had not begun; his lawyers called the allegations 'vague'. In 2026 fresh complaints naming him were under investigation. He has not been convicted in any case.",
    status: 'Accused in eight ED/CBI cases; on bail since April 2024; trials pending; fresh complaints under probe (Aug 2026); not convicted.',
    people: ['Rana Kapoor'],
    sourceUrl: 'https://www.business-standard.com/companies/news/yes-bank-founder-rana-kapoor-gets-bail-walks-out-of-jail-after-4-years-124041901285_1.html',
    sourceLabel: 'Business Standard (PTI) — Rana Kapoor gets bail, walks out of jail after 4 years (19 Apr 2024)',
    sources: ['https://www.newindianexpress.com/business/2026/Aug/05/yes-bank-ex-md-rana-kapoor-suraksha-arc-promoter-valia-under-investigation-in-rs-600-crore-loan-assignment'],
  },
  {
    id: 'hgh013',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'ICICI–Videocon case',
    kind: 'scam',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question: "In Feb 2024 the Bombay High Court ruled on the CBI's Dec 2022 arrest of ex-ICICI Bank CEO Chanda Kochhar in the Videocon loan case. What did it hold?",
    options: ['The arrest was illegal, made without application of mind', 'The arrest was valid and her bail was cancelled', 'The case had to move to a special PMLA court', 'The CBI needed RBI sanction before any arrest'],
    correctIndex: 0,
    explanation: "The HC said arresting her and husband Deepak Kochhar on material already known when the Sec 41A notice was issued was an 'abuse of power', and confirmed their bail. Separately, a SAFEMA appellate tribunal in July 2025 upheld ED's asset attachment, finding a ₹64-crore quid pro quo; the Kochhars have challenged that in the HC. No criminal verdict yet.",
    status: 'Chanda and Deepak Kochhar: chargesheeted by CBI; arrest held illegal (Feb 2024); on bail; ED attachment upheld by tribunal, under challenge (Dec 2025); not convicted.',
    people: ['Chanda Kochhar', 'Deepak Kochhar'],
    sourceUrl: 'https://www.barandbench.com/news/chanda-kochhar-deepak-kochhar-cbi-arrest-icici-videocon-loan-case-illegal-bombay-high-court',
    sourceLabel: "Bar & Bench — CBI's arrest of Chanda Kochhar was illegal: Bombay High Court (6 Feb 2024)",
    sources: ['https://lawbeat.in/news-updates/videocon-scam-deepak-and-chanda-kochhar-move-bombay-high-court-against-eds-property-attachment-1546598', 'https://timesofindia.indiatimes.com/india/chanda-kochhar-got-rs-64-crore-bribe-to-ok-videocon-loan-tribunal/articleshow/122801576.cms'],
  },
  {
    id: 'hgh014',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Defence & Security',
    subtopic: 'Rafale deal',
    kind: 'scam',
    difficulty: 'simple',
    year: 2019,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In November 2019 the Supreme Court decided review petitions against its December 2018 Rafale verdict. What did it do?',
    options: ['Ordered a CBI probe into the pricing', 'Sent the deal to a Joint Parliamentary Committee', 'Asked the CAG to re-audit the offset contracts', 'Dismissed them, finding no merit and no need for an FIR'],
    correctIndex: 3,
    explanation: 'A bench led by CJI Ranjan Gogoi dismissed the reviews on Nov 14, 2019, reiterating there was no occasion to doubt the decision-making in buying 36 jets in the roughly ₹58,000-crore deal. Petitioners had alleged irregularities in pricing and the choice of offset partner; the ruling was read as a second clean chit to the government.',
    status: 'Supreme Court dismissed petitions seeking a probe (Dec 2018) and the review (Nov 2019); no Indian criminal case.',
    sourceUrl: 'https://timesofindia.indiatimes.com/india/supreme-court-gives-clean-chit-to-modi-government-in-rafale-deal/articleshow/72050668.cms',
    sourceLabel: 'Times of India — Supreme Court dismisses pleas seeking review of Rafale judgment (14 Nov 2019)',
    sources: ['https://www.ndtv.com/india-news/rafale-case-supreme-court-dismisses-petitions-against-its-order-rejecting-cbi-probe-into-fighter-jet-2132248'],
  },
  {
    id: 'hgh015',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Defence & Security',
    subtopic: 'Rafale deal',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2019,
    asOf: '2026-09',
    govt: 'NDA',
    question: "The CAG's Feb 2019 report compared the 36-jet Rafale deal with the price negotiated in 2007. How much cheaper did it find the new deal?",
    options: ['9%', '2.86%', '20%', '0.5%'],
    correctIndex: 1,
    explanation: "CAG found the NDA's deal 2.86% cheaper than the UPA-era 2007 price, but said Dassault's savings from not furnishing bank guarantees should have been passed on to the ministry. The Congress disputed the audit, alleging a conflict of interest because of the auditor's earlier role in the finance ministry.",
    sourceUrl: 'https://www.hindustantimes.com/india-news/rafale-jets-2-9-per-cent-cheaper-than-upa-era-deal-says-cag-report-tabled-in-parliament/story-EWfX9E4Q2N8IhgXriOH9vJ.html',
    sourceLabel: 'Hindustan Times — Rafale deal 2.9% cheaper than UPA-era deal, says CAG (13 Feb 2019)',
    sources: ['https://timesofindia.indiatimes.com/business/india-business/ndas-rafale-deal-2-86-cheaper-than-price-negotiated-by-upa-in-2007-cag/articleshow/67976690.cms'],
  },
  {
    id: 'hgh016',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Defence & Security',
    subtopic: 'Rafale deal',
    kind: 'scam',
    difficulty: 'simple',
    year: 2021,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In June 2021 a judicial investigation into suspected corruption in the 2016 Rafale sale to India was formally opened in which country?',
    options: ['France', 'India', 'Switzerland', 'United Arab Emirates'],
    correctIndex: 0,
    explanation: "France's national financial prosecutor's office (PNF) opened the probe on June 14, 2021 after Mediapart's reports; a judge was appointed to lead it. The Wire reported in Feb 2026 that the probe was still continuing. In India, the Supreme Court dismissed pleas for a probe in 2018 and 2019.",
    status: 'French judicial inquiry opened June 2021, reported ongoing (Feb 2026); Indian Supreme Court declined a probe (2018, 2019).',
    sourceUrl: 'https://www.freepressjournal.in/topnews/sale-of-rafale-aircraft-french-judge-opens-criminal-investigation-into-deal-with-india',
    sourceLabel: 'Free Press Journal — French judge opens criminal investigation into Rafale deal (3 Jul 2021)',
    sources: ['https://m.thewire.in/article/security/exclusive-as-india-looks-to-buy-114-rafales-french-prosectors-continue-probe-into-earlier-deal', 'https://www.france24.com/en/europe/20210702-french-judge-tasked-with-investigating-rafale-fighter-jet-sale-to-india'],
  },
  {
    id: 'hgh017',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Adani–Hindenburg',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In Jan 2024 the Supreme Court declined an SIT or CBI probe into Hindenburg’s Adani allegations. SEBI had then finished probes in how many of its 24 cases?',
    options: ['12', '4', '22', '18'],
    correctIndex: 2,
    explanation: "A bench led by CJI D.Y. Chandrachud found no ground to doubt SEBI, refused to rely on OCCRP and media reports, upheld SEBI's tightened rules, and gave it three months for the remaining two cases. The Adani Group has consistently denied Hindenburg's allegations.",
    status: 'Allegations by Hindenburg Research (Jan 2023); SC refused SIT (Jan 2024); SEBI closed key related-party proceedings (Sept 2025); group denies wrongdoing.',
    sourceUrl: 'https://www.livelaw.in/top-stories/supreme-court-adani-hindenburg-endorses-sebi-probe-regulations-245712',
    sourceLabel: 'LiveLaw — Supreme Court refuses SIT probe in Adani-Hindenburg case (3 Jan 2024)',
    sources: ['https://timesofindia.indiatimes.com/business/india-business/explained-why-supreme-court-did-not-order-cbi-or-sit-probe-into-adani-hindenburg-case/articleshow/106504163.cms'],
  },
  {
    id: 'hgh018',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Adani–Hindenburg',
    kind: 'scam',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: "In Sept 2025 SEBI passed final orders on Hindenburg's charge that the Adani Group routed undisclosed related-party deals via two firms. What did it find?",
    options: ['Violations proven; a ₹1,000-crore penalty imposed', 'Matter referred to the CBI for a criminal probe', 'Allegations not established; proceedings closed without penalty', 'Promoters barred from the market for five years'],
    correctIndex: 2,
    explanation: "SEBI's Sept 18, 2025 orders closed proceedings over Milestone Tradelinks and Rehvar Infrastructure, finding the related-party violations 'not established' and issuing no directions. Gautam Adani said SEBI had reaffirmed that the claims were baseless. Hindenburg, which also alleged tax-haven use, had shut down in Jan 2025.",
    status: 'Gautam Adani: not charged in India; SEBI closed these proceedings (Sept 2025); US criminal case dismissed (Aug 2026).',
    people: ['Gautam Adani'],
    sourceUrl: 'https://www.newindianexpress.com/business/2025/Sep/18/sebi-gives-clean-chit-to-adani-group-in-the-hindenburg-case',
    sourceLabel: 'The New Indian Express — SEBI gives clean chit to Adani Group in the Hindenburg case (18 Sep 2025)',
    sources: ['https://www.aljazeera.com/economy/2025/9/18/indian-regulators-dismiss-stock-manipulation-allegations-on-adani-group', 'https://www.outlookindia.com/national/us-court-dismisses-criminal-charges-against-gautam-adani'],
  },
  {
    id: 'hgh019',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Energy & Mining',
    subtopic: 'Adani US case',
    kind: 'scam',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'US prosecutors indicted Gautam Adani in Nov 2024 over an alleged solar-power bribery scheme. What happened to the criminal charges against him in Aug 2026?',
    options: ['A New York jury convicted him', 'They were transferred to an Indian court', "A US judge dismissed them with prejudice at the DOJ's request", 'He pleaded guilty and paid a fine'],
    correctIndex: 2,
    explanation: 'The indictment alleged bribes of about $265 million promised to Indian state officials; the group denied it. In May 2026 the DOJ moved to drop the case, calling it primarily foreign, and on Aug 10, 2026 Judge Garaufis dismissed the charges against the Adanis while questioning the process. Separately they settled SEC civil claims for $18 million.',
    status: 'Criminal charges dismissed with prejudice (10 Aug 2026); SEC civil case settled ($6m + $12m); allegations never tested at trial; group denies wrongdoing.',
    people: ['Gautam Adani', 'Sagar Adani'],
    sourceUrl: 'https://www.outlookindia.com/national/us-court-dismisses-criminal-charges-against-gautam-adani',
    sourceLabel: 'Outlook India — US court dismisses criminal charges against Gautam Adani (11 Aug 2026)',
    sources: ['https://www.businesstoday.in/world/us/story/us-judge-dismisses-bribery-case-against-gautam-adani-but-flags-concern-heres-what-the-case-was-about-548417-2026-08-11', 'https://www.barandbench.com/news/litigation/adani-case-was-a-name-and-shame-indictment-by-biden-administration-without-realistic-prospect-of-trial-us-doj-to-court'],
  },
  {
    id: 'hgh020',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Adani–Hindenburg',
    kind: 'scam',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'Hindenburg Research, whose Jan 2023 report set off a steep fall in Adani Group shares, announced what in January 2025?',
    options: ['It was shutting down the firm', 'A second report on Adani ports', 'A damages settlement with Adani', 'A move of its office to Mumbai'],
    correctIndex: 0,
    explanation: "Its founder announced the closure on Jan 15, 2025, calling it a planned step after finishing its pipeline of work. The Adani Group had rejected all of Hindenburg's accusations; SEBI later closed its related-party proceedings (Sept 2025).",
    status: 'Hindenburg allegations (Jan 2023) denied by the Adani Group; SEBI closed related-party proceedings (Sept 2025).',
    sourceUrl: 'https://timesofindia.indiatimes.com/business/india-business/why-did-hindenburg-research-short-seller-behind-adani-group-150-bn-rout-shut-down-read-full-text-of-founder-nate-andersons-personal-note/articleshow/117287676.cms',
    sourceLabel: 'Times of India — Why did Hindenburg Research shut down? (16 Jan 2025)',
    sources: ['https://frontline.thehindu.com/news/hindenburg-research-closure-nate-anderson-adani-group-short-seller-wall-street/article69134775.ece'],
  },
  {
    id: 'hgh021',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Adani–Hindenburg',
    kind: 'institution',
    difficulty: 'expert',
    year: 2023,
    asOf: '2026-09',
    govt: 'NDA',
    question: "What did the Supreme Court's expert committee on the Adani–Hindenburg matter say about SEBI in its May 2023 report?",
    options: ['It could not, for now, find a regulatory failure by SEBI', 'SEBI had colluded with the Adani Group', 'Adani stocks should be suspended pending probe', 'Hindenburg had broken Indian securities law'],
    correctIndex: 0,
    explanation: "The committee examined public-shareholding, related-party disclosure and price-manipulation questions and said it could not, at that stage, arrive at a finding of 'regulatory failure'. Petitioners contested this; in Jan 2024 the Supreme Court declined to order a separate probe and let SEBI finish its own.",
    sourceUrl: 'https://www.livelaw.in/top-stories/supreme-court-sc-adani-hindenburg-report-expert-committee-securities-and-exchange-board-of-india-sebi-regulatory-failure-229112',
    sourceLabel: "LiveLaw — Prima facie 'no regulatory failure', says SC expert committee (19 May 2023)",
    sources: ['https://www.thehindu.com/news/national/sebi-probe-into-adani-drew-blank-supreme-court-appointed-panel/article66869790.ece'],
  },
  {
    id: 'hgh022',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'Lokpal',
    kind: 'institution',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In May 2025 the Lokpal ruled on three complaints against former SEBI chief Madhabi Puri Buch based on Hindenburg’s claims. What did it decide?',
    options: ['Ordered a CBI inquiry into her investments', 'Referred them to the Supreme Court', "Disposed of them as resting on 'presumptions and assumptions'", 'Imposed a penalty and a bar on public office'],
    correctIndex: 2,
    explanation: "A full bench led by Justice A.M. Khanwilkar disposed of all three complaints on May 28, 2025, saying they were not backed by verifiable material and that a short-seller's report could not alone justify action. Buch had denied all the allegations.",
    status: 'Complaints disposed of by the Lokpal (May 2025); no case against her; she denied the allegations.',
    people: ['Madhabi Puri Buch'],
    sourceUrl: 'https://www.thehindu.com/news/national/lokpal-gives-clean-chit-to-madhabi-puri-buch-in-hindenburg-case/article69630578.ece',
    sourceLabel: 'The Hindu — Lokpal gives clean chit to Madhabi Puri Buch in Hindenburg case (28 May 2025)',
    sources: ['https://www.scconline.com/blog/post/2025/05/29/lokpal-gives-clean-chit-former-sebi-chairperson-madhabi-puri-buch-all-corruption-allegations/'],
  },
  {
    id: 'hgh023',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Education & Exams',
    subtopic: 'NEET-UG 2024',
    kind: 'scam',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In July 2024 the Supreme Court refused to cancel NEET-UG 2024 despite a proven paper leak. What was its main reason?',
    options: ['The CBI had found that no leak occurred', 'Results had already been declared final by law', 'No evidence the leak was systemic enough to taint the whole exam', 'A re-test needed a constitutional amendment'],
    correctIndex: 2,
    explanation: "On July 23, 2024 the Court held the leak, probed by the CBI in Hazaribagh and Patna, was not shown to be widespread, and a re-test would hurt lakhs of honest candidates; the CBI said the Hazaribagh leak reached 155 'beneficiaries'. In 2026 the NTA did cancel NEET-UG after a fresh leak allegation.",
    status: 'CBI investigated the 2024 leak; Supreme Court declined a re-test (July 2024).',
    sourceUrl: 'https://www.scobserver.in/journal/supreme-court-refuses-to-cancel-2024-neet-ug-exam-due-to-insufficient-evidence-of-systemic-leak/',
    sourceLabel: 'Supreme Court Observer — SC refuses to cancel NEET UG 2024 (23 Jul 2024)',
  },
  {
    id: 'hgh024',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Education & Exams',
    subtopic: 'NEET-UG 2026',
    kind: 'scam',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'What did the National Testing Agency do with the NEET-UG exam held on May 3, 2026, after allegations of a paper leak?',
    options: ['Cancelled results only in the affected states', 'Cancelled it and held a re-exam on June 21, 2026', 'Let results stand after a court order', 'Postponed all counselling to 2027'],
    correctIndex: 1,
    explanation: 'The NTA cancelled the exam on May 12, 2026 and the CBI is investigating. About 20 lakh candidates sat the re-test (22.05 lakh took the original), with a record 2.79 lakh absent; results came on July 16. Parliament then toughened the anti-leak law.',
    status: 'Exam cancelled by the NTA (12 May 2026); CBI investigation ongoing (Sept 2026).',
    sourceUrl: 'https://www.thehindu.com/news/national/neet-ug-over-27-lakh-candidates-skipped-re-test-highest-absentee-count-ever/article71234173.ece',
    sourceLabel: 'The Hindu — NEET UG 2026: over 2.7 lakh candidates skipped re-test (17 Jul 2026)',
    sources: ['https://www.thehindu.com/education/neet-ug-2026-retest-questions-papers-medical-entrance-examination-nta-iaf/article71076050.ece', 'https://prsindia.org/billtrack/the-public-examinations-prevention-of-unfair-means-amendment-bill-2026'],
  },
  {
    id: 'hgh025',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Education & Exams',
    subtopic: 'Anti-paper-leak law',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'After the NEET-UG 2026 cancellation, Parliament amended the 2024 anti-paper-leak law. What minimum fine does it now set for organised exam crime?',
    options: ['₹10 crore', '₹1 crore', '₹10 lakh', '₹50 lakh'],
    correctIndex: 0,
    explanation: "The Public Examinations (Prevention of Unfair Means) Amendment Bill, 2026, passed by both Houses by July 30, raises organised-crime penalties from 5–10 years and at least ₹1 crore to a minimum of 7 years and ₹10 crore, allows seizure of offenders' property, and asks states to set up fast-track courts.",
    sourceUrl: 'https://prsindia.org/billtrack/the-public-examinations-prevention-of-unfair-means-amendment-bill-2026',
    sourceLabel: 'PRS Legislative Research — Public Examinations Amendment Bill, 2026 (Jul 2026)',
    sources: ['https://newsonair.gov.in/parliament-passes-public-examinations-prevention-of-unfair-means-amendment-bill-2026/'],
  },
  {
    id: 'hgh026',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'Pegasus spyware',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDA',
    question: "The Supreme Court's Pegasus technical committee examined 29 phones. On how many did it find some malware, without proof it was Pegasus?",
    options: ['None', '29', '5', '14'],
    correctIndex: 2,
    explanation: "Reading the report on Aug 25, 2022, CJI N.V. Ramana said five of 29 phones had 'some malware' but that did not mean Pegasus. He added the report recorded that the Government of India 'was not cooperative' and had taken the same stand as in court. The report was kept in sealed cover.",
    status: 'SC committee found malware but no conclusive proof of Pegasus (Aug 2022); CJI said it recorded the Centre was “not cooperative”; report sealed.',
    sourceUrl: 'https://www.thehindu.com/news/national/of-29-phones-examined-five-infected-with-some-malware-but-does-not-mean-it-is-pegasus-spyware-panel-report-in-supreme-court/article65808941.ece',
    sourceLabel: 'The Hindu — Malware found in 5 phones, no proof of Pegasus: panel (25 Aug 2022)',
    sources: ['https://internetfreedom.in/pegasus-investigation-report-to-remain-in-sealed-cover-even-though-it-contains-evidence-that-5-phones-had-malware/'],
  },
  {
    id: 'hgh027',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'CBI and politicians',
    kind: 'institution',
    difficulty: 'expert',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDA',
    question: "An Indian Express probe (2022) found the Opposition's share of politicians in the CBI's net was about 60% under UPA. What was it under NDA-II?",
    options: ['About 70%', 'About 95%', 'About 80%', 'About 50%'],
    correctIndex: 1,
    explanation: 'Of 72 leaders probed by the CBI in 2004–14, 43 (60%) were from the Opposition; of 124 since 2014, 118 (95%). Under UPA, 29 of the 72 were from Congress or allies, in cases such as 2G, CWG and coal. The government says agencies act on evidence and that such cases are a tiny share of their work.',
    sourceUrl: 'https://indianexpress.com/article/express-exclusive/from-60-per-cent-in-upa-to-95-per-cent-in-nda-a-surge-in-share-of-opposition-leaders-in-cbi-net-express-investigation-8160912/',
    sourceLabel: 'The Indian Express — From 60% in UPA to 95% in NDA: Opposition leaders in CBI net (20 Sep 2022)',
    sources: ['https://indianexpress.com/article/india/ed-driven-by-legal-mandate-evidence-not-shifting-sands-of-politics-official-response-to-express-report-9252298/'],
  },
  {
    id: 'hgh028',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'ED and politicians',
    kind: 'institution',
    difficulty: 'simple',
    year: 2022,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'An Indian Express investigation (2022) found that of 121 prominent politicians probed by the ED since 2014, what share were from the Opposition?',
    options: ['54% (65 leaders)', '75% (91 leaders)', '30% (36 leaders)', '95% (115 leaders)'],
    correctIndex: 3,
    explanation: 'Under UPA (2004–14) only 26 politicians were probed by the ED, 14 (54%) from the Opposition. An ED official said the agency cannot register cases on its own—it acts on FIRs by police or other agencies—and also probes BJP politicians; the government strongly denies political bias.',
    sourceUrl: 'https://indianexpress.com/article/express-exclusive/since-2014-4-fold-jump-in-ed-cases-against-politicians-95-per-cent-are-from-opposition-8163060/',
    sourceLabel: 'The Indian Express — Since 2014, 4-fold jump in ED cases against politicians; 95% from Opposition (21 Sep 2022)',
  },
  {
    id: 'hgh029',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'ED and politicians',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question: "Rebutting the 'washing machine' charge in April 2024, a senior official said how many of about 6,260 PMLA cases involved MPs, MLAs and politically exposed persons?",
    options: ['149 (about 2.3%)', '1,200 (about 19%)', '3,100 (about 50%)', '12 (about 0.2%)'],
    correctIndex: 0,
    explanation: "The official said the ED is 'driven by legal mandates and evidence, not the shifting sands of political will'; those 149 cases led to attachments of nearly ₹29,000 crore and convictions of two ex-ministers. For the CBI, politicians were about 1% of 10,622 inquiries and cases in 11 years.",
    sourceUrl: 'https://indianexpress.com/article/india/ed-driven-by-legal-mandate-evidence-not-shifting-sands-of-politics-official-response-to-express-report-9252298/',
    sourceLabel: 'The Indian Express — ED driven by legal mandate, evidence: official responds (5 Apr 2024)',
  },
  {
    id: 'hgh030',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'Defections under probe',
    kind: 'institution',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'The Indian Express found (April 2024) that 25 Opposition politicians facing central probes had joined the BJP since 2014. How many then got a reprieve?',
    options: ['5', '12', '17', '23'],
    correctIndex: 3,
    explanation: "Three cases were closed and 20 stalled; in only two was there no let-up. Ten of the 25 came from the Congress. The Opposition calls this a 'washing machine'. A CBI official said probes are 'based on evidence' and remain open; an ED official said it cannot proceed once the base FIR is closed.",
    sourceUrl: 'https://indianexpress.com/article/express-exclusive/since-2014-25-opposition-leaders-facing-corruption-probe-crossed-over-to-bjp-23-of-them-got-reprieve-9247737/',
    sourceLabel: 'The Indian Express — 25 Opposition leaders facing probes crossed over to BJP, 23 got reprieve (3 Apr 2024)',
    sources: ['https://www.business-standard.com/politics/23-politicians-have-got-reprieve-in-corruption-cases-on-joining-bjp-report-124040300589_1.html'],
  },
  {
    id: 'hgh031',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'PMLA convictions',
    kind: 'institution',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In March 2025 the Finance Ministry told Rajya Sabha the ED had registered 193 cases against politicians in about ten years. How many ended in conviction?',
    options: ['47', '0', '119', '2'],
    correctIndex: 3,
    explanation: "MoS Pankaj Chaudhary said two cases ended in conviction (one each in 2016-17 and 2019-20) and none in acquittal on merits; cases peaked at 32 in 2022-23. He said the ED acts on 'credible evidence', does not distinguish by party, and is open to judicial review. Party-wise data is not kept.",
    sourceUrl: 'https://www.livelaw.in/top-stories/2-convictions-in-193-ed-cases-filed-against-political-leaders-in-last-10-years-centre-tells-parliament-286862',
    sourceLabel: 'LiveLaw — 2 convictions in 193 ED cases against political leaders (19 Mar 2025)',
    sources: ['https://www.deccanherald.com/india/193-politicians-faced-ed-cases-between-2015-16-and-2024-25-only-2-convictions-3452451'],
  },
  {
    id: 'hgh032',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'PMLA convictions',
    kind: 'institution',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'At its 70th anniversary in May 2026, what conviction rate did the ED claim in money-laundering trials that had been completed?',
    options: ['About 6%', 'About 50%', 'About 25%', 'About 94%'],
    correctIndex: 3,
    explanation: 'The ED said ~94% of completed trials ended in conviction (19 persons in FY26) and that it filed 657 main prosecution complaints that year. Critics note that few trials finish: the Supreme Court has flagged only about 40 convictions out of some 5,000 ED cases over ten years.',
    sourceUrl: 'https://www.newindianexpress.com/india/2026/May/01/ed-marks-70th-founding-anniversary-with-record-asset-attachments-of-rs-81422-in-fy-2025-26',
    sourceLabel: 'The New Indian Express — ED marks 70th anniversary with record attachments (1 May 2026)',
    sources: ['https://www.livelaw.in/top-stories/2-convictions-in-193-ed-cases-filed-against-political-leaders-in-last-10-years-centre-tells-parliament-286862'],
  },
  {
    id: 'hgh033',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'PMLA law',
    kind: 'institution',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: "Which 2022 Supreme Court ruling, upholding the ED's arrest, attachment and strict-bail powers under PMLA, went before a new review bench in Aug 2026?",
    options: ['Arnesh Kumar v State of Bihar', 'Vijay Madanlal Choudhary v Union of India', 'Lalita Kumari v Government of UP', 'Vineet Narain v Union of India'],
    correctIndex: 1,
    explanation: 'The July 2022 verdict underpins arrest without a prior police case, pre-FIR attachment, not giving the accused the ECIR, and the tough Section 45 bail test. In Aug 2026 a three-judge bench led by CJI Surya Kant was set to hear the review petitions; a date was yet to be fixed.',
    sourceUrl: 'https://www.hindustantimes.com/ht-explainers/supreme-court-pmla-review-petitions-new-bench-prevention-of-money-laundering-act-enforcement-directorate-2022-judgment-101787301820024.html',
    sourceLabel: 'Hindustan Times — Why the Supreme Court will take another look at its 2022 PMLA verdict (21 Aug 2026)',
    sources: ['https://www.livelaw.in/top-stories/supreme-court-pmla-review-bench-reconstituted-by-consent-justice-ujjal-bhuyan-nk-singh-replaced-by-justices-joymalya-bagchi-vmohana-546631'],
  },
  {
    id: 'hgh034',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'ED leadership',
    kind: 'institution',
    difficulty: 'expert',
    year: 2023,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In July 2023 the Supreme Court held the third extension given to the then ED director illegal. What did it do with the law allowing such extensions?',
    options: ['Struck the amendments down entirely', 'Referred the law to a five-judge bench', 'Upheld it, letting ED and CBI chiefs serve up to five years', 'Ordered a two-year cap on all tenures'],
    correctIndex: 2,
    explanation: "The Court said the extension broke its 2021 order barring further extensions, but let him stay till July 31, 2023 (later Sept 15) citing the FATF review. It upheld the CVC and DSPE Act amendments that let the Centre extend ED and CBI chiefs' terms to five years in the public interest.",
    sourceUrl: 'https://www.livelaw.in/top-stories/supreme-court-sc-enforcement-directorate-director-sanjay-kumar-mishra-central-vigilance-commission-amendment-act-232449',
    sourceLabel: "LiveLaw — Supreme Court invalidates extensions of ED Director's term (11 Jul 2023)",
    sources: ['https://www.thehindu.com/news/national/sc-allows-sanjay-kumar-mishra-to-continue-as-ed-director-till-september-15/article67127129.ece'],
  },
  {
    id: 'hgh035',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'CBI general consent',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2023,
    asOf: '2026-09',
    govt: 'NDA',
    question: "In December 2023 the Centre told Lok Sabha how many states had withdrawn 'general consent' for the CBI to investigate in their territory?",
    options: ['3', '17', '25', '10'],
    correctIndex: 3,
    explanation: 'Punjab, Jharkhand, Kerala, Rajasthan, Chhattisgarh, West Bengal, Mizoram, Telangana, Meghalaya and Tamil Nadu. Under Section 6 of the DSPE Act the CBI needs state consent; the Centre said it had no plan to amend it, while a parliamentary panel sought a new law letting the CBI act without consent. The list can change with state governments.',
    sourceUrl: 'https://thesouthfirst.com/pti/10-stateswithdraw-general-consent-to-cbi-to-investigate-cases-centre/',
    sourceLabel: 'The South First (PTI) — 10 states withdraw general consent to CBI: Centre (20 Dec 2023)',
  },
  {
    id: 'hgh036',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'CVC report',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: "The CVC's annual report (released Sept 2026) said how many CBI corruption cases under the PC Act were pending trial at the end of 2025?",
    options: ['1,208', '7,229', '22,540', '409'],
    correctIndex: 1,
    explanation: "Of these, 409 had been pending for over 20 years, and 14,083 appeals and revisions were pending in higher courts. The report put the CBI's conviction rate at 71.71% in 2025, up from 69.14% in 2024.",
    sourceUrl: 'https://www.thehindu.com/news/national/cbi-investigations-corruption-cases-pending-trials-central-vigilance-commission-report/article71415055.ece',
    sourceLabel: 'The Hindu — 7,229 CBI cases under PC Act pending trial; 409 for over 20 years (1 Sep 2026)',
    sources: ['https://theprint.in/india/over-7200-corruption-cases-probed-by-cbi-pending-trials-409-for-more-than-2-decades/3030812/'],
  },
  {
    id: 'hgh037',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'Lokpal',
    kind: 'institution',
    difficulty: 'expert',
    year: 2023,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In 2023 the Lokpal told a parliamentary panel how many people it had prosecuted for graft since it began work in 2019?',
    options: ['Not a single person', '12 people', '57 people', '3 people'],
    correctIndex: 0,
    explanation: "It had received 8,703 complaints since 2019-20; 6,775 were rejected for not being in the prescribed format, only three were fully investigated and about 68% were disposed of without action. It said it had 'not prosecuted even a single person accused of graft'.",
    sourceUrl: 'https://www.thehindu.com/news/national/lokpal-disposed-of-68-corruption-complaints-against-public-servants-without-any-action-parliamentary-panel-report/article66698721.ece',
    sourceLabel: 'The Hindu — Lokpal disposed of 68% complaints without any action: panel report (4 Apr 2023)',
    sources: ['https://theprint.in/judiciary/five-years-on-lokpal-is-now-god-of-small-things-its-been-catching-tiny-fish/2681750/'],
  },
  {
    id: 'hgh038',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'Lokpal',
    kind: 'spend',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In Oct 2025 India’s anti-graft ombudsman, the Lokpal, floated a tender that drew outrage and was cancelled weeks later. What was it for?',
    options: ['A new ₹200-crore headquarters', 'Seven BMW cars for its chair and members', 'Foreign study tours for members', 'Hiring private jets for travel'],
    correctIndex: 1,
    explanation: "The Oct 16, 2025 tender sought seven BMW 3 Series 330Li cars (about ₹60 lakh each before taxes; over ₹4 crore in all). After criticism from Opposition parties and civil society, a full-bench decision of Nov 27 led to its cancellation, recorded on the e-procurement site as 'administrative reasons'.",
    sourceUrl: 'https://www.hindustantimes.com/india-news/lokpal-withdraws-tender-for-7-bmw-cars-after-furore-101767293477449.html',
    sourceLabel: 'Hindustan Times — Lokpal withdraws tender for 7 BMW cars after furore (2 Jan 2026)',
    sources: ['https://m.thewire.in/article/government/after-facing-criticism-lokpal-cancels-its-tender-to-procure-seven-bmw-cars-worth-rs-70-lakh-each'],
  },
  {
    id: 'hgh039',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'Lokpal',
    kind: 'institution',
    difficulty: 'expert',
    year: 2019,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'The Lokpal and Lokayuktas Act was notified in January 2014. When was India’s first Lokpal chairperson appointed?',
    options: ['March 2014', 'January 2017', 'March 2019', 'November 2021'],
    correctIndex: 2,
    explanation: 'A retired Supreme Court judge was appointed on March 19, 2019, nearly five years after the Act (passed in 2013 after a nationwide anti-corruption movement) was notified. The government moved after the Supreme Court set a February-end deadline; the selection panel was chaired by the Prime Minister.',
    sourceUrl: 'https://www.thehindu.com/news/national/justice-pc-ghose-appointed-first-lokpal/article26582874.ece',
    sourceLabel: 'The Hindu — Justice P.C. Ghose appointed first Lokpal (19 Mar 2019)',
    sources: ['https://lawstreet.co/executive/former-supreme-court-judge-justice-pinaki-chandra-ghose-to-be-first-lokpal-chairperson'],
  },
  {
    id: 'hgh040',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Bank fraud data',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: "RBI's 2025-26 annual report put the amount involved in bank frauds reported in FY26 at about how much?",
    options: ['₹4,802 crore', '₹48,021 crore', '₹1.48 lakh crore', '₹12,230 crore'],
    correctIndex: 1,
    explanation: "Up 46% from ₹32,803 crore, even as cases fell to 10,114 from 23,722. ₹30,199 crore came from 314 older cases re-reported after the Supreme Court's March 2023 ruling on hearing borrowers. Card and digital fraud fell to ₹29 crore. RBI notes frauds reported in a year may have happened years earlier.",
    sourceUrl: 'https://indianexpress.com/article/business/bank-frauds-amount-rises-46-pc-to-rs-48000-crore-in-fy26-rbi-annual-report-10713875/',
    sourceLabel: 'The Indian Express — Bank frauds amount rises 46% to Rs 48,000 crore in FY26 (29 May 2026)',
    sources: ['https://www.thehindu.com/business/Economy/financial-institutions-report-over-10000-cases-of-fraud-involving-48000-crore-in-fy26-rbi-data/article71036689.ece'],
  },
  {
    id: 'hgh041',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Bank fraud rules',
    kind: 'institution',
    difficulty: 'expert',
    year: 2023,
    asOf: '2026-09',
    govt: 'NDA',
    question: "In March 2023 the Supreme Court said banks must do what before classifying a borrower's account as 'fraud' under RBI's directions?",
    options: ['Give the borrower a hearing and a reasoned order', 'Get a CBI FIR registered first', "Obtain the RBI governor's approval", 'Wait for a court conviction'],
    correctIndex: 0,
    explanation: "A bench led by CJI D.Y. Chandrachud read the audi alteram partem rule into RBI's master directions, since a fraud tag amounts to blacklisting with serious civil and criminal consequences. Banks then re-examined older cases: 122 worth ₹18,674 crore were re-reported in FY25 and 314 worth ₹30,199 crore in FY26.",
    sourceUrl: 'https://www.livelaw.in/top-stories/breaking-banks-must-give-opportunity-of-hearing-to-borrowers-before-classifying-their-accounts-as-fraud-supreme-court-224828',
    sourceLabel: 'LiveLaw — Banks must hear borrowers before classifying accounts as fraud: SC (27 Mar 2023)',
    sources: ['https://indianexpress.com/article/business/bank-fraud-amount-jumps-by-three-times-to-rs-36014-crore-in-fy25-rbi-10036075/'],
  },
  {
    id: 'hgh042',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Wilful defaulters',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'The Finance Minister told Lok Sabha (March 2026) that dues of wilful defaulters rose from ₹39,369 crore in March 2014 to how much by March 2025?',
    options: ['₹83,000 crore', '₹12.4 lakh crore', '₹1.2 lakh crore', '₹3.83 lakh crore'],
    correctIndex: 3,
    explanation: 'Per CIBIL data (borrowers owing ₹25 lakh and above), wilful defaulters rose from 5,076 to 18,318; dues were ₹1.94 lakh crore by March 2019. ABG Shipyard topped the ten largest at ₹6,695 crore, followed by Gitanjali Gems at ₹6,237 crore.',
    status: 'Wilful-defaulter status is a lender classification under RBI rules, not a court verdict; recovery and criminal cases proceed separately.',
    sourceUrl: 'https://www.moneylife.in/article/from-39369-crore-to-383264-crore-in-10-years-indias-wilful-default-crisis-laid-bare-in-parliament-abg-shipyard-leads-at-6695-crore/79963.html',
    sourceLabel: "Moneylife — India's wilful default crisis laid bare in Parliament (17 Mar 2026)",
    sources: ['https://www.thehindu.com/business/ten-biggest-wilful-defaulters-owe-40825-cr-to-banks/article67147485.ece'],
  },
  {
    id: 'hgh043',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'ED asset attachments',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'The Enforcement Directorate reported its highest-ever single-year asset attachments under PMLA in 2025-26. About how much were they worth?',
    options: ['₹81,422 crore', '₹8,142 crore', '₹3.1 lakh crore', '₹19,500 crore'],
    correctIndex: 0,
    explanation: 'The FY26 figure was 171% up on ₹30,036 crore the year before, and cumulative attachments since PMLA took effect in 2005 crossed ₹2.36 lakh crore. The ED said restitution to victims such as banks and homebuyers reached ₹32,678 crore in FY26. Attachment is not forfeiture, and critics note that few PMLA trials conclude.',
    sourceUrl: 'https://www.newindianexpress.com/india/2026/May/01/ed-marks-70th-founding-anniversary-with-record-asset-attachments-of-rs-81422-in-fy-2025-26',
    sourceLabel: 'The New Indian Express — ED marks 70th anniversary with record asset attachments (1 May 2026)',
    sources: ['https://telanganatoday.com/ed-raids-and-asset-attachments-hit-record-high-in-fy26', 'https://www.livelaw.in/top-stories/2-convictions-in-193-ed-cases-filed-against-political-leaders-in-last-10-years-centre-tells-parliament-286862'],
  },
  {
    id: 'hgh044',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Sahara refunds',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'By Feb 2026, how much had been paid to Sahara co-operative depositors through the CRCS-Sahara Refund Portal set up in 2023?',
    options: ['₹138 crore', '₹24,000 crore', '₹8,783.55 crore', '₹50,000 crore'],
    correctIndex: 2,
    explanation: 'The Cooperation Minister told Lok Sabha the money reached 40.33 lakh investors, up to ₹50,000 each, in Aadhaar-seeded accounts under Supreme Court orders; 1.45 crore applications had been filed. The Court allowed another ₹5,000 crore from the Sahara-SEBI refund account and extended payouts to Dec 31, 2026.',
    sourceUrl: 'https://m.economictimes.com/news/india/sahara-refund-rs-8800-crore-disbursed-to-40-lakh-depositors-amit-shah-parliament/articleshow/129633126.cms',
    sourceLabel: 'Economic Times — Rs 8,800 crore refunded to over 40 lakh Sahara depositors (17 Mar 2026)',
    sources: ['https://www.business-standard.com/india-news/amit-shah-says-6-842-cr-refunded-to-3-544-million-sahara-group-depositors-125120200878_1.html'],
  },
  {
    id: 'hgh045',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Defence & Security',
    subtopic: 'AgustaWestland',
    kind: 'scam',
    difficulty: 'simple',
    year: 2010,
    asOf: '2026-09',
    govt: 'UPA',
    question: 'The AgustaWestland case concerns a 2010 order, worth about ₹3,600 crore, that India placed to buy what?',
    options: ['36 fighter jets', '56 transport aircraft', '12 VVIP helicopters', 'Six Scorpene submarines'],
    correctIndex: 2,
    explanation: 'After bribery allegations India cancelled the contract and blacklisted parent Finmeccanica (now Leonardo); the ban was lifted in 2021. The CBI and ED allege a middleman channelled bribes to officials and politicians to secure it. As of Feb 2026 charges had not been framed; the alleged middleman denies all charges.',
    status: 'CBI/ED cases pending; charges not framed as of Feb 2026; the alleged middleman denies all charges.',
    sourceUrl: 'https://m.thewire.in/article/news/jail-for-christian-michel-joint-venture-for-adani-revives-agustawestland-ghosts',
    sourceLabel: 'The Wire — Jail for Christian Michel, joint venture for Adani revives AgustaWestland ghosts (17 Feb 2026)',
    sources: ['https://indianexpress.com/article/legal-news/agustawestland-case-delhi-hc-christian-michel-james-jail-10625012/'],
  },
  {
    id: 'hgh046',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Defence & Security',
    subtopic: 'AgustaWestland',
    kind: 'scam',
    difficulty: 'simple',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'Christian Michel James, alleged middleman in the AgustaWestland helicopter case, was extradited to India in December 2018 from which country?',
    options: ['United Arab Emirates', 'United Kingdom', 'Italy', 'Switzerland'],
    correctIndex: 0,
    explanation: "He was sent from Dubai under the India-UAE treaty. Arguing he had already served over seven years—the maximum for the offences he was extradited for—he sought release; the Delhi HC dismissed his plea in April 2026 and the Supreme Court sought the Centre's reply (July 2026). He denies all charges.",
    status: 'In judicial custody since Dec 2018; charges not framed (Feb 2026); release plea pending before the SC (July 2026); denies all charges.',
    people: ['Christian Michel James'],
    sourceUrl: 'https://indialegallive.com/constitutional-law-news/courts-news/agustawestland-case-supreme-court-grants-centre-three-weeks-to-respond-to-christian-michel-plea/',
    sourceLabel: 'India Legal — SC grants Centre three weeks to respond to Christian Michel plea (24 Jul 2026)',
    sources: ['https://indianexpress.com/article/legal-news/agustawestland-case-delhi-hc-christian-michel-james-jail-10625012/', 'https://m.thewire.in/article/news/jail-for-christian-michel-joint-venture-for-adani-revives-agustawestland-ghosts'],
  },
  {
    id: 'hgh047',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Energy & Mining',
    subtopic: '2G spectrum case',
    kind: 'scam',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: "A special court acquitted ex-telecom minister A. Raja and others in the 2G case in Dec 2017. What was the status of the CBI's appeal in early 2026?",
    options: ['Dismissed by the Supreme Court in 2019', 'Withdrawn by the CBI in 2020', 'Allowed in 2025, reversing the acquittals', 'Pending in the Delhi High Court, admitted in 2024'],
    correctIndex: 3,
    explanation: "In March 2024 the Delhi HC granted the CBI leave to appeal, citing 'contradictions' in the trial verdict; Hindustan Times reported in Feb 2026 that the matter had been pending in the HC for over eight years. Raja, DMK MP Kanimozhi and the others stand acquitted unless the HC rules otherwise.",
    status: 'Acquitted by the trial court (Dec 2017); CBI appeal pending in the Delhi High Court (Feb 2026).',
    people: ['A. Raja', 'Kanimozhi'],
    sourceUrl: 'https://www.hindustantimes.com/cities/delhi-news/kejriwal-acquittal-challenge-may-spark-2g-case-back-into-life-101772216259674.html',
    sourceLabel: 'Hindustan Times — Kejriwal acquittal: challenge may spark 2G case back into life (28 Feb 2026)',
    sources: ['https://www.business-standard.com/india-news/delhi-hc-admits-cbi-s-appeal-challenging-acquittals-in-2g-scam-case-124032200870_1.html'],
  },
  {
    id: 'hgh048',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Energy & Mining',
    subtopic: '2G spectrum case',
    kind: 'scam',
    difficulty: 'simple',
    year: 2010,
    asOf: '2026-09',
    govt: 'UPA',
    question: "In 2010 the CAG estimated a notional ('presumptive') loss to the exchequer from the 2G spectrum allocation of about how much?",
    options: ['₹30,000 crore', '₹17,600 crore', '₹1.76 lakh crore', '₹7.6 lakh crore'],
    correctIndex: 2,
    explanation: "The figure led telecom minister A. Raja to resign in 2010; the CBI later alleged a smaller loss of ₹30,984 crore, and the Supreme Court cancelled 122 licences in 2012. But the trial court acquitted all accused in Dec 2017; the CBI's appeal is pending in the Delhi High Court.",
    status: 'Accused acquitted by the trial court (Dec 2017); CBI appeal pending (Feb 2026).',
    people: ['A. Raja'],
    sourceUrl: 'https://www.hindustantimes.com/cities/delhi-news/kejriwal-acquittal-challenge-may-spark-2g-case-back-into-life-101772216259674.html',
    sourceLabel: 'Hindustan Times — Kejriwal acquittal: challenge may spark 2G case back into life (28 Feb 2026)',
    sources: ['https://www.business-standard.com/india-news/delhi-hc-admits-cbi-s-appeal-challenging-acquittals-in-2g-scam-case-124032200870_1.html'],
  },
  {
    id: 'hgh049',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Energy & Mining',
    subtopic: 'Coal block allocation',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2014,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In Sept 2014 the Supreme Court quashed coal block allocations made since 1993 as illegal and arbitrary. How many of the 218 blocks did it cancel?',
    options: ['214', '46', '118', '72'],
    correctIndex: 0,
    explanation: 'Only four were spared. The Court also levied ₹295 per tonne on coal already mined from the cancelled blocks. The criminal cases that followed have had mixed results: five convictions so far, with sentences stayed by the Delhi HC, and several acquittals in 2025–26.',
    status: 'Allocations quashed by SC (Sept 2014); CBI coal cases: some convictions under appeal, several acquittals (Mar 2026).',
    sourceUrl: 'https://www.livelaw.in/supreme-court-quashes-214-coal-blocks-allocation-since-1993-levies-penalty-rs-295-per-metric-ton-coal-extracted',
    sourceLabel: 'LiveLaw — Supreme Court quashes 214 coal blocks allocated since 1993 (24 Sep 2014)',
    sources: ['https://indianexpress.com/article/legal-news/former-coal-secy-h-c-gupta-ex-mp-vijay-darda-acquitted-coal-block-scam-case-10604218/'],
  },
  {
    id: 'hgh050',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Energy & Mining',
    subtopic: 'Coal block allocation',
    kind: 'scam',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'Former coal secretary H.C. Gupta has faced several coal-block trials. What was his overall record as of March 2026?',
    options: ['Acquitted in every case', 'Convicted in some cases, acquitted or discharged in others', 'Convicted in all cases and serving time', 'Never charged; only a witness'],
    correctIndex: 1,
    explanation: "He was convicted in cases including Kamal Sponge and Vini Iron, with appeals pending in the Delhi HC; he was discharged in Mednirai (April 2025), acquitted in Mahugarhi (June 2025) and 'honourably acquitted' in Bander (March 2026), where the judge called the allocation a policy decision taken per the PMO's instructions.",
    status: 'Convicted in some coal cases (appeals pending in Delhi HC); acquitted or discharged in others (Mar 2026).',
    people: ['H.C. Gupta'],
    sourceUrl: 'https://m.thewire.in/article/government/bander-coal-block-acquittal-hard-questions-prosecuting-bureaucrats-committee-decisions',
    sourceLabel: 'The Wire — Coal block acquittal raises hard questions about prosecuting bureaucrats (28 Mar 2026)',
    sources: ['https://indianexpress.com/article/legal-news/former-coal-secy-h-c-gupta-ex-mp-vijay-darda-acquitted-coal-block-scam-case-10604218/'],
  },
  {
    id: 'hgh051',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'Commonwealth Games 2010',
    kind: 'scam',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: "What happened in April 2025 to the Enforcement Directorate's money-laundering case linked to the 2010 Commonwealth Games in Delhi?",
    options: ['The organisers were convicted and jailed', "A Delhi court accepted the ED's closure report", 'The Supreme Court transferred it to the CBI', 'It was merged with the 2G case'],
    correctIndex: 1,
    explanation: "The court accepted the ED's closure report in the case against organising-committee chief Suresh Kalmadi, then secretary general Lalit Bhanot and others, ending a probe of over a decade without a trial. Kalmadi, a former Union minister and Congress leader, died on Jan 6, 2026.",
    status: 'ED money-laundering case closed by court (Apr 2025); no conviction; Kalmadi died Jan 2026.',
    people: ['Suresh Kalmadi', 'Lalit Bhanot'],
    sourceUrl: 'https://www.thehindu.com/news/national/court-accepts-eds-closure-report-in-2010-cwg-case-against-suresh-kalmadi-others/article69502708.ece',
    sourceLabel: "The Hindu — Court accepts ED's closure report in 2010 CWG case (29 Apr 2025)",
    sources: ['https://www.thehindu.com/news/national/former-union-minister-and-congress-leader-suresh-kalmadi-passes-away/article70476649.ece', 'https://theprint.in/judiciary/15-years-after-cwg-scam-why-a-delhi-court-accepted-eds-closure-report-against-suresh-kalmadi/2608812/'],
  },
  {
    id: 'hgh052',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Media & Speech',
    subtopic: 'National Herald case',
    kind: 'scam',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: "In Dec 2025 a Delhi trial court refused to take cognisance of the ED's National Herald complaint against Sonia and Rahul Gandhi. On what ground?",
    options: ['The ED had missed the limitation period', 'Lok Sabha had not sanctioned prosecution', 'The accused had repaid the loan in full', 'There was no FIR; the case began as a private complaint'],
    correctIndex: 3,
    explanation: "The court held the money-laundering case was 'not maintainable' because it rested on BJP leader Subramanian Swamy's private complaint, not an FIR. The ED's challenge is in the Delhi HC; the Gandhis call it an 'abuse of the process of law'. The next hearing was listed for Oct 12, 2026.",
    status: "Trial court refused cognisance of ED complaint (16 Dec 2025); ED's revision pending in Delhi HC (Sept 2026); no charges framed; accused contest the case.",
    people: ['Sonia Gandhi', 'Rahul Gandhi', 'Subramanian Swamy'],
    sourceUrl: 'https://www.newindianexpress.com/india/2026/Sep/22/sonia-rahul-term-eds-plea-in-delhi-hc-on-national-herald-case-an-abuse-of-process-of-law',
    sourceLabel: "The New Indian Express — Sonia, Rahul term ED's plea in National Herald case an 'abuse of process' (22 Sep 2026)",
    sources: ['https://www.thehindu.com/news/cities/Delhi/national-herald-case-delhi-high-court-grants-three-weeks-to-sonia-gandhi-rahul-gandhi-to-respond-to-ed-plea/article71272423.ece'],
  },
  {
    id: 'hgh053',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'INX Media case',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2019,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'Former Union finance minister P. Chidambaram was taken into custody in August 2019 in the INX Media case. How many days passed before he walked out on bail?',
    options: ['16', '365', '106', '45'],
    correctIndex: 2,
    explanation: 'Released on Dec 4, 2019 after Supreme Court bail, he said not one charge had been framed. In Feb 2026 the ED sought a speedy trial in the INX Media and Aircel-Maxis money-laundering cases after filing the prosecution sanction. He and his son Karti deny wrongdoing and call the cases a political witch hunt.',
    status: 'Accused in CBI/ED cases (INX Media, Aircel-Maxis); on bail since Dec 2019; trial not begun (Feb 2026); denies charges.',
    people: ['P. Chidambaram', 'Karti Chidambaram'],
    sourceUrl: 'https://www.thenewsminute.com/news/no-charge-framed-against-me-p-chidambaram-he-walks-out-tihar-113506',
    sourceLabel: 'The News Minute — No charge framed against me: P Chidambaram walks out of Tihar (5 Dec 2019)',
    sources: ['https://www.rediff.com/news/report/ed-seeks-trial-against-chidambaram-in-pmla-cases/20260226.htm'],
  },
  {
    id: 'hgh054',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Sterling Biotech case',
    kind: 'scam',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: "In April 2026 the Supreme Court closed the criminal cases against Sterling Biotech's promoters, who had left India in 2017. On what basis?",
    options: ['A settlement: they paid about ₹5,111 crore to lenders', 'A trial court acquitted them on all counts', 'The CBI filed a closure report', 'A pardon under Article 72'],
    correctIndex: 0,
    explanation: "After Nitin and Chetan Sandesara paid ₹5,111.43 crore and settled the rest, the Court held further proceedings would serve no purpose and quashed them; the CBI's FIR had cited ₹5,383 crore. They had been declared fugitive economic offenders and never stood trial. SEBI was also told to close its proceedings.",
    status: 'Criminal proceedings quashed by the Supreme Court after settlement (Apr 2026); no conviction.',
    people: ['Nitin Sandesara', 'Chetan Sandesara'],
    sourceUrl: 'https://www.indiatoday.in/india/story/supreme-court-closes-sandesara-brothers-fraud-case-rs-5000-crore-settlement-2896293-2026-04-14',
    sourceLabel: 'India Today — Supreme Court closes Sandesara fraud case after settlement (14 Apr 2026)',
    sources: ['https://dailypioneer.com/news/sc-tells-sebi-to-close-sandesara-brothers-case'],
  },
  {
    id: 'hgh055',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'Anil Ambani group probe',
    kind: 'scam',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In Feb 2026 the Supreme Court, hearing a PIL on alleged siphoning of about ₹40,000 crore at the Anil Ambani group, asked which agency to form an SIT?',
    options: ['Enforcement Directorate', 'SEBI', 'Serious Fraud Investigation Office', 'Reserve Bank of India'],
    correctIndex: 0,
    explanation: "The bench led by CJI Surya Kant flagged 'unexplained delay' by the ED and faulted the CBI for merging different banks' complaints into one FIR. In Sept 2026 the CBI registered another FIR on LIC's complaint alleging a ₹2,684-crore loss. Anil Ambani's spokesperson denies any wrongdoing; no court has found guilt.",
    status: 'Named in CBI FIRs and ED probes (2025–26); no court finding of guilt; denies wrongdoing (Sept 2026).',
    people: ['Anil Ambani'],
    sourceUrl: 'https://www.verdictum.in/court-updates/supreme-court/40000-crore-anil-ambani-group-fraud-case-cbi-reliance-enforcement-directorate-1606496',
    sourceLabel: "Verdictum — SC criticises ED for 'unexplained delay' in Anil Ambani group case (4 Feb 2026)",
    sources: ['https://lawchakra.in/latest-news/cbi-fir-reliance-capital-anil-ambani-lic-2684-crore-wrongful-loss/'],
  },
  {
    id: 'hgh056',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Defence & Security',
    subtopic: 'Sanjay Bhandari case',
    kind: 'scam',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'Why did the UK High Court in Feb 2025 discharge defence consultant Sanjay Bhandari from an order to extradite him to India?',
    options: ['India had missed a treaty deadline', 'He had become a British citizen', 'Human-rights grounds: risk of ill-treatment in custody', 'The charges were not crimes in the UK'],
    correctIndex: 2,
    explanation: "India was refused leave to appeal to the UK Supreme Court in April 2025. A Delhi court then declared him a fugitive economic offender in the ED's case (July 2025), upheld by the Delhi HC in April 2026, allowing his assets to be confiscated. His counsel argued he lives lawfully in the UK.",
    status: 'Accused in ED/Income Tax cases; declared FEO (upheld Apr 2026); UK refused extradition; not tried.',
    people: ['Sanjay Bhandari'],
    sourceUrl: 'https://www.thehindu.com/news/international/uk-court-refuses-india-permission-to-appeal-sanjay-bhandari-extradition-discharge/article69426673.ece',
    sourceLabel: 'The Hindu — UK court refuses India permission to appeal Bhandari extradition discharge (8 Apr 2025)',
    sources: ['https://www.newindianexpress.com/cities/delhi/2026/Apr/10/delhi-high-court-rejects-sanjay-bhandaris-plea-upholds-fugitive-economic-offender-tag', 'https://www.newsonair.gov.in/nirav-modi-faces-setback-as-uk-high-court-rejects-plea-to-reopen-extradition-case'],
  },
  {
    id: 'hgh057',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Governance & Institutions',
    subtopic: 'Lalit Modi',
    kind: 'scam',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In March 2025, which country’s prime minister ordered cancellation of the passport it had recently issued to former IPL chief Lalit Modi?',
    options: ['Fiji', 'Malta', 'Antigua and Barbuda', 'Vanuatu'],
    correctIndex: 3,
    explanation: "Vanuatu's PM acted days after India's MEA confirmed Modi had applied to surrender his Indian passport. The PM also noted Interpol had twice rejected India's requests for an alert notice on Modi for lack of 'substantive judicial evidence'. Modi challenged the cancellation in a Vanuatu court.",
    status: 'Wanted by Indian agencies over financial allegations; no conviction; Interpol declined India’s alert requests (Mar 2025).',
    people: ['Lalit Modi'],
    sourceUrl: 'https://www.thehindu.com/news/international/vanuatu-pm-cancel-passport-issued-to-lalit-modi-interpol-alert/article69312139.ece',
    sourceLabel: "The Hindu — Vanuatu PM orders cancellation of Lalit Modi's passport (10 Mar 2025)",
    sources: ['https://www.bbc.com/news/articles/ckg813zy096o', 'https://timesofindia.indiatimes.com/india/lalit-modi-moves-vanuatu-court-against-his-passport-cancellation/articleshow/118909754.cms'],
  },
  {
    id: 'hgh058',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Infrastructure',
    subtopic: 'IL&FS collapse',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2018,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In Oct 2018 the Centre moved the NCLT to supersede the board of defaulting infrastructure lender IL&FS. About how much debt was the group carrying?',
    options: ['₹9,100 crore', '₹91,000 crore', '₹4.5 lakh crore', '₹25,000 crore'],
    correctIndex: 1,
    explanation: 'IL&FS, whose shareholders included LIC, had about ₹91,000 crore of debt, raising fears of a credit crisis. By June 30, 2026 the new board reported a resolution value of ₹57,556 crore against a ₹61,000-crore target, with 205 of 302 group entities resolved.',
    sourceUrl: 'https://m.economictimes.com/industry/banking/finance/banking/everything-about-the-ilfs-crisis-that-has-india-in-panic-mode/articleshow/66026024.cms',
    sourceLabel: 'Economic Times — IL&FS: the crisis that has India in panic mode (1 Oct 2018)',
    sources: ['https://www.cnbctv18.com/business/companies/ilfs-resolution-value-crosses-rs57500-crore-as-debt-discharged-tops-rs50000-crore-19949625.htm'],
  },
  {
    id: 'hgh059',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'PACL investor refunds',
    kind: 'scam',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: 'In March 2026 the ED restored assets worth over ₹15,000 crore to the SC-appointed Lodha committee for investors in which alleged Ponzi scheme?',
    options: ['Saradha Group', 'PACL (Pearls Group)', 'Rose Valley', 'Sahara India'],
    correctIndex: 1,
    explanation: "A PMLA court ordered 455 properties (about ₹15,582 crore) restituted; the alleged fraud is put at about ₹48,000 crore. The CBI case was filed in 2014 on the Supreme Court's direction, and the Court set up the Lodha panel in 2016 to sell assets and refund investors. Promoter Nirmal Singh Bhangoo died in Aug 2024.",
    status: 'CBI/ED cases (from 2014); promoter died Aug 2024; ED restitution ordered (Mar 2026).',
    people: ['Nirmal Singh Bhangoo'],
    sourceUrl: 'https://www.outlookmoney.com/news/ed-restitutes-rs-15000-crore-worth-assets-in-pacl-fraud-case',
    sourceLabel: "Outlook Money (PTI) — ED restitutes Rs 15,000-crore worth assets in PACL 'fraud' case (31 Mar 2026)",
    sources: ['https://m.economictimes.com/news/india/ed-restitutes-rs-15000-crore-worth-assets-in-pacl-fraud-case/articleshow/129906988.cms'],
  },
  {
    id: 'hgh060',
    domain: 'civics',
    region: 'India',
    state: 'IN',
    topic: 'Banking & Finance',
    subtopic: 'NSE co-location case',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2026,
    asOf: '2026-09',
    govt: 'NDA',
    question: "To settle its long-running co-location and dark-fibre cases, how much did the National Stock Exchange pay under SEBI's consent mechanism?",
    options: ['₹149 crore', '₹14,910 crore', '₹625 crore', '₹1,491 crore'],
    correctIndex: 3,
    explanation: "The cases concerned claims that some brokers got faster access to NSE's trading data. SEBI cleared the settlement in July 2026 and in Sept 2026 the Supreme Court allowed it and disposed of the pending proceedings, removing a hurdle to NSE's IPO.",
    status: 'Settled with SEBI via consent mechanism (July 2026); SC disposed of proceedings (Sept 2026).',
    sourceUrl: 'https://www.newindianexpress.com/india/2026/Sep/18/sc-allows-nse-and-sebi-to-settle-co-location-dispute-nse-pays-rs-1491-crore-under-sebis-consent-mechanism',
    sourceLabel: 'The New Indian Express — SC allows NSE and SEBI to settle co-location dispute (18 Sep 2026)',
    sources: ['https://www.moneycontrol.com/news/business/markets/sebi-agrees-to-settle-nse-co-location-dark-fibre-cases-for-rs-1491-crore-issues-demand-letter-13989376.html'],
  },
]);
