// HISAAB DO — Schemes & benefits lane (hsc001–hsc060).
// Contract: docs/hisaab/CHARTER.md §2–§5 and editions/hisaab/bank/schema.mjs.
// Research notes, sources and stale-risk list: docs/hisaab/research/schemes-notes.md.
// Every figure was read on the item's sourceUrl in Sept 2026 (asOf). No item names a person.

export const HISAAB_SCHEMES = Object.freeze([
  {
    id: "hsc001",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PM-KISAN",
    kind: "scheme",
    difficulty: "simple",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "Under PM-KISAN, launched in February 2019, how much does an eligible landholding farmer family get from the Centre each year?",
    options: ["₹12,000, in four instalments", "₹6,000, in three instalments", "₹4,000, in two instalments", "₹10,000, in one instalment"],
    correctIndex: 1,
    explanation: "PM-KISAN pays ₹6,000 a year in three equal instalments straight into Aadhaar-seeded bank accounts by DBT. The Agriculture Ministry said in Feb 2025 that over ₹3.46 lakh crore had been paid in 18 instalments since launch.",
    sourceUrl: "https://pib.gov.in/PressReleasePage.aspx?PRID=2100758",
    sourceLabel: "PIB (Agriculture Ministry) — Assessment of impact of PM-KISAN (7 Feb 2025)",
    tags: ["distribution"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister (launched PM-KISAN at Gorakhpur, 24 Feb 2019)", party: "BJP" }],
    outcome:
      "Announced in the Interim Budget of 1 Feb 2019, it paid its first ₹2,000 instalment to 1.01 crore farmers on 24 Feb 2019, 46 days before Lok Sabha polling began. By Feb 2025 over ₹3.46 lakh crore had been paid in 18 instalments (PIB).",
  },
  {
    id: "hsc002",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PM-KISAN",
    kind: "scheme",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "Widening PM-KISAN to all landholding farmers in May 2019, the Cabinet projected about 14.5 crore beneficiaries. How many got the 18th instalment, per the ministry in Feb 2025?",
    options: ["About 13.8 crore", "About 11.2 crore", "About 6.2 crore", "About 9.59 crore"],
    correctIndex: 3,
    explanation: "The May 2019 Cabinet note projected ~14.5 crore beneficiaries and ₹87,217.50 crore for 2019-20. In Feb 2025 the ministry said 9.59 crore farmers got the 18th instalment, after land-record, Aadhaar-payment and e-KYC checks, and a 2024 saturation drive that added over 25 lakh eligible farmers.",
    sourceUrl: "https://pib.gov.in/PressReleasePage.aspx?PRID=2100758",
    sourceLabel: "PIB (Agriculture Ministry) — Assessment of impact of PM-KISAN (7 Feb 2025)",
    sources: ["https://www.pmindia.gov.in/en/news_updates/pm-kisan-scheme-extension-to-include-all-eligible-farmer-families-irrespective-of-the-size-of-land-holdings/"],
    tags: ["distribution"],
  },
  {
    id: "hsc003",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PM-KISAN",
    kind: "scheme",
    difficulty: "expert",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "In July 2021 the Agriculture Ministry told the Lok Sabha that PM-KISAN money had reached about 42 lakh ineligible people. Roughly how much had they been paid?",
    options: ["About ₹300 crore", "About ₹3,000 crore", "About ₹30,000 crore", "About ₹900 crore"],
    correctIndex: 1,
    explanation: "A written Lok Sabha reply put it at ₹2,992.75 crore paid to 42,16,643 ineligible people (such as income-tax payers), with the largest numbers in Assam, Tamil Nadu and Punjab. The government said it was recovering the money.",
    sourceUrl: "https://www.tribuneindia.com/news/nation/govt-deposited-rs-3-000-cr-under-pm-kisan-scheme-in-accounts-of-over-42-lakh-ineligible-persons-285908/amp",
    sourceLabel: "The Tribune — Govt deposited Rs 3,000 cr under PM-KISAN in accounts of over 42 lakh ineligible persons (21 Jul 2021)",
    tags: ["distribution"],
  },
  {
    id: "hsc004",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PM-KISAN",
    kind: "scheme",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "By March 2025, how much had the Centre recovered from ineligible PM-KISAN beneficiaries since the scheme began, per its written reply in the Lok Sabha?",
    options: ["About ₹416 crore", "About ₹41 crore", "About ₹4,160 crore", "About ₹1,250 crore"],
    correctIndex: 0,
    explanation: "The Agriculture Minister told the Lok Sabha (25 Mar 2025) that ₹416 crore had been recovered, against over ₹3.68 lakh crore paid in 19 instalments. He said the scheme began on states' self-certified lists, and later added PFMS, UIDAI and income-tax data checks to block ineligible payouts.",
    sourceUrl: "https://www.outlookbusiness.com/news/govt-recovers-rs-416-crore-from-ineligible-farmers-so-far-under-pm-kisan-agri-min",
    sourceLabel: "Outlook Business (PTI) — Govt recovers Rs 416 crore from ineligible farmers under PM-KISAN (25 Mar 2025)",
    sources: ["https://www.tribuneindia.com/news/nation/govt-deposited-rs-3-000-cr-under-pm-kisan-scheme-in-accounts-of-over-42-lakh-ineligible-persons-285908/amp"],
    tags: ["distribution"],
  },
  {
    id: "hsc005",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "Ayushman Bharat PM-JAY",
    kind: "scheme",
    difficulty: "simple",
    year: 2018,
    asOf: "2026-09",
    govt: "NDA",
    question: "Ayushman Bharat PM-JAY, launched in 2018, gives free hospital insurance of up to how much, on a family basis?",
    options: ["₹1 lakh", "₹5 lakh", "₹10 lakh", "₹30,000"],
    correctIndex: 1,
    explanation: "PM-JAY gives up to ₹5 lakh of free hospital cover on a family basis. It is run by the National Health Authority at the Union level and by state health authorities and district units in the states.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-health-coverage-to-all-senior-citizens-of-the-age-70-years-and-above-irrespective-of-income-under-ayushman-bharat-pradhan-mantri-jan-arogya-yojana-ab-pm-jay/",
    sourceLabel: "PMO — Cabinet approves health coverage to all senior citizens aged 70+ under AB PM-JAY (11 Sep 2024)",
    sources: ["https://medicaldialogues.in/news/health/dead-patients-getting-treatment-cag-audit-report-flags-errors-in-pmjay-scheme-health-ministry-issues-clarification-115777"],
    tags: ["distribution"],
  },
  {
    id: "hsc006",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "Ayushman Bharat PM-JAY",
    kind: "scheme",
    difficulty: "simple",
    year: 2024,
    asOf: "2026-09",
    govt: "NDA",
    question: "In September 2024 the Cabinet opened Ayushman Bharat PM-JAY to every senior citizen above what age, irrespective of income?",
    options: ["60 years", "65 years", "75 years", "70 years"],
    correctIndex: 3,
    explanation: "The 11 Sept 2024 decision covers all citizens aged 70 and above regardless of socio-economic status, aiming at about 4.5 crore families and 6 crore senior citizens with ₹5 lakh free cover on a family basis.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-health-coverage-to-all-senior-citizens-of-the-age-70-years-and-above-irrespective-of-income-under-ayushman-bharat-pradhan-mantri-jan-arogya-yojana-ab-pm-jay/",
    sourceLabel: "PMO — Cabinet approves health coverage to all senior citizens aged 70+ under AB PM-JAY (11 Sep 2024)",
    tags: ["distribution"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister (chaired the Union Cabinet that approved it)", party: "BJP" }],
  },
  {
    id: "hsc007",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "Ayushman Bharat PM-JAY",
    kind: "scheme",
    difficulty: "expert",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "CAG's 2023 audit of Ayushman Bharat PM-JAY found up to how many beneficiaries registered against one same-or-invalid mobile number?",
    options: ["About 7,500", "About 75,000", "About 7.5 lakh", "About 75 lakh"],
    correctIndex: 2,
    explanation: "CAG Report No. 11 of 2023 found registrations ranging from 11 to 7,49,820 beneficiaries against the same or an invalid number (such as 9999999999). The Health Ministry replied that mobile numbers play no role in eligibility, which is fixed by the beneficiary database and Aadhaar e-KYC, and are used only to contact patients.",
    sourceUrl: "https://cag.gov.in/uploads/download_audit_report/2023/04_Executive-Summary-064d22bab3b3f45.25634714.pdf",
    sourceLabel: "CAG — Performance Audit of AB-PMJAY, Report No. 11 of 2023, Executive Summary (Aug 2023)",
    sources: ["https://medicaldialogues.in/news/health/dead-patients-getting-treatment-cag-audit-report-flags-errors-in-pmjay-scheme-health-ministry-issues-clarification-115777"],
    tags: ["distribution"],
  },
  {
    id: "hsc008",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "Ayushman Bharat PM-JAY",
    kind: "scheme",
    difficulty: "extreme",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "CAG's 2023 PM-JAY audit found claims paid for treating patients the system had earlier recorded as 'died'. How much went to hospitals in those 3,903 claims?",
    options: ["₹6.97 lakh", "₹69.7 crore", "₹697 crore", "₹6.97 crore"],
    correctIndex: 3,
    explanation: "CAG found 88,760 patients died during treatment, yet 2,14,923 later claims were shown as paid against them; 3,903 claims worth ₹6.97 crore for 3,446 patients were actually paid. The Health Ministry called media reports of this misleading, saying hospitals may seek pre-authorisation up to three days before admission, so some patients died after a request was raised.",
    sourceUrl: "https://cag.gov.in/uploads/download_audit_report/2023/Report-No.-11-of-2023_PA-on-PMJAY_English-PDF-A-064d22bab2b83b5.38721048.pdf",
    sourceLabel: "CAG — Performance Audit of AB-PMJAY, Report No. 11 of 2023, para 5.8.2.8 (Aug 2023)",
    sources: ["https://www.business-standard.com/india-news/examining-recommendations-of-cag-audit-report-on-ab-pm-jay-health-ministry-123081800138_1.html"],
    tags: ["distribution"],
  },
  {
    id: "hsc009",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PM Ujjwala Yojana",
    kind: "scheme",
    difficulty: "simple",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "Ujjwala, the 2016 scheme giving deposit-free LPG connections to poor households, reached its 8-crore target in September 2019. How did that compare with its deadline?",
    options: ["Exactly on the deadline", "One year late", "Seven months early", "Two years late"],
    correctIndex: 2,
    explanation: "The PMO announced on 7 Sept 2019 that the 8 crore target was met seven months ahead of the March 2020 deadline. The target had been raised from 5 crore to 8 crore connections.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/ujjwala-yojana-achieves-target-of-8-crore-lpg-connections-7-months-ahead-of-target-date/",
    sourceLabel: "PMO — Ujjwala Yojana achieves target of 8 crore LPG connections 7 months ahead of target date (7 Sep 2019)",
    sources: ["https://cag.gov.in/uploads/download_audit_report/2019/Executive_Summary_of_Report_No_14_of_2019_Performance_Audit_of_Pradhan_Mantri_Ujjwala_Yojana_Ministry_of_Petroleum_and_Natural_Gas_0.pdf"],
    tags: ["distribution"],
  },
  {
    id: "hsc010",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PM Ujjwala Yojana",
    kind: "scheme",
    difficulty: "expert",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "CAG's 2019 Ujjwala audit worked out how many LPG refills a year, on average, beneficiaries with over a year's connection bought (to March 2018)?",
    options: ["3.66 refills", "7.20 refills", "9.80 refills", "12 refills"],
    correctIndex: 0,
    explanation: "For 1.93 crore such beneficiaries the average was 3.66 refills a year, falling to 3.21 by Dec 2018. CAG called sustained LPG use \"a big challenge\" and urged that nil- and low-consumption beneficiaries be encouraged to keep refilling.",
    sourceUrl: "https://cag.gov.in/uploads/download_audit_report/2019/Executive_Summary_of_Report_No_14_of_2019_Performance_Audit_of_Pradhan_Mantri_Ujjwala_Yojana_Ministry_of_Petroleum_and_Natural_Gas_0.pdf",
    sourceLabel: "CAG — Performance Audit of PMUY, Report No. 14 of 2019, Executive Summary (Dec 2019)",
    tags: ["distribution"],
  },
  {
    id: "hsc011",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PM Ujjwala Yojana",
    kind: "scheme",
    difficulty: "extreme",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "CAG flagged a risk that Ujjwala cylinders were diverted to commercial use. How many BPL beneficiaries were averaging more than 12 cylinders a year?",
    options: ["About 1.98 lakh", "About 19.8 lakh", "About 1.98 crore", "About 19,800"],
    correctIndex: 0,
    explanation: "CAG Report No. 14 of 2019 found 1.98 lakh beneficiaries above 12 cylinders a year — \"improbable\" for BPL households — and 13.96 lakh who took 3 to 41 refills in a single month. It asked oil companies to review high-consumption cases regularly.",
    sourceUrl: "https://cag.gov.in/uploads/download_audit_report/2019/Executive_Summary_of_Report_No_14_of_2019_Performance_Audit_of_Pradhan_Mantri_Ujjwala_Yojana_Ministry_of_Petroleum_and_Natural_Gas_0.pdf",
    sourceLabel: "CAG — Performance Audit of PMUY, Report No. 14 of 2019, Executive Summary (Dec 2019)",
    tags: ["distribution"],
  },
  {
    id: "hsc012",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PM Ujjwala Yojana",
    kind: "scheme",
    difficulty: "extreme",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "Per CAG, all-India LPG coverage stood at 61.9% in May 2016 as Ujjwala began. What had it reached by April 2019?",
    options: ["72.4%", "81.0%", "94.3%", "99.8%"],
    correctIndex: 2,
    explanation: "CAG recorded coverage rising to 94.3%, with 7.19 crore Ujjwala connections issued by March 2019 — a real gain — while flagging weak de-duplication, connections to minors and low refill rates.",
    sourceUrl: "https://cag.gov.in/uploads/download_audit_report/2019/Executive_Summary_of_Report_No_14_of_2019_Performance_Audit_of_Pradhan_Mantri_Ujjwala_Yojana_Ministry_of_Petroleum_and_Natural_Gas_0.pdf",
    sourceLabel: "CAG — Performance Audit of PMUY, Report No. 14 of 2019, Executive Summary (Dec 2019)",
    tags: ["distribution"],
  },
  {
    id: "hsc013",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PM Ujjwala Yojana",
    kind: "scheme",
    difficulty: "expert",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "In September 2023 the Cabinet approved 75 lakh more Ujjwala LPG connections over three years. What total number of beneficiaries would that take the scheme to?",
    options: ["8 crore", "12.5 crore", "15.2 crore", "10.35 crore"],
    correctIndex: 3,
    explanation: "The 13 Sept 2023 decision added 75 lakh connections to be released over three years, taking PMUY beneficiaries to 10.35 crore.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-expansion-of-ujjwala-yojana/",
    sourceLabel: "PMO — Cabinet approves expansion of Ujjwala Yojana (13 Sep 2023)",
    tags: ["distribution"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister (chaired the Union Cabinet that approved it)", party: "BJP" }],
  },
  {
    id: "hsc014",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "Beti Bachao Beti Padhao",
    kind: "spend",
    difficulty: "expert",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "A parliamentary committee reported in Dec 2021 what share of Beti Bachao Beti Padhao funds released in 2016–2019 went on media advocacy alone?",
    options: ["About 25%", "About 50%", "About 79%", "About 10%"],
    correctIndex: 2,
    explanation: "The Committee on Empowerment of Women found 78.91% of ₹446.72 crore released in 2016–19 went to media advocacy, and urged a shift to measurable outcomes in girls' education and health. It also credited that advocacy with drawing political attention to valuing the girl child.",
    sourceUrl: "https://www.thequint.com/news/india/beti-bachao-beti-padhao-80-funds-spent-on-ads-says-parliamentary-committee",
    sourceLabel: "The Quint — Beti Bachao Beti Padhao: 80% funds spent on ads, says parliamentary committee (Dec 2021)",
  },
  {
    id: "hsc015",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "Beti Bachao Beti Padhao",
    kind: "spend",
    difficulty: "extreme",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "Of ₹622.48 crore in Beti Bachao Beti Padhao money given to states up to 2019-20, what share had they actually spent, per a 2021 parliamentary committee?",
    options: ["About 50%", "About 25%", "About 75%", "About 95%"],
    correctIndex: 1,
    explanation: "The Committee on Empowerment of Women found states spent only 25.13% of the ₹622.48 crore they received, out of ₹848 crore allocated from 2014-15 to 2019-20 — which it called poor utilisation.",
    sourceUrl: "https://www.thequint.com/news/india/beti-bachao-beti-padhao-80-funds-spent-on-ads-says-parliamentary-committee",
    sourceLabel: "The Quint — Beti Bachao Beti Padhao: 80% funds spent on ads, says parliamentary committee (Dec 2021)",
  },
  {
    id: "hsc016",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "PMKVY / Skill India",
    kind: "scheme",
    difficulty: "expert",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "CAG's 2025 audit of the skilling scheme PMKVY found bank details blank, zero or 'N/A' for what share of 95.9 lakh participants in PMKVY 2.0 and 3.0?",
    options: ["About 12%", "About 94.5%", "About 38%", "About 61%"],
    correctIndex: 1,
    explanation: "CAG Report No. 20 of 2025 found 90,66,264 of 95,90,801 records (94.53%) empty or invalid, plus entries like '11111111111'. The ministry replied that the field was made non-mandatory after ground-level problems and that pay-outs were meant to go to Aadhaar-seeded accounts.",
    sourceUrl: "https://cag.gov.in/uploads/download_audit_report/2025/Report-No.-20-of-2025_PA-PMKVY_English-PDF-A-06943abec463479.68516873.pdf",
    sourceLabel: "CAG — Performance Audit of PMKVY, Report No. 20 of 2025, para 2.4.2.2 (Dec 2025)",
    sources: ["https://theprint.in/india/education/only-41-placed-age-education-ignored-cag-flags-gaps-in-modi-govts-flagship-upskilling-scheme/2812644/"],
  },
  {
    id: "hsc017",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "PMKVY / Skill India",
    kind: "scheme",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "Per CAG's 2025 PMKVY audit, what share of the 56.14 lakh candidates certified under short-term training and special projects were placed in jobs?",
    options: ["About 17%", "About 63%", "About 88%", "About 41%"],
    correctIndex: 3,
    explanation: "CAG found 23.18 lakh of 56.14 lakh certified candidates (41%) placed. In Kerala, training partners had submitted incorrect placement proof; after audit flagged it, the state recovered ₹22.33 lakh and blacklisted the agency.",
    sourceUrl: "https://cag.gov.in/uploads/PressRelease/PR-Press-Brief-Report-No-20-of-2025-English-06944f390e59d02-19424340.pdf",
    sourceLabel: "CAG — Press brief on Report No. 20 of 2025 (PMKVY) (Dec 2025)",
    sources: ["https://cag.gov.in/uploads/download_audit_report/2025/Report-No.-20-of-2025_PA-PMKVY_English-PDF-A-06943abec463479.68516873.pdf"],
  },
  {
    id: "hsc018",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "UDAN regional flights",
    kind: "scheme",
    difficulty: "extreme",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "CAG's 2023 audit of UDAN found how many of 774 routes awarded up to UDAN-3 kept flying beyond the three-year subsidised period (as of March 2023)?",
    options: ["112 routes", "371 routes", "403 routes", "54 routes"],
    correctIndex: 3,
    explanation: "403 routes (52%) never started; of 371 that did, only 112 finished the three-year concession, and just 54 (7% of those awarded) continued after it. The scheme has continued in later rounds (version 5.2 by July 2023).",
    sourceUrl: "https://factly.in/review-cag-highlights-certain-gaps-in-the-implementation-of-the-rcs-udan-scheme/",
    sourceLabel: "Factly — Review: CAG highlights gaps in implementation of RCS-UDAN (Aug 2023)",
  },
  {
    id: "hsc019",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PMGKAY free grain",
    kind: "scheme",
    difficulty: "simple",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "In November 2023 the Cabinet extended free foodgrain under PMGKAY for five years from January 2024. About how many people does it cover?",
    options: ["About 40 crore", "About 81 crore", "About 20 crore", "About 120 crore"],
    correctIndex: 1,
    explanation: "The Centre will give free grain to about 81.35 crore beneficiaries for five years from 1 Jan 2024 at an estimated ₹11.80 lakh crore — which PIB called among the world's largest food security schemes.",
    sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1980686",
    sourceLabel: "PIB (Cabinet) — Free foodgrains for 81.35 crore beneficiaries for five years (29 Nov 2023)",
    tags: ["distribution"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister (led the Cabinet that extended free grain)", party: "BJP" }],
  },
  {
    id: "hsc020",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PMGKAY free grain",
    kind: "scheme",
    difficulty: "simple",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "How much free grain does a poorest-of-the-poor Antyodaya household get each month under the food security entitlement now delivered via PMGKAY?",
    options: ["5 kg", "15 kg", "50 kg", "35 kg"],
    correctIndex: 3,
    explanation: "Antyodaya families are entitled to 35 kg a month. PIB put the economic cost of 35 kg of rice at ₹1,371 (wheat ₹946), borne by the Centre since the grain became free.",
    sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1980686",
    sourceLabel: "PIB (Cabinet) — Free foodgrains for 81.35 crore beneficiaries for five years (29 Nov 2023)",
    tags: ["distribution"],
  },
  {
    id: "hsc021",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "National Food Security Act",
    kind: "scheme",
    difficulty: "expert",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "PMGKAY's free grain is delivered \"as per entitlement\" under which law, passed in 2013?",
    options: ["National Food Security Act", "Essential Commodities Act", "Right to Food Act", "Public Distribution Act"],
    correctIndex: 0,
    explanation: "The National Food Security Act, 2013, passed under the UPA government, sets the entitlements. The NDA government's PMGKAY, begun in 2020 during Covid, now provides those NFSA entitlements free to 81.35 crore people.",
    sourceUrl: "https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=1990696",
    sourceLabel: "PIB (Food & Public Distribution) — Year-End Review 2023 (27 Dec 2023)",
    sources: ["https://en.wikipedia.org/wiki/National_Food_Security_Act,_2013", "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1980686", "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-extension-of-pradhan-mantri-garib-kalyan-anna-yojana-allocation-of-additional-foodgrain-for-further-five-months-from-july-to-november-2020/"],
    tags: ["distribution"],
  },
  {
    id: "hsc022",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "One Nation One Ration Card",
    kind: "scheme",
    difficulty: "simple",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "What does 'One Nation One Ration Card' let a food-security beneficiary do?",
    options: ["Take cash instead of grain each month", "Collect ration at any fair price shop in India", "Buy subsidised grain only online", "Add relatives from other states to the card"],
    correctIndex: 1,
    explanation: "Under ONORC any NFSA beneficiary can take grain from any fair price shop at the same entitlement and price. PIB said 28 crore portability transactions moved over 80 lakh tonnes in 2023 (to November), and 99.8% of shops used ePoS machines.",
    sourceUrl: "https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=1990696",
    sourceLabel: "PIB (Food & Public Distribution) — Year-End Review 2023 (27 Dec 2023)",
    tags: ["distribution"],
  },
  {
    id: "hsc023",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "PM Jan Dhan Yojana",
    kind: "scheme",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "By August 2025 PM Jan Dhan Yojana had 56.16 crore accounts. What share of account holders were women?",
    options: ["38.2%", "46.1%", "66.7%", "55.7%"],
    correctIndex: 3,
    explanation: "As of 13 Aug 2025, 55.7% (31.31 crore) of holders were women and 66.7% of accounts were in rural or semi-urban areas, with ₹2.68 lakh crore in deposits. PIB said banks were contacting holders to reduce inoperative accounts.",
    sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2161401",
    sourceLabel: "PIB (Finance Ministry) — PMJDY completes 11 years (Aug 2025)",
    tags: ["distribution"],
  },
  {
    id: "hsc024",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "PM Jan Dhan Yojana",
    kind: "scheme",
    difficulty: "simple",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "Every PM Jan Dhan account comes with a free RuPay debit card. What does that card carry?",
    options: ["Life insurance of ₹10 lakh", "A ₹5,000 joining bonus", "Unlimited free ATM withdrawals", "Accident insurance of ₹2 lakh"],
    correctIndex: 3,
    explanation: "PMJDY accounts are zero-balance with no maintenance charge; the RuPay card has built-in accident cover of ₹2 lakh, and holders can get an overdraft of up to ₹10,000. At least four free withdrawals a month are allowed; banks may charge beyond that.",
    sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2161401",
    sourceLabel: "PIB (Finance Ministry) — PMJDY completes 11 years (Aug 2025)",
    tags: ["distribution"],
  },
  {
    id: "hsc025",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PMAY-Gramin",
    kind: "scheme",
    difficulty: "expert",
    year: 2024,
    asOf: "2026-09",
    govt: "NDA",
    question: "PMAY-Gramin, launched in 2016, aimed to build 2.95 crore rural houses by March 2024. How many were still incomplete at that deadline?",
    options: ["About 3.5 lakh", "About 35 lakh", "About 1.2 crore", "None; the target was met"],
    correctIndex: 1,
    explanation: "The Cabinet noted on 9 Aug 2024 that 35 lakh houses were not completed by 31 Mar 2024 and would be finished in 2024-25. It also approved 2 crore more houses for 2024–29 with a total outlay of ₹3,06,137 crore.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-implementation-of-the-pradhan-mantri-awaas-yojana-gramin-pmay-g-during-fy-2024-25-to-2028-29/",
    sourceLabel: "PMO — Cabinet approves PMAY-G during FY 2024-25 to 2028-29 (9 Aug 2024)",
    tags: ["distribution"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister (chaired the Union Cabinet that approved it)", party: "BJP" }],
  },
  {
    id: "hsc026",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PMAY-Gramin",
    kind: "spend",
    difficulty: "extreme",
    year: 2024,
    asOf: "2026-09",
    govt: "NDA",
    question: "What is the unit assistance to build one PMAY-Gramin house in the plains, kept unchanged for 2024–29?",
    options: ["₹2.50 lakh", "₹70,000", "₹1.20 lakh", "₹1.80 lakh"],
    correctIndex: 2,
    explanation: "Assistance stays at ₹1.20 lakh in plain areas and ₹1.30 lakh in north-eastern and hill states/UTs such as Himachal Pradesh, Uttarakhand, J&K and Ladakh; the Centre shares the cost with states.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-implementation-of-the-pradhan-mantri-awaas-yojana-gramin-pmay-g-during-fy-2024-25-to-2028-29/",
    sourceLabel: "PMO — Cabinet approves PMAY-G during FY 2024-25 to 2028-29 (9 Aug 2024)",
    tags: ["distribution"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister (chaired the Union Cabinet that approved it)", party: "BJP" }],
  },
  {
    id: "hsc027",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PMAY-Urban",
    kind: "scheme",
    difficulty: "expert",
    year: 2022,
    asOf: "2026-09",
    govt: "NDA",
    question: "PMAY-Urban's 'Housing for All' mission was due to end in 2022. In August 2022 the Cabinet extended it to December 2024 to finish about how many sanctioned houses?",
    options: ["About 1.23 crore", "About 12 lakh", "About 3 crore", "About 50 lakh"],
    correctIndex: 0,
    explanation: "The 10 Aug 2022 decision extended PMAY-U so that 122.69 lakh houses sanctioned by 31 Mar 2022 could be completed, after states sought more time. The same note said 8.04 lakh urban houses were completed under the earlier scheme in 2004–2014.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-continuation-of-pradhan-mantri-awas-yojana-urban-pmay-u-housing-for-all-mission-up-to-31st-december-2024/",
    sourceLabel: "PMO — Cabinet approves continuation of PMAY-U up to 31 Dec 2024 (10 Aug 2022)",
    tags: ["distribution"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister (chaired the Union Cabinet that approved it)", party: "BJP" }],
  },
  {
    id: "hsc028",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "PMAY-Urban 2.0",
    kind: "spend",
    difficulty: "extreme",
    year: 2024,
    asOf: "2026-09",
    govt: "NDA",
    question: "PMAY-Urban 2.0, approved in August 2024, aims at 1 crore homes for urban poor and middle-class families. How much government subsidy was earmarked?",
    options: ["₹10 lakh crore", "₹2.30 lakh crore", "₹75,000 crore", "₹5.5 lakh crore"],
    correctIndex: 1,
    explanation: "The 9 Aug 2024 Cabinet decision set government subsidy at ₹2.30 lakh crore within a total investment of ₹10 lakh crore for 1 crore houses.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-pradhan-mantri-awas-yojana-urban-2-0-scheme/",
    sourceLabel: "PMO — Cabinet approves PMAY-Urban 2.0 (9 Aug 2024)",
    tags: ["distribution"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister (chaired the Union Cabinet that approved it)", party: "BJP" }],
  },
  {
    id: "hsc029",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "Jal Jeevan Mission",
    kind: "scheme",
    difficulty: "simple",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "When Jal Jeevan Mission began in 2019, roughly what share of rural households had a tap water connection?",
    options: ["About 17%", "About 45%", "About 60%", "About 5%"],
    correctIndex: 0,
    explanation: "Only 3.23 crore (17%) rural households had tap connections in 2019; by March 2026 states reported about 15.80 crore of 19.36 crore (81.61%). These are state-reported connections; the restructured JJM 2.0 shifts focus from building pipes to service delivery.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-extension-of-jal-jeevan-mission-jjm-period-up-to-december-2028-with-enhanced-outlay-and-restructured-implementation-focusing-on-structural-reforms-in-rural-drinking-water-supply-sec/",
    sourceLabel: "PMO — Cabinet approves extension of Jal Jeevan Mission up to Dec 2028 (10 Mar 2026)",
  },
  {
    id: "hsc030",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "Jal Jeevan Mission",
    kind: "spend",
    difficulty: "extreme",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "In March 2026 the Cabinet extended Jal Jeevan Mission to December 2028. What total outlay did it approve?",
    options: ["₹3.59 lakh crore", "₹8.69 lakh crore", "₹2.08 lakh crore", "₹12.4 lakh crore"],
    correctIndex: 1,
    explanation: "The 10 Mar 2026 decision raised total outlay to ₹8.69 lakh crore, with central assistance up from ₹2.08 lakh crore (approved 2019-20) to ₹3.59 lakh crore, and set a \"Sujalam Bharat\" digital framework for village water services.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-extension-of-jal-jeevan-mission-jjm-period-up-to-december-2028-with-enhanced-outlay-and-restructured-implementation-focusing-on-structural-reforms-in-rural-drinking-water-supply-sec/",
    sourceLabel: "PMO — Cabinet approves extension of Jal Jeevan Mission up to Dec 2028 (10 Mar 2026)",
  },
  {
    id: "hsc031",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "Jal Jeevan Mission complaints",
    kind: "scam",
    difficulty: "expert",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "In Dec 2025 the Jal Shakti Ministry told Parliament of 17,036 complaints of financial irregularities and poor work under Jal Jeevan Mission. Which state reported about 84% of them?",
    options: ["Rajasthan", "Madhya Pradesh", "Uttar Pradesh", "Bihar"],
    correctIndex: 2,
    explanation: "Uttar Pradesh reported about 84%. It said it enquired into all 14,264 complaints it received, took action in 434 cases involving 171 officials, 120 contractors and 143 inspection agencies, and found the rest addressed or irrelevant.",
    status: "Complaints and administrative action as reported by states in a ministry reply to Parliament (Dec 2025); no court finding is implied.",
    sourceUrl: "https://www.lokmattimes.com/national/17036-complaints-related-to-jal-mission-received-across-states-ministry/",
    sourceLabel: "Lokmat Times (IANS) — 17,036 complaints related to Jal Mission received across states: Ministry (1 Dec 2025)",
  },
  {
    id: "hsc032",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "Swachh Bharat Mission",
    kind: "scheme",
    difficulty: "expert",
    year: 2018,
    asOf: "2026-09",
    govt: "NDA",
    question: "Sanitation dashboards showed rural toilet coverage heading to 100%. What share of rural households reported latrine access in the NSO's July–Dec 2018 survey?",
    options: ["About 71%", "About 96%", "About 41%", "About 55%"],
    correctIndex: 0,
    explanation: "NSS 76th round found 71.3% of rural and 96.2% of urban households had latrine access. The statistics ministry noted possible respondent bias, since a question on government benefits came first. The sanitation department's data put rural coverage at 100% in 2019-20.",
    sourceUrl: "https://pib.gov.in/Pressreleaseshare.aspx?PRID=1593252",
    sourceLabel: "PIB (MoSPI) — NSS Report 584: Drinking Water, Sanitation, Hygiene and Housing, 76th round (Nov 2019)",
    sources: ["https://prsindia.org/theprsblog/seven-years-of-swachh-bharat-mission"],
  },
  {
    id: "hsc033",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "Swachh Bharat Mission",
    kind: "institution",
    difficulty: "expert",
    year: 2018,
    asOf: "2026-09",
    govt: "NDA",
    question: "In 2018, which parliamentary standing committee warned that Swachh Bharat was counting non-functional toilets, inflating the data?",
    options: ["Rural Development", "Health and Family Welfare", "Urban Development", "Water Resources"],
    correctIndex: 0,
    explanation: "The Standing Committee on Rural Development said a village with 100% household toilets cannot be called open-defecation free until everyone uses them, and questioned construction quality. The 15th Finance Commission (2020) also found open defecation persisted despite toilet access.",
    sourceUrl: "https://prsindia.org/theprsblog/seven-years-of-swachh-bharat-mission",
    sourceLabel: "PRS Legislative Research — Seven years of Swachh Bharat Mission (Oct 2021)",
  },
  {
    id: "hsc034",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "Swachh Bharat Mission-Urban",
    kind: "scheme",
    difficulty: "extreme",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "Swachh Bharat Mission–Urban first aimed for 66 lakh household toilets by 2 October 2019. What was that target revised to in 2019?",
    options: ["80 lakh", "1 crore", "45 lakh", "59 lakh"],
    correctIndex: 3,
    explanation: "The target was cut to 59 lakh individual household latrines in 2019, and the revised target was achieved by 2020, according to PRS citing government data.",
    sourceUrl: "https://prsindia.org/theprsblog/seven-years-of-swachh-bharat-mission",
    sourceLabel: "PRS Legislative Research — Seven years of Swachh Bharat Mission (Oct 2021)",
  },
  {
    id: "hsc035",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "Nirmal Bharat Abhiyan",
    kind: "scheme",
    difficulty: "expert",
    year: 2012,
    asOf: "2026-09",
    govt: "UPA",
    question: "Before Swachh Bharat (2014), the UPA government's rural sanitation scheme, a 2012 revamp of the Total Sanitation Campaign, was called what?",
    options: ["Swajal Dhara", "Rajiv Swachhta Mission", "Jal Nirmal Yojana", "Nirmal Bharat Abhiyan"],
    correctIndex: 3,
    explanation: "In 2012 the Total Sanitation Campaign was revamped as Nirmal Bharat Abhiyan with higher toilet incentives; rural toilet access had risen only from 22% (2001) to 32.7% (2011). Swachh Bharat Mission was launched on 2 Oct 2014.",
    sourceUrl: "https://prsindia.org/theprsblog/seven-years-of-swachh-bharat-mission",
    sourceLabel: "PRS Legislative Research — Seven years of Swachh Bharat Mission (Oct 2021)",
    sources: ["https://en.wikipedia.org/wiki/Swachh_Bharat_Mission"],
  },
  {
    id: "hsc036",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "VB-G RAM G Act",
    kind: "scheme",
    difficulty: "simple",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "From 1 July 2026 MGNREGA was replaced by the VB-G RAM G Act. How many days of wage work a year does the new law guarantee a rural household?",
    options: ["100 days", "150 days", "125 days", "90 days"],
    correctIndex: 2,
    explanation: "Passed by both Houses on 18 Dec 2025 and in force from 1 July 2026, it raises MGNREGA's 100-day guarantee to 125 and adds an infrastructure mandate. Opposition MPs protested and wanted the Bill sent to a standing committee.",
    sourceUrl: "https://www.business-standard.com/india-news/vb-g-ram-g-replacing-mgnrega-to-come-into-force-across-india-from-july-1-126051100540_1.html",
    sourceLabel: "Business Standard — VB-G RAM G replacing MGNREGA to come into force across India from July 1 (11 May 2026)",
    sources: ["https://prsindia.org/billtrack/the-viksit-bharat-%E2%80%93-guarantee-for-rozgar-and-ajeevika-mission-gramin-vb-%E2%80%93-g-ram-g-bill-2025", "https://www.deccanherald.com/india/contentious-vb-g-ram-g-bill-2025-tabled-in-parliament-amidst-opposition-protest-3832673"],
    tags: ["distribution"],
    enactedBy: [{ name: "Shivraj Singh Chouhan", role: "Union Rural Development Minister (ministry in charge of the law)", party: "BJP" }],
  },
  {
    id: "hsc037",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "VB-G RAM G Act",
    kind: "scheme",
    difficulty: "expert",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "Under the VB-G RAM G Act that replaced MGNREGA, how is the cost split between the Centre and most states?",
    options: ["Centre pays all wages", "75:25, Centre to state", "60:40, Centre to state", "50:50, Centre to state"],
    correctIndex: 2,
    explanation: "Wages, material and admin costs are shared 60:40 (90:10 for north-eastern and Himalayan states). Under MGNREGA the Centre paid the entire unskilled wage bill and three-fourths of material costs.",
    sourceUrl: "https://prsindia.org/billtrack/the-viksit-bharat-%E2%80%93-guarantee-for-rozgar-and-ajeevika-mission-gramin-vb-%E2%80%93-g-ram-g-bill-2025",
    sourceLabel: "PRS Legislative Research — The VB-G RAM G Bill, 2025 (Dec 2025)",
    tags: ["distribution"],
    enactedBy: [{ name: "Shivraj Singh Chouhan", role: "Union Rural Development Minister (ministry in charge of the law)", party: "BJP" }],
  },
  {
    id: "hsc038",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "MGNREGA wage payments",
    kind: "scheme",
    difficulty: "expert",
    year: 2024,
    asOf: "2026-09",
    govt: "NDA",
    question: "From which date did the Centre make the Aadhaar-Based Payment System the only channel for paying MGNREGS wages, after several extensions?",
    options: ["1 January 2024", "1 April 2022", "1 July 2026", "15 August 2023"],
    correctIndex: 0,
    explanation: "ABPS became the exclusive channel from 1 Jan 2024. The Rural Development Ministry called it \"the best alternative\" to avoid rejections and speed wages; LibTech India researchers, analysing 3.13 crore wage transactions, disputed claims that it made payments quicker.",
    sourceUrl: "https://m.thewire.in/article/government/mgnrega-aadhaar-based-payments-wages-delay-rejections",
    sourceLabel: "The Wire — MGNREGS: Govt's claims of quickness with Aadhaar-based payments are false (30 Jan 2025)",
    tags: ["distribution"],
  },
  {
    id: "hsc039",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "MGNREGA work days",
    kind: "scheme",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "What share of MGNREGS households got the full 100 days of work in 2024-25 (to January 2025), per PRS analysis of ministry data?",
    options: ["About 4%", "About 8%", "About 25%", "About 40%"],
    correctIndex: 0,
    explanation: "PRS found only 4% of households got 100 days in 2024-25, down from 8% in 2023-24, and wages received were below notified rates in 11 of 30 states/UTs. The Economic Survey 2023-24 argued MGNREGS demand is not a true indicator of rural distress.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2025/DFG_Analysis_2025-26_Rural_Development.pdf",
    sourceLabel: "PRS Legislative Research — Demand for Grants 2025-26 Analysis: Rural Development (4 Feb 2025)",
    tags: ["distribution"],
  },
  {
    id: "hsc040",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "MGNREGA",
    kind: "scheme",
    difficulty: "simple",
    year: 2005,
    asOf: "2026-09",
    govt: "UPA",
    question: "MGNREGA, the rural jobs law with a 100-day work guarantee that was repealed in 2026, was enacted in which year?",
    options: ["1999", "2009", "2005", "2014"],
    correctIndex: 2,
    explanation: "The National Rural Employment Guarantee Act, 2005, passed under the UPA government, guaranteed 100 days of wage work a year to rural households. It was repealed and replaced by the VB-G RAM G Act from 1 July 2026.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2025/DFG_Analysis_2025-26_Rural_Development.pdf",
    sourceLabel: "PRS Legislative Research — Demand for Grants 2025-26 Analysis: Rural Development (4 Feb 2025)",
    sources: ["https://www.scconline.com/blog/post/2026/05/12/vbgramg-act-implemented-from-1-july-2026/", "https://en.wikipedia.org/wiki/National_Rural_Employment_Guarantee_Act,_2005"],
    tags: ["distribution"],
  },
  {
    id: "hsc041",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "MGNREGA budget",
    kind: "spend",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "What was MGNREGS's budget estimate for 2025-26, its last full year before the law was replaced?",
    options: ["₹60,000 crore", "₹86,000 crore", "₹1.2 lakh crore", "₹73,000 crore"],
    correctIndex: 1,
    explanation: "PRS: ₹86,000 crore, the same as 2024-25 revised estimates, after actual spending of ₹89,154 crore in 2023-24. For its successor, VB-G RAM G, the Centre allocated over ₹95,000 crore in the next Union Budget, with states adding their share.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2025/DFG_Analysis_2025-26_Rural_Development.pdf",
    sourceLabel: "PRS Legislative Research — Demand for Grants 2025-26 Analysis: Rural Development (4 Feb 2025)",
    sources: ["https://www.business-standard.com/india-news/vb-g-ram-g-replacing-mgnrega-to-come-into-force-across-india-from-july-1-126051100540_1.html"],
    tags: ["distribution"],
  },
  {
    id: "hsc042",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Unified Pension Scheme",
    kind: "scheme",
    difficulty: "simple",
    year: 2024,
    asOf: "2026-09",
    govt: "NDA",
    question: "The Unified Pension Scheme for central employees (effective April 2025) assures what pension after 25 years of service?",
    options: ["Whatever the market-linked corpus buys", "50% of average basic pay of last 12 months", "100% of the last basic pay drawn", "A flat ₹10,000 a month"],
    correctIndex: 1,
    explanation: "Approved on 24 Aug 2024, UPS assures 50% of the average basic pay of the last 12 months, a 60% family pension, a ₹10,000 minimum after 10 years, and inflation-linked relief. It is an option alongside the market-linked NPS.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-unified-pension-scheme/",
    sourceLabel: "PMO — Cabinet approves Unified Pension Scheme (24 Aug 2024)",
    sources: ["https://indianexpress.com/article/explained/centre-announced-unified-pension-scheme-how-will-ups-differ-from-ops-nps-9531351/", "https://en.wikipedia.org/wiki/Unified_Pension_Scheme"],
  },
  {
    id: "hsc043",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "National Pension System",
    kind: "scheme",
    difficulty: "extreme",
    year: 2004,
    asOf: "2026-09",
    govt: "NDA",
    question: "The market-linked National Pension System, which UPS now sits beside, applied to central government staff joining on or after which date?",
    options: ["1 April 2010", "1 January 2014", "1 January 2004", "1 April 1998"],
    correctIndex: 2,
    explanation: "The NPS, brought in by the NDA government of the time, covered recruits from 1 Jan 2004 and linked pensions to invested contributions. Five opposition-ruled states had moved back to the Old Pension Scheme before the Centre approved UPS in Aug 2024.",
    sourceUrl: "https://www.thehindu.com/news/national/rip-new-pension-scheme-born-january-1-2004-extinguished-august-24-2024/article68563482.ece",
    sourceLabel: "The Hindu — RIP New Pension Scheme: born January 1, 2004, extinguished August 24, 2024 (25 Aug 2024)",
    sources: ["https://en.wikipedia.org/wiki/National_Pension_System"],
  },
  {
    id: "hsc044",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "Atal Pension Yojana",
    kind: "scheme",
    difficulty: "simple",
    year: 2015,
    asOf: "2026-09",
    govt: "NDA",
    question: "Atal Pension Yojana, launched in May 2015 for unorganised-sector workers, guarantees what monthly pension from age 60?",
    options: ["A flat ₹3,000", "₹500 to ₹2,000", "₹10,000 to ₹15,000", "₹1,000 to ₹5,000"],
    correctIndex: 3,
    explanation: "APY guarantees ₹1,000–₹5,000 a month from 60, depending on contributions. Over 8.66 crore subscribers had enrolled by 19 Jan 2026, and the Cabinet extended its funding support to 2030-31.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-for-continuation-of-atal-pension-yojana-apy-and-extension-of-funding-support-for-promotional-and-developmental-activities-and-gap-funding-till-2030-31/",
    sourceLabel: "PMO — Cabinet approves continuation of Atal Pension Yojana till 2030-31 (21 Jan 2026)",
    tags: ["distribution"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister (chaired the Cabinet that extended APY to 2030-31)", party: "BJP" }],
  },
  {
    id: "hsc045",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "Smart Cities Mission",
    kind: "scheme",
    difficulty: "expert",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "Ten years after its 2015 launch, how many of the 100 Smart Cities Mission cities had completed all their projects by March 2025?",
    options: ["18", "54", "82", "100"],
    correctIndex: 0,
    explanation: "Per PIB data cited by Down To Earth, 18 cities had finished all projects, though 7,504 projects (93%) worth ₹1,50,306 crore were complete overall; 559 projects worth ₹14,239 crore were still ongoing across 82 cities.",
    sourceUrl: "https://www.downtoearth.org.in/governance/after-a-decade-of-its-launch-only-18-out-of-100-cities-have-completed-smart-cities-mission-projects-but-there-are-some-positive-takeaways",
    sourceLabel: "Down To Earth — After a decade, only 18 of 100 cities have completed Smart Cities Mission projects (29 Apr 2025)",
  },
  {
    id: "hsc046",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PM Fasal Bima Yojana",
    kind: "scheme",
    difficulty: "simple",
    year: 2016,
    asOf: "2026-09",
    govt: "NDA",
    question: "Under PM Fasal Bima Yojana (2016), what premium does a farmer pay for kharif crops, with governments paying the rest?",
    options: ["10% of sum insured", "2% of sum insured", "0.5% of sum insured", "5% of sum insured"],
    correctIndex: 1,
    explanation: "Farmers pay 2% for kharif, 1.5% for rabi and 5% for horticulture; the Centre and states share the remaining premium equally. About 68 crore farmer applications had been insured by Jan 2025.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2025/DFG_Analysis_2025-26_Agriculture_&_Farmers_Welfare.pdf",
    sourceLabel: "PRS Legislative Research — Demand for Grants 2025-26 Analysis: Agriculture and Farmers Welfare (4 Feb 2025)",
    tags: ["distribution"],
  },
  {
    id: "hsc047",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PM Fasal Bima Yojana",
    kind: "spend",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "PM Fasal Bima Yojana claims paid peaked in 2017-18. Roughly how much was paid out that year, per PRS citing the scheme dashboard?",
    options: ["₹16,441 crore", "₹8,500 crore", "₹52,000 crore", "₹29,043 crore"],
    correctIndex: 3,
    explanation: "Claims fell from ₹29,043 crore (2017-18) to ₹16,441 crore (2022-23), and the 2025-26 allocation of ₹12,242 crore was the lowest since 2018-19. The Agriculture standing committee (2021) blamed delayed claims partly on late state premium subsidy.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2025/DFG_Analysis_2025-26_Agriculture_&_Farmers_Welfare.pdf",
    sourceLabel: "PRS Legislative Research — Demand for Grants 2025-26 Analysis: Agriculture and Farmers Welfare (4 Feb 2025)",
    tags: ["distribution"],
  },
  {
    id: "hsc048",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "PM Fasal Bima Yojana",
    kind: "scheme",
    difficulty: "expert",
    year: 2020,
    asOf: "2026-09",
    govt: "NDA",
    question: "What did the Centre change in PM Fasal Bima Yojana in February 2020 for farmers who had taken crop loans?",
    options: ["Made enrolment compulsory", "Doubled their premium share", "Made enrolment voluntary", "Ended cover for rabi crops"],
    correctIndex: 2,
    explanation: "Until 2020 PMFBY was compulsory for loanee farmers — banks deducted their premium from loan accounts — and voluntary for others. The revamp, as the article put it, made it 100% voluntary and capped premiums at 30%.",
    sourceUrl: "https://indianexpress.com/article/india/pmfby-2-0-a-revamped-crop-insurance-scheme-6288647/",
    sourceLabel: "The Indian Express — PMFBY 2.0: a revamped crop insurance scheme (27 Feb 2020)",
    sources: ["https://prsindia.org/files/budget/budget_parliament/2025/DFG_Analysis_2025-26_Agriculture_&_Farmers_Welfare.pdf"],
  },
  {
    id: "hsc049",
    domain: "civics",
    region: "India",
    state: "GJ",
    topic: "Farm & Food",
    subtopic: "PM Fasal Bima Yojana",
    kind: "scheme",
    difficulty: "expert",
    year: 2020,
    asOf: "2026-09",
    govt: "BJP",
    question: "In August 2020, which state left PM Fasal Bima Yojana citing the premium burden and launched its own state-funded scheme for kharif 2020?",
    options: ["Gujarat", "Punjab", "Kerala", "Haryana"],
    correctIndex: 0,
    explanation: "BusinessLine reported (10 Aug 2020) that BJP-ruled Gujarat exited PMFBY over the premium burden and launched a state-funded alternative — \"too\", because other states had already left.",
    sourceUrl: "https://www.thehindubusinessline.com/economy/agri-business/gujarat-too-exits-pm-crop-insurance-scheme-citing-premium-burden/article32319981.ece",
    sourceLabel: "The Hindu BusinessLine — Gujarat, too, exits PM crop insurance scheme, citing premium burden (10 Aug 2020)",
  },
  {
    id: "hsc050",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Environment & Land",
    subtopic: "Namami Gange",
    kind: "spend",
    difficulty: "extreme",
    year: 2017,
    asOf: "2026-09",
    govt: "NDA",
    question: "A CAG audit of Namami Gange for 2014–17 found the National Mission for Clean Ganga spent what share of its revised budget in 2014-15?",
    options: ["37%", "8%", "63%", "91%"],
    correctIndex: 1,
    explanation: "CAG found spending of 8% (2014-15), 37% (2015-16) and 63% (2016-17). By March 2017 NMCG had received ₹3,633 crore of the ₹7,387 crore it was eligible for and used ₹1,836.4 crore — which CAG said indicated poor implementation.",
    sourceUrl: "https://frontline.thehindu.com/the-nation/murky-waters/article10008438.ece",
    sourceLabel: "Frontline — Namami Gange: Murky waters (3 Jan 2018)",
  },
  {
    id: "hsc051",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Environment & Land",
    subtopic: "Namami Gange",
    kind: "spend",
    difficulty: "simple",
    year: 2015,
    asOf: "2026-09",
    govt: "NDA",
    question: "Namami Gange, the NDA government's flagship Ganga clean-up, was allocated what budget for the five years ending in 2020?",
    options: ["₹2,000 crore", "₹75,000 crore", "₹20,000 crore", "₹4,000 crore"],
    correctIndex: 2,
    explanation: "The ₹20,000 crore allocation was about four times earlier efforts; officials said ₹4,000 crore had been spent on cleaning the river since the first central plan in 1985. A later CAG audit found funds badly under-used in 2014–17.",
    sourceUrl: "https://frontline.thehindu.com/the-nation/murky-waters/article10008438.ece",
    sourceLabel: "Frontline — Namami Gange: Murky waters (3 Jan 2018)",
  },
  {
    id: "hsc052",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Defence & Security",
    subtopic: "Agnipath",
    kind: "scheme",
    difficulty: "simple",
    year: 2022,
    asOf: "2026-09",
    govt: "NDA",
    question: "Under the Agnipath military recruitment scheme (2022), what share of each annual batch of Agniveers can stay on after four years?",
    options: ["Up to 50%", "Up to 75%", "Up to 25%", "All of them"],
    correctIndex: 2,
    explanation: "Of about 45,000–50,000 recruits a year, most leave after four years; only 25% can continue for another 15 years in the regular cadre, which makes the 13-lakh-strong forces leaner.",
    sourceUrl: "https://indianexpress.com/article/explained/agnipath-scheme-for-recruiting-soldiers-7969432/",
    sourceLabel: "The Indian Express — Agnipath scheme for recruiting soldiers: what is it, how will it work? (Jun 2022)",
  },
  {
    id: "hsc053",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "PM SVANidhi",
    kind: "scheme",
    difficulty: "expert",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "When PM SVANidhi for street vendors was restructured in August 2025, the first-tranche loan was raised from ₹10,000 to what?",
    options: ["₹15,000", "₹20,000", "₹25,000", "₹50,000"],
    correctIndex: 0,
    explanation: "The Cabinet (27 Aug 2025) extended lending to 31 Mar 2030 with an outlay of ₹7,332 crore, raised the first loan to ₹15,000 and the second to ₹25,000 (the third stays ₹50,000), and added UPI-linked RuPay credit cards, targeting 1.15 crore beneficiaries.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-restructuring-extension-of-lending-period-beyond-31-12-2024-of-pm-street-vendors-atmanirbhar-nidhi-pm-svanidhi-scheme/",
    sourceLabel: "PMO — Cabinet approves restructuring and extension of PM SVANidhi (27 Aug 2025)",
  },
  {
    id: "hsc054",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Energy & Mining",
    subtopic: "PM Surya Ghar",
    kind: "scheme",
    difficulty: "simple",
    year: 2024,
    asOf: "2026-09",
    govt: "NDA",
    question: "PM Surya Ghar: Muft Bijli Yojana (2024) aims to fit rooftop solar on 1 crore homes to give up to how much free electricity a month?",
    options: ["100 units", "200 units", "500 units", "300 units"],
    correctIndex: 3,
    explanation: "Approved on 29 Feb 2024 with ₹75,021 crore, it gives central subsidy of about ₹30,000 for a 1 kW system, ₹60,000 for 2 kW and ₹78,000 for 3 kW or more, at benchmark prices.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-pm-surya-ghar-muft-bijli-yojana-for-installing-rooftop-solar-in-one-crore-households/",
    sourceLabel: "PMO — Cabinet approves PM-Surya Ghar: Muft Bijli Yojana (29 Feb 2024)",
    tags: ["distribution", "pre-election"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister (launched it; chaired the Cabinet that approved it)", party: "BJP" }],
    outcome:
      "Launched by the PM on 13 Feb 2024 and approved by the Cabinet on 29 Feb with an outlay of ₹75,021 crore, 50 days before Lok Sabha polling began on 19 Apr 2024. The BJP won 240 of 543 seats, short of a majority; the NDA won 293.",
    poll: { label: "Lok Sabha 2024", month: "2024-04", gapDays: 50, result: "BJP won 240 of 543 seats; NDA 293" },
  },
  {
    id: "hsc055",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "Direct Benefit Transfer",
    kind: "spend",
    difficulty: "extreme",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "The Centre's DBT Mission credits Direct Benefit Transfer with 'estimated gains' from removing fake or duplicate beneficiaries. What total did its portal show in September 2026?",
    options: ["About ₹51,400 crore", "About ₹5.14 lakh crore", "About ₹51 lakh crore", "About ₹1.2 lakh crore"],
    correctIndex: 1,
    explanation: "The dbtbharat.gov.in dashboard showed ₹5,14,201.92 crore. These are government estimates; researchers writing in The Wire argue DBT's exclusion errors — eligible people who could not get their money — need independent evaluation. The figure is live and changes over time.",
    sourceUrl: "https://dbtbharat.gov.in/",
    sourceLabel: "DBT Mission, Cabinet Secretariat — dbtbharat.gov.in dashboard (viewed Sep 2026)",
    sources: ["https://m.thewire.in/article/political-economy/a-tale-of-trade-offs-the-anatomy-of-the-direct-benefit-transfers-system"],
    tags: ["distribution"],
  },
  {
    id: "hsc056",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "Direct Benefit Transfer",
    kind: "scheme",
    difficulty: "expert",
    year: 2013,
    asOf: "2026-09",
    govt: "UPA",
    question: "Aadhaar-linked Direct Benefit Transfer for pensions, scholarships and MGNREGS payments began rolling out in January 2013 under which government?",
    options: ["NDA-I", "NDA-II", "UPA-I", "UPA-II"],
    correctIndex: 3,
    explanation: "The UPA-II government set up a National Committee on Direct Cash Transfers in Dec 2012 and began DBT in Jan 2013; in Andhra Pradesh it started in one district, not the five announced, as Aadhaar-linked accounts lagged. Today the DBT portal lists 320 schemes across 56 ministries.",
    sourceUrl: "https://www.thehindu.com/todays-paper/direct-benefit-transfer-scheme-finally-gets-going/article4281371.ece",
    sourceLabel: "The Hindu — Direct Benefit Transfer scheme finally gets going (7 Jan 2013)",
    sources: ["https://pib.gov.in/newsite/PrintRelease.aspx?relid=90093", "https://dbtbharat.gov.in/", "https://en.wikipedia.org/wiki/Direct_Benefit_Transfer"],
    tags: ["distribution"],
    enactedBy: [{ name: "Jairam Ramesh", role: "Union Rural Development Minister (launched DBT in Andhra Pradesh, 2013)", party: "INC" }],
  },
  {
    id: "hsc057",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "Freebies debate",
    kind: "institution",
    difficulty: "expert",
    year: 2022,
    asOf: "2026-09",
    govt: "NDA",
    question: "In August 2022 the Supreme Court sent the election-freebies debate to a three-judge bench to reconsider a 2013 ruling. What had that ruling held pre-poll freebie promises to be?",
    options: ["A corrupt practice that voids an election", "Legal only if the budget can fund them", "Not a 'corrupt practice' under election law", "Banned once the model code is in force"],
    correctIndex: 2,
    explanation: "The 2013 verdict, in a Tamil Nadu case, held such promises cannot be termed a corrupt practice. Petitioners argued it overlooked the Representation of the People Act; the court cited the complexity of the issues in referring it to a larger bench.",
    sourceUrl: "https://indianexpress.com/article/india/supreme-court-electoral-freebies-revdi-issue-ramana-8112552/",
    sourceLabel: "The Indian Express — Election freebies: Supreme Court refers matter to three-judge bench (26 Aug 2022)",
  },
  {
    id: "hsc058",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Energy & Mining",
    subtopic: "Saubhagya",
    kind: "scheme",
    difficulty: "expert",
    year: 2022,
    asOf: "2026-09",
    govt: "NDA",
    question: "Under Saubhagya, states declared every 'willing' household electrified by March 2019. How many households did the scheme electrify in all, per the Power Ministry?",
    options: ["About 2.86 crore", "About 28.6 lakh", "About 8.6 crore", "About 1.2 crore"],
    correctIndex: 0,
    explanation: "The Power Ministry said 2.86 crore households were electrified, including homes that became willing after 31 Mar 2019; the scheme closed on 31 Mar 2022. All villages had been declared electrified on 28 Apr 2018.",
    sourceUrl: "https://pib.gov.in/Pressreleaseshare.aspx?PRID=1845839",
    sourceLabel: "PIB (Power Ministry) — Schemes to achieve uninterrupted power supply (28 Jul 2022)",
    tags: ["distribution"],
  },
  {
    id: "hsc059",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Energy & Mining",
    subtopic: "Rural power supply",
    kind: "scheme",
    difficulty: "extreme",
    year: 2022,
    asOf: "2026-09",
    govt: "NDA",
    question: "After village and household electrification drives, what average daily hours of power supply did the Power Ministry report for rural areas in July 2022?",
    options: ["About 12 hours", "About 16 hours", "About 21.5 hours", "About 24 hours"],
    correctIndex: 2,
    explanation: "The ministry put average supply at 21.48 hours in rural and 23.78 hours in urban areas as of 8 July 2022, after the DDUGJY village scheme (18,374 villages) and the Saubhagya household scheme.",
    sourceUrl: "https://pib.gov.in/Pressreleaseshare.aspx?PRID=1845839",
    sourceLabel: "PIB (Power Ministry) — Schemes to achieve uninterrupted power supply (28 Jul 2022)",
  },
  {
    id: "hsc060",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "ECLGS",
    kind: "scheme",
    difficulty: "expert",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "ECLGS 5.0, approved in May 2026 amid the West Asia crisis, offers government-guaranteed extra credit to MSMEs, other firms and which specific sector?",
    options: ["Scheduled passenger airlines", "Private hospitals", "Real-estate developers", "Film production houses"],
    correctIndex: 0,
    explanation: "It gives 100% guarantee cover for MSMEs and 90% for non-MSMEs and airlines, with no fee; airlines can borrow up to ₹1,500 crore each. The Covid-era ECLGS limit had been raised to ₹5 lakh crore in Aug 2022.",
    sourceUrl: "https://www.pmindia.gov.in/en/news_updates/cabinet-approves-emergency-credit-line-guarantee-scheme-5-0/",
    sourceLabel: "PMO — Cabinet approves Emergency Credit Line Guarantee Scheme 5.0 (5 May 2026)",
    sources: ["https://www.pmindia.gov.in/en/news_updates/cabinet-approves-enhancement-in-the-corpus-of-emergency-credit-line-guarantee-scheme-for-increasing-the-limit-of-admissible-guarantees/"],
  },
]);
