// HISAAB DO — Budget & spending lane (hbx001–hbx050; hbx046 dropped in the 26 Sep 2026 fact audit).
// Every figure below was read on the linked page in September 2026 and re-checked on 26 Sep 2026; see
// docs/hisaab/research/spending-notes.md for sources, drops and figures likely to change.
export const HISAAB_SPENDING = Object.freeze([
  {
    id: "hbx001",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Union Budget size",
    kind: "spend",
    difficulty: "simple",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "Union Budget 2014-15 planned total spending of about ₹17.9 lakh crore. About how much does Budget 2026-27 plan to spend?",
    options: ["About ₹35.5 lakh crore", "About ₹71.4 lakh crore", "About ₹53.5 lakh crore", "About ₹44.8 lakh crore"],
    correctIndex: 2,
    explanation: "Budget 2014-15 (July 2014) put total expenditure at ₹17,94,892 crore; Budget 2026-27 puts it at ₹53,47,315 crore — about three times as much in nominal rupees. The economy grew too: nominal GDP was projected at about ₹128.8 lakh crore for 2014-15 and ₹393 lakh crore for 2026-27. All are budget estimates, not final spending.",
    sourceUrl: "https://www.indiabudget.gov.in/doc/Budget_at_Glance/budget_at_a_glance.pdf",
    sourceLabel: "Ministry of Finance — Budget at a Glance 2026-27 (Feb 2026)",
    sources: ["https://www.indiabudget.gov.in/budget2014-2015/ub2014-15/bag/bag1.pdf", "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2221455"],
  },
  {
    id: "hbx002",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Rupee Goes To: interest",
    kind: "spend",
    difficulty: "simple",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "In Budget 2026-27's 'Rupee Goes To' chart, how many paise of every rupee go to interest payments on past borrowing?",
    options: ["20 paise", "11 paise", "6 paise", "32 paise"],
    correctIndex: 0,
    explanation: "Interest takes 20 paise of every rupee in 2026-27, more than triple the 6 paise for major subsidies. Only the states' share of taxes (22 paise) is larger; central sector schemes get 17 paise. In rupees, interest payments are budgeted at ₹14,03,972 crore.",
    sourceUrl: "https://www.indiabudget.gov.in/doc/Budget_at_Glance/budget_at_a_glance.pdf",
    sourceLabel: "Ministry of Finance — Budget at a Glance 2026-27 (Feb 2026)",
    sources: ["https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf"],
  },
  {
    id: "hbx003",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Rupee Comes From: borrowing",
    kind: "spend",
    difficulty: "expert",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "In Budget 2026-27's 'Rupee Comes From' chart, how many paise of every rupee the Union receives come from borrowings and other liabilities?",
    options: ["9 paise", "15 paise", "38 paise", "24 paise"],
    correctIndex: 3,
    explanation: "Borrowings and other liabilities are the single biggest source, at 24 paise; all taxes together bring 64 paise and non-tax revenue 10. The fiscal deficit this borrowing covers is budgeted at ₹16,95,768 crore, or 4.3% of GDP; gross market borrowing is put at ₹17.2 lakh crore.",
    sourceUrl: "https://www.indiabudget.gov.in/doc/Budget_at_Glance/budget_at_a_glance.pdf",
    sourceLabel: "Ministry of Finance — Budget at a Glance 2026-27 (Feb 2026)",
    sources: ["https://www.pib.gov.in/PressReleasePage.aspx?PRID=2221455"],
  },
  {
    id: "hbx004",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "Income tax vs corporation tax",
    kind: "spend",
    difficulty: "expert",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "In Budget 2026-27's 'Rupee Comes From' chart, which single tax brings the Union the most paise per rupee?",
    options: ["Corporation tax", "Income tax", "GST & other taxes", "Union excise duties"],
    correctIndex: 1,
    explanation: "Income tax (which includes securities transaction tax) brings 21 paise, corporation tax 18, GST and other taxes 15, excise 6 and customs 4. In rupees, PRS shows ₹14,66,000 crore budgeted from taxes on income against ₹12,31,000 crore from corporation tax.",
    sourceUrl: "https://www.indiabudget.gov.in/doc/Budget_at_Glance/budget_at_a_glance.pdf",
    sourceLabel: "Ministry of Finance — Budget at a Glance 2026-27 (Feb 2026)",
    sources: ["https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf"],
  },
  {
    id: "hbx005",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Interest vs revenue receipts",
    kind: "spend",
    difficulty: "extreme",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "PRS calculates that interest payments took 37% of the Union's revenue receipts in 2013-14. What share are they estimated to take in 2026-27?",
    options: ["About 25%", "About 40%", "About 52%", "About 33%"],
    correctIndex: 1,
    explanation: "Per PRS, interest rose from 37% of revenue receipts in 2013-14 to 42% in 2020-21 and is estimated at 40% in 2026-27 — about 26% of total spending. PRS also finds 65.3% of revenue receipts go on committed spending: salaries, pensions and interest.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2026-27 Analysis (1 Feb 2026)",
  },
  {
    id: "hbx006",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Fiscal deficit 2020-21",
    kind: "spend",
    difficulty: "simple",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "In the Covid year 2020-21, the Union's fiscal deficit (actuals) reached what share of GDP?",
    options: ["4.6%", "6.4%", "12.8%", "9.2%"],
    correctIndex: 3,
    explanation: "In the pandemic year the fiscal deficit reached ₹18,18,291 crore, or 9.2% of GDP (actuals, PRS). It has since come down: 6.9% in 2021-22 (revised), 4.8% in 2024-25 (actuals) and 4.4% in 2025-26 (revised), with 4.3% targeted for 2026-27.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2022/Union%20Budget%20Analysis%20-%202022-23.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2022-23 Analysis (Feb 2022)",
    sources: ["https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf"],
  },
  {
    id: "hbx007",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Fiscal deficit 2013-14",
    kind: "spend",
    difficulty: "extreme",
    year: 2014,
    asOf: "2026-09",
    govt: "UPA",
    question: "For 2013-14, the UPA government's last full year, what fiscal deficit did the revised estimate show as a share of GDP?",
    options: ["4.6%", "3.3%", "5.9%", "2.8%"],
    correctIndex: 0,
    explanation: "The Budget at a Glance 2014-15 shows the 2013-14 fiscal deficit at ₹5,24,539 crore, or 4.6% of GDP (revised estimate), against a 4.8% budget target. The new NDA government's July 2014 budget then targeted 4.1% for 2014-15.",
    sourceUrl: "https://www.indiabudget.gov.in/budget2014-2015/ub2014-15/bag/bag1.pdf",
    sourceLabel: "Ministry of Finance — Budget at a Glance 2014-15 (July 2014)",
  },
  {
    id: "hbx008",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Central government debt",
    kind: "spend",
    difficulty: "expert",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "The Centre's outstanding liabilities peaked in 2020-21. About what share of GDP did they reach, per PRS?",
    options: ["49%", "55%", "61%", "72%"],
    correctIndex: 2,
    explanation: "PRS: liabilities rose between 2018-19 and 2020-21 to a high of 61% of GDP, then moderated. They are estimated at 55.6% of GDP in 2026-27 (56.1% in the 2025-26 revised estimate). The government's stated aim is around 50% ± 1% of GDP by March 2031.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2026-27 Analysis (1 Feb 2026)",
    sources: ["https://www.pib.gov.in/PressReleasePage.aspx?PRID=2221455"],
  },
  {
    id: "hbx009",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "Capital expenditure",
    kind: "spend",
    difficulty: "simple",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "Union capital expenditure was budgeted at about ₹2.27 lakh crore in 2014-15. What is it in Budget 2026-27?",
    options: ["About ₹6.1 lakh crore", "About ₹18.5 lakh crore", "About ₹12.2 lakh crore", "About ₹9.4 lakh crore"],
    correctIndex: 2,
    explanation: "Capital expenditure was ₹2,26,781 crore in BE 2014-15 and is ₹12,21,821 crore in BE 2026-27, over five times more and 11.5% above the 2025-26 revised estimate (PRS). Counting grants to states for creating assets, 'effective capex' is ₹17,14,523 crore.",
    sourceUrl: "https://www.indiabudget.gov.in/doc/Budget_at_Glance/budget_at_a_glance.pdf",
    sourceLabel: "Ministry of Finance — Budget at a Glance 2026-27 (Feb 2026)",
    sources: ["https://www.indiabudget.gov.in/budget2014-2015/ub2014-15/bag/bag1.pdf", "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf"],
  },
  {
    id: "hbx010",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "Capex 2024-25: budget vs actual",
    kind: "spend",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "Budget 2024-25 set capital expenditure at ₹11,11,111 crore. How much did the Union actually spend on capex that year?",
    options: ["₹10,51,953 crore", "₹12,04,318 crore", "₹11,11,111 crore", "₹9,48,506 crore"],
    correctIndex: 0,
    explanation: "Actual 2024-25 capital expenditure was ₹10,51,953 crore — about ₹59,000 crore short of the ₹11.11 lakh crore budgeted (PRS, July 2024). The pattern repeated in 2025-26: capex is revised to ₹10,95,755 crore against ₹11,21,090 crore budgeted.",
    sourceUrl: "https://www.indiabudget.gov.in/doc/Budget_at_Glance/budget_at_a_glance.pdf",
    sourceLabel: "Ministry of Finance — Budget at a Glance 2026-27 (Feb 2026)",
    sources: ["https://prsindia.org/files/budget/budget_parliament/2024/Union_Budget_Analysis_2024-25.pdf", "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf"],
  },
  {
    id: "hbx011",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Defence & Security",
    subtopic: "Defence allocation",
    kind: "spend",
    difficulty: "simple",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "Which ministry gets the largest allocation in Budget 2026-27 — about 15% of all Union spending?",
    options: ["Road Transport & Highways", "Railways", "Home Affairs", "Defence"],
    correctIndex: 3,
    explanation: "Defence is allotted ₹7,84,678 crore, 15% of budgeted spending, per PRS — including ₹2,19,306 crore of capital outlay for the armed forces, 17.6% above the 2025-26 revised estimate. Next come Road Transport & Highways (6%), Railways (5%) and Home Affairs (5%).",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2026-27 Analysis (1 Feb 2026)",
    sources: ["https://www.indiabudget.gov.in/doc/Budget_at_Glance/budget_at_a_glance.pdf"],
  },
  {
    id: "hbx012",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "Health ministry allocation",
    kind: "spend",
    difficulty: "expert",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "About how much does Budget 2026-27 allot to the Ministry of Health & Family Welfare?",
    options: ["About ₹2.4 lakh crore", "About ₹1.07 lakh crore", "About ₹58,000 crore", "About ₹3.1 lakh crore"],
    correctIndex: 1,
    explanation: "Health gets ₹1,06,530 crore, 10% over the 2025-26 revised estimate (PRS), and less than Education's ₹1,39,289 crore. The Health ministry's 2025-26 allocation was also revised down, from ₹99,859 crore to ₹96,854 crore.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2026-27 Analysis (1 Feb 2026)",
  },
  {
    id: "hbx013",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Welfare & Subsidies",
    subtopic: "Subsidy bill",
    kind: "spend",
    difficulty: "expert",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "Food and fertiliser together make up about what share of the Union's ₹4.55 lakh crore subsidy bill in Budget 2026-27?",
    options: ["About 55%", "About 87%", "About 70%", "About 96%"],
    correctIndex: 1,
    explanation: "Food subsidy (₹2,27,629 crore) and fertiliser subsidy (₹1,70,799 crore) are 87% of total subsidies of ₹4,54,773 crore, per PRS; LPG subsidy is just 2.6%. In 2025-26, food subsidy overshot its budget by 12% and fertiliser subsidy by 11% at the revised stage.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2026-27 Analysis (1 Feb 2026)",
    tags: ["distribution"],
  },
  {
    id: "hbx014",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Food subsidy 2020-21",
    kind: "spend",
    difficulty: "extreme",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "Budget 2020-21 allotted about ₹1.16 lakh crore for food subsidy. What did the revised estimate grow to?",
    options: ["About ₹2.42 lakh crore", "About ₹1.97 lakh crore", "About ₹6.10 lakh crore", "About ₹4.23 lakh crore"],
    correctIndex: 3,
    explanation: "The revised 2020-21 food subsidy was ₹4,22,618 crore, 266% above the ₹1,15,570 crore budgeted. PRS, citing the budget speech, links the extra allocation to clearing the Food Corporation of India's pending food-subsidy dues. The 2021-22 budget then allotted ₹2,42,836 crore.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2021/Union%20Budget%20Analysis%20-%202021-22_0.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2021-22 Analysis (Feb 2021)",
    tags: ["distribution"],
  },
  {
    id: "hbx015",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Farm & Food",
    subtopic: "Fertiliser subsidy",
    kind: "spend",
    difficulty: "extreme",
    year: 2022,
    asOf: "2026-09",
    govt: "NDA",
    question: "Fertiliser subsidy peaked in 2022-23 when global raw-material prices spiked. What was the actual bill that year?",
    options: ["About ₹2.51 lakh crore", "About ₹1.64 lakh crore", "About ₹3.37 lakh crore", "About ₹1.05 lakh crore"],
    correctIndex: 0,
    explanation: "Actual fertiliser subsidy was ₹2,51,339 crore in 2022-23, which PRS attributes to a sharp rise in international prices of raw materials for fertiliser. It fell to ₹1,89,487 crore in 2023-24 and is budgeted at ₹1,70,799 crore for 2026-27.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2024/Union_Budget_Analysis_2024-25.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2024-25 Analysis (July 2024)",
    sources: ["https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf"],
    tags: ["distribution"],
  },
  {
    id: "hbx016",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "Jal Jeevan Mission",
    kind: "scheme",
    difficulty: "extreme",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "Jal Jeevan Mission was budgeted ₹67,000 crore for 2025-26. What did the revised estimate cut it to?",
    options: ["₹60,000 crore", "₹45,500 crore", "₹17,000 crore", "₹33,000 crore"],
    correctIndex: 2,
    explanation: "PRS: spending on Jal Jeevan Mission was cut by ₹50,000 crore to ₹17,000 crore at the revised stage, the main reason the Jal Shakti ministry's 2025-26 allocation fell from ₹99,503 crore to ₹41,437 crore. The scheme is allotted ₹67,670 crore again for 2026-27.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2026-27 Analysis (1 Feb 2026)",
  },
  {
    id: "hbx017",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "Income tax relief 2025",
    kind: "spend",
    difficulty: "extreme",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "Budget 2025 made income up to ₹12 lakh tax-free, forgoing about ₹1 lakh crore. By the revised estimate, how far short of its own target did income-tax receipts fall?",
    options: ["About ₹26,000 crore", "About ₹2.40 lakh crore", "About ₹1.26 lakh crore", "About ₹74,000 crore"],
    correctIndex: 2,
    explanation: "The nil-tax threshold under the new regime rose from ₹7 lakh to ₹12 lakh (₹12.75 lakh for salaried earners). Budget 2025-26 then expected ₹14,38,000 crore from income tax; the revised estimate is ₹13,12,000 crore, a ₹1,26,000 crore shortfall (PRS).",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2026-27 Analysis (1 Feb 2026)",
    sources: [
      "https://www.business-standard.com/budget/news/budget-2025-tax-free-income-limit-under-new-regime-rises-to-rs-12-lakh-125020101583_1.html",
      "https://www.livemint.com/elections/delhi-election-results-did-nirmala-sitharaman-s-income-tax-cuts-fuel-bjp-s-capital-gains-11738990221509.html",
      "https://frontline.thehindu.com/news/delhi-election-results-2025-bjp-wins-46-seats-ends-aap-rule/article69195445.ece",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Nirmala Sitharaman", role: "Union Finance Minister (presented Budget 2025-26)", party: "BJP" }],
    outcome:
      "Presented on 1 Feb 2025; Delhi voted four days later, on 5 Feb, and the BJP won 48 of 70 seats to AAP’s 22. Income-tax receipts for 2025-26 were later revised to ₹13,12,000 crore against ₹14,38,000 crore budgeted (PRS).",
    poll: { label: "Delhi Assembly 2025", month: "2025-02", gapDays: 4, result: "BJP won 48 of 70 seats; AAP 22" },
  },
  {
    id: "hbx018",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Disinvestment",
    kind: "spend",
    difficulty: "expert",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "The Centre budgeted ₹47,000 crore from selling stakes in public sector firms in 2025-26. About what share of that target does the revised estimate expect to meet?",
    options: ["About 72%", "About 45%", "About 96%", "About 58%"],
    correctIndex: 0,
    explanation: "Revised disinvestment receipts for 2025-26 are ₹33,837 crore — 71.9% of target, per PRS. The 2026-27 target is ₹80,000 crore, which PRS calls the first increase after five straight years of downward revisions and shortfalls.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2026-27 Analysis (1 Feb 2026)",
  },
  {
    id: "hbx019",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "16th Finance Commission",
    kind: "institution",
    difficulty: "simple",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "What share of the divisible pool of central taxes did the 16th Finance Commission recommend for the states for 2026-31?",
    options: ["32%", "50%", "45%", "41%"],
    correctIndex: 3,
    explanation: "The 16th FC kept the states' share at 41%, as under the 15th FC, for 2026-27 to 2030-31, though 18 of 28 states had pitched for 50%. It said states already account for over two-thirds of the nation's non-debt revenues. It also added 'contribution to GDP' (10% weight) to the formula for splitting taxes among states (Business Standard, PRS).",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2026-27 Analysis (1 Feb 2026)",
    sources: ["https://www.business-standard.com/budget/news/16th-finance-commission-retains-41-percent-devolution-gdp-criterion-126020101042_1.html"],
  },
  {
    id: "hbx020",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "Cesses and surcharges",
    kind: "institution",
    difficulty: "expert",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "Some Union levies are not shared with states at all because they sit outside the 'divisible pool'. Which ones?",
    options: ["Corporation tax", "Cesses and surcharges", "Customs duties", "Central GST (CGST)"],
    correctIndex: 1,
    explanation: "The divisible pool is the Centre's gross tax revenue minus the cost of collection and cesses and surcharges, so the Centre keeps those levies in full (PRS). The states' share recommended by each Finance Commission applies only to what remains in the pool.",
    sourceUrl: "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf",
    sourceLabel: "PRS Legislative Research — Union Budget 2026-27 Analysis (1 Feb 2026)",
  },
  {
    id: "hbx021",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "RBI surplus transfer 2019",
    kind: "institution",
    difficulty: "simple",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "In Aug 2019 the RBI board, adopting the Bimal Jalan committee's capital framework, approved transferring how much to the government?",
    options: ["₹68,000 crore", "₹1,76,051 crore", "₹2,40,000 crore", "₹3,40,000 crore"],
    correctIndex: 1,
    explanation: "The ₹1,76,051 crore combined the RBI's 2018-19 surplus of ₹1,23,414 crore with ₹52,637 crore of 'excess' risk provisions released under the revised Economic Capital Framework (PRS). The RBI board said it accepted all the committee's recommendations.",
    status: "Named only as chair of an RBI expert committee (report 2019); the item alleges no wrongdoing by him.",
    otherSide: "Congress called the transfer 'stealing from RBI'; the Finance Minister said it was 'outlandish' to question the RBI, which had set up the Jalan panel of eminent experts.",
    people: ["Bimal Jalan"],
    sourceUrl: "https://prsindia.org/policy/monthly-policy-review/august-2019",
    sourceLabel: "PRS Legislative Research — Monthly Policy Review, August 2019",
    sources: [
      "https://www.business-standard.com/amp/article/news-ani/rbi-to-transfer-rs-1-76-051-crore-to-government-119082601410_1.html",
      "https://www.deccanherald.com/india/cong-says-centre-stole-from-rbi-nirmala-hits-back-757425.html",
    ],
  },
  {
    id: "hbx022",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "RBI surplus transfer 2026",
    kind: "institution",
    difficulty: "expert",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "In May 2026 the RBI approved a record surplus transfer to the Centre for 2025-26. About how much?",
    options: ["₹1.58 lakh crore", "₹2.11 lakh crore", "₹3.95 lakh crore", "₹2.87 lakh crore"],
    correctIndex: 3,
    explanation: "The RBI board approved ₹2,86,588.46 crore, topping the previous year's record, while setting aside ₹1,09,379.64 crore for its contingent risk buffer (kept at 6.5% of its balance sheet). Such payouts feed 'dividends and profits', which PRS says make up 59% of non-tax revenue in 2026-27.",
    sourceUrl: "https://www.rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=62789",
    sourceLabel: "Reserve Bank of India — press release on surplus transfer (22 May 2026)",
    sources: ["https://www.business-standard.com/economy/news/rbi-to-transfer-record-rs-2-87-trillion-dividend-to-govt-for-fy26-126052201017_1.html", "https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf"],
  },
  {
    id: "hbx023",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "Demonetisation 2016",
    kind: "spend",
    difficulty: "simple",
    year: 2018,
    asOf: "2026-09",
    govt: "NDA",
    question: "Of the ₹500 and ₹1,000 notes demonetised in November 2016, what share came back to the banking system, per the RBI annual report for 2017-18?",
    options: ["About 99.3%", "About 86%", "About 73%", "About 91.5%"],
    correctIndex: 0,
    explanation: "The RBI's annual report for 2017-18 said ₹15.31 lakh crore of the ₹15.42 lakh crore in demonetised ₹500 and ₹1,000 notes had come back, 99.3%. It also noted that currency in circulation had surpassed its pre-demonetisation level.",
    otherSide: "The Centre told the Supreme Court the note ban was a 'well-considered' step against fake money, terror financing, black money and tax evasion.",
    sourceUrl: "https://www.business-standard.com/article/news-ani/99-3-demonetised-notes-returned-to-banks-rbi-118082901029_1.html",
    sourceLabel: "Business Standard (ANI) — 99.3% demonetised notes returned to banks: RBI (29 Aug 2018)",
    sources: ["https://rbidocs.rbi.org.in/rdocs/AnnualReport/PDFs/8VIIICURRENCYEBA72A2F77784806B26D8F22FAD05C35.PDF", "https://www.business-standard.com/article/current-affairs/sc-upholds-demonetisation-says-test-of-proportionality-satisfied-123010200294_1.html"],
  },
  {
    id: "hbx024",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "Demonetisation verdict",
    kind: "institution",
    difficulty: "expert",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "On 2 January 2023 a five-judge Supreme Court bench ruled on the 2016 note ban. What was the outcome?",
    options: ["Struck down by 3:2", "Upheld by 5:0", "Upheld by 4:1", "Referred to a larger bench"],
    correctIndex: 2,
    explanation: "The majority held the decision-making process valid and the move proportionate, citing six months of Centre–RBI consultation. The dissenting judge said the power lay in Parliament's law-making power over currency (Entry 36, List I), not Section 26(2) of the RBI Act.",
    otherSide: "Congress said calling it 'upheld' was misleading: the ruling covered the decision-making process, not whether the note ban met its stated objectives.",
    sourceUrl: "https://www.business-standard.com/article/current-affairs/sc-upholds-demonetisation-says-test-of-proportionality-satisfied-123010200294_1.html",
    sourceLabel: "Business Standard — SC upholds demonetisation, says test of proportionality satisfied (2 Jan 2023)",
    sources: ["https://www.business-standard.com/article/economy-policy/to-say-demonetisation-was-upheld-is-misleading-congress-on-sc-verdict-123010200404_1.html"],
  },
  {
    id: "hbx025",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "₹2,000 note withdrawal",
    kind: "institution",
    difficulty: "extreme",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "When the RBI withdrew ₹2,000 notes on 19 May 2023, ₹3.56 lakh crore were in circulation. What share had returned by 30 April 2026?",
    options: ["87.20%", "93.65%", "98.47%", "99.91%"],
    correctIndex: 2,
    explanation: "By 30 April 2026, ₹2,000 notes worth ₹5,451 crore were still with the public; 98.47% had come back. The RBI says the notes remain legal tender and can still be exchanged or deposited at its 19 issue offices.",
    sourceUrl: "https://newsonair.gov.in/rbi-says-98-47-per-cent-of-%E2%82%B92000-banknotes-have-been-returned/",
    sourceLabel: "All India Radio News — RBI says 98.47% of ₹2,000 banknotes returned (2 May 2026)",
  },
  {
    id: "hbx026",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "Bank loan write-offs",
    kind: "spend",
    difficulty: "simple",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "Banks wrote off bad loans worth about how much over the ten financial years to 2023-24, according to a reply in Parliament (March 2025)?",
    options: ["About ₹16.35 lakh crore", "About ₹4.2 lakh crore", "About ₹35.8 lakh crore", "About ₹9.9 lakh crore"],
    correctIndex: 0,
    explanation: "Write-offs totalled about ₹16.35 lakh crore, peaking at ₹2,36,265 crore in 2018-19; the lowest was ₹58,786 crore in 2014-15, and 2023-24 saw ₹1,70,270 crore. The Finance Minister said banks keep pursuing recovery through civil suits, debt recovery tribunals, SARFAESI and insolvency proceedings.",
    otherSide: "The Finance Minister said write-offs do not waive borrowers' liabilities and so do not benefit the borrower.",
    sourceUrl: "https://www.business-standard.com/finance/news/banks-wrote-off-bad-loans-worth-rs-16-35-trillion-in-last-10-years-govt-125031700462_1.html",
    sourceLabel: "Business Standard (PTI) — Banks wrote off bad loans worth Rs 16.35 trillion in last 10 years: Govt (17 Mar 2025)",
  },
  {
    id: "hbx027",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Corporate tax cut 2019",
    kind: "spend",
    difficulty: "simple",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "In September 2019 the Centre cut the base corporate tax rate for existing domestic companies that give up exemptions, from 30% to what?",
    options: ["25%", "18%", "15%", "22%"],
    correctIndex: 3,
    explanation: "The Taxation Laws (Amendment) Ordinance set an optional 22% rate (25.17% effective with surcharge and cess) and 15% for new manufacturing firms. The Finance Ministry estimated revenue forgone at ₹1,45,000 crore and pitched the cut as a boost to investment and 'Make in India'.",
    sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1585641",
    sourceLabel: "PIB (Ministry of Finance) — Corporate tax rates slashed to 22% for domestic companies (20 Sep 2019)",
    sources: ["https://www.business-standard.com/economy/news/govt-lost-rs-1-trn-in-taxes-in-fy21-due-to-corporate-tax-cut-mos-fin-123080800817_1.html"],
    enactedBy: [{ name: "Nirmala Sitharaman", role: "Union Finance Minister (announced the cut in Goa, 20 Sep 2019)", party: "BJP" }],
    outcome:
      "Corporate tax collections fell from ₹6.63 lakh crore in 2018-19 to ₹5.56 lakh crore in 2019-20, the first year of the cut, before recovering in later years, a minister told Parliament in 2023.",
  },
  {
    id: "hbx028",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Corporate tax cut: revenue cost",
    kind: "spend",
    difficulty: "extreme",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "The government told Parliament how much revenue the 2019 corporate tax cut cost in 2019-20 alone. What figure did it give?",
    options: ["₹45,300 crore", "₹1,28,170 crore", "₹2,15,600 crore", "₹86,940 crore"],
    correctIndex: 1,
    explanation: "A Minister of State for Finance put the 2019-20 loss at ₹1,28,170 crore and re-estimated 2020-21 at ₹1,00,241 crore. Corporate tax collections later recovered, reaching over ₹8.28 lakh crore in 2022-23 (provisional), up from ₹5.56 lakh crore in 2019-20.",
    sourceUrl: "https://www.business-standard.com/economy/news/govt-lost-rs-1-trn-in-taxes-in-fy21-due-to-corporate-tax-cut-mos-fin-123080800817_1.html",
    sourceLabel: "Business Standard (PTI) — Govt lost Rs 1 trn in taxes in FY21 due to corporate tax cut: MoS Fin (8 Aug 2023)",
  },
  {
    id: "hbx029",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "GST launch 2017",
    kind: "spend",
    difficulty: "simple",
    year: 2017,
    asOf: "2026-09",
    govt: "NDA",
    question: "Where was GST launched at the stroke of midnight on 1 July 2017?",
    options: ["Rashtrapati Bhavan forecourt", "Central Hall of Parliament", "Vigyan Bhawan, New Delhi", "RBI headquarters, Mumbai"],
    correctIndex: 1,
    explanation: "The President and Prime Minister pressed the button in Parliament's Central Hall. Congress, Trinamool, RJD, DMK and the Left boycotted, calling it a spectacle for self-promotion; Congress allies NCP and SP attended.",
    otherSide: "The Finance Minister rejected the opposition's self-promotion charge, and the PM said there could be no 'better and sacred' venue than Central Hall.",
    sourceUrl: "https://www.business-standard.com/article/news-ians/gst-rolls-out-past-midnight-from-central-hall-of-parliament-roundup-117070100031_1.html",
    sourceLabel: "Business Standard (IANS) — GST rolls out past midnight from Central Hall of Parliament (1 Jul 2017)",
  },
  {
    id: "hbx030",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "GST compensation cess",
    kind: "spend",
    difficulty: "expert",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "GST promised states compensation for revenue shortfalls for five years. In September 2021 the GST Council extended the compensation cess until when?",
    options: ["June 2022", "March 2024", "March 2030", "March 2026"],
    correctIndex: 3,
    explanation: "The extension let the Centre repay loans it raised and passed to states in lieu of compensation during the pandemic — about ₹1.10 lakh crore in 2020-21 alone. The government said the extended cess would only service those loans. Budget 2026-27 shows no compensation-cess receipts.",
    sourceUrl: "https://www.business-standard.com/article/economy-policy/gst-council-extends-levy-of-compensation-cess-till-march-2026-121091701331_1.html",
    sourceLabel: "Business Standard (IANS) — GST Council extends levy of compensation cess till March 2026 (17 Sep 2021)",
    sources: ["https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf"],
  },
  {
    id: "hbx031",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "GST 2.0 (2025)",
    kind: "spend",
    difficulty: "simple",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "GST 2.0, effective 22 September 2025, moved most goods to 5% or 18%. Which of these did it exempt from GST altogether?",
    options: ["Individual health insurance premiums", "Cement", "Small cars", "Two-wheelers up to 350cc"],
    correctIndex: 0,
    explanation: "PIB: individual health insurance was exempted, which it said would make premiums cheaper, while cement, small cars and two-wheelers up to 350cc were cut from 28% to 18%. Many daily food items moved to 5% or nil. Hindustan Times reported that individual life insurance policies were exempted too.",
    sourceUrl: "https://www.pib.gov.in/FactsheetDetails.aspx?Id=150302",
    sourceLabel: "PIB — Factsheet: GST Reforms for a New Generation (20 Sep 2025)",
    sources: [
      "https://www.hindustantimes.com/business/new-two-tier-gst-structure-to-kick-in-from-22-september-nirmala-sitharaman-101756917458027.html",
      "https://www.thehindu.com/elections/bihar-assembly/bihar-assembly-election-first-phase-sees-over-64-voter-turnout/article70249590.ece",
      "https://www.hindustantimes.com/india-news/nda-mahagathbandhan-bjp-jdu-rjd-congress-ljp-jan-suraaj-prashant-kishore-tejashwi-seat-tally-101763169862862.html",
    ],
    tags: ["pre-election"],
    enactedBy: [{ name: "Nirmala Sitharaman", role: "Union Finance Minister; heads the GST Council that approved it", party: "BJP" }],
    outcome:
      "The GST Council approved the two-slab structure on 3 Sep 2025; the rates took effect on 22 Sep, 45 days before Bihar’s first phase of polling on 6 Nov. The NDA won 202 of 243 seats in Bihar.",
    poll: { label: "Bihar Assembly 2025", month: "2025-11", gapDays: 45, result: "NDA won 202 of 243 seats; BJP 89, JD(U) 85" },
  },
  {
    id: "hbx032",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Jobs & Economy",
    subtopic: "Air India sale",
    kind: "spend",
    difficulty: "expert",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "The Tata group's winning ₹18,000 crore bid for Air India (Oct 2021) was mostly debt taken over. How much was paid in cash?",
    options: ["₹9,000 crore", "₹15,300 crore", "₹2,700 crore", "₹600 crore"],
    correctIndex: 2,
    explanation: "Tata paid ₹2,700 crore in cash and took on ₹15,300 crore of debt. About ₹46,262 crore of Air India's debt and ₹15,834 crore of other liabilities stayed with the government's holding company, AIAHL. The rival consortium bid ₹15,100 crore.",
    sourceUrl: "https://www.business-standard.com/article/companies/air-india-returns-to-tatas-after-group-puts-in-winning-bid-of-rs-18-000-cr-121100800762_1.html",
    sourceLabel: "Business Standard — Air India returns to Tatas after group puts in winning bid of Rs 18,000 cr (8 Oct 2021)",
  },
  {
    id: "hbx033",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "LIC IPO",
    kind: "spend",
    difficulty: "simple",
    year: 2022,
    asOf: "2026-09",
    govt: "NDA",
    question: "LIC's May 2022 IPO — India's largest at the time — raised about how much for the government?",
    options: ["About ₹8,235 crore", "About ₹52,000 crore", "About ₹20,557 crore", "About ₹12,860 crore"],
    correctIndex: 2,
    explanation: "Priced at ₹949 a share, the ₹20,557 crore IPO was subscribed 2.95 times. LIC closed its first trading day at ₹873, 8% below the issue price, valuing the insurer at about ₹5.54 lakh crore.",
    sourceUrl: "https://www.business-standard.com/article/markets/lic-shares-drop-8-below-issue-price-on-debut-end-at-rs-873-apiece-122051701018_1.html",
    sourceLabel: "Business Standard — LIC shares drop 8% below issue price on debut (18 May 2022)",
    sources: ["https://www.business-standard.com/article/markets/lic-ipo-govt-raises-rs-20-560-crore-as-firs-sets-issue-prices-at-rs-949-122051300346_1.html"],
  },
  {
    id: "hbx034",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "National Monetisation Pipeline",
    kind: "scheme",
    difficulty: "extreme",
    year: 2026,
    asOf: "2026-09",
    govt: "NDA",
    question: "The National Monetisation Pipeline (2021) targeted ₹6 lakh crore from brownfield public assets. What potential does NMP 2.0 (FY26 to FY30) estimate?",
    options: ["₹16.72 lakh crore", "₹9.5 lakh crore", "₹25.1 lakh crore", "₹11.4 lakh crore"],
    correctIndex: 0,
    explanation: "NMP 2.0, launched in February 2026, estimates ₹16.72 lakh crore over five years, including ₹5.8 lakh crore of private investment. The Finance Minister said NMP 1.0 met nearly 90% of its target. When NMP 1.0 launched, Congress called it 'legalised loot and organised plunder'; it covered assets such as roads, railway stations, airports and stadiums.",
    otherSide: "The Finance Minister said NMP involves no transfer of ownership or land, only brownfield assets already built but underused.",
    sourceUrl: "https://www.business-standard.com/markets/capital-market-news/finance-minister-nirmala-sitharaman-launches-national-monetisation-pipeline-2-0-126022400250_1.html",
    sourceLabel: "Business Standard — Finance Minister launches National Monetisation Pipeline 2.0 (24 Feb 2026)",
    sources: ["https://www.business-standard.com/article/economy-policy/asset-monetisation-pipeline-govt-used-4-methods-to-value-rs-6-trn-assets-121082500021_1.html", "https://www.business-standard.com/article/current-affairs/legalised-loot-organised-plunder-cong-on-national-monetisation-pipeline-121082400549_1.html"],
  },
  {
    id: "hbx035",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "PM CARES Fund",
    kind: "institution",
    difficulty: "simple",
    year: 2020,
    asOf: "2026-09",
    govt: "NDA",
    question: "PM CARES Fund's trust deed was registered on 27 March 2020. About how much did it receive by 31 March 2020, per its audited statement?",
    options: ["About ₹310 crore", "About ₹12,450 crore", "About ₹890 crore", "About ₹3,077 crore"],
    correctIndex: 3,
    explanation: "Its audited receipts-and-payments account shows ₹3,076.62 crore by 31 March 2020, almost all voluntary contributions, including ₹39.68 lakh from abroad. Donations qualify for 100% income-tax exemption and count as corporate CSR spending; the fund also has an FCRA exemption for foreign donations.",
    sourceUrl: "https://pmcares.gov.in/assets/donation/pdf/Audited%20Statement.PDF",
    sourceLabel: "PM CARES Fund — Audited receipts and payments account, period ended 31 Mar 2020",
    sources: ["https://pmcares.gov.in/assets/donation/pdf/Audited_Statement_2020_21.pdf", "https://pmcares.gov.in/en/web/page/about_us"],
    tags: ["relief"],
    enactedBy: [{ name: "Narendra Modi", role: "Prime Minister; ex-officio Chairman of the PM CARES Fund", party: "BJP" }],
  },
  {
    id: "hbx036",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Health",
    subtopic: "PM CARES Fund spending",
    kind: "institution",
    difficulty: "extreme",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "PM CARES Fund's audited 2020-21 accounts list its disbursals. What got the single largest amount?",
    options: ["50,000 Made-in-India ventilators", "6.6 crore Covid-19 vaccine doses", "States' funds for migrant workers", "Oxygen plants in public hospitals"],
    correctIndex: 1,
    explanation: "Of ₹3,976 crore disbursed in 2020-21, ₹1,392.83 crore bought 6.6 crore vaccine doses, ₹1,311.34 crore went on 50,000 ventilators, ₹1,000 crore to states for migrants and ₹201.58 crore on 162 oxygen plants. Receipts plus opening balance that year totalled ₹10,990 crore.",
    sourceUrl: "https://pmcares.gov.in/assets/donation/pdf/Audited_Statement_2020_21.pdf",
    sourceLabel: "PM CARES Fund — Audited receipts and payments account 2020-21",
    tags: ["relief"],
  },
  {
    id: "hbx037",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "PM CARES Fund balance",
    kind: "institution",
    difficulty: "extreme",
    year: 2025,
    asOf: "2026-09",
    govt: "NDA",
    question: "PM CARES Fund's audited accounts for 2024-25 show how much money it held on 31 March 2025, mostly in fixed deposits?",
    options: ["About ₹1,240 crore", "About ₹8,452 crore", "About ₹19,600 crore", "About ₹4,105 crore"],
    correctIndex: 1,
    explanation: "It closed 2024-25 with ₹8,452.07 crore, including ₹7,846.65 crore in FDs that earned ₹469 crore interest that year. Payments in 2024-25 were under ₹1 crore (₹87.85 lakh, under PM CARES for Children). The accounts are audited by a chartered-accountant firm and posted on the fund's website.",
    sourceUrl: "https://pmcares.gov.in/assets/donation/pdf/Audited_Statement_2024_25.pdf",
    sourceLabel: "PM CARES Fund — Audited receipts and payments account 2024-25 (signed Aug 2026)",
    tags: ["relief"],
  },
  {
    id: "hbx038",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "PM CARES and NDRF",
    kind: "institution",
    difficulty: "expert",
    year: 2020,
    asOf: "2026-09",
    govt: "NDA",
    question: "In August 2020 the Supreme Court heard a plea to move PM CARES money to the National Disaster Response Fund. What did it do?",
    options: ["Ordered a full transfer", "Ordered a CAG audit first", "Referred it to Parliament", "Dismissed the plea"],
    correctIndex: 3,
    explanation: "The court held PM CARES money belongs to a public charitable trust, entirely different from the NDRF, so there was no occasion to order a transfer; the Centre stays free to route funds to the NDRF. It also found the existing national disaster plan sufficient for Covid-19.",
    otherSide: "The petitioner had argued PM CARES was neither CAG-audited nor under the RTI Act, and that moving its money to the NDRF would bring it under the disaster law.",
    sourceUrl: "https://www.livelaw.in/top-stories/sc-dismisses-plea-to-transfer-pm-cares-funds-to-ndrf-saysfresh-national-disaster-plan-for-covid-19-not-needed-161577",
    sourceLabel: "LiveLaw — SC dismisses plea to transfer PM CARES funds to NDRF (18 Aug 2020)",
    sources: ["https://www.livemint.com/news/india/no-transfer-of-money-from-pm-cares-to-disaster-relief-fund-sc-11597732268728.html"],
    tags: ["relief"],
  },
  {
    id: "hbx039",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "PM CARES and RTI",
    kind: "institution",
    difficulty: "expert",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "In a September 2021 reply to a Delhi High Court plea to declare PM CARES a 'State', what did the PMO say barred disclosure of the trust's information in any case?",
    options: ["The RTI Act's bar on third-party information", "The Official Secrets Act", "Parliamentary privilege", "A national-security exemption"],
    correctIndex: 0,
    explanation: "A PMO under secretary, who serves the trust honorarily, said that whether or not the trust is a 'State' or an RTI 'public authority', Section 8 of the RTI Act bars disclosing third-party information. He said the trust works transparently and posts its audited accounts and spending online. The PMO had earlier refused RTI requests about the fund.",
    status: "Reply filed in a Delhi HC petition (2021) seeking Article 12 status; no final ruling reported as of Sep 2026. In Jan 2026 a Delhi HC bench hearing a separate RTI appeal orally said the fund keeps third-party privacy rights under the RTI Act.",
    otherSide: "The petitioner argued that a fund set up by the PM, with ministers as trustees, cannot be treated as one outside government control.",
    sourceUrl: "https://indianexpress.com/article/cities/delhi/pm-cares-fund-not-a-fund-of-government-of-india-hc-told-7528391/",
    sourceLabel: "Indian Express — PM-CARES Fund not a fund of Government of India, Delhi HC told (23 Sep 2021)",
    sources: [
      "https://www.livelaw.in/top-stories/pm-cares-funds-not-a-public-authority-under-rti-act-affirms-appellate-authority-in-pmo-159152",
      "https://www.business-standard.com/india-news/pm-cares-fund-privacy-rights-rti-act-delhi-high-court-order-126011301228_1.html",
      "https://www.livelaw.in/high-court/delhi-high-court/pm-cares-fund-juristic-personality-right-to-privacy-rti-act-518738",
    ],
    tags: ["relief"],
  },
  {
    id: "hbx040",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "New Parliament building",
    kind: "spend",
    difficulty: "simple",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "India's new Parliament building, inaugurated on 28 May 2023, was built at an estimated cost of about how much?",
    options: ["About ₹2,850 crore", "About ₹415 crore", "About ₹971 crore", "About ₹20,000 crore"],
    correctIndex: 2,
    explanation: "Business Standard puts the building's cost at ₹971 crore; Tata Projects won the construction contract in September 2020 with a bid of ₹861.90 crore. The ₹20,000 crore figure often quoted is for the wider Central Vista redevelopment, of which the Parliament building is one part.",
    sourceUrl: "https://www.business-standard.com/india-news/new-parliamentary-building-explained-costs-construction-design-more-123091300281_1.html",
    sourceLabel: "Business Standard — New Parliament building explained: costs, construction, design (Sep 2023)",
    sources: ["https://scroll.in/article/964355/centres-rs-20000-crore-central-vista-redevelopment-plan-may-sit-at-odds-with-delhi-heritage-rules", "https://www.business-standard.com/article/companies/tata-projects-wins-bid-to-construct-new-parliament-building-officials-120091601583_1.html"],
  },
  {
    id: "hbx041",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "Central Vista verdict",
    kind: "institution",
    difficulty: "expert",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "In January 2021 the Supreme Court cleared the Central Vista redevelopment, including the new Parliament. By what margin?",
    options: ["Unanimous 5:0", "3:2 majority", "2:1 majority", "Unanimous 3:0"],
    correctIndex: 2,
    explanation: "The majority found the land-use change proper and said the court cannot order the government not to spend on one project in favour of another. The dissenting judge held the public was not taken into confidence, and would have quashed the land-use change and the environmental clearance.",
    sourceUrl: "https://www.thehindu.com/news/national/sc-gives-nod-to-central-vista-project/article33498980.ece",
    sourceLabel: "The Hindu — Plan to erect new Parliament building gets SC green light (5 Jan 2021)",
  },
  {
    id: "hbx042",
    domain: "civics",
    region: "India",
    state: "GJ",
    topic: "Infrastructure",
    subtopic: "Statue of Unity",
    kind: "spend",
    difficulty: "extreme",
    year: 2014,
    asOf: "2026-09",
    govt: "BJP",
    question: "In July 2014, L&T's lowest bid to build the Statue of Unity was about ₹2,980 crore. What had the project been estimated to cost?",
    options: ["₹2,063 crore", "₹3,640 crore", "₹1,120 crore", "₹2,540 crore"],
    correctIndex: 0,
    explanation: "The Indian Express reported the bid against a ₹2,063 crore cost estimate for the project. The same week, the Union Budget 2014-15 allotted ₹200 crore to the project, and Gujarat's own 2014-15 budget sanctioned ₹500 crore.",
    sourceUrl: "https://indianexpress.com/article/cities/ahmedabad/lt-to-build-statue-of-unity-centre-grants-rs-200-crore/",
    sourceLabel: "Indian Express — L&T to build Statue of Unity, Centre grants Rs 200 crore (11 Jul 2014)",
    sources: ["https://www.thehindu.com/news/national/other-states/statue-of-unity-gets-rs-200-crore/article6197549.ece"],
  },
  {
    id: "hbx043",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "Mumbai–Ahmedabad bullet train",
    kind: "spend",
    difficulty: "simple",
    year: 2017,
    asOf: "2026-09",
    govt: "NDA",
    question: "Japan's JICA funds 81% of the Mumbai–Ahmedabad bullet train through a 50-year yen loan. At what annual interest rate?",
    options: ["1.5%", "4%", "7.25%", "0.1%"],
    correctIndex: 3,
    explanation: "The loan (about ₹88,000 crore in 2017) carries 0.1% interest; a 2017 critique argued it is not 'free', as rupee repayments over 50 years would grow with the Japan–India inflation gap. The project costs over ₹1 lakh crore, and in January 2026 the Railways Minister set 15 August 2027 for the first operations.",
    otherSide: "The PM described the 0.1% yen loan from Japan as virtually free of cost.",
    sourceUrl: "https://www.business-standard.com/article/economy-policy/do-the-math-india-s-first-bullet-train-isn-t-free-of-cost-as-modi-claims-117091800116_1.html",
    sourceLabel: "Business Standard (The Wire) — Do the math: India's first bullet train isn't free of cost (18 Sep 2017)",
    sources: ["https://www.business-standard.com/india-news/india-first-bullet-train-mumbai-ahmedabad-operations-august-15-2027-126010100919_1.html"],
  },
  {
    id: "hbx044",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "Bharatmala Phase I audit",
    kind: "spend",
    difficulty: "extreme",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "CAG's 2023 audit found only 75.62% of Bharatmala Phase I's approved length awarded by March 2023. What share of its outlay had been sanctioned?",
    options: ["62.10%", "158.24%", "98.75%", "211.40%"],
    correctIndex: 1,
    explanation: "The CAG report, tabled on 10 August 2023, flagged cost overruns in the ₹5.35 lakh crore programme and irregularities in awarding projects, and recommended probing tendering lapses to fix responsibility on officials. No later finding on those recommendations was reported as of Sep 2026.",
    otherSide: "An official said the audit missed that land-acquisition costs had risen five-fold from the ₹30,000 crore first estimated, and that any discrepancy would be investigated.",
    sourceUrl: "https://www.business-standard.com/economy/news/costlier-land-acquisition-led-to-bharatmala-cost-overrun-official-123081700257_1.html",
    sourceLabel: "Business Standard — Costlier land acquisition led to Bharatmala cost overrun: official (17 Aug 2023)",
  },
  {
    id: "hbx045",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Infrastructure",
    subtopic: "Dwarka Expressway",
    kind: "spend",
    difficulty: "expert",
    year: 2023,
    asOf: "2026-09",
    govt: "NDA",
    question: "CAG's Bharatmala audit flagged the Dwarka Expressway's cost at about ₹250 crore per km. What per-km figure was it compared with?",
    options: ["₹72.5 crore per km", "₹18.2 crore per km", "₹152 crore per km", "₹5.6 crore per km"],
    correctIndex: 1,
    explanation: "Opposition parties alleged corruption in the award. The ministry said bridge- and tunnel-heavy Bharatmala projects average ₹152 crore/km, and ministry sources said the 8-lane elevated road's four packages were awarded at ₹181.94 crore/km, 12% below estimates.",
    otherSide: "The road ministry called the comparison a 'gross misrepresentation of facts', saying ₹18.2 crore/km was only a normative average used for Cabinet approval.",
    sourceUrl: "https://www.business-standard.com/india-news/govt-saved-12-cost-in-awarding-dwarka-experssway-project-report-123081600613_1.html",
    sourceLabel: "Business Standard — Govt saved 12% cost in awarding Dwarka Expressway project: report (16 Aug 2023)",
    sources: [
      "https://www.newsonair.gov.in/road-transport-and-highways-ministry-issues-clarification-on-high-capital-cost-for-dwarka-expressway",
      "https://www.business-standard.com/politics/aap-protests-at-dwarka-expressway-over-irregularities-flagged-by-cag-report-123081600189_1.html",
    ],
  },
  {
    id: "hbx047",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "Public sector bank mergers",
    kind: "institution",
    difficulty: "simple",
    year: 2019,
    asOf: "2026-09",
    govt: "NDA",
    question: "In August 2019 the Centre announced merging 10 public sector banks into four. Oriental Bank of Commerce and United Bank of India went into which anchor bank?",
    options: ["Punjab National Bank", "Canara Bank", "Union Bank of India", "Indian Bank"],
    correctIndex: 0,
    explanation: "PNB absorbed OBC and United Bank; Syndicate Bank went into Canara Bank; Andhra and Corporation Bank into Union Bank of India; Allahabad Bank into Indian Bank. The Centre also announced ₹55,250 crore of capital for PSBs, citing efficiency and lower lending costs.",
    sourceUrl: "https://prsindia.org/policy/monthly-policy-review/august-2019",
    sourceLabel: "PRS Legislative Research — Monthly Policy Review, August 2019",
  },
  {
    id: "hbx048",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Energy & Mining",
    subtopic: "Excise duty on petrol",
    kind: "spend",
    difficulty: "expert",
    year: 2020,
    asOf: "2026-09",
    govt: "NDA",
    question: "Central excise on a litre of petrol was ₹9.48 in 2014. After the hikes of March–May 2020, what total did it reach?",
    options: ["₹19.90 a litre", "₹45.10 a litre", "₹32.98 a litre", "₹24.56 a litre"],
    correctIndex: 2,
    explanation: "PTI reported the 2020 hikes mopped up gains from the crash in global oil prices instead of passing them on; excise reached ₹32.98/litre on petrol and ₹31.83 on diesel. Cuts in Nov 2021 and May 2022 brought petrol to ₹19.90. The Centre's taxes from the petroleum sector rose from ₹1.72 lakh crore (2014-15) to ₹4.92 lakh crore (2021-22).",
    sourceUrl: "https://www.business-standard.com/article/pti-stories/govt-hikes-excise-duty-on-petrol-by-record-rs-10-diesel-by-rs-13-120050600005_1.html",
    sourceLabel: "Business Standard (PTI) — Govt hikes excise duty on petrol by record Rs 10, diesel by Rs 13 (6 May 2020)",
    sources: ["https://www.business-standard.com/article/economy-policy/excise-duty-on-petrol-was-rs-9-48-ltr-diesel-rs-3-56-in-2014-minister-122080100962_1.html"],
  },
  {
    id: "hbx049",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Banking & Finance",
    subtopic: "Retrospective tax",
    kind: "spend",
    difficulty: "extreme",
    year: 2021,
    asOf: "2026-09",
    govt: "NDA",
    question: "A 2021 law withdrew tax demands raised under the 2012 retrospective amendment. About how much had the government collected from the three firms that paid, which it offered to refund?",
    options: ["About ₹1,100 crore", "About ₹22,100 crore", "About ₹8,000 crore", "About ₹45 crore"],
    correctIndex: 2,
    explanation: "Business Standard: about ₹8,000 crore had been collected from three of the 17 companies with such demands, almost all of it from Cairn Energy, plus ₹44.7 crore from Vodafone and ₹48 crore from WNS. Refunds depended on dropping litigation and claims for costs or damages. The Act covered deals before 28 May 2012; the 2012 amendment was the UPA government's.",
    sourceUrl: "https://www.business-standard.com/article/economy-policy/govt-approaches-17-companies-to-settle-retrospective-tax-cases-121082300011_1.html",
    sourceLabel: "Business Standard — Govt approaches 17 companies to settle retrospective tax cases (23 Aug 2021)",
    sources: ["https://www.business-standard.com/article/economy-policy/us-body-hails-indian-govt-s-move-to-withdraw-retrospective-tax-law-121080600136_1.html"],
  },
  {
    id: "hbx050",
    domain: "civics",
    region: "India",
    state: "IN",
    topic: "Governance & Institutions",
    subtopic: "MPLADS suspension",
    kind: "spend",
    difficulty: "simple",
    year: 2020,
    asOf: "2026-09",
    govt: "NDA",
    question: "In April 2020 the Cabinet suspended MPs' local-area development funds (MPLADS) for 2020-21 and 2021-22. How much went to the Consolidated Fund instead?",
    options: ["₹7,900 crore", "₹1,975 crore", "₹15,800 crore", "₹3,950 crore"],
    correctIndex: 0,
    explanation: "The government said the two years of MPLADS money, ₹7,900 crore, would go to the Consolidated Fund for managing Covid-19; MPs, ministers and the PM also took a 30% pay cut for a year. The Cabinet restored MPLADS in November 2021: ₹2 crore per MP for the rest of 2021-22, then ₹5 crore a year (PIB).",
    otherSide: "A Congress MP backed the 30% pay cut but called suspending MPLADS 'a bit of an overstretch' that would hurt the poor most.",
    sourceUrl: "https://www.business-standard.com/article/news-ani/pm-ministers-mps-to-get-30-pc-less-salary-mplad-funds-suspended-for-2-years-120040600896_1.html",
    sourceLabel: "Business Standard (ANI) — PM, ministers, MPs to get 30% less salary; MPLAD funds suspended for 2 years (6 Apr 2020)",
    sources: [
      "https://www.business-standard.com/article/news-ani/move-on-mp-s-salaries-good-mplad-fund-should-not-be-suspended-manish-tewari-120040601556_1.html",
      "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1770523",
    ],
    tags: ["relief"],
    enactedBy: [{ name: "Prakash Javadekar", role: "Union Minister (announced the Cabinet decision, Apr 2020)", party: "BJP" }],
  },
]);
