// HISAAB DO — lane: States, North & Hindi belt (hst100–hst199).
// UP, UT, HP, PB, HR, DL, JK, RJ, BR, JH. Every item was checked against the page in `sourceUrl`
// (and `sources`) in September 2026, and independently fact-audited on 26 Sep 2026 (see the
// "Fact audit" section of the notes). See docs/hisaab/research/states-north-notes.md for sources,
// drops, contested items and the `govt` convention used in this lane:
//   govt = the party/arrangement heading the STATE whose record the item is about — for scheme and
//   spend items, the government that ran/budgeted it; for case items, the government in office when
//   the alleged conduct happened (a later arrest or ruling is carried in `status`).
// Hinglish names of schemes are kept as the government spells them.

export const HISAAB_STATES_NORTH = Object.freeze([
  // ───────────────────────────── DELHI ─────────────────────────────
  {
    id: 'hst100',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Governance & Institutions',
    subtopic: 'Delhi excise policy 2021-22 — CAG audit',
    kind: 'spend',
    difficulty: 'expert',
    year: 2021,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      "The CAG audit of Delhi's 2021-22 excise (liquor) policy, tabled in the Delhi Assembly in February 2025, put the cumulative revenue loss at about how much?",
    options: ['₹2,002 crore', '₹520 crore', '₹7,500 crore', '₹14,000 crore'],
    correctIndex: 0,
    explanation:
      'The CAG put the loss at ₹2,002.68 crore, citing vends that never opened in non-conforming wards and surrendered zones not re-tendered. AAP said seven of the report’s eight chapters faulted the old policy and that the new one was not implemented as designed. A separate CBI case over the policy ended in discharge in Feb 2026 (CBI has appealed).',
    status:
      'Audit finding, not a court finding. Related CBI case: all 23 accused discharged 27 Feb 2026; CBI revision pending in Delhi HC (as of Sept 2026).',
    otherSide:
      'AAP says the first seven of the report’s eight chapters audit the old 2017–21 policy, and that the CAG’s eighth chapter found the new policy was designed to raise revenue and curb smuggling.',
    sourceUrl: 'https://www.tribuneindia.com/news/delhi/2k-cr-loss-cag-report-on-delhi-excise-policy-tabled/amp',
    sourceLabel: 'The Tribune — ₹2k-cr loss: CAG report on Delhi excise policy tabled (Feb 2025)',
    sources: [
      'https://www.newsonair.gov.in/cag-report-flags-%E2%82%B92000-crore-revenue-loss-in-delhi-liquor-policy',
      'https://aamaadmiparty.org/press-release/cag-report-shows-that-old-excise-policy-was-causing-loss-to-public-exchequer-needed-change-atishi/',
    ],
  },
  {
    id: 'hst101',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Governance & Institutions',
    subtopic: 'Delhi excise policy case — arrest of the CM',
    kind: 'scam',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      'Which agency arrested Arvind Kejriwal on 21 March 2024, while he was Delhi’s chief minister, in the excise-policy case?',
    options: [
      'Central Bureau of Investigation (CBI)',
      'Delhi Police Economic Offences Wing',
      'Enforcement Directorate (ED)',
      'National Investigation Agency (NIA)',
    ],
    correctIndex: 2,
    explanation:
      'The ED arrested him under the money-laundering law on 21 Mar 2024; the CBI arrested him on 26 Jun 2024. The Supreme Court granted bail in the CBI case on 13 Sep 2024, one judge questioning the timing of that arrest. On 27 Feb 2026 a trial court discharged him and 22 others in the CBI case, finding the conspiracy claim unsupported. He has not been convicted.',
    status:
      'Arrested by ED (21 Mar 2024) and CBI (26 Jun 2024); on bail since Sept 2024; discharged in the CBI case 27 Feb 2026; CBI revision pending in Delhi HC (arguments listed 5–6 Oct 2026); PMLA trial proceedings deferred. Not convicted.',
    otherSide:
      'A trial court found no prima facie case and discharged him in the CBI case (Feb 2026); at the Supreme Court his counsel called the CBI arrest an ‘insurance arrest’.',
    people: ['Arvind Kejriwal'],
    sourceUrl:
      'https://www.scobserver.in/journal/supreme-court-grants-bail-to-arvind-kejriwal-in-cbi-case-bench-splits-over-the-validity-of-arrest/',
    sourceLabel: 'Supreme Court Observer — SC grants bail to Kejriwal in CBI case (13 Sep 2024)',
    sources: [
      'https://www.scconline.com/blog/post/2024/09/13/supreme-court-grants-bail-delhi-cm-arvind-kejriwal-cbi-case-delhi-excise-liquor-policy/',
      'https://www.scconline.com/blog/post/2026/03/09/del-hc-issues-notice-cbis-challenge-to-discharge-delhi-excise-policy-case/',
      'https://www.socialnews.xyz/2026/08/17/delhi-hc-gives-kejriwal-sisodia-4-weeks-to-file-replies-on-cbi-plea-against-discharge-in-excise-policy-case',
    ],
  },
  {
    id: 'hst102',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Governance & Institutions',
    subtopic: 'Delhi excise policy case — trial court order',
    kind: 'scam',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      'A trial court discharged Arvind Kejriwal, Manish Sisodia and 21 others in the CBI excise case in Feb 2026. In March, what did the Delhi HC do with its remarks against the CBI’s investigating officer?',
    options: [
      'Expunged them permanently',
      'Upheld them and ordered action',
      'Sent them to the Supreme Court',
      'Stayed them until the next hearing',
    ],
    correctIndex: 3,
    explanation:
      'Issuing notice on the CBI’s revision, the HC called the remarks prima facie ‘foundationally misconceived’ and stayed them, including a call for departmental action against the officer. The trial judge had found no prima facie case and called the policy the outcome of a consultative process; the CBI says he weighed evidence as if at trial.',
    status:
      'Discharged by the trial court 27 Feb 2026. CBI revision pending before the Delhi HC (last listed for arguments 5–6 Oct 2026); connected money-laundering proceedings deferred. Neither has been convicted.',
    otherSide:
      'The trial court held the chargesheet disclosed no prima facie case or overarching conspiracy against any of the 23; the HC gave them till its 5–6 Oct 2026 hearing to reply to the CBI’s revision.',
    people: ['Arvind Kejriwal', 'Manish Sisodia'],
    sourceUrl:
      'https://www.scconline.com/blog/post/2026/03/09/del-hc-issues-notice-cbis-challenge-to-discharge-delhi-excise-policy-case/',
    sourceLabel: 'SCC Online — Delhi HC issues notice on CBI’s challenge to discharge (9 Mar 2026)',
    sources: [
      'https://www.businesstoday.in/india/story/delhi-excise-policy-case-arvind-kejriwal-manish-sisodia-get-relief-cbi-to-approach-delhi-high-court-518293-2026-02-27',
      'https://www.socialnews.xyz/2026/08/17/delhi-hc-gives-kejriwal-sisodia-4-weeks-to-file-replies-on-cbi-plea-against-discharge-in-excise-policy-case',
    ],
  },
  {
    id: 'hst103',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Governance & Institutions',
    subtopic: 'CM residence, 6 Flagstaff Road — CAG audit',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2022,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      'A CAG audit found that rebuilding the Delhi chief minister’s residence at 6 Flagstaff Road rose from a ₹7.91 crore estimate to what final cost?',
    options: ['₹12.40 crore', '₹33.66 crore', '₹52.10 crore', '₹91.50 crore'],
    correctIndex: 1,
    explanation:
      'The audit, tabled by the BJP government on 23 Mar 2026, put the overrun at 342% and flagged a ‘doubtful’ choice of consultants, repeated estimate revisions and higher-specification items. The Assembly’s Public Accounts Committee called off a 14 Sept 2026 site visit, alleging its proceedings had been leaked and politicised.',
    otherSide:
      'AAP says the BJP lied about a pool, gold commodes and a bar at the bungalow, and dared the committee to take media cameras on its visit (Sept 2026).',
    sourceUrl: 'https://dailypioneer.com/news/cag-slams-inr-33-66-crore-renovation-of-kejriwal-s-bungalow',
    sourceLabel: 'The Pioneer — CAG slams ₹33.66 crore renovation of Kejriwal’s bungalow (24 Mar 2026)',
    sources: [
      'https://www.tribuneindia.com/news/delhi/common-man-or-conman-bjp-targets-kejriwal-over-cags-findings-on-cm-residence',
      'https://www.aninews.in/news/national/general-news/delhi-assembly-committee-to-visit-kejriwal8217s-former-residence-aap-challenges-bjp-over-8216sheesh-mahal8217-claims20260912230147/',
      'https://www.thehansindia.com/news/cities/new-delhi/breach-of-confidentiality-delhi-assemblys-public-accounts-committee-puts-off-sheesh-mahal-visit-1121923',
    ],
  },
  {
    id: 'hst104',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Welfare & Subsidies',
    subtopic: 'Free bus travel for women (pink ticket)',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2019,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      'Since 29 October 2019, women in Delhi have ridden public buses free using a single-journey ticket of what colour?',
    options: ['Green', 'Pink', 'Blue', 'Yellow'],
    correctIndex: 1,
    explanation:
      'The AAP government’s scheme issues a free ‘pink ticket’ for each ride on government-run buses. At launch about 8.5 lakh women were regular bus riders; earlier fares ran from ₹5 to ₹25. The rollout came with 13,000 bus marshals for safety.',
    sourceUrl: 'https://www.aljazeera.com/news/2019/10/29/pink-tickets-as-delhi-rolls-out-free-bus-travel-for-women',
    sourceLabel: 'Al Jazeera — Pink tickets as Delhi rolls out free bus travel for women (29 Oct 2019)',
    sources: ['https://www.thehindu.com/elections/delhi-assembly/delhi-assembly-elections-2020-aap-sweeps-delhi-with-62-seats/article30790189.ece'],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Arvind Kejriwal', role: 'Chief Minister, Delhi', party: 'AAP' }],
    outcome:
      'Rolled out on 29 Oct 2019 for about 8.5 lakh women who rode buses regularly, with 13,000 bus marshals; Delhi voted 102 days later, on 8 Feb 2020. AAP won 62 of 70 seats and the BJP 8.',
    poll: { label: 'Delhi Assembly 2020', month: '2020-02', gapDays: 102, result: 'AAP won 62 of 70 seats; BJP 8' },
  },
  {
    id: 'hst105',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Health',
    subtopic: 'Mohalla clinics — CAG audit',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2023,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      "A CAG audit of Delhi's health services, tabled in Feb 2025, found roughly what share of Mohalla Clinic patients got under one minute of consultation (Oct 2022–Mar 2023)?",
    options: ['About 10%', 'About 30%', 'About 50%', 'About 70%'],
    correctIndex: 3,
    explanation:
      'The audit also found only 523 of a planned 1,000 clinics running by March 2023, and among 74 sampled clinics 21 lacked toilets and 10 lacked drinking water. It was tabled by the new BJP government on 28 Feb 2025, weeks after AAP lost power; the clinics had been AAP’s flagship of free primary care.',
    sourceUrl: 'https://www.tribuneindia.com/news/delhi/cag-report-highlights-mohalla-clinic-vacancies-overcrowding-in-hospitals',
    sourceLabel: 'The Tribune — CAG report highlights mohalla clinic vacancies, overcrowding (Feb 2025)',
    sources: ['https://m.economictimes.com/news/india/keenly-awaited-cag-report-on-state-of-healthcare-in-delhi-tabled-in-assembly/articleshow/118625858.cms'],
  },
  {
    id: 'hst106',
    domain: 'civics',
    region: 'India',
    state: 'DL',
    topic: 'Welfare & Subsidies',
    subtopic: 'Mahila Samriddhi / Delhi Lakshmi Yojana',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Delhi's ₹2,500-a-month scheme for women, budgeted at ₹5,100 crore in March 2025 and promised in the BJP manifesto as the Mahila Samriddhi Yojana, has since been renamed. What is it called now?",
    options: ['Mahila Samman Yojana', 'Ladli Behna Yojana', 'Delhi Lakshmi Yojana', 'Lado Lakshmi Yojana'],
    correctIndex: 2,
    explanation:
      'The BJP government’s first budget (Mar 2025) set aside ₹5,100 crore. Registration for women aged 21–60 opened on 1 Aug 2026, some 16 months later; on 26 Aug the CM handed the first 4,190 sanction letters, with payments due from 1 Sept. Over 9 lakh women had registered by then.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/delhi/2025/Delhi_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Delhi Budget Analysis 2025-26',
    sources: [
      'https://www.thehindu.com/news/cities/Delhi/lakshmi-scheme-cm-hands-sanction-letters-to-over-4000-women/article71393989.ece',
      'https://www.socialnews.xyz/2026/07/28/delhi-women-to-register-for-rs-2500-scheme-from-aug-1',
    ],
    tags: ['distribution'],
    enactedBy: [{ name: 'Rekha Gupta', role: 'Chief Minister, Delhi', party: 'BJP' }],
  },

  // ───────────────────────────── PUNJAB ─────────────────────────────
  {
    id: 'hst107',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Health',
    subtopic: 'Health minister sacked over ‘1% commission’',
    kind: 'scam',
    difficulty: 'expert',
    year: 2022,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      'Punjab health minister Vijay Singla was sacked and arrested in May 2022 over an alleged 1% commission demand. What did Punjab Police file in the case in 2025?',
    options: [
      'A cancellation (closure) report',
      'A 40,000-page chargesheet',
      'A plea to transfer the case to the CBI',
      'An application to cancel his bail',
    ],
    correctIndex: 0,
    explanation:
      'CM Bhagwant Mann sacked him on 24 May 2022, and he was arrested the same day on a superintending engineer’s complaint; the HC bailed him in July 2022. In June 2025 police told a Mohali court his voice samples did not match and no concrete evidence of corruption was found; the complainant said he had no objection. Opposition parties called it a clean chit.',
    status:
      'Arrested 24 May 2022; on HC bail since 8 Jul 2022; police cancellation report filed 2 Jun 2025, Mohali court reserved its decision (no ruling found in sources checked, Sept 2026). Not convicted.',
    otherSide:
      'Police told the court his voice samples did not match and no concrete evidence of corruption was found; the complainant said he had no objection to the case being closed.',
    people: ['Vijay Singla', 'Bhagwant Mann'],
    sourceUrl:
      'https://theprint.in/india/punjab-police-files-closure-report-in-corruption-case-against-ex-minister-vijay-singla/2673929/',
    sourceLabel: 'ThePrint — Punjab Police files closure report in case against ex-minister Vijay Singla (Jun 2025)',
    sources: [
      'https://www.tribuneindia.com/news/punjab/graft-case-against-singla-dropped-as-voice-samples-didnt-match-cm',
      'https://www.tribuneindia.com/news/punjab/punjab-health-minister-sacked-on-corruption-charges-arrested-397807',
      'https://www.tribuneindia.com/news/punjab/sacked-punjab-health-minister-vijay-singla-granted-bail-by-punjab-and-haryana-high-court-410588',
    ],
  },
  {
    id: 'hst108',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Energy & Mining',
    subtopic: 'Power subsidy bill',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      'Per PRS, how much did Punjab budget for power subsidies in 2025-26 — about 18% of its revenue receipts?',
    options: ['₹4,500 crore', '₹9,800 crore', '₹20,500 crore', '₹41,000 crore'],
    correctIndex: 2,
    explanation:
      'PRS puts it at ₹20,500 crore, 1.5% above 2024-25; in 2023-24 Punjab spent ₹18,177 crore (20% of revenue receipts). The state itself calls rising power subsidies a concern, and the 15th Finance Commission linked Punjab’s long-term finances to rationalising free farm power.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/punjab/2025/Punjab_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Punjab Budget Analysis 2025-26',
    tags: ['distribution'],
    enactedBy: [{ name: 'Harpal Singh Cheema', role: 'Finance Minister, Punjab (presented the 2025-26 budget)', party: 'AAP' }],
  },
  {
    id: 'hst109',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Banking & Finance',
    subtopic: 'State debt',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'AAP',
    question: "Punjab's outstanding debt at the end of 2025-26 was budgeted at about what share of its GSDP, according to PRS?",
    options: ['About 25%', 'About 44.5%', 'About 33%', 'About 60%'],
    correctIndex: 1,
    explanation:
      'PRS: 44.5% of GSDP, marginally below the 44.8% revised estimate for 2024-25; the state also repays ₹89,449 crore of old debt in 2025-26. For comparison PRS puts Haryana at 26.2% and Himachal Pradesh at 40.5% for the same year.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/punjab/2025/Punjab_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Punjab Budget Analysis 2025-26',
  },
  {
    id: 'hst110',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Governance & Institutions',
    subtopic: 'Disproportionate assets case against ex-minister',
    kind: 'scam',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'Other',
    question:
      'Akali Dal leader Bikram Singh Majithia, arrested by the Punjab Vigilance Bureau in June 2025, was booked in what kind of case?',
    options: [
      'Electoral bond fraud',
      'Illegal sand mining',
      'Criminal defamation',
      'Disproportionate assets (corruption law)',
    ],
    correctIndex: 3,
    explanation:
      'The Vigilance Bureau alleges about ₹540 crore of wealth amassed over a 2007–2017 check period, when he was an MLA and for some years a minister, and filed a 40,000-page chargesheet in Aug 2025. The Supreme Court granted bail on 2 Feb 2026 after seven months in custody.',
    status:
      'FIR 2025 under the Prevention of Corruption Act; arrested 25 Jun 2025; chargesheeted Aug 2025; on bail (Supreme Court, 2 Feb 2026); trial pending, no charges framed in sources checked (Sept 2026). Not convicted; his counsel calls it political vendetta.',
    otherSide:
      'His counsel told the Supreme Court the case is political vendetta, with 295 witnesses and no prospect of the trial ending soon (Feb 2026).',
    people: ['Bikram Singh Majithia'],
    sourceUrl: 'https://www.tribuneindia.com/news/punjab/bikram-majithia-akali-ex-minister-granted-bail-in-disproportionate-assets-case/',
    sourceLabel: 'The Tribune — SC grants bail to Akali leader Bikram Majithia (Feb 2026)',
    sources: [
      'https://www.newsonair.gov.in/punjab-vigilance-bureau-arrests-sad-leader-bikram-singh-majithia-in-da-case',
      'https://www.newsonair.gov.in/punjab-vigilance-bureau-files-40000-page-charge-sheet-against-sad-leader-bikram-singh-majithia',
    ],
  },
  {
    id: 'hst111',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Health',
    subtopic: 'Mukh Mantri Sehat Yojana',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'AAP',
    question:
      "Punjab's Mukh Mantri Sehat Yojana, cleared in July 2025 for every resident, offers cashless treatment of up to how much per family per year?",
    options: ['₹1 lakh', '₹5 lakh', '₹10 lakh', '₹25 lakh'],
    correctIndex: 2,
    explanation:
      'The cabinet cleared it on 10 Jul 2025 with no income test, replacing an income-based ₹5 lakh cover, and the 2025-26 budget gave it ₹778 crore. The planned 2 Oct 2025 start slipped: it was rolled out on 22 Jan 2026 for all 65 lakh families in the state.',
    sourceUrl: 'https://www.tribuneindia.com/news/punjab/punjab-cabinet-gives-nod-to-scheme-providing-rs-10-lakh-health-cover-to-all-families',
    sourceLabel: 'The Tribune — Punjab Cabinet gives nod to ₹10 lakh health cover for all families (Jul 2025)',
    sources: ['https://theprint.in/india/punjab-kejriwal-mann-roll-out-mukh-mantri-sehat-yojna-free-cashless-treatment-up-to-rs-10-lakh/2833772/'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Bhagwant Mann', role: 'Chief Minister, Punjab', party: 'AAP' }],
  },
  {
    id: 'hst112',
    domain: 'civics',
    region: 'India',
    state: 'PB',
    topic: 'Governance & Institutions',
    subtopic: 'Anti-drug campaign',
    kind: 'institution',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'AAP',
    question: "What is the name of the Punjab Police's statewide anti-drug drive launched on 1 March 2025?",
    options: ['Yudh Nashian Virudh', 'Operation Seal', 'Operation Clean Punjab', 'Nasha Mukt Bharat Abhiyaan'],
    correctIndex: 0,
    explanation:
      'On day one more than 8,000 police in 900 teams raided about 800 places, arresting 290 alleged smugglers and registering 230-plus FIRs, according to All India Radio. Arrest counts are the government’s own figures; convictions come much later, if at all.',
    sourceUrl: 'https://www.newsonair.gov.in/punjab-police-launch-drive-against-drug-menace-on-war-footing-yudh-nasheyan-virudh',
    sourceLabel: 'All India Radio — Punjab police launch drive against drug menace on war footing (1 Mar 2025)',
  },

  // ───────────────────────────── HARYANA ─────────────────────────────
  {
    id: 'hst113',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Environment & Land',
    subtopic: 'Manesar land case',
    kind: 'scam',
    difficulty: 'expert',
    year: 2007,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "The CBI's Manesar case alleges farmers sold land cheaply under threat of acquisition, after which an order of 24 August 2007 released it to builders. Which party ran Haryana when that order was passed?",
    options: ['INLD', 'INC', 'BJP', 'JJP'],
    correctIndex: 1,
    explanation:
      'The acquisition notice for 912 acres came in Aug 2004; the CBI alleges landowners in three villages then sold at ₹20–25 lakh an acre, a loss of about ₹1,500 crore, before the 2007 release. It chargesheeted ex-CM Bhupinder Singh Hooda and others in 2018. Charges were framed against other accused and firms in Jan 2026.',
    status:
      'CBI chargesheet 2018; Supreme Court stayed proceedings against Hooda (17 Nov 2025), so no charges framed against him; trial of other accused and firms under way from 2026. Not convicted.',
    otherSide:
      'Hooda says the matter is sub judice and he has complete faith in the judiciary; the Supreme Court has stayed the proceedings against him.',
    people: ['Bhupinder Singh Hooda'],
    sourceUrl:
      'https://www.tribuneindia.com/news/haryana/what-is-manesar-land-scam-and-why-cbi-court-has-decided-to-start-trial-in-case/',
    sourceLabel: 'The Tribune — What is Manesar land scam and why CBI court decided to start trial (Jan 2026)',
    sources: ['https://theprint.in/india/hc-dismisses-hoodas-plea-for-postponing-trial-proceedings-in-manesar-land-deal-case/2779387/'],
  },
  {
    id: 'hst114',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Education & Exams',
    subtopic: 'Cash-for-marks recruitment case',
    kind: 'scam',
    difficulty: 'expert',
    year: 2021,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Haryana's Vigilance Bureau arrested an HPSC deputy secretary in Nov 2021 over alleged bribes to raise marks in a dental-surgeon recruitment test. About how much cash did the state say had been seized?",
    options: ['₹3.5 crore', '₹35 lakh', '₹35 crore', '₹350 crore'],
    correctIndex: 0,
    explanation:
      'The dismissal order said ₹2.10 crore of it came from an associate and that HCS-2021 prelims answer sheets were also allegedly tampered with. The BJP-JJP government sacked the officer in Dec 2021; the Congress demanded a probe monitored by the High Court’s chief justice. The ED later brought a linked money-laundering case.',
    status:
      'Arrested Nov 2021 and dismissed Dec 2021; in ED custody in the linked money-laundering case from Dec 2023 until the High Court granted regular bail (21 Nov 2024); trial pending. Not convicted.',
    otherSide:
      'The officer told the court part of the seized cash was an HPSC secret fund for interviews, and that police had not shown who paid or benefited from any bribe (2022).',
    sourceUrl: 'https://theprint.in/india/haryana-deputy-secy-anil-nagar-sacked-in-dental-surgeon-recruitment-exam-scam/778045/',
    sourceLabel: 'ThePrint — Haryana deputy secy sacked in dental surgeon recruitment exam scam (7 Dec 2021)',
    sources: [
      'https://timesofindia.indiatimes.com/city/chandigarh/hpsc-cash-for-job-scam-bail-granted-to-key-accused-anil-nagar/articleshow/115543324.cms',
      'https://timesofindia.indiatimes.com/city/chandigarh/money-seized-was-haryana-public-service-commission-secret-fund-claims-anil-nagar/articleshow/90258585.cms',
    ],
  },
  {
    id: 'hst115',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Welfare & Subsidies',
    subtopic: 'Deendayal Lado Lakshmi Yojana',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Haryana's Deendayal Lado Lakshmi Yojana, launched on 25 September 2025, pays each eligible woman how much a month?",
    options: ['₹1,000', '₹1,500', '₹2,500', '₹2,100'],
    correctIndex: 3,
    explanation:
      'It covers women aged 23–60 in families earning up to ₹1 lakh a year — about 20 lakh women in phase one — and any number of eligible women in one household can claim it. The 2025-26 budget set aside ₹5,000 crore for it.',
    sourceUrl:
      'https://www.tribuneindia.com/news/haryana/cm-nayab-saini-launches-deendayal-lado-lakshmi-yojana-eligible-women-to-receive-rs-2100-monthly',
    sourceLabel: 'The Tribune — CM Nayab Saini launches Deendayal Lado Lakshmi Yojana (25 Sep 2025)',
    sources: ['https://prsindia.org/files/budget/budget_state/haryana/2025/Haryana_Budget_Analysis_2025-26.pdf'],
    tags: ['distribution'],
    enactedBy: [{ name: 'Nayab Singh Saini', role: 'Chief Minister, Haryana', party: 'BJP' }],
  },
  {
    id: 'hst116',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Banking & Finance',
    subtopic: 'Interest burden',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'BJP',
    question: "Per PRS, what share of Haryana's 2025-26 revenue receipts goes to interest payments alone?",
    options: ['About 5%', 'About 12%', 'About 21%', 'About 35%'],
    correctIndex: 2,
    explanation:
      'PRS: ₹26,231 crore of interest, or 21% of revenue receipts; with salaries (25%) and pensions (13%), 58% is committed before any new spending. Outstanding debt is budgeted at 26.2% of GSDP at the end of 2025-26.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/haryana/2025/Haryana_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Haryana Budget Analysis 2025-26',
  },
  {
    id: 'hst117',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Farm & Food',
    subtopic: 'Mera Pani Meri Viraasat',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Haryana's 2025-26 budget raised the per-acre payment to farmers who give up paddy under ‘Mera Pani, Meri Viraasat’ from ₹7,000 to what?",
    options: ['₹7,500', '₹8,000', '₹10,000', '₹12,000'],
    correctIndex: 1,
    explanation:
      'PRS records the rise to ₹8,000 an acre, and the subsidy for direct sowing of paddy going from ₹4,000 to ₹4,500 an acre. The scheme pays farmers to switch away from water-guzzling paddy.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/haryana/2025/Haryana_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Haryana Budget Analysis 2025-26',
    tags: ['distribution'],
    enactedBy: [{ name: 'Nayab Singh Saini', role: 'Chief Minister, Haryana (presented the 2025-26 budget)', party: 'BJP' }],
  },
  {
    id: 'hst118',
    domain: 'civics',
    region: 'India',
    state: 'HR',
    topic: 'Education & Exams',
    subtopic: 'HPSC assistant professor (English) results',
    kind: 'institution',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "In November 2025 how many candidates cleared the Haryana Public Service Commission's subject test for 613 English assistant-professor vacancies?",
    options: ['613', '1,226', '2,400', '151'],
    correctIndex: 3,
    explanation:
      'About 2,400 candidates who had cleared the June prelims sat the test on 17 Aug 2025; many NET/JRF-qualified candidates, including gold medallists, missed the 35% minimum and protested. The HPSC secretary said the examination process was robust and marks were given transparently. The drive covered 2,424 posts in 26 subjects.',
    sourceUrl:
      'https://theprint.in/india/education/why-did-haryanas-brightest-fail-hpscs-assistant-professor-exams-an-evaluation-or-education-debate/2799991/',
    sourceLabel: 'ThePrint — Why did Haryana’s brightest fail HPSC’s assistant professor exams? (Dec 2025)',
  },

  // ───────────────────────────── HIMACHAL PRADESH ─────────────────────────────
  {
    id: 'hst119',
    domain: 'civics',
    region: 'India',
    state: 'HP',
    topic: 'Welfare & Subsidies',
    subtopic: 'Old Pension Scheme restored',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2023,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "In January 2023 Himachal's new Congress government decided to move about 1.36 lakh employees from the National Pension System back to what?",
    options: ['The Old Pension Scheme', 'The Unified Pension Scheme', 'Atal Pension Yojana', 'A state provident fund'],
    correctIndex: 0,
    explanation:
      'The OPS was a 2022 poll promise. The CM said affordability would come from financial discipline, and blamed the previous BJP government for leaving debt of over ₹75,000 crore plus salary and pension arrears. By 2025-26 pensions alone took 28% of the state’s revenue receipts (PRS).',
    sourceUrl:
      'https://www.thehindu.com/news/national/other-states/himachal-pradesh-decides-to-restores-ops-for-its-employees/article66373793.ece',
    sourceLabel: 'The Hindu — Himachal Pradesh decides to restore OPS for its employees (13 Jan 2023)',
    tags: ['pre-election'],
    sources: ['https://www.livemint.com/elections/assembly-elections/election-results-2022-bjp-sets-gujarat-record-congress-wins-himachal-pradesh-11670495701908.html'],
    enactedBy: [{ name: 'Sukhvinder Singh Sukhu', role: 'Chief Minister, Himachal Pradesh', party: 'INC' }],
    outcome:
      'A Congress campaign promise for the 12 Nov 2022 poll, which it won with 40 of 68 seats. The cabinet restored the OPS on 13 Jan 2023; the CM said it would benefit over 1.36 lakh NPS employees.',
    poll: { label: 'Himachal Assembly 2022', month: '2022-11', result: 'Congress won 40 of 68 seats; BJP 25' },
  },
  {
    id: 'hst120',
    domain: 'civics',
    region: 'India',
    state: 'HP',
    topic: 'Banking & Finance',
    subtopic: 'Salary and pension dates shifted',
    kind: 'spend',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'In September 2024, amid a cash crunch, Himachal Pradesh moved the monthly payment of salaries and pensions to which days of the month?',
    options: ['1st and 5th', '5th and 10th', '7th and 15th', '10th and 20th'],
    correctIndex: 1,
    explanation:
      'The CM told the Assembly that the Centre’s ₹520 crore revenue deficit grant arrives on the 6th and the ₹740 crore tax share on the 10th, so paying on the 1st forced costly advance borrowing at about 7.5%. The change would save about ₹3 crore a month. The BJP opposition raised the delayed salaries in the House.',
    sourceUrl:
      'https://www.thehindu.com/news/national/himachal-pradesh/himachal-govt-to-pay-employee-salaries-on-5th-pension-on-10th-per-month-for-fiscal-prudence/article68605272.ece',
    sourceLabel: 'The Hindu — Himachal govt to pay salaries on 5th, pension on 10th (4 Sep 2024)',
  },
  {
    id: 'hst121',
    domain: 'civics',
    region: 'India',
    state: 'HP',
    topic: 'Banking & Finance',
    subtopic: '2026-27 budget after RDG ended',
    kind: 'spend',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Presenting a smaller ₹54,928-crore budget for 2026-27 after the Centre's Revenue Deficit Grant ended, Himachal deferred what share of the CM's own salary for six months?",
    options: ['20%', '30%', '50%', '100%'],
    correctIndex: 2,
    explanation:
      'The CM said ending the grant costs the state about ₹8,105 crore a year; Himachal got ₹48,630 crore as RDG in 2020-21 to 2025-26. Ministers’ pay was deferred 30%, MLAs’ 20%, and top officers’ 20–30%. He blamed the previous government’s management as well as the grant’s end.',
    sourceUrl:
      'https://www.thehindu.com/news/national/himachal-pradesh/himachal-cm-sukhu-presents-54928-crore-budget-for-2026-27/article70768571.ece',
    sourceLabel: 'The Hindu — RDG discontinuation fallout: Himachal presents ‘reduced’ budget (21 Mar 2026)',
  },
  {
    id: 'hst122',
    domain: 'civics',
    region: 'India',
    state: 'HP',
    topic: 'Energy & Mining',
    subtopic: 'Seli hydro dues — attachment order',
    kind: 'spend',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'In November 2024 the Himachal Pradesh High Court ordered attachment of which state-owned property in Delhi, over dues owed to a hydropower company?',
    options: ['Himachal Sadan', 'HP Tourism reception centre', 'Himachal Emporium', 'Himachal Bhawan'],
    correctIndex: 3,
    explanation:
      'The court allowed the firm to seek auction of Himachal Bhawan at Mandi House to recover about ₹150 crore. The 340 MW Seli project, allotted in 2009, never came up; the state forfeited the ₹64 crore upfront premium, but an arbitrator ordered it refunded with interest and the state had not paid. No later ruling was found in sources checked (Sept 2026).',
    otherSide:
      'The Chief Minister said the ₹64 crore was forfeited under the 2006 hydro policy, that the refund was an arbitrator’s decision the state had challenged, and that it would examine the order.',
    sources: ['https://www.tribuneindia.com/news/himachal/will-examine-high-court-order-says-cm-sukhu-as-he-faces-heat-over-himachal-bhawan-attachment/amp'],
    sourceUrl:
      'https://www.thehindu.com/news/national/himachal-pradesh/hc-orders-attachment-of-delhis-himachal-bhawan-after-hp-govt-fails-to-clear-dues-of-power-firm/article68885313.ece',
    sourceLabel: 'The Hindu — HC orders attachment of Delhi’s Himachal Bhawan (19 Nov 2024)',
  },
  {
    id: 'hst123',
    domain: 'civics',
    region: 'India',
    state: 'HP',
    topic: 'Education & Exams',
    subtopic: 'Scholarship scam',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2017,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "In March 2024 the CBI chargesheeted 20 institutions and 105 people in Himachal's alleged scholarship scam. About what value of allegedly fake claims (2013–2017) did its case cite?",
    options: ['About ₹18 crore', 'About ₹181 crore', 'About ₹81 crore', 'About ₹1,810 crore'],
    correctIndex: 1,
    explanation:
      'The CBI case (2019, on the state’s request) says about 80% of the money went to private institutions while about 32,000 students did not get their scholarships; 19 people, including institute heads, bank staff and education officials, were arrested. It surfaced when students in Spiti went unpaid for five years.',
    status:
      'CBI case 2019; chargesheets against 20 institutions and 105 persons (Mar 2024); linked ED money-laundering case continuing (Supreme Court cancelled an accused institute chairman’s anticipatory bail, 16 Jul 2026); trials pending; no conviction reported (Sept 2026).',
    otherSide:
      'An accused institute chairman told the courts he had cooperated with the probe since 2019; the Supreme Court still set aside his anticipatory bail (Jul 2026). None of the accused has been convicted.',
    sources: ['https://www.livelawbiz.com/top-stories/supreme-court-sets-aside-anticipatory-bail-granted-to-hgpi-chairman-in-post-matric-scholarship-scam-pmla-case-541499'],
    sourceUrl:
      'https://www.thehindu.com/news/national/himachal-pradesh/himachal-multi-crore-scholarship-scam-cbi-files-charge-sheet-against-20-institutes-105-individuals/article68005966.ece',
    sourceLabel: 'The Hindu — Himachal scholarship scam: CBI files charge sheet against 20 institutes, 105 individuals (29 Mar 2024)',
    tags: ['distribution'],
  },
  {
    id: 'hst124',
    domain: 'civics',
    region: 'India',
    state: 'HP',
    topic: 'Banking & Finance',
    subtopic: 'Committed expenditure',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Per PRS, what share of Himachal's 2025-26 revenue receipts is committed to salaries, pensions and interest before any other spending?",
    options: ['About 42%', 'About 58%', 'About 83%', 'About 97%'],
    correctIndex: 2,
    explanation:
      'PRS: ₹35,222 crore, or 83% — salaries 39%, pensions 28%, interest 16% (81% in 2023-24). Outstanding debt is estimated at 40.5% of GSDP. For contrast, PRS puts Jharkhand’s committed share at 29% and Haryana’s at 58%.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/himachal-pradesh/2025/HP_State_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Himachal Pradesh Budget Analysis 2025-26',
  },

  // ───────────────────────────── UTTAR PRADESH ─────────────────────────────
  {
    id: 'hst125',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Education & Exams',
    subtopic: 'Police constable exam leak',
    kind: 'scam',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'The UP Police constable exam of 17–18 February 2024, cancelled after paper-leak allegations, was held to fill how many posts?',
    options: ['26,382', '32,679', '1,20,000', '60,244'],
    correctIndex: 3,
    explanation:
      'The state cancelled the exam in February and re-held it over five days in August 2024, with about 5 lakh candidates a shift. The ED alleges the same accused also leaked a second state recruitment paper and used those proceeds to fund this leak; it filed a supplementary chargesheet against 18 accused in Jan 2026.',
    status:
      'Exam cancelled Feb 2024 and re-held Aug 2024; STF FIR Mar 2024; ED prosecution complaints Jan 2025 (7 accused, under trial) and Jan 2026 (18 accused); no conviction reported (Sept 2026).',
    otherSide:
      'The state cancelled and re-held the exam with free bus travel for candidates, and in July 2024 notified an anti-leak ordinance allowing life terms and fines of up to ₹1 crore.',
    sourceUrl: 'https://theprint.in/india/cancelled-over-paper-leak-up-police-constable-re-exam-now-in-august/2190854/',
    sourceLabel: 'ThePrint (PTI) — Cancelled over paper leak, UP police constable re-exam now in August (25 Jul 2024)',
    sources: [
      'https://www.hindustantimes.com/cities/lucknow-news/up-police-ro-aro-paper-leak-cases-enforcement-directorate-files-supplementary-charge-sheet-against-18-accused-under-pmla-101768418602170.html',
    ],
  },
  {
    id: 'hst126',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Education & Exams',
    subtopic: 'UPPSC RO/ARO exam cancelled',
    kind: 'scam',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'Which UPPSC recruitment exam, held on 11 February 2024, did the UP government cancel on 2 March 2024 over an alleged leak, promising a re-test within six months?',
    options: [
      'Review Officer / Assistant Review Officer',
      'Combined State Upper Subordinate (PCS) prelims',
      'Lower Subordinate Services',
      'Staff Nurse (Allopathy)',
    ],
    correctIndex: 0,
    explanation:
      'The chief minister ordered the cancellation after the question paper allegedly circulated on social media, and the UP Police Special Task Force was asked to investigate. It came days after the constable exam was scrapped for the same reason.',
    status:
      'Exam cancelled 2 Mar 2024; STF investigation; ED prosecution complaints Jan 2025 (under trial) and Jan 2026 (18 accused), jointly with the police constable leak; no conviction reported (Sept 2026).',
    otherSide:
      'The government said it cancelled both sessions on evidence it had publicly invited and the commission’s own report, and ordered a re-test within six months.',
    sourceUrl: 'https://theprint.in/india/up-govt-cancels-ro-aro-exam-over-paper-leak/1986280/',
    sourceLabel: 'ThePrint (PTI) — UP govt cancels RO/ARO exam over paper leak (2 Mar 2024)',
    sources: [
      'https://www.hindustantimes.com/cities/lucknow-news/up-police-ro-aro-paper-leak-cases-enforcement-directorate-files-supplementary-charge-sheet-against-18-accused-under-pmla-101768418602170.html',
    ],
  },
  {
    id: 'hst127',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Infrastructure',
    subtopic: 'Gomti riverfront project',
    kind: 'scam',
    difficulty: 'simple',
    year: 2016,
    asOf: '2026-09',
    govt: 'SP',
    question:
      "Lucknow's Gomti riverfront project (2014–17), pegged at ₹1,513 crore and probed by the CBI since 2017, was carried out under which state government?",
    options: ['BSP government', 'Samajwadi Party government', 'BJP government', "President's Rule"],
    correctIndex: 1,
    explanation:
      'The CBI’s 2021 case names 17 irrigation officials and 172 others, alleging tenders were not advertised and forged bids made up the quorum; ₹1,437 crore had been spent. Its first chargesheet (Feb 2021) named two officials and four private parties. The probe began after the BJP took office in 2017; no politician has been chargesheeted in these filings.',
    status:
      'CBI cases registered Nov 2017 and Jul 2021; first chargesheet Feb 2021 against two officials and private parties; trial and further probe pending; no politician charged (Sept 2026).',
    otherSide:
      'No politician has been charged: the CBI’s filings name irrigation officials, firms and their owners. No reply from the Samajwadi Party to the probe was found in sources checked (Sept 2026).',
    sourceUrl:
      'https://www.thehindu.com/news/national/other-states/cbi-registers-fresh-case-in-gomti-river-front-project-irregularities-searches-at-over-40-locations/article35142515.ece',
    sourceLabel: 'The Hindu — Gomti project: CBI conducts raids in 40 locations (5 Jul 2021)',
    sources: ['https://www.thehindu.com/news/national/cbi-files-chargesheet-in-gomti-river-front-project-case/article33866155.ece'],
  },
  {
    id: 'hst128',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Infrastructure',
    subtopic: 'Ganga Expressway cost',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2026,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'The 594-km Ganga Expressway from Meerut to Prayagraj, inaugurated on 29 April 2026, cost about how much?',
    options: ['₹12,839 crore', '₹23,349 crore', '₹36,230 crore', '₹58,000 crore'],
    correctIndex: 2,
    explanation:
      'Built by UPEIDA as a six-lane road through 12 districts. For scale: the 341-km Purvanchal Expressway cost ₹23,349 crore and the 296-km Bundelkhand Expressway ₹14,849 crore. The Yamuna Expressway (166 km) cost ₹12,839 crore.',
    sourceUrl: 'https://theprint.in/india/as-ganga-joins-yamuna-expressways-set-to-drive-ups-economy-and-politics-ahead-of-2027/2926661/',
    sourceLabel: 'ThePrint — As Ganga joins Yamuna, expressways set to drive UP’s economy and politics (May 2026)',
  },
  {
    id: 'hst129',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Banking & Finance',
    subtopic: 'State budget 2025-26',
    kind: 'spend',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'BJP',
    question: "Per PRS, about how much did UP's 2025-26 budget estimate it would spend, excluding debt repayment?",
    options: ['About ₹1.5 lakh crore', 'About ₹3.8 lakh crore', 'About ₹12 lakh crore', 'About ₹7.6 lakh crore'],
    correctIndex: 3,
    explanation:
      'PRS: ₹7,57,333 crore, up 17%, plus ₹51,403 crore of debt repayment. UP budgets a revenue surplus of 2.6% of GSDP, and salaries, pensions and interest take 50% of its revenue receipts.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/uttar-pradesh/2025/UP_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Uttar Pradesh Budget Analysis 2025-26',
  },
  {
    id: 'hst130',
    domain: 'civics',
    region: 'India',
    state: 'UP',
    topic: 'Infrastructure',
    subtopic: 'Ganga Expressway rain damage',
    kind: 'spend',
    difficulty: 'simple',
    year: 2026,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      'About four months after its inauguration, a stretch of the Ganga Expressway was reported caved in after heavy rain on 1 September 2026. In which district?',
    options: ['Unnao', 'Hardoi', 'Meerut', 'Prayagraj'],
    correctIndex: 0,
    explanation:
      'A pit about seven feet deep opened near the Basiratganj toll plaza; it was the second reported damage in the district that monsoon. UPEIDA said repairs began at once. The opposition Samajwadi Party mocked it as the country’s ‘first express waterway’.',
    sourceUrl: 'https://theprint.in/india/rain-damages-ganga-expressway-in-unnao-akhilesh-takes-dig-at-up-govt/3031298/',
    sourceLabel: 'ThePrint (PTI) — Rain damages Ganga Expressway in Unnao (1 Sep 2026)',
  },

  // ───────────────────────────── UTTARAKHAND ─────────────────────────────
  {
    id: 'hst131',
    domain: 'civics',
    region: 'India',
    state: 'UT',
    topic: 'Education & Exams',
    subtopic: 'Anti-cheating law 2023',
    kind: 'institution',
    difficulty: 'expert',
    year: 2023,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "Uttarakhand's anti-cheating law, first brought in by ordinance in February 2023 after recruitment-exam leaks, allows fines of up to how much for those leaking or selling papers?",
    options: ['₹10 lakh', '₹1 crore', '₹10 crore', '₹100 crore'],
    correctIndex: 2,
    explanation:
      'The Governor signed the ordinance on 10 Feb 2023 and it was later passed as an Act; it also allows life imprisonment. It followed a 2022 leak in a UKSSSC graduate-level exam affecting over a lakh aspirants. Another UKSSSC exam was hit by an alleged leak in Sept 2025; the CM said over 100 people had been arrested in exam-cheating cases since 2022.',
    sourceUrl:
      'https://theprint.in/india/another-exam-another-leak-uttarakhand-cant-plug-gaps-despite-anti-cheating-law-uksssc-stir-spills-over/2750820/',
    sourceLabel: 'ThePrint — Another exam, another leak: Uttarakhand can’t plug gaps despite anti-cheating law (Sep 2025)',
  },
  {
    id: 'hst132',
    domain: 'civics',
    region: 'India',
    state: 'UT',
    topic: 'Education & Exams',
    subtopic: 'UKSSSC exam of 21 Sept 2025',
    kind: 'scam',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "After three pages allegedly leaked from a Haridwar centre, what happened to the UKSSSC's 21 September 2025 graduate-level exam for 416 posts?",
    options: [
      'It was cancelled in October 2025',
      'Its result was declared on schedule',
      'Only the Haridwar centre was re-tested',
      'It was handed over to the UPSC',
    ],
    correctIndex: 0,
    explanation:
      'More than one lakh candidates had appeared. After weeks of protests by the Uttarakhand Unemployed Union, the state recommended a CBI probe, and on 11 Oct 2025 the commission cancelled the exam, promising a re-test within three months.',
    status:
      'Exam cancelled 11 Oct 2025; CBI took over and chargesheeted three accused; special CBI court found sufficient grounds to frame charges (Aug 2026); trial pending. No conviction.',
    otherSide:
      'The commission cancelled the exam and the state sought a CBI probe; one of the three accused argued in court she did not know an exam was under way, but the judge found grounds to proceed.',
    sources: ['https://timesofindia.indiatimes.com/city/dehradun/court-finds-sufficient-grounds-to-frame-charges-against-3-uksssc-paper-leak-accused/articleshow/133189276.cms'],
    sourceUrl:
      'https://www.thehindu.com/news/national/uttarakhand/paper-leak-uttarakhand-cancels-graduate-level-recruitment-examination-to-be-held-within-three-months/article70151741.ece',
    sourceLabel: 'The Hindu — ‘Paper leak’: Uttarakhand cancels graduate-level recruitment examination (11 Oct 2025)',
  },
  {
    id: 'hst133',
    domain: 'civics',
    region: 'India',
    state: 'UT',
    topic: 'Education & Exams',
    subtopic: '2016 UKSSSC village-officer exam',
    kind: 'scam',
    difficulty: 'expert',
    year: 2016,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Uttarakhand's STF, probing the March 2016 UKSSSC exam for village panchayat development officers, said a forensic lab confirmed what?",
    options: [
      'The question paper was leaked on WhatsApp',
      'Candidates used Bluetooth earpieces',
      'Admit cards were forged in bulk',
      'OMR answer sheets were tampered with',
    ],
    correctIndex: 3,
    explanation:
      'The exam and its results came in March 2016; a panel found irregularities in 2017 and the case went to vigilance in 2019 and the STF in 2022. In Oct 2022 the STF arrested the then commission chairman, a retired forest officer, and the then secretary, at whose house OMR scanning was allegedly done. The BJP government called it zero tolerance.',
    status:
      'Arrests by the STF in Oct 2022 (incl. the then chairman and secretary); case pending in court; no later ruling found in sources checked (Sept 2026). Not convicted.',
    otherSide:
      'No public response from the arrested former commission officials was found in sources checked (Sept 2026); none has been convicted.',
    sourceUrl:
      'https://www.thehindu.com/news/national/other-states/retd-indian-forest-service-officer-arrested-in-uttarakhand-state-service-board-recruitment-scam/article65985763.ece',
    sourceLabel: 'The Hindu — Retd. IFS officer arrested in Uttarakhand recruitment scam (8 Oct 2022)',
  },
  {
    id: 'hst134',
    domain: 'civics',
    region: 'India',
    state: 'UT',
    topic: 'Environment & Land',
    subtopic: 'Joshimath subsidence',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2023,
    asOf: '2026-09',
    govt: 'BJP',
    question: 'When land subsidence hit Joshimath in January 2023, about how many structures developed cracks?',
    options: ['About 68', 'About 868', 'About 2,600', 'About 8,680'],
    correctIndex: 1,
    explanation:
      '181 structures were declared unsafe. By mid-2023 officials said ₹26 crore in compensation had reached 118 families and ₹1 lakh immediate relief 324 families, while residents said payouts fell short of relocation costs. Hydropower tunnelling, unchecked construction and loose soil were among causes cited.',
    sourceUrl: 'https://theprint.in/india/six-months-on-fresh-sinkhole-revives-fears-of-subsidence-in-joshimath/1657087/',
    sourceLabel: 'ThePrint — Six months on, fresh sinkhole revives fears of subsidence in Joshimath (2023)',
    tags: ['relief'],
  },
  {
    id: 'hst135',
    domain: 'civics',
    region: 'India',
    state: 'UT',
    topic: 'Infrastructure',
    subtopic: 'Silkyara tunnel collapse',
    kind: 'spend',
    difficulty: 'simple',
    year: 2023,
    asOf: '2026-09',
    govt: 'BJP',
    question:
      "For about how long were 41 workers trapped in Uttarakhand's collapsed Silkyara road tunnel before all were rescued on 28 November 2023?",
    options: ['About 4 days', 'About 40 days', 'About 17 days', 'About 3 months'],
    correctIndex: 2,
    explanation:
      'A section collapsed on 12 Nov 2023. Rat-hole mining experts dug through the last stretch of rubble, and all 41 were brought out on the 17th day of a multi-agency operation.',
    sourceUrl: 'https://theprint.in/india/all-41-workers-rescued-from-collapsed-silkyara-tunnel/1862757/',
    sourceLabel: 'ThePrint (PTI) — All 41 workers rescued from collapsed Silkyara tunnel (28 Nov 2023)',
  },
  {
    id: 'hst136',
    domain: 'civics',
    region: 'India',
    state: 'UT',
    topic: 'Banking & Finance',
    subtopic: 'State debt and committed spending',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'BJP',
    question: "PRS estimates Uttarakhand's outstanding debt at the end of 2025-26 at about what share of its GSDP?",
    options: ['About 25%', 'About 44%', 'About 51%', 'About 12%'],
    correctIndex: 0,
    explanation:
      'PRS: 25% of GSDP, up from a 24% budget estimate for 2024-25 — just below Haryana (26.2%) and Jharkhand (27%). But 60% of Uttarakhand’s revenue receipts are committed to salaries (33%), pensions (16%) and interest (11%).',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/uttarakhand/2025/Uttarakhand_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Uttarakhand Budget Analysis 2025-26',
  },

  // ───────────────────────────── JAMMU & KASHMIR ─────────────────────────────
  {
    id: 'hst137',
    domain: 'civics',
    region: 'India',
    state: 'JK',
    topic: 'Governance & Institutions',
    subtopic: 'Article 370 — Supreme Court verdict',
    kind: 'institution',
    difficulty: 'simple',
    year: 2023,
    asOf: '2026-09',
    govt: "President's Rule",
    question:
      'In December 2023 a five-judge Supreme Court bench ruled on the August 2019 abrogation of Article 370. What was the outcome?',
    options: ['Struck down 3–2', 'Referred to a seven-judge bench', 'Upheld unanimously', 'Upheld 3–2'],
    correctIndex: 2,
    explanation:
      'The Constitution Bench held that the President could notify that Article 370 ceases to operate, a move that also split the state into two Union Territories. The Union Home Minister promised statehood without a timeline; it had still not been restored in Sept 2026, when the Assembly took up a second resolution seeking it.',
    sourceUrl:
      'https://www.thehindu.com/news/national/sc-upholds-abrogation-of-article-370-says-move-was-part-of-70-year-old-exercise-to-integrate-jk-to-the-union/article67626914.ece',
    sourceLabel: 'The Hindu — SC upholds abrogation of Article 370 (11 Dec 2023)',
    sources: [
      'https://www.thehindu.com/elections/jammu-and-kashmir-assembly/after-decisive-mandate-governance-challenges-likely-for-nc-congress-alliance-in-jk-as-key-administrative-powers-remain-with-the-l-g/article68733481.ece',
      'https://www.hindustantimes.com/cities/chandigarh-news/autumn-session-omar-moves-resolution-in-house-seeks-urgent-statehood-for-jk-101790366541328.html',
    ],
  },
  {
    id: 'hst138',
    domain: 'civics',
    region: 'India',
    state: 'JK',
    topic: 'Environment & Land',
    subtopic: 'Roshni land scheme',
    kind: 'scam',
    difficulty: 'expert',
    year: 2020,
    asOf: '2026-09',
    govt: 'Other',
    question:
      'In October 2020 the J&K High Court ordered which agency to probe the Roshni scheme, under which occupants of state land could buy ownership?',
    options: ['Enforcement Directorate', 'Central Bureau of Investigation', 'National Investigation Agency', 'J&K Anti-Corruption Bureau'],
    correctIndex: 1,
    explanation:
      'The 2001 law (J&K State Lands — Vesting of Ownership to the Occupants — Act) was repealed by the administration in 2018, which had also ordered an Anti-Corruption Bureau probe into prime land being cornered. A petitioner alleged a ₹25,000 crore loss; the court asked the CBI to report every eight weeks and held the Act void from the start.',
    status:
      'HC ordered a CBI probe 9 Oct 2020; CBI cases followed. In Jan 2026 the HC ruled corruption prosecutions can continue despite the Act being void, but quashed chargesheets where no corrupt intent was shown. No conviction reported (Sept 2026).',
    otherSide:
      'In Jan 2026 the High Court quashed chargesheets against some officials and beneficiaries, finding no material that they used corrupt means or gained from the land transfers.',
    sourceUrl: 'https://www.thehindu.com/news/national/other-states/hc-orders-cbi-probe-into-roshni-land-scam-in-jk/article32818909.ece',
    sourceLabel: 'The Hindu — HC orders CBI probe into Roshni land scam in J&K (10 Oct 2020)',
    sources: ['https://kashmirobserver.net/2026/01/30/roshni-act-void-but-corruption-cases-can-proceed-jk-hc/'],
  },
  {
    id: 'hst139',
    domain: 'civics',
    region: 'India',
    state: 'JK',
    topic: 'Education & Exams',
    subtopic: 'JKSSB sub-inspector recruitment leak',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2022,
    asOf: '2026-09',
    govt: "President's Rule",
    question:
      "Over paper-leak allegations, J&K's administration in July 2022 cancelled the JKSSB selection list for about how many police sub-inspector candidates?",
    options: ['About 300', 'About 5,000', 'About 12,000', 'About 1,200'],
    correctIndex: 3,
    explanation:
      'The exam was held on 27 Mar 2022; lists of about 1,300 junior engineers and 1,000 finance account assistants were scrapped too. The CBI chargesheeted 33 accused in Nov 2022 and the ED opened a money-laundering case, alleging a money trail of about ₹2.52 crore from selling the paper.',
    status:
      'CBI chargesheet against 33 accused (Nov 2022); ED money-laundering case; special court bailed the alleged kingpin (Nov 2024) and the HC refused to cancel that bail (Apr 2026); trial pending. No conviction reported (Sept 2026).',
    otherSide:
      'The accused told the High Court they had kept every bail condition and not tampered with evidence; it refused the ED’s plea to cancel their bail (Apr 2026).',
    sourceUrl:
      'https://www.thehindu.com/news/national/jammu-and-kashmir/jammu-kashmir-sub-inspector-recruitment-exam-paper-leak-case-court-dismisses-bail-plea-of-kingpin/article68459947.ece',
    sourceLabel: 'The Hindu — J&K sub-inspector recruitment exam leak: court dismisses bail plea of kingpin (29 Jul 2024)',
    sources: ['https://www.dailyexcelsior.com/hc-refuses-to-cancel-bail-in-jkssb-paper-leak-case/'],
  },
  {
    id: 'hst140',
    domain: 'civics',
    region: 'India',
    state: 'JK',
    topic: 'Banking & Finance',
    subtopic: 'UT debt',
    kind: 'spend',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: "President's Rule",
    question: "PRS estimates Jammu & Kashmir's outstanding debt at the end of 2023-24 at about what share of its GSDP?",
    options: ['About 25%', 'About 36%', 'About 51%', 'About 70%'],
    correctIndex: 2,
    explanation:
      'PRS: 51% of GSDP at end-2023-24, up from 48% a year earlier; outstanding guarantees add another 8% of GSDP (Mar 2025). PRS also flags gaps between the budget’s 2023-24 figures and the CAG’s provisional accounts. Committed spending takes 56% of revenue receipts in 2025-26.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/jammu-and-kashmir/2025/J%26K_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Jammu and Kashmir Budget Analysis 2025-26',
  },
  {
    id: 'hst141',
    domain: 'civics',
    region: 'India',
    state: 'JK',
    topic: 'Welfare & Subsidies',
    subtopic: 'Free public transport for women',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'Other',
    question:
      "J&K's 2025-26 budget, the first by the National Conference-led government, promised all women free rides on what from April 2025?",
    options: [
      'Government-owned public transport, incl. e-buses',
      'Private buses via fare reimbursement',
      'Train services within the UT',
      'App-based cabs up to 10 km',
    ],
    correctIndex: 0,
    explanation:
      'The same budget, presented on 7 Mar 2025, raised free ration for Antyodaya Anna Yojana families to 10 kg and launched Mission YUVA with a target of 4.25 lakh jobs over five years.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/jammu-and-kashmir/2025/J%26K_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Jammu and Kashmir Budget Analysis 2025-26',
    tags: ['distribution'],
    enactedBy: [{ name: 'Omar Abdullah', role: 'Chief Minister, Jammu & Kashmir (presented the 2025-26 budget)', party: 'JKNC' }],
  },
  {
    id: 'hst142',
    domain: 'civics',
    region: 'India',
    state: 'JK',
    topic: 'Governance & Institutions',
    subtopic: 'Powers of the elected UT Assembly',
    kind: 'institution',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: "President's Rule",
    question:
      'Under the J&K Reorganisation Act 2019, the elected Assembly of the Union Territory cannot make laws on which State List subjects?',
    options: [
      'Agriculture and fisheries',
      'Local government and municipalities',
      'Public health and sanitation',
      'Police and public order',
    ],
    correctIndex: 3,
    explanation:
      'Those stay with the Lieutenant Governor. In July 2024, before the polls, the Union Home Ministry amended the business rules to give the LG more say over police, All India Services officers, the Advocate-General and prosecution sanctions. The NC–Congress alliance then won a majority in Oct 2024.',
    sourceUrl:
      'https://www.thehindu.com/elections/jammu-and-kashmir-assembly/after-decisive-mandate-governance-challenges-likely-for-nc-congress-alliance-in-jk-as-key-administrative-powers-remain-with-the-l-g/article68733481.ece',
    sourceLabel: 'The Hindu — Governance challenges likely for NC-Congress alliance as key powers remain with L-G (8 Oct 2024)',
  },

  // ───────────────────────────── RAJASTHAN ─────────────────────────────
  {
    id: 'hst143',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Education & Exams',
    subtopic: 'SI recruitment exam 2021 cancelled',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2021,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'In April 2026 a Rajasthan HC bench upheld cancelling the 2021 police sub-inspector exam over paper leaks. How many vacancies had that exam been held to fill?',
    options: ['859', '3,896', '12,000', '60,244'],
    correctIndex: 0,
    explanation:
      'The Sept 2021 exam was quashed by a single judge on 28 Aug 2025; the SOG has arrested 122 people, including 55 trainee SIs and two RPSC members. The BJP government’s cabinet panel had advised against cancelling, saying 6.3% of examinees were tainted. The bench urged ‘no political appointments’ to the RPSC; a re-exam was held on 20 Sep 2026.',
    status:
      'Exam cancelled (single judge Aug 2025; division bench upheld 4 Apr 2026); re-exam held 20 Sep 2026; criminal cases against arrested accused pending; no conviction reported (Sept 2026).',
    otherSide:
      'The state’s cabinet sub-committee had advised against scrapping the recruitment, saying the SOG found only 6.3% of examinees tainted; the High Court bench disagreed.',
    sourceUrl:
      'https://www.thehindu.com/news/national/rajasthan/rajasthan-high-court-upholds-cancellation-of-2021-policesub-inspector-exam-over-paper-leak/article70823951.ece',
    sourceLabel: 'The Hindu — Rajasthan HC upholds cancellation of 2021 police SI exam (4 Apr 2026)',
    sources: ['https://theprint.in/india/three-wanted-criminals-arrested-during-rajasthan-si-2021-re-examination-sog/3048165/'],
  },
  {
    id: 'hst144',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Education & Exams',
    subtopic: 'Senior teacher exam 2022 leak',
    kind: 'scam',
    difficulty: 'expert',
    year: 2022,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "In Sept 2023 the ED arrested a sitting RPSC member in the case over the leaked general-knowledge paper of Rajasthan's Dec 2022 senior-teacher exam. How much did police allege he was paid for it?",
    options: ['₹6 lakh', '₹60 lakh', '₹6 crore', '₹16 crore'],
    correctIndex: 1,
    explanation:
      'The Rajasthan Police SOG, under the then Congress government, first arrested him in Apr 2023, alleging he took ₹60 lakh to pass the paper to a gang that sold it to candidates for ₹8–10 lakh each; the Opposition BJP sought a CBI probe into the leaks. The ED also arrested an alleged broker. The Governor suspended him and in Apr 2026 sanctioned his prosecution. The allegations are yet to be tested at trial.',
    status:
      'Arrested by the SOG (Apr 2023, then bailed) and the ED under PMLA (Sept 2023); suspended; Supreme Court interim bail (9 Feb 2026) revoked (Mar 2026); prosecution sanctioned (Apr 2026); trial pending. Not convicted.',
    otherSide:
      'No public statement from the suspended member was found in sources checked (Sept 2026); the ₹60 lakh figure is a police allegation, and he has not been convicted.',
    sourceUrl:
      'https://www.thehindu.com/news/national/other-states/ed-arrests-anil-kumar-meena-rpsc-member-babulal-katara-in-paper-leak-case/article67314716.ece',
    sourceLabel: 'The Hindu — ED arrests RPSC member, broker in paper leak case (16 Sep 2023)',
    sources: ['https://timesofindia.indiatimes.com/city/jaipur/guv-grants-prosecution-sanction-for-ex-rpsc-member-katara/articleshow/130316992.cms'],
  },
  {
    id: 'hst145',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Infrastructure',
    subtopic: 'Jal Jeevan Mission case',
    kind: 'scam',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'INC',
    question:
      'Former Rajasthan minister Mahesh Joshi was arrested by the ED in April 2025 and by the state ACB in May 2026 over alleged irregularities in which scheme?',
    options: ['Chiranjeevi health insurance', 'Indira Rasoi Yojana', 'Jal Jeevan Mission', 'PM Awas Yojana-Gramin'],
    correctIndex: 2,
    explanation:
      'Joshi headed the Public Health Engineering department, which ran the tap-water mission, in the 2018–23 Congress government. PTI reports describe an alleged ₹900 crore scam; the ED case stems from the ACB FIR, which alleges firms bribed officials to win tenders. The Supreme Court bailed him in the ED case in Dec 2025.',
    status:
      'ED arrest 24 Apr 2025 (Supreme Court bail Dec 2025); ACB arrest 7 May 2026, in judicial custody; ACB chargesheet filed; Rajasthan HC denied bail 13 Aug 2026. Not convicted; calls the case a conspiracy.',
    otherSide:
      'Joshi says the case is a conspiracy built on statements by firms he blacklisted as minister; his lawyer says he sat on no bid-evaluation or finance committee that passed the tenders.',
    people: ['Mahesh Joshi'],
    sourceUrl: 'https://theprint.in/india/jjm-scam-former-rajasthan-minister-joshi-sent-to-judicial-custody/2927798/',
    sourceLabel: 'ThePrint (PTI) — JJM ‘scam’: former Rajasthan minister Joshi sent to judicial custody (11 May 2026)',
    sources: [
      'https://theprint.in/india/ed-arrests-former-rajasthan-minister-mahesh-joshi-in-money-laundering-case/2602508/',
      'https://timesofindia.indiatimes.com/city/jaipur/joshi-held-in-jal-jeevan-laundering-case/articleshow/120595653.cms',
      'https://www.etvbharat.com/en/state/rajasthan-hc-denies-bail-to-former-minister-mahesh-joshi-and-former-ias-officer-subodh-agrawal-among-other-accused-in-jjm-scam-enn26081304387',
    ],
  },
  {
    id: 'hst146',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Welfare & Subsidies',
    subtopic: 'Old Pension Scheme restored',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2022,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "In February 2022, which state's Congress government used its budget to restore the Old Pension Scheme for staff who joined on or after 1 January 2004?",
    options: ['Himachal Pradesh', 'Punjab', 'Chhattisgarh', 'Rajasthan'],
    correctIndex: 3,
    explanation:
      'The chief minister said the NPS had left employees anxious about old age and urged other states to rethink it; a staff federation said over 4 lakh employees would benefit. The Hindu called it a populist budget ahead of the 2023 poll. By 2025-26 pensions took 12% of Rajasthan’s revenue receipts (PRS).',
    sourceUrl: 'https://www.thehindu.com/news/national/other-states/old-pension-scheme-revived-in-rajasthan-budget/article65078024.ece',
    sourceLabel: 'The Hindu — Old pension scheme revived in Rajasthan budget (23 Feb 2022)',
    sources: ['https://prsindia.org/files/budget/budget_state/rajasthan/2025/Rajasthan_Budget_Analysis_2025-26.pdf'],
  },
  {
    id: 'hst147',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Health',
    subtopic: 'Chiranjeevi health insurance',
    kind: 'scheme',
    difficulty: 'expert',
    year: 2023,
    asOf: '2026-09',
    govt: 'INC',
    question:
      "Under the 2018–23 Congress government, Rajasthan's Chiranjeevi health insurance scheme claimed to cover treatment up to how much per family per year?",
    options: ['₹5 lakh', '₹10 lakh', '₹25 lakh', '₹50 lakh'],
    correctIndex: 2,
    explanation:
      'In the 2023 campaign Congress promised to raise it to ₹50 lakh; a BJP spokesperson called that impractical, arguing few families’ bills ever crossed the ₹5 lakh offered by the Centre’s Ayushman Bharat, and asked the government to publish how many had.',
    sourceUrl:
      'https://www.thehindu.com/elections/rajasthan-assembly/ashok-gehlots-expansion-of-health-cover-under-chiranjeevi-scheme-impractical-says-bjp-leader/article67567361.ece',
    sourceLabel: 'The Hindu — Expansion of health cover under Chiranjeevi scheme ‘impractical’, says BJP leader (Nov 2023)',
    sources: ['https://www.livemint.com/elections/assembly-elections/bjp-emerges-victorious-in-rajasthan-assembly-election-securing-115-seats-a-recap-10-points-11701651737789.html'],
    tags: ['distribution', 'pre-election'],
    enactedBy: [{ name: 'Ashok Gehlot', role: 'Chief Minister, Rajasthan', party: 'INC' }],
    outcome:
      'In the 2023 campaign the Congress promised to raise the cover to ₹50 lakh. Rajasthan voted on 25 Nov 2023; the BJP won 115 of 199 seats and the Congress 69.',
    poll: { label: 'Rajasthan Assembly 2023', month: '2023-11', result: 'BJP won 115 of 199 seats; Congress 69' },
  },
  {
    id: 'hst148',
    domain: 'civics',
    region: 'India',
    state: 'RJ',
    topic: 'Banking & Finance',
    subtopic: 'State debt',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'BJP',
    question: "Which figure is closest to Rajasthan's outstanding debt at the end of 2025-26, as a share of GSDP, per PRS?",
    options: ['About 18%', 'About 36.5%', 'About 51%', 'About 65%'],
    correctIndex: 1,
    explanation:
      'PRS: 36.5%, below the 37.7% budget estimate for 2024-25. Rajasthan also repays ₹1,57,452 crore of debt in 2025-26, and interest takes 14% of revenue receipts.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/rajasthan/2025/Rajasthan_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Rajasthan Budget Analysis 2025-26',
  },

  // ───────────────────────────── BIHAR ─────────────────────────────
  {
    id: 'hst149',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Banking & Finance',
    subtopic: 'Srijan scam',
    kind: 'scam',
    difficulty: 'simple',
    year: 2017,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      'The Srijan scam, exposed in 2017, involved government funds allegedly diverted into the bank accounts of an NGO based in which Bihar district?',
    options: ['Bhagalpur', 'Gaya', 'Muzaffarpur', 'Darbhanga'],
    correctIndex: 0,
    explanation:
      'Money from land-acquisition and welfare accounts was allegedly moved to the NGO’s accounts with help from bank and government staff, then spent on property. The CBI took over in Aug 2017. The RJD blamed the Nitish Kumar government; the BJP alleged the NGO got its office lease in 2004 under Rabri Devi.',
    people: ['Nitish Kumar', 'Rabri Devi'],
    status:
      'CBI re-registered 10 cases in Aug 2017; ED attached assets (₹18.45 crore by Oct 2021) and filed a chargesheet; first verdict Nov 2025, when a special CBI court convicted three bank and collectorate staff in one case; other trials pending. No politician charged (Sept 2026).',
    otherSide:
      'No politician has been charged; in 2017 the RJD blamed the ruling JD(U)-BJP government while the BJP pointed to the NGO’s 2004 office lease under the RJD government.',
    sourceUrl: 'https://www.thehindu.com/news/national/other-states/cbi-takes-over-probe-into-1000-crore-srijan-scam-in-bihar/article61470793.ece',
    sourceLabel: 'The Hindu — CBI re-registers 10 cases linked to Srijan scam (26 Aug 2017)',
    sources: [
      'https://www.thehindu.com/news/national/other-states/enforcement-directorate-arrests-one-person-in-srijan-scam-case/article36889215.ece',
      'https://www.etvbharat.com/en/state/cbi-court-sentences-three-in-bihars-multi-crore-srijan-scam-enn25111901804',
    ],
  },
  {
    id: 'hst150',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Jobs & Economy',
    subtopic: 'Land-for-jobs case',
    kind: 'scam',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'UPA',
    question:
      'In January 2026 a Delhi court framed charges in the CBI’s land-for-jobs case against Lalu Prasad, Rabri Devi and others. The Railway jobs at issue were given in which period?',
    options: ['1990–1997', '2000–2004', '2014–2019', '2004–2009'],
    correctIndex: 3,
    explanation:
      'The CBI alleges Group D substitutes were hired while Lalu Prasad was Union Railway Minister, in return for land given to his family and a company they controlled. The court rejected the family’s discharge pleas and framed charges; some railway officials and substitutes were discharged. In Apr 2026 the Supreme Court declined to quash the FIR.',
    status:
      'CBI case: charges framed 9 Jan 2026; Supreme Court declined to quash the FIR (13 Apr 2026) but let him raise lack of prior sanction at trial; trial under way. ED money-laundering case: charge-framing hearing listed 30 Sep 2026. Not convicted; the family denies the charges.',
    otherSide:
      'Lalu Prasad and his family call the case politically motivated and deny the CBI’s charges; the Supreme Court exempted him from appearing in person at the trial.',
    people: ['Lalu Prasad Yadav', 'Rabri Devi'],
    sourceUrl: 'https://www.thehindu.com/news/national/land-for-jobs-case-delhi-court-frames-charges-against-lalu-prasad/article70489533.ece',
    sourceLabel: 'The Hindu — Delhi court frames charges against Lalu Prasad, others in land-for-jobs case (9 Jan 2026)',
    sources: [
      'https://theprint.in/india/delhi-court-adjourns-framing-of-charges-in-eds-land-for-job-irctc-cases-against-lalu/3028488/',
      'https://www.thehindu.com/news/national/sc-allows-lalu-prasad-to-raise-plea-of-prior-sanction-during-trial/article70856529.ece',
    ],
  },
  {
    id: 'hst151',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Health',
    subtopic: 'Prohibition and hooch deaths',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      'How many ‘confirmed’ hooch deaths did Bihar’s excise department acknowledge between the April 2016 start of prohibition and April 2025?',
    options: ['About 19', 'About 90', 'About 190', 'About 1,900'],
    correctIndex: 2,
    explanation:
      'The department named Saran, Siwan, Gaya, Bhojpur, Buxar and Gopalganj as the worst-hit districts. By 31 Mar 2025 it had registered 9.36 lakh cases and arrested 14.32 lakh people under the prohibition law. The figure counts only deaths the department treats as ‘confirmed’.',
    sourceUrl: 'https://www.thehindu.com/news/national/bihar/dry-bihar-recorded-190-confirmed-hooch-deaths-in-last-9-years-official/article69412794.ece',
    sourceLabel: 'The Hindu (PTI) — Dry Bihar recorded 190 confirmed hooch deaths in last 9 years: official (4 Apr 2025)',
  },
  {
    id: 'hst152',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Welfare & Subsidies',
    subtopic: 'Mukhyamantri Mahila Rojgar Yojana',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      "Weeks before the 2025 Assembly election, how much did each of 75 lakh women receive at the launch of Bihar's Mukhyamantri Mahila Rojgar Yojana?",
    options: ['₹2,500', '₹10,000', '₹25,000', '₹1 lakh'],
    correctIndex: 1,
    explanation:
      'The PM transferred ₹7,500 crore in all on 26 Sep 2025 for the state-funded scheme, which promises up to ₹2 lakh more later based on how the women’s ventures do. The RJD complained to the Election Commission that further payments on 17, 24 and 31 Oct, after the model code began, broke it.',
    sourceUrl: 'https://www.thehindu.com/elections/bihar-assembly/pm-modi-launches-bihars-mukhyamantri-mahila-rojgar-yojana/article70096776.ece',
    sourceLabel: 'The Hindu — PM Modi launches Bihar’s Mukhyamantri Mahila Rojgar Yojana (26 Sep 2025)',
    sources: [
      'https://theprint.in/india/rjd-leader-writes-to-ec-says-bihar-govt-violated-mcc-by-transferring-money-to-women-ahead-of-poll/2774961/',
      'https://www.hindustantimes.com/india-news/nda-mahagathbandhan-bjp-jdu-rjd-congress-ljp-jan-suraaj-prashant-kishore-tejashwi-seat-tally-101763169862862.html',
    ],
    tags: ['distribution', 'pre-election'],
    enactedBy: [
      { name: 'Nitish Kumar', role: 'Chief Minister, Bihar', party: 'JD(U)' },
      { name: 'Narendra Modi', role: 'Prime Minister (launched it and made the first transfer)', party: 'BJP' },
    ],
    outcome:
      '₹7,500 crore reached 75 lakh women on 26 Sep 2025, 41 days before Bihar’s first phase of polling on 6 Nov. The NDA won 202 of 243 seats (BJP 89, JD(U) 85); the RJD won 25.',
    poll: { label: 'Bihar Assembly 2025', month: '2025-11', gapDays: 41, result: 'NDA won 202 of 243 seats; BJP 89, JD(U) 85' },
  },
  {
    id: 'hst153',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Education & Exams',
    subtopic: 'BPSC 70th prelims row',
    kind: 'institution',
    difficulty: 'expert',
    year: 2024,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      'After weeks of protest over the December 2024 BPSC 70th prelims (3.29 lakh candidates), what did the Patna High Court do with petitions seeking a full re-exam?',
    options: [
      'Dismissed them',
      'Ordered a fresh exam statewide',
      'Stayed the results indefinitely',
      'Ordered a CBI inquiry',
    ],
    correctIndex: 0,
    explanation:
      'The commission had re-held the exam only for one Patna centre, where candidates said papers came late (5,943 took the 4 Jan 2025 re-test), and declared results with 21,581 qualifying. Protesters wanted all 912 centres re-tested; the High Court dismissed their pleas on 28 Mar 2025.',
    sourceUrl: 'https://www.thehindu.com/news/national/bihar/bpsc-row-patna-high-court-dismisses-petitions-demanding-fresh-examination/article69386895.ece',
    sourceLabel: 'The Hindu — BPSC row: Patna High Court dismisses petitions demanding fresh exam (28 Mar 2025)',
  },
  {
    id: 'hst154',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Infrastructure',
    subtopic: 'Aguwani–Sultanganj bridge collapse',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2023,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      'The under-construction Aguwani Ghat–Sultanganj bridge over the Ganga collapsed for the second time on 4 June 2023. What was its sanctioned cost?',
    options: ['₹171 crore', '₹716 crore', '₹3,210 crore', '₹1,716 crore'],
    correctIndex: 3,
    explanation:
      'Foundation laid in 2014, it was due in 2019 and missed its deadline eight times; part of it had fallen in wind and rain in April 2022 without action against the builder. The JD(U)-RJD government ordered a probe, and the minister holding the road construction portfolio promised strict action against those responsible.',
    status:
      'State ordered a probe and served the builder a show-cause notice (Jun 2023); the Patna HC blamed laxity by the state and the contractor (Jun 2023). No case against any minister reported (Sept 2026).',
    otherSide:
      'The road construction minister said the firm got a show-cause notice, engineers on the project had been removed, and he had flagged the faulty pier while in opposition.',
    sourceUrl: 'https://www.thehindu.com/news/national/other-states/under-construction-bridge-collapses-in-bihars-bhagalpur/article66931549.ece',
    sourceLabel: 'The Hindu — Under-construction bridge collapses in Bihar’s Bhagalpur; probe ordered (4 Jun 2023)',
    sources: [
      'https://www.livemint.com/news/india/bhagalpur-bridge-collapse-bihar-govt-issues-show-cause-notice-to-construction-company-11686064928789.html',
      'https://www.scconline.com/blog/post/2023/06/17/bhagalpur-bridge-collapsed-due-to-laxity-of-state-government-and-contractor-patna-hc-legal-news/',
    ],
  },
  {
    id: 'hst155',
    domain: 'civics',
    region: 'India',
    state: 'BR',
    topic: 'Banking & Finance',
    subtopic: 'Fiscal deficit 2024-25',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'JDU',
    question:
      "Bihar budgeted a 3% fiscal deficit for 2024-25. What did the revised estimate, cited by PRS, show instead?",
    options: ['2.1% of GSDP', '9.2% of GSDP', '4.5% of GSDP', '15% of GSDP'],
    correctIndex: 1,
    explanation:
      'PRS: 9.2% of GSDP in the 2024-25 revised estimate, with a revenue deficit of 4.1%. For 2025-26 Bihar again targets a 3% fiscal deficit and even a small revenue surplus; outstanding debt is estimated at 37% of GSDP.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/bihar/2025/Bihar_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Bihar Budget Analysis 2025-26',
  },

  // ───────────────────────────── JHARKHAND ─────────────────────────────
  {
    id: 'hst156',
    domain: 'civics',
    region: 'India',
    state: 'JH',
    topic: 'Environment & Land',
    subtopic: 'Ranchi land case against the CM',
    kind: 'scam',
    difficulty: 'simple',
    year: 2024,
    asOf: '2026-09',
    govt: 'JMM',
    question:
      'Which agency arrested Hemant Soren on 31 January 2024, soon after he resigned as Jharkhand CM, in a money-laundering case over an 8.86-acre Ranchi plot?',
    options: [
      'Central Bureau of Investigation',
      'Jharkhand Anti-Corruption Bureau',
      'Enforcement Directorate',
      'Income Tax Department',
    ],
    correctIndex: 2,
    explanation:
      'In June 2024 the Jharkhand HC bailed him, saying there were ‘reasons to believe’ he was not guilty; the Supreme Court upheld the bail and his JMM won the Nov 2024 election. In June 2026 the PMLA court rejected his discharge plea, citing ‘grave suspicion’, and it has listed framing of charges against him for 30 Sep 2026.',
    status:
      'Arrested 31 Jan 2024; on bail since 28 Jun 2024; discharge plea rejected 8 Jun 2026; HC refused to stay proceedings (18 Sep 2026); charges framed against the 16 co-accused, framing against him deferred to 30 Sep 2026. Not convicted; his lawyers say the ED’s case rests on hearsay.',
    otherSide:
      'Soren’s lawyers say the ED’s claim that he controlled the 8.86 acres rests on hearsay; in 2024 the High Court saw ‘reasons to believe’ he was not guilty when it bailed him.',
    people: ['Hemant Soren'],
    sourceUrl:
      'https://theprint.in/judiciary/grave-suspicion-against-accused-pmla-court-junks-cm-hemant-sorens-discharge-plea-in-land-parcel-case/2954026/',
    sourceLabel: 'ThePrint — ‘Grave suspicion against accused’: PMLA court junks CM Hemant Soren’s discharge plea (8 Jun 2026)',
    sources: [
      'https://theprint.in/india/jkhand-hc-rejects-cms-plea-seeking-discharge-from-criminal-proceedings-in-land-deal-case/3046928/',
      'https://www.hindustantimes.com/cities/ranchi-news/money-laundering-case-soren-appears-before-pmla-court-framing-of-charge-deferred-till-sept-30-101790271418947.html',
    ],
  },
  {
    id: 'hst157',
    domain: 'civics',
    region: 'India',
    state: 'JH',
    topic: 'Welfare & Subsidies',
    subtopic: 'IAS officer reinstated after bail',
    kind: 'scam',
    difficulty: 'expert',
    year: 2025,
    asOf: '2026-09',
    govt: 'JMM',
    question:
      'IAS officer Pooja Singhal, arrested by the ED in May 2022 and reinstated by Jharkhand in January 2025, faces a case over funds allegedly diverted from which scheme?',
    options: ['PM-KISAN', 'Mid-day meal scheme', 'MGNREGS (rural job guarantee)', 'Swachh Bharat Mission'],
    correctIndex: 2,
    explanation:
      'The ED’s case links her to about ₹18 crore of MGNREGS funds allegedly embezzled in Khunti when she was deputy commissioner in 2009–10; she was mines secretary under the JMM government at her arrest. After bail in Dec 2024 the state revoked her suspension on a panel’s advice; the BJP criticised it. In Sept 2026 the Supreme Court let the trial continue.',
    status:
      'Arrested by ED 11 May 2022; cognisance taken Jul 2022; bail 7 Dec 2024; suspension revoked Jan 2025; Supreme Court declined to quash cognisance, leaving the sanction question for trial (25 Sep 2026); trial pending. Not convicted.',
    otherSide:
      'Her counsel told the Supreme Court the ₹19 crore recovered from her chartered accountant is not attributable to her and that prosecution needed government sanction; the court left sanction open.',
    people: ['Pooja Singhal'],
    sourceUrl:
      'https://theprint.in/india/ias-at-21-arrested-for-mnregs-fund-embezzlement-now-reinstated-the-highs-lows-of-pooja-singhal/2460755/',
    sourceLabel: 'ThePrint — IAS at 21, arrested for MNREGS fund embezzlement, now reinstated (25 Jan 2025)',
    sources: [
      'https://theprint.in/india/jpsc-ex-chairman-is-the-latest-4-ias-officers-faced-arrests-in-jharkhand-since-2022/3012576/',
      'https://www.etvbharat.com/en/bharat/money-laundering-trial-to-continue-against-jharkhand-ias-officer-pooja-singhal-sc-enn26092506885',
    ],
  },
  {
    id: 'hst158',
    domain: 'civics',
    region: 'India',
    state: 'JH',
    topic: 'Infrastructure',
    subtopic: 'Rural development tender case',
    kind: 'scam',
    difficulty: 'extreme',
    year: 2024,
    asOf: '2026-09',
    govt: 'JMM',
    question:
      "In May 2024 the ED said it found about how much cash in a Ranchi flat linked to the officer on special duty of a Jharkhand minister, in a rural-development tender probe?",
    options: ['About ₹3 crore', 'About ₹8 crore', 'About ₹100 crore', 'About ₹32 crore'],
    correctIndex: 3,
    explanation:
      'The ED arrested the OSD and, on 15 May 2024, Congress minister Alamgir Alam, who then resigned. He spent two years in jail before the Supreme Court granted bail on 11 May 2026; the BJP said bail on age and health grounds was not an acquittal. In Sept 2026 the Supreme Court left the rejection of his discharge plea in place.',
    status:
      'Arrested by ED 15 May 2024; Supreme Court bail 11 May 2026 (released 14 May); discharge plea rejected by the PMLA court and HC, and the Supreme Court declined to interfere (16 Sep 2026); trial pending. Not convicted; says he is innocent.',
    otherSide:
      'Alam calls himself innocent and says he has faith in the judiciary (May 2026).',
    people: ['Alamgir Alam'],
    sourceUrl: 'https://www.thehindu.com/news/national/jharkhand/congress-leader-and-former-jharkhand-minister-alamgir-alam-walks-out-of-jail/article70979362.ece',
    sourceLabel: 'The Hindu — Former Jharkhand minister Alamgir Alam walks out of jail (15 May 2026)',
    sources: [
      'https://www.thehindu.com/news/national/ed-arrests-jharkhand-ministers-secretary-latters-domestic-help-after-cash-haul/article68148085.ece',
      'https://telanganatoday.com/alamgir-alams-discharge-plea-rejected-by-supreme-court-in-money-laundering-case',
    ],
  },
  {
    id: 'hst159',
    domain: 'civics',
    region: 'India',
    state: 'JH',
    topic: 'Welfare & Subsidies',
    subtopic: 'Mukhyamantri Maiya Samman Yojana',
    kind: 'scheme',
    difficulty: 'simple',
    year: 2025,
    asOf: '2026-09',
    govt: 'JMM',
    question: "Jharkhand's Mukhyamantri Maiya Samman Yojana pays eligible women aged 18 to 50 how much a month?",
    options: ['₹1,000', '₹2,500', '₹2,100', '₹1,500'],
    correctIndex: 1,
    explanation:
      'PRS: the scheme supports women aged 18 to 50, and revised 2024-25 figures put its cost at ₹7,238 crore that year. PRS notes similar cash transfers for women in Maharashtra, West Bengal, Madhya Pradesh and Karnataka.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/jharkhand/2025/Jharkhand_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Jharkhand Budget Analysis 2025-26',
    tags: ['distribution'],
  },
  {
    id: 'hst160',
    domain: 'civics',
    region: 'India',
    state: 'JH',
    topic: 'Education & Exams',
    subtopic: 'JSSC-CGL exam cancelled',
    kind: 'institution',
    difficulty: 'expert',
    year: 2026,
    asOf: '2026-09',
    govt: 'JMM',
    question:
      'In August 2026, after a student protest in Ranchi that had run 24 days, the Jharkhand government cancelled which exam along with all work by its contracted exam agency?',
    options: [
      'JPSC Civil Services prelims',
      'Jharkhand Police constable exam',
      'JSSC Combined Graduate Level (CGL) exam',
      'JAC Class 12 board exam',
    ],
    correctIndex: 2,
    explanation:
      'The government also ordered a probe into work given to the agency since 2014 and cancelled its exams, results and selections. Days earlier the state CID had arrested a former JPSC chairman amid the protests. Student leaders welcomed the move but asked for a system that guarantees no future leaks.',
    sourceUrl:
      'https://theprint.in/india/jharkhand-govt-gives-cancels-jssc-cgl-exam-orders-probe-of-work-contracted-to-tdpl-since-2014/3017703/',
    sourceLabel: 'ThePrint — Jharkhand govt cancels JSSC-CGL exam, orders probe of work contracted since 2014 (17 Aug 2026)',
    sources: ['https://theprint.in/india/jpsc-ex-chairman-is-the-latest-4-ias-officers-faced-arrests-in-jharkhand-since-2022/3012576/'],
  },
  {
    id: 'hst161',
    domain: 'civics',
    region: 'India',
    state: 'JH',
    topic: 'Welfare & Subsidies',
    subtopic: 'Maiya Samman budget share',
    kind: 'spend',
    difficulty: 'extreme',
    year: 2025,
    asOf: '2026-09',
    govt: 'JMM',
    question:
      "Jharkhand's 2025-26 budget gave its Maiya Samman cash scheme for women ₹13,363 crore, per PRS. About what share of the state's budgeted revenue receipts is that?",
    options: ['About 2%', 'About 5%', 'About 11%', 'About 25%'],
    correctIndex: 2,
    explanation:
      'PRS: 11%, up from about 7% of receipts in revised 2024-25 figures, and the largest item under social welfare. Even so, Jharkhand commits only 29% of revenue receipts to salaries, pensions and interest and projects debt at 27% of GSDP.',
    sourceUrl: 'https://prsindia.org/files/budget/budget_state/jharkhand/2025/Jharkhand_Budget_Analysis_2025-26.pdf',
    sourceLabel: 'PRS Legislative Research — Jharkhand Budget Analysis 2025-26',
    tags: ['distribution'],
  },
]);
