'use client';
import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import Collections, {CollectionCover} from './collections';
import {Journal} from './journal';
import {usePlayer} from './use-player';
import {request} from '@/lib/duel-client';
import {FORMAT_COPY,completedRounds} from '@/lib/duel-presentation.mjs';
import {DuelHUD,MatchFinish,RoundReview} from './rivalry-widgets';
import ArcadeStage from './arcade-stage';
import {Passport,MissionStrip} from './passport';
import Discovery from './discovery';
import Expeditions,{Clubhouse,ExpeditionCase} from './expeditions';
import { Slider } from '@/components/ui/slider';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { Zap, Swords, ArrowRight, Copy, Check, Timer, Coins, Radio, ShieldCheck, ArrowLeft, ExternalLink, Trophy, FlaskConical, Wifi, Volume2, VolumeX, Moon, Sun, Atom, Flag, CircleDot, Layers, BookOpen, Bookmark, Settings, Bot, Users, ChevronRight, Lock, CheckCircle2, X, Shuffle, HelpCircle, Compass, Brain, Rocket, ChevronDown } from 'lucide-react';

type Config={opponent:'bot'|'friend';mode:string;stake:number;duration:number;domain:string;region:string;topic:string;subtopic:string;difficulty:string};
type Credentials={roomId:string;token:string;invite?:string;profileEpoch?:string};
const INITIAL:Config={opponent:'bot',mode:'quick',stake:0,duration:15,domain:'all',region:'all',topic:'all',subtopic:'all',difficulty:'all'};
const MODES=[{id:'quick',name:'Quick Draw',short:'One question. Make it count.',rounds:1,icon:Zap},{id:'trilogy',name:'Triple Threat',short:'Up to three. First to two wins.',rounds:3,icon:Swords},{id:'gauntlet',name:'The Gauntlet',short:'Five questions. Highest score wins.',rounds:5,icon:Rocket}];
function randomToken(){return Array.from(crypto.getRandomValues(new Uint8Array(24)),b=>b.toString(16).padStart(2,'0')).join('');}
function roomId(){return crypto.randomUUID().replaceAll('-','');}
function Picker({label,value,items,onChange,disabled=false}:{label:string;value:string;items:[string,string][];onChange:(s:string)=>void;disabled?:boolean}){return <div className="field"><Label>{label}</Label><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,t])=><SelectItem value={v} key={v}>{t}</SelectItem>)}</SelectContent></Select></div>}
function safeSave(value:Credentials|null){try{if(value)sessionStorage.setItem('fact-duel-online-seat',JSON.stringify(value));else sessionStorage.removeItem('fact-duel-online-seat');}catch{}}
function parseInvite(text:string){const url=new URL(text,window.location.origin);const id=url.searchParams.get('room'),invite=new URLSearchParams(url.hash.slice(1)).get('invite');if(!id||!invite||!/^[a-f0-9]{32}$/.test(id)||!/^[A-Za-z0-9_-]{32,64}$/.test(invite))throw new Error('Paste the complete invitation link, including its ending.');return {roomId:id,invite};}
export default function Arena(){
 const [tab,setTab]=useState('home'),[catalogue,setCatalogue]=useState<any>(null),[config,setConfig]=useState<Config>(INITIAL),[name,setName]=useState('Challenger'),[joinLink,setJoinLink]=useState(''),[joinView,setJoinView]=useState(false),[room,setRoom]=useState<any>(null),[credentials,setCredentials]=useState<Credentials|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[light,setLight]=useState(false),[sound,setSound]=useState(false),[leaveOpen,setLeaveOpen]=useState(false),[metrics,setMetrics]=useState({rttMs:0,jitterMs:0,offset:0,samples:0}),[remaining,setRemaining]=useState(0),[shown,setShown]=useState(false),[answerPending,setAnswerPending]=useState(false),[countdown,setCountdown]=useState(3),[connected,setConnected]=useState(true),[copied,setCopied]=useState(false);
 const [selectedExpedition,setSelectedExpedition]=useState<string|null>(null);
 const [settingsOpen,setSettingsOpen]=useState(false),[clearOpen,setClearOpen]=useState(false),[chosen,setChosen]=useState<number|null>(null),[volume,setVolume]=useState(.35),[showArt,setShowArt]=useState(true);
 const player=usePlayer(room,credentials?.profileEpoch);const {journal,save:saveFact,clear:clearJournal,persistent:storageOK}=player;
 const playedCues=useRef(new Set<string>()),lastFocusKey=useRef<string|null>(null);
 const roomRef=useRef<any>(null),credRef=useRef<Credentials|null>(null),clock=useRef(metrics),audio=useRef<AudioContext|null>(null),startMark=useRef<{roundId:string;at:number}|null>(null),pending=useRef<any>(null),locked=useRef(false),mutation=useRef(false),revealing=useRef(false),createDraft=useRef<any>(null),joinDraft=useRef<any>(null),alive=useRef(true),recovered=useRef(false);
 const signal=useCallback((type:string)=>{if(!sound||volume<=0||document.hidden)return;try{
  audio.current=audio.current||new AudioContext();const ac=audio.current;void ac.resume();
  const notes=type==='stamp'?[392,523.25,659.25,783.99]:type==='correct'?[523.25,659.25]:type==='learn'?[392,440]:type==='win'?[523.25,659.25,783.99]:type==='loss'?[392,329.63]:type==='draw'?[440,440]:type==='count'?[523.25]:[440];
  notes.forEach((frequency,i)=>{const o=ac.createOscillator(),g=ac.createGain();o.type=type==='count'?'sine':'triangle';o.connect(g);g.connect(ac.destination);o.frequency.value=frequency;const t=ac.currentTime+i*.095;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,.10*volume),t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+.13);o.start(t);o.stop(t+.14);});
 }catch{}},[sound,volume]);
 const accept=useCallback((data:any)=>{const next=data.room;if(!next||!alive.current||credRef.current?.roomId!==next.id)return;const prev=roomRef.current;if(prev?.id===next.id&&prev.revision>next.revision)return;roomRef.current=next;if(!prev||next.revision!==prev.revision||next.round?.question?.id!==prev.round?.question?.id)setRoom(next);setConnected(true);},[]);
 const remember=useCallback((c:Credentials|null)=>{const bound=c?{...c,profileEpoch:c.profileEpoch??player.epoch()}:null;credRef.current=bound;setCredentials(bound);safeSave(bound);},[player.epoch]);
 useEffect(()=>{alive.current=true;request({action:'catalogue'}).then(data=>setCatalogue(data.catalogue)).catch(e=>setError(e.message));try{setLight(localStorage.getItem('fact-duel-online-theme')==='light');setShowArt(localStorage.getItem('fact-duel-art')!=='off');setSound(localStorage.getItem('fact-duel-online-sound')==='on');const savedName=localStorage.getItem('fact-duel-name');if(savedName)setName(savedName.slice(0,24));const v=Number(localStorage.getItem('fact-duel-volume')??'.35');if(Number.isFinite(v))setVolume(Math.max(0,Math.min(1,v)));}catch{}try{const url=new URL(window.location.href);if(url.hash.includes('invite=')){setTab('arena');setJoinView(true);setJoinLink(url.toString());history.replaceState({},'',url.pathname);}else{const saved=JSON.parse(sessionStorage.getItem('fact-duel-online-seat')||'null');if(saved?.roomId&&saved?.token){recovered.current=true;remember({...saved,profileEpoch:saved.profileEpoch??'initial'});}}}catch{}return()=>{alive.current=false;};},[remember]);
 useEffect(()=>{document.documentElement.dataset.theme=light?'light':'dark';try{localStorage.setItem('fact-duel-online-theme',light?'light':'dark');localStorage.setItem('fact-duel-online-sound',sound?'on':'off');}catch{}},[light,sound]);
 useEffect(()=>{try{localStorage.setItem('fact-duel-name',name);localStorage.setItem('fact-duel-volume',String(volume));}catch{}},[name,volume]);
 const calibrate=useCallback(async()=>{const samples:{rtt:number;offset:number}[]=[];for(let i=0;i<7;i++){const before=performance.now();const data=await request({action:'clock'});const after=performance.now();samples.push({rtt:after-before,offset:data.serverNow-(before+after)/2});}const sorted=[...samples].sort((a,b)=>a.rtt-b.rtt);const m={rttMs:Math.round(sorted[0].rtt),jitterMs:Math.round(sorted[6].rtt-sorted[0].rtt),offset:sorted[0].offset,samples:samples.length};clock.current=m;setMetrics(m);return m;},[]);
 useEffect(()=>{void calibrate().catch(()=>{});},[calibrate]);
 useEffect(()=>{if(!credentials)return;let stopped=false,timer:any;const poll=async()=>{try{const data=await request({action:'state',...credentials});if(stopped)return;accept(data);if(recovered.current&&data.room.round?.issuedAt!==null&&data.room.round?.issuedAt!==undefined&&!data.room.round?.result){recovered.current=false;await request({action:'leave',...credentials}).then(accept);setNote('The page reloaded after the question appeared. The match was refunded to avoid restarting the timer.');}else recovered.current=false;}catch(e:any){if(stopped)return;setConnected(false);if([403,404,410].includes(e.status)){setError(e.message);remember(null);roomRef.current=null;setRoom(null);return;}}finally{if(!stopped&&!roomRef.current?.settled){const phase=roomRef.current?.phase;timer=setTimeout(poll,document.hidden?3000:['playing','scheduled'].includes(phase)?500:1500);}}};void poll();return()=>{stopped=true;clearTimeout(timer);};},[credentials,accept,remember]);
 const mutate=useCallback(async(action:string,extra:any={})=>{if(mutation.current||!credRef.current)return;mutation.current=true;setBusy(true);setError('');try{const data=await request({action,...credRef.current,...extra});accept(data);}catch(e:any){setError(e.message);}finally{mutation.current=false;setBusy(false);}},[accept]);
 const resetLocal=useCallback(()=>{remember(null);roomRef.current=null;setRoom(null);startMark.current=null;pending.current=null;locked.current=false;setChosen(null);revealing.current=false;setShown(false);setAnswerPending(false);setError('');createDraft.current=null;joinDraft.current=null;},[remember]);
 const leave=useCallback(async()=>{await mutate('leave');setLeaveOpen(false);},[mutate]);
 useEffect(()=>{const visibility=()=>{const r=roomRef.current,c=credRef.current;if(document.hidden&&c&&r&&['playing','scheduled'].includes(r.phase)){void request({action:'leave',...c}).then(accept).catch(()=>setError('Connection lost while leaving. Reconnect to check the match status.'));}};document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility);},[accept]);
 const phase=room?.phase,rd=room?.round,question=rd?.question;
 useEffect(()=>{
  const key=room?`${room.id}:${phase}:${rd?.id}:${question&&shown?'question':'state'}`:tab;
  if(lastFocusKey.current===null){lastFocusKey.current=key;return;}
  if(lastFocusKey.current===key||document.hidden||settingsOpen||leaveOpen||clearOpen)return;
  if(question&&!rd?.result&&!shown)return;
  lastFocusKey.current=key;
  const frame=requestAnimationFrame(()=>{const target=document.querySelector<HTMLElement>(question&&shown&&!rd?.result?'.question-card h1':'#main-content h1, #main-content h2');if(target){target.tabIndex=-1;target.focus({preventScroll:false});}});
  return()=>cancelAnimationFrame(frame);
 },[tab,room?.id,phase,rd?.id,!!question,!!rd?.result,shown,settingsOpen,leaveOpen,clearOpen]);
 useEffect(()=>{if(!room||!['scheduled','playing'].includes(room.phase))return;let running=true;const check=async()=>{const r=roomRef.current,c=credRef.current;if(!r?.round||!c||!running)return;const until=r.round.scheduledAt-(performance.now()+clock.current.offset);setCountdown(Math.max(0,Math.ceil(until/1000)));if(until<=0&&r.round.issuedAt===null&&!revealing.current){revealing.current=true;try{const data=await request({action:'reveal',...c,roundId:r.round.id});accept(data);}catch(e:any){if(e.code!=='too_early')setError(e.message);}finally{revealing.current=false;}}};const id=setInterval(check,150);void check();return()=>{running=false;clearInterval(id);};},[room?.id,phase,rd?.id,accept]);
 useLayoutEffect(()=>{if(!question||rd?.result)return;if(startMark.current?.roundId===rd.id)return;setShown(false);setChosen(null);setAnswerPending(false);locked.current=false;pending.current=null;let a=0,b=0;a=requestAnimationFrame(()=>{b=requestAnimationFrame(()=>{startMark.current={roundId:rd.id,at:performance.now()};setShown(true);setRemaining(room.config.duration*1000);});});return()=>{cancelAnimationFrame(a);cancelAnimationFrame(b);};},[question?.id,rd?.result,rd?.id,room?.config.duration]);
 const expire=useCallback(()=>setRemaining(0),[]);
 useEffect(()=>{if(rd?.result){locked.current=true;setAnswerPending(false);const key=`result-${rd.id}`;if(!playedCues.current.has(key)){playedCues.current.add(key);signal(rd.result.winner===null?'draw':rd.result.winner===room.seat?'win':'loss');}}},[rd?.id,rd?.result,room?.seat,signal]);
 useEffect(()=>{if(!rd||question||!['scheduled','playing'].includes(phase)||![1,2,3].includes(countdown))return;const key=`count-${rd.id}-${countdown}`;if(!playedCues.current.has(key)){playedCues.current.add(key);signal('count');}},[rd?.id,question?.id,phase,countdown,signal]);
 const sendPending=useCallback(async()=>{const p=pending.current,c=credRef.current;if(!p||!c)return;setAnswerPending(true);setError('');try{const data=await request({action:'answer',...c,...p});accept(data);setAnswerPending(false);}catch(e:any){setAnswerPending(false);setError(e.status===409?e.message:'Your choice is locked on this screen. Retry sending the same answer.');}},[accept]);
 const answer=useCallback((choice:number)=>{const r=roomRef.current,start=startMark.current;if(!r?.round||r.round.result||locked.current||r.round.answerLocked[r.seat]||!start||start.roundId!==r.round.id||!shown)return;const elapsedMs=performance.now()-start.at;if(elapsedMs>=r.config.duration*1000)return;locked.current=true;setChosen(choice);pending.current={roundId:r.round.id,attemptId:randomToken(),choice,elapsedMs};signal('lock');void sendPending();},[shown,signal,sendPending]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||target.isContentEditable||['INPUT','SELECT','TEXTAREA'].includes(target.tagName)||leaveOpen||settingsOpen)return;if(['1','2','3','4'].includes(e.key)&&roomRef.current?.phase==='playing'){e.preventDefault();answer(Number(e.key)-1);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[answer,leaveOpen,settingsOpen]);
 async function create(forcedConfig?:Config){if(busy||!player.loaded)return;if(!name.trim()){setError('Choose a player name first.');return;}setBusy(true);setError('');setShowArt(false);const draft=createDraft.current||(createDraft.current={roomId:roomId(),token:randomToken(),invite:randomToken(),name,profileEpoch:player.epoch(),config:{...(forcedConfig||config)}});try{const data=await request({action:'create',...draft});remember({roomId:draft.roomId,token:draft.token,invite:draft.invite,profileEpoch:draft.profileEpoch});accept(data);createDraft.current=null;if(draft.config.opponent==='bot'&&data.room.phase==='waiting'){const m=clock.current.samples?clock.current:await calibrate();accept(await request({action:'ready',roomId:draft.roomId,token:draft.token,roundId:null,rttMs:m.rttMs,jitterMs:m.jitterMs}));}}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function join(){if(busy||!player.loaded)return;if(!name.trim()){setError('Choose a player name first.');return;}setShowArt(false);setBusy(true);setError('');try{const info=parseInvite(joinLink);const draft=joinDraft.current||(joinDraft.current={...info,token:randomToken(),name,profileEpoch:player.epoch()});const data=await request({action:'join',...draft});remember({roomId:draft.roomId,token:draft.token,profileEpoch:draft.profileEpoch});accept(data);joinDraft.current=null;}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function ready(){setBusy(true);setError('');try{const m=await calibrate();setBusy(false);await mutate('ready',{roundId:roomRef.current?.round?.id||null,rttMs:m.rttMs,jitterMs:m.jitterMs});}catch(e:any){setError('Could not check the connection. Try ready again.');setBusy(false);}}
 async function copyInvite(){const c=credentials;if(!c?.invite)return;const link=`${window.location.origin}/?room=${c.roomId}#invite=${c.invite}`;try{await navigator.clipboard.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setNote(link);}}
 const facets=catalogue?.facets||[];
 const pool=useMemo(()=>facets.filter((q:any)=>['domain','region','topic','subtopic','difficulty'].every(k=>(config as any)[k]==='all'||q[k]===(config as any)[k])),[facets,config]);
 const topics=catalogue?.topics?.filter((t:any)=>config.domain==='all'||t.domain===config.domain)||[];
 const subtopics=[...new Set<string>(facets.filter((q:any)=>(config.topic==='all'||q.topic===config.topic)&&(config.domain==='all'||q.domain===config.domain)).map((q:any)=>q.subtopic))];
 const change=(patch:Partial<Config>)=>{createDraft.current=null;setConfig(c=>({...c,...patch}));};
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const register=(tool:any)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'read_duel_status',description:'Read the visible room phase, scores, and demo coin balances. Does not reveal private answers or access tokens.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:any){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');const r=roomRef.current;return r?{phase:r.phase,scores:r.scores,balances:r.balances,round:r.roundIndex+1}:{phase:'lobby'};}});
  register({name:'configure_duel_mode',description:'Choose Quick Draw, Triple Threat or The Gauntlet in the lobby. Does not create a room or reserve coins.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['quick','trilogy','gauntlet']}},required:['mode'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:any){if(!input||Object.keys(input).length!==1||!['quick','trilogy','gauntlet'].includes(input.mode))throw new Error('Choose quick, trilogy or gauntlet.');if(roomRef.current)throw new Error('Leave the current room before changing mode.');createDraft.current=null;setConfig(c=>({...c,mode:input.mode}));setTab('arena');await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {mode:input.mode,roomCreated:false};}});
  return()=>lifecycle.abort();
 },[]);
 const active=room&&['playing','scheduled'].includes(phase),isLocked=!!rd?.answerLocked?.[room?.seat]||locked.current;
 const modeInfo=MODES.find(m=>m.id===config.mode)||MODES[0];
 const matchMode=MODES.find(m=>m.id===room?.config.mode)||MODES[0];
 const canPlay=player.loaded&&!!catalogue&&pool.length>=modeInfo.rounds&&!!name.trim();
 const chooseCollection=(domain:string,topic:string)=>{change({domain,topic,subtopic:'all',region:'all',difficulty:'all'});setJoinView(false);setTab('arena');window.scrollTo({top:0,behavior:'instant'});};
 const go=(next:string)=>{setTab(next);window.scrollTo({top:0,behavior:'instant'});};
 const missionAction=(action:string)=>{if(action.startsWith('topic:')){const topic=action.slice(6),item=catalogue?.topics.find((t:any)=>t.topic===topic);if(item)chooseCollection(item.domain,topic);return;}if(['quick','trilogy','gauntlet'].includes(action)){setJoinView(false);change({mode:action});go('arena');}else go(action==='play'?'discovery':action==='recall'?'discovery':'journal');};
 const clearFilters=()=>change({domain:'all',topic:'all',subtopic:'all',region:'all',difficulty:'all'});
 const leaveOrBack=()=>room?.settled?resetLocal():setLeaveOpen(true);
 const openExpedition=(id:string|null)=>{setSelectedExpedition(id);go('journeys');};
 const quickDuel=(mode:string,topic='all')=>{const chosenTopic=catalogue?.topics.find((t:any)=>t.topic===topic);const next={...INITIAL,mode,topic,domain:chosenTopic?.domain||'all'};createDraft.current=null;setConfig(next);setJoinView(false);go('arena');void create(next);};
 const setupDuel=(intent:'friend'|'join'|'settings'='settings')=>{setJoinView(intent==='join');if(intent==='friend')change({opponent:'friend'});go('arena');};
 return <div className={`site-shell arcade-shell rivalry-shell journey-shell skin-${player.passport.skin} ${active?'active-game':''}`}>
 <a className="skip-link" href="#main-content">Skip to content</a>
 <header className="topbar"><a href="/" className="brand" aria-label="Fact Duel home" onClick={e=>{e.preventDefault();if(room)leaveOrBack();else go('home');}}><Zap/><span>FACT<span>//</span>DUEL</span></a><span className="edition-label">THE KNOWLEDGE ARENA</span><div className="top-controls"><span className="private-badge"><Lock size={13}/>Private playtest</span><Button variant="ghost" size="icon" onClick={()=>setSound(v=>!v)} aria-label={sound?'Mute sounds':'Enable sounds'} aria-pressed={sound}>{sound?<Volume2/>:<VolumeX/>}</Button><Button variant="ghost" size="icon" onClick={()=>setSettingsOpen(true)} aria-label="Open settings" disabled={!!active}><Settings/></Button></div></header>
 <div className="app-frame"><nav className="side-nav" aria-label="Main navigation">{[['home','Clubhouse',Compass],['journeys','Expeditions',Flag],['arena','Duels',Swords],['passport','Player',Trophy],['journal','Vault',BookOpen]].map(([id,label,Icon]:any)=><Button key={id} variant="ghost" className={tab===id?'nav-active':''} aria-current={tab===id?'page':undefined} disabled={!!room} onClick={()=>go(id)}><Icon/><span>{label}</span></Button>)}<div className="nav-bottom"><span>For the fans.<br/>For the know-it-alls.</span><a href="/studio" tabIndex={room?-1:undefined} aria-disabled={!!room} onClick={e=>{if(room)e.preventDefault();}}><Compass/>Product studio<ArrowUpRightIcon/></a></div></nav>
 <main id="main-content" className="main-shell">{!room&&player.storageError&&<p className="notice-box" role="status">{player.storageError}</p>}<div className="announcements" aria-live="polite">{error&&<div role="alert" className="error-box">{error}{!catalogue&&!room&&<Button variant="outline" onClick={()=>{setError('');request({action:'catalogue'}).then(d=>setCatalogue(d.catalogue)).catch(e=>setError(e.message));}}>Retry loading</Button>}</div>}{note&&<div className="notice-box"><span>{note}</span><Button variant="ghost" size="icon" aria-label="Dismiss notice" onClick={()=>setNote('')}><X/></Button></div>}</div>
 {!room&&tab==='home'&&<Clubhouse player={player} name={name} ready={player.loaded&&!!catalogue&&!!name.trim()} busy={busy} onRoute={openExpedition} onDuel={quickDuel} onSetup={setupDuel} onExplore={()=>go('collections')} onPassport={()=>go('passport')} onVault={()=>go('journal')} onDiscovery={()=>go('discovery')} onShowroom={()=>go('showroom')}/>}
 {!room&&tab==='journeys'&&<Expeditions selected={selectedExpedition} onSelect={openExpedition} player={player} onDuel={quickDuel} onBack={()=>go('home')} signal={signal}/>}
 {!room&&tab==='arena'&&<>
 <div className="rivalry-heading"><div><p className="eyebrow">THE KNOWLEDGE ARENA</p><h1>Your knowledge. Your next win.</h1></div><button className="profile-chip" onClick={()=>go('passport')}><span className="profile-monogram">{name.charAt(0).toUpperCase()||'P'}</span><span><strong>{name}</strong><small>{player.summary.points} activity pts · on this device</small></span><ChevronRight size={16}/></button></div>
 <div className="rivalry-lobby">
 <section className={`duel-builder format-${config.mode}`} aria-labelledby="match-setup"><div className="builder-heading"><span className="eyebrow">YOUR NEXT MATCH</span><span className="free-tag">FREE PLAY</span></div><div className="builder-format"><div className="builder-format-title"><h2 id="match-setup">{joinView?'Join a friend.':modeInfo.name}</h2>{!joinView&&<Button variant="ghost" onClick={()=>{const target=document.getElementById('formats');target?.focus();target?.scrollIntoView({block:'center'});}}>Change<ChevronDown size={15}/></Button>}</div><p>{joinView?'Bring the full invitation link.':(FORMAT_COPY as any)[config.mode].rule}</p></div><div className="segmented opponent-tabs"><Button variant="ghost" aria-pressed={!joinView&&config.opponent==='bot'} onClick={()=>{setJoinView(false);change({opponent:'bot'});}}><Bot/>Bot</Button><Button variant="ghost" aria-pressed={!joinView&&config.opponent==='friend'} onClick={()=>{setJoinView(false);change({opponent:'friend'});}}><Users/>Friend</Button><Button variant="ghost" aria-pressed={joinView} onClick={()=>setJoinView(true)}>Join</Button></div>
 {joinView?<><div className="field"><Label htmlFor="join-name">Your name</Label><Input id="join-name" value={name} onChange={e=>{setName(e.target.value);joinDraft.current=null;}} maxLength={24} autoComplete="nickname"/></div><div className="field"><Label htmlFor="invite">Invitation link</Label><Input id="invite" value={joinLink} onChange={e=>{setJoinLink(e.target.value);joinDraft.current=null;}} placeholder="Paste your friend’s invitation"/></div><Button className="primary-action wide match-launch" onClick={join} disabled={!player.loaded||busy||!name.trim()||!joinLink.trim()}>{busy?'Joining…':'Join the duel'}<ArrowRight/></Button><p className="small-note">Both screens need access to this private site. Room invitations do not grant site access.</p></>:<>
 <div className="lobby-versus"><div><span className="seat-avatar you">{name.charAt(0).toUpperCase()||'P'}</span><strong>You</strong></div><span className="versus-mark">VS</span><div><span className="seat-avatar opponent">{config.opponent==='bot'?<Bot/>:<Users/>}</span><strong>{config.opponent==='bot'?'Lucky Guess':'Your friend'}</strong><small>{config.opponent==='bot'?'RANDOM BOT':'INVITE ONLY'}</small></div></div>
 <Button className="primary-action wide match-launch" onClick={()=>create()} disabled={busy||!canPlay}><Zap/>{busy?'Setting the arena…':!player.loaded?'Loading your player…':config.opponent==='bot'?'Play Lucky Guess':'Create friend duel'}<ArrowRight/></Button><div className="launch-terms"><span><Timer size={14}/>{config.duration}s per question</span><span><Coins size={14}/>{config.stake?`${config.stake} demo coins`:'No entry cost'}</span></div>
 <p className="live-round-note">Live rounds: stay on this screen. Switching away cancels and refunds.</p>
 <button className="topic-select-row" onClick={()=>go('collections')}><span><small>PLAYING</small><strong>{config.topic==='all'?(config.domain==='all'?'Sports + science mix':config.domain==='sports'?'All sports':'All science'):config.topic}</strong></span><span>Change<ChevronRight size={16}/></span></button>
 <details className="match-options"><summary>Match settings <span>name · timer · topics · coins</span></summary><div className="field"><Label htmlFor="player-name">Your player name</Label><Input id="player-name" value={name} onChange={e=>{setName(e.target.value);createDraft.current=null;}} maxLength={24} autoComplete="nickname" placeholder="Choose a name"/></div><div className="options-grid"><Picker label="Territory" value={config.domain} onChange={v=>change({domain:v,topic:'all',subtopic:'all',region:'all'})} items={[["all","Sports + science"],["sports","Sports"],["science","Science"]]}/><Picker label="Topic" value={config.topic} onChange={v=>change({topic:v,subtopic:'all'})} items={[["all","All topics"],...topics.map((t:any)=>[t.topic,t.topic] as [string,string])]}/><Picker label="Region" value={config.region} onChange={v=>change({region:v})} items={['all','US','India','Europe','Global'].map(v=>[v,v==='all'?'All regions':v])}/><Picker label="Level" value={config.difficulty} onChange={v=>change({difficulty:v})} items={['all','simple','expert','extreme'].map(v=>[v,v==='all'?'All levels':v])}/><Picker label="Subtopic" value={config.subtopic} onChange={v=>change({subtopic:v})} items={[["all","Any subtopic"],...subtopics.map(v=>[v,v] as [string,string])]}/><Picker label="Time per question" value={String(config.duration)} onChange={v=>change({duration:Number(v)})} items={[["10","10 seconds"],["15","15 seconds"],["30","30 seconds"]]}/></div><Label className="entry-label">Optional demo coins · once per match</Label><div className="stakes">{[0,10,25,50,100].map(stake=><Button key={stake} variant={stake===config.stake?'default':'outline'} aria-pressed={stake===config.stake} onClick={()=>change({stake})}>{stake||'Free'}</Button>)}</div><p className="small-note">Coins have no cash value. Draws refund the entry. Every new room starts with 1,000 per player.</p></details>

 <div className="pool-count"><span>{catalogue?`${pool.length} questions in this selection`:'Loading questions…'}</span><span>{modeInfo.rounds} needed</span></div>{catalogue&&pool.length<modeInfo.rounds&&<div className="pool-warning" role="status">Not enough questions for {modeInfo.name}.<Button variant="link" onClick={clearFilters}>Use all topics</Button>{pool.length>0&&config.mode!=='quick'&&<Button variant="link" onClick={()=>change({mode:'quick'})}>Play one question</Button>}</div>}
 <details className="fair-play"><summary><ShieldCheck size={15}/>Know the rules<ChevronDown size={15}/></summary><p>{config.opponent==='bot'?`Lucky Guess chooses each answer with equal probability and waits a random 1–${config.duration-.5}s. It never reacts to your answer.`:'Each player sees the full question on their own screen. You both ready up before a round.'}</p><p>Correctness comes first, then reported answer time. Both correct within 150 ms is a draw. Stay on this screen: switching away or reloading during a round cancels and refunds the match.</p><p>Coins are free simulations and have no cash value.</p><Button variant="link" onClick={()=>go('rules')}>Full rules & timing</Button></details>
 </>}
 </section>
 <section className={`arena-poster format-${config.mode}`} aria-label="FACT DUEL arena"><img src="/art/rivalry-stage.webp" alt="Polished lightning token and a metallic sports sphere surrounded by luminous science orbits" width="1672" height="941"/><div className="poster-copy"><span className="poster-label">SPORTS × SCIENCE</span><h2>KNOW IT.<br/><em>PROVE IT.</em></h2><p>One rival. Four answers.<br/>Make yours count.</p></div><div className="poster-bottom"><span><Swords size={15}/>1 v 1 knowledge duels</span><button onClick={()=>go('showroom')}><Atom size={15}/>Enter the 3D arena<ArrowRight size={15}/></button></div></section>
 <section id="formats" tabIndex={-1} className="format-section" aria-label="Choose your format"><div className="minor-heading"><h2>Choose your format</h2><span>One attempt per question</span></div><div className="format-cards">{MODES.map(m=>{const Icon=m.icon,f=(FORMAT_COPY as any)[m.id];return <button key={m.id} className={`format-card format-${m.id} ${config.mode===m.id&&!joinView?'selected':''}`} aria-pressed={config.mode===m.id&&!joinView} onClick={()=>{setJoinView(false);change({mode:m.id});}}><span className="format-top"><Icon/><span>{f.number}</span></span><small>{f.tag}</small><strong>{m.name}</strong><p>{f.short}</p><span className="format-select">{config.mode===m.id&&!joinView?<><Check size={15}/>Selected</>:<>Choose format<ArrowRight size={15}/></>}</span></button>;})}</div></section>
 </div>
 <div className="home-secondary"><section className="topic-spotlight"><div className="minor-heading"><h2>Pick your obsession</h2><Button variant="ghost" onClick={()=>go('collections')}>All subjects<ArrowRight size={16}/></Button></div><div className="topic-chips">{[['Cricket',Flag,'sports'],['Football',CircleDot,'sports'],['Basketball',Trophy,'sports'],['Space',Rocket,'science'],['Physics',Atom,'science']].map(([topic,Icon,domain]:any)=><button key={topic} aria-pressed={config.topic===topic} onClick={()=>chooseCollection(domain,topic)}><Icon size={18}/>{topic}<span>{catalogue?.topics.find((t:any)=>t.topic===topic)?.count??'…'}</span></button>)}</div><div className="form-row"><span>YOUR LAST FIVE</span>{journal.matches.length?journal.matches.slice(0,5).reverse().map((m:any)=><span className={`form-result form-${m.outcome}`} key={m.id} title={`${m.bot?'Bot':'Friend'} match: ${m.outcome}`}>{m.outcome==='win'?'W':m.outcome==='loss'?'L':'D'}</span>):<p>Your first result goes here.</p>}<button onClick={()=>go('journal')}>Match history<ArrowRight size={14}/></button></div></section><section className="warmup-card"><span className="warmup-icon"><Brain/></span><div><span className="eyebrow">NO CLOCK. NO OPPONENT.</span><h2>Warm up your brain.</h2><p>Three facts, at your pace.</p></div><Button variant="outline" onClick={()=>go('discovery')}>Start Discovery<ArrowRight size={16}/></Button></section></div>
 <div className="home-foot"><button onClick={()=>go('passport')}><Compass size={16}/>{player.summary.complete} / 3 side quests complete<span>Open Passport<ChevronRight size={15}/></span></button><p>{catalogue?.count??'…'} sourced sample questions · Private playtest</p></div>
 </>}
 {!room&&tab==='showroom'&&<section className="arena-showroom"><Button variant="ghost" onClick={()=>go('arena')}><ArrowLeft/>Back to play</Button><div className="section-heading"><div><p className="eyebrow">THE ARENA OBJECT</p><h1>Take it for a spin.</h1></div><span className="tag">3D is optional</span></div>{showArt?<ArcadeStage/>:<Button onClick={()=>setShowArt(true)}>Show arena artwork</Button>}<p className="small-note">Drag horizontally or use the rotate controls. Switch back to the static view whenever you like. The scene is removed before a match starts.</p></section>}
 {!room&&tab==='collections'&&<Collections catalogue={catalogue} passport={player.passport} onChoose={chooseCollection}/>}
 {!room&&tab==='passport'&&<><ExpeditionCase player={player} onOpen={openExpedition}/><Passport player={player} catalogue={catalogue} onAction={missionAction}/></>}
 {!room&&tab==='discovery'&&<Discovery topic={config.topic} player={player} onBack={()=>go('arena')}/>}
 {!room&&tab==='journal'&&<Journal journal={journal} issues={player.profile.issues} storageOK={storageOK} onSave={saveFact} onOpen={player.open} onRecall={player.recall} onExport={player.exportAll} epoch={player.profile.epoch} loaded={player.loaded} onPlay={()=>go('discovery')}/>}
 {!room&&tab==='rules'&&<><Playbook/><Button variant="outline" onClick={()=>go('timing')}><Timer/>Explore the timing lab<ArrowRight/></Button></>}
 {!room&&tab==='timing'&&<><Button variant="ghost" onClick={()=>go('rules')}><ArrowLeft/>Back to playbook</Button><TimingLab/></>}
 {room&&<section className="room-screen"><div className="room-bar"><Button variant="ghost" onClick={leaveOrBack}><ArrowLeft/>{room.settled?'Back to play':'Leave'}</Button><span className="tag">{matchMode.name} · {room.roundIndex+1} / {matchMode.rounds}</span><span className={`connection ${connected?'':'disconnected'}`}><Wifi size={15}/><span className="connection-text">{connected?'Connected':'Reconnecting…'}</span></span></div><DuelHUD room={room}/>
 {['waiting','between'].includes(phase)&&<><div className="ready-panel"><span className="round-symbol">{phase==='between'?<CheckCircle2/>:room.players[1]?.kind==='bot'?<Bot/>:<Users/>}</span><p className="eyebrow">{phase==='between'?'A MOMENT TO LEARN':'THE CHALLENGE IS SET'}</p><h1>{phase==='between'?(rd.result.winner===null?'Honours even.':rd.result.winner===room.seat?'That round is yours.':'A fact for next time.'):room.players[1]?'Ready for the first question?':'Invite your rival.'}</h1><p>{phase==='between'?'Review the explanation below, then start the next round when you are ready.':room.players[1]?.kind==='bot'?'Lucky Guess is ready. Its choices and response times are random.':room.players[1]?'You both decide when to begin. One attempt each after the countdown. Stay here during play; switching away cancels the match.':'Share the link with someone who can access this private site, or add a practice bot.'}</p><div className="ready-actions">{credentials?.invite&&room.players[1]?.kind!=='bot'&&<Button variant="outline" onClick={copyInvite}>{copied?<Check/>:<Copy/>}{copied?'Copied':'Copy room invitation'}</Button>}{!room.players[1]&&room.seat===0&&<Button variant="outline" onClick={()=>mutate('add_bot')} disabled={busy}><Bot/>Add practice bot</Button>}</div><div className="ready-status">{room.players.map((p:any,i:number)=><span key={i}><span className={`ready-indicator ${p?.ready?'ready':''}`}>{p?.ready?<Check size={12}/>:null}</span>{p?.name||'Open seat'} · {p?.ready?'Ready':p?'Not ready':'Waiting'}</span>)}</div><Button className="primary-action" onClick={ready} disabled={busy||!room.players[1]||room.players[room.seat].ready}>{busy?'Checking connection…':room.players[room.seat].ready?'Waiting for your rival…':phase==='between'?`Start round ${room.roundIndex+2}`:'I’m ready'}<ArrowRight/></Button><p className="small-note">{phase==='waiting'?`${room.config.stake} demo coins each, once per match. Draws refund both.`:'Your original match entry stays reserved. No new entry.'}</p></div>{phase==='between'&&rd?.result&&<RoundReview room={room} player={player}/>}</>}
 {['scheduled','playing'].includes(phase)&&!question&&<div className="countdown-panel"><p className="eyebrow">ONE QUESTION. ONE ATTEMPT.</p><h1>{countdown>0?'Here we go.':'Opening your question…'}</h1><strong aria-hidden="true">{countdown>0?countdown:<Radio/>}</strong><p role="status">{countdown>0?'Get ready for your question.':'Waiting for the question to arrive.'}</p></div>}
 {['scheduled','playing'].includes(phase)&&question&&!rd.result&&<div className="question-area"><RoundClock label={`${question.topic} / ${question.subtopic}`} start={startMark} roundId={rd.id} duration={room.config.duration*1000} running={shown} onExpire={expire}/><div className="question-card" style={{visibility:shown?'visible':'hidden'}}><span className="question-mode-label">{(FORMAT_COPY as any)[room.config.mode].tag}<span>{question.difficulty}</span></span><h1>{question.question}</h1><div className="answer-grid">{question.options.map((option:string,i:number)=><Button key={`${question.id}-${i}`} variant="outline" className={`answer-button ${chosen===i?'chosen':''}`} aria-pressed={chosen===i} disabled={!shown||isLocked||remaining<=0} onClick={()=>answer(i)}><kbd>{i+1}</kbd><span>{option}</span>{chosen===i&&<Lock size={17}/>}</Button>)}</div></div><div className="answer-status" role="status">{isLocked?<><Lock size={16}/>{rd.answerLocked[room.seat]?'Received. Your answer is sealed.':answerPending?'Sending your locked answer…':'Your choice is locked on this device.'}</>:remaining<=0?'Time is up. Waiting for the round to close.':'Tap once or press 1–4. Your first answer locks.'}</div>{isLocked&&<p className="waiting-note">{rd.answerLocked[1-room.seat]?'Both answers are in. Comparing…':'Waiting for the other attempt or its time limit.'}</p>}{pending.current&&!rd.answerLocked[room.seat]&&!answerPending&&<Button className="retry-button" variant="outline" onClick={sendPending}>Retry sending this answer</Button>}<p className="small-note">Answers lock on tap/click release or a 1–4 keypress. You get one attempt. A close result can be a draw.</p></div>}
 {['complete','cancelled'].includes(phase)&&<div className="final-panel"><MatchFinish room={room} onReplay={()=>{const next={...room.config};setConfig(next);resetLocal();go('arena');if(next.opponent==='bot')void create(next);}} onVault={()=>{resetLocal();go('journal');}} onFinish={()=>{resetLocal();go('passport');}}/>{completedRounds(room).length>0&&<RoundReview room={room} player={player}/>}</div>}
 </section>}
 </main></div>
 {!room&&<footer><span>KNOW IT. PROVE IT.</span><span><button className="footer-rules" onClick={()=>go('rules')}>Play rules</button> · Free simulated coins · Private playtest</span><a href="/studio">Research & roadmap</a></footer>}
 <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>Make yourself at home.</DialogTitle><DialogDescription>Preferences stay on this device. Sounds are optional.</DialogDescription></DialogHeader><div className="setting-row"><Label htmlFor="sound-setting">Game sounds</Label><Switch id="sound-setting" checked={sound} onCheckedChange={setSound}/></div><div className="setting-row"><Label htmlFor="theme-setting">Light theme</Label><Switch id="theme-setting" checked={light} onCheckedChange={setLight}/></div><div className="setting-row"><Label htmlFor="art-setting">Showroom artwork</Label><Switch id="art-setting" checked={showArt} onCheckedChange={v=>{setShowArt(v);try{localStorage.setItem('fact-duel-art',v?'on':'off');}catch{}}}/></div><div className="field"><Label>Sound volume</Label><Slider aria-label="Sound volume" value={[volume*100]} min={0} max={100} step={5} onValueChange={v=>setVolume(v[0]/100)}/></div><Button variant="outline" disabled={!sound} onClick={()=>signal('win')}><Volume2/>Preview sound</Button><div className="settings-storage"><h3>Your local activity</h3><p>Expedition progress and stamps, journal, saved question issues, passport points, missions and card finishes stay in this browser. Export them before resetting. Theme and sound preferences are kept.</p><Button variant="outline" disabled={!player.loaded} onClick={player.exportAll}>Export all activity</Button><Button variant="outline" disabled={!player.loaded} onClick={()=>{setSettingsOpen(false);setClearOpen(true);}}>Reset local activity</Button></div></DialogContent></Dialog>
 <AlertDialog open={leaveOpen} onOpenChange={setLeaveOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Leave this match?</AlertDialogTitle><AlertDialogDescription>The room ends for both players. Unsettled entries are refunded; completed payouts remain final.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep playing</AlertDialogCancel><AlertDialogAction onClick={leave}>Leave & refund</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={clearOpen} onOpenChange={setClearOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reset your local activity?</AlertDialogTitle><AlertDialogDescription>This removes expedition progress, scores and stamps, the journal, saved facts, saved question issues, passport points, missions and earned card finishes in this browser. Export first to keep a copy. Theme, sound preferences and room coins are unaffected.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep activity</AlertDialogCancel><AlertDialogAction disabled={!player.loaded} onClick={clearJournal}>Reset local activity</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function ArrowUpRightIcon(){return <ChevronRight size={14}/>;}
function RoundClock({label,start,roundId,duration,running,onExpire}:{label:string;start:{current:{roundId:string;at:number}|null};roundId:string;duration:number;running:boolean;onExpire:()=>void}){
 const [left,setLeft]=useState(duration);
 useEffect(()=>{setLeft(duration);if(!running)return;let done=false;const tick=()=>{const mark=start.current;if(!mark||mark.roundId!==roundId)return;const remaining=Math.max(0,duration-(performance.now()-mark.at));setLeft(remaining);if(remaining===0&&!done){done=true;onExpire();}};tick();const timer=setInterval(tick,50);return()=>clearInterval(timer);},[start,roundId,duration,running,onExpire]);
 return <><div className="question-top"><span>{label}</span><span className="count-timer" aria-hidden="true"><Timer/>{(left/1000).toFixed(1)}<small>s</small></span></div><div className="timer-track" aria-hidden="true"><span style={{width:`${100*left/duration}%`}}/></div></>;
}

function TimingLab(){const[a,setA]=useState(2200),[b,setB]=useState(2300),[networkA,setNetworkA]=useState(500),[networkB,setNetworkB]=useState(40);const serverA=a+networkA,serverB=b+networkB;const winner=(x:number,y:number,band=0)=>Math.abs(x-y)<=band?'Draw':x<y?'Player A':'Player B';return <section className="timing-lab"><p className="eyebrow">TIMING LAB · ILLUSTRATIVE MODEL</p><h1>A faster packet isn't<br/>always a faster answer.</h1><p>Change response time and total transport delay. This model assumes honest client clocks and excludes display/input variation.</p><div className="lab-controls">{[['Player A response',a,setA,5000],['Player B response',b,setB,5000],['Player A network total',networkA,setNetworkA,1500],['Player B network total',networkB,setNetworkB,1500]].map(([label,value,fn,max]:any)=><div className="slider-field" key={label}><Label>{label}<strong>{value} ms</strong></Label><Slider aria-label={label} value={[value]} min={0} max={max} step={10} onValueChange={v=>fn(v[0])}/></div>)}</div><div className="table-scroll"><table><thead><tr><th>Comparison</th><th>Player A</th><th>Player B</th><th>Result</th></tr></thead><tbody><tr><td>Server elapsed envelope</td><td>{serverA} ms</td><td>{serverB} ms</td><td>{winner(serverA,serverB)}</td></tr><tr><td>Reported screen time</td><td>{a} ms</td><td>{b} ms</td><td>{winner(a,b)}</td></tr><tr><td>Screen time + 150 ms tie band</td><td>{a} ms</td><td>{b} ms</td><td>{winner(a,b,150)}</td></tr></tbody></table></div><div className="protocol-note"><ShieldCheck/><div><h2>The trade-off stays visible.</h2><p>Measuring locally avoids charging a player for packet delivery time. A modified browser can still lie about that measurement. This prototype checks plausibility and refunds inconsistent timing; a ranked service needs stronger validation and an explicit uncertainty policy.</p></div></div></section>}
function Playbook(){return <section className="playbook"><p className="eyebrow">TWO SCREENS, CLEAR RULES</p><h1>How an online duel works.</h1><div className="rule-grid">{[['1. Choose your rival','Practice bot works in all three modes without a second screen. It picks each answer uniformly at random and waits a random 1 second to half a second before the time limit. Choices and times are fixed before play; it does not adapt to your answers. Or create a friend room and share its invite with a permitted tester.'],['2. Ready to begin','Start practice begins a short countdown. Friends press ready to start. A practice bot is automatically ready for each round; friends ready on both screens. Both demo entries are reserved once per match.'],['3. One attempt each','Your screen measures from its reveal marker to activation: tap/click release or a 1–4 keypress. Your first accepted answer locks. Both answers remain sealed until both players finish or time runs out.'],['4. Compare the durations','A sole correct answer wins. If both are correct, the shorter reported screen duration wins unless the difference is at most 150 ms, which is a draw.'],['5. Check the envelope','The server timestamps an answer when its database write succeeds and applies a capped transport allowance of 0.5–2 seconds. Implausible timings void and refund the match. These checks cannot prove client honesty.'],['6. Learn and replay','The result includes the fact, explanation, source and both response times. Bot rows are labelled as scheduled simulations. Start another room only when you choose.']].map(([title,text])=><article key={title}><h2>{title}</h2><p>{text}</p></article>)}</div><div className="protocol-note"><ShieldCheck/><div><h2>Casual play, with boundaries.</h2><p>Quick Draw has one round. Triple Threat has up to three: first to two wins, otherwise the higher score after three wins. The Gauntlet plays all five questions and the higher final score wins. Tied scores refund both entries. Leaving, reloading after reveal, or hiding an active match cancels and refunds it. Reading sources between rounds is fine.</p><p>Coins are free, non-transferable and have no cash value. Each room begins with 1,000 per player. Rooms expire after two hours. There is no cash-out, purchase, public matchmaking or verified global rank.</p><p>A web page cannot guarantee zero latency, physical display timing or an unmodified client. This is a private playtest. The Product Studio separates implemented features from plans and untested scale. Discovery offers three untimed teaching cards from the same sample, even before your first duel. Vault recall revisits encountered facts. Passport points describe browser-local activity and never change competitive rules.</p></div></div></section>}
