'use client';
import {Button} from '@/components/ui/button';
import {ArrowRight,Check,Compass,BookOpen,Orbit,Lock,Sparkles,Flag,Layers} from 'lucide-react';
import {TOPIC_STYLE} from './collections';
const FINISHES=[{id:'classic',name:'Original',copy:'Yours from the start.'},{id:'orbit',name:'Orbit',copy:'Complete First field notes.'},{id:'grid',name:'Field grid',copy:'Complete Field notes.'},{id:'rally',name:'Rally',copy:'Complete The mode tour.'}];
export function MissionStrip({summary,onOpen}:{summary:any;onOpen:()=>void}){const mission=summary.missions.find((m:any)=>!m.complete)||summary.missions[0],done=mission.steps.filter((s:any)=>s.done).length;return <button className="mission-strip" onClick={onOpen}><span className="mini-stamp"><Compass/></span><span><small>YOUR NEXT SIDE QUEST</small><strong>{mission.complete?'Passport complete. Keep exploring.':mission.name}</strong></span><span className="mission-mini-progress">{done}/{mission.steps.length}<ArrowRight size={16}/></span></button>;}
export function Passport({player,catalogue,onAction}:{player:any;catalogue:any;onAction:(s:string)=>void}){
 const {passport:p,summary:s}=player;const next=s.next,percent=next?Math.min(100,100*(s.points-s.tier.at)/(next.at-s.tier.at)):100;
 return <section className={`passport-page skin-${p.skin}`}><div className="section-heading"><div><p className="eyebrow">NO DEADLINES. JUST A LITTLE DIRECTION.</p><h1>Your player passport.</h1></div><Button variant="outline" onClick={player.exportAll}><BookOpen/>Export activity</Button></div><p className="muted">Finite missions and card finishes, earned by exploring. Saved in this browser. No streak to lose, and no advantage in a duel.</p><div className="passport-id"><div className="passport-emblem"><Orbit/><span>FD</span></div><div><p className="eyebrow">PLAYER CARD</p><h2>{s.tier.name}</h2><p>{s.points} activity points · {s.facts} distinct facts encountered</p><div className="passport-meter"><span style={{width:`${percent}%`}}/></div><small>{next?`${next.at-s.points} more activity points to ${next.name}`:'The last activity title is yours. There is no timer to maintain it.'}</small></div><span className="passport-stamp">PLAY IT<br/>YOUR WAY</span></div><p className="small-note">10 points per new fact, 5 for its first explanation opening, 5 for its first untimed attempt. Points are local activity—not verified skill. Your earlier journal stays here. Activity counts are local to this browser.</p>
 <div className="passport-section-heading"><h2>Choose a side quest.</h2><span>{s.complete} / {s.missions.length} complete</span></div><div className="mission-grid">{s.missions.map((m:any,i:number)=><article className={`mission-card ${m.complete?'mission-complete':''}`} key={m.id}><div className="mission-card-top"><span>0{i+1}</span>{m.complete?<span className="tag"><Check size={14}/>Complete</span>:<span className="tag">At your pace</span>}</div><h3>{m.name}</h3><p>{m.description}</p><ul>{m.steps.map((step:any,j:number)=><li key={j}><span className={`task-check ${step.done?'checked':''}`}>{step.done?<Check size={13}/>:j+1}</span><span>{step.label}</span></li>)}</ul><div className="mission-reward"><Sparkles size={17}/>{m.reward}</div><Button variant={m.complete?'outline':'default'} disabled={m.complete} onClick={()=>onAction(m.steps.find((step:any)=>!step.done)?.action||'play')}>{m.complete?'Finish unlocked':'Continue mission'}{m.complete?<Check/>:<ArrowRight/>}</Button></article>)}</div>
 <div className="passport-section-heading"><h2>Make the card yours.</h2><span>Cosmetics only</span></div><div className="finish-grid">{FINISHES.map(f=>{const unlocked=s.skins.includes(f.id);return <button className={`finish-card skin-${f.id} ${p.skin===f.id?'finish-selected':''}`} key={f.id} aria-pressed={p.skin===f.id} disabled={!unlocked||!player.loaded} onClick={()=>player.skin(f.id)}><span className="finish-preview"><span>FACT<br/>//DUEL</span>{!unlocked?<Lock size={18}/>:p.skin===f.id?<Check size={18}/>:<Sparkles size={18}/>}</span><strong>{f.name}</strong><small>{p.skin===f.id?'Equipped':unlocked?'Tap to equip':f.copy}</small></button>;})}</div>
 <div className="passport-section-heading"><h2>Your collection stamps.</h2><span>Encountered, not mastered</span></div><div className="collection-passport">{(catalogue?.topics||[]).map((topic:any)=>{const facts=Object.values(p.facts).filter((f:any)=>f.topic===topic.topic),opened=facts.filter((f:any)=>f.opened).length,recalled=facts.filter((f:any)=>f.recalled).length,Icon=TOPIC_STYLE[topic.topic]?.icon||Layers;return <article key={topic.topic}><Icon/><div><h3>{topic.topic}</h3><p>{facts.length} distinct facts encountered · {topic.count} in today’s sample</p><small>{opened} explanations opened · {recalled} untimed attempts on distinct facts</small></div><Button variant="ghost" size="icon" aria-label={`Choose ${topic.topic}`} onClick={()=>onAction(`topic:${topic.topic}`)}><ArrowRight/></Button></article>;})}</div><div className="passport-footnote"><Flag/><p>All game modes and collections are available from the start. Missions never unlock answers, extra time or coins. You can pause here and return whenever you want.</p></div></section>;
}
