/* SABHA — The Reading Room · Question Bank v1
 * All facts verbatim from panel-content.md §4–§5 (primary-source spine).
 * Shape: { id, mode:'duel'|'check'|'record', era, difficulty:1..5, q, options, answerIndex, source, note }
 */
window.SABHA_QUESTIONS = [
  /* ---------------- Duel bank (30) ---------------- */
  { id:'ih001', mode:'duel', era:'Ancient India', difficulty:2,
    q:"The Great Bath, one of the earliest public water tanks of the ancient world, is located at which Indus Valley site?",
    options:["Harappa","Mohenjo-daro","Dholavira","Lothal"], answerIndex:1,
    source:"Archaeological Survey of India / NCERT",

    sourceUrl:"https://asi.nic.in",
    note:"The Great Bath is the signature structure of Mohenjo-daro's citadel mound. Harappa, Dholavira and Lothal are sister Indus sites with their own distinct features." },
  { id:'ih002', mode:'duel', era:'Ancient India', difficulty:4,
    q:"Ashoka's expression of remorse after the Kalinga war is recorded in which of his Major Rock Edicts?",
    options:["Major Rock Edict VII","Major Rock Edict X","Major Rock Edict XIII","Major Rock Edict II"], answerIndex:2,
    source:"Archaeological Survey of India (Epigraphia Indica)",

    sourceUrl:"https://asi.nic.in",
    note:"Rock Edict XIII describes the Kalinga war and Ashoka's remorse. It is omitted at the Kalinga-region sites where the edicts were inscribed." },
  { id:'ih003', mode:'duel', era:'Medieval India', difficulty:3,
    q:"Construction of the Qutub Minar in Delhi was begun by which ruler?",
    options:["Iltutmish","Ghiyasuddin Balban","Qutb-ud-din Aibak","Alauddin Khalji"], answerIndex:2,
    source:"ASI / NCERT (Themes in Indian History, Part II)",

    sourceUrl:"https://asi.nic.in",
    note:"Qutb-ud-din Aibak began the tower; Iltutmish completed it. Alauddin Khalji added the Alai Darwaza to the same complex." },
  { id:'ih004', mode:'duel', era:'Medieval India', difficulty:3,
    q:"The Moroccan traveller Ibn Battuta, author of the Rihla, visited India during the reign of which sultan?",
    options:["Alauddin Khalji","Firoz Shah Tughlaq","Muhammad bin Tughlaq","Sikandar Lodi"], answerIndex:2,
    source:"NCERT (Themes in Indian History, Part II)",

    sourceUrl:"https://ncert.nic.in",
    note:"Ibn Battuta served at the court of Muhammad bin Tughlaq. His Rihla is a principal traveller's account of the fourteenth-century Sultanate." },
  { id:'ih005', mode:'duel', era:'Mughal Era', difficulty:2,
    q:"In the First Battle of Panipat (1526), Babur defeated which ruler?",
    options:["Rana Sanga","Ibrahim Lodi","Hemu","Mahmud Begada"], answerIndex:1,
    source:"NCERT / India Year Book",

    sourceUrl:"https://ncert.nic.in",
    note:"Panipat I (1526) ended Lodi rule and opened the Mughal era. Rana Sanga fell at Khanwa (1527); Hemu at Panipat II (1556)." },
  { id:'ih006', mode:'duel', era:'Mughal Era', difficulty:3,
    q:"The Ain-i-Akbari, a detailed statistical account of Akbar's empire, was written by whom?",
    options:["Badauni","Abul Fazl","Faizi","Birbal"], answerIndex:1,
    source:"NCERT (Themes in Indian History, Part II)",

    sourceUrl:"https://ncert.nic.in",
    note:"Abul Fazl wrote the Akbarnama; its third volume, the Ain-i-Akbari, records the empire's administration in detail. Badauni was his critical contemporary." },
  { id:'ih007', mode:'duel', era:'Colonial Period & Freedom Movement', difficulty:1,
    q:"In which year was the Battle of Plassey fought?",
    options:["1757","1764","1772","1746"], answerIndex:0,
    source:"NCERT / India Year Book",

    sourceUrl:"https://ncert.nic.in",
    note:"Plassey was fought in 1757; Buxar followed in 1764. The Treaty of Allahabad (1765) granted the Company the diwani of Bengal." },
  { id:'ih008', mode:'duel', era:'Colonial Period & Freedom Movement', difficulty:3,
    q:"The Regulating Act of 1773 designated the Governor of Bengal as the:",
    options:["Viceroy of India","Governor-General of Bengal","Governor-General of India","Secretary of State for India"], answerIndex:1,
    source:"India Year Book / NCERT",

    sourceUrl:"https://publicationsdivision.nic.in",
    note:"The Regulating Act of 1773 created the Governor-General of Bengal. The 'Governor-General of India' title dates to the Charter Act 1833; 'Viceroy' and 'Secretary of State' to 1858." },
  { id:'ih009', mode:'duel', era:'Colonial Period & Freedom Movement', difficulty:2,
    q:"The first session of the Indian National Congress (December 1885) was held in which city?",
    options:["Calcutta","Madras","Bombay","Lahore"], answerIndex:2,
    source:"India Year Book / NCERT",

    sourceUrl:"https://publicationsdivision.nic.in",
    note:"The first session met in Bombay on 28 December 1885, with W.C. Bonnerjee as president. The second session (1886) met in Calcutta." },
  { id:'ih010', mode:'duel', era:'Colonial Period & Freedom Movement', difficulty:3,
    q:"On which date did Mahatma Gandhi begin the Salt March from Sabarmati Ashram to Dandi?",
    options:["12 March 1930","6 April 1930","26 January 1930","8 August 1942"], answerIndex:0,
    source:"India Year Book",

    sourceUrl:"https://publicationsdivision.nic.in",
    note:"The march began 12 March 1930; the salt law was broken at Dandi on 6 April 1930. 26 January 1930 was Purna Swaraj Day and 8 August 1942 the Quit India resolution." },
  { id:'ih011', mode:'duel', era:'Constituent Assembly & Constitution-Making', difficulty:2,
    q:"The Constitution of India was adopted by the Constituent Assembly on:",
    options:["26 January 1950","26 November 1949","15 August 1947","9 December 1946"], answerIndex:1,
    source:"Constituent Assembly Debates / Ministry of Law & Justice",

    sourceUrl:"https://www.constitutionofindia.net",
    note:"Adopted 26 November 1949; commenced 26 January 1950. The Assembly's first sitting was 9 December 1946." },
  { id:'ih012', mode:'duel', era:'Constituent Assembly & Constitution-Making', difficulty:3,
    q:"The Constituent Assembly of India held its first sitting on:",
    options:["9 December 1946","13 December 1946","22 January 1947","29 August 1947"], answerIndex:0,
    source:"Constituent Assembly Debates",

    sourceUrl:"https://www.constitutionofindia.net",
    note:"First sitting: 9 December 1946. The Objectives Resolution was moved 13 December 1946 and adopted 22 January 1947; the Drafting Committee was set up 29 August 1947." },
  { id:'ih013', mode:'duel', era:'Constituent Assembly & Constitution-Making', difficulty:1,
    q:"Who chaired the Drafting Committee of the Constituent Assembly?",
    options:["Dr. Rajendra Prasad","Dr. B.R. Ambedkar","Jawaharlal Nehru","Alladi Krishnaswami Ayyar"], answerIndex:1,
    source:"Constituent Assembly Debates",

    sourceUrl:"https://www.constitutionofindia.net",
    note:"Dr. B.R. Ambedkar chaired the Drafting Committee. Dr. Rajendra Prasad was President of the Assembly; B.N. Rau was Constitutional Adviser." },
  { id:'ih014', mode:'duel', era:'Civics/Polity', difficulty:2,
    q:"The Election Commission of India was established on which date (now observed as National Voters' Day)?",
    options:["26 January 1950","25 January 1950","15 March 1950","25 October 1951"], answerIndex:1,
    source:"Election Commission of India",

    sourceUrl:"https://eci.gov.in",
    note:"The ECI was established on 25 January 1950, observed as National Voters' Day. The first general election ran from 25 October 1951 to 21 February 1952." },
  { id:'ih015', mode:'duel', era:'Civics/Polity', difficulty:2,
    q:"Article 32 of the Constitution, which Dr. Ambedkar called its 'heart and soul', guarantees the:",
    options:["Right to Equality","Right against Exploitation","Right to Constitutional Remedies","Right to Freedom of Religion"], answerIndex:2,
    source:"Constitution of India / Constituent Assembly Debates",

    sourceUrl:"https://legislative.gov.in/constitution-of-india/",
    note:"Article 32 guarantees the right to move the Supreme Court for enforcement of Fundamental Rights. Ambedkar called it the Constitution's 'heart and soul' in the Assembly debates." },
  { id:'ih016', mode:'duel', era:'Civics/Polity', difficulty:3,
    q:"The power and procedure for Parliament to amend the Constitution is laid down in:",
    options:["Article 356","Article 360","Article 368","Article 370"], answerIndex:2,
    source:"Constitution of India",

    sourceUrl:"https://legislative.gov.in/constitution-of-india/",
    note:"Article 368 governs constitutional amendment. Article 356 covers failure of constitutional machinery in a State; Article 360 financial emergency." },
  { id:'ih017', mode:'duel', era:'Civics/Polity', difficulty:4,
    q:"The Finance Commission, constituted by the President every fifth year or earlier, is provided for under:",
    options:["Article 263","Article 280","Article 292","Article 312"], answerIndex:1,
    source:"Constitution of India",

    sourceUrl:"https://legislative.gov.in/constitution-of-india/",
    note:"Article 280 provides for the Finance Commission. Article 263 provides for the Inter-State Council; Article 312 for All-India Services." },
  { id:'ih018', mode:'duel', era:'Post-Independence (1947–1977)', difficulty:2,
    q:"The Constitution (42nd Amendment) Act, 1976 — often called the 'Mini-Constitution' — added which words to the Preamble?",
    options:["Sovereign and Democratic","Socialist, Secular and Integrity","Fraternity and Justice","Federal and Parliamentary"], answerIndex:1,
    source:"Constitution of India",

    sourceUrl:"https://legislative.gov.in/constitution-of-india/",
    note:"The 42nd Amendment (1976) added 'Socialist, Secular and Integrity' to the Preamble. 'Sovereign Democratic Republic' and 'Justice... Fraternity' were in the original; 'Federal'/'Parliamentary' do not appear in it." },
  { id:'ih019', mode:'duel', era:'Post-Independence (1947–1977)', difficulty:3,
    q:"The National Emergency proclaimed in June 1975 on grounds of 'internal disturbance' was issued under:",
    options:["Article 352","Article 356","Article 360","Article 365"], answerIndex:0,
    source:"Constitution of India / Gazette of India (proclamation of 25 June 1975)",

    sourceUrl:"https://legislative.gov.in/constitution-of-india/",
    note:"The proclamation of 25 June 1975 was issued under Article 352 and revoked on 21 March 1977. The general election followed in March 1977." },
  { id:'ih020', mode:'duel', era:'Post-Independence (1947–1977)', difficulty:3,
    q:"How many major commercial banks were nationalised by the ordinance of 19 July 1969?",
    options:["6","14","20","8"], answerIndex:1,
    source:"RBI history",

    sourceUrl:"https://www.rbi.org.in",
    note:"Fourteen banks were nationalised on 19 July 1969; six more followed in 1980, making twenty in total." },
  { id:'ih021', mode:'duel', era:'1977–1991', difficulty:2,
    q:"India's first Maruti 800 car was delivered in which year?",
    options:["1981","1983","1985","1971"], answerIndex:1,
    source:"Maruti Suzuki corporate record",

    sourceUrl:"https://marutisuzuki.com",
    note:"Maruti Udyog was incorporated in 1981; the first Maruti 800 was delivered in December 1983." },
  { id:'ih022', mode:'duel', era:'Economic Milestones', difficulty:3,
    q:"India's Green Revolution began in the mid-1960s primarily with high-yielding varieties of which crop?",
    options:["Rice","Wheat","Cotton","Sugarcane"], answerIndex:1,
    source:"India Year Book / Ministry of Agriculture",

    sourceUrl:"https://publicationsdivision.nic.in",
    note:"High-yielding dwarf wheat varieties were introduced in 1965–66, anchoring the Green Revolution. Operation Flood (1970) followed in dairying." },
  { id:'ih023', mode:'duel', era:'Liberalisation Era (1991–2014)', difficulty:2,
    q:"In which year did the Right to Information Act come into force across India?",
    options:["2002","2005","2007","2010"], answerIndex:1,
    source:"PRS Legislative Research",

    sourceUrl:"https://prsindia.org",
    note:"The RTI Act came into force on 12 October 2005; it repealed the Freedom of Information Act, 2002." },
  { id:'ih024', mode:'duel', era:'Liberalisation Era (1991–2014)', difficulty:3,
    q:"Article 21A, guaranteeing free and compulsory education to children aged 6–14, was inserted by which amendment?",
    options:["42nd Amendment","61st Amendment","86th Amendment","93rd Amendment"], answerIndex:2,
    source:"Constitution of India (Constitution (86th Amendment) Act, 2002)",

    sourceUrl:"https://legislative.gov.in/constitution-of-india/",
    note:"The 86th Amendment (2002) inserted Article 21A; the RTE Act followed in 2009, effective 1 April 2010. The 61st Amendment (1988) lowered the voting age to 18." },
  { id:'ih025', mode:'duel', era:'Liberalisation Era (1991–2014)', difficulty:2,
    q:"India's Pokhran-II nuclear tests (Operation Shakti) were conducted in:",
    options:["May 1974","May 1998","May 1999","September 1996"], answerIndex:1,
    source:"PIB / DRDO",

    sourceUrl:"https://pib.gov.in",
    note:"Operation Shakti tests were conducted on 11 and 13 May 1998. Pokhran-I was 18 May 1974." },
  { id:'ih026', mode:'duel', era:'Contemporary Institutions (2014–today)', difficulty:2,
    q:"The Goods and Services Tax (GST) was rolled out across India on which date?",
    options:["1 April 2017","1 July 2017","8 September 2016","1 January 2018"], answerIndex:1,
    source:"GST Council / PRS Legislative Research",

    sourceUrl:"https://gstcouncil.gov.in",
    note:"GST rolled out nationwide on 1 July 2017 (as of 2017). 8 September 2016 was presidential assent to the Constitution (101st Amendment) Act." },
  { id:'ih027', mode:'duel', era:'Contemporary Institutions (2014–today)', difficulty:1,
    q:"The Chandrayaan-3 Vikram lander touched down near the lunar south polar region on:",
    options:["23 August 2023","14 July 2023","7 September 2019","22 October 2008"], answerIndex:0,
    source:"ISRO",

    sourceUrl:"https://www.isro.gov.in",
    note:"Vikram touched down on 23 August 2023, now National Space Day (as of 2023). 14 July 2023 was the launch; 7 September 2019 the Chandrayaan-2 landing attempt; 22 October 2008 the Chandrayaan-1 launch." },
  { id:'ih028', mode:'duel', era:'Contemporary Institutions (2014–today)', difficulty:2,
    q:"The Constitution (106th Amendment) Act, 2023 (Nari Shakti Vandan Adhiniyam) provides for:",
    options:["One-third reservation of seats for women in the Lok Sabha and State Legislative Assemblies, effective after the next census and delimitation","One-half reservation for women in the Rajya Sabha","Reservation for women in private-sector employment","Reservation for women in the Union Council of Ministers"], answerIndex:0,
    source:"Ministry of Law & Justice / PRS",

    sourceUrl:"https://legislative.gov.in/constitution-of-india/",
    note:"Assent was given 28 September 2023; the Act inserted Articles 330A and 332A. It is operative after the next census and delimitation." },
  { id:'ih029', mode:'duel', era:'Regional & State History', difficulty:2,
    q:"Telangana became India's 29th state on:",
    options:["1 November 2000","2 June 2014","30 May 1987","1 November 1956"], answerIndex:1,
    source:"Andhra Pradesh Reorganisation Act, 2014 / India Year Book",

    sourceUrl:"https://legislative.gov.in/constitution-of-india/",
    note:"Telangana was formed on 2 June 2014. The 2000 distractor marks the three states formed that year, each on its own date: Chhattisgarh on 1 November 2000, Uttarakhand on 9 November 2000, and Jharkhand on 15 November 2000; 1987 marks Goa; 1956 the States Reorganisation Act." },
  { id:'ih030', mode:'duel', era:'India in the World', difficulty:3,
    q:"The first summit of the Non-Aligned Movement was held in:",
    options:["Bandung, 1955","Belgrade, 1961","Cairo, 1964","Lusaka, 1970"], answerIndex:1,
    source:"Ministry of External Affairs",

    sourceUrl:"https://www.mea.gov.in",
    note:"Bandung 1955 was the Asian-African Conference, a precursor. Belgrade hosted the first NAM summit, 1–6 September 1961." },

  /* ---------------- WhatsApp Check (5) ---------------- */
  { id:'wc001', mode:'check', era:'WhatsApp Check', difficulty:1,
    q:"Viral forward: “UNESCO has declared Jana Gana Mana the world's best national anthem.”",
    options:["True","False"], answerIndex:1,
    source:"PIB Fact Check / UNESCO",

    sourceUrl:"https://factcheck.pib.gov.in",
    note:"False — a recycled viral forward; no such UNESCO designation exists. Debunked repeatedly by UNESCO and PIB Fact Check." },
  { id:'wc002', mode:'check', era:'WhatsApp Check', difficulty:1,
    q:"Viral forward: “Hindi is the national language of India.”",
    options:["True","False"], answerIndex:1,
    source:"Constitution of India, Article 343 / Official Languages Act, 1963",

    sourceUrl:"https://legislative.gov.in/constitution-of-india/",
    note:"False — the Constitution names no national language. Article 343 makes Hindi in Devanagari script an official language of the Union, alongside English (Official Languages Act, 1963)." },
  { id:'wc003', mode:'check', era:'WhatsApp Check', difficulty:2,
    q:"Viral forward: “Parliament consists of two Houses — so the President is not part of it.”",
    options:["True","False"], answerIndex:1,
    source:"Constitution of India, Article 79",

    sourceUrl:"https://legislative.gov.in/constitution-of-india/",
    note:"False — the statement is incomplete: Parliament includes the President plus the two Houses (Article 79 — the Council of States and the House of the People)." },
  { id:'wc004', mode:'check', era:'WhatsApp Check', difficulty:2,
    q:"Viral forward: “Dr. Ambedkar hand-wrote the Constitution of India.”",
    options:["True","False"], answerIndex:1,
    source:"Parliament Library / Constituent Assembly record",

    sourceUrl:"https://sansad.in",
    note:"False — he chaired the Drafting Committee. The calligraphy was by Prem Behari Narain Raizada, with illustrations by Nandalal Bose's Shantiniketan team." },
  { id:'wc005', mode:'check', era:'WhatsApp Check', difficulty:2,
    q:"Viral forward: “India currently has 29 states.”",
    options:["True","False"], answerIndex:1,
    source:"Jammu & Kashmir Reorganisation Act, 2019",

    sourceUrl:"https://legislative.gov.in/constitution-of-india/",
    note:"Stale — 28 states since the Jammu & Kashmir Reorganisation Act, 2019 (in force 31 October 2019). Telangana (2 June 2014) had made it 29 for five years. (28 states, as of September 2025.)" },

  /* ---------------- The Record Shows (3 sets) ---------------- */
  { id:'rs001', mode:'record', era:'The Record Shows', difficulty:3,
    q:"The Emergency of 1975–77. One side remembers: “It lasted two full years.” The other remembers: “It ended with the 1976 election.” What does the record show?",
    options:[
      "Proclaimed 25 June 1975 under Article 352; revoked 21 March 1977 — the general election followed in March 1977",
      "It ran for exactly two years, 1975 to 1977",
      "It was ended by the general election of 1976",
      "Both popular versions are mistaken"
    ], answerIndex:0,
    source:"Gazette of India (proclamation of 25 June 1975; revocation of 21 March 1977)",

    sourceUrl:"https://egazette.gov.in",
    note:"The proclamation (Article 352) is dated 25 June 1975; revocation 21 March 1977; the election followed in March 1977. Both popular framings misstate the dates." },
  { id:'rs002', mode:'record', era:'The Record Shows', difficulty:4,
    q:"The Objectives Resolution. One side remembers: “The Assembly adopted it collectively, without a mover.” The other remembers: “The Drafting Committee wrote it.” What does the record show?",
    options:[
      "Moved by Jawaharlal Nehru on 13 December 1946; adopted 22 January 1947 — before the Drafting Committee existed (29 August 1947)",
      "It was drafted by the Drafting Committee in 1947",
      "It was adopted collectively with no named mover",
      "Both popular versions are mistaken"
    ], answerIndex:0,
    source:"Constituent Assembly Debates",

    sourceUrl:"https://www.constitutionofindia.net",
    note:"Nehru moved the Objectives Resolution on 13 December 1946; it was adopted 22 January 1947. The Drafting Committee was constituted only on 29 August 1947." },
  { id:'rs003', mode:'record', era:'The Record Shows', difficulty:3,
    q:"Why 26 January? One side remembers: “That is the day the Constitution was adopted.” The other remembers: “That is Independence Day.” What does the record show?",
    options:[
      "The Constitution was adopted 26 November 1949 and commenced 26 January 1950 — the date chosen to honour Purna Swaraj Day (26 January 1930)",
      "The Constitution was adopted on 26 January 1950",
      "26 January marks the transfer of power in 1947",
      "Both popular versions are mistaken"
    ], answerIndex:0,
    source:"Constituent Assembly Debates / Ministry of Law & Justice",

    sourceUrl:"https://www.constitutionofindia.net",
    note:"Adoption: 26 November 1949. Commencement: 26 January 1950, honouring Purna Swaraj Day (26 January 1930, Lahore session resolution of December 1929)." }
];
