// Ledger — News-awareness question bank: Indian government schemes & finance/investment
// 47 items. Every fact checked against official records (PIB, RBI, SEBI, NPCI, scheme portals, Union Budget documents, AMFI, IRDAI).
// Mutable facts are date-stamped in the note field. Compiled 2024-2026 source window.
window.LEDGER_FINANCE = [

// ============ SECTION 1: GOVERNMENT SCHEMES (17) ============
{ id:'gs001', era:'Government Schemes', difficulty:2,
  q:"In which year was the Pradhan Mantri Jan Dhan Yojana (PMJDY), the national mission for financial inclusion, launched?",
  options:["2013","2014","2015","2017"], answerIndex:1,
  source:"PIB — PM Jan Dhan Yojana Completes 12 Years (release, 27 Aug 2026)",
  sourceUrl:"https://www.pib.gov.in/PressReleasePage.aspx?PRID=2303643",
  note:"PMJDY was launched on 28 August 2014, offering zero-balance accounts with a RuPay debit card. PIB records 59.09 crore accounts as of August 2026." },

{ id:'gs002', era:'Government Schemes', difficulty:2,
  q:"How many days of guaranteed wage employment per rural household per financial year does the MGNREGA Act provide as a legal entitlement?",
  options:["50 days","75 days","100 days","150 days"], answerIndex:2,
  source:"Ministry of Rural Development — MGNREGA portal (nrega.nic.in)",
  sourceUrl:"https://nrega.nic.in/",
  note:"Parliament passed NREGA in 2005; it came into force on 2 February 2006. It was renamed Mahatma Gandhi NREGA on 2 October 2009." },

{ id:'gs003', era:'Government Schemes', difficulty:2,
  q:"What annual hospitalisation cover does Ayushman Bharat – PM Jan Arogya Yojana (PM-JAY) provide per eligible family?",
  options:["₹5 lakh","₹2 lakh","₹3 lakh","₹10 lakh"], answerIndex:0,
  source:"National Health Authority — PM-JAY portal",
  sourceUrl:"https://pmjay.gov.in/",
  note:"PM-JAY was launched on 23 September 2018 at Ranchi. It provides ₹5 lakh per family per year for secondary and tertiary hospitalisation, administered by the National Health Authority." },

{ id:'gs004', era:'Government Schemes', difficulty:1,
  q:"What annual income support does PM-KISAN provide to eligible landholding farmer families?",
  options:["₹3,000","₹4,000","₹5,000","₹6,000"], answerIndex:3,
  source:"PM-KISAN portal, Ministry of Agriculture & Farmers Welfare",
  sourceUrl:"https://pmkisan.gov.in/",
  note:"PM-KISAN was launched on 24 February 2019 at Gorakhpur. The ₹6,000 is paid in three instalments of ₹2,000 via Direct Benefit Transfer (DBT, the government payment mechanism launched on 1 January 2013)." },

{ id:'gs005', era:'Government Schemes', difficulty:3,
  q:"The PM Ujjwala Yojana, providing deposit-free LPG connections to poor households, was launched on 1 May 2016 from which place?",
  options:["Lucknow","Varanasi","Ballia (Uttar Pradesh)","Gorakhpur"], answerIndex:2,
  source:"PIB — PM Ujjwala Yojana factsheet, Ministry of Petroleum & Natural Gas",
  sourceUrl:"https://www.pib.gov.in/FactsheetDetails.aspx?Id=148555",
  note:"PMUY was launched at Ballia, UP, on 1 May 2016, with financial assistance of ₹1,600 per connection. Ujjwala 2.0 followed on 10 August 2021 from Mahoba, UP." },

{ id:'gs006', era:'Government Schemes', difficulty:2,
  q:"In which year was the Pradhan Mantri Awas Yojana (Urban) launched with the 'Housing for All' goal?",
  options:["2015","2014","2016","2019"], answerIndex:0,
  source:"Ministry of Housing & Urban Affairs — PMAY-Urban portal",
  sourceUrl:"https://pmay-urban.gov.in/",
  note:"PMAY-U was launched on 25 June 2015, originally targeting Housing for All by 2022. The rural counterpart, PMAY-Gramin, restructured the earlier Indira Awaas Yojana from 2016." },

{ id:'gs007', era:'Government Schemes', difficulty:3,
  q:"The Startup India initiative (launched 16 January 2016) is anchored by which government body for recognition of startups?",
  options:["NITI Aayog","SIDBI","SEBI","Department for Promotion of Industry and Internal Trade (DPIIT)"], answerIndex:3,
  source:"Startup India portal, DPIIT, Ministry of Commerce & Industry",
  sourceUrl:"https://www.startupindia.gov.in/",
  note:"Startup India was unveiled on 16 January 2016; DPIIT handles startup recognition and the action plan. The related Stand-Up India loan scheme followed on 5 April 2016." },

{ id:'gs008', era:'Government Schemes', difficulty:3,
  q:"Under the Pradhan Mantri MUDRA Yojana (launched 8 April 2015), the 'Shishu' category covers collateral-free loans of up to what amount?",
  options:["₹25,000","₹50,000","₹1 lakh","₹5 lakh"], answerIndex:1,
  source:"MUDRA Ltd. — PMMY portal",
  sourceUrl:"https://www.mudra.org.in/",
  note:"PMMY's original tiers were Shishu (up to ₹50,000), Kishore (up to ₹5 lakh) and Tarun (up to ₹10 lakh). Budget 2024-25 announced a 'Tarun Plus' tier up to ₹20 lakh, notified in October 2024 for borrowers who repaid an earlier Tarun loan." },

{ id:'gs009', era:'Government Schemes', difficulty:4,
  q:"Under Stand-Up India (launched 5 April 2016), scheduled commercial banks facilitate loans in what range for greenfield enterprises of SC/ST and women entrepreneurs?",
  options:["₹1 lakh to ₹10 lakh","₹5 lakh to ₹25 lakh","₹50,000 to ₹5 lakh","₹10 lakh to ₹1 crore"], answerIndex:3,
  source:"Stand-Up India portal (standupmitra.in), SIDBI / Department of Financial Services",
  sourceUrl:"https://www.standupmitra.in/",
  note:"The scheme covers composite loans of ₹10 lakh–₹1 crore for greenfield ventures, with each bank branch asked to serve at least one SC/ST and one woman borrower. It is monitored through the StandUp Mitra portal." },

{ id:'gs010', era:'Government Schemes', difficulty:2,
  q:"The Sukanya Samriddhi Yojana, a small-savings scheme for the girl child, was launched on 22 January 2015 as part of which campaign?",
  options:["Digital India","Beti Bachao, Beti Padhao","Skill India","Swachh Bharat Mission"], answerIndex:1,
  source:"PIB — Sukanya Samriddhi Yojana backgrounder (21 Jan 2026)",
  sourceUrl:"https://www.pib.gov.in/PressReleasePage.aspx?PRID=2216748",
  note:"Launched at Panipat, Haryana, on 22 January 2015 under Beti Bachao, Beti Padhao. Accounts are opened for girls below age 10 and mature 21 years from opening; deposits qualify under Section 80C." },

{ id:'gs011', era:'Government Schemes', difficulty:3,
  q:"What is the guaranteed monthly pension range a subscriber can choose under the Atal Pension Yojana (payable from age 60)?",
  options:["₹1,000 to ₹5,000","₹500 to ₹2,000","₹3,000 to ₹10,000","₹2,000 to ₹8,000"], answerIndex:0,
  source:"PIB — Atal Pension Yojana milestone release / PFRDA",
  sourceUrl:"https://www.pib.gov.in/PressReleasePage.aspx?PRID=2254487",
  note:"APY was launched on 9 May 2015 and is administered by PFRDA under the NPS architecture. Entry age is 18–40; since 1 October 2022, income-tax payers are not eligible to enrol afresh." },

{ id:'gs012', era:'Government Schemes', difficulty:4,
  q:"The Production Linked Incentive (PLI) scheme pays manufacturers an incentive calculated on what basis?",
  options:["Total exports in a year","A fixed percentage of the total investment","Incremental sales of manufactured goods over a defined base year","Number of new employees hired"], answerIndex:2,
  source:"DPIIT, Ministry of Commerce & Industry — PLI schemes",
  sourceUrl:"https://dpiit.gov.in/",
  note:"PLI was first notified in March–April 2020 for mobile manufacturing and specified electronic components; in November 2020 the Union Cabinet extended it to 10 more sectors, taking coverage to 14 sectors with a total outlay of about ₹1.97 lakh crore." },

{ id:'gs013', era:'Government Schemes', difficulty:2,
  q:"Which is the nodal ministry for the Jal Jeevan Mission, the rural tap-water programme announced on 15 August 2019?",
  options:["Ministry of Jal Shakti","Ministry of Rural Development","Ministry of Housing and Urban Affairs","Ministry of Health and Family Welfare"], answerIndex:0,
  source:"Jal Jeevan Mission portal, Department of Drinking Water & Sanitation",
  sourceUrl:"https://jaljeevanmission.gov.in/",
  note:"JJM targets a Functional Household Tap Connection (FHTC) supplying at least 55 litres per person per day to every rural household. The original 2024 target was extended to 2028 in Budget 2025-26." },

{ id:'gs014', era:'Government Schemes', difficulty:3,
  q:"What is the first-cycle collateral-free working-capital loan offered to street vendors under PM SVANidhi (launched 1 June 2020)?",
  options:["₹5,000","₹7,500","₹10,000","₹25,000"], answerIndex:2,
  source:"PM SVANidhi portal, Ministry of Housing & Urban Affairs",
  sourceUrl:"https://pmsvanidhi.mohua.gov.in/",
  note:"PM SVANidhi offers an initial ₹10,000 working-capital loan with a 7% interest subsidy, and subsequent cycles of ₹20,000 and ₹50,000. It also pays cashback for digital transactions." },

{ id:'gs015', era:'Government Schemes', difficulty:4,
  q:"The Antyodaya Anna Yojana, which supplies highly subsidised foodgrains to the 'poorest of the poor' families through the PDS, was launched in which year?",
  options:["1997","2000","2005","2013"], answerIndex:1,
  source:"Department of Food & Public Distribution, Ministry of Consumer Affairs",
  sourceUrl:"https://dfpd.gov.in/",
  note:"AAY was launched on 25 December 2000, initially covering one crore poorest families at 35 kg of grain a month at ₹3/kg rice and ₹2/kg wheat. The national school meal programme began earlier, on 15 August 1995, as the NP-NSPE (now PM POSHAN)." },

{ id:'gs016', era:'Government Schemes', difficulty:2,
  q:"The Pradhan Mantri Gram Sadak Yojana (PMGSY), providing all-weather road connectivity to eligible unconnected rural habitations, was launched on 25 December 2000 with which nodal ministry?",
  options:["Ministry of Road Transport and Highways","Ministry of Rural Development","Ministry of Panchayati Raj","Ministry of Housing and Urban Affairs"], answerIndex:1,
  source:"PIB — PMGSY completes 25 years (release, 25 December 2025); Ministry of Rural Development",
  sourceUrl:"https://www.pib.gov.in/PressReleasePage.aspx?PRID=2208381",
  note:"PMGSY began on 25 December 2000 as a fully centrally sponsored programme (funding later shared 60:40 with states). It is implemented by the Ministry of Rural Development; a fourth phase (2024-29) targets a further 25,000 habitations." },

{ id:'gs017', era:'Government Schemes', difficulty:2,
  q:"The Sarva Shiksha Abhiyan, the flagship programme for universalisation of elementary education for children aged 6-14, was launched in 2001 under which ministry?",
  options:["Ministry of Women and Child Development","Ministry of Social Justice and Empowerment","Ministry of Labour and Employment","Ministry of Human Resource Development (now Ministry of Education)"], answerIndex:3,
  source:"Ministry of Education — Department of School Education & Literacy, SSA programme records",
  sourceUrl:"https://dsel.education.gov.in/",
  note:"SSA ran as a centrally sponsored scheme from 2001, aligned with the 86th Constitutional Amendment (2002) inserting Article 21A. In 2018 it was subsumed into Samagra Shiksha, which covers schooling from pre-primary to Class 12." },

// ============ SECTION 2: MONEY & MARKETS (12) ============
{ id:'mm016', era:'Money & Markets', difficulty:1,
  q:"In which year was the Reserve Bank of India established?",
  options:["1947","1950","1955","1935"], answerIndex:3,
  source:"RBI — History / About Us",
  sourceUrl:"https://www.rbi.org.in/",
  note:"RBI was set up under the Reserve Bank of India Act, 1934 and began operations on 1 April 1935. It was nationalised on 1 January 1949." },

{ id:'mm017', era:'Money & Markets', difficulty:2,
  q:"The 'repo rate' announced by the RBI is best described as:",
  options:["The rate at which RBI lends short-term funds to banks against government securities","The interest banks pay on savings accounts","The rate at which banks park surplus funds with RBI","The yield on 10-year government bonds"], answerIndex:0,
  source:"RBI — Monetary Policy / Policy Rates",
  sourceUrl:"https://www.rbi.org.in/",
  note:"The repo rate is set by the Monetary Policy Committee. The reverse repo is the rate at which banks park funds with RBI, and the Cash Reserve Ratio (CRR) is the share of deposits banks must hold as cash with RBI." },

{ id:'mm018', era:'Money & Markets', difficulty:3,
  q:"How many members does the RBI's Monetary Policy Committee (MPC) have?",
  options:["4","6","8","10"], answerIndex:1,
  source:"RBI — Monetary Policy Committee framework",
  sourceUrl:"https://www.rbi.org.in/",
  note:"The MPC was constituted in 2016 under the amended RBI Act, 1934, and held its first meeting in October 2016. It has three RBI members (including the Governor as chair) and three external members nominated by the Government." },

{ id:'mm019', era:'Money & Markets', difficulty:3,
  q:"In India, the Consumer Price Index (CPI) used as the RBI's inflation target benchmark is compiled and released by which body?",
  options:["Office of the Economic Adviser, DPIIT","Reserve Bank of India","National Statistical Office (MoSPI)","Finance Commission"], answerIndex:2,
  source:"Ministry of Statistics & Programme Implementation — CPI releases",
  sourceUrl:"https://www.mospi.gov.in/",
  note:"CPI (retail inflation) is released monthly by the NSO under MoSPI; the Wholesale Price Index (WPI) is released by the Office of the Economic Adviser, DPIIT. The RBI's target since 2016 is CPI of 4% within a 2–6% band." },

{ id:'mm020', era:'Money & Markets', difficulty:2,
  q:"The BSE Sensex, India's benchmark stock index, tracks how many companies?",
  options:["20","30","50","100"], answerIndex:1,
  source:"BSE Ltd. — Sensex index information",
  sourceUrl:"https://www.bseindia.com/",
  note:"The Sensex was launched in 1986 with base year 1978-79 = 100. It first crossed 1,000 points in July 1990 and 10,000 points on 7 February 2006." },

{ id:'mm021', era:'Money & Markets', difficulty:2,
  q:"Which is Asia's oldest stock exchange, tracing its origins to 1875?",
  options:["National Stock Exchange (NSE)","Calcutta Stock Exchange","Madras Stock Exchange","Bombay Stock Exchange (BSE)"], answerIndex:3,
  source:"BSE Ltd. — Exchange history",
  sourceUrl:"https://www.bseindia.com/",
  note:"BSE was founded in 1875 as the Native Share & Stock Brokers' Association. The NSE was incorporated in 1992 and commenced trading in 1994." },

{ id:'mm022', era:'Money & Markets', difficulty:3,
  q:"In which year did SEBI acquire statutory powers through an Act of Parliament?",
  options:["1988","1990","1992","2003"], answerIndex:2,
  source:"SEBI — About / SEBI Act, 1992",
  sourceUrl:"https://www.sebi.gov.in/",
  note:"SEBI was first set up in 1988 as a non-statutory body. It became a statutory regulator with the Securities and Exchange Board of India Act, 1992." },

{ id:'mm023', era:'Money & Markets', difficulty:2,
  q:"The Unified Payments Interface (UPI), launched in 2016, was developed by which organisation?",
  options:["National Payments Corporation of India (NPCI)","Reserve Bank of India","SEBI","Ministry of Electronics and IT"], answerIndex:0,
  source:"NPCI — UPI product page",
  sourceUrl:"https://www.npci.org.in/",
  note:"UPI was launched on 11 April 2016 by then RBI Governor Raghuram Rajan as an NPCI pilot with 21 banks; public apps rolled out from August 2016. It runs 24x7 and settles instantly." },

{ id:'mm024', era:'Money & Markets', difficulty:4,
  q:"Which statement correctly distinguishes RTGS from NEFT for bank transfers in India?",
  options:["RTGS settles in half-hourly batches while NEFT is real time","NEFT requires a minimum transfer of ₹2 lakh","RTGS settles each transaction individually in real time and is meant for high-value transfers (minimum ₹2 lakh)","Both systems have a maximum limit of ₹2 lakh per transaction"], answerIndex:2,
  source:"RBI — FAQ on NEFT and RTGS",
  sourceUrl:"https://www.rbi.org.in/",
  note:"Per RBI, RTGS is real-time gross settlement with a ₹2 lakh minimum; NEFT settles in half-hourly batches, 24x7 since December 2019, with no RBI-mandated minimum or maximum. NPCI's IMPS (launched November 2010) offers instant transfers round the clock." },

{ id:'mm025', era:'Money & Markets', difficulty:3,
  q:"In which year did the RBI begin its first Digital Rupee (central bank digital currency) pilots?",
  options:["2020","2022","2024","2019"], answerIndex:1,
  source:"RBI — Digital Rupee (e₹) pilot press releases",
  sourceUrl:"https://www.rbi.org.in/",
  note:"RBI launched the wholesale pilot (e₹-W) for settlement of government securities on 1 November 2022 and the retail pilot (e₹-R) on 1 December 2022. The pilots were ongoing as of 2024–25." },

{ id:'mm026', era:'Money & Markets', difficulty:4,
  q:"Sovereign Gold Bonds, first issued in November 2015, are issued by which institution on behalf of the Government of India?",
  options:["SEBI","Ministry of Mines","India Post","Reserve Bank of India"], answerIndex:3,
  source:"RBI — Sovereign Gold Bond Scheme 2015",
  sourceUrl:"https://www.rbi.org.in/",
  note:"SGBs are denominated in grams of gold, pay 2.5% annual interest on the issue price, and have an 8-year tenor with exit options after the fifth year. No fresh tranches were issued after February 2024 (as documented through 2024)." },

{ id:'mm027', era:'Money & Markets', difficulty:1,
  q:"On which date did the Government of India announce the withdrawal of legal-tender status of ₹500 and ₹1,000 banknotes (demonetisation)?",
  options:["8 November 2016","1 July 2017","15 August 2014","26 January 2016"], answerIndex:0,
  source:"RBI — Withdrawal of Specified Bank Notes (8 Nov 2016 notifications)",
  sourceUrl:"https://www.rbi.org.in/",
  note:"The announcement on 8 November 2016 made ₹500 and ₹1,000 notes (Specified Bank Notes) cease to be legal tender from midnight; new ₹500 and ₹2,000 notes were introduced. For currency context, the ₹ symbol, designed by D. Udaya Kumar, had been adopted on 15 July 2010." },

// ============ SECTION 3: INVESTMENT AWARENESS (10) ============
{ id:'ia028', era:'Investment Awareness', difficulty:1,
  q:"A Systematic Investment Plan (SIP) in a mutual fund means:",
  options:["A one-time lump-sum investment","A government small-savings scheme","Investing a fixed amount at regular intervals into a chosen fund","A type of bank fixed deposit"], answerIndex:2,
  source:"AMFI — Investor education (Mutual Funds Sahi Hai)",
  sourceUrl:"https://www.amfiindia.com/",
  note:"AMFI describes an SIP as a facility to invest fixed sums at regular intervals in a mutual fund scheme. SIP returns are market-linked and not guaranteed." },

{ id:'ia029', era:'Investment Awareness', difficulty:3,
  q:"Among PPF, EPF, SCSS and NPS, which product is market-linked, with returns depending on the performance of the chosen pension funds?",
  options:["Public Provident Fund (PPF)","Employees' Provident Fund (EPF)","Senior Citizens Savings Scheme (SCSS)","National Pension System (NPS)"], answerIndex:3,
  source:"PFRDA — National Pension System",
  sourceUrl:"https://www.pfrda.org.in/",
  note:"PPF (since 1968), EPF (under the 1952 Act) and SCSS pay government-notified or declared rates. NPS, regulated by PFRDA and open to all citizens since May 2009, invests contributions in market instruments through pension fund managers." },

{ id:'ia030', era:'Investment Awareness', difficulty:2,
  q:"What is the basic difference between a term insurance plan and an endowment plan?",
  options:["Term insurance pays out only on death during the policy term and has no maturity value; endowment combines a death cover with a savings payout at maturity","Term insurance always pays a maturity bonus","Endowment plans are always cheaper than term plans for the same cover","There is no practical difference between the two"], answerIndex:0,
  source:"IRDAI — Life insurance consumer education",
  sourceUrl:"https://irdai.gov.in/",
  note:"Term plans offer pure risk cover, so premiums buy a larger sum assured. Endowment plans mix insurance with savings and typically cost more for the same cover." },

{ id:'ia031', era:'Investment Awareness', difficulty:1,
  q:"In personal finance, 'diversification' refers to:",
  options:["Putting all savings into the single best-performing asset","Spreading investments across different assets so that one poor performer does not wipe out the portfolio","Investing only in gold and property","Switching investments daily to catch every rally"], answerIndex:1,
  source:"SEBI — Investor education",
  sourceUrl:"https://investor.sebi.gov.in/",
  note:"Diversification is a standard risk-management principle in SEBI and AMFI investor-education material: different assets (equity, debt, gold, deposits) rarely fall together." },

{ id:'ia032', era:'Investment Awareness', difficulty:3,
  q:"In a mutual fund, the Total Expense Ratio (TER) is:",
  options:["The annual charge the fund house levies, expressed as a percentage of the fund's assets","A tax paid to the government on redemptions","A one-time entry load on every purchase","The brokerage charged on the investor's demat account"], answerIndex:0,
  source:"AMFI — Mutual fund expenses; SEBI TER regulations",
  sourceUrl:"https://www.amfiindia.com/",
  note:"SEBI caps TER on a sliding scale linked to assets under management, and direct plans carry lower TERs than regular plans because no distributor commission is embedded." },

{ id:'ia033', era:'Investment Awareness', difficulty:2,
  q:"Under DICGC deposit insurance, what is the maximum amount insured per depositor per bank (principal plus interest)?",
  options:["₹1 lakh","₹2 lakh","₹5 lakh","₹10 lakh"], answerIndex:2,
  source:"DICGC (RBI subsidiary) — Deposit insurance",
  sourceUrl:"https://www.dicgc.org.in/",
  note:"The cover was raised from ₹1 lakh to ₹5 lakh with effect from 4 February 2020. DICGC, a wholly owned RBI subsidiary, insures deposits in commercial and cooperative banks; balances across branches of the same bank are aggregated." },

{ id:'ia034', era:'Investment Awareness', difficulty:3,
  q:"The Senior Citizens Savings Scheme (SCSS), a small-savings deposit paying quarterly interest, is generally open to individuals aged:",
  options:["50 years and above","55 years and above","58 years and above","60 years and above"], answerIndex:3,
  source:"India Post / Department of Economic Affairs — SCSS rules",
  sourceUrl:"https://www.indiapost.gov.in/",
  note:"SCSS was introduced in 2004. Entry is at age 60 (with specified exceptions for retirees aged 55–60 and certain retired defence personnel aged 50+); the account runs 5 years and can be extended by 3." },

{ id:'ia035', era:'Investment Awareness', difficulty:4,
  q:"The SARFAESI Act, 2002 empowers banks and notified financial institutions to:",
  options:["Print currency notes","Recover bad loans by enforcing security interests (seizing and selling secured assets) without needing to file a court case first","Fix the repo rate on behalf of RBI","Issue new banking licences"], answerIndex:1,
  source:"India Code — Securitisation and Reconstruction of Financial Assets and Enforcement of Security Interest Act, 2002",
  sourceUrl:"https://www.indiacode.nic.in/",
  note:"SARFAESI applies to secured loans classified as NPAs and lets lenders enforce the security interest, subject to notice and borrower appeal rights before the Debt Recovery Tribunal." },

{ id:'ia036', era:'Investment Awareness', difficulty:4,
  q:"As revised by the Union Budget 2024-25, long-term capital gains on listed equity shares (held for more than 12 months) are taxed at:",
  options:["10% on gains above ₹1 lakh a year","12.5% on gains above ₹1.25 lakh a year","15% flat on all gains","20% with indexation"], answerIndex:1,
  source:"Union Budget 2024-25 — Finance Minister's speech / Finance (No. 2) Bill",
  sourceUrl:"https://www.indiabudget.gov.in/",
  note:"Budget 2024-25 (presented 23 July 2024) set LTCG on listed equity at 12.5% with an annual exemption of ₹1.25 lakh, replacing the earlier 10% rate over ₹1 lakh. Rates can change in future budgets; this item is date-stamped to FY 2024-25." },

{ id:'ia037', era:'Investment Awareness', difficulty:2,
  q:"In Indian taxation, 'TDS' stands for:",
  options:["Tax Deposited at Source","Total Deduction System","Tax Deferred Scheme","Tax Deducted at Source"], answerIndex:3,
  source:"Income Tax Department — TDS provisions",
  sourceUrl:"https://incometaxindia.gov.in/",
  note:"Under TDS, the payer (e.g., a bank paying interest or an employer paying salary) deducts tax before making the payment and deposits it with the government. Thresholds and rates are prescribed in the Income-tax Act and revised through successive budgets." },

// ============ SECTION 4: BUDGETS & DOCUMENTS (8) ============
{ id:'bd038', era:'Budgets & Documents', difficulty:2,
  q:"The Union Budget is presented in Parliament as the 'Annual Financial Statement' under which Article of the Constitution?",
  options:["Article 112","Article 280","Article 360","Article 74"], answerIndex:0,
  source:"Union Budget portal / Constitution of India",
  sourceUrl:"https://www.indiabudget.gov.in/",
  note:"Article 112 requires the President to lay the Annual Financial Statement before both Houses each year. The Budget documents are prepared by the Budget Division of the Department of Economic Affairs, Ministry of Finance." },

{ id:'bd039', era:'Budgets & Documents', difficulty:2,
  q:"The customary 'halwa ceremony' held at North Block before the Union Budget traditionally marks:",
  options:["The close of the financial year","The start of the 'lock-in' period for officials involved in preparing the Budget documents","The signing of the Finance Bill","The tabling of the Economic Survey"], answerIndex:1,
  source:"Ministry of Finance / PIB — Budget traditions",
  sourceUrl:"https://www.indiabudget.gov.in/",
  note:"After the halwa ceremony, officials handling Budget printing and preparation stay in North Block to preserve secrecy until the Budget is presented. Since the paperless Budget of 2021, the lock-in and printing exercise have shrunk considerably." },

{ id:'bd040', era:'Budgets & Documents', difficulty:2,
  q:"The Economic Survey, tabled in Parliament shortly before the Union Budget, is prepared by:",
  options:["The Reserve Bank of India","NITI Aayog","The Department of Economic Affairs, Ministry of Finance","The Finance Commission"], answerIndex:2,
  source:"Union Budget portal — Economic Survey",
  sourceUrl:"https://www.indiabudget.gov.in/economicsurvey/",
  note:"The Economic Survey reviews the year's economic developments and is prepared under the guidance of the Chief Economic Adviser in the Department of Economic Affairs. Since 2017's schedule change, it is typically tabled on 31 January, a day before the Budget." },

{ id:'bd041', era:'Budgets & Documents', difficulty:3,
  q:"The Finance Commission, which recommends how central taxes are shared between the Union and the States, is provided for under:",
  options:["Article 112","Article 279A","Article 324","Article 280"], answerIndex:3,
  source:"Finance Commission of India — Constitutional mandate",
  sourceUrl:"https://fincomindia.nic.in/",
  note:"Article 280 requires the President to constitute a Finance Commission roughly every five years. The 15th Finance Commission (chaired by N.K. Singh) set the States' share at 41% of the divisible pool for 2021-26." },

{ id:'bd042', era:'Budgets & Documents', difficulty:3,
  q:"The GST Council, the joint Union-State body that decides GST rates, was created by the Constitution (101st Amendment) Act, 2016 under:",
  options:["Article 280","Article 263","Article 312","Article 279A"], answerIndex:3,
  source:"GST Council — Constitutional provisions",
  sourceUrl:"https://gstcouncil.gov.in/",
  note:"Article 279A created the GST Council, chaired by the Union Finance Minister with state finance ministers as members. GST rates are structured in four main slabs — 5%, 12%, 18% and 28% — besides exempted (0%) items and cess on specified goods." },

{ id:'bd043', era:'Budgets & Documents', difficulty:3,
  q:"In which year was the Union Budget first presented in a fully paperless format, using a digital tablet?",
  options:["2019","2020","2021","2023"], answerIndex:2,
  source:"Union Budget 2021-22 records, Ministry of Finance",
  sourceUrl:"https://www.indiabudget.gov.in/",
  note:"On 1 February 2021, Finance Minister Nirmala Sitharaman presented the first paperless Budget on a tablet carried in a bahi-khata-style cover, during the COVID-19 pandemic. A Union Budget mobile app was also launched that year for document access." },

{ id:'bd044', era:'Budgets & Documents', difficulty:4,
  q:"A 'vote-on-account', typically sought in general-election years, primarily does what?",
  options:["Introduces new income-tax slabs for the full year","Obtains Parliament's approval for essential government expenditure for a limited period until a full budget is passed","Is another name for the Finance Bill","Is presented by the RBI Governor"], answerIndex:1,
  source:"Union Budget portal — Budget process glossary",
  sourceUrl:"https://www.indiabudget.gov.in/",
  note:"A vote-on-account covers expenditure for part of the year (usually two months) so government functions continue. An interim budget, by contrast, includes the full year's accounts; the incoming government later presents the full budget." },

{ id:'bd045', era:'Budgets & Documents', difficulty:4,
  q:"The 16th Finance Commission, constituted on 31 December 2023 with Dr Arvind Panagariya as Chairman, makes recommendations for which award period?",
  options:["2021-22 to 2025-26","2024-25 to 2028-29","2025-26 to 2029-30","2026-27 to 2030-31"], answerIndex:3,
  source:"Finance Commission of India — 16th FC notification",
  sourceUrl:"https://fincomindia.nic.in/",
  note:"The 16th FC covers 1 April 2026 to 31 March 2031, succeeding the 15th FC's 2021-26 award. (As of the 2024 reference point, the Commission was constituted and consulting; its report was due by 31 October 2025.)" }
];
